calsoft_hyd_bfr – SWAT+
calsoft_hyd_bfr Subroutine
39 statements
Source File
subroutine calsoft_hyd_bfr()
Uses
channel_module
plant_module
ru_module
sd_channel_module
reservoir_module
basin_module
conditional_module
maximum_data_module
time_module
calibration_data_module
hru_lte_module
soil_module
aquifer_module
organic_mineral_mass_module
hydrograph_module
Arguments
None
Calls
Call graph
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_latq, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_pet, calsoft_hyd_bfr_surq