gwflow_read – SWAT+
gwflow_read Subroutine
2077 statements
Source File
subroutine gwflow_read()
Uses
input_file_module
constituent_mass_module
hydrograph_module
gwflow_module
sd_channel_module
maximum_data_module
reservoir_data_module
cs_data_module
hru_module
Arguments
None
Local Variables
Type Visibility Attributes Name Initial
logical, private :: i_exist
logical, private :: i_exist2
integer, private :: date_time
integer, private :: i
integer, private :: j
integer, private :: k
integer, private :: m
integer, private :: n
integer, private :: s
integer, private :: count
integer, private :: cell_num
integer, private :: sol_index
integer, private :: channel
integer, private :: chan_cell
integer, private :: ob_num
integer, private :: active_cell
real, private :: cell_size
real, private :: x_coord
real, private :: y_coord
integer, private :: num_conn
real, private :: sum
real, private :: dist_x
real, private :: dist_y
real, private :: min_dist
real, private :: distance
real, private :: gw_cell_volume
integer, private :: in_gw
integer, private :: in_hru_cell
integer, private :: in_cell_hru
integer, private :: in_huc_cell
integer, private :: in_res_cell
integer, private :: in_canal_cell
integer, private :: in_gw_minl
integer, private :: K_zone
integer, private :: Sy_zone
integer, private :: nzones_aquK
integer, private :: nzones_aquSy
integer, private :: nzones_strK
integer, private :: nzones_strbed
integer, private :: pumpex_cell
integer, private :: res_cell
integer, private :: res_id
real, private :: res_stage
integer, private :: canal_out
integer, private :: day_beg
integer, private :: day_end
integer, private :: canal
real, private :: thick
real, private :: depth
real, private :: width
real, private :: length
real, private :: stage
integer, private :: num_unique
integer, private :: cell
integer, private :: hru_count
integer, private :: hru_cell
integer, private :: nhru_connected
integer, private :: num_hru
real, private :: hru_area
integer, private :: hru_id
integer, private :: lsu
integer, private :: nlsu
integer, private :: nlsu_connected
integer, private :: lsu_id
integer, private :: cell_count
real, private :: poly_area
real, private :: cell_area
real, private :: lsu_area
integer, private :: in_usgs_head
integer, private :: num_usgs_wells
integer, private :: in_str_obs
real, private :: head_vals
real, private :: usgs_lat
real, private :: usgs_long
real, private :: usgs_site_id
integer, private :: huc12_connect
real, private :: huc12_id
real, private :: huc12_dum
integer, private :: dum
integer, private :: dum1
integer, private :: dum2
integer, private :: dum3
integer, private :: dum7
integer, private :: dum8
real, private :: dum4
real, private :: dum5
real, private :: dum6
real, private :: single_value
Outside Variables and Types Used
type(input_sim) (1 attribute from input_file_module)
Attribute Name Description
in_sim
basin
type(input_basin) (1 attribute from input_file_module)
Attribute Name Description
in_basin
climate
type(input_cli) (1 attribute from input_file_module)
Attribute Name Description
in_cli
connect
type(input_con) (1 attribute from input_file_module)
Attribute Name Description
in_con
channel
type(input_cha) (1 attribute from input_file_module)
Attribute Name Description
in_cha
reservoir
character(len=16) (5 attributes from constituent_mass_module)
Attribute Name Description
pest_init_name
path_init_name
hmet_init_name
salt_init_name
cs_init_name
rtb cs
integer (15 attributes from hydrograph_module)
Attribute Name Description
mhyd
none |max number of hydrographs
Read more…
mcmd
|
inum2
none |inflow hydrograph storage location number
Read more…
jrch
none |reach number
Read more…
jrchq
|
ncell
!number of gwflow cells
num_active
!number of active cells
gwflag_day
!flag for writing daily mass balance file
gwflag_yr
!flag for writing yearly mass balance file
maxint
number of intervals in hydrograph for degradation
num_geol_shale
isep
|
ilu
|
ulu
|
iwgen
|
real (7 attributes from gwflow_module)
Attribute Name Description
gw_time_step
days !flow solution time step
Read more…
wtemp
stream water temperature C
peakrate
sed_reduc_t
no3_reduc_kg
rct
reaction parameters
rct_shale
reaction parameters for shale
type(data_files_max_elements) (1 attribute from maximum_data_module)
Attribute Name Description
db_mx
type(reservoir_data_char_input) (2 attributes from reservoir_data_module)
Attribute Name Description
res_dat_c
wet_dat_c
type(reservoir_data_char_input_cs) (2 attributes from reservoir_data_module)
Attribute Name Description
res_dat_c_cs
wet_dat_c_cs
type(reservoir_data) (1 attribute from reservoir_data_module)
Attribute Name Description
res_dat
type(constituent_rct) (2 attributes from cs_data_module)
Attribute Name Description
cs_rct_soil
cs_rct_aqu
character(len=1) (1 attribute from hru_module)
Attribute Name Description
timest
|
I/O Operations
Unconditional Operations
Unit unit_*
Operation Details Variable Defaults Line
write write (*,111) "reading from groundwater file ", date_time(5), date_time(6), date_time(7) - 148
Unit unit_out_gw
Operation Details Variable Defaults Line
write write(out_gw,*) - 151
write write(out_gw,*) 'reading from file gwflow.input...' - 152
write write(out_gw,*) ' reading basic information...' - 177
else (line 182)
Unit unit_out_gw
Operation Details Variable Defaults Line
write write(out_gw,*) ' checking for connection (HRU, LSU) files...' - 202
if (i_exist) (line 205)
Unit unit_out_gw
Operation Details Variable Defaults Line
write write(out_gw,*) ' found gwflow.hrucell: proceed' - 208
write write(out_gw,*) ' gwflow.hrucell not found: using gwflow.lsucell' - 216
write write(out_gw,*) ' gwflow.lsucell: gw-->soil transfer not simulated' - 217
write write(out_gw,*) ' gwflow.lsucell: gw-->wetland transfer not simulated' - 218
write write(out_gw,*) ' found gwflow.lsucell: proceed' - 228
write write(out_gw,*) ' gwflow.lsucell: gw-->soil transfer not simulated' - 229
write write(out_gw,*) ' gwflow.lsucell: gw-->wetland transfer not simulated' - 230
write write(out_gw,*) ' gwflow.lsucell not found: using gwflow.hrucell' - 236
write write(out_gw,*) ' neither gwflow.hrucell or gwflow.lsucell found; stop simulation' - 240
write write(out_gw,*) ' reading aquifer and streambed parameters...' - 246
write write(out_gw,*) ' reading aquifer hydraulic conductivity' - 249
write write(out_gw,*) ' reading aquifer specific yield' - 259
write write(out_gw,*) ' reading streambed hydraulic conductivity' - 268
write write(out_gw,*) ' reading streambed thickness' - 277
write write(out_gw,*) ' reading grid cell information...' - 288
write write(out_gw,*) ' groundwater pumping external (gwflow.pumpex found)' - 951
write write(out_gw,*) ' groundwater-tile drainage outflow (gwflow.tiles found)' - 989
write write(out_gw,*) ' groundwater-reservoir exchange (gwflow.rescells found)' - 1063
write write(out_gw,*) ' groundwater-floodplain exchange (gwflow.floodplain found)' - 1134
write write(out_gw,*) ' canal-->groundwater seepage (gwflow.canals found)' - 1194
if (gw_state(i)%init < gw_state(i)%botm) (line 576)
Unit unit_out_gw
Operation Details Variable Defaults Line
write write(out_gw,*) ' counting number of active cells' - 585
if (distance.lt.min_dist) (line 614)
Unit unit_out_gw
Operation Details Variable Defaults Line
write write(out_gw,*) ' reading groundwater output times' - 626
write write(out_gw,*) ' reading observation cells' - 637
if (usgs_site_id.eq.usgs_id(k)) (line 695)
Unit unit_out_gw
Operation Details Variable Defaults Line
write write(out_gw,*) - 718
write write(out_gw,*) 'additional gwflow preparation...' - 719
write write(out_gw,*) - 720
write write(out_gw,*) ' processing channel-cell information' - 721
elseif (grid_type == "unstructured") (line 728)
Unit unit_out_gw
Operation Details Variable Defaults Line
write write(out_gw,*) ' allocate and prepare source-sink arrays...' - 740
write write(out_gw,*) ' recharge from soil' - 786
write write(out_gw,*) ' groundwater ET' - 794
write write(out_gw,*) ' groundwater-channel exchange' - 812
write write(out_gw,*) ' gwflow.pumpex not found; pumping not simulated' - 980
if (gw_soil_flag == 1) (line 843)
Unit unit_out_gw
Operation Details Variable Defaults Line
write write(out_gw,*) ' groundwater-->soil transfer' - 844
if (gw_satx_flag == 1) (line 876)
Unit unit_out_gw
Operation Details Variable Defaults Line
write write(out_gw,*) ' groundwater saturation excess flow' - 877
if (gw_state(i)%stat > 0) (line 893)
Unit unit_out_gw
Operation Details Variable Defaults Line
write write(out_gw,*) ' groundwater pumping for irrigation' - 906
if (gw_state(i)%stat == 1 .and. gw_state(i)%tile == 1) (line 1045)
Unit unit_out_gw
Operation Details Variable Defaults Line
write write(out_gw,*) ' gwflow.tiles not found; tile drainage not simulated' - 1055
if (grid_type == "structured") (line 1099)
Unit unit_out_gw
Operation Details Variable Defaults Line
write write(out_gw,*) ' gwflow.rescells not found (groundwater-res exchange not simulated)' - 1113
write write(out_gw,*) - 1905
write write(out_gw,*) ' initialize groundwater balance files and arrays' - 1906
if (gw_wet_flag == 1) (line 1118)
Unit unit_out_gw
Operation Details Variable Defaults Line
write write(out_gw,*) ' groundwater-->wetland exchange' - 1119
if (gw_fp_cellid(i) == gw_chan_id(k)) (line 1176)
Unit unit_out_gw
Operation Details Variable Defaults Line
write write(out_gw,*) ' gwflow.floodplain not found (groundwater-fp exchange not simulated)' - 1185
if (canal_out(canal) == 1) (line 1320)
Unit unit_out_gw
Operation Details Variable Defaults Line
write write(out_gw,*) ' gwflow.canals not found (canal seepage not simulated)' - 1344
write write(out_gw,*) - 1351
if (cs_db%num_cs > 0) (line 1378)
Unit unit_out_gw
Operation Details Variable Defaults Line
write write(out_gw,*) ' groundwater solute transport preparation...' - 1393
write write(out_gw,*) ' groundwater solute being simulated (gwflow.solutes found)' - 1394
if (gw_canal_flag == 1) (line 1647)
Unit unit_out_gw
Operation Details Variable Defaults Line
write write(out_gw,*) - 1670
write write(out_gw,*) ' read and prepare connection (HRU-cell or LSU-cell)' - 1671
if (lsu_cells_link == 1) (line 1672)
Unit unit_out_gw
Operation Details Variable Defaults Line
write write(out_gw,*) ' LSU-cell connections (gwflow.lsucell)' - 1673
if (nat_model == 1) (line 1722)
Unit unit_out_gw
Operation Details Variable Defaults Line
write write(out_gw,*) ' HRU-cell connections (gwflow.hrucell)' - 1754
Unit in_con%hru_con
Operation Details Variable Defaults Line
open open(5101,file=in_con%hru_con) - 1732
read read(5101,*) - 1736
read read(5101,*) - 1737
read read(5101,*) dum1,dum2,dum3,dum4,dum5,dum6,dum7,dum8,huc12_id - 1739
backspace backspace(5101) - 1740
read read(5101,*) hru_id - 1744
read read(5101,*,end=15) dum1,dum2,dum3,dum4,dum5,dum6,dum7,dum8,huc12_id - 1747
backspace backspace(5101) - 1748
if (cell_included_huc12(cell_num) == 1) (line 1845)
Unit unit_out_gw
Operation Details Variable Defaults Line
write write(out_gw,*) ' HRU-cell connections (gwflow.cellhru)' - 1862
if (gwflag_aa.eq.1) (line 2214)
Unit unit_out_gw
Operation Details Variable Defaults Line
write write(out_gw,*) - 2278
write write(out_gw,*) ' final preparations...' - 2279
write write(out_gw,*) ' map recharge delay to HRUs' - 2280
Unit file_name
Operation Details Variable Defaults Line
open open(out_solbal_aa+n,file=file_name) - 2216
write write(out_solbal_aa+n,*) 'Solute:',gwsol_nm(n) - 2217
write write(out_solbal_aa+n,*) 'Average annual groundwater watershed-wide solute loads' - 2218
write write(out_solbal_aa+n,*) - 2219
write write(out_solbal_aa+n,*) 'Positive value: solute mass added to aquifer' - 2220
write write(out_solbal_aa+n,*) 'Negative value: solute mass removed from aquifer' - 2221
write write(out_solbal_aa+n,*) - 2222
write write(out_solbal_aa+n,*) 'delm: kg total change in groundwater solute mass across all years' - 2223
write write(out_solbal_aa+n,*) 'rech: kg solute mass in recharge water' - 2224
write write(out_solbal_aa+n,*) 'gwsw: kg solute mass loaded to streams' - 2225
write write(out_solbal_aa+n,*) 'swgw: kg solute mass loaded from streams' - 2226
write write(out_solbal_aa+n,*) 'satx: kg solute mass loaded to streams by saturation excess flow' - 2227
write write(out_solbal_aa+n,*) 'soil: kg solute mass loaded to HRU soil profiles' - 2228
write write(out_solbal_aa+n,*) 'advn: kg solute mass transported by advection' - 2229
write write(out_solbal_aa+n,*) 'disp: kg solute mass transported by dispersion' - 2230
write write(out_solbal_aa+n,*) 'rcti: kg solute mass produced by kinetic reaction' - 2231
write write(out_solbal_aa+n,*) 'rcto: kg solute mass consumed by kinetic reaction' - 2232
write write(out_solbal_aa+n,*) 'minl: kg solute mass added by mineral dissolution' - 2233
write write(out_solbal_aa+n,*) 'sorb: kg solute mass removed via sorption' - 2234
write write(out_solbal_aa+n,*) 'ppag: kg solute mass removed by groundwater pumping for irrigation' - 2235
write write(out_solbal_aa+n,*) 'ppex: kg solute mass removed by groundwater pumping specified by user' - 2236
write write(out_solbal_aa+n,*) 'tile: kg solute mass removed by tile drains' - 2237
write write(out_solbal_aa+n,*) 'resv: kg solute mass loaded to/from reservoirs' - 2238
write write(out_solbal_aa+n,*) 'wetl: kg solute mass loaded to/from wetlands' - 2239
write write(out_solbal_aa+n,*) 'canl: kg solute mass loaded to groundwater from canal seepage' - 2240
write write(out_solbal_aa+n,*) 'fpln: kg solute mass in floodplain exchange' - 2241
write write(out_solbal_aa+n,*) - 2242
write write(out_solbal_aa+n,120) (sol_hdr_aa(j),j=1,20) - 2245
if (cell_id_usg(i,j) > 0) (line 2348)
Unit unit_out_gw
Operation Details Variable Defaults Line
write write(out_gw,*) ' prepare output files for monthly and annual average groundwater head' - 2364
if (gw_solute_flag == 1) (line 2373)
Unit unit_out_gw
Operation Details Variable Defaults Line
write write(out_gw,*) ' prepare output files for monthly and annual average solute conc.' - 2374
if (gw_flow_cal.eq.1) (line 2403)
Unit unit_out_gw
Operation Details Variable Defaults Line
write write(out_gw,*) - 2436
write write(out_gw,*) - 2437
write write(out_gw,*) 'record of daily gwflow use...' - 2438
write write(out_gw,*) - 2439
if (gwflag_day.eq.1) (line 2121)
Unit file_name
Operation Details Variable Defaults Line
open open(out_solbal_dy+n,file=file_name) - 2123
write write(out_solbal_dy+n,*) 'Solute:',gwsol_nm(n) - 2124
write write(out_solbal_dy+n,*) 'Groundwater watershed-wide solute loads for each day' - 2125
write write(out_solbal_dy+n,*) - 2126
write write(out_solbal_dy+n,*) 'Positive value: solute mass added to aquifer' - 2127
write write(out_solbal_dy+n,*) 'Negative value: solute mass removed from aquifer' - 2128
write write(out_solbal_dy+n,*) - 2129
write write(out_solbal_dy+n,*) 'ts: days time step used for groundwater solute calculations' - 2130
write write(out_solbal_dy+n,*) 'mbef: kg total groundwater solute mass at the beginning of the day' - 2131
write write(out_solbal_dy+n,*) 'maft: kg total groundwater solute mass at the end of the day' - 2132
write write(out_solbal_dy+n,*) 'rech: kg solute mass in recharge water' - 2133
write write(out_solbal_dy+n,*) 'gwsw: kg solute mass loaded to streams' - 2134
write write(out_solbal_dy+n,*) 'swgw: kg solute mass loaded from streams' - 2135
write write(out_solbal_dy+n,*) 'satx: kg solute mass loaded to streams by saturation excess flow' - 2136
write write(out_solbal_dy+n,*) 'soil: kg solute mass loaded to HRU soil profiles' - 2137
write write(out_solbal_dy+n,*) 'advn: kg solute mass transported by advection' - 2138
write write(out_solbal_dy+n,*) 'disp: kg solute mass transported by dispersion' - 2139
write write(out_solbal_dy+n,*) 'rcti: kg solute mass produced by kinetic reaction' - 2140
write write(out_solbal_dy+n,*) 'rcto: kg solute mass consumed by kinetic reaction' - 2141
write write(out_solbal_dy+n,*) 'minl: kg solute mass added by mineral dissolution' - 2142
write write(out_solbal_dy+n,*) 'sorb: kg solute mass removed by sorption' - 2143
write write(out_solbal_dy+n,*) 'ppag: kg solute mass removed by groundwater pumping for irrigation' - 2144
write write(out_solbal_dy+n,*) 'ppex: kg solute mass removed by groundwater pumping specified by user' - 2145
write write(out_solbal_dy+n,*) 'tile: kg solute mass removed by tile drains' - 2146
write write(out_solbal_dy+n,*) 'resv: kg solute mass loaded to/from reservoirs' - 2147
write write(out_solbal_dy+n,*) 'wetl: kg solute mass loaded to/from wetlands' - 2148
write write(out_solbal_dy+n,*) 'canl: kg solute mass loaded to groundwater from canal seepage' - 2149
write write(out_solbal_dy+n,*) 'fpln: kg solute mass in floodplain exchange' - 2150
write write(out_solbal_dy+n,*) 'error: -- mass balance error for aquifer' - 2151
write write(out_solbal_dy+n,*) - 2152
write write(out_solbal_dy+n,119) (sol_hdr_day(j),j=1,24) - 2155
if (gwflag_yr.eq.1) (line 2159)
Unit file_name
Operation Details Variable Defaults Line
open open(out_solbal_yr+n,file=file_name) - 2161
write write(out_solbal_yr+n,*) 'Solute:',gwsol_nm(n) - 2162
write write(out_solbal_yr+n,*) 'Groundwater watershed-wide solute loads for each year' - 2163
write write(out_solbal_yr+n,*) - 2164
write write(out_solbal_yr+n,*) 'Positive value: solute mass added to aquifer' - 2165
write write(out_solbal_yr+n,*) 'Negative value: solute mass removed from aquifer' - 2166
write write(out_solbal_yr+n,*) - 2167
write write(out_solbal_yr+n,*) 'delm: kg change in groundwater solute mass during the year' - 2168
write write(out_solbal_yr+n,*) 'rech: kg solute mass in recharge water' - 2169
write write(out_solbal_yr+n,*) 'gwsw: kg solute mass loaded to streams' - 2170
write write(out_solbal_yr+n,*) 'swgw: kg solute mass loaded from streams' - 2171
write write(out_solbal_yr+n,*) 'satx: kg solute mass loaded to streams by saturation excess flow' - 2172
write write(out_solbal_yr+n,*) 'soil: kg solute mass loaded to HRU soil profiles' - 2173
write write(out_solbal_yr+n,*) 'advn: kg solute mass transported by advection' - 2174
write write(out_solbal_yr+n,*) 'disp: kg solute mass transported by dispersion' - 2175
write write(out_solbal_yr+n,*) 'rcti: kg solute mass produced by kinetic reaction' - 2176
write write(out_solbal_yr+n,*) 'rcto: kg solute mass consumed by kinetic reaction' - 2177
write write(out_solbal_yr+n,*) 'minl: kg solute mass added by mineral dissolution' - 2178
write write(out_solbal_yr+n,*) 'sorb: kg solute mass removed by denitrification' - 2179
write write(out_solbal_yr+n,*) 'ppag: kg solute mass removed by groundwater pumping for irrigation' - 2180
write write(out_solbal_yr+n,*) 'ppex: kg solute mass removed by groundwater pumping specified by user' - 2181
write write(out_solbal_yr+n,*) 'tile: kg solute mass removed by tile drains' - 2182
write write(out_solbal_yr+n,*) 'resv: kg solute mass loaded to/from reservoirs' - 2183
write write(out_solbal_yr+n,*) 'wetl: kg solute mass loaded to/from wetlands' - 2184
write write(out_solbal_yr+n,*) 'canl: kg solute mass loaded to groundwater from canal seepage' - 2185
write write(out_solbal_yr+n,*) 'fpln: kg solute mass in floodplain exchange' - 2186
write write(out_solbal_yr+n,*) - 2187
write write(out_solbal_yr+n,120) (sol_hdr_yr(j),j=1,20) - 2190
Allocations
if (i_exist) (line 234)
Operation Variables Details Line
allocate zones_aquK(nzones_aquK allocate (zones_aquK(nzones_aquK), source = 0.) 253
allocate zones_aquSy(nzones_aquSy allocate (zones_aquSy(nzones_aquSy), source = 0.) 262
allocate zones_strK(nzones_strK allocate (zones_strK(nzones_strK), source = 0.) 271
allocate zones_strbed(nzones_strbed allocate (zones_strbed(nzones_strbed), source = 0.) 280
allocate gw_pumpex_cell(gw_npumpex allocate (gw_pumpex_cell(gw_npumpex), source = 0) 955
allocate gw_pumpex_nperiods(gw_npumpex allocate (gw_pumpex_nperiods(gw_npumpex), source = 0) 956
allocate gw_pumpex_dates(gw_npumpex,2,1000 allocate (gw_pumpex_dates(gw_npumpex,2,1000), source = 0) 957
allocate gw_pumpex_rates(gw_npumpex,1000 allocate (gw_pumpex_rates(gw_npumpex,1000), source = 0.) 958
allocate gw_resv_info(sp_ob%res allocate (gw_resv_info(sp_ob%res)) 1071
allocate gw_fpln_info(sp_ob%chandeg allocate (gw_fpln_info(sp_ob%chandeg)) 1139
allocate gw_fp_cellid(gw_fp_ncells allocate (gw_fp_cellid(gw_fp_ncells), source = 0) 1141
allocate gw_fp_chanid(gw_fp_ncells allocate (gw_fp_chanid(gw_fp_ncells), source = 0) 1142
allocate gw_fp_K(gw_fp_ncells allocate (gw_fp_K(gw_fp_ncells), source = 0.) 1143
allocate gw_fp_area(gw_fp_ncells allocate (gw_fp_area(gw_fp_ncells), source = 0.) 1144
allocate gw_chan_canl_info(sp_ob%chandeg allocate (gw_chan_canl_info(sp_ob%chandeg)) 1198
allocate canal_out_info(gw_ncanal,5 allocate (canal_out_info(gw_ncanal,5), source = 0.) 1203
if (grid_type == "structured") (line 292)
Operation Variables Details Line
allocate grid_status(grid_nrow,grid_ncol allocate (grid_status(grid_nrow,grid_ncol), source = 0) 297
allocate cell_id_usg(grid_nrow,grid_ncol allocate (cell_id_usg(grid_nrow,grid_ncol), source = 0) 301
allocate cell_id_list(grid_nrow*grid_ncol allocate (cell_id_list(grid_nrow*grid_ncol), source = 0) 302
if (grid_status(i,j) > 0) (line 310)
Operation Variables Details Line
allocate gw_state(ncell allocate (gw_state(ncell)) 319
allocate cell_con(ncell allocate (cell_con(ncell)) 344
if (grid_status(i,j-1) > 0) (line 370)
Operation Variables Details Line
allocate cell_con(cell_id_usg(i,j allocate (cell_con(cell_id_usg(i,j))%cell_id(num_conn), source = 0) 375
if (cell_id_usg(i,j) > 0) (line 434)
Operation Variables Details Line
allocate grid_val(grid_nrow,grid_ncol allocate (grid_val(grid_nrow,grid_ncol), source = 0.) 440
allocate grid_int(grid_nrow,grid_ncol allocate (grid_int(grid_nrow,grid_ncol), source = 0) 441
allocate delay(ncell allocate (delay(ncell), source = 0.) 489
allocate gwsol_chem(i allocate (gwsol_chem(i)%shale(num_geol_shale), source = 0) 1532
allocate gwsol_chem(i allocate (gwsol_chem(i)%shale_sseratio(num_geol_shale), source = 0.) 1533
allocate gwsol_chem(i allocate (gwsol_chem(i)%shale_o2a(num_geol_shale), source = 0.) 1534
allocate gwsol_chem(i allocate (gwsol_chem(i)%shale_no3a(num_geol_shale), source = 0.) 1535
elseif (grid_type == "unstructured") (line 525)
Operation Variables Details Line
allocate gw_state(ncell allocate (gw_state(ncell)) 528
allocate delay(ncell allocate (delay(ncell), source = 0.) 555
allocate cell_con(ncell allocate (cell_con(ncell)) 556
allocate cell_con(i allocate (cell_con(i)%cell_id(gw_state(i)%ncon), source = 0) 567
allocate gw_ss(ncell allocate (gw_ss(ncell)) 743
allocate gw_ss_sum(ncell allocate (gw_ss_sum(ncell)) 765
allocate gwflow_perc(num_hru allocate (gwflow_perc(num_hru), source = 0.) 790
allocate etremain(num_hru allocate (etremain(num_hru), source = 0.) 798
allocate cell_con(i allocate (cell_con(i)%latl(gw_state(i)%ncon), source = 0.) 803
allocate cell_con(i allocate (cell_con(i)%sat(gw_state(i)%ncon), source = 0.) 804
allocate gw_chan_info(sp_ob%chandeg allocate (gw_chan_info(sp_ob%chandeg)) 817
allocate gw_chan_info(i allocate (gw_chan_info(i)%cells(gw_chan_info(i)%ncon), source = 0) 824
allocate gw_chan_info(i allocate (gw_chan_info(i)%leng(gw_chan_info(i)%ncon), source = 0.) 825
allocate gw_chan_info(i allocate (gw_chan_info(i)%elev(gw_chan_info(i)%ncon), source = 0.) 826
allocate gw_chan_info(i allocate (gw_chan_info(i)%hydc(gw_chan_info(i)%ncon), source = 0.) 827
allocate gw_chan_info(i allocate (gw_chan_info(i)%thck(gw_chan_info(i)%ncon), source = 0.) 828
allocate gw_tile_info(sp_ob%chandeg allocate (gw_tile_info(sp_ob%chandeg)) 1031
if (gw_state(i)%stat == 1) (line 596)
Operation Variables Details Line
allocate gw_bound_near(ncell allocate (gw_bound_near(ncell), source = 0) 602
allocate gw_bound_dist(ncell allocate (gw_bound_dist(ncell), source = 0.) 603
if (distance.lt.min_dist) (line 614)
Operation Variables Details Line
allocate gw_output_yr(gw_num_output allocate (gw_output_yr(gw_num_output), source = 0) 629
allocate gw_output_day(gw_num_output allocate (gw_output_day(gw_num_output), source = 0) 630
allocate gw_obs_cells(gw_num_obs_wells allocate (gw_obs_cells(gw_num_obs_wells), source = 0) 640
if (usgs_obs == 1) (line 643)
Operation Variables Details Line
allocate usgs_id(gw_num_obs_wells allocate (usgs_id(gw_num_obs_wells), source = 0.d0) 644
allocate gw_obs_head(gw_num_obs_wells allocate (gw_obs_head(gw_num_obs_wells), source = 0.) 654
allocate usgs_head_vals(gw_num_obs_wells,101 allocate (usgs_head_vals(gw_num_obs_wells,101), source = 0.) 690
if (usgs_site_id.eq.usgs_id(k)) (line 695)
Operation Variables Details Line
allocate gw_obs_head_annual(gw_num_obs_wells,366 allocate (gw_obs_head_annual(gw_num_obs_wells,366), source = 0.) 705
allocate sim_head_vals(gw_num_obs_wells,101 allocate (sim_head_vals(gw_num_obs_wells,101), source = 0.) 706
allocate gw_obs_sat_annual(gw_num_obs_wells,366 allocate (gw_obs_sat_annual(gw_num_obs_wells,366), source = 0.) 707
allocate sim_sat_vals(gw_num_obs_wells,101 allocate (sim_sat_vals(gw_num_obs_wells,101), source = 0.) 708
allocate gw_chan_cell(sp_ob%gwflow allocate (gw_chan_cell(sp_ob%gwflow), source = 0) 722
allocate gw_chan_K(sp_ob%gwflow allocate (gw_chan_K(sp_ob%gwflow), source = 0.) 723
allocate gw_chan_thick(sp_ob%gwflow allocate (gw_chan_thick(sp_ob%gwflow), source = 0.) 724
if (gw_soil_flag == 1) (line 843)
Operation Variables Details Line
allocate cell_channel(ncell allocate (cell_channel(ncell), source = 0.) 852
allocate hru_soil(num_hru,20,gw_nsolute allocate (hru_soil(num_hru,20,gw_nsolute), source = 0.) 1611
if (gw_satx_flag == 1) (line 876)
Operation Variables Details Line
allocate gw_satx_info(sp_ob%chandeg allocate (gw_satx_info(sp_ob%chandeg)) 878
if (gw_state(i)%stat > 0) (line 881)
Operation Variables Details Line
allocate gw_satx_info(i allocate (gw_satx_info(i)%cells(gw_satx_info(i)%ncon), source = 0) 888
allocate hru_pump(sp_ob%hru allocate (hru_pump(sp_ob%hru), source = 0.) 914
allocate hru_pump_mo(sp_ob%hru allocate (hru_pump_mo(sp_ob%hru), source = 0.) 915
allocate hru_pump_yr(sp_ob%hru allocate (hru_pump_yr(sp_ob%hru), source = 0.) 916
allocate hru_pump_mo_all(sp_ob%hru,time%nbyr*12 allocate (hru_pump_mo_all(sp_ob%hru,time%nbyr*12), source = 0.) 917
allocate hru_pump_yr_all(sp_ob%hru,time%nbyr allocate (hru_pump_yr_all(sp_ob%hru,time%nbyr), source = 0.) 918
if (hru_pump_flag == 1) (line 931)
Operation Variables Details Line
allocate hru_pump_ids(num_hru_pump_obs allocate (hru_pump_ids(num_hru_pump_obs), source = 0) 935
allocate hru_pump_obs(num_hru_pump_obs allocate (hru_pump_obs(num_hru_pump_obs), source = 0.) 939
if (gw_tile_group_flag == 1) (line 998)
Operation Variables Details Line
allocate gw_tile_groups(gw_tile_num_group,5000 allocate (gw_tile_groups(gw_tile_num_group,5000), source = 0) 1000
if (gw_state(i)%stat.eq.1 .and. gw_state(i)%tile.eq.1) (line 1033)
Operation Variables Details Line
allocate gw_tile_info(i allocate (gw_tile_info(i)%cells(gw_tile_info(i)%ncon), source = 0) 1040
if (res_id > 0) (line 1077)
Operation Variables Details Line
allocate gw_resv_info(i allocate (gw_resv_info(i)%cells(gw_resv_info(i)%ncon), source = 0) 1083
allocate gw_resv_info(i allocate (gw_resv_info(i)%elev(gw_resv_info(i)%ncon), source = 0.) 1084
allocate gw_resv_info(i allocate (gw_resv_info(i)%hydc(gw_resv_info(i)%ncon), source = 0.) 1085
allocate gw_resv_info(i allocate (gw_resv_info(i)%thck(gw_resv_info(i)%ncon), source = 0.) 1086
if (gw_wet_flag == 1) (line 1118)
Operation Variables Details Line
allocate wet_thick(sp_ob%hru allocate (wet_thick(sp_ob%hru), source = 0.) 1121
allocate flood_freq(sp_ob%chandeg allocate (flood_freq(sp_ob%chandeg), source = 0) 1129
if (gw_fp_area(i).gt.(gw_state(gw_fp_cellid(i))%area)) (line 1152)
Operation Variables Details Line
allocate gw_fpln_info(i allocate (gw_fpln_info(i)%cells(gw_fpln_info(i)%ncon), source = 0) 1161
allocate gw_fpln_info(i allocate (gw_fpln_info(i)%hydc(gw_fpln_info(i)%ncon), source = 0.) 1162
allocate gw_fpln_info(i allocate (gw_fpln_info(i)%area(gw_fpln_info(i)%ncon), source = 0.) 1163
allocate gw_fpln_info(i allocate (gw_fpln_info(i)%mtch(gw_fpln_info(i)%ncon), source = 0) 1164
if (channel == 0) (line 1207)
Operation Variables Details Line
allocate gw_chan_canl_info(i allocate (gw_chan_canl_info(i)%canals(gw_chan_canl_info(i)%ncanal), source = 0) 1220
allocate gw_chan_canl_info(i allocate (gw_chan_canl_info(i)%wdth(gw_chan_canl_info(i)%ncanal), source = 0.) 1221
allocate gw_chan_canl_info(i allocate (gw_chan_canl_info(i)%dpth(gw_chan_canl_info(i)%ncanal), source = 0.) 1222
allocate gw_chan_canl_info(i allocate (gw_chan_canl_info(i)%thck(gw_chan_canl_info(i)%ncanal), source = 0.) 1223
allocate gw_chan_canl_info(i allocate (gw_chan_canl_info(i)%dayb(gw_chan_canl_info(i)%ncanal), source = 0) 1224
allocate gw_chan_canl_info(i allocate (gw_chan_canl_info(i)%daye(gw_chan_canl_info(i)%ncanal), source = 0) 1225
if (canal_out(canal) == 0) (line 1235)
Operation Variables Details Line
allocate canalK_zones(num_canalK_zones allocate (canalK_zones(num_canalK_zones), source = 0.) 1248
allocate gw_canl_info(i allocate (gw_canl_info(i)%cells(gw_canl_info(i)%ncon), source = 0) 1291
allocate gw_canl_info(i allocate (gw_canl_info(i)%leng(gw_canl_info(i)%ncon), source = 0.) 1292
allocate gw_canl_info(i allocate (gw_canl_info(i)%elev(gw_canl_info(i)%ncon), source = 0.) 1293
allocate gw_canl_info(i allocate (gw_canl_info(i)%hydc(gw_canl_info(i)%ncon), source = 0.) 1294
if (canal_out(canal) == 1) (line 1259)
Operation Variables Details Line
allocate gw_canl_out_info(gw_canal_ncells_out allocate (gw_canl_out_info(gw_canal_ncells_out)) 1263
allocate gw_canl_info(gw_ncanal allocate (gw_canl_info(gw_ncanal)) 1279
if (cs_db%num_cs > 0) (line 1378)
Operation Variables Details Line
allocate canal_out_conc(gw_nsolute allocate (canal_out_conc(gw_nsolute), source = 0.) 1401
allocate gwsol_state(ncell allocate (gwsol_state(ncell)) 1409
allocate gwsol_state(i allocate (gwsol_state(i)%solute(gw_nsolute)) 1411
if (gwsol_minl == 1) (line 1445)
Operation Variables Details Line
allocate gwsol_minl_state(ncell allocate (gwsol_minl_state(ncell)) 1450
allocate gwsol_minl_state(i allocate (gwsol_minl_state(i)%fract(gw_nminl), source = 0.) 1452
if (gwsol_cons == 1) (line 1486)
Operation Variables Details Line
allocate gwsol_chem(ncell allocate (gwsol_chem(ncell)) 1488
if (grid_type == "unstructured") (line 1499)
Operation Variables Details Line
allocate cell_int(ncell allocate (cell_int(ncell), source = 0) 1500
if (grid_int(i,j) > 0) (line 1561)
Operation Variables Details Line
allocate gwsol_ss(ncell allocate (gwsol_ss(ncell)) 1586
allocate gwsol_ss(i allocate (gwsol_ss(i)%solute(gw_nsolute)) 1588
allocate gwsol_ss_sum(ncell allocate (gwsol_ss_sum(ncell)) 1591
allocate gwsol_ss_sum(i allocate (gwsol_ss_sum(i)%solute(gw_nsolute)) 1593
allocate gw_rechsol(sp_ob%hru,gw_nsolute allocate (gw_rechsol(sp_ob%hru,gw_nsolute), source = 0.) 1599
allocate gwflow_percsol(num_hru,gw_nsolute allocate (gwflow_percsol(num_hru,gw_nsolute), source = 0.) 1600
if (gw_canal_flag == 1) (line 1647)
Operation Variables Details Line
allocate gw_obs_solute(gw_num_obs_wells,gw_nsolute allocate (gw_obs_solute(gw_num_obs_wells,gw_nsolute), source = 0.) 1659
if (lsu_cells_link == 1) (line 1672)
Operation Variables Details Line
allocate lsus_connected(nlsu allocate (lsus_connected(nlsu), source = 0) 1679
allocate lsu_num_cells(nlsu allocate (lsu_num_cells(nlsu), source = 0) 1688
allocate lsu_cells(nlsu,5000 allocate (lsu_cells(nlsu,5000), source = 0) 1689
allocate lsu_cells_fract(nlsu,5000 allocate (lsu_cells_fract(nlsu,5000), source = 0.) 1690
if (nat_model == 1) (line 1722)
Operation Variables Details Line
allocate huc12(sp_ob%outlet allocate (huc12(sp_ob%outlet), source = 0.d0) 1725
allocate huc12_hrus(sp_ob%outlet,5000 allocate (huc12_hrus(sp_ob%outlet,5000), source = 0) 1733
allocate huc12_nhru(sp_ob%outlet allocate (huc12_nhru(sp_ob%outlet), source = 0) 1734
allocate hrus_connected(num_hru allocate (hrus_connected(num_hru), source = 0) 1761
allocate hru_num_cells(num_hru allocate (hru_num_cells(num_hru), source = 0) 1770
allocate hru_cells(num_hru,5000 allocate (hru_cells(num_hru,5000), source = 0) 1771
allocate hru_cells_fract(num_hru,5000 allocate (hru_cells_fract(num_hru,5000), source = 0.) 1772
allocate cells_fract(num_hru,5000 allocate (cells_fract(num_hru,5000), source = 0.) 1773
allocate huc12_cells(sp_ob%outlet,50000 allocate (huc12_cells(sp_ob%outlet,50000), source = 0) 1816
allocate huc12_ncell(sp_ob%outlet allocate (huc12_ncell(sp_ob%outlet), source = 0) 1817
allocate cell_included_huc12(ncell allocate (cell_included_huc12(ncell), source = 0) 1818
allocate gw_huc12_wb(15,sp_ob%outlet allocate (gw_huc12_wb(15,sp_ob%outlet), source = 0.) 2041
allocate gw_huc12_wb_mo(15,sp_ob%outlet allocate (gw_huc12_wb_mo(15,sp_ob%outlet), source = 0.) 2069
if (cell_included_huc12(cell_num) == 1) (line 1845)
Operation Variables Details Line
allocate cell_received(ncell allocate (cell_received(ncell), source = 0) 1859
allocate cell_num_hrus(ncell allocate (cell_num_hrus(ncell), source = 0) 1863
allocate cell_hrus(ncell,100 allocate (cell_hrus(ncell,100), source = 0) 1864
allocate cell_hrus_fract(ncell,100 allocate (cell_hrus_fract(ncell,100), source = 0.) 1865
if (gw_solute_flag == 1) (line 2075)
Operation Variables Details Line
allocate sol_grid_chng_yr(gw_nsolute allocate (sol_grid_chng_yr(gw_nsolute), source = 0.) 2078
allocate sol_grid_rech_yr(gw_nsolute allocate (sol_grid_rech_yr(gw_nsolute), source = 0.) 2079
allocate sol_grid_gwsw_yr(gw_nsolute allocate (sol_grid_gwsw_yr(gw_nsolute), source = 0.) 2080
allocate sol_grid_swgw_yr(gw_nsolute allocate (sol_grid_swgw_yr(gw_nsolute), source = 0.) 2081
allocate sol_grid_satx_yr(gw_nsolute allocate (sol_grid_satx_yr(gw_nsolute), source = 0.) 2082
allocate sol_grid_advn_yr(gw_nsolute allocate (sol_grid_advn_yr(gw_nsolute), source = 0.) 2083
allocate sol_grid_disp_yr(gw_nsolute allocate (sol_grid_disp_yr(gw_nsolute), source = 0.) 2084
allocate sol_grid_rcti_yr(gw_nsolute allocate (sol_grid_rcti_yr(gw_nsolute), source = 0.) 2085
allocate sol_grid_rcto_yr(gw_nsolute allocate (sol_grid_rcto_yr(gw_nsolute), source = 0.) 2086
allocate sol_grid_minl_yr(gw_nsolute allocate (sol_grid_minl_yr(gw_nsolute), source = 0.) 2087
allocate sol_grid_sorb_yr(gw_nsolute allocate (sol_grid_sorb_yr(gw_nsolute), source = 0.) 2088
allocate sol_grid_ppag_yr(gw_nsolute allocate (sol_grid_ppag_yr(gw_nsolute), source = 0.) 2089
allocate sol_grid_ppex_yr(gw_nsolute allocate (sol_grid_ppex_yr(gw_nsolute), source = 0.) 2090
allocate sol_grid_tile_yr(gw_nsolute allocate (sol_grid_tile_yr(gw_nsolute), source = 0.) 2091
allocate sol_grid_soil_yr(gw_nsolute allocate (sol_grid_soil_yr(gw_nsolute), source = 0.) 2092
allocate sol_grid_resv_yr(gw_nsolute allocate (sol_grid_resv_yr(gw_nsolute), source = 0.) 2093
allocate sol_grid_wetl_yr(gw_nsolute allocate (sol_grid_wetl_yr(gw_nsolute), source = 0.) 2094
allocate sol_grid_canl_yr(gw_nsolute allocate (sol_grid_canl_yr(gw_nsolute), source = 0.) 2095
allocate sol_grid_fpln_yr(gw_nsolute allocate (sol_grid_fpln_yr(gw_nsolute), source = 0.) 2096
allocate sol_grid_chng_tt(gw_nsolute allocate (sol_grid_chng_tt(gw_nsolute), source = 0.) 2097
allocate sol_grid_rech_tt(gw_nsolute allocate (sol_grid_rech_tt(gw_nsolute), source = 0.) 2098
allocate sol_grid_gwsw_tt(gw_nsolute allocate (sol_grid_gwsw_tt(gw_nsolute), source = 0.) 2099
allocate sol_grid_swgw_tt(gw_nsolute allocate (sol_grid_swgw_tt(gw_nsolute), source = 0.) 2100
allocate sol_grid_satx_tt(gw_nsolute allocate (sol_grid_satx_tt(gw_nsolute), source = 0.) 2101
allocate sol_grid_advn_tt(gw_nsolute allocate (sol_grid_advn_tt(gw_nsolute), source = 0.) 2102
allocate sol_grid_disp_tt(gw_nsolute allocate (sol_grid_disp_tt(gw_nsolute), source = 0.) 2103
allocate sol_grid_rcti_tt(gw_nsolute allocate (sol_grid_rcti_tt(gw_nsolute), source = 0.) 2104
allocate sol_grid_rcto_tt(gw_nsolute allocate (sol_grid_rcto_tt(gw_nsolute), source = 0.) 2105
allocate sol_grid_minl_tt(gw_nsolute allocate (sol_grid_minl_tt(gw_nsolute), source = 0.) 2106
allocate sol_grid_sorb_tt(gw_nsolute allocate (sol_grid_sorb_tt(gw_nsolute), source = 0.) 2107
allocate sol_grid_ppag_tt(gw_nsolute allocate (sol_grid_ppag_tt(gw_nsolute), source = 0.) 2108
allocate sol_grid_ppex_tt(gw_nsolute allocate (sol_grid_ppex_tt(gw_nsolute), source = 0.) 2109
allocate sol_grid_tile_tt(gw_nsolute allocate (sol_grid_tile_tt(gw_nsolute), source = 0.) 2110
allocate sol_grid_soil_tt(gw_nsolute allocate (sol_grid_soil_tt(gw_nsolute), source = 0.) 2111
allocate sol_grid_resv_tt(gw_nsolute allocate (sol_grid_resv_tt(gw_nsolute), source = 0.) 2112
allocate sol_grid_wetl_tt(gw_nsolute allocate (sol_grid_wetl_tt(gw_nsolute), source = 0.) 2113
allocate sol_grid_canl_tt(gw_nsolute allocate (sol_grid_canl_tt(gw_nsolute), source = 0.) 2114
allocate sol_grid_fpln_tt(gw_nsolute allocate (sol_grid_fpln_tt(gw_nsolute), source = 0.) 2115
if (gwflag_aa.eq.1) (line 2214)
Operation Variables Details Line
allocate gw_delay(num_hru allocate (gw_delay(num_hru), source = 0.) 2281
allocate gw_rech(num_hru allocate (gw_rech(num_hru), source = 0.) 2282
if (gw_num_obs_chan.gt.0) (line 2392)
Operation Variables Details Line
allocate obs_channels(gw_num_obs_chan allocate (obs_channels(gw_num_obs_chan), source = 0) 2394
allocate obs_flow_vals(gw_num_obs_chan,num_months allocate (obs_flow_vals(gw_num_obs_chan,num_months), source = 0.) 2395
allocate sim_flow_vals(gw_num_obs_chan,num_months allocate (sim_flow_vals(gw_num_obs_chan,num_months), source = 0.) 2396
if (gw_flow_cal.eq.1) (line 2403)
Operation Variables Details Line
allocate hydsep_flag(sp_ob%chandeg allocate (hydsep_flag(sp_ob%chandeg), source = 0) 2416
allocate chan_hyd_sep(sp_ob%chandeg,6 allocate (chan_hyd_sep(sp_ob%chandeg,6), source = 0.) 2418
Calls
Call graph
gwflow_read calls 10, 1000, 10000, 50