gwflow_simulate – SWAT+
gwflow_simulate Subroutine
2114 statements
Source File
subroutine gwflow_simulate()
Uses
calibration_data_module
hydrograph_module
soil_module
water_body_module
gwflow_module
sd_channel_module
maximum_data_module
time_module
hru_module
~ ~ ~ PURPOSE ~ ~ ~
this subroutine calculates new groundwater storage and solute mass for each gwflow grid cell;
also, computes and write out daily/annual/average annual fluxes and mass balance error
** tu Wunused-label: 103 format(i8,i8,i8,i8,i8,i8,i8,50(f15.3)) ** tu Wunused-label: 104 format(10000(f12.2)) ** tu Wunused-label: 106 format(i8,i8,i8,50(f12.3)) ** tu Wunused-label: 108 format(i8,2x,50(e12.4)) ** tu Wunused-label: 109 format(i8,i8,1000(e12.3))
Arguments
None
Local Variables
Type Visibility Attributes Name Initial
integer, private :: i
integer, private :: j
integer, private :: k
integer, private :: n
integer, private :: s
integer, private :: dum
integer, private :: num_ts
integer, private :: cell_id
real, private :: sum
real, private :: area1
real, private :: area2
real, private :: area
real, private :: conn_length
real, private :: dist_x
real, private :: dist_y
real, private :: grad_distance
real, private :: Q_cell
real, private :: face_K
real, private :: sat_thick1
real, private :: sat_thick2
real, private :: face_sat
real, private :: stor_change
real, private :: sat_change
real, private :: flow_area
real, private :: Q
real, private :: gradient
real, private :: frac_sat
real, private :: depth_wt_avg
real, private :: mass_error
real, private :: sum_tile
integer, private :: t
real, private :: gw_trans_time_step
real, private :: time_fraction
real, private :: gw_volume_old
real, private :: gw_volume_new
real, private :: gw_volume_inter
real, private :: mass_adv
real, private :: mass_dsp
real, private :: m_change
real, private :: del_no_sorp
real, private :: mass_sorb
real, private :: sol_grid_mbef
real, private :: sol_grid_maft
real, private :: sol_grid_rech
real, private :: sol_grid_gwsw
real, private :: sol_grid_swgw
real, private :: sol_grid_satx
real, private :: sol_grid_advn
real, private :: sol_grid_disp
real, private :: sol_grid_rcti
real, private :: sol_grid_rcto
real, private :: sol_grid_minl
real, private :: sol_grid_sorb
real, private :: sol_grid_ppag
real, private :: sol_grid_ppex
real, private :: sol_grid_tile
real, private :: sol_grid_soil
real, private :: sol_grid_resv
real, private :: sol_grid_wetl
real, private :: sol_grid_canl
real, private :: sol_grid_fpln
real, private :: head_sum
real, private :: head_avg
real, private :: head_mae
real, private :: error_sum
real, private :: head_residual
real, private :: error_sum_well
integer, private :: write_yr
integer, private :: usgs_yr
integer, private :: val_count
integer, private :: val_count_well
integer, private :: num_yrs_calb
integer, private :: num_yrs_test
real, private :: head_mae_calb
real, private :: head_mae_test
real, private :: sat_sum
real, private :: sat_avg
real, private :: sum_sat
real, private :: sum_sat_well
real, private :: sat_div
real, private :: sat_div_calb
real, private :: sat_div_test
integer, private :: num_gw_meas
integer, private :: num_gw_meas_calb
integer, private :: num_gw_meas_test
integer, private :: chan_count
integer, private :: month_count
integer, private :: month_count_calb
integer, private :: month_count_test
real, private :: sum_obs_flow
real, private :: sum_sim_flow
real, private :: mean_obs_flow
real, private :: mean_sim_flow
real, private :: sum_resi_nse
real, private :: sum_diff_nse
real, private :: sum_resi_nse1
real, private :: sum_diff_nse1
real, private :: sum_num
real, private :: sum_den
real, private :: sum_den1
real, private :: sum_den2
real, private :: cc
real, private :: sum_sim_sd
real, private :: sum_obs_sd
real, private :: sim_sd
real, private :: obs_sd
integer, private :: num_months_calb
integer, private :: num_months_test
Outside Variables and Types Used
type(calibration_parameters) (1 attribute from calibration_data_module)
Attribute Name Description
cal_parms
dimensioned to db_mx%cal_parms_tot
type(update_parameters) (2 attributes from calibration_data_module)
Attribute Name Description
cal_upd
dimensioned to db_mx%cal_parms
chg
type(update_conditional) (1 attribute from calibration_data_module)
Attribute Name Description
upd_cond
type(soft_calibration_codes) (1 attribute from calibration_data_module)
Attribute Name Description
cal_codes
integer (17 attributes from hydrograph_module)
Attribute Name Description
mhyd
none |max number of hydrographs
Read more…
mcmd
|
inum2
none |inflow hydrograph storage location number
Read more…
jrch
none |reach number
Read more…
jrchq
|
nmbr_cbn_tests
none |number of soil carbon tests
Read more…
ncell
!number of gwflow cells
num_active
!number of active cells
gwflag_day
!flag for writing daily mass balance file
gwflag_yr
!flag for writing yearly mass balance file
maxint
number of intervals in hydrograph for degradation
ndays
ndays_leap
isep
|
ilu
|
ulu
|
iwgen
|
type(soilayer) (1 attribute from soil_module)
Attribute Name Description
layer1
type(soil_physical_properties) (1 attribute from soil_module)
Attribute Name Description
phys1
type(soil_carbon_test) (1 attribute from soil_module)
Attribute Name Description
sol_cbn_test
type(soil_profile) (1 attribute from soil_module)
Attribute Name Description
soil
type(water_body) (5 attributes from water_body_module)
Attribute Name Description
wbodz
res_wat_d
res_wat_m
res_wat_y
res_wat_a
real (7 attributes from gwflow_module)
Attribute Name Description
gw_time_step
days !flow solution time step
Read more…
wtemp
stream water temperature C
peakrate
sed_reduc_t
no3_reduc_kg
cal_adj
yrs_print
type(data_files_max_elements) (1 attribute from maximum_data_module)
Attribute Name Description
db_mx
character(len=29) (1 attribute from time_module)
Attribute Name Description
cal_sim
character(len=1) (1 attribute from hru_module)
Attribute Name Description
timest
|
I/O Operations
Unconditional Operations
Unit unit_out_gw
Operation Details Variable Defaults Line
write write(out_gw,*) 'gwflow subroutine called:',time%yrc,time%day - 166
if (hru_pump_flag == 1) (line 207)
Unit unit_out_hru_pump_obs
Operation Details Variable Defaults Line
write write(out_hru_pump_obs,119) time%yrc,time%day, (hru_pump_obs(i),i=1,num_hru_pump_obs) - 212
if (gw_solute_flag == 1) (line 252)
Unit unit_out_tile_cells
Operation Details Variable Defaults Line
write write(out_tile_cells,102) time%day,time%yrc, (sum_tile(i),i=1,gw_tile_num_group), (c_tile(i,1),i=1,gw_tile_num_group), (c_tile(i,2),i=1,gw_tile_num_group) - 256
write write(out_tile_cells,102) time%day,time%yrc, (sum_tile(i),i=1,gw_tile_num_group) - 259
Unit unit_out_gwconc
Operation Details Variable Defaults Line
write write(out_gwconc,*) gwsol_nm(s),'concentration for:',time%yrc,time%day - 639
Unit unit_out_gwobs_sol
Operation Details Variable Defaults Line
write write(out_gwobs_sol,119) time%yrc,time%day,(gw_obs_solute(k,1),k=1,gw_num_obs_wells), (gw_obs_solute(k,2),k=1,gw_num_obs_wells) - 689
Unit unit_out_conc_mo
Operation Details Variable Defaults Line
write write(out_conc_mo,*) time%yrc,time%mo - 1057
write write(out_conc_mo,*) gwsol_nm(s) - 1064
Unit unit_out_conc_yr
Operation Details Variable Defaults Line
write write(out_conc_yr,*) time%yrc - 1126
write write(out_conc_yr,*) gwsol_nm(s) - 1133
Unit unit_out_gw_rech
Operation Details Variable Defaults Line
write write(out_gw_rech,*) 'Recharge for year (m3/day):',time%yrc - 1203
Unit unit_out_sol_rech
Operation Details Variable Defaults Line
write write(out_sol_rech,*) gwsol_nm(s),'recharge flux for year (kg/day):',time%yrc - 1222
Unit unit_out_sol_gwsw
Operation Details Variable Defaults Line
write write(out_sol_gwsw,*) gwsol_nm(s),'gw-channel flux for year (kg/day):',time%yrc - 1279
Unit unit_out_sol_satx
Operation Details Variable Defaults Line
write write(out_sol_satx,*) gwsol_nm(s),'sat. excess flux for year (kg/day):',time%yrc - 1319
Unit unit_out_sol_soil
Operation Details Variable Defaults Line
write write(out_sol_soil,*) gwsol_nm(s),'gw-->soil flux for year (kg/day):',time%yrc - 1360
Unit unit_out_sol_tile
Operation Details Variable Defaults Line
write write(out_sol_tile,*) gwsol_nm(s),'tile drain flux for year (kg/day):',time%yrc - 1419
Unit unit_out_sol_ppag
Operation Details Variable Defaults Line
write write(out_sol_ppag,*) gwsol_nm(s),'ag pumping flux for year (kg/day):',time%yrc - 1459
Unit unit_out_sol_ppex
Operation Details Variable Defaults Line
write write(out_sol_ppex,*) gwsol_nm(s),'ex pumping flux for year (kg/day):',time%yrc - 1522
Unit unit_out_sol_resv
Operation Details Variable Defaults Line
write write(out_sol_resv,*) gwsol_nm(s),'gw-reservoir flux for year (kg/day):',time%yrc - 1563
Unit unit_out_sol_wetl
Operation Details Variable Defaults Line
write write(out_sol_wetl,*) gwsol_nm(s),'gw-wetland flux for year (kg/day):',time%yrc - 1604
Unit unit_out_sol_canl
Operation Details Variable Defaults Line
write write(out_sol_canl,*) gwsol_nm(s),'gw-canal flux for year (kg/day):',time%yrc - 1645
Unit unit_out_sol_fpln
Operation Details Variable Defaults Line
write write(out_sol_fpln,*) gwsol_nm(s),'gw-floodplain flux for year (kg/day):',time%yrc - 1686
Unit unit_out_sol_rcti
Operation Details Variable Defaults Line
write write(out_sol_rcti,*) gwsol_nm(s),'chem. reaction flux for year (kg/day):',time%yrc - 1709
Unit unit_out_sol_rcto
Operation Details Variable Defaults Line
write write(out_sol_rcto,*) gwsol_nm(s),'chem. reaction flux for year (kg/day):',time%yrc - 1731
Unit unit_out_sol_minl
Operation Details Variable Defaults Line
write write(out_sol_minl,*) gwsol_nm(s),'mineral dissolved mass for year (kg/day):',time%yrc - 1753
Unit unit_out_sol_sorb
Operation Details Variable Defaults Line
write write(out_sol_sorb,*) gwsol_nm(s),'sorption flux for year (kg/day):',time%yrc - 1775
if (gw_output_yr(gw_output_index).eq.time%yrc .and. gw_output_day(gw_output_index).eq.time%day) (line 619)
Unit unit_out_gwheads
Operation Details Variable Defaults Line
write write(out_gwheads,*) 'Groundwater Head for:',time%yrc,time%day - 620
if (cell_id_usg(i,j) > 0) (line 625)
Unit unit_out_gwheads
Operation Details Variable Defaults Line
write write(out_gwheads,100) (grid_val(i,j),j=1,grid_ncol) - 631
write write(out_gwheads,120) (gw_state(i)%head,i=1,ncell) - 634
write write(out_gwheads,*) - 636
Unit unit_out_gwconc
Operation Details Variable Defaults Line
write write(out_gwconc,101) (grid_val(i,j),j=1,grid_ncol) - 650
write write(out_gwconc,120) (gwsol_state(i)%solute(s)%conc,i=1,ncell) - 653
write write(out_gwconc,*) - 655
Unit unit_out_head_mo
Operation Details Variable Defaults Line
write write(out_head_mo,100) (grid_val(i,j),j=1,grid_ncol) - 1045
write write(out_head_mo,121) (gw_state(i)%hdmo,i=1,ncell) - 1048
write write(out_head_mo,*) - 1050
Unit unit_out_conc_mo
Operation Details Variable Defaults Line
write write(out_conc_mo,101) (grid_val(i,j),j=1,grid_ncol) - 1075
write write(out_conc_mo,121) (gwsol_state(i)%solute(s)%cnmo,i=1,ncell) - 1078
write write(out_conc_mo,*) - 1085
Unit unit_out_head_yr
Operation Details Variable Defaults Line
write write(out_head_yr,100) (grid_val(i,j),j=1,grid_ncol) - 1114
write write(out_head_yr,121) (gw_state(i)%hdyr,i=1,ncell) - 1117
write write(out_head_yr,*) - 1119
Unit unit_out_conc_yr
Operation Details Variable Defaults Line
write write(out_conc_yr,101) (grid_val(i,j),j=1,grid_ncol) - 1144
write write(out_conc_yr,121) (gwsol_state(i)%solute(s)%cnyr,i=1,ncell) - 1147
write write(out_conc_yr,*) - 1154
Unit unit_out_gw_rech
Operation Details Variable Defaults Line
write write(out_gw_rech,101) (grid_val(i,j),j=1,grid_ncol) - 1214
write write(out_gw_rech,121) (gw_ss_sum(i)%rech,i=1,ncell) - 1217
write write(out_gw_rech,*) - 1219
Unit unit_out_sol_rech
Operation Details Variable Defaults Line
write write(out_sol_rech,101) (grid_val(i,j),j=1,grid_ncol) - 1233
write write(out_sol_rech,121) (gwsol_ss_sum(i)%solute(s)%rech,i=1,ncell) - 1236
write write(out_sol_rech,*) - 1238
Unit unit_out_gw_et
Operation Details Variable Defaults Line
write write(out_gw_et,*) 'Groundwater ET for year:',time%yrc - 1242
write write(out_gw_et,101) (grid_val(i,j),j=1,grid_ncol) - 1253
write write(out_gw_et,121) (gw_ss_sum(i)%gwet,i=1,ncell) - 1256
write write(out_gw_et,*) - 1258
Unit unit_out_gwsw
Operation Details Variable Defaults Line
write write(out_gwsw,*) 'GW-SW Exchange Rates for year:',time%yrc - 1260
write write(out_gwsw,101) (grid_val(i,j),j=1,grid_ncol) - 1271
write write(out_gwsw,121) (gw_ss_sum(i)%gwsw,i=1,ncell) - 1274
write write(out_gwsw,*) - 1276
Unit unit_out_sol_gwsw
Operation Details Variable Defaults Line
write write(out_sol_gwsw,101) (grid_val(i,j),j=1,grid_ncol) - 1290
write write(out_sol_gwsw,121) (gwsol_ss_sum(i)%solute(s)%gwsw,i=1,ncell) - 1293
write write(out_sol_gwsw,*) - 1295
Unit unit_out_gw_satex
Operation Details Variable Defaults Line
write write(out_gw_satex,101) (grid_val(i,j),j=1,grid_ncol) - 1311
write write(out_gw_satex,121) (gw_ss_sum(i)%satx,i=1,ncell) - 1314
write write(out_gw_satex,*) - 1316
Unit unit_out_sol_satx
Operation Details Variable Defaults Line
write write(out_sol_satx,101) (grid_val(i,j),j=1,grid_ncol) - 1330
write write(out_sol_satx,121) (gwsol_ss_sum(i)%solute(s)%satx,i=1,ncell) - 1333
write write(out_sol_satx,*) - 1335
Unit unit_out_gw_soil
Operation Details Variable Defaults Line
write write(out_gw_soil,101) (grid_val(i,j),j=1,grid_ncol) - 1352
write write(out_gw_soil,121) (gw_ss_sum(i)%soil,i=1,ncell) - 1355
write write(out_gw_soil,*) - 1357
Unit unit_out_sol_soil
Operation Details Variable Defaults Line
write write(out_sol_soil,101) (grid_val(i,j),j=1,grid_ncol) - 1371
write write(out_sol_soil,121) (gwsol_ss_sum(i)%solute(s)%soil,i=1,ncell) - 1374
write write(out_sol_soil,*) - 1376
Unit unit_out_lateral
Operation Details Variable Defaults Line
write write(out_lateral,*) 'Lateral flow for year:',time%yrc - 1381
write write(out_lateral,101) (grid_val(i,j),j=1,grid_ncol) - 1392
write write(out_lateral,121) (gw_ss_sum(i)%latl,i=1,ncell) - 1395
write write(out_lateral,*) - 1397
Unit unit_out_gw_tile
Operation Details Variable Defaults Line
write write(out_gw_tile,101) (grid_val(i,j),j=1,grid_ncol) - 1411
write write(out_gw_tile,121) (gw_ss_sum(i)%tile,i=1,ncell) - 1414
write write(out_gw_tile,*) - 1416
Unit unit_out_sol_tile
Operation Details Variable Defaults Line
write write(out_sol_tile,101) (grid_val(i,j),j=1,grid_ncol) - 1430
write write(out_sol_tile,121) (gwsol_ss_sum(i)%solute(s)%tile,i=1,ncell) - 1433
write write(out_sol_tile,*) - 1435
Unit unit_out_gw_pumpag
Operation Details Variable Defaults Line
write write(out_gw_pumpag,*) 'Pumping rate for year (m3/day):',time%yrc - 1440
write write(out_gw_pumpag,101) (grid_val(i,j),j=1,grid_ncol) - 1451
write write(out_gw_pumpag,121) (gw_ss_sum(i)%ppag,i=1,ncell) - 1454
write write(out_gw_pumpag,*) - 1456
Unit unit_out_sol_ppag
Operation Details Variable Defaults Line
write write(out_sol_ppag,101) (grid_val(i,j),j=1,grid_ncol) - 1470
write write(out_sol_ppag,121) (gwsol_ss_sum(i)%solute(s)%ppag,i=1,ncell) - 1473
write write(out_sol_ppag,*) - 1475
Unit unit_out_gw_pumpdef
Operation Details Variable Defaults Line
write write(out_gw_pumpdef,*) 'Pumping rate not satisfied for year (m3/day):',time%yrc - 1484
write write(out_gw_pumpdef,101) (grid_val(i,j),j=1,grid_ncol) - 1495
write write(out_gw_pumpdef,121) (gw_ss_sum(i)%ppdf,i=1,ncell) - 1498
write write(out_gw_pumpdef,*) - 1500
Unit unit_out_gw_pumpex
Operation Details Variable Defaults Line
write write(out_gw_pumpex,101) (grid_val(i,j),j=1,grid_ncol) - 1514
write write(out_gw_pumpex,121) (gw_ss_sum(i)%ppex,i=1,ncell) - 1517
write write(out_gw_pumpex,*) - 1519
Unit unit_out_sol_ppex
Operation Details Variable Defaults Line
write write(out_sol_ppex,101) (grid_val(i,j),j=1,grid_ncol) - 1533
write write(out_sol_ppex,121) (gwsol_ss_sum(i)%solute(s)%ppex,i=1,ncell) - 1536
write write(out_sol_ppex,*) - 1538
Unit unit_out_gw_res
Operation Details Variable Defaults Line
write write(out_gw_res,101) (grid_val(i,j),j=1,grid_ncol) - 1555
write write(out_gw_res,121) (gw_ss_sum(i)%resv,i=1,ncell) - 1558
write write(out_gw_res,*) - 1560
Unit unit_out_sol_resv
Operation Details Variable Defaults Line
write write(out_sol_resv,101) (grid_val(i,j),j=1,grid_ncol) - 1574
write write(out_sol_resv,121) (gwsol_ss_sum(i)%solute(s)%resv,i=1,ncell) - 1577
write write(out_sol_resv,*) - 1579
Unit unit_out_gw_wet
Operation Details Variable Defaults Line
write write(out_gw_wet,101) (grid_val(i,j),j=1,grid_ncol) - 1596
write write(out_gw_wet,121) (gw_ss_sum(i)%wetl,i=1,ncell) - 1599
write write(out_gw_wet,*) - 1601
Unit unit_out_sol_wetl
Operation Details Variable Defaults Line
write write(out_sol_wetl,101) (grid_val(i,j),j=1,grid_ncol) - 1615
write write(out_sol_wetl,121) (gwsol_ss_sum(i)%solute(s)%wetl,i=1,ncell) - 1618
write write(out_sol_wetl,*) - 1620
Unit unit_out_gw_canal
Operation Details Variable Defaults Line
write write(out_gw_canal,101) (grid_val(i,j),j=1,grid_ncol) - 1637
write write(out_gw_canal,121) (gw_ss_sum(i)%canl,i=1,ncell) - 1640
write write(out_gw_canal,*) - 1642
Unit unit_out_sol_canl
Operation Details Variable Defaults Line
write write(out_sol_canl,101) (grid_val(i,j),j=1,grid_ncol) - 1656
write write(out_sol_canl,121) (gwsol_ss_sum(i)%solute(s)%canl,i=1,ncell) - 1659
write write(out_sol_canl,*) - 1661
Unit unit_out_gw_fp
Operation Details Variable Defaults Line
write write(out_gw_fp,101) (grid_val(i,j),j=1,grid_ncol) - 1678
write write(out_gw_fp,121) (gw_ss_sum(i)%fpln,i=1,ncell) - 1681
write write(out_gw_fp,*) - 1683
Unit unit_out_sol_fpln
Operation Details Variable Defaults Line
write write(out_sol_fpln,101) (grid_val(i,j),j=1,grid_ncol) - 1697
write write(out_sol_fpln,121) (gwsol_ss_sum(i)%solute(s)%fpln,i=1,ncell) - 1700
write write(out_sol_fpln,*) - 1702
Unit unit_out_sol_rcti
Operation Details Variable Defaults Line
write write(out_sol_rcti,101) (grid_val(i,j),j=1,grid_ncol) - 1720
write write(out_sol_rcti,121) (gwsol_ss_sum(i)%solute(s)%rcti,i=1,ncell) - 1723
write write(out_sol_rcti,*) - 1725
Unit unit_out_sol_rcto
Operation Details Variable Defaults Line
write write(out_sol_rcto,101) (grid_val(i,j),j=1,grid_ncol) - 1742
write write(out_sol_rcto,121) (gwsol_ss_sum(i)%solute(s)%rcto,i=1,ncell) - 1745
write write(out_sol_rcto,*) - 1747
Unit unit_out_sol_minl
Operation Details Variable Defaults Line
write write(out_sol_minl,101) (grid_val(i,j),j=1,grid_ncol) - 1764
write write(out_sol_minl,121) (gwsol_ss_sum(i)%solute(s)%minl,i=1,ncell) - 1767
write write(out_sol_minl,*) - 1769
Unit unit_out_sol_sorb
Operation Details Variable Defaults Line
write write(out_sol_sorb,101) (grid_val(i,j),j=1,grid_ncol) - 1786
write write(out_sol_sorb,121) (gwsol_ss_sum(i)%solute(s)%sorb,i=1,ncell) - 1789
write write(out_sol_sorb,*) - 1791
if (usgs_obs == 1) (line 680)
Unit unit_out_gwobs
Operation Details Variable Defaults Line
write write(out_gwobs,119) time%yrc,time%day,(gw_obs_head(k),k=1,gw_num_obs_wells) - 686
if (gwflag_day.eq.1) (line 862)
Unit unit_out_gwbal
Operation Details Variable Defaults Line
write write(out_gwbal,102) time%yrc,time%day,gw_time_step,vbef_grid,vaft_grid,rech_grid,gwet_grid,gwsw_grid,swgw_grid, satx_grid,soil_grid,latl_grid,bndr_grid,ppag_grid,ppex_grid, tile_grid,resv_grid,wetl_grid,canl_grid,fpln_grid, mass_error,frac_sat,depth_wt_avg,ppdf_grid - 866
if (gwflag_day == 1) (line 966)
Unit unit_out_solbal_dy+s
Operation Details Variable Defaults Line
write write(out_solbal_dy+s,102) time%yrc,time%day,gw_time_step, sol_grid_mbef,sol_grid_maft,sol_grid_rech,sol_grid_gwsw,sol_grid_swgw, sol_grid_satx,sol_grid_soil,sol_grid_advn,sol_grid_disp, sol_grid_rcti,sol_grid_rcto,sol_grid_minl, sol_grid_sorb,sol_grid_ppag,sol_grid_ppex,sol_grid_tile,sol_grid_resv, sol_grid_wetl,sol_grid_canl,sol_grid_fpln, mass_error - 973
if (nat_model == 1) (line 1024)
Unit unit_out_huc12wb_mo
Operation Details Variable Defaults Line
write write(out_huc12wb_mo,125) time%yrc,time%mo,huc12(n),(gw_huc12_wb_mo(i,n),i=1,15) - 1026
Unit unit_out_head_mo
Operation Details Variable Defaults Line
write write(out_head_mo,*) time%yrc,time%mo - 1034
Unit unit_out_huc12wb
Operation Details Variable Defaults Line
write write(out_huc12wb,112) huc12(n),(gw_huc12_wb(i,n),i=1,15) - 2416
if (time%end_yr == 1) (line 1097)
Unit unit_out_head_yr
Operation Details Variable Defaults Line
write write(out_head_yr,*) time%yrc - 1103
if (gw_satx_flag.eq.1) (line 1299)
Unit unit_out_gw_satex
Operation Details Variable Defaults Line
write write(out_gw_satex,*) 'Saturation Excess Volumes for:',time%yrc - 1300
if (gw_soil_flag.eq.1) (line 1340)
Unit unit_out_gw_soil
Operation Details Variable Defaults Line
write write(out_gw_soil,*) 'Groundwater --> Soil Transfer for:',time%yrc - 1341
if (gw_tile_flag == 1) (line 1399)
Unit unit_out_gw_tile
Operation Details Variable Defaults Line
write write(out_gw_tile,*) 'Tile Drain Outflow Volumes for:',time%yrc - 1400
if (gw_pumpex_flag == 1) (line 1502)
Unit unit_out_gw_pumpex
Operation Details Variable Defaults Line
write write(out_gw_pumpex,*) 'Pumping rate for year (m3/day):',time%yrc - 1503
if (gw_res_flag == 1) (line 1543)
Unit unit_out_gw_res
Operation Details Variable Defaults Line
write write(out_gw_res,*) 'Groundwater-Reservoir Exchange Volumes for:',time%yrc - 1544
if (gw_wet_flag == 1) (line 1584)
Unit unit_out_gw_wet
Operation Details Variable Defaults Line
write write(out_gw_wet,*) 'Groundwater outflow to wetlands for:',time%yrc - 1585
if (gw_canal_flag == 1) (line 1625)
Unit unit_out_gw_canal
Operation Details Variable Defaults Line
write write(out_gw_canal,*) 'Groundwater-Canal Exchange Volumes for:',time%yrc - 1626
if (gw_fp_flag == 1) (line 1666)
Unit unit_out_gw_fp
Operation Details Variable Defaults Line
write write(out_gw_fp,*) 'Floodplain Exchange Volumes for:',time%yrc - 1667
if (gwflag_yr.eq.1) (line 1838)
Unit unit_out_gwbal_yr
Operation Details Variable Defaults Line
write write(out_gwbal_yr,105) time%yrc, ss_grid_yr%chng,ss_grid_yr%rech,ss_grid_yr%gwet,ss_grid_yr%gwsw,ss_grid_yr%swgw, ss_grid_yr%satx,ss_grid_yr%soil,ss_grid_yr%latl,ss_grid_yr%bndr,ss_grid_yr%ppag, ss_grid_yr%ppex,ss_grid_yr%tile,ss_grid_yr%resv,ss_grid_yr%wetl,ss_grid_yr%canl, ss_grid_yr%fpln,ss_grid_yr%ppdf - 1843
Unit unit_out_solbal_yr+s
Operation Details Variable Defaults Line
write write(out_solbal_yr+s,105) time%yrc, sol_grid_chng_yr,sol_grid_rech_yr,sol_grid_gwsw_yr,sol_grid_swgw_yr,sol_grid_satx_yr, sol_grid_soil_yr,sol_grid_advn_yr,sol_grid_disp_yr, sol_grid_rcti_yr,sol_grid_rcto_yr,sol_grid_minl_yr,sol_grid_sorb_yr, sol_grid_ppag_yr,sol_grid_ppex_yr,sol_grid_tile_yr,sol_grid_resv_yr,sol_grid_wetl_yr, sol_grid_canl_yr,sol_grid_fpln_yr - 1890
if (time%yrc == time%yrc_end .and. time%day == time%day_end) (line 1919)
Unit unit_out_hru_pump_mo
Operation Details Variable Defaults Line
write write(out_hru_pump_mo,105) i,(hru_pump_mo_all(i,j),j=1,num_months) - 1924
Unit unit_out_hru_pump_yr
Operation Details Variable Defaults Line
write write(out_hru_pump_yr,105) i,(hru_pump_yr_all(i,j),j=1,time%nbyr) - 1925
if (gwflag_aa.eq.1) (line 1946)
Unit unit_out_gwbal_aa
Operation Details Variable Defaults Line
write write(out_gwbal_aa,105) time%yrc, ss_grid_tt%chng,ss_grid_tt%rech,ss_grid_tt%gwet,ss_grid_tt%gwsw,ss_grid_tt%swgw, ss_grid_tt%satx,ss_grid_tt%soil,ss_grid_tt%latl,ss_grid_tt%bndr,ss_grid_tt%ppag, ss_grid_tt%ppex,ss_grid_tt%tile,ss_grid_tt%resv,ss_grid_tt%wetl,ss_grid_tt%canl, ss_grid_tt%fpln,ss_grid_tt%ppdf - 1951
Unit unit_out_solbal_aa+s
Operation Details Variable Defaults Line
write write(out_solbal_aa+s,105) time%yrc, sol_grid_chng_tt(s),sol_grid_rech_tt(s),sol_grid_gwsw_tt(s),sol_grid_swgw_tt(s), sol_grid_satx_tt(s),sol_grid_soil_tt(s),sol_grid_advn_tt(s),sol_grid_disp_tt(s), sol_grid_rcti_tt(s),sol_grid_rcto_tt(s),sol_grid_minl_tt(s),sol_grid_sorb_tt(s), sol_grid_ppag_tt(s),sol_grid_ppex_tt(s),sol_grid_tile_tt(s),sol_grid_resv_tt(s), sol_grid_wetl_tt(s),sol_grid_canl_tt(s),sol_grid_fpln_tt(s) - 1982
if (val_count.gt.0) (line 2021)
Unit unit_out_gwobs_usgs
Operation Details Variable Defaults Line
write write(out_gwobs_usgs,*) 'MAE (m), SAT/MAE, #Meas' - 2031
write write(out_gwobs_usgs,*) head_mae,sat_div,num_gw_meas - 2032
write write(out_gwobs_usgs,*) - 2033
write write(out_gwobs_usgs,*) 'MAE (m), SAT/MAE, #Meas per well' - 2034
write write(out_gwobs_usgs,*) 'Observed values - Simulated values' - 2035
write write(out_gwobs_usgs,111) usgs_id(k),head_mae_well(k,1),sat_div_well(k,1),num_gw_meas_well(k,1) - 2037
write write(out_gwobs_usgs,*) 'MAE_calib,MAE_test,SAT/MAE_calib,SAT_MAE_test,#calib,#test' - 2124
write write(out_gwobs_usgs,115) head_mae_calb,head_mae_test,sat_div_calb,sat_div_test,num_gw_meas_calb,num_gw_meas_test - 2125
write write(out_gwobs_usgs,*) - 2126
write write(out_gwobs_usgs,*) 'MAE (m), SAT/MAE per well, #Meas per well' - 2127
write write(out_gwobs_usgs,*) 'Observed values - Simulated values' - 2128
write write(out_gwobs_usgs,116) usgs_id(k),head_mae_well(k,1),head_mae_well(k,2),sat_div_well(k,1),sat_div_well(k,2), num_gw_meas_well(k,1),num_gw_meas_well(k,2) - 2131
write write(out_gwobs_usgs,*) - 2134
write write(out_gwobs_usgs,*) 'Year, Well, Row, Col, Obs, Sim, SatThick' - 2135
write write(out_gwobs_usgs,110) write_yr,usgs_id(k),gw_obs_cells(k),usgs_head_vals(k,usgs_yr), sim_head_vals(k,j),sim_sat_vals(k,j) - 2141
if (obs_flow_vals(i,j).gt.0) (line 2225)
Unit unit_out_strobs
Operation Details Variable Defaults Line
write write(out_strobs,*) 'Statistics for specified channels' - 2236
write write(out_strobs,*) 'Channel, count, NSE, NSE1, NNSE, PBIAS, KGE' - 2237
write write(out_strobs,114) obs_channels(i),month_count,stream_nse(i,1),stream_nse1(i,1),stream_nnse(i,1), stream_pbias(i,1),stream_kg(i,1) - 2240
if (obs_flow_vals(i,j+num_months_calb).gt.0) (line 2380)
Unit unit_out_strobs
Operation Details Variable Defaults Line
write write(out_strobs,*) 'Statistics for specified channels (calib/testing)' - 2391
write write(out_strobs,*) 'Channel, count, NSE, NSE1, NNSE, PBIAS, KGE' - 2392
write write(out_strobs,114) obs_channels(i),month_count_calb,stream_nse(i,1),stream_nse1(i,1),stream_nnse(i,1), stream_pbias(i,1),stream_kg(i,1) - 2395
write write(out_strobs,114) obs_channels(i),month_count_test,stream_nse(i,2),stream_nse1(i,2),stream_nnse(i,2), stream_pbias(i,2),stream_kg(i,2) - 2397
write write(out_strobs,*) - 2400
write write(out_strobs,*) 'Monthly values for each specified channel' - 2401
write write(out_strobs,*) 'Channel:',obs_channels(i) - 2403
write write(out_strobs,*) 'Month Observed Simulated' - 2404
write write(out_strobs,113) j,obs_flow_vals(i,j),sim_flow_vals(i,j) - 2406
write write(out_strobs,*) - 2408
Allocations
if (gw_num_obs_chan.gt.0) (line 2150)
Operation Variables Details Line
allocate stream_nse(gw_num_obs_chan,2 allocate (stream_nse(gw_num_obs_chan,2), source = 0.) 2152
allocate stream_nse1(gw_num_obs_chan,2 allocate (stream_nse1(gw_num_obs_chan,2), source = 0.) 2153
allocate stream_nnse(gw_num_obs_chan,2 allocate (stream_nnse(gw_num_obs_chan,2), source = 0.) 2154
allocate stream_kg(gw_num_obs_chan,2 allocate (stream_kg(gw_num_obs_chan,2), source = 0.) 2155
allocate stream_pbias(gw_num_obs_chan,2 allocate (stream_pbias(gw_num_obs_chan,2), source = 0.) 2156
if (stream_obs == 1) (line 2422)
Operation Variables Details Line
deallocate stream_nse deallocate(stream_nse) 2423
deallocate stream_nse1 deallocate(stream_nse1) 2424
deallocate stream_nnse deallocate(stream_nnse) 2425
deallocate stream_kg deallocate(stream_kg) 2426
deallocate stream_pbias deallocate(stream_pbias) 2427
Calls
Call graph
gwflow_simulate calls 1000, 10000, 50, gwflow_canl_out, gwflow_chem, gwflow_gwet, gwflow_ppex, gwflow_rech