proc_res – SWAT+
proc_res Subroutine
19 statements
Source File
subroutine proc_res()
Uses
hydrograph_module
allocate and initialize reservoir variables Osvaldo
Arguments
None
Calls
Call graph
proc_res calls res_allo, res_initial, res_objects, res_read, res_read_conds, res_read_csdb, res_read_hyd, res_read_init, res_read_nut, res_read_salt_cs, res_read_saltdb, res_read_sed