proc_read – SWAT+
proc_read Subroutine
39 statements
Source File
subroutine proc_read()
read pesticide metabolites
Arguments
None
Calls
Call graph
proc_read calls ch_read_temp, cli_read_atmodep, cli_read_atmodep_cs, cli_read_atmodep_salt, cli_staread, constit_db_read, cs_aqu_read, cs_fert_read, cs_hru_read, cs_irr_read, cs_plant_read, cs_reactions_read, cs_uptake_read, cs_urban_read, field_read, hmet_hru_aqu_read, hydrol_read, path_hru_aqu_read, pest_hru_aqu_read, pest_metabolite_read, salt_aqu_read, salt_fert_read, salt_hru_read, salt_irr_read, salt_plant_read, salt_roadsalt_read, salt_uptake_read, salt_urban_read, snowdb_read, soil_db_read, soil_lte_db_read, soil_plant_init, soil_plant_init_cs, solt_db_read, topo_read