proc_open – SWAT+
proc_open Subroutine
21 statements
Source File
subroutine proc_open()
write headers in output files
Arguments
None
Calls
Call graph
proc_open calls header_aquifer, header_channel, header_const, header_hyd, header_lu_change, header_mgt, header_path, header_pest, header_reservoir, header_salt, header_sd_channel, header_snutc, header_water_allocation, header_wetland, header_write, header_yield, output_landscape_init