actions – TestDataProject
actions Subroutine
831 statements
Source File
subroutine actions(ob_cur, ob_num, idtbl)
Purpose
n/a
Stack Flow
Called From
hru_control
mallo_control
sd_channel_control
sd_channel_control2
sd_channel_control3
time_control
wallo_demand
Procedures that call this Subroutine. This shows the call stack back to the main program.
Calls
amax1
amin1
pl_fert_wet
pl_fert
pl_manure
salt_fert
cs_fert
mgt_newtillmix
mgt_transplant
mgt_harvbiomass
mgt_harvgrain
mgt_harvresidue
mgt_harvtuber
mgt_killop
pest_apply
pl_graze
wet_initial
mgt_newtillmix_wet
hru_fr_change
hru_lum_init
plant_init
cn2_init
structure_set_parms
pl_burnop
curno
Procedures called by this Subroutine.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ob_cur
integer, intent(in) :: ob_num
integer, intent(in) :: idtbl
Uses
landuse_data_module
tillage_data_module
aquifer_module
plant_module
mgt_operations_module
hydrograph_module
organic_mineral_mass_module
constituent_mass_module
tiles_data_module
manure_allocation_module
plant_data_module
septic_data_module
soil_module
basin_module
time_module
climate_module
water_allocation_module
output_landscape_module
calibration_data_module
water_body_module
maximum_data_module
hru_module
reservoir_module
reservoir_data_module
sd_channel_module
hru_lte_module
conditional_module
fertilizer_data_module
Outside Variables and Types
tillage_data_module
type(tillage_db) (2 arrays)
Variable Declaration Description Line Numbers
:: tilldb (2 components)
Component Line Numbers
character(len=16), public :: tillnm = " " 336, 725, 841
real, public :: effmix = 0. 338
None 336, 725, 841
aquifer_module
type(aquifer_data_parameters) (1 array)
Variable Declaration Description Line Numbers
:: aqu_prm (1 component)
Component Line Numbers
real, public :: area_ha = 0. 193
None 193
type(aquifer_dynamic) (1 array)
Variable Declaration Description Line Numbers
:: aqu_d (1 component)
Component Line Numbers
real, public :: stor = 0. 193, 205, 206
None 193, 205, 206
plant_module
integer (8 arrays)
Variable Declaration Description Line Numbers
public, :: basin_plants
number of different plants in the basin
-
:: pcom None 115, 140, 172, 255, 266, 289, 299, 314, 330, 340, 350, 393, 403, 478, 488, 509, 519, 595, 640, 653, 671, 719, 722, 825, 852, 1090, 1104, 1113, 1125, 1131, 1142
type(plant_community) (26 arrays)
Variable Declaration Description Line Numbers
:: pcom (26 components)
Component Line Numbers
type(auto_operations), public,dimension(:), allocatable :: dtbl -
type(plant_status), public,dimension(:), allocatable :: plcur -
type(auto_operations), public,dimension(:), allocatable :: dtbl -
integer, public :: days_irr = -366 257, 633
type(fertilize_future), public,dimension(:), allocatable :: fert_fut -
integer, public :: pcomdb = 0 352, 405, 489, 521
integer, public :: days_plant = -366 353, 626
integer, public :: npl = 0 364, 417, 491, 533, 888, 1092, 1132
type(plant_status), public,dimension(:), allocatable :: plcur -
type(plant_status), public,dimension(:), allocatable :: plcur -
type(plant_growth), public,dimension(:), allocatable :: plg -
type(plant_status), public,dimension(:), allocatable :: plcur -
integer, public :: days_harv = -366 406, 522, 612
type(plant_status), public,dimension(:), allocatable :: plcur -
type(plant_status), public,dimension(:), allocatable :: plcur -
type(plant_status), public,dimension(:), allocatable :: plcur -
type(plant_stress), public,dimension(:), allocatable :: plstr -
type(plant_stress), public,dimension(:), allocatable :: plstr -
type(plant_stress), public,dimension(:), allocatable :: plstr -
type(plant_stress), public,dimension(:), allocatable :: plstr -
type(plant_stress), public,dimension(:), allocatable :: plstr -
integer, public :: days_kill = -366 490, 619
character(len=40), public :: last_kill = "" 494, 560
type(plant_status), public,dimension(:), allocatable :: plcur -
integer, public :: rot_yr = 1 605
character(len=40), public,dimension(:), allocatable :: pl 890, 895, 897
None -
real (8 arrays)
Variable Declaration Description Line Numbers
:: pcom None 153, 160, 251, 276, 284, 310, 337, 377, 385, 470, 500, 506, 588, 650, 726, 1101, 1119, 1135
character(len=1) (2 arrays)
Variable Declaration Description Line Numbers
:: pcom None 369, 370, 1136
type(basin_crop_yields) (4 arrays)
Variable Declaration Description Line Numbers
:: bsn_crop_yld (2 components)
Component Line Numbers
real, public :: area_ha = 0. 453, 571
real, public :: yield = 0. 454, 572
None 453, 571
public,dimension(:), allocatable, :: bsn_crop_yld_aa -
public, :: bsn_crop_yld_z -
mgt_operations_module
type(irrigation_operation) (3 arrays)
Variable Declaration Description Line Numbers
:: irrop_db (3 components)
Component Line Numbers
real, public :: amt_mm = 25.4 146, 147, 161
real, public :: eff = 0. 146, 147, 179, 184
real, public :: surq = 0. 146, 147, 180, 181, 184, 185
None 146, 147, 161
type(puddle_operation) (3 arrays)
Variable Declaration Description Line Numbers
:: pudl_db (3 components)
Component Line Numbers
character(len=40), public :: name = "" 829
real, public :: wet_hc = 0. 835
real, public :: sed = 0. 837
None 829
type(filtstrip_operation) (1 array)
Variable Declaration Description Line Numbers
:: filtstrip_db (1 component)
Component Line Numbers
character(len=40), public :: name = "" 1019
None 1019
type(grwaterway_operation) (1 array)
Variable Declaration Description Line Numbers
:: grwaterway_db (1 component)
Component Line Numbers
character(len=40), public :: name = "" 1038
None 1038
type(bmpuser_operation) (1 array)
Variable Declaration Description Line Numbers
:: bmpuser_db (1 component)
Component Line Numbers
character(len=40), public :: name = "" 1065
None 1065
type(chemical_application_operation) (2 arrays)
Variable Declaration Description Line Numbers
:: chemapp_db (2 components)
Component Line Numbers
real, public :: surf_frac = 0. 272
real, public :: app_eff = 0. 645
None 272
type(harvest_operation) (2 arrays)
Variable Declaration Description Line Numbers
:: harvop_db (2 components)
Component Line Numbers
real, public :: bm_min = 0 422, 538
character(len=40), public :: typ = "" 424, 540
None 422, 538
type(grazing_operation) (2 arrays)
Variable Declaration Description Line Numbers
public,dimension(:), allocatable, :: grazeop_db -
public, :: graze -
type(management_ops) (1 array)
Variable Declaration Description Line Numbers
:: mgt (1 component)
Component Line Numbers
character(len=40), public :: op_char = "" 275, 283, 309, 460
None 275, 283, 309, 460
type(management_schedule) (3 arrays)
Variable Declaration Description Line Numbers
:: sched (3 components)
Component Line Numbers
character(len=40), public,dimension (:), allocatable :: auto_name 356, 357, 360, 409, 410, 413, 525, 526, 529
character(len=40), public,dimension (:), allocatable :: auto_crop 358, 411, 527
character(len=40), public,dimension (:), allocatable :: auto_crop -
None 356, 357, 360, 409, 410, 413, 525, 526, 529
unknown (1 array)
Variable Declaration Description Line Numbers
:: sched None 361, 414, 530
hydrograph_module
integer (1 array)
Variable Declaration Description Line Numbers
public, :: ich
none |object number
Read more… -
type(hyd_output) (6 arrays)
Variable Declaration Description Line Numbers
public, :: hz -
public,dimension(:), allocatable, target, :: aqu -
:: res (1 component)
Component Line Numbers
real, public :: flo = 0. 228, 229, 771, 775
None 228, 229, 771, 775
:: wet (2 components)
Component Line Numbers
real, public :: flo = 0. 272, 837
real, public :: sed = 0. 837
None 272, 837
:: ch_stor (1 component)
Component Line Numbers
real, public :: flo = 0. 211, 212
None 211, 212
type(irrigation_water_transfer) (5 arrays)
Variable Declaration Description Line Numbers
:: irrig (5 components)
Component Line Numbers
real, public :: applied = 0. 132, 146, 154, 179, 184, 198, 215, 232, 247
real, public :: demand = 0. 135, 137, 142, 182, 186, 194, 195, 200, 211, 212, 217, 228, 229, 234, 252
real, public :: runoff = 0. 147, 181, 185, 199, 216, 233
type(hyd_output), public :: water -
type(hyd_output), public :: water 222, 239
None 132, 146, 154, 179, 184, 198, 215, 232, 247
real (1 array)
Variable Declaration Description Line Numbers
:: irrig None 205
organic_mineral_mass_module
type(soil_profile_mass) (1 array)
Variable Declaration Description Line Numbers
:: soil1 (1 component)
Component Line Numbers
type(organic_mass), public,dimension(:), allocatable :: rsd -
None -
real (2 arrays)
Variable Declaration Description Line Numbers
:: soil1 None 153, 160, 251, 277, 285, 311, 338, 378, 386, 470, 500, 588, 651, 727, 1101, 1119
:: pl_mass None 153, 160, 251, 276, 284, 310, 337, 378, 386, 418, 492, 534, 650, 726, 1101, 1119
type(plant_community_mass) (3 arrays)
Variable Declaration Description Line Numbers
:: pl_mass (3 components)
Component Line Numbers
type(organic_mass), public,dimension(:), allocatable :: tot -
type(organic_mass), public,dimension(:), allocatable :: yield_tot 446, 564
type(organic_mass), public,dimension(:), allocatable :: yield_yr 447, 565
None -
type(organic_mass) (2 arrays)
Variable Declaration Description Line Numbers
:: pl_yield (1 component)
Component Line Numbers
real, public :: m = 0. 462, 471, 572, 580, 589
None 462, 471, 572, 580, 589
public,dimension(:), allocatable, :: manure
dimension to number of manures in database
-
type(fertilizer_mass) (1 array)
Variable Declaration Description Line Numbers
public,dimension(:), allocatable, :: fert
dimension to number of fertilzers in database
-
constituent_mass_module
type(constituent_mass) (3 arrays)
Variable Declaration Description Line Numbers
public,dimension (:), allocatable, :: cs_irr -
public,dimension (:), allocatable, :: cs_aqu -
public,dimension (:), allocatable, :: ch_water -
tiles_data_module
type(subsurface_drainage) (1 array)
Variable Declaration Description Line Numbers
:: sdr (1 component)
Component Line Numbers
character(len=13), public :: name = "null" 979, 992, 1011, 1030, 1050, 1058, 1076
None 979, 992, 1011, 1030, 1050, 1058, 1076
manure_allocation_module
type(manure_demand_amount) (6 arrays)
Variable Declaration Description Line Numbers
public, :: manure_amtz -
:: mallo None 114
type(manure_allocation) (5 arrays)
Variable Declaration Description Line Numbers
:: mallo (5 components)
Component Line Numbers
type(manure_demand_objects), public,dimension(:), allocatable :: dmd -
type(manure_demand_objects), public,dimension(:), allocatable :: dmd -
type(manure_demand_objects), public,dimension(:), allocatable :: dmd -
type(manure_demand_objects), public,dimension(:), allocatable :: dmd -
type(manure_demand_objects), public,dimension(:), allocatable :: dmd -
None -
integer (3 arrays)
Variable Declaration Description Line Numbers
:: mallo None 116
real (1 array)
Variable Declaration Description Line Numbers
:: mallo None 118
plant_data_module
character(len=40) (2 arrays)
Variable Declaration Description Line Numbers
public,dimension (:), allocatable, :: plts_bsn
none |plant names simulated in current run
Read more… -
:: pcomdb None 367, 419, 493, 494, 535, 560
type(plant_db) (4 arrays)
Variable Declaration Description Line Numbers
:: pldb (4 components)
Component Line Numbers
character(len=40), public :: plantnm = "" 376, 384, 469, 499, 587
real, public :: hvsti = 0.76 696, 698
real, public :: wsyf = 0.01 696, 697
character(len=18), public :: trig = "" 1134
None 376, 384, 469, 499, 587
type(plant_community_db) (2 arrays)
Variable Declaration Description Line Numbers
:: pcomdb (2 components)
Component Line Numbers
type(plant_init_db), public,dimension(:), allocatable :: pl -
type(plant_init_db), public,dimension(:), allocatable :: pl -
None -
integer (1 array)
Variable Declaration Description Line Numbers
:: pcomdb None 366
septic_data_module
type(septic_system) (1 array)
Variable Declaration Description Line Numbers
:: sep (1 component)
Component Line Numbers
character(len=13), public :: name = "default" 1000
None 1000
soil_module
type(soil_profile) (2 arrays)
Variable Declaration Description Line Numbers
:: soil (2 components)
Component Line Numbers
real, public :: sw = 0. 153, 160, 251, 276, 284, 310, 337, 377, 386, 470, 500, 588, 650, 726, 1101, 1119
type(soilayer), public,dimension (:), allocatable :: ly -
None 153, 160, 251, 276, 284, 310, 337, 377, 386, 470, 500, 588, 650, 726, 1101, 1119
real (1 array)
Variable Declaration Description Line Numbers
:: soil None 881, 918, 934, 951, 968
basin_module
type(basin_print_codes) (1 array)
Variable Declaration Description Line Numbers
:: pco (1 component)
Component Line Numbers
character(len=1), public :: mgtout = "n" 151, 158, 249, 274, 282, 308, 335, 375, 383, 468, 498, 586, 648, 724, 1099, 1116
None 151, 158, 249, 274, 282, 308, 335, 375, 383, 468, 498, 586, 648, 724, 1099, 1116
time_module
type(time_current) (3 arrays)
Variable Declaration Description Line Numbers
:: time (3 components)
Component Line Numbers
integer, public :: yrc = 0 152, 159, 250, 275, 283, 309, 336, 376, 384, 469, 499, 587, 649, 725, 860, 884, 921, 936, 953, 970, 991, 1010, 1029, 1049, 1057, 1075, 1100, 1118
integer, public :: mo = 0 152, 159, 250, 275, 283, 309, 336, 376, 384, 469, 499, 587, 649, 725, 860, 884, 921, 936, 953, 970, 991, 1010, 1029, 1049, 1057, 1075, 1100, 1118
integer, public :: day_mo = 0 152, 159, 250, 275, 283, 309, 336, 376, 384, 469, 499, 587, 649, 725, 860, 884, 921, 936, 953, 970, 991, 1010, 1029, 1049, 1057, 1075, 1100, 1118
None 152, 159, 250, 275, 283, 309, 336, 376, 384, 469, 499, 587, 649, 725, 860, 884, 921, 936, 953, 970, 991, 1010, 1029, 1049, 1057, 1075, 1100, 1118
water_allocation_module
real (1 array)
Variable Declaration Description Line Numbers
public, :: dmd_m3
m3 |demand
Read more… -
calibration_data_module
type(soft_calibration_codes) (1 array)
Variable Declaration Description Line Numbers
:: cal_codes (1 component)
Component Line Numbers
character(len=1), public :: plt = "n" 456, 575
None 456, 575
type(soft_data_calib_plant) (4 arrays)
Variable Declaration Description Line Numbers
:: plcal (4 components)
Component Line Numbers
integer, public :: lum_num = 0 459, 577
type(pl_calib_regions), public,dimension(:), allocatable :: lum -
type(pl_calib_regions), public,dimension(:), allocatable :: lum -
type(pl_calib_regions), public,dimension(:), allocatable :: lum -
None 459, 577
type(soft_calib_pl_processes) (2 arrays)
Variable Declaration Description Line Numbers
:: plcal None -
character(len=16) (1 array)
Variable Declaration Description Line Numbers
:: plcal None 460, 578
real (2 arrays)
Variable Declaration Description Line Numbers
:: plcal None 461, 579
water_body_module
type(water_body) (2 arrays)
Variable Declaration Description Line Numbers
public, :: wbodz -
public,dimension(:), allocatable, target, :: wet_wat_d -
maximum_data_module
type(data_files_max_elements) (8 arrays)
Variable Declaration Description Line Numbers
:: db_mx (8 components)
Component Line Numbers
integer, public :: wet_dat = 0 796
integer, public :: pudl_db = 0 828
integer, public :: tillparm = 0 840
integer, public :: sdr = 0 978
integer, public :: septic = 0 999
integer, public :: filtop_db = 0 1018
integer, public :: grassop_db = 0 1037
integer, public :: bmpuserop_db = 0 1064
None 796
hru_module
integer (9 arrays)
Variable Declaration Description Line Numbers
public, :: ilu
|
-
:: hru None 737
public, :: ipl -
public, :: isol -
public, :: ihru
none |HRU number
Read more… -
type(subsurface_drainage_parameters) (1 array)
Variable Declaration Description Line Numbers
:: sdr (1 component)
Component Line Numbers
character(len=40), public :: name = "null" 979, 992, 1011, 1030, 1050, 1058, 1076
None 979, 992, 1011, 1030, 1050, 1058, 1076
type(hydrologic_response_unit) (21 arrays)
Variable Declaration Description Line Numbers
:: hru (21 components)
Component Line Numbers
real, public :: irr_hmax = 0 129, 177
real, public :: irr_hmin = 0 130, 134, 178
real, public :: area_ha = 0. 135, 142, 182, 186, 453, 454, 461, 462, 571, 572, 579, 580, 812
real, public :: irr_yr = 0. 247
integer, public :: mgt_ops = 0 355, 408, 524
integer, public :: crop_reg = 0 458, 576
integer, public :: tiledrain = 0 720, 990
type(land_use_mgt_variables), public :: lumv -
type(saturated_buffer), public :: sb -
type(saturated_buffer), public :: sb -
type(hru_databases), public :: dbs -
real, public :: wet_hc = 0. 835
integer, public :: land_use_mgt = 0 870
type(hru_databases), public :: dbs -
character(len=40), public :: land_use_mgt_c = "" 873, 874, 885
type(hru_databases), public :: dbs -
type(land_use_mgt_variables), public :: lumv -
type(land_use_mgt_variables), public :: lumv -
type(land_use_mgt_variables), public :: lumv -
type(topography), public :: topo -
type(land_use_mgt_variables), public :: lumv -
None 129, 177
real (16 arrays)
Variable Declaration Description Line Numbers
:: hru None 721, 727
public, :: qtile -
public, :: fertno3 -
public, :: fertnh3 -
public, :: fertorgn -
public, :: fertsolp -
public, :: fertorgp -
public,dimension (:), allocatable, :: sol_sumno3 -
public,dimension (:), allocatable, :: sol_sumsolp -
public,dimension (:), allocatable, :: cn2 -
public,dimension (:), allocatable, :: phubase -
type(saturated_buffer_parameters) (1 array)
Variable Declaration Description Line Numbers
:: hru None -
reservoir_module
type(reservoir) (3 arrays)
Variable Declaration Description Line Numbers
:: res_ob (3 components)
Component Line Numbers
real, public :: pvol = 0. 771
real, public :: evol = 0. 775
real, public :: weir_hgt = 0 818
None 771
type(wetland) (4 arrays)
Variable Declaration Description Line Numbers
:: wet_ob (4 components)
Component Line Numbers
real, public :: depth = 0 132, 134, 135, 179, 181, 182, 847
real, public :: weir_hgt = 0 810, 812
real, public :: pvol = 0. 812, 813, 814
real, public :: evol = 0. 813, 814
None 132, 134, 135, 179, 181, 182, 847
reservoir_data_module
type(reservoir_data) (1 array)
Variable Declaration Description Line Numbers
:: wet_dat (1 component)
Component Line Numbers
character(len=25), public :: name = "default" 797
None 797
sd_channel_module
type(swatdeg_channel_dynamic) (2 arrays)
Variable Declaration Description Line Numbers
:: sd_ch (2 components)
Component Line Numbers
real, public :: cov = 0. 1082
character(len=25), public :: order = "" 1083
None 1082
hru_lte_module
type(swatdeg_hru_dynamic) (11 arrays)
Variable Declaration Description Line Numbers
:: hlt (11 components)
Component Line Numbers
character(len=1), public :: gro = "n" 678, 706
real, public :: g = 0. 679, 707
real, public :: alai = 0. 680, 702, 708
real, public :: dm = 0. 681, 699, 701, 709
real, public :: hufh = 0. 682, 710
integer, public :: iplant = 0 690
real, public :: pet = 0. 691, 694, 712
real, public :: aet = 0. 694, 711
real, public :: yield = 0. 700
real, public :: npp = 0. 701
real, public :: lai_mx = 0. 702
None 678, 706
conditional_module
type(decision_table) (15 arrays)
Variable Declaration Description Line Numbers
:: d_tbl (15 components)
Component Line Numbers
integer, public :: acts = 0 96
integer, public :: alts = 0 98
character(len=1), public,dimension(:), allocatable :: act_hit 99
character(len=1), public,dimension(:,:), allocatable :: act_outcomes 99
type(actions_var), public,dimension(:), allocatable :: act -
type(actions_var), public,dimension(:), allocatable :: act -
type(actions_var), public,dimension(:), allocatable :: act -
integer, public,dimension(:), allocatable :: act_app 119, 270, 303, 372, 373, 644
type(actions_var), public,dimension(:), allocatable :: act -
type(actions_var), public,dimension(:), allocatable :: act -
integer, public,dimension(:), allocatable :: act_typ 141, 174, 268, 301, 331, 404, 520, 643, 662, 869, 1091
type(actions_var), public,dimension(:), allocatable :: act -
type(actions_var), public,dimension(:), allocatable :: act -
type(actions_var), public,dimension(:), allocatable :: act -
integer, public,dimension(:), allocatable :: lu_chg_mx 868
None 96
character(len=25) (4 arrays)
Variable Declaration Description Line Numbers
:: d_tbl None 106
integer (1 array)
Variable Declaration Description Line Numbers
:: d_tbl None 117, 125, 173, 190, 263, 296, 322, 327, 347, 400, 485, 516, 602, 609, 616, 623, 630, 637, 659, 675, 687, 716, 733, 764, 782, 791, 806, 823, 865, 910, 926, 941, 958, 975, 996, 1015, 1034, 1054, 1061, 1087, 1109, 1128
real (2 arrays)
Variable Declaration Description Line Numbers
:: d_tbl None 118, 129, 142, 177, 184, 185, 186, 269, 302, 430, 546, 604, 605, 611, 612, 618, 619, 625, 626, 632, 633, 645, 721, 743, 746, 749, 758, 771, 775, 810, 818, 915, 1082, 1114
character(len=40) (1 array)
Variable Declaration Description Line Numbers
:: d_tbl None 358, 361, 367, 411, 414, 419, 493, 527, 530, 535, 578, 649, 740, 767, 809, 829, 858, 861, 1114
Local Variables
Type Visibility Attributes Name Initial
integer, public :: icom = 0
integer, public :: iac = 0
integer, public :: ial = 0
integer, public :: iburn = 0
integer, public :: idtill = 0
integer, public :: ifertop = 0
integer, public :: ifrt = 0
integer, public :: ipestop = 0
integer, public :: ipst = 0
integer, public :: iharvop = 0
integer, public :: iihru = 0
integer, public :: ilu = 0
integer, public :: j = 0
integer, public :: iob = 0
integer, public :: idp = 0
integer, public :: istr = 0
integer, public :: istr1 = 0
integer, public :: iob_out = 0
integer, public :: inhyd = 0
integer, public :: ihyd_in = 0
integer, public :: icon = 0
integer, public :: iplt_bsn = 0
integer, public :: irrop = 0
integer, public :: igr = 0
integer, public :: ireg = 0
integer, public :: ilum = 0
integer, public :: isrc = 0
integer, public :: isched = 0
integer, public :: ipud = 0
integer, public :: ipdl = 0
integer, public :: ires = 0
integer, public :: idb = 0
integer, public :: imallo = 0
integer, public :: idmd = 0
integer, public :: irec = 0
integer, public :: iplt = 0
integer, public :: num_plts_cur = 0
integer, public :: hru_rcv
real, public :: hiad1 = 0.
real, public :: biomass = 0.
real, public :: frt_kg = 0.
real, public :: harveff = 0.
real, public :: wur = 0.
real, public :: frac = 0.
real, public :: rto = 0.
real, public :: rto1 = 0.
real, public :: pest_kg = 0.
real, public :: chg_par
real, public :: yield = 0.
real, public :: sumpst = 0.
real, public :: rock = 0.
real, public :: p_factor = 0.
real, public :: cn_prev = 0.
real, public :: stor_m3 = 0.
character(len=1), public :: action = ""
character(len=40), public :: lu_prev = ""
I/O
I/O files used in this subroutine.
Unit Type Filename Operations
2612 Output unit_2612
"mgt_out.txt" 16 operation(s)
3612 Output unit_3612
"lu_change_out.txt" 12 operation(s)
Control Flow
Complexity Indicators: Complex Depth: 7 Early Exits: 1
Features: DO I/O IF SELECT
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
   7 ihru, ipl, isol,  phubase, sol_sumno3, sol_sumsolp, qtile
DO iac = 1, d_tbl%acts Lines 96-1151
  97 action = "n"
DO ial = 1, d_tbl%alts Lines 98-103
IF (d_tbl%act_hit(ial) == "y" .and. d_tbl%act_outcomes(iac,ial) == "y") THEN Lines 99-102
 100 action = "y"
EXIT  101 exit
END IFLine 102
END DOLine 103
IF (action == "y") THEN Lines 105-1150
SELECT CASE (d_tbl%act(iac)%typ) Lines 106-1149
CASE ("manure_demand") Lines 109-122
 110 j = ob_cur
 111 idmd = ob_num
 112 imallo = 1
 114 mallo(imallo)%dmd(idmd)%manure_amt = manure_amtz
IF (pcom(j)%dtbl(idtbl)%num_actions(iac) <= Int(d_tbl%act(iac)%const2)) THEN Lines 115-120
 116 mallo(imallo)%dmd(idmd)%manure_amt%mallo_obj = 1
 117 mallo(imallo)%dmd(idmd)%manure_amt%src_obj = d_tbl%act(iac)%ob_num
 118 mallo(imallo)%dmd(idmd)%manure_amt%app_t_ha = d_tbl%act(iac)%const
 119 mallo(imallo)%dmd(idmd)%manure_amt%app_method = d_tbl%act_app(iac)
END IFLine 120
CASE ("irr_demand") Lines 123-166
 124 ipl = 1
 125 j = d_tbl%act(iac)%ob_num
 126 if (j == 0) j = ob_cur
IF (d_tbl%act(iac)%name=='ponding') THEN Lines 128-138
 129 hru(j)%irr_hmax = d_tbl%act(iac)%const
 130 hru(j)%irr_hmin = d_tbl%act(iac)%const2
 132 wet_ob(j)%depth = wet_ob(j)%depth + irrig(j)%applied / 1000.
IF (wet_ob(j)%depth*1000.) THEN Lines 134-135
 135 irrig(j)%demand = max(0.,d_tbl%act(iac)%const-wet_ob(j)%depth*1000.) * hru(j)%area_ha * 10.
END IFLine 135
ELSE Lines 136-138
 137 irrig(j)%demand = 0.
END IF Line 138
END IFLine 138
ELSE Lines 139-164
IF (pcom(j)%dtbl(idtbl)%num_actions(iac) <= Int(d_tbl%act(iac)%const2)) THEN Lines 140-155
if unlimited source, set irrigation applied directly to hru (line 144)
if unlimited source, set irrigation applied directly to hru (line 144)
 141 irrop = d_tbl%act_typ(iac)
 142 irrig(j)%demand = d_tbl%act(iac)%const * hru(j)%area_ha * 10.
IF (d_tbl%act(iac)%file_pointer == "unlim") THEN Lines 145-148
 146 irrig(j)%applied = irrop_db(irrop)%amt_mm * irrop_db(irrop)%eff * (1. - irrop_db(irrop)%surq)
 147 irrig(j)%runoff = irrop_db(irrop)%amt_mm * irrop_db(irrop)%eff * irrop_db(irrop)%surq
END IFLine 148
IF (pco%mgtout == "y") THEN Lines 151-155
WRITE  152 write (2612, *) j, time%yrc, time%mo, time%day_mo, d_tbl%act(iac)%name, "IRRIGATE", phubase(j),  &
 153 pcom(j)%plcur(ipl)%phuacc, soil(j)%sw,pl_mass(j)%tot(ipl)%m, soil1(j)%rsd(1)%m, &
 154 sol_sumno3(j), sol_sumsolp(j), irrig(j)%applied
END IFLine 155
END IFLine 155
ELSE Lines 156-163
set demand for irrigation from channel, reservoir or aquifer (line 157)
set demand for irrigation from channel, reservoir or aquifer (line 157)
IF (pco%mgtout == "y") THEN Lines 158-162
WRITE  159 write (2612, *) j, time%yrc, time%mo, time%day_mo, d_tbl%act(iac)%name, "IRRIG_DMD", phubase(j), &
 160 pcom(j)%plcur(ipl)%phuacc, soil(j)%sw,pl_mass(j)%tot(ipl)%m, soil1(j)%rsd(1)%m, &
 161 sol_sumno3(j), sol_sumsolp(j), irrop_db(irrop)%amt_mm
END IFLine 162
END IF Line 163
END IF Line 164
CASE ("irrigate") Lines 167-261
check number of applications per year (line 171)
check number of applications per year (line 171)
 168 ipl = 1
 169 j = ob_cur
IF (pcom(j)%dtbl(idtbl)%num_actions(iac) <= Int(d_tbl%act(iac)%const2)) THEN Lines 172-259
 173 isrc = d_tbl%act(iac)%ob_num
 174 irrop = d_tbl%act_typ(iac)
 190 iob = d_tbl%act(iac)%ob_num
 247 hru(j)%irr_yr = hru(j)%irr_yr + irrig(j)%applied
 255 pcom(j)%dtbl(idtbl)%num_actions(iac) = pcom(j)%dtbl(idtbl)%num_actions(iac) + 1
 256 pcom(j)%dtbl(idtbl)%days_act(iac) = 1
 257 pcom(j)%days_irr = 1
 258 if (iac > 1) pcom(j)%dtbl(idtbl)%days_act(iac-1) =  0
IF (d_tbl%act(iac)%name=='ponding') THEN Lines 176-182
 177 hru(j)%irr_hmax = d_tbl%act(iac)%const
 178 hru(j)%irr_hmin = d_tbl%act(iac)%const2
 179 irrig(j)%applied = max(0.,d_tbl%act(iac)%const-wet_ob(j)%depth*1000.) * irrop_db(irrop)%eff * &
 180 (1. - irrop_db(irrop)%surq)
 181 irrig(j)%runoff = max(0.,d_tbl%act(iac)%const-wet_ob(j)%depth*1000.) * irrop_db(irrop)%surq
 182 irrig(j)%demand = max(0.,d_tbl%act(iac)%const-wet_ob(j)%depth*1000.) * hru(j)%area_ha * 10.
END IFLine 182
ELSE Lines 183-187
 184 irrig(j)%applied = d_tbl%act(iac)%const * irrop_db(irrop)%eff * (1. - irrop_db(irrop)%surq)
 185 irrig(j)%runoff = d_tbl%act(iac)%const * irrop_db(irrop)%surq
 186 irrig(j)%demand = d_tbl%act(iac)%const * hru(j)%area_ha * 10.
END IF Line 187
SELECT CASE (d_tbl%act(iac)%ob) Lines 191-244
CASE ("aqu") Lines 192-209
 193 stor_m3 = aqu_d(iob)%stor * aqu_prm(iob)%area_ha * 10.
 202 rto = amax1 (0., rto)
 203 rto = amin1 (1., rto)
 204 rto1 = (1. - rto)
 205 irrig(j)%water%flo = rto * aqu_d(iob)%stor
 206 aqu_d(iob)%stor = rto1 * aqu_d(iob)%stor
 207 cs_irr(iob) = rto * cs_aqu(iob)
 208 cs_aqu(iob) = rto1 * cs_aqu(iob)
IF (stor_m3 > irrig(j)%demand) THEN Lines 194-195
 195 rto = irrig(j)%demand / stor_m3
END IFLine 195
ELSE Lines 196-201
 197 rto = 0.
 198 irrig(j)%applied = 0.
 199 irrig(j)%runoff = 0.
 200 irrig(j)%demand = 0.
END IF Line 201
CASE ("cha", "sdc") Lines 210-226
 219 rto = amax1 (0., rto)
 220 rto = amin1 (1., rto)
 221 rto1 = (1. - rto)
 222 irrig(j)%water = rto * ch_stor(iob)
 223 ch_stor(iob) = rto1 * ch_stor(iob)
 224 cs_irr(iob) = rto * ch_water(iob)
 225 ch_water(iob) = rto1 * ch_water(iob)
IF (ch_stor(iob)%flo > irrig(j)%demand) THEN Lines 211-212
 212 rto = irrig(j)%demand / ch_stor(iob)%flo
END IFLine 212
ELSE Lines 213-218
 214 rto = 0.
 215 irrig(j)%applied = 0.
 216 irrig(j)%runoff = 0.
 217 irrig(j)%demand = 0.
END IF Line 218
CASE ("res") Lines 227-243
 236 rto = amax1 (0., rto)
 237 rto = amin1 (1., rto)
 238 rto1 = (1. - rto)
 239 irrig(j)%water = rto * res(iob)
 240 res(iob) = rto1 * res(iob)
IF (res(iob)%flo > irrig(j)%demand) THEN Lines 228-229
 229 rto = irrig(j)%demand / res(iob)%flo
END IFLine 229
ELSE Lines 230-235
 231 rto = 0.
 232 irrig(j)%applied = 0.
 233 irrig(j)%runoff = 0.
 234 irrig(j)%demand = 0.
END IF Line 235
END SELECTLine 244
IF (pco%mgtout == "y") THEN Lines 249-253
WRITE  250 write (2612, *) j, time%yrc, time%mo, time%day_mo, d_tbl%act(iac)%name, "IRRIGATE", phubase(j),  &
 251 pcom(j)%plcur(ipl)%phuacc, soil(j)%sw, pl_mass(j)%tot(ipl)%m, soil1(j)%rsd(1)%m, &
 252 sol_sumno3(j), sol_sumsolp(j), irrig(j)%demand
END IFLine 253
END IFLine 259
CASE ("fertilize") Lines 262-294
 263 j = d_tbl%act(iac)%ob_num
 264 if (j == 0) j = ob_cur
IF (pcom(j)%dtbl(idtbl)%num_actions(iac) <= Int(d_tbl%act(iac)%const2)) THEN Lines 266-292
 267 ipl = 1
 268 ifrt = d_tbl%act_typ(iac)
 269 frt_kg = d_tbl%act(iac)%const
 270 ifertop = d_tbl%act_app(iac)
 289 pcom(j)%dtbl(idtbl)%num_actions(iac) = pcom(j)%dtbl(idtbl)%num_actions(iac) + 1
 290 pcom(j)%dtbl(idtbl)%days_act(iac) = 1
 291 if (iac > 1) pcom(j)%dtbl(idtbl)%days_act(iac-1) =  0
IF (wet(j)%flo > 0. .and. chemapp_db(ifertop)%surf_frac == 1) THEN Lines 272-279
CALL  273 call pl_fert_wet (ifrt, frt_kg)
IF (pco%mgtout == "y") THEN Lines 274-279
WRITE  275 write (2612,*) j, time%yrc, time%mo, time%day_mo, mgt%op_char, " FERT-WET", &
 276 phubase(j), pcom(j)%plcur(ipl)%phuacc, soil(j)%sw, pl_mass(j)%tot(ipl)%m,           &
 277 soil1(j)%rsd(1)%m, sol_sumno3(j), sol_sumsolp(j), frt_kg, fertno3, fertnh3,         &
 278 fertorgn, fertsolp, fertorgp
END IFLine 279
END IFLine 279
ELSE Lines 280-288
CALL  281 call pl_fert (ifrt, frt_kg, ifertop)
IF (pco%mgtout == "y") THEN Lines 282-287
WRITE  283 write (2612,*) j, time%yrc, time%mo, time%day_mo, mgt%op_char, "    FERT ", &
 284 phubase(j), pcom(j)%plcur(ipl)%phuacc, soil(j)%sw, pl_mass(j)%tot(ipl)%m,           &
 285 soil1(j)%rsd(1)%m, sol_sumno3(j), sol_sumsolp(j), frt_kg, fertno3, fertnh3,         &
 286 fertorgn, fertsolp, fertorgp
END IFLine 287
END IF Line 288
END IFLine 292
CASE ("manure") Lines 295-319
 296 j = d_tbl%act(iac)%ob_num
 297 if (j == 0) j = ob_cur
IF (pcom(j)%dtbl(idtbl)%num_actions(iac) <= Int(d_tbl%act(iac)%const2)) THEN Lines 299-317
 300 ipl = 1
 301 ifrt = d_tbl%act_typ(iac)
 302 frt_kg = d_tbl%act(iac)%const
 303 ifertop = d_tbl%act_app(iac)
CALL  305 call pl_manure (ifrt, frt_kg, ifertop)
CALL  306 call salt_fert(j,ifrt,frt_kg,ifertop)
CALL  307 call cs_fert(j,ifrt,frt_kg,ifertop)
 314 pcom(j)%dtbl(idtbl)%num_actions(iac) = pcom(j)%dtbl(idtbl)%num_actions(iac) + 1
 315 pcom(j)%dtbl(idtbl)%days_act(iac) = 1
 316 if (iac > 1) pcom(j)%dtbl(idtbl)%days_act(iac-1) =  0
IF (pco%mgtout == "y") THEN Lines 308-313
WRITE  309 write (2612,*) j, time%yrc, time%mo, time%day_mo, mgt%op_char, " MANURE ", &
 310 phubase(j), pcom(j)%plcur(ipl)%phuacc, soil(j)%sw, pl_mass(j)%tot(ipl)%m,           &
 311 soil1(j)%rsd(1)%m, sol_sumno3(j), sol_sumsolp(j), frt_kg, fertno3, fertnh3,         &
 312 fertorgn, fertsolp, fertorgp
END IFLine 313
END IFLine 317
CASE ("fert_future") Lines 320-325
 321 j = ob_cur
 322 ifrt = d_tbl%act(iac)%ob_num
 323 pcom(j)%fert_fut(ifrt)%day_fert = Int (d_tbl%act(iac)%const2)
CASE ("till") Lines 326-345
 327 j = d_tbl%act(iac)%ob_num
 328 if (j == 0) j = ob_cur
IF (pcom(j)%dtbl(idtbl)%num_actions(iac) <= Int(d_tbl%act(iac)%const2)) THEN Lines 330-343
 331 idtill = d_tbl%act_typ(iac)
 332 ipl = 1
CALL  333 call mgt_newtillmix(j, 0., idtill)
 340 pcom(j)%dtbl(idtbl)%num_actions(iac) = pcom(j)%dtbl(idtbl)%num_actions(iac) + 1
 341 pcom(j)%dtbl(idtbl)%days_act(iac) = 1
 342 if (iac > 1) pcom(j)%dtbl(idtbl)%days_act(iac-1) =  0
IF (pco%mgtout == "y") THEN Lines 335-339
WRITE  336 write (2612, *) j, time%yrc, time%mo, time%day_mo, tilldb(idtill)%tillnm, "    TILLAGE",    &
 337 phubase(j), pcom(j)%plcur(ipl)%phuacc, soil(j)%sw, pl_mass(j)%tot(ipl)%m,        &
 338 soil1(j)%rsd(1)%m, sol_sumno3(j), sol_sumsolp(j), tilldb(idtill)%effmix
END IFLine 339
END IFLine 343
CASE ("plant") Lines 346-398
 347 j = d_tbl%act(iac)%ob_num
 348 if (j == 0) j = ob_cur
 393 pcom(j)%dtbl(idtbl)%num_actions(iac) = pcom(j)%dtbl(idtbl)%num_actions(iac) + 1
 394 pcom(j)%dtbl(idtbl)%days_act(iac) = 1
 395 if (iac > 1) pcom(j)%dtbl(idtbl)%days_act(iac-1) =  0
IF (pcom(j)%dtbl(idtbl)%num_actions(iac) <= Int(d_tbl%act(iac)%const2)) THEN Lines 350-359
check for generic plant-harv and set crops (line 354)
 352 icom = pcom(j)%pcomdb
 353 pcom(j)%days_plant = 1
 355 isched = hru(j)%mgt_ops
 356 if (sched(isched)%auto_name(idtbl) == "pl_hv_summer1" .or.      &
 357 sched(isched)%auto_name(idtbl) == "pl_hv_winter1") then
 358 d_tbl%act(iac)%option = sched(isched)%auto_crop(1)
END IFLine 359
IF (sched(isched)%auto_name(idtbl) == "pl_hv_summer2") THEN Lines 360-362
 361 d_tbl%act(iac)%option = sched(isched)%auto_crop(pcom(j)%rot_yr)
END IFLine 362
DO ipl = 1, pcom(j)%npl Lines 364-391
 366 idp = pcomdb(icom)%pl(ipl)%db_num
IF (d_tbl%act(iac)%option == pcomdb(icom)%pl(ipl)%cpnm) THEN Lines 367-390
check to see if the crop is already growing (line 368)
check to see if the crop is already growing (line 368)
IF (pcom(j)%plcur(ipl)%gro == "n") THEN Lines 369-380
 370 pcom(j)%plcur(ipl)%gro = "y"
 371 pcom(j)%plcur(ipl)%idorm = "n"
IF (d_tbl%act_app(iac) > 0) THEN Lines 372-374
CALL  373 call mgt_transplant (d_tbl%act_app(iac))
END IFLine 374
IF (pco%mgtout == "y") THEN Lines 375-380
WRITE  376 write (2612, *) j, time%yrc, time%mo, time%day_mo, pldb(idp)%plantnm, "    PLANT",   &
 377 phubase(j), pcom(j)%plcur(ipl)%phuacc, soil(ihru)%sw,                     &
 378 pl_mass(j)%tot(ipl)%m, soil1(j)%rsd(1)%m, sol_sumno3(j),                  &
 379 sol_sumsolp(j), pcom(j)%plg(ipl)%lai, pcom(j)%plcur(ipl)%lai_pot
END IFLine 380
END IFLine 380
ELSE Lines 381-389
don't plant if the crop is already growing (line 382)
don't plant if the crop is already growing (line 382)
IF (pco%mgtout == "y") THEN Lines 383-388
WRITE  384 write (2612, *) j, time%yrc, time%mo, time%day_mo, pldb(idp)%plantnm,         &
 385 "    PLANT_ALREADY_GROWING", phubase(j), pcom(j)%plcur(ipl)%phuacc,       &
 386 soil(j)%sw, pl_mass(j)%tot(ipl)%m, soil1(j)%rsd(1)%m, sol_sumno3(j),      &
 387 sol_sumsolp(j),pcom(j)%plg(ipl)%lai, pcom(j)%plcur(ipl)%lai_pot
END IFLine 388
END IF Line 389
END IFLine 390
END DOLine 391
CASE ("harvest") Lines 399-483
 400 j = d_tbl%act(iac)%ob_num
 401 if (j == 0) j = ob_cur
 478 pcom(j)%dtbl(idtbl)%num_actions(iac) = pcom(j)%dtbl(idtbl)%num_actions(iac) + 1
 479 pcom(j)%dtbl(idtbl)%days_act(iac) = 1
 480 if (iac > 1) pcom(j)%dtbl(idtbl)%days_act(iac-1) =  0
IF (pcom(j)%dtbl(idtbl)%num_actions(iac) <= Int(d_tbl%act(iac)%const2)) THEN Lines 403-412
check for generic plant-harv and set crops (line 407)
 404 iharvop = d_tbl%act_typ(iac)
 405 icom = pcom(j)%pcomdb
 406 pcom(j)%days_harv = 1
 408 isched = hru(j)%mgt_ops
 409 if (sched(isched)%auto_name(idtbl) == "pl_hv_summer1" .or.      &
 410 sched(isched)%auto_name(idtbl) == "pl_hv_winter1") then
 411 d_tbl%act(iac)%option = sched(isched)%auto_crop(1)
END IFLine 412
IF (sched(isched)%auto_name(idtbl) == "pl_hv_summer2") THEN Lines 413-415
 414 d_tbl%act(iac)%option = sched(isched)%auto_crop(pcom(j)%rot_yr)
END IFLine 415
DO ipl = 1, pcom(j)%npl Lines 417-477
 418 biomass = pl_mass(j)%tot(ipl)%m
IF (d_tbl%act(iac)%option == pcomdb(icom)%pl(ipl)%cpnm .or. d_tbl%act(iac)%option == "all") THEN Lines 419-475
sum yield and num. of harvest to calc ave yields (line 445)
sum basin crop yields and area harvested (line 451)
 446 pl_mass(j)%yield_tot(ipl) = pl_mass(j)%yield_tot(ipl) + pl_yield
 447 pl_mass(j)%yield_yr(ipl) = pl_mass(j)%yield_yr(ipl) + pl_yield
 448 pcom(j)%plcur(ipl)%harv_num_yr = pcom(j)%plcur(ipl)%harv_num_yr + 1
 449 pcom(j)%plcur(ipl)%harv_num_yr = pcom(j)%plcur(ipl)%harv_num_yr + 1
 452 iplt_bsn = pcom(j)%plcur(ipl)%bsn_num
 453 bsn_crop_yld(iplt_bsn)%area_ha = bsn_crop_yld(iplt_bsn)%area_ha + hru(j)%area_ha
 454 bsn_crop_yld(iplt_bsn)%yield = bsn_crop_yld(iplt_bsn)%yield + yield * hru(j)%area_ha / 1000.
 467 idp = pcom(j)%plcur(ipl)%idplt
IF (biomass > harvop_db(iharvop)%bm_min) THEN Lines 422-443
SELECT CASE (harvop_db(iharvop)%typ) Lines 424-442
CASE ("biomass") Lines 425-426
CALL  426 call mgt_harvbiomass (j, ipl, iharvop)
CASE ("grain") Lines 427-428
CALL  428 call mgt_harvgrain (j, ipl, iharvop)
CASE ("residue") Lines 429-431
 430 harveff = d_tbl%act(iac)%const
CALL  431 call mgt_harvresidue (j, harveff)
CASE ("tree") Lines 432-433
CALL  433 call mgt_harvbiomass (j, ipl, iharvop)
CASE ("tuber") Lines 434-435
CALL  435 call mgt_harvtuber (j, ipl, iharvop)
CASE ("peanuts") Lines 436-437
CALL  437 call mgt_harvtuber (j, ipl, iharvop)
CASE ("stripper") Lines 438-439
CALL  439 call mgt_harvbiomass (j, ipl, iharvop)
CASE ("picker") Lines 440-441
CALL  441 call mgt_harvgrain (j, ipl, iharvop)
END SELECTLine 442
END IFLine 443
IF (cal_codes%plt == "y") THEN Lines 456-465
sum regional crop yields for soft calibration (line 457)
 458 ireg = hru(j)%crop_reg
DO ilum = 1, plcal(ireg)%lum_num Lines 459-464
IF (plcal(ireg)%lum(ilum)%meas%name == mgt%op_char) THEN Lines 460-463
 461 plcal(ireg)%lum(ilum)%ha = plcal(ireg)%lum(ilum)%ha + hru(j)%area_ha
 462 plcal(ireg)%lum(ilum)%sim%yield = plcal(ireg)%lum(ilum)%sim%yield + pl_yield%m * hru(j)%area_ha / 1000.
END IFLine 463
END DOLine 464
END IFLine 465
IF (pco%mgtout == "y") THEN Lines 468-474
WRITE  469 write (2612, *) j, time%yrc, time%mo, time%day_mo,  pldb(idp)%plantnm, "    HARVEST",      &
 470 phubase(j), pcom(j)%plcur(ipl)%phuacc, soil(j)%sw, biomass, soil1(j)%rsd(1)%m, &
 471 sol_sumno3(j), sol_sumsolp(j), pl_yield%m, pcom(j)%plstr(ipl)%sum_n, &
 472 pcom(j)%plstr(ipl)%sum_p, pcom(j)%plstr(ipl)%sum_tmp, pcom(j)%plstr(ipl)%sum_w, &
 473 pcom(j)%plstr(ipl)%sum_a
END IFLine 474
END IFLine 475
END DOLine 477
CASE ("kill") Lines 484-514
 485 j = d_tbl%act(iac)%ob_num
 486 if (j == 0) j = ob_cur
IF (pcom(j)%dtbl(idtbl)%num_actions(iac) <= Int(d_tbl%act(iac)%const2)) THEN Lines 488-512
 489 icom = pcom(j)%pcomdb
 490 pcom(j)%days_kill = 1
 509 pcom(j)%dtbl(idtbl)%num_actions(iac) = pcom(j)%dtbl(idtbl)%num_actions(iac) + 1
 510 pcom(j)%dtbl(idtbl)%days_act(iac) = 1
 511 if (iac > 1) pcom(j)%dtbl(idtbl)%days_act(iac-1) =  0
DO ipl = 1, pcom(j)%npl Lines 491-508
 492 biomass = pl_mass(j)%tot(ipl)%m
 506 pcom(j)%plcur(ipl)%phuacc = 0.
 507 phubase(j) = 0.
IF (d_tbl%act(iac)%option == pcomdb(icom)%pl(ipl)%cpnm .or. d_tbl%act(iac)%option == "all") THEN Lines 493-505
 494 pcom(j)%last_kill = pcomdb(icom)%pl(ipl)%cpnm
CALL  495 call mgt_killop (j, ipl)
 497 idp = pcom(j)%plcur(ipl)%idplt
IF (pco%mgtout == "y") THEN Lines 498-504
WRITE  499 write (2612, *) j, time%yrc, time%mo, time%day_mo,  pldb(idp)%plantnm, "         KILL",     &
 500 phubase(j), pcom(j)%plcur(ipl)%phuacc, soil(j)%sw, biomass, soil1(j)%rsd(1)%m,  &
 501 sol_sumno3(j), sol_sumsolp(j), yield, pcom(j)%plstr(ipl)%sum_n,                  &
 502 pcom(j)%plstr(ipl)%sum_p, pcom(j)%plstr(ipl)%sum_tmp, pcom(j)%plstr(ipl)%sum_w,  &
 503 pcom(j)%plstr(ipl)%sum_a
END IFLine 504
END IFLine 505
END DOLine 508
END IFLine 512
CASE ("harvest_kill") Lines 515-600
 516 j = d_tbl%act(iac)%ob_num
 517 if (j == 0) j = ob_cur
 595 pcom(j)%dtbl(idtbl)%num_actions(iac) = pcom(j)%dtbl(idtbl)%num_actions(iac) + 1
 596 pcom(j)%dtbl(idtbl)%days_act(iac) = 1
 597 if (iac > 1) pcom(j)%dtbl(idtbl)%days_act(iac-1) =  0
IF (pcom(j)%dtbl(idtbl)%num_actions(iac) <= Int(d_tbl%act(iac)%const2)) THEN Lines 519-528
check for generic plant-harv and set crops (line 523)
 520 iharvop = d_tbl%act_typ(iac)
 521 icom = pcom(j)%pcomdb
 522 pcom(j)%days_harv = 1
 524 isched = hru(j)%mgt_ops
 525 if (sched(isched)%auto_name(idtbl) == "pl_hv_summer1" .or.      &
 526 sched(isched)%auto_name(idtbl) == "pl_hv_winter1") then
 527 d_tbl%act(iac)%option = sched(isched)%auto_crop(1)
END IFLine 528
IF (sched(isched)%auto_name(idtbl) == "pl_hv_summer2") THEN Lines 529-531
 530 d_tbl%act(iac)%option = sched(isched)%auto_crop(pcom(j)%rot_yr)
END IFLine 531
DO ipl = 1, pcom(j)%npl Lines 533-594
 534 biomass = pl_mass(j)%tot(ipl)%m
IF (d_tbl%act(iac)%option == pcomdb(icom)%pl(ipl)%cpnm .or. d_tbl%act(iac)%option == "all") THEN Lines 535-593
sum yield and number of harvests to calc ave yields (line 563)
sum basin crop yields and area harvested (line 569)
sum regional crop yields for soft calibration (line 574)
sum regional crop yields for soft calibration (line 574)
 560 pcom(j)%last_kill = pcomdb(icom)%pl(ipl)%cpnm
CALL  561 call mgt_killop (j, ipl)
 564 pl_mass(j)%yield_tot(ipl) = pl_mass(j)%yield_tot(ipl) + pl_yield
 565 pl_mass(j)%yield_yr(ipl) = pl_mass(j)%yield_yr(ipl) + pl_yield
 566 pcom(j)%plcur(ipl)%harv_num = pcom(j)%plcur(ipl)%harv_num + 1
 567 pcom(j)%plcur(ipl)%harv_num_yr = pcom(j)%plcur(ipl)%harv_num_yr + 1
 570 iplt_bsn = pcom(j)%plcur(ipl)%bsn_num
 571 bsn_crop_yld(iplt_bsn)%area_ha = bsn_crop_yld(iplt_bsn)%area_ha + hru(j)%area_ha
 572 bsn_crop_yld(iplt_bsn)%yield = bsn_crop_yld(iplt_bsn)%yield + pl_yield%m * hru(j)%area_ha / 1000.
 585 idp = pcom(j)%plcur(ipl)%idplt
IF (biomass > harvop_db(iharvop)%bm_min) THEN Lines 538-558
SELECT CASE (harvop_db(iharvop)%typ) Lines 540-557
CASE ("biomass") Lines 541-542
CALL  542 call mgt_harvbiomass (j, ipl, iharvop)
CASE ("grain") Lines 543-544
CALL  544 call mgt_harvgrain (j, ipl, iharvop)
CASE ("residue") Lines 545-547
 546 harveff = d_tbl%act(iac)%const
CALL  547 call mgt_harvresidue (j, harveff)
CASE ("tree") Lines 548-548
CASE ("tuber") Lines 549-550
CALL  550 call mgt_harvtuber (j, ipl, iharvop)
CASE ("peanuts") Lines 551-552
CALL  552 call mgt_harvtuber (j, ipl, iharvop)
CASE ("stripper") Lines 553-554
CALL  554 call mgt_harvgrain (j, ipl, iharvop)
CASE ("picker") Lines 555-556
CALL  556 call mgt_harvgrain (j, ipl, iharvop)
END SELECTLine 557
END IFLine 558
IF (cal_codes%plt == "y") THEN Lines 575-583
 576 ireg = hru(j)%crop_reg
DO ilum = 1, plcal(ireg)%lum_num Lines 577-582
IF (plcal(ireg)%lum(ilum)%meas%name == d_tbl%act(iac)%option) THEN Lines 578-581
 579 plcal(ireg)%lum(ilum)%ha = plcal(ireg)%lum(ilum)%ha + hru(j)%area_ha
 580 plcal(ireg)%lum(ilum)%sim%yield = plcal(ireg)%lum(ilum)%sim%yield + pl_yield%m * hru(j)%area_ha / 1000.
END IFLine 581
END DOLine 582
END IFLine 583
IF (pco%mgtout == "y") THEN Lines 586-592
WRITE  587 write (2612, *) j, time%yrc, time%mo, time%day_mo,  pldb(idp)%plantnm, "    HARV/KILL",        &
 588 phubase(j), pcom(j)%plcur(ipl)%phuacc, soil(j)%sw, biomass, soil1(j)%rsd(1)%m,     &
 589 sol_sumno3(j), sol_sumsolp(j), pl_yield%m, pcom(j)%plstr(ipl)%sum_n,   &
 590 pcom(j)%plstr(ipl)%sum_p, pcom(j)%plstr(ipl)%sum_tmp, pcom(j)%plstr(ipl)%sum_w,     &
 591 pcom(j)%plstr(ipl)%sum_a
END IFLine 592
END IFLine 593
END DOLine 594
CASE ("rot_reset") Lines 601-607
 602 j = d_tbl%act(iac)%ob_num
 603 if (j == 0) j = ob_cur
 604 if (d_tbl%act(iac)%const < 1) d_tbl%act(iac)%const = 1
 605 pcom(j)%rot_yr = d_tbl%act(iac)%const
CASE ("harv_reset") Lines 608-614
 609 j = d_tbl%act(iac)%ob_num
 610 if (j == 0) j = ob_cur
 611 if (d_tbl%act(iac)%const < 1) d_tbl%act(iac)%const = 1
 612 pcom(j)%days_harv = d_tbl%act(iac)%const
CASE ("kill_reset") Lines 615-621
 616 j = d_tbl%act(iac)%ob_num
 617 if (j == 0) j = ob_cur
 618 if (d_tbl%act(iac)%const < 1) d_tbl%act(iac)%const = 1
 619 pcom(j)%days_kill = d_tbl%act(iac)%const
CASE ("plant_reset") Lines 622-628
 623 j = d_tbl%act(iac)%ob_num
 624 if (j == 0) j = ob_cur
 625 if (d_tbl%act(iac)%const < 1) d_tbl%act(iac)%const = 1
 626 pcom(j)%days_plant = d_tbl%act(iac)%const
CASE ("irr_reset") Lines 629-635
 630 j = d_tbl%act(iac)%ob_num
 631 if (j == 0) j = ob_cur
 632 if (d_tbl%act(iac)%const < 1) d_tbl%act(iac)%const = 1
 633 pcom(j)%days_irr = d_tbl%act(iac)%const
CASE ("pest_apply") Lines 636-657
 637 j = d_tbl%act(iac)%ob_num
 638 if (j == 0) j = ob_cur
IF (pcom(j)%dtbl(idtbl)%num_actions(iac) <= Int(d_tbl%act(iac)%const2)) THEN Lines 640-656
 641 ipl = 1
 642 sumpst = sumpst + 1
 643 ipst = d_tbl%act_typ(iac)
 644 ipestop = d_tbl%act_app(iac)
 645 pest_kg = d_tbl%act(iac)%const * chemapp_db(ipestop)%app_eff
CALL  646 call pest_apply (j, ipst, pest_kg, ipestop)
 653 pcom(j)%dtbl(idtbl)%num_actions(iac) = pcom(j)%dtbl(idtbl)%num_actions(iac) + 1
IF (pco%mgtout == "y") THEN Lines 648-652
WRITE  649 write (2612, *) j, time%yrc, time%mo, time%day_mo, d_tbl%act(iac)%option, "    PEST ",        &
 650 phubase(j), pcom(j)%plcur(ipl)%phuacc, soil(j)%sw,pl_mass(j)%tot(ipl)%m,           &
 651 soil1(j)%rsd(1)%m, sol_sumno3(j), sol_sumsolp(j), pest_kg
END IFLine 652
END IFLine 656
CASE ("graze") Lines 658-673
 659 j = d_tbl%act(iac)%ob_num
 660 if (j == 0) j = ob_cur
 662 igr = d_tbl%act_typ(iac)
 663 graze = grazeop_db(igr)
CALL  664 call pl_graze
 671 pcom(j)%dtbl(idtbl)%num_actions(iac) = pcom(j)%dtbl(idtbl)%num_actions(iac) + 1
CASE ("grow_init") Lines 674-684
 675 j = d_tbl%act(iac)%ob_num
 676 if (j == 0) j = ob_cur
 678 hlt(j)%gro = "y"
 679 hlt(j)%g = 0.
 680 hlt(j)%alai = 0.
 681 hlt(j)%dm = 0.
 682 hlt(j)%hufh = 0.
CASE ("grow_end") Lines 685-714
 687 j = d_tbl%act(iac)%ob_num
 688 if (j == 0) j = ob_cur
 690 idp = hlt(j)%iplant
 696 hiad1 = (pldb(idp)%hvsti - pldb(idp)%wsyf) *                            &
 697 (wur / (wur + Exp(6.13 - .0883 * wur))) + pldb(idp)%wsyf
 698 hiad1 = amin1 (hiad1, pldb(idp)%hvsti)
 699 yield = 0.8 * hlt(j)%dm * hiad1
 700 hlt(j)%yield = yield / 1000.
 701 hlt(j)%npp = hlt(j)%dm / 1000.
 702 hlt(j)%lai_mx = hlt(j)%alai
 706 hlt(j)%gro = "n"
 707 hlt(j)%g = 0.
 708 hlt(j)%alai = 0.
 709 hlt(j)%dm = 0.
 710 hlt(j)%hufh = 0.
 711 hlt(j)%aet = 0.
 712 hlt(j)%pet = 0.
IF (hlt(j)%pet < 10.) THEN Lines 691-692
 692 wur = 100.
END IFLine 692
ELSE Lines 693-695
 694 wur = 100. * hlt(j)%aet / hlt(j)%pet
END IF Line 695
CASE ("tiledep_control") Lines 715-731
 716 j = d_tbl%act(iac)%ob_num
 717 if (j == 0) j = ob_cur
IF (pcom(j)%dtbl(idtbl)%num_actions(iac) <= Int(d_tbl%act(iac)%const2)) THEN Lines 719-729
 720 istr = hru(j)%tiledrain
 721 hru(j)%lumv%sdr_dep = d_tbl%act(iac)%const
 722 pcom(j)%dtbl(idtbl)%num_actions(iac) = pcom(j)%dtbl(idtbl)%num_actions(iac) + 1
IF (pco%mgtout == "y") THEN Lines 724-728
WRITE  725 write (2612, *) j, time%yrc, time%mo, time%day_mo, tilldb(idtill)%tillnm, "  DRAIN_CONTROL",    &
 726 phubase(j), pcom(j)%plcur(1)%phuacc, soil(j)%sw, pl_mass(j)%tot(1)%m,        &
 727 soil1(j)%rsd(1)%m, sol_sumno3(j), sol_sumsolp(j), hru(j)%lumv%sdr_dep
END IFLine 728
END IFLine 729
CASE ("tileflo_contol") Lines 732-762
set amount of tile flow to send to buffer hru (line 736)
 733 j = d_tbl%act(iac)%ob_num
 734 if (j == 0) j = ob_cur
 737 hru_rcv = hru(j)%sb%sb_db%hru_rcv
SELECT CASE (d_tbl%act(iac)%option) Lines 740-760
CASE ("flo_mm") Lines 742-744
 743 hru(hru_rcv)%sb%inflo = Min (qtile, d_tbl%act(iac)%const)
CASE ("min_mm") Lines 745-747
 746 hru(hru_rcv)%sb%inflo = Max (qtile, d_tbl%act(iac)%const)
CASE ("max_mm") Lines 748-750
 749 hru(hru_rcv)%sb%inflo = Min (qtile, d_tbl%act(iac)%const)
CASE ("all_flo") Lines 751-753
 752 hru(hru_rcv)%sb%inflo = qtile
CASE ("zero_flo") Lines 754-756
 755 hru(hru_rcv)%sb%inflo = 0.
CASE ("frac") Lines 757-759
 758 hru(hru_rcv)%sb%inflo = d_tbl%act(iac)%const * qtile
END SELECTLine 760
CASE ("res_demand") Lines 763-780
 764 j = d_tbl%act(iac)%ob_num
 765 if (j == 0) j = ob_cur
SELECT CASE (d_tbl%act(iac)%option) Lines 767-778
CASE ("storage") Lines 769-777
IF (d_tbl%act(iac)%file_pointer == "pvol") THEN Lines 770-773
 771 dmd_m3 = d_tbl%act(iac)%const * res_ob(j)%pvol - res(j)%flo
 772 dmd_m3 = Max (0., dmd_m3)
END IFLine 773
IF (d_tbl%act(iac)%file_pointer == "evol") THEN Lines 774-777
 775 dmd_m3 = d_tbl%act(iac)%const * res_ob(j)%evol - res(j)%flo
 776 dmd_m3 = Max (0., dmd_m3)
END IFLine 777
END SELECTLine 778
CASE ("impound_off") Lines 781-789
 782 j = d_tbl%act(iac)%ob_num
 783 if (j == 0) j = ob_cur
 785 hru(j)%dbs%surf_stor = 0
 786 wet(j) = hz
 787 wet_wat_d(j) = wbodz
CASE ("impound_on") Lines 790-804
xwalk with wetland.wet name (line 795)
 791 j = d_tbl%act(iac)%ob_num
 792 if (j == 0) j = ob_cur
 793 iihru = j
CALL  802 call wet_initial (iihru)
DO ires = 1, db_mx%wet_dat Lines 796-800
IF (wet_dat(ires)%name == d_tbl%act(iac)%file_pointer) THEN Lines 797-799
 798 hru(j)%dbs%surf_stor = ires
END IFLine 799
END DOLine 800
CASE ("weir_height") Lines 805-821
 806 j = d_tbl%act(iac)%ob_num
 807 if (j == 0) j = ob_cur
IF (d_tbl%act(iac)%option == "wet") THEN Lines 809-816
 810 wet_ob(j)%weir_hgt = d_tbl%act(iac)%const / 1000.
 812 wet_ob(j)%pvol = hru(j)%area_ha * wet_ob(j)%weir_hgt * 10.**4
IF (wet_ob(j)%evol < wet_ob(j)%pvol*1.2) THEN Lines 813-815
 814 wet_ob(j)%evol = wet_ob(j)%pvol * 1.2
END IFLine 815
END IFLine 816
ELSE Lines 817-819
 818 res_ob(j)%weir_hgt = d_tbl%act(iac)%const / 1000.
END IF Line 819
CASE ("puddle") Lines 822-855
 823 j = d_tbl%act(iac)%ob_num
 824 if (j == 0) j = ob_cur
IF (pcom(j)%dtbl(idtbl)%num_actions(iac) <= Int(d_tbl%act(iac)%const2)) THEN Lines 825-853
xwalk with puddle.ops (line 827)
 835 if (pudl_db(ipud)%wet_hc>0) hru(j)%wet_hc = pudl_db(ipud)%wet_hc
 837 wet(j)%sed = pudl_db(ipud)%sed * wet(j)%flo / 1000000.
 852 pcom(j)%dtbl(idtbl)%num_actions(iac) = pcom(j)%dtbl(idtbl)%num_actions(iac) + 1
DO ipdl = 1, db_mx%pudl_db Lines 828-832
IF (pudl_db(ipdl)%name == d_tbl%act(iac)%option) THEN Lines 829-831
 830 ipud = ipdl
END IFLine 831
END DOLine 832
DO idb = 1, db_mx%tillparm Lines 840-845
IF (tilldb(idb)%tillnm == d_tbl%act(iac)%name) THEN Lines 841-844
 842 idtill = idb
EXIT  843 exit
END IFLine 844
END DOLine 845
IF (wet_ob(j)%depth > 0.001) THEN Lines 847-848
CALL  848 call mgt_newtillmix_wet(j,idtill)
END IFLine 848
ELSE Lines 849-851
CALL  850 call mgt_newtillmix(j,0.,idtill)
END IF Line 851
END IFLine 853
CASE ("hru_fr_update") Lines 856-863
write to new landuse change file (line 859)
CALL  858 call hru_fr_change (d_tbl%act(iac)%option, d_tbl%act(iac)%file_pointer)
WRITE  860 write (3612,*) j, time%yrc, time%mo, time%day_mo,  "   HRU_FRACTION_CHANGE ",        &
 861 d_tbl%act(iac)%option, d_tbl%act(iac)%file_pointer, "   0   0"
CASE ("lu_change") Lines 864-908
reset composite usle value - in hydro_init (line 879)
write to new landuse change file (line 883)
add new plants in simulation for yield output (line 887)
 865 j = d_tbl%act(iac)%ob_num
 866 if (j == 0) j = ob_cur
 868 d_tbl%lu_chg_mx(iac) = d_tbl%lu_chg_mx(iac) + 1
 869 ilu = d_tbl%act_typ(iac)
 870 hru(j)%land_use_mgt = ilu
 871 hru(j)%dbs%land_use_mgt = ilu
 873 lu_prev = hru(j)%land_use_mgt_c
 874 hru(j)%land_use_mgt_c = d_tbl%act(iac)%file_pointer
 875 isol = hru(j)%dbs%soil
CALL  876 call hru_lum_init (j)
CALL  877 call plant_init (1,j)
CALL  878 call cn2_init (j)
 880 rock = Exp(-.053 * soil(j)%phys(1)%rock)
 881 hru(j)%lumv%usle_mult = rock * soil(j)%ly(1)%usle_k *       &
 882 hru(j)%lumv%usle_p * hru(j)%lumv%usle_ls * 11.8
WRITE  884 write (3612,*) j, time%yrc, time%mo, time%day_mo,  "    LU_CHANGE ",        &
 885 lu_prev, hru(j)%land_use_mgt_c, "   0   0"
DO ipl = 1, pcom(j)%npl Lines 888-905
IF (basin_plants == 0) THEN Lines 889-891
 890 plts_bsn(1) = pcom(j)%pl(ipl)
 891 basin_plants = 1
END IFLine 891
ELSE Lines 892-904
 893 num_plts_cur = basin_plants
DO iplt = 1, num_plts_cur Lines 894-903
 895 if (pcom(j)%pl(ipl) == plts_bsn(iplt)) exit
IF (iplt == basin_plants) THEN Lines 896-902
 897 plts_bsn(iplt+1) = pcom(j)%pl(ipl)
 898 bsn_crop_yld(iplt+1) = bsn_crop_yld_z
 899 bsn_crop_yld_aa(iplt+1) = bsn_crop_yld_z
 900 basin_plants = basin_plants + 1
 901 pcom(j)%plcur(ipl)%bsn_num = basin_plants
END IFLine 902
END DOLine 903
END IF Line 904
END DOLine 905
CASE ("p_factor") Lines 909-924
set new p factor (line 914)
reset composite usle value - in hydro_init (line 916)
write to new landuse change file (line 920)
 910 j = d_tbl%act(iac)%ob_num
 911 if (j == 0) j = ob_cur
 913 p_factor = hru(j)%lumv%usle_p
 915 hru(j)%lumv%usle_p = d_tbl%act(iac)%const
 917 rock = Exp(-.053 * soil(j)%phys(1)%rock)
 918 hru(j)%lumv%usle_mult = rock * soil(j)%ly(1)%usle_k *       &
 919 hru(j)%lumv%usle_p * hru(j)%lumv%usle_ls * 11.8
WRITE  921 write (3612,*) j, time%yrc, time%mo, time%day_mo,  "     P_FACTOR",        &
 922 "  null           null",  p_factor, hru(j)%lumv%usle_p
CASE ("contour") Lines 925-939
set new p factor as function of slope - from cons_practice.lum relationship (line 930)
reset composite usle value - in hydro_init (line 932)
 926 j = d_tbl%act(iac)%ob_num
 927 if (j == 0) j = ob_cur
 929 p_factor = hru(j)%lumv%usle_p
 931 hru(j)%lumv%usle_p = 2.7 * hru(j)%topo%slope + .26
 933 rock = Exp(-.053 * soil(j)%phys(1)%rock)
 934 hru(j)%lumv%usle_mult = rock * soil(j)%ly(1)%usle_k *       &
 935 hru(j)%lumv%usle_p * hru(j)%lumv%usle_ls * 11.8
WRITE  936 write (3612,*) j, time%yrc, time%mo, time%day_mo,  "      CONTOUR ",        &
 937 "  null           null",  p_factor, hru(j)%lumv%usle_p
CASE ("stripcrop") Lines 940-956
set new p factor as function of slope - from cons_practice.lum relationship (line 945)
adjust for pasture - above equation is for row crops (line 947)
reset composite usle value - in hydro_init (line 949)
 941 j = d_tbl%act(iac)%ob_num
 942 if (j == 0) j = ob_cur
 944 p_factor = hru(j)%lumv%usle_p
 946 hru(j)%lumv%usle_p = 2.32 * hru(j)%topo%slope + .36
 948 if (d_tbl%act(iac)%file_pointer == "pasture") hru(j)%lumv%usle_p = .5 * hru(j)%lumv%usle_p
 950 rock = Exp(-.053 * soil(j)%phys(1)%rock)
 951 hru(j)%lumv%usle_mult = rock * soil(j)%ly(1)%usle_k *       &
 952 hru(j)%lumv%usle_p * hru(j)%lumv%usle_ls * 11.8
WRITE  953 write (3612,*) j, time%yrc, time%mo, time%day_mo,  "    STRIPCROP ",        &
 954 "  null           null",  p_factor, hru(j)%lumv%usle_p
CASE ("terrace") Lines 957-973
set new p factor as function of slope - from cons_practice.lum relationship (line 962)
adjust for sod outlet - above equation is for underflow outlet (line 964)
reset composite usle value - in hydro_init (line 966)
 958 j = d_tbl%act(iac)%ob_num
 959 if (j == 0) j = ob_cur
 961 p_factor = hru(j)%lumv%usle_p
 963 hru(j)%lumv%usle_p = 1.4 * hru(j)%topo%slope + .13
 965 if (d_tbl%act(iac)%file_pointer == "sod_outlet") hru(j)%lumv%usle_p = 2. * hru(j)%lumv%usle_p
 967 rock = Exp(-.053 * soil(j)%phys(1)%rock)
 968 hru(j)%lumv%usle_mult = rock * soil(j)%ly(1)%usle_k *       &
 969 hru(j)%lumv%usle_p * hru(j)%lumv%usle_ls * 11.8
WRITE  970 write (3612,*) j, time%yrc, time%mo, time%day_mo,  "      TERRACE ",        &
 971 "  null           null",  p_factor, hru(j)%lumv%usle_p
CASE ("tile_install") Lines 974-994
set parameters for structural land use/management (line 985)
set parameters for structural land use/management (line 985)
write to new landuse change file (line 989)
 975 j = d_tbl%act(iac)%ob_num
 976 if (j == 0) j = ob_cur
 990 istr = hru(j)%tiledrain
WRITE  991 write (3612,*) j, time%yrc, time%mo, time%day_mo,  " TILE_INSTALL ",        &
 992 sdr(istr)%name, sdr(istr1)%name, "   0   0"
DO istr = 1, db_mx%sdr Lines 978-983
IF (d_tbl%act(iac)%file_pointer == sdr(istr)%name) THEN Lines 979-982
 980 istr1 = istr
EXIT  981 exit
END IFLine 982
END DOLine 983
IF (d_tbl%act(iac)%file_pointer /= "null") THEN Lines 986-988
CALL  987 call structure_set_parms("tiledrain       ", istr1, j)
END IFLine 988
CASE ("septic_install") Lines 995-1013
set parameters for structural land use/management (line 1006)
set parameters for structural land use/management (line 1006)
 996 j = d_tbl%act(iac)%ob_num
 997 if (j == 0) j = ob_cur
WRITE 1010 write (3612,*) j, time%yrc, time%mo, time%day_mo,  " SEPTIC_INSTALL ",       &
1011 sdr(istr)%name, sdr(istr1)%name, "   0   0"
DO istr = 1, db_mx%septic Lines 999-1004
IF (d_tbl%act(iac)%file_pointer == sep(istr)%name) THEN Lines 1000-1003
1001 istr1 = istr
EXIT 1002 exit
END IFLine 1003
END DOLine 1004
IF (d_tbl%act(iac)%file_pointer /= "null") THEN Lines 1007-1009
CALL 1008 call structure_set_parms("septic          ", istr1, j)
END IFLine 1009
CASE ("fstrip_install") Lines 1014-1032
set parameters for structural land use/management (line 1025)
set parameters for structural land use/management (line 1025)
1015 j = d_tbl%act(iac)%ob_num
1016 if (j == 0) j = ob_cur
WRITE 1029 write (3612,*) j, time%yrc, time%mo, time%day_mo,  " FSTRIP_INSTALL ",       &
1030 sdr(istr)%name, sdr(istr1)%name, "   0   0"
DO istr = 1, db_mx%filtop_db Lines 1018-1023
IF (d_tbl%act(iac)%file_pointer == filtstrip_db(istr)%name) THEN Lines 1019-1022
1020 istr1 = istr
EXIT 1021 exit
END IFLine 1022
END DOLine 1023
IF (d_tbl%act(iac)%file_pointer /= "null") THEN Lines 1026-1028
CALL 1027 call structure_set_parms("fstrip         ", istr1, j)
END IFLine 1028
CASE ("grassww_install") Lines 1033-1052
set parameters for structural land use/management (line 1045)
set parameters for structural land use/management (line 1045)
1034 j = d_tbl%act(iac)%ob_num
1035 if (j == 0) j = ob_cur
WRITE 1049 write (3612,*) j, time%yrc, time%mo, time%day_mo,  " GRASSWW_INSTALL ",       &
1050 sdr(istr)%name, sdr(istr1)%name, "   0   0"
DO istr = 1, db_mx%grassop_db Lines 1037-1043
IF (d_tbl%act(iac)%file_pointer == grwaterway_db(istr)%name) THEN Lines 1038-1042
1040 hru(j)%lumv%grwat_i = 1
EXIT 1041 exit
END IFLine 1042
END DOLine 1043
IF (d_tbl%act(iac)%file_pointer /= "null") THEN Lines 1046-1048
CALL 1047 call structure_set_parms("grassww         ", istr1, j)
END IFLine 1048
CASE ("grassww_uninstall") Lines 1053-1059
1054 j = d_tbl%act(iac)%ob_num
1055 if (j == 0) j = ob_cur
1056 hru(j)%lumv%grwat_i = 0
WRITE 1057 write (3612,*) j, time%yrc, time%mo, time%day_mo,  " GRASSWW_UNINSTALL ",       &
1058 sdr(istr)%name, sdr(istr1)%name, "   0   0"
CASE ("user_def_bmp") Lines 1060-1078
set parameters for structural land use/management (line 1071)
set parameters for structural land use/management (line 1071)
1061 j = d_tbl%act(iac)%ob_num
1062 if (j == 0) j = ob_cur
WRITE 1075 write (3612,*) j, time%yrc, time%mo, time%day_mo,  " USER_DEF_BMP ",       &
1076 sdr(istr)%name, sdr(istr1)%name, "   0   0"
DO istr = 1, db_mx%bmpuserop_db Lines 1064-1069
IF (d_tbl%act(iac)%file_pointer == bmpuser_db(istr)%name) THEN Lines 1065-1068
1066 istr1 = istr
EXIT 1067 exit
END IFLine 1068
END DOLine 1069
IF (d_tbl%act(iac)%file_pointer /= "null") THEN Lines 1072-1074
CALL 1073 call structure_set_parms("user_def        ", istr1, j)
END IFLine 1074
CASE ("chan_change") Lines 1079-1085
1080 ich = ob_cur
1082 sd_ch(ich)%cov = d_tbl%act(iac)%const
1083 sd_ch(ich)%order = d_tbl%act(iac)%file_pointer
CASE ("burn") Lines 1086-1107
1087 j = d_tbl%act(iac)%ob_num
1088 if (j == 0) j = ob_cur
IF (pcom(j)%dtbl(idtbl)%num_actions(iac) <= Int(d_tbl%act(iac)%const2)) THEN Lines 1090-1105
1091 iburn = d_tbl%act_typ(iac)
1098 ipl = 1
1104 pcom(j)%dtbl(idtbl)%num_actions(iac) = pcom(j)%dtbl(idtbl)%num_actions(iac) + 1
DO ipl = 1, pcom(j)%npl Lines 1092-1094
CALL 1093 call pl_burnop (j, iburn)
END DOLine 1094
IF (pco%mgtout == "y") THEN Lines 1099-1103
WRITE 1100 write (2612, *) j, time%yrc, time%mo, time%day_mo, d_tbl%act(iac)%name, "    BURN", phubase(j),    &
1101 pcom(j)%plcur(ipl)%phuacc, soil(j)%sw,pl_mass(j)%tot(ipl)%m, soil1(j)%rsd(1)%m,   &
1102 sol_sumno3(j), sol_sumsolp(j)
END IFLine 1103
END IFLine 1105
CASE ("cn_update") Lines 1108-1126
1109 j = d_tbl%act(iac)%ob_num
1110 if (j == 0) j = ob_cur
1112 cn_prev = cn2(j)
1125 pcom(j)%dtbl(idtbl)%num_actions(iac) = pcom(j)%dtbl(idtbl)%num_actions(iac) + 1
IF (pcom(j)%dtbl(idtbl)%num_actions(iac) <= Int(d_tbl%act(iac)%const2)) THEN Lines 1113-1123
1114 cn2(j) = chg_par (cn2(j), d_tbl%act(iac)%option, d_tbl%act(iac)%const, 35., 95.)
CALL 1115 call curno (cn2(j), j)
IF (pco%mgtout == "y") THEN Lines 1116-1121
1117 ipl = 1
WRITE 1118 write (2612, *) j, time%yrc, time%mo, time%day_mo, d_tbl%act(iac)%name, "    CNUP", phubase(j),    &
1119 pcom(j)%plcur(ipl)%phuacc, soil(j)%sw, pl_mass(j)%tot(ipl)%m, soil1(j)%rsd(1)%m,       &
1120 sol_sumno3(j), sol_sumsolp(j), cn_prev, cn2(j)
END IFLine 1121
END IFLine 1123
CASE ("pheno_reset") Lines 1127-1146
1128 j = d_tbl%act(iac)%ob_num
1129 if (j == 0) j = ob_cur
1142 pcom(j)%dtbl(idtbl)%num_actions(iac) = pcom(j)%dtbl(idtbl)%num_actions(iac) + 1
1143 pcom(j)%dtbl(idtbl)%days_act(iac) = 1
1144 if (iac > 1) pcom(j)%dtbl(idtbl)%days_act(iac-1) =  0
IF (pcom(j)%dtbl(idtbl)%num_actions(iac) <= Int(d_tbl%act(iac)%const2)) THEN Lines 1131-1140
DO ipl = 1, pcom(j)%npl Lines 1132-1139
1133 idp = pcom(j)%plcur(ipl)%idplt
IF (pldb(idp)%trig == "moisture_gro") THEN Lines 1134-1138
1135 pcom(j)%plcur(ipl)%phuacc = 0.
1136 pcom(j)%plcur(ipl)%gro = "y"
1137 pcom(j)%plcur(ipl)%idorm = "n"
END IFLine 1138
END DOLine 1139
END IFLine 1140
CASE ("herd") Lines 1147-1148
END SELECTLine 1149
END IFLine 1150
END DOLine 1151
RETURN 1153 return
Allocations
n/a
Variables
Type Visibility Attributes Name Initial
integer, public :: ob_cur
integer, public :: ob_num
integer, public :: idtbl
Call graph
hru_control calls actions
mallo_control calls actions
sd_channel_control calls actions, wallo_control
sd_channel_control2 calls actions
sd_channel_control3 calls actions, wallo_control
time_control calls actions, mallo_control, command, wallo_control
wallo_demand calls actions
calhard_control calls time_control
calsoft_hyd calls time_control
calsoft_hyd_bfr_et calls time_control
calsoft_hyd_bfr_latq calls time_control
calsoft_hyd_bfr_perc calls time_control
calsoft_hyd_bfr_pet calls time_control
calsoft_hyd_bfr_surq calls time_control
calsoft_plant calls time_control
calsoft_sed calls time_control
caltsoft_hyd calls time_control
command calls hru_control, sd_channel_control3
wallo_control calls wallo_demand
main calls time_control, calhard_control, command, calsoft_control
calsoft_control calls calsoft_hyd, calsoft_plant, calsoft_sed, caltsoft_hyd, calsoft_hyd_bfr
calsoft_hyd_bfr calls calsoft_hyd_bfr_et, calsoft_hyd_bfr_latq, calsoft_hyd_bfr_perc, calsoft_hyd_bfr_pet, calsoft_hyd_bfr_surq
actions calls amax1, amin1, cn2_init, cs_fert, curno, hru_fr_change, hru_lum_init, mgt_harvbiomass, mgt_harvgrain, mgt_harvresidue, mgt_harvtuber, mgt_killop, mgt_newtillmix, mgt_newtillmix_wet, mgt_transplant, pest_apply, pl_burnop, pl_fert, pl_fert_wet, pl_graze, pl_manure, plant_init, salt_fert, structure_set_parms, wet_initial