allocate_parms – TestDataProject
allocate_parms Subroutine
152 statements
Source File
subroutine allocate_parms()
Called From
n/a
Arguments
n/a
Outside Variables and Types
real (115 attributes from hru_module)
Attribute Name Description
epmax
cvm_com
rsdco_plcom
translt
uno3d
uapd
par
htfac
un2
up2
qstemm
septic changes added 1/28/09 gsm
bio_bod
biom
rbiom
fcoli
bz_perc
plqm
Septic system by Jaehak Jeong
sol_sumno3
sol_sumsolp
sanyld
silyld
clayld
sagyld
lagyld
grayld
wnan
phusw
ranrns_hru
tc_gwat
wfsh
sed_con
orgn_con
orgp_con
soln_con
solp_con
filterw
cn2
smx
cnday
tconc
usle_cfac
usle_eifac
t_ov
canstor
ovrlnd
cumei
cumeira
cumrt
cumrai
sstmaxd
stmaxd
surqsolp
cklsp
pplnt
brt
twash
doxq
percn
cbodu
chl_a
qdr
latno3
latq
nplnt
tileno3
sedminpa
sedminps
sedorgn
sedorgp
sedyld
sepbtm
surfq
surqno3
surqsalt
latqsalt
tilesalt
percsalt
gwupsalt
urbqsalt
wetqsalt
wtspsalt
surqcs
rtb cs
latqcs
rtb cs
tilecs
rtb cs
perccs
rtb cs
gwupcs
rtb cs
urbqcs
rtb cs
sedmcs
rtb cs
irswcs
rtb cs
irgwcs
rtb cs
wetqcs
rtb cs
wtspcs
rtb cs
phubase
dormhr
wrt
bss
surf_bs
rateinf_prev
urb_abstinit
burn
gwsoilq
rtb gwflow
satexq
rtb gwflow
bss_ex
rtb gwflow
gwsoiln
rtb gwflow
gwsoilp
rtb gwflow
satexn
rtb gwflow
hhqday
ubnrunoff
ubntss
ovrlnd_dt
hhsurfq
hhsurf_bs
subdaily erosion modeling by Jaehak Jeong
hhsedy
init_abstrc
tillage_depth
tillage_factor
integer (14 attributes from hru_module)
Attribute Name Description
iseptic
septic variables for output.std
i_sep
sep_tsincefail
itb
!!!! drains
yr_skip
isweep
itill
swtrg
grz_days
igrz
ndeat
tillage_switch
tillage_days
mhyd
none |max number of hydrographs
Read more…
type (3 attributes from time_module)
Attribute Name Description
time%step None
sp_ob%hru None
sp_ob%chan None
Uses
hru_module
time_module
constituent_mass_module
hydrograph_module
I/O
n/a
Local Variables
Type Visibility Attributes Name Initial
integer, public :: mhru = 0
integer, public :: mch = 0
integer, public :: mpc = 0
initialize variables
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure. Use mouse wheel to zoom, drag to pan.
Reset Zoom Help
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
~ ~ ~ PURPOSE ~ ~ ~ (line 2)
this subroutine allocates array sizes (line 3)
~ ~ ~ INCOMING VARIABLES ~ ~ ~ (line 5)
name |units |definition (line 6)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ (line 7)
mhyd |none |max number of hydrographs (line 8)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ (line 9)
initialize variables (line 22)
drains (line 27)
arrays for plant communities (line 43)
septic changes added 1/28/09 gsm (line 48)
arrays for management output (output.mgt) (line 62)
arrays which contain data related to years of rotation, (line 68)
grazings per year, and HRUs (line 69)
arrays which contain data related to HRUs (line 72)
Drainmod tile equations 01/2006 (line 141)
sj aug 09 end (line 191)
Arrays for subdaily erosion modeling by Jaehak Jeong (line 196)
By Zhang for C/N cycling (line 213)
============================ (line 214)
zero reservoir module (line 221)
  23 mhyd = 1  !!added for jaehak vars
  24 mhru = sp_ob%hru
  25 mch = sp_ob%chan
  28 allocate (wnan(10), source = 0.)
  29 allocate (ranrns_hru(mhru), source = 0.)
  32 mpc = 20
  33 allocate (uno3d(mpc), source = 0.)
  34 allocate (uapd(mpc), source = 0.)
  35 allocate (un2(mpc), source = 0.)
  36 allocate (up2(mpc), source = 0.)
  37 allocate (translt(mpc), source = 0.)
  38 allocate (par(mpc), source = 0.)
  39 allocate (htfac(mpc), source = 0.)
  40 allocate (epmax(mpc), source = 0.)
  41 epmax = 0.
  44 allocate (cvm_com(mhru), source = 0.)
  45 allocate (rsdco_plcom(mhru), source = 0.)
  46 allocate (percn(mhru), source = 0.)
  49 allocate (i_sep(mhru), source = 0)
  50 allocate (sep_tsincefail(mhru), source = 0)
  51 allocate (qstemm(mhru), source = 0.)
  52 allocate (bio_bod(mhru), source = 0.)
  53 allocate (biom(mhru), source = 0.)
  54 allocate (rbiom(mhru), source = 0.)
  55 allocate (fcoli(mhru), source = 0.)
  56 allocate (bz_perc(mhru), source = 0.)
  57 allocate (plqm(mhru), source = 0.)
  58 allocate (itb(mhru), source = 0)
  60 allocate (hhqday(mhru,time%step), source = 0.)
  63 allocate (sol_sumno3(mhru), source = 0.)
  64 allocate (sol_sumsolp(mhru), source = 0.)
  66 allocate (iseptic(mhru), source = 0)
  70 allocate (grz_days(mhru), source = 0)
  73 allocate (brt(mhru), source = 0.)
  74 allocate (canstor(mhru), source = 0.)
  75 allocate (cbodu(mhru), source = 0.)
  76 allocate (chl_a(mhru), source = 0.)
  77 allocate (cklsp(mhru), source = 0.)
  78 allocate (cn2(mhru), source = 0.)
  79 allocate (cnday(mhru), source = 0.)
  81 allocate (cumei(mhru), source = 0.)
  82 allocate (cumeira(mhru), source = 0.)
  83 allocate (cumrt(mhru), source = 0.)
  84 allocate (cumrai(mhru), source = 0.)
  86 allocate (dormhr(mhru), source = 0.)
  87 allocate (doxq(mhru), source = 0.)
  88 allocate (filterw(mhru), source = 0.)
  89 allocate (igrz(mhru), source = 0)
  90 allocate (yr_skip(mhru), source = 0)
  91 allocate (isweep(mhru), source = 0)
  92 allocate (phusw(mhru), source = 0.)
  93 allocate (latno3(mhru), source = 0.)
  94 allocate (latq(mhru), source = 0.)
  95 allocate (ndeat(mhru), source = 0)
  96 allocate (nplnt(mhru), source = 0.)
  97 allocate (orgn_con(mhru), source = 0.)
  98 allocate (orgp_con(mhru), source = 0.)
  99 allocate (ovrlnd(mhru), source = 0.)
 100 allocate (phubase(mhru), source = 0.)
 102 allocate (pplnt(mhru), source = 0.)
 103 allocate (qdr(mhru), source = 0.)
 105 allocate (gwsoilq(mhru), source = 0.)  !rtb gwflow
 108 allocate (satexq(mhru), source = 0.)  !rtb gwflow
 111 allocate (gwsoiln(mhru), source = 0.)  !rtb gwflow
 114 allocate (gwsoilp(mhru), source = 0.)  !rtb gwflow
 117 allocate (satexn(mhru), source = 0.)  !rtb gwflow
 122 allocate (sstmaxd(mhru), source = 0.)
 124 allocate (sedminpa(mhru), source = 0.)
 125 allocate (sedminps(mhru), source = 0.)
 126 allocate (sedorgn(mhru), source = 0.)
 127 allocate (sedorgp(mhru), source = 0.)
 128 allocate (sedyld(mhru), source = 0.)
 130 allocate (sanyld(mhru), source = 0.)
 131 allocate (silyld(mhru), source = 0.)
 132 allocate (clayld(mhru), source = 0.)
 133 allocate (sagyld(mhru), source = 0.)
 134 allocate (lagyld(mhru), source = 0.)
 135 allocate (grayld(mhru), source = 0.)
 136 allocate (sed_con(mhru), source = 0.)
 137 allocate (sepbtm(mhru), source = 0.)
 138 allocate (smx(mhru), source = 0.)
 139 allocate (soln_con(mhru), source = 0.)
 140 allocate (solp_con(mhru), source = 0.)
 142 allocate (stmaxd(mhru), source = 0.)
 143 allocate (itill(mhru), source = 0)
 144 allocate (surfq(mhru), source = 0.)
 145 allocate (surqno3(mhru), source = 0.)
 146 allocate (surqsolp(mhru), source = 0.)
 147 allocate (swtrg(mhru), source = 0)
 148 allocate (rateinf_prev(mhru), source = 0.)
 149 allocate (urb_abstinit(mhru), source = 0.)
 150 allocate (t_ov(mhru), source = 0.)
 151 allocate (tconc(mhru), source = 0.)
 152 allocate (tc_gwat(mhru), source = 0.)
 153 allocate (tileno3(mhru), source = 0.)
 154 allocate (twash(mhru), source = 0.)
 155 allocate (usle_cfac(mhru), source = 0.)
 156 allocate (usle_eifac(mhru), source = 0.)
 157 allocate (wfsh(mhru), source = 0.)
 159 allocate (surqsalt(mhru,8), source = 0.)
 160 allocate (latqsalt(mhru,8), source = 0.)
 161 allocate (tilesalt(mhru,8), source = 0.)
 162 allocate (percsalt(mhru,8), source = 0.)
 163 allocate (gwupsalt(mhru,8), source = 0.)
 164 allocate (urbqsalt(mhru,8), source = 0.)
 165 allocate (wetqsalt(mhru,8), source = 0.)
 166 allocate (wtspsalt(mhru,8), source = 0.)
 168 allocate (surqcs(mhru,10), source = 0.)
 169 allocate (latqcs(mhru,10), source = 0.)
 170 allocate (tilecs(mhru,10), source = 0.)
 171 allocate (perccs(mhru,10), source = 0.)
 172 allocate (gwupcs(mhru,10), source = 0.)
 173 allocate (sedmcs(mhru,10), source = 0.)
 174 allocate (urbqcs(mhru,10), source = 0.)
 175 allocate (wetqcs(mhru,10), source = 0.)
 176 allocate (wtspcs(mhru,10), source = 0.)
 177 allocate (irswcs(mhru,10), source = 0.)
 178 allocate (irgwcs(mhru,10), source = 0.)
 180 allocate (bss(40,mhru), source = 0.)  !rtb salt/cs (changed to 40)
 183 allocate (bss_ex(10,mhru), source = 0.)  !rtb gwflow
 186 allocate (wrt(2,mhru), source = 0.)
 187 allocate (surf_bs(55,mhru), source = 0.)  !rtb salt/cs (changed to 55)
 192 allocate (hhsurf_bs(2,mhru,time%step), source = 0.)
 193 allocate (ubnrunoff(time%step), source = 0.)
 194 allocate (ubntss(time%step), source = 0.)
 197 allocate (hhsedy(mhru,time%step), source = 0.)
 198 allocate (ovrlnd_dt(mhru,time%step), source = 0.)
 199 allocate (init_abstrc(mhru), source = 0.)
 200 allocate (hhsurfq(mhru,time%step), source = 0.)
 203 allocate (tillage_switch(mhru), source = 0)
 204 allocate (tillage_depth(mhru), source = 0.)
 205 allocate (tillage_days(mhru), source = 0)
 206 allocate (tillage_factor(mhru), source = 0.)
 208 tillage_switch = 0
 209 tillage_depth = 0.
 210 tillage_days = 0
 211 tillage_factor = 0.
 216 call zero0
 217 call zero1
 218 call zero2
 219 call zeroini
 222 return
 223 end
Allocations
Memory allocations and deallocations grouped by variable.
Variable Allocations Deallocations
wnan line 28 none
ranrns_hru line 29 none
uno3d line 33 none
uapd line 34 none
un2 line 35 none
up2 line 36 none
translt line 37 none
par line 38 none
htfac line 39 none
epmax line 40 none
cvm_com line 44 none
rsdco_plcom line 45 none
percn line 46 none
i_sep line 49 none
sep_tsincefail line 50 none
qstemm line 51 none
bio_bod line 52 none
biom line 53 none
rbiom line 54 none
fcoli line 55 none
bz_perc line 56 none
plqm line 57 none
itb line 58 none
hhqday line 60 none
sol_sumno3 line 63 none
sol_sumsolp line 64 none
iseptic line 66 none
grz_days line 70 none
brt line 73 none
canstor line 74 none
cbodu line 75 none
chl_a line 76 none
cklsp line 77 none
cn2 line 78 none
cnday line 79 none
cumei line 81 none
cumeira line 82 none
cumrt line 83 none
cumrai line 84 none
dormhr line 86 none
doxq line 87 none
filterw line 88 none
igrz line 89 none
yr_skip line 90 none
isweep line 91 none
phusw line 92 none
latno3 line 93 none
latq line 94 none
ndeat line 95 none
nplnt line 96 none
orgn_con line 97 none
orgp_con line 98 none
ovrlnd line 99 none
phubase line 100 none
pplnt line 102 none
qdr line 103 none
gwsoilq line 105 none
satexq line 108 none
gwsoiln line 111 none
gwsoilp line 114 none
satexn line 117 none
sstmaxd line 122 none
sedminpa line 124 none
sedminps line 125 none
sedorgn line 126 none
sedorgp line 127 none
sedyld line 128 none
sanyld line 130 none
silyld line 131 none
clayld line 132 none
sagyld line 133 none
lagyld line 134 none
grayld line 135 none
sed_con line 136 none
sepbtm line 137 none
smx line 138 none
soln_con line 139 none
solp_con line 140 none
stmaxd line 142 none
itill line 143 none
surfq line 144 none
surqno3 line 145 none
surqsolp line 146 none
swtrg line 147 none
rateinf_prev line 148 none
urb_abstinit line 149 none
t_ov line 150 none
tconc line 151 none
tc_gwat line 152 none
tileno3 line 153 none
twash line 154 none
usle_cfac line 155 none
usle_eifac line 156 none
wfsh line 157 none
surqsalt line 159 none
latqsalt line 160 none
tilesalt line 161 none
percsalt line 162 none
gwupsalt line 163 none
urbqsalt line 164 none
wetqsalt line 165 none
wtspsalt line 166 none
surqcs line 168 none
latqcs line 169 none
tilecs line 170 none
perccs line 171 none
gwupcs line 172 none
sedmcs line 173 none
urbqcs line 174 none
wetqcs line 175 none
wtspcs line 176 none
irswcs line 177 none
irgwcs line 178 none
bss line 180 none
bss_ex line 183 none
wrt line 186 none
surf_bs line 187 none
hhsurf_bs line 192 none
ubnrunoff line 193 none
ubntss line 194 none
hhsedy line 197 none
ovrlnd_dt line 198 none
init_abstrc line 199 none
hhsurfq line 200 none
tillage_switch line 203 none
tillage_depth line 204 none
tillage_days line 205 none
tillage_factor line 206 none
Calls
Procedures Called
List of procedures called by this Subroutine.
zero0
zero1
zero2
zeroini
Call Graph
Visual representation of procedures called by this Subroutine.
Call graph
allocate_parms calls zero0, zero1, zero2, zeroini