aqu_1d_control – test-src-project
aqu_1d_control Subroutine
276 statements
Source File
subroutine aqu_1d_control()
Uses
aquifer_module
aqu_pesticide_module
salt_module
salt_aquifer
cs_aquifer
pesticide_data_module
climate_module
hydrograph_module
constituent_mass_module
maximum_data_module
ch_pesticide_module
time_module
Arguments
n/a
I/O
n/a
Outside Variables and Types
type(aquifer_database) (1 attribute from aquifer_module)
Attribute Name Description
aqu_dat
type(aquifer_data_parameters) (1 attribute from aquifer_module)
Attribute Name Description
aqu_prm
type(aquifer_dynamic) (1 attribute from aquifer_module)
Attribute Name Description
aqu_d
type(aqu_pesticide_output) (1 attribute from aqu_pesticide_module)
Attribute Name Description
aqupst_d
type(object_salt_balance_aqu) (1 attribute from salt_aquifer)
Attribute Name Description
asaltb_d
type(object_cs_balance_aqu) (1 attribute from cs_aquifer)
Attribute Name Description
acsb_d
type(pesticide_db) (1 attribute from pesticide_data_module)
Attribute Name Description
pestdb
type(pesticide_cp) (1 attribute from pesticide_data_module)
Attribute Name Description
pestcp
type(weather_station) (1 attribute from climate_module)
Attribute Name Description
wst
integer (2 attributes from hydrograph_module)
Attribute Name Description
iwst
|
icmd
|
type(hyd_output) (4 attributes from hydrograph_module)
Attribute Name Description
hd
hz
aqu
res
type(timestep) (1 attribute from hydrograph_module)
Attribute Name Description
ts
type (8 attributes from hydrograph_module)
Attribute Name Description
w_temp%gw None
cs_db%num_tot None
cs_db%num_cs None
cs_db%num_pests None
cs_db%pest_num None
cs_db%num_salts None
db_mx%aqu2d None
time%step None
type(object_connectivity) (1 attribute from hydrograph_module)
Attribute Name Description
ob
type(channel_aquifer_elements) (1 attribute from hydrograph_module)
Attribute Name Description
aq_ch
sorted by drainage area (smallest first)
type(constituent_mass) (2 attributes from constituent_mass_module)
Attribute Name Description
cs_aqu
hin_csz
type(all_constituent_hydrograph) (1 attribute from constituent_mass_module)
Attribute Name Description
obcs
type(gw_load_hydrograph) (1 attribute from constituent_mass_module)
Attribute Name Description
aq_chcs
!! Bang Comments
lag recharge from bottom of soil to water table ** disabled
add recharge to aquifer storage compute groundwater depth from surface compute flow and subtract from storage set hydrograph flow from aquifer- convert mm to m3 compute seepage through aquifer and subtract from storage compute revap (deep root uptake from aquifer) and subtract from storage compute nitrate recharge into the aquifer compute nitrate return flow out of aquifer (kg/ha / mm) kg = (kg/ha / mm) * mm * ha compute NO3 lost in the aquifer compute nitrate seepage out of aquifer kg/ha = (kg/ha / mm) * mm compute mineral p flow (constant concentration) from aquifer - m^3 * ppm * 1000 kg/m^3 = 1/1000 temperature of aquifer flow compute fraction of flow to each channel in the aquifer if connected to aquifer - add flow find the first channel contributing set fractions for flow to each channel save hydrographs to distribute on following day compute pesticide transport and decay set initial pesticide at start of day add incoming pesticide to storage compute pesticide decay in the aquifer add decay to daughter pesticides compute pesticide in aquifer flow assume specific yield = upper limit (effective vs total porosity) and bulk density of 2.0 (ave of rock and soil - 2.65 and 1.35) mm = (mm/mm + (m^3/ton)*(ton/m^3)) * m * 1000. compute volume of flow through the layer - mm compute concentration in the flow return flow (1) and deep seepage (2) kg = kg/mm * mm set pesticide output variables - kg assume frsol = 1 (all soluble) all soluble - may add later compute outflow objects (flow to channels, reservoirs, or aquifer) if flow from hru is directly routed sum outflow to channels, reservoirs and other aquifers total ingoing and outgoing (retuen flow + percolation) for output to SWIFT
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure.
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
  56 iaq = ob(icmd)%num
  57 iaqdb = ob(icmd)%props
  58 iwst = ob(icmd)%wst
  59 stor_init = aqu_d(iaq)%stor
  61 ob(icmd)%hd(1) = hz
  62 ob(icmd)%hd(2) = hz
IF (cs_db%num_tot > 0) THEN Lines 63-66
  64 obcs(icmd)%hd(1) = hin_csz
  65 obcs(icmd)%hd(2) = hin_csz
END IFLine 66
  69 aqu_d(iaq)%rchrg = ob(icmd)%hin%flo / (10. * ob(icmd)%area_ha)
IF (cs_db%num_salts > 0) THEN Lines 73-75
  74 call salt_chem_aqu
END IFLine 75
IF (cs_db%num_cs > 0) THEN Lines 79-82
  80 call cs_rctn_aqu
  81 call cs_sorb_aqu
END IFLine 82
  87 aqu_prm(iaq)%rchrg_prev = aqu_d(iaq)%rchrg
  90 aqu_d(iaq)%stor = aqu_d(iaq)%stor + aqu_d(iaq)%rchrg
  93 aqu_d(iaq)%dep_wt = aqu_dat(iaq)%dep_bot - (aqu_d(iaq)%stor / (1000. * aqu_dat(iaq)%spyld))
  94 aqu_d(iaq)%dep_wt = max (0., aqu_d(iaq)%dep_wt)
IF (aqu_d(iaq)%dep_wt <= aqu_dat(iaq)%flo_min) THEN Lines 97-101
  98 aqu_d(iaq)%flo = aqu_d(iaq)%flo * aqu_prm(iaq)%alpha_e + aqu_d(iaq)%rchrg * (1. - aqu_prm(iaq)%alpha_e)
  99 aqu_d(iaq)%flo = Max (0., aqu_d(iaq)%flo)
 100 aqu_d(iaq)%flo = Min (aqu_d(iaq)%stor, aqu_d(iaq)%flo)
 101 aqu_d(iaq)%stor = aqu_d(iaq)%stor - aqu_d(iaq)%flo
END IFLine 101
ELSE Lines 102-104
 103 aqu_d(iaq)%flo = 0.
END IF Line 104
 107 ob(icmd)%hd(1)%flo = 10. * aqu_d(iaq)%flo * ob(icmd)%area_ha
 110 aqu_d(iaq)%seep = aqu_d(iaq)%rchrg * aqu_dat(iaq)%seep
 111 aqu_d(iaq)%seep = amin1 (aqu_d(iaq)%seep, aqu_d(iaq)%stor)
 112 ob(icmd)%hd(2)%flo = 10. * aqu_d(iaq)%seep * ob(icmd)%area_ha
 114 aqu_d(iaq)%stor = aqu_d(iaq)%stor - aqu_d(iaq)%seep
IF (aqu_d(iaq)%dep_wt < aqu_dat(iaq)%revap_min) THEN Lines 117-120
 118 aqu_d(iaq)%revap = wst(iwst)%weat%pet * aqu_dat(iaq)%revap_co
 119 aqu_d(iaq)%revap = amin1 (aqu_d(iaq)%revap, aqu_d(iaq)%stor)
 120 aqu_d(iaq)%stor = aqu_d(iaq)%stor - aqu_d(iaq)%revap
END IFLine 120
ELSE Lines 121-123
 122 aqu_d(iaq)%revap = 0.
END IF Line 123
 126 aqu_d(iaq)%no3_rchg = ob(icmd)%hin%no3 / ob(icmd)%area_ha
 127 aqu_d(iaq)%no3_st = aqu_d(iaq)%no3_st + aqu_d(iaq)%no3_rchg
 128 aqu_prm(iaq)%rchrgn_prev = aqu_d(iaq)%no3_rchg
IF (aqu_d(iaq)%stor > 1.e-6) THEN Lines 131-133
 133 conc_no3 = aqu_d(iaq)%no3_st / aqu_d(iaq)%stor
END IFLine 133
ELSE Lines 134-136
 135 conc_no3 = 0.
END IF Line 136
 138 ob(icmd)%hd(1)%no3 = (conc_no3 * aqu_d(iaq)%flo) * ob(icmd)%area_ha
 139 ob(icmd)%hd(1)%no3 = amin1(ob(icmd)%hd(1)%no3, (aqu_d(iaq)%no3_st * ob(icmd)%area_ha))
 140 aqu_d(iaq)%no3_lat = ob(icmd)%hd(1)%no3 / ob(icmd)%area_ha
 141 aqu_d(iaq)%no3_st = aqu_d(iaq)%no3_st - aqu_d(iaq)%no3_lat
 146 no3_init = aqu_d(iaq)%no3_st
 147 aqu_d(iaq)%no3_st = aqu_d(iaq)%no3_st * aqu_prm(iaq)%nloss
 148 aqu_d(iaq)%no3_loss = no3_init - aqu_d(iaq)%no3_st
 152 aqu_d(iaq)%no3_seep = conc_no3 * aqu_d(iaq)%seep
 153 aqu_d(iaq)%no3_seep = amin1(aqu_d(iaq)%no3_seep, aqu_d(iaq)%no3_st)
 154 aqu_d(iaq)%no3_st = aqu_d(iaq)%no3_st - aqu_d(iaq)%no3_seep
 155 ob(icmd)%hd(2)%no3 = aqu_d(iaq)%no3_seep * ob(icmd)%area_ha
DO m=1,cs_db%num_salts Lines 159-163
 160 salt_recharge = obcs(icmd)%hin(1)%salt(m) !kg
 161 cs_aqu(iaq)%salt(m) = cs_aqu(iaq)%salt(m) + salt_recharge !kg
 162 asaltb_d(iaq)%salt(m)%rchrg = salt_recharge
END DOLine 163
DO m=1,cs_db%num_salts Lines 165-203
 167 gw_volume = (aqu_d(iaq)%stor/1000.) * (ob(icmd)%area_ha*10000.) !m3 of groundwater
 174 gw_discharge = (aqu_d(iaq)%flo/1000.) * (ob(icmd)%area_ha*10000.) !mm --> m3
 175 salt_discharge = (cs_aqu(iaq)%saltc(m)*gw_discharge) / 1000. !kg
 180 cs_aqu(iaq)%salt(m) = cs_aqu(iaq)%salt(m) - salt_discharge !kg (update salt storage)
 181 obcs(icmd)%hd(1)%salt(m) = salt_discharge !kg (store salt loading, for input to streams)
 182 if (db_mx%aqu2d > 0) then !save to distribute on following day (if aqu2d method is used, with "aqu_cha.lin" file)
 183 aq_chcs(iaq)%hd(1)%salt(m) = obcs(icmd)%hd(1)%salt(m) !save to distribute on following day
 185 asaltb_d(iaq)%salt(m)%saltgw = obcs(icmd)%hd(1)%salt(m) !kg (store for daily output)
 187 gw_seep = (aqu_d(iaq)%seep/1000.) * (ob(icmd)%area_ha*10000.) !m3 of groundwater
 188 salt_seep = (cs_aqu(iaq)%saltc(m) * gw_seep) / 1000. !kg
 192 cs_aqu(iaq)%salt(m) = cs_aqu(iaq)%salt(m) - salt_seep !kg (update salt storage)
 193 asaltb_d(iaq)%salt(m)%seep = salt_seep !kg (store for daily output)
 194 obcs(icmd)%hd(2)%salt(m) = asaltb_d(iaq)%salt(m)%seep
 201 asaltb_d(iaq)%salt(m)%mass = cs_aqu(iaq)%salt(m) !store mass for output
 202 asaltb_d(iaq)%salt(m)%conc = cs_aqu(iaq)%saltc(m) !store concentration for output
IF (gw_volume.gt.0) THEN Lines 168-169
 169 cs_aqu(iaq)%saltc(m) = (cs_aqu(iaq)%salt(m) * 1000.) / gw_volume !g/m3 = mg/L
END IFLine 169
ELSE Lines 170-172
 171 cs_aqu(iaq)%saltc(m) = 0.
END IF Line 172
IF (salt_discharge .gt. cs_aqu(iaq)%salt(m)) THEN Lines 177-179
 178 salt_discharge = cs_aqu(iaq)%salt(m)
END IFLine 179
IF (salt_seep.gt.cs_aqu(iaq)%salt(m)) THEN Lines 189-191
 190 salt_seep = cs_aqu(iaq)%salt(m)
END IFLine 191
IF (gw_volume.gt.0) THEN Lines 196-197
 197 cs_aqu(iaq)%saltc(m) = (cs_aqu(iaq)%salt(m) * 1000.) / gw_volume !g/m3 = mg/L
END IFLine 197
ELSE Lines 198-200
 199 cs_aqu(iaq)%saltc(m) = 0.
END IF Line 200
END DOLine 203
DO ics=1,cs_db%num_cs Lines 207-211
 208 cs_recharge = obcs(icmd)%hin(1)%cs(ics) !kg
 209 cs_aqu(iaq)%cs(ics) = cs_aqu(iaq)%cs(ics) + cs_recharge !kg
 210 acsb_d(iaq)%cs(ics)%rchrg = cs_recharge
END DOLine 211
DO ics=1,cs_db%num_cs Lines 213-251
 215 gw_volume = (aqu_d(iaq)%stor/1000.) * (ob(icmd)%area_ha*10000.) !m3 of groundwater
 222 gw_discharge = (aqu_d(iaq)%flo/1000.) * (ob(icmd)%area_ha*10000.) !mm --> m3
 223 cs_discharge = (cs_aqu(iaq)%csc(ics)*gw_discharge) / 1000. !kg
 228 cs_aqu(iaq)%cs(ics) = cs_aqu(iaq)%cs(ics) - cs_discharge !kg (update constituent mass storage)
 229 obcs(icmd)%hd(1)%cs(ics) = cs_discharge !kg (store constituent loading, for input to streams)
 230 if (db_mx%aqu2d > 0) then !save to distribute on following day (if aqu2d method is used, with "aqu_cha.lin" file)
 231 aq_chcs(iaq)%hd(1)%cs(ics) = obcs(icmd)%hd(1)%cs(ics)
 233 acsb_d(iaq)%cs(ics)%csgw = obcs(icmd)%hd(1)%cs(ics) !kg (store for daily output)
 235 gw_seep = (aqu_d(iaq)%seep/1000.) * (ob(icmd)%area_ha*10000.) !m3 of groundwater
 236 cs_seep = (cs_aqu(iaq)%csc(ics) * gw_seep) / 1000. !kg
 240 cs_aqu(iaq)%cs(ics) = cs_aqu(iaq)%cs(ics) - cs_seep !kg (update constituent mass storage)
 241 acsb_d(iaq)%cs(ics)%seep = cs_seep !kg (store for daily output)
 242 obcs(icmd)%hd(2)%cs(ics) = acsb_d(iaq)%cs(ics)%seep
 249 acsb_d(iaq)%cs(ics)%mass = cs_aqu(iaq)%cs(ics)  !store mass for output
 250 acsb_d(iaq)%cs(ics)%conc = cs_aqu(iaq)%csc(ics) !store concentration for output
IF (gw_volume.gt.0) THEN Lines 216-217
 217 cs_aqu(iaq)%csc(ics) = (cs_aqu(iaq)%cs(ics) * 1000.) / gw_volume !g/m3 = mg/L
END IFLine 217
ELSE Lines 218-220
 219 cs_aqu(iaq)%csc(ics) = 0.
END IF Line 220
IF (cs_discharge .gt. cs_aqu(iaq)%cs(ics)) THEN Lines 225-227
 226 cs_discharge = cs_aqu(iaq)%cs(ics)
END IFLine 227
IF (cs_seep.gt.cs_aqu(iaq)%cs(ics)) THEN Lines 237-239
 238 cs_seep = cs_aqu(iaq)%cs(ics)
END IFLine 239
IF (gw_volume.gt.0) THEN Lines 244-245
 245 cs_aqu(iaq)%csc(ics) = (cs_aqu(iaq)%cs(ics) * 1000.) / gw_volume !g/m3 = mg/L
END IFLine 245
ELSE Lines 246-248
 247 cs_aqu(iaq)%csc(ics) = 0.
END IF Line 248
END DOLine 251
 254 aqu_d(iaq)%minp = ob(icmd)%hin%flo * aqu_dat(iaq)%minp / 1000.
 255 ob(icmd)%hd(1)%solp = aqu_d(iaq)%minp
 258 ob(icmd)%hd(1)%temp = w_temp%gw
IF (db_mx%aqu2d > 0) THEN Lines 262-284
 263 contrib_len = aq_ch(iaq)%len_tot * aqu_d(iaq)%flo / aqu_dat(iaq)%bf_max
 266 icontrib = 0
 283 aq_ch(iaq)%hd = ob(icmd)%hd(1)
DO icha = 1, aq_ch(iaq)%num_tot Lines 267-273
IF (contrib_len >= aq_ch(iaq)%ch(icha)%len_left) THEN Lines 268-272
 269 icontrib = icha
 270 contrib_len_left = aq_ch(iaq)%ch(icha)%len_left + aq_ch(iaq)%ch(icha)%len
 271 exit
END IFLine 272
END DOLine 273
DO icha = 1, aq_ch(iaq)%num_tot Lines 275-281
IF (icha >= icontrib .and. icontrib > 0) THEN Lines 276-277
 277 aq_ch(iaq)%ch(icha)%flo_fr = aq_ch(iaq)%ch(icha)%len / contrib_len_left
END IFLine 277
ELSE Lines 278-280
 279 aq_ch(iaq)%ch(icha)%flo_fr = 0.
END IF Line 280
END DOLine 281
END IFLine 284
DO ipest = 1, cs_db%num_pests Lines 287-347
 288 ipest_db = cs_db%pest_num(ipest)
 291 pest_init = cs_aqu(iaq)%pest(ipest)
 294 cs_aqu(iaq)%pest(ipest) = cs_aqu(iaq)%pest(ipest) + obcs(icmd)%hin(1)%pest(ipest)
 297 aqupst_d(iaq)%pest(ipest)%react = 0.
 313 kd = pestdb(ipest_db)%koc * aqu_dat(iaq)%cbn / 100.
 317 zdb1 = (aqu_dat(iaq)%spyld + kd * 2.0) * aqu_dat(iaq)%flo_dist * 1000.
 320 flow_mm = aqu_d(iaq)%flo + aqu_d(iaq)%seep
 321 obcs(icmd)%hd(1)%pest(ipest) = 0.
 322 obcs(icmd)%hd(2)%pest(ipest) = 0.
 339 aqupst_d(iaq)%pest(ipest)%tot_in = obcs(icmd)%hin(1)%pest(ipest)
 341 aqupst_d(iaq)%pest(ipest)%sol_flo = obcs(icmd)%hd(1)%pest(ipest)
 342 aqupst_d(iaq)%pest(ipest)%sor_flo = 0.      !! all soluble - may add later
 343 aqupst_d(iaq)%pest(ipest)%sol_perc = obcs(icmd)%hd(2)%pest(ipest)
 344 aqupst_d(iaq)%pest(ipest)%stor_ave = cs_aqu(iaq)%pest(ipest)
 345 aqupst_d(iaq)%pest(ipest)%stor_init = pest_init
 346 aqupst_d(iaq)%pest(ipest)%stor_final = cs_aqu(iaq)%pest(ipest)
IF (cs_aqu(iaq)%pest(ipest) > 0.) THEN Lines 298-310
 299 aqupst_d(iaq)%pest(ipest)%react = cs_aqu(iaq)%pest(ipest) * (1. - pestcp(ipest_db)%decay_s)
 300 cs_aqu(iaq)%pest(ipest) =  cs_aqu(iaq)%pest(ipest) * pestcp(ipest_db)%decay_s
DO imeta = 1, pestcp(ipest_db)%num_metab Lines 302-309
 303 ipseq = pestcp(ipest_db)%daughter(imeta)%num
 304 ipdb = cs_db%pest_num(ipseq)
 305 mol_wt_rto = pestdb(ipdb)%mol_wt / pestdb(ipest_db)%mol_wt
 306 aqupst_d(iaq)%pest(ipseq)%metab = aqupst_d(iaq)%pest(ipseq)%metab + aqupst_d(iaq)%pest(ipest)%react *     &
 307 pestcp(ipest_db)%daughter(imeta)%soil_fr * mol_wt_rto
 308 cs_aqu(iaq)%pest(ipseq) = cs_aqu(iaq)%pest(ipseq) + aqupst_d(iaq)%pest(ipseq)%metab
END DOLine 309
END IFLine 310
IF (cs_aqu(iaq)%pest(ipest) >= 1.e-12 .and. flow_mm > 0.) THEN Lines 325-336
 326 pest_kg =  cs_aqu(iaq)%pest(ipest) * (1. - Exp(-flow_mm / (zdb1 + 1.e-6)))
 327 conc = pest_kg / flow_mm
 328 conc = Min (pestdb(ipest_db)%solub / 100., conc)      ! check solubility
 329 pest_kg = conc * flow_mm
 330 if (pest_kg >  cs_aqu(iaq)%pest(ipest)) pest_kg = cs_aqu(iaq)%pest(ipest)
 333 obcs(icmd)%hd(1)%pest(ipest) = pest_kg * aqu_d(iaq)%flo / flow_mm
 334 obcs(icmd)%hd(2)%pest(ipest) = pest_kg * aqu_d(iaq)%seep / flow_mm
 335 cs_aqu(iaq)%pest(ipest) =  cs_aqu(iaq)%pest(ipest) - pest_kg
END IFLine 336
END DOLine 347
 351 iob_out = icmd
 352 aqu_d(iaq)%flo_cha = 0.
 353 aqu_d(iaq)%flo_res = 0.
 354 aqu_d(iaq)%flo_ls = 0.
DO iout = 1, ob(iob_out)%src_tot Lines 355-369
IF (ob(iob_out)%htyp_out(iout) == "tot") THEN Lines 357-368
SELECT CASE (ob(iob_out)%obtyp_out(iout)) Lines 358-367
CASE ("cha") Lines 359-360
 360 aqu_d(iaq)%flo_cha = aqu_d(iaq)%flo_cha + aqu_d(iaq)%flo * ob(iob_out)%frac_out(iout)
CASE ("sdc") Lines 361-362
 362 aqu_d(iaq)%flo_cha = aqu_d(iaq)%flo_cha + aqu_d(iaq)%flo * ob(iob_out)%frac_out(iout)
CASE ("res") Lines 363-364
 364 aqu_d(iaq)%flo_res = aqu_d(iaq)%flo_res + aqu_d(iaq)%flo * ob(iob_out)%frac_out(iout)
CASE ("aqu") Lines 365-366
 366 aqu_d(iaq)%flo_ls = aqu_d(iaq)%flo_ls + aqu_d(iaq)%flo * ob(iob_out)%frac_out(iout)
END SELECTLine 367
END IFLine 368
END DOLine 369
 372 ob(icmd)%hin_tot = ob(icmd)%hin_tot + ob(icmd)%hin
 373 ob(icmd)%hout_tot = ob(icmd)%hout_tot + ob(icmd)%hd(1) + ob(icmd)%hd(2)
DO ii = 1, time%step Lines 376-379
 377 step = real(time%step)
 378 ob(icmd)%ts(1,ii) = ob(icmd)%hd(1) / step
END DOLine 379
 382 return
Allocations
n/a
Calls
Calls
Procedures called by this subroutine.
Local Variables
Type Visibility Attributes Name Initial
integer, private :: iaq
integer, private :: iaqdb
integer, private :: icha
integer, private :: iob_out
integer, private :: iout
integer, private :: ii
integer, private :: icontrib
integer, private :: ipest
integer, private :: ipest_db
integer, private :: ipseq
integer, private :: ipdb
integer, private :: imeta
real, private :: mol_wt_rto
real, private :: stor_init
real, private :: conc_no3
real, private :: step
real, private :: contrib_len
real, private :: contrib_len_left
real, private :: pest_init
real, private :: no3_init
real, private :: flow_mm
real, private :: pest_kg
real, private :: conc
real, private :: zdb1
real, private :: kd
real, private :: gw_volume
real, private :: salt_recharge
real, private :: gw_discharge
real, private :: salt_discharge
real, private :: gw_seep
real, private :: salt_seep
real, private :: cs_recharge
real, private :: cs_discharge
real, private :: cs_seep
integer, private :: m
integer, private :: ics
Call graph
aqu_1d_control calls amin1, cs_rctn_aqu, cs_sorb_aqu, salt_chem_aqu