cal_parm_select – TestDataProject
cal_parm_select Subroutine
573 statements
Source File
subroutine cal_parm_select(ielem, ly, chg_parm, chg_typ, chg_val, absmin, absmax, num_db)
Called From
n/a
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ielem
integer, intent(in) :: ly
character(len=16), intent(in) :: chg_parm
character(len=16), intent(in) :: chg_typ
real, intent(in) :: chg_val
real, intent(in) :: absmin
real, intent(in) :: absmax
integer, intent(in) :: num_db
Outside Variables and Types
type (35 attributes from basin_module)
Attribute Name Description
bsn_cc%gwflow None
bsn_prm%evrch None
bsn_prm%plaps None
bsn_prm%psp None
bsn_prm%msk_co1 None
bsn_prm%rsd_covco None
bsn_prm%tb_adj None
bsn_prm%sdnco None
bsn_prm%msk_co2 None
bsn_prm%adj_pkr None
bsn_prm%evlai None
bsn_prm%phoskd None
bsn_prm%msk_x None
bsn_prm%percop None
bsn_prm%prf None
bsn_prm%ffcb None
bsn_prm%cmn None
bsn_prm%rsdco None
bsn_prm%nperco_lchtile None
bsn_prm%surlag None
bsn_prm%nperco None
bsn_prm%tlaps None
bsn_prm%cdn None
bsn_prm%dorm_hr None
bsn_prm%n_updis None
bsn_prm%pperco None
sp_ob%hru None
sdr%latksat None
sdr%drain_co None
sdr%radius None
sdr%time None
sdr%pumpcap None
sdr%lag None
sdr%dist None
luse%ovn None
type(reservoir_hyd_data) (1 attribute from reservoir_data_module)
Attribute Name Description
res_hyd
type(water_body_data_parameters) (1 attribute from reservoir_data_module)
Attribute Name Description
res_prm
type(decision_table) (1 attribute from conditional_module)
Attribute Name Description
dtbl_res
type(swatdeg_channel_dynamic) (1 attribute from sd_channel_module)
Attribute Name Description
sd_ch
type(plant_community) (1 attribute from plant_module)
Attribute Name Description
pcom
type(soil_profile) (1 attribute from soil_module)
Attribute Name Description
soil
type(plant_db) (1 attribute from plant_data_module)
Attribute Name Description
pldb
type(hyd_output) (1 attribute from hydrograph_module)
Attribute Name Description
res
type(reservoir) (1 attribute from reservoir_module)
Attribute Name Description
res_ob
type(hydrologic_response_unit) (1 attribute from hru_module)
Attribute Name Description
hru
integer (3 attributes from hru_module)
Attribute Name Description
ipl
isol
ihru
none |HRU number
Read more…
real (5 attributes from hru_module)
Attribute Name Description
cn2
tconc
brt
gw_delay
|
gw_bed_change
|
type(field) (3 attributes from hru_module)
Attribute Name Description
field%wid None
field%ang None
field%length None
type(soil_profile_mass) (1 attribute from organic_mineral_mass_module)
Attribute Name Description
soil1
type(pesticide_db) (1 attribute from pesticide_data_module)
Attribute Name Description
pestdb
type(groundwater_state) (1 attribute from gwflow_module)
Attribute Name Description
gw_state
type(cell_channel_info) (1 attribute from gwflow_module)
Attribute Name Description
gw_chan_info
type(channel_nut_data) (1 attribute from channel_data_module)
Attribute Name Description
ch_nut
type(swatdeg_hru_data) (1 attribute from hru_lte_module)
Attribute Name Description
hlt_db
type(swatdeg_hru_dynamic) (1 attribute from hru_lte_module)
Attribute Name Description
hlt
type(aquifer_database) (1 attribute from aquifer_module)
Attribute Name Description
aqu_dat
type(aquifer_data_parameters) (1 attribute from aquifer_module)
Attribute Name Description
aqu_prm
type(aquifer_dynamic) (1 attribute from aquifer_module)
Attribute Name Description
aqu_d
Uses
basin_module
reservoir_data_module
conditional_module
sd_channel_module
plant_module
soil_module
plant_data_module
hydrograph_module
reservoir_module
hru_module
channel_module
organic_mineral_mass_module
pesticide_data_module
gwflow_module
channel_data_module
hru_lte_module
aquifer_module
I/O
n/a
Local Variables
Type Visibility Attributes Name Initial
integer, public :: jj = 0
integer, public :: ipl = 0
integer, public :: ihru = 0
integer, public :: icell
real, public :: exp
real, public :: c_val = 0.
real, public :: abmax = 0.
real, public :: chg_par
real, public :: perc_ln_func = 0.
real, public :: rock = 0.
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure. Use mouse wheel to zoom, drag to pan.
Reset Zoom Help
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
SELECT CASE (chg_parm) Lines 61-1013
CASE ("cn2") Lines 63-67
  64 cn2(ielem) = chg_par (cn2(ielem), chg_typ, chg_val, absmin, absmax)
  65 call curno (cn2(ielem), ielem)
CASE ("biomix") Lines 68-71
  69 hru(ielem)%hyd%biomix = chg_par (hru(ielem)%hyd%biomix,           &
  70 chg_typ, chg_val, absmin, absmax)
CASE ("cn3_swf") Lines 72-79
don't change for tile *********************Mike (line 73)
don't change for tile *********************Mike (line 73)
IF (hru(ielem)%tiledrain == 0) THEN Lines 74-78
  75 hru(ielem)%hyd%cn3_swf = chg_par (hru(ielem)%hyd%cn3_swf,         &
  76 chg_typ, chg_val, absmin, absmax)
  77 call curno (cn2(ielem), ielem)
END IFLine 78
CASE ("usle_p") Lines 80-83
  81 hru(ielem)%lumv%usle_p = chg_par (hru(ielem)%lumv%usle_p,         &
  82 chg_typ, chg_val, absmin, absmax)
CASE ("usle_c") Lines 84-87
  85 pldb(ielem)%usle_c = chg_par (pldb(ielem)%usle_c,         &
  86 chg_typ, chg_val, absmin, absmax)
CASE ("ovn") Lines 88-91
  89 hru(ielem)%luse%ovn = chg_par (hru(ielem)%luse%ovn,               &
  90 chg_typ, chg_val, absmin, absmax)
CASE ("elev") Lines 92-95
  93 hru(ielem)%topo%elev = chg_par (hru(ielem)%topo%elev,             &
  94 chg_typ, chg_val, absmin, absmax)
CASE ("slope") Lines 96-99
  97 hru(ielem)%topo%slope = chg_par (hru(ielem)%topo%slope,           &
  98 chg_typ, chg_val, absmin, absmax)
CASE ("slope_len") Lines 100-103
 101 hru(ielem)%topo%slope_len = chg_par(hru(ielem)%topo%slope_len,    &
 102 chg_typ, chg_val, absmin, absmax)
CASE ("lat_ttime") Lines 104-108
 105 hru(ielem)%hyd%lat_ttime = chg_par(hru(ielem)%hyd%lat_ttime,      &
 106 chg_typ, chg_val, absmin, absmax)
 107 hru(ielem)%hyd%lat_ttime = 1. - Exp(-1. / hru(ielem)%hyd%lat_ttime)
CASE ("lat_sed") Lines 109-112
 110 hru(ielem)%hyd%lat_sed = chg_par (hru(ielem)%hyd%lat_sed,         &
 111 chg_typ, chg_val, absmin, absmax)
CASE ("lat_len") Lines 113-116
 114 hru(ielem)%topo%lat_len = chg_par (hru(ielem)%topo%lat_len,     &
 115 chg_typ, chg_val, absmin, absmax)
CASE ("latq_co") Lines 117-120
 118 hru(ielem)%hyd%latq_co = chg_par (hru(ielem)%hyd%latq_co,       &
 119 chg_typ, chg_val, absmin, absmax)
CASE ("canmx") Lines 121-124
 122 hru(ielem)%hyd%canmx = chg_par (hru(ielem)%hyd%canmx,           &
 123 chg_typ, chg_val, absmin, absmax)
CASE ("esco") Lines 125-128
 126 hru(ielem)%hyd%esco = chg_par (hru(ielem)%hyd%esco,             &
 127 chg_typ, chg_val, absmin, absmax)
CASE ("epco") Lines 129-136
set epco parameter for each crop (line 132)
 130 hru(ielem)%hyd%epco = chg_par (hru(ielem)%hyd%epco,             &
 131 chg_typ, chg_val, absmin, absmax)
DO ipl = 1, pcom(ielem)%npl Lines 133-135
 134 pcom(ielem)%plcur(ipl)%epco = hru(ielem)%hyd%epco
END DOLine 135
CASE ("erorgn") Lines 137-140
 138 hru(ielem)%hyd%erorgn = chg_par (hru(ielem)%hyd%erorgn,         &
 139 chg_typ, chg_val, absmin, absmax)
CASE ("erorgp") Lines 141-144
 142 hru(ielem)%hyd%erorgp = chg_par (hru(ielem)%hyd%erorgp,         &
 143 chg_typ, chg_val, absmin, absmax)
CASE ("dis_stream") Lines 145-148
 146 hru(ielem)%topo%dis_stream = chg_par(hru(ielem)%topo%dis_stream,&
 147 chg_typ, chg_val, absmin, absmax)
CASE ("perco") Lines 149-162
don't change for tile *********************Mike (line 150)
don't change for tile *********************Mike (line 150)
IF (hru(ielem)%tiledrain == 0) THEN Lines 151-161
 152 hru(ielem)%hyd%perco = chg_par (hru(ielem)%hyd%perco,           &
 153 chg_typ, chg_val, absmin, absmax)
IF (hru(ielem)%hyd%perco > 1.e-9) THEN Lines 154-157
 155 perc_ln_func = 1.0052 * log(-log(hru(ielem)%hyd%perco - 1.e-6)) + 5.6862
 156 hru(ielem)%hyd%perco_lim = exp(-perc_ln_func)
 157 hru(ielem)%hyd%perco_lim = amin1 (1., hru(ielem)%hyd%perco_lim)
END IFLine 157
ELSE Lines 158-160
 159 hru(ielem)%hyd%perco_lim = 0.
END IF Line 160
END IFLine 161
CASE ("petco") Lines 163-166
 164 hru(ielem)%hyd%pet_co = chg_par (hru(ielem)%hyd%pet_co,     &
 165 chg_typ, chg_val, absmin, absmax)
CASE ("lat_orgn") Lines 167-170
 168 hru(ielem)%hyd%lat_orgn = chg_par (hru(ielem)%hyd%lat_orgn,     &
 169 chg_typ, chg_val, absmin, absmax)
CASE ("lat_orgp") Lines 171-174
 172 hru(ielem)%hyd%lat_orgp = chg_par (hru(ielem)%hyd%lat_orgp,     &
 173 chg_typ, chg_val, absmin, absmax)
CASE ("field_len") Lines 175-178
 176 hru(ielem)%field%length = chg_par(hru(ielem)%field%length,      &
 177 chg_typ, chg_val, absmin, absmax)
CASE ("field_wid") Lines 179-182
 180 hru(ielem)%field%wid = chg_par(hru(ielem)%field%wid,            &
 181 chg_typ, chg_val, absmin, absmax)
CASE ("field_ang") Lines 183-186
 184 hru(ielem)%field%ang = chg_par(hru(ielem)%field%ang,            &
 185 chg_typ, chg_val, absmin, absmax)
CASE ("snofall_tmp") Lines 187-190
 188 hru(ielem)%sno%falltmp = chg_par(hru(ielem)%sno%falltmp,        &
 189 chg_typ, chg_val, absmin, absmax)
CASE ("snomelt_tmp") Lines 191-194
 192 hru(ielem)%sno%melttmp = chg_par(hru(ielem)%sno%melttmp,        &
 193 chg_typ, chg_val, absmin, absmax)
CASE ("snomelt_max") Lines 195-198
 196 hru(ielem)%sno%meltmx = chg_par(hru(ielem)%sno%meltmx,        &
 197 chg_typ, chg_val, absmin, absmax)
CASE ("snomelt_min") Lines 199-202
 200 hru(ielem)%sno%meltmn = chg_par(hru(ielem)%sno%meltmn,        &
 201 chg_typ, chg_val, absmin, absmax)
CASE ("snomelt_lag") Lines 203-206
 204 hru(ielem)%sno%timp = chg_par(hru(ielem)%sno%timp,            &
 205 chg_typ, chg_val, absmin, absmax)
CASE ("tile_dep") Lines 207-219
define soil layer the drainage tile is in (line 210)
define soil layer the drainage tile is in (line 210)
 208 hru(ielem)%lumv%sdr_dep = chg_par(hru(ielem)%lumv%sdr_dep,      &
 209 chg_typ, chg_val, absmin, absmax)
IF (hru(ielem)%lumv%sdr_dep > 0) THEN Lines 211-215
DO jj = 1, soil(ielem)%nly Lines 212-215
 213 if (hru(ielem)%lumv%sdr_dep < soil(ielem)%phys(jj)%d) hru(ielem)%lumv%ldrain = jj
 214 if (hru(ielem)%lumv%sdr_dep < soil(ielem)%phys(jj)%d) exit
END DOLine 215
END IFLine 215
ELSE Lines 216-218
 217 hru(ielem)%lumv%ldrain = 0
END IF Line 218
CASE ("tile_dtime") Lines 220-229
setting tile lage time (line 223)
setting tile lage time (line 223)
 221 hru(ielem)%sdr%time = chg_par(hru(ielem)%sdr%time,             &
 222 chg_typ, chg_val, absmin, absmax)
IF (hru(ielem)%lumv%ldrain > 0 .and. hru(ielem)%sdr%lag > 0.01) THEN Lines 224-225
 225 hru(ielem)%lumv%tile_ttime = 1. - Exp(-24. / hru(ielem)%sdr%lag)
END IFLine 225
ELSE Lines 226-228
 227 hru(ielem)%lumv%tile_ttime = 0.
END IF Line 228
CASE ("tile_lag") Lines 230-233
 231 hru(ielem)%sdr%lag = chg_par(hru(ielem)%sdr%lag,               &
 232 chg_typ, chg_val, absmin, absmax)
CASE ("tile_rad") Lines 234-237
 235 hru(ielem)%sdr%radius = chg_par(hru(ielem)%sdr%radius,         &
 236 chg_typ, chg_val, absmin, absmax)
CASE ("tile_dist") Lines 238-241
 239 hru(ielem)%sdr%dist = chg_par(hru(ielem)%sdr%dist,             &
 240 chg_typ, chg_val, absmin, absmax)
CASE ("tile_drain") Lines 242-245
 243 hru(ielem)%sdr%drain_co = chg_par(hru(ielem)%sdr%drain_co,     &
 244 chg_typ, chg_val, absmin, absmax)
CASE ("tile_pump") Lines 246-249
 247 hru(ielem)%sdr%pumpcap = chg_par(hru(ielem)%sdr%pumpcap,       &
 248 chg_typ, chg_val, absmin, absmax)
CASE ("tile_latk") Lines 250-254
 251 hru(ielem)%sdr%lag = chg_par(hru(ielem)%sdr%latksat,           &
 252 chg_typ, chg_val, absmin, absmax)
CASE ("anion_excl") Lines 255-258
 256 soil(ielem)%anion_excl = chg_par(soil(ielem)%anion_excl,         &
 257 chg_typ, chg_val, absmin, absmax)
CASE ("crk") Lines 259-262
 260 soil(ielem)%crk = chg_par(soil(ielem)%crk,                      &
 261 chg_typ, chg_val, absmin, absmax)
CASE ("z") Lines 263-268
 264 soil(ielem)%phys(ly)%d = chg_par(soil(ielem)%phys(ly)%d,     &
 265 chg_typ, chg_val, absmin, absmax)
 266 call soil_awc_init (ielem)
 267 call curno (cn2(ielem), ielem)
CASE ("bd") Lines 269-274
 270 soil(ielem)%phys(ly)%bd = chg_par(soil(ielem)%phys(ly)%bd,    &
 271 chg_typ, chg_val, absmin, absmax)
 272 call soil_awc_init (ielem)
 273 call curno (cn2(ielem), ielem)
CASE ("awc") Lines 275-280
 276 soil(ielem)%phys(ly)%awc = chg_par(soil(ielem)%phys(ly)%awc,  &
 277 chg_typ, chg_val, absmin, absmax)
 278 call soil_awc_init (ielem)
 279 call curno (cn2(ielem), ielem)
CASE ("k") Lines 281-286
 282 soil(ielem)%phys(ly)%k = chg_par(soil(ielem)%phys(ly)%k,      &
 283 chg_typ, chg_val, absmin, absmax)
 284 soil(ielem)%phys(ly)%hk = (soil(ielem)%phys(ly)%ul - soil(ielem)%phys(ly)%fc) / soil(ielem)%phys(ly)%k
 285 if (soil(ielem)%phys(ly)%hk < 1.) soil(ielem)%phys(ly)%hk = 1.
CASE ("cbn") Lines 287-290
 288 soil1(ielem)%tot(ly)%c = chg_par(soil1(ielem)%tot(ly)%c,    &
 289 chg_typ, chg_val, absmin, absmax)
CASE ("clay") Lines 291-297
 292 soil(ielem)%phys(ly)%clay = chg_par(soil(ielem)%phys(ly)%clay, &
 293 chg_typ, chg_val, absmin, absmax)
 294 call soil_awc_init (ielem)
 295 call soil_text_init (ielem)
 296 call curno (cn2(ielem), ielem)
CASE ("silt") Lines 298-302
 299 soil(ielem)%phys(ly)%silt = chg_par(soil(ielem)%phys(ly)%silt, &
 300 chg_typ, chg_val, absmin, absmax)
 301 call soil_text_init (ielem)
CASE ("sand") Lines 303-307
 304 soil(ielem)%phys(ly)%sand = chg_par(soil(ielem)%phys(ly)%sand, &
 305 chg_typ, chg_val, absmin, absmax)
 306 call soil_text_init (ielem)
CASE ("rock") Lines 308-316
 309 soil(ielem)%phys(ly)%rock = chg_par(soil(ielem)%phys(ly)%rock, &
 310 chg_typ, chg_val, absmin, absmax)
IF (ly == 1) THEN Lines 311-315
 312 rock = Exp(-.053 * soil(ielem)%phys(1)%rock)
 313 hru(ielem)%lumv%usle_mult = rock * soil(ielem)%ly(1)%usle_k *       &
 314 hru(ielem)%lumv%usle_p * hru(ielem)%lumv%usle_ls * 11.8
END IFLine 315
CASE ("alb") Lines 317-320
 318 soil(ielem)%ly(ly)%alb = chg_par(soil(ielem)%ly(ly)%alb,       &
 319 chg_typ, chg_val, absmin, absmax)
CASE ("usle_k") Lines 321-327
 322 soil(ielem)%ly(ly)%usle_k = chg_par(soil(ielem)%ly(ly)%usle_k, &
 323 chg_typ, chg_val, absmin, absmax)
 324 rock = Exp(-.053 * soil(ielem)%phys(1)%rock)
 325 hru(ielem)%lumv%usle_mult = rock * soil(ielem)%ly(1)%usle_k *       &
 326 hru(ielem)%lumv%usle_p * hru(ielem)%lumv%usle_ls * 11.8
CASE ("ec") Lines 328-331
 329 soil(ielem)%ly(ly)%ec = chg_par(soil(ielem)%ly(ly)%ec,         &
 330 chg_typ, chg_val, absmin, absmax)
CASE ("cal") Lines 332-335
 333 soil(ielem)%ly(ly)%cal = chg_par(soil(ielem)%ly(ly)%cal,       &
 334 chg_typ, chg_val, absmin, absmax)
CASE ("ph") Lines 336-338
 337 soil(ielem)%ly(ly)%ph = chg_par(soil(ielem)%ly(ly)%ph,        &
 338 chg_typ, chg_val, absmin, absmax)
CASE ("cmn_h") Lines 339-342
 340 hru(ielem)%nut%cmn = chg_par(hru(ielem)%nut%cmn,           &
 341 chg_typ, chg_val, absmin, absmax)
CASE ("nperco_h") Lines 343-346
 344 hru(ielem)%nut%nperco = chg_par(hru(ielem)%nut%nperco,                  &
 345 chg_typ, chg_val, absmin, absmax)
CASE ("pperco_h") Lines 347-349
 348 hru(ielem)%nut%pperco = chg_par(hru(ielem)%nut%pperco,                  &
 349 chg_typ, chg_val, absmin, absmax)
CASE ("phoskd_h") Lines 350-352
 351 hru(ielem)%nut%phoskd = chg_par(hru(ielem)%nut%phoskd,                  &
 352 chg_typ, chg_val, absmin, absmax)
CASE ("psp_h") Lines 353-355
 354 hru(ielem)%nut%psp = chg_par(hru(ielem)%nut%psp,                        &
 355 chg_typ, chg_val, absmin, absmax)
CASE ("nperco_lchtile_h") Lines 356-359
 357 hru(ielem)%nut%nperco_lchtile = chg_par(hru(ielem)%nut%nperco_lchtile,  &
 358 chg_typ, chg_val, absmin, absmax)
CASE ("plaps") Lines 360-363
 361 bsn_prm%plaps = chg_par(bsn_prm%plaps,                         &
 362 chg_typ, chg_val, absmin, absmax)
CASE ("tlaps") Lines 364-367
 365 bsn_prm%tlaps = chg_par(bsn_prm%tlaps,                         &
 366 chg_typ, chg_val, absmin, absmax)
CASE ("surlag") Lines 368-374
 369 bsn_prm%surlag = chg_par(bsn_prm%surlag,                         &
 370 chg_typ, chg_val, absmin, absmax)
DO ihru = 1, sp_ob%hru Lines 371-373
 372 brt(ihru) = 1. - Exp(-bsn_prm%surlag / tconc(ihru))
END DOLine 373
CASE ("adj_pkr") Lines 375-378
 376 bsn_prm%adj_pkr = chg_par(bsn_prm%adj_pkr,                      &
 377 chg_typ, chg_val, absmin, absmax)
CASE ("prf") Lines 379-382
 380 bsn_prm%prf = chg_par(bsn_prm%prf,                              &
 381 chg_typ, chg_val, absmin, absmax)
CASE ("evrch") Lines 383-386
 384 bsn_prm%evrch = chg_par(bsn_prm%evrch,                          &
 385 chg_typ, chg_val, absmin, absmax)
CASE ("evlai") Lines 387-390
 388 bsn_prm%evlai = chg_par(bsn_prm%evlai,                          &
 389 chg_typ, chg_val, absmin, absmax)
CASE ("ffcb") Lines 391-394
 392 bsn_prm%ffcb = chg_par(bsn_prm%ffcb,                            &
 393 chg_typ, chg_val, absmin, absmax)
CASE ("cmn") Lines 395-398
 396 bsn_prm%cmn = chg_par(bsn_prm%cmn,                              &
 397 chg_typ, chg_val, absmin, absmax)
CASE ("nperco") Lines 399-402
 400 bsn_prm%nperco = chg_par(bsn_prm%nperco,                        &
 401 chg_typ, chg_val, absmin, absmax)
CASE ("pperco") Lines 403-406
 404 bsn_prm%pperco = chg_par(bsn_prm%pperco,                        &
 405 chg_typ, chg_val, absmin, absmax)
CASE ("phoskd") Lines 407-410
 408 bsn_prm%phoskd = chg_par(bsn_prm%phoskd,                        &
 409 chg_typ, chg_val, absmin, absmax)
CASE ("psp") Lines 411-414
 412 bsn_prm%psp = chg_par(bsn_prm%psp,                              &
 413 chg_typ, chg_val, absmin, absmax)
CASE ("rsdco") Lines 415-418
 416 bsn_prm%rsdco = chg_par(bsn_prm%rsdco,                          &
 417 chg_typ, chg_val, absmin, absmax)
CASE ("percop") Lines 419-422
 420 bsn_prm%percop = chg_par(bsn_prm%percop,                        &
 421 chg_typ, chg_val, absmin, absmax)
CASE ("msk_co1") Lines 423-426
 424 bsn_prm%msk_co1= chg_par(bsn_prm%msk_co1,                       &
 425 chg_typ, chg_val, absmin, absmax)
CASE ("msk_co2") Lines 427-430
 428 bsn_prm%msk_co2 = chg_par(bsn_prm%msk_co2,                      &
 429 chg_typ, chg_val, absmin, absmax)
CASE ("msk_x") Lines 431-434
 432 bsn_prm%msk_x = chg_par(bsn_prm%msk_x,                          &
 433 chg_typ, chg_val, absmin, absmax)
CASE ("nperco_lchtile") Lines 435-438
 436 bsn_prm%msk_x = chg_par(bsn_prm%nperco_lchtile,                          &
 437 chg_typ, chg_val, absmin, absmax)
CASE ("cdn") Lines 439-442
 440 bsn_prm%cdn = chg_par(bsn_prm%cdn,                              &
 441 chg_typ, chg_val, absmin, absmax)
CASE ("tb_adj") Lines 443-446
 444 bsn_prm%tb_adj = chg_par(bsn_prm%tb_adj,                        &
 445 chg_typ, chg_val, absmin, absmax)
CASE ("sdnco") Lines 447-450
 448 bsn_prm%sdnco = chg_par(bsn_prm%sdnco,                          &
 449 chg_typ, chg_val, absmin, absmax)
CASE ("n_updis") Lines 451-454
 452 bsn_prm%n_updis = chg_par(bsn_prm%n_updis,                      &
 453 chg_typ, chg_val, absmin, absmax)
CASE ("rsd_covco") Lines 455-458
 456 bsn_prm%rsd_covco = chg_par(bsn_prm%rsd_covco,                      &
 457 chg_typ, chg_val, absmin, absmax)
CASE ("dorm_hr") Lines 459-463
 460 bsn_prm%dorm_hr = chg_par(bsn_prm%dorm_hr,                      &
 461 chg_typ, chg_val, absmin, absmax)
CASE ("mumax") Lines 464-466
 465 ch_nut(ielem)%mumax = chg_par(ch_nut(ielem)%mumax,                &
 466 chg_typ, chg_val, absmin, absmax)
CASE ("rs1") Lines 467-470
 468 ch_nut(ielem)%rs1 = chg_par(ch_nut(ielem)%rs1,                &
 469 chg_typ, chg_val, absmin, absmax)
CASE ("rs2") Lines 471-474
 472 ch_nut(ielem)%rs2 = chg_par(ch_nut(ielem)%rs2,                &
 473 chg_typ, chg_val, absmin, absmax)
CASE ("rs3") Lines 475-478
 476 ch_nut(ielem)%rs3 = chg_par(ch_nut(ielem)%rs3,                &
 477 chg_typ, chg_val, absmin, absmax)
CASE ("rs4") Lines 479-482
 480 ch_nut(ielem)%rs4 = chg_par(ch_nut(ielem)%rs4,                &
 481 chg_typ, chg_val, absmin, absmax)
CASE ("rs5") Lines 483-486
 484 ch_nut(ielem)%rs5 = chg_par(ch_nut(ielem)%rs5,                &
 485 chg_typ, chg_val, absmin, absmax)
CASE ("rs6") Lines 487-490
 488 ch_nut(ielem)%rs6 = chg_par(ch_nut(ielem)%rs6,                &
 489 chg_typ, chg_val, absmin, absmax)
CASE ("rs7") Lines 491-494
 492 ch_nut(ielem)%rs7 = chg_par(ch_nut(ielem)%rs7,                &
 493 chg_typ, chg_val, absmin, absmax)
CASE ("rk1") Lines 495-498
 496 ch_nut(ielem)%rk1 = chg_par(ch_nut(ielem)%rk1,                &
 497 chg_typ, chg_val, absmin, absmax)
CASE ("rk2") Lines 499-502
 500 ch_nut(ielem)%rk2 = chg_par(ch_nut(ielem)%rk2,                &
 501 chg_typ, chg_val, absmin, absmax)
CASE ("rk3") Lines 503-506
 504 ch_nut(ielem)%rk3 = chg_par(ch_nut(ielem)%rk3,                &
 505 chg_typ, chg_val, absmin, absmax)
CASE ("rk4") Lines 507-510
 508 ch_nut(ielem)%rk4 = chg_par(ch_nut(ielem)%rk4,                &
 509 chg_typ, chg_val, absmin, absmax)
CASE ("rk5") Lines 511-514
 512 ch_nut(ielem)%rs2 = chg_par(ch_nut(ielem)%rs2,                &
 513 chg_typ, chg_val, absmin, absmax)
CASE ("rk6") Lines 515-518
 516 ch_nut(ielem)%rk6 = chg_par(ch_nut(ielem)%rk6,                &
 517 chg_typ, chg_val, absmin, absmax)
CASE ("bc1") Lines 519-522
 520 ch_nut(ielem)%bc1 = chg_par(ch_nut(ielem)%bc1,                &
 521 chg_typ, chg_val, absmin, absmax)
CASE ("bc2") Lines 523-526
 524 ch_nut(ielem)%bc2 = chg_par(ch_nut(ielem)%bc2,                &
 525 chg_typ, chg_val, absmin, absmax)
CASE ("bc3") Lines 527-530
 528 ch_nut(ielem)%bc3 = chg_par(ch_nut(ielem)%bc3,                &
 529 chg_typ, chg_val, absmin, absmax)
CASE ("bc4") Lines 531-535
 532 ch_nut(ielem)%bc4 = chg_par(ch_nut(ielem)%bc4,                &
 533 chg_typ, chg_val, absmin, absmax)
CASE ("pst_koc") Lines 536-539
 537 pestdb(ielem)%koc = chg_par(pestdb(ielem)%koc,                &
 538 chg_typ, chg_val, absmin, absmax)
CASE ("pst_washoff") Lines 540-543
 541 pestdb(ielem)%washoff = chg_par(pestdb(ielem)%washoff,        &
 542 chg_typ, chg_val, absmin, absmax)
CASE ("pst_foliar_hlife") Lines 544-547
 545 pestdb(ielem)%foliar_hlife = chg_par(pestdb(ielem)%foliar_hlife, &
 546 chg_typ, chg_val, absmin, absmax)
CASE ("pst_soil_hlife") Lines 548-551
 549 pestdb(ielem)%soil_hlife = chg_par(pestdb(ielem)%soil_hlife,    &
 550 chg_typ, chg_val, absmin, absmax)
CASE ("pst_solub") Lines 552-555
 553 pestdb(ielem)%solub = chg_par(pestdb(ielem)%solub,    &
 554 chg_typ, chg_val, absmin, absmax)
CASE ("pst_aq_hlife") Lines 556-559
 557 pestdb(ielem)%aq_hlife = chg_par(pestdb(ielem)%aq_hlife,        &
 558 chg_typ, chg_val, absmin, absmax)
CASE ("pst_aq_volat") Lines 560-563
 561 pestdb(ielem)%aq_volat = chg_par(pestdb(ielem)%aq_volat,        &
 562 chg_typ, chg_val, absmin, absmax)
CASE ("pst_aq_settle") Lines 564-567
 565 pestdb(ielem)%aq_settle = chg_par(pestdb(ielem)%aq_settle,        &
 566 chg_typ, chg_val, absmin, absmax)
CASE ("pst_aq_resus") Lines 568-571
 569 pestdb(ielem)%aq_resus = chg_par(pestdb(ielem)%aq_resus,        &
 570 chg_typ, chg_val, absmin, absmax)
CASE ("pst_ben_hlife") Lines 572-575
 573 pestdb(ielem)%ben_hlife = chg_par(pestdb(ielem)%ben_hlife,  &
 574 chg_typ, chg_val, absmin, absmax)
CASE ("pst_ben_bury") Lines 576-579
 577 pestdb(ielem)%ben_bury = chg_par(pestdb(ielem)%ben_bury,  &
 578 chg_typ, chg_val, absmin, absmax)
CASE ("pst_ben_act_dep") Lines 580-584
 581 pestdb(ielem)%ben_act_dep = chg_par(pestdb(ielem)%ben_act_dep,  &
 582 chg_typ, chg_val, absmin, absmax)
CASE ("chw") Lines 585-588
 586 sd_ch(ielem)%chw = chg_par(sd_ch(ielem)%chw,                  &
 587 chg_typ, chg_val, absmin, absmax)
CASE ("chd") Lines 589-592
 590 sd_ch(ielem)%chd = chg_par(sd_ch(ielem)%chd,                  &
 591 chg_typ, chg_val, absmin, absmax)
CASE ("chs") Lines 593-596
 594 sd_ch(ielem)%chs = chg_par(sd_ch(ielem)%chs,                  &
 595 chg_typ, chg_val, absmin, absmax)
CASE ("chl") Lines 597-600
 598 sd_ch(ielem)%chl = chg_par(sd_ch(ielem)%chl,                  &
 599 chg_typ, chg_val, absmin, absmax)
CASE ("chn") Lines 601-604
 602 sd_ch(ielem)%chn = chg_par(sd_ch(ielem)%chn,                  &
 603 chg_typ, chg_val, absmin, absmax)
CASE ("chk") Lines 605-608
 606 sd_ch(ielem)%chk = chg_par(sd_ch(ielem)%chk,                  &
 607 chg_typ, chg_val, absmin, absmax)
CASE ("bank_exp") Lines 609-612
 610 sd_ch(ielem)%bank_exp = chg_par(sd_ch(ielem)%bank_exp,            &
 611 chg_typ, chg_val, absmin, absmax)
CASE ("cov") Lines 613-616
 614 sd_ch(ielem)%cov = chg_par(sd_ch(ielem)%cov,                  &
 615 chg_typ, chg_val, absmin, absmax)
CASE ("vcr_coef") Lines 617-620
 618 sd_ch(ielem)%vcr_coef = chg_par(sd_ch(ielem)%vcr_coef,              &
 619 chg_typ, chg_val, absmin, absmax)
CASE ("d50") Lines 621-624
 622 sd_ch(ielem)%d50 = chg_par(sd_ch(ielem)%d50,  &
 623 chg_typ, chg_val, absmin, absmax)
CASE ("ch_clay") Lines 625-628
 626 sd_ch(ielem)%ch_clay = chg_par(sd_ch(ielem)%ch_clay,            &
 627 chg_typ, chg_val, absmin, absmax)
CASE ("carbon") Lines 629-632
 630 sd_ch(ielem)%carbon = chg_par(sd_ch(ielem)%carbon,            &
 631 chg_typ, chg_val, absmin, absmax)
CASE ("ch_bd") Lines 633-635
 634 sd_ch(ielem)%ch_bd = chg_par(sd_ch(ielem)%ch_bd, chg_typ, chg_val, absmin, absmax)
CASE ("chss") Lines 636-638
 637 sd_ch(ielem)%chss = chg_par(sd_ch(ielem)%chss, chg_typ, chg_val, absmin, absmax)
CASE ("bankfull_flo") Lines 639-642
 640 sd_ch(ielem)%bankfull_flo = chg_par(sd_ch(ielem)%bankfull_flo,      &
 641 chg_typ, chg_val, absmin, absmax)
CASE ("fps") Lines 643-645
 644 sd_ch(ielem)%fps = chg_par(sd_ch(ielem)%fps, chg_typ, chg_val, absmin, absmax)
CASE ("fpn") Lines 646-648
 647 sd_ch(ielem)%fpn = chg_par(sd_ch(ielem)%fpn, chg_typ, chg_val, absmin, absmax)
CASE ("hc_kh") Lines 649-652
 650 sd_ch(ielem)%hc_kh = chg_par(sd_ch(ielem)%hc_kh,            &
 651 chg_typ, chg_val, absmin, absmax)
CASE ("hc_hgt") Lines 653-656
 654 sd_ch(ielem)%hc_hgt = chg_par(sd_ch(ielem)%hc_hgt,            &
 655 chg_typ, chg_val, absmin, absmax)
CASE ("hc_ini") Lines 657-660
 658 sd_ch(ielem)%hc_ini = chg_par(sd_ch(ielem)%hc_ini,            &
 659 chg_typ, chg_val, absmin, absmax)
CASE ("ch_n_conc") Lines 661-663
 662 sd_ch(ielem)%n_conc = chg_par (sd_ch(ielem)%n_conc, chg_typ, chg_val, absmin, absmax)
CASE ("ch_p_conc") Lines 664-666
 665 sd_ch(ielem)%p_conc = chg_par (sd_ch(ielem)%p_conc, chg_typ, chg_val, absmin, absmax)
CASE ("ch_p_bio") Lines 667-669
 668 sd_ch(ielem)%p_bio = chg_par (sd_ch(ielem)%p_bio, chg_typ, chg_val, absmin, absmax)
CASE ("pk_rto") Lines 670-673
 671 sd_ch(ielem)%pk_rto = chg_par(sd_ch(ielem)%pk_rto,            &
 672 chg_typ, chg_val, absmin, absmax)
CASE ("fp_inun_days") Lines 674-677
 675 sd_ch(ielem)%fp_inun_days = chg_par(sd_ch(ielem)%fp_inun_days,            &
 676 chg_typ, chg_val, absmin, absmax)
CASE ("n_setl") Lines 678-681
 679 sd_ch(ielem)%n_setl = chg_par(sd_ch(ielem)%n_setl,            &
 680 chg_typ, chg_val, absmin, absmax)
CASE ("p_setl") Lines 682-685
 683 sd_ch(ielem)%p_setl = chg_par(sd_ch(ielem)%p_setl,            &
 684 chg_typ, chg_val, absmin, absmax)
CASE ("n_sol_part") Lines 686-689
 687 sd_ch(ielem)%n_sol_part = chg_par(sd_ch(ielem)%n_sol_part,            &
 688 chg_typ, chg_val, absmin, absmax)
CASE ("p_sol_part") Lines 690-693
 691 sd_ch(ielem)%p_sol_part = chg_par(sd_ch(ielem)%p_sol_part,            &
 692 chg_typ, chg_val, absmin, absmax)
CASE ("n_dep_enr") Lines 694-697
 695 sd_ch(ielem)%n_dep_enr = chg_par(sd_ch(ielem)%n_dep_enr,            &
 696 chg_typ, chg_val, absmin, absmax)
CASE ("p_dep_enr") Lines 698-701
 699 sd_ch(ielem)%p_dep_enr = chg_par(sd_ch(ielem)%p_dep_enr,            &
 700 chg_typ, chg_val, absmin, absmax)
CASE ("arc_len_fr") Lines 702-705
 703 sd_ch(ielem)%arc_len_fr = chg_par(sd_ch(ielem)%arc_len_fr,            &
 704 chg_typ, chg_val, absmin, absmax)
CASE ("bed_exp") Lines 706-709
 707 sd_ch(ielem)%bed_exp = chg_par(sd_ch(ielem)%bed_exp,            &
 708 chg_typ, chg_val, absmin, absmax)
CASE ("wash_bed_fr") Lines 710-714
 711 sd_ch(ielem)%wash_bed_fr = chg_par(sd_ch(ielem)%wash_bed_fr,            &
 712 chg_typ, chg_val, absmin, absmax)
CASE ("esa") Lines 715-718
 716 res_ob(ielem)%esa = chg_par(res_ob(ielem)%esa,             &
 717 chg_typ, chg_val, absmin, absmax)
CASE ("evol") Lines 719-722
 720 res_ob(ielem)%evol = chg_par(res_ob(ielem)%evol,           &
 721 chg_typ, chg_val, absmin, absmax)
CASE ("psa") Lines 723-726
 724 res_ob(ielem)%psa = chg_par(res_ob(ielem)%psa,             &
 725 chg_typ, chg_val, absmin, absmax)
CASE ("pvol") Lines 727-730
 728 res_ob(ielem)%pvol = chg_par(res_ob(ielem)%pvol,           &
 729 chg_typ, chg_val, absmin, absmax)
CASE ("nsed") Lines 731-733
 732 res_prm(ielem)%sed%nsed = chg_par(res_prm(ielem)%sed%nsed,           &
 733 chg_typ, chg_val, absmin, absmax)
CASE ("res_d50") Lines 734-739
d50 -micro meters (line 737)
 735 res_prm(ielem)%sed%d50 = chg_par(res_prm(ielem)%sed%d50,           &
 736 chg_typ, chg_val, absmin, absmax)
 738 res_prm(ielem)%sed_stlr_co = exp(-0.184 * res_prm(ielem)%sed%d50)
CASE ("soln_stl_fr") Lines 740-742
 741 res_prm(ielem)%soln_stl_fr = chg_par(res_prm(ielem)%soln_stl_fr,           &
 742 chg_typ, chg_val, absmin, absmax)
CASE ("solp_stl_fr") Lines 743-745
 744 res_prm(ielem)%solp_stl_fr = chg_par(res_prm(ielem)%solp_stl_fr,           &
 745 chg_typ, chg_val, absmin, absmax)
CASE ("sed_stlr") Lines 746-749
 747 res_prm(ielem)%sed%sed_stlr = chg_par(res_prm(ielem)%sed%sed_stlr,           &
 748 chg_typ, chg_val, absmin, absmax)
CASE ("velsetlr") Lines 750-753
 751 res_prm(ielem)%sed%velsetlr = chg_par(res_prm(ielem)%sed%velsetlr,           &
 752 chg_typ, chg_val, absmin, absmax)
CASE ("k_res") Lines 754-757
 755 res_hyd(ielem)%k = chg_par(res_hyd(ielem)%k,                 &
 756 chg_typ, chg_val, absmin, absmax)
CASE ("evrsv") Lines 758-761
 759 res_hyd(ielem)%evrsv = chg_par(res_hyd(ielem)%evrsv,        &
 760 chg_typ, chg_val, absmin, absmax)
CASE ("vol") Lines 762-765
 763 res(ielem)%flo = chg_par(res(ielem)%flo,                    &
 764 chg_typ, chg_val, absmin, absmax)
CASE ("sed") Lines 766-769
 767 res(ielem)%sed = chg_par(res(ielem)%sed,                    &
 768 chg_typ, chg_val, absmin, absmax)
CASE ("orgp") Lines 770-773
 771 res(ielem)%sedp = chg_par(res(ielem)%sedp,                  &
 772 chg_typ, chg_val, absmin, absmax)
CASE ("orgn") Lines 774-777
 775 res(ielem)%orgn = chg_par(res(ielem)%orgn,                  &
 776 chg_typ, chg_val, absmin, absmax)
CASE ("solp") Lines 778-781
 779 res(ielem)%solp = chg_par(res(ielem)%solp,                  &
 780 chg_typ, chg_val, absmin, absmax)
CASE ("no3") Lines 782-785
 783 res(ielem)%no3 = chg_par(res(ielem)%no3,                    &
 784 chg_typ, chg_val, absmin, absmax)
CASE ("nh3") Lines 786-789
 787 res(ielem)%nh3 = chg_par(res(ielem)%nh3,                    &
 788 chg_typ, chg_val, absmin, absmax)
CASE ("no2") Lines 790-793
 791 res(ielem)%no2 = chg_par(res(ielem)%no2,                    &
 792 chg_typ, chg_val, absmin, absmax)
CASE ("psetlr1") Lines 794-797
 795 res_prm(ielem)%nut%psetlr1 = chg_par(res_prm(ielem)%nut%psetlr1,    &
 796 chg_typ, chg_val, absmin, absmax)
CASE ("psetlr2") Lines 798-801
 799 res_prm(ielem)%nut%psetlr2 = chg_par(res_prm(ielem)%nut%psetlr2,    &
 800 chg_typ, chg_val, absmin, absmax)
CASE ("nsetlr1") Lines 802-805
 803 res_prm(ielem)%nut%nsetlr1 = chg_par(res_prm(ielem)%nut%nsetlr1,    &
 804 chg_typ, chg_val, absmin, absmax)
CASE ("nsetlr2") Lines 806-809
 807 res_prm(ielem)%nut%nsetlr2 = chg_par(res_prm(ielem)%nut%nsetlr2,    &
 808 chg_typ, chg_val, absmin, absmax)
CASE ("nsolr") Lines 810-813
 811 res_prm(ielem)%nut%nsolr = chg_par(res_prm(ielem)%nut%nsolr,        &
 812 chg_typ, chg_val, absmin, absmax)
CASE ("psolr") Lines 814-818
 815 res_prm(ielem)%nut%psolr = chg_par(res_prm(ielem)%nut%psolr,      &
 816 chg_typ, chg_val, absmin, absmax)
CASE ("drawdown_days") Lines 819-823
IF (ly <= dtbl_res(ielem)%acts) THEN Lines 820-823
 821 dtbl_res(ielem)%act(ly)%const = chg_par(dtbl_res(ielem)%act(ly)%const,      &
 822 chg_typ, chg_val, absmin, absmax)
END IFLine 823
CASE ("withdraw_rate") Lines 824-830
IF (ly <= dtbl_res(ielem)%acts) THEN Lines 825-828
 826 dtbl_res(ielem)%act(ly)%const2 = chg_par(dtbl_res(ielem)%act(ly)%const2,    &
 827 chg_typ, chg_val, absmin, absmax)
END IFLine 828
CASE ("flo_init_mm") Lines 831-833
 832 aqu_dat(ielem)%flo = chg_par(aqu_dat(ielem)%flo,                &
 833 chg_typ, chg_val, absmin, absmax)
CASE ("dep_bot") Lines 834-837
 835 aqu_dat(ielem)%dep_bot = chg_par(aqu_dat(ielem)%dep_bot,        &
 836 chg_typ, chg_val, absmin, absmax)
CASE ("dep_wt_init") Lines 838-841
 839 aqu_dat(ielem)%dep_wt = chg_par(aqu_dat(ielem)%dep_wt,          &
 840 chg_typ, chg_val, absmin, absmax)
CASE ("no3_init") Lines 842-845
 843 aqu_dat(ielem)%no3 = chg_par(aqu_dat(ielem)%no3,                &
 844 chg_typ, chg_val, absmin, absmax)
CASE ("minp_init") Lines 846-849
 847 aqu_dat(ielem)%minp = chg_par(aqu_dat(ielem)%minp,              &
 848 chg_typ, chg_val, absmin, absmax)
CASE ("cbn_init") Lines 850-853
 851 aqu_dat(ielem)%cbn = chg_par(aqu_dat(ielem)%cbn,                &
 852 chg_typ, chg_val, absmin, absmax)
CASE ("flo_dist") Lines 854-857
 855 aqu_dat(ielem)%flo_dist = chg_par(aqu_dat(ielem)%flo_dist,      &
 856 chg_typ, chg_val, absmin, absmax)
CASE ("bf_max") Lines 858-861
 859 aqu_dat(ielem)%bf_max = chg_par(aqu_dat(ielem)%bf_max,          &
 860 chg_typ, chg_val, absmin, absmax)
CASE ("alpha") Lines 862-866
 863 aqu_dat(ielem)%alpha = chg_par(aqu_dat(ielem)%alpha,            &
 864 chg_typ, chg_val, absmin, absmax)
 865 aqu_prm(ielem)%alpha_e = Exp(-aqu_dat(ielem)%alpha)
CASE ("revap_co") Lines 867-870
 868 aqu_dat(ielem)%revap_co = chg_par(aqu_dat(ielem)%revap_co,      &
 869 chg_typ, chg_val, absmin, absmax)
CASE ("deep_seep") Lines 871-874
 872 aqu_dat(ielem)%seep = chg_par(aqu_dat(ielem)%seep,              &
 873 chg_typ, chg_val, absmin, absmax)
CASE ("sp_yld") Lines 875-879
 876 aqu_dat(ielem)%spyld = chg_par(aqu_dat(ielem)%spyld,            &
 877 chg_typ, chg_val, absmin, absmax)
 878 aqu_d(ielem)%stor = 1000. * (aqu_dat(ielem)%dep_bot - aqu_d(ielem)%dep_wt) * aqu_dat(ielem)%spyld
CASE ("hlife_n") Lines 880-884
 881 aqu_dat(ielem)%hlife_n = chg_par(aqu_dat(ielem)%hlife_n,        &
 882 chg_typ, chg_val, absmin, absmax)
 883 aqu_prm(ielem)%nloss = Exp(-.693 / (aqu_dat(ielem)%hlife_n + .1))
CASE ("flo_min") Lines 885-888
 886 aqu_dat(ielem)%flo_min = chg_par(aqu_dat(ielem)%flo_min,        &
 887 chg_typ, chg_val, absmin, absmax)
CASE ("revap_min") Lines 889-893
 890 aqu_dat(ielem)%revap_min = chg_par(aqu_dat(ielem)%revap_min,    &
 891 chg_typ, chg_val, absmin, absmax)
CASE ("cn2_lte") Lines 894-896
 895 hlt_db(ielem)%cn2 = chg_par (hlt_db(ielem)%cn2, chg_typ, chg_val, absmin, absmax)
CASE ("awc_lte") Lines 897-901
 898 c_val = chg_val * hlt(ielem)%soildep
 899 abmax = absmax * hlt(ielem)%soildep
 900 hlt(ielem)%awc = chg_par (hlt(ielem)%awc, chg_typ, c_val, absmin, abmax)
CASE ("etco_lte") Lines 902-904
 903 hlt_db(ielem)%etco = chg_par (hlt_db(ielem)%etco, chg_typ, chg_val, absmin, absmax)
CASE ("tc_lte") Lines 905-907
 906 hlt_db(ielem)%tc = chg_par (hlt_db(ielem)%tc, chg_typ, chg_val, absmin, absmax)
CASE ("soildep_lte") Lines 908-910
 909 hlt_db(ielem)%soildep = chg_par (hlt_db(ielem)%soildep, chg_typ, chg_val, absmin, absmax)
CASE ("slope_lte") Lines 911-913
 912 hlt_db(ielem)%slope = chg_par (hlt_db(ielem)%slope, chg_typ, chg_val, absmin, absmax)
CASE ("slopelen_lte") Lines 914-916
 915 hlt_db(ielem)%slopelen = chg_par (hlt_db(ielem)%slopelen, chg_typ, chg_val, absmin, absmax)
CASE ("sy_lte") Lines 917-919
 918 hlt_db(ielem)%sy = chg_par (hlt_db(ielem)%sy, chg_typ, chg_val, absmin, absmax)
CASE ("abf_lte") Lines 920-922
 921 hlt_db(ielem)%abf = chg_par (hlt_db(ielem)%abf, chg_typ, chg_val, absmin, absmax)
CASE ("revapc_lte") Lines 923-925
 924 hlt_db(ielem)%revapc = chg_par (hlt_db(ielem)%revapc, chg_typ, chg_val, absmin, absmax)
CASE ("percc_lte") Lines 926-928
 927 hlt_db(ielem)%percc = chg_par (hlt_db(ielem)%percc, chg_typ, chg_val, absmin, absmax)
CASE ("sw_lte") Lines 929-931
 930 hlt_db(ielem)%sw = chg_par (hlt_db(ielem)%sw, chg_typ, chg_val, absmin, absmax)
CASE ("gw_lte") Lines 932-934
 933 hlt_db(ielem)%gw = chg_par (hlt_db(ielem)%gw, chg_typ, chg_val, absmin, absmax)
CASE ("gwflow_lte") Lines 935-937
 936 hlt_db(ielem)%gwflow = chg_par (hlt_db(ielem)%gwflow, chg_typ, chg_val, absmin, absmax)
CASE ("gwdeep_lte") Lines 938-940
 939 hlt_db(ielem)%gwdeep = chg_par (hlt_db(ielem)%gwdeep, chg_typ, chg_val, absmin, absmax)
CASE ("snow_lte") Lines 941-943
 942 hlt_db(ielem)%snow = chg_par (hlt_db(ielem)%snow, chg_typ, chg_val, absmin, absmax)
CASE ("uslek_lte") Lines 944-946
 945 hlt_db(ielem)%uslek = chg_par (hlt_db(ielem)%uslek, chg_typ, chg_val, absmin, absmax)
CASE ("uslec_lte") Lines 947-949
 948 hlt_db(ielem)%uslec = chg_par (hlt_db(ielem)%uslec, chg_typ, chg_val, absmin, absmax)
CASE ("uslep_lte") Lines 950-952
 951 hlt_db(ielem)%uslep = chg_par (hlt_db(ielem)%uslep, chg_typ, chg_val, absmin, absmax)
CASE ("uslels_lte") Lines 953-957
 954 hlt_db(ielem)%uslels = chg_par (hlt_db(ielem)%uslels, chg_typ, chg_val, absmin, absmax)
CASE ("aquifer_K") Lines 958-962
IF (bsn_cc%gwflow.eq.1) THEN Lines 959-961
 960 gw_state(ielem)%hydc = chg_par(gw_state(ielem)%hydc, chg_typ, chg_val, absmin, absmax)
END IFLine 961
CASE ("aquifer_Sy") Lines 963-967
IF (bsn_cc%gwflow.eq.1) THEN Lines 964-966
 965 gw_state(ielem)%spyd = chg_par(gw_state(ielem)%spyd, chg_typ, chg_val, absmin, absmax)
END IFLine 966
CASE ("aquifer_delay") Lines 968-972
IF (bsn_cc%gwflow.eq.1) THEN Lines 969-971
 970 gw_delay(ielem) = chg_par(gw_delay(ielem), chg_typ, chg_val, absmin, absmax)
END IFLine 971
CASE ("aquifer_exdp") Lines 973-977
IF (bsn_cc%gwflow.eq.1) THEN Lines 974-976
 975 gw_state(ielem)%exdp = chg_par(gw_state(ielem)%exdp, chg_typ, chg_val, absmin, absmax)
END IFLine 976
CASE ("stream_K") Lines 978-984
IF (bsn_cc%gwflow.eq.1) THEN Lines 979-983
DO icell=1,gw_chan_info(ielem)%ncon !loop through cells connected to channel Lines 980-982
 981 gw_chan_info(ielem)%hydc(icell) = chg_par(gw_chan_info(ielem)%hydc(icell), chg_typ, chg_val, absmin, absmax)
END DOLine 982
END IFLine 983
CASE ("stream_thk") Lines 985-991
IF (bsn_cc%gwflow.eq.1) THEN Lines 986-990
DO icell=1,gw_chan_info(ielem)%ncon !loop through cells connected to channel Lines 987-989
 988 gw_chan_info(ielem)%thck(icell) = chg_par(gw_chan_info(ielem)%thck(icell), chg_typ, chg_val, absmin, absmax)
END DOLine 989
END IFLine 990
CASE ("stream_bed") Lines 992-997
IF (bsn_cc%gwflow.eq.1) THEN Lines 993-995
 994 gw_bed_change = chg_par(gw_bed_change, chg_typ, chg_val, absmin, absmax)
END IFLine 995
CASE ("lab_p") Lines 998-1002
DO jj = 1, soil(ielem)%nly Lines 999-1001
1000 soil1(ielem)%mp(ly)%lab = chg_par (soil1(ielem)%mp(ly)%lab, chg_typ, chg_val, absmin, absmax)
END DOLine 1001
CASE ("hum_c_n") Lines 1003-1007
DO jj = 1, soil(ielem)%nly Lines 1004-1006
1005 soil1(ielem)%hact(ly)%n = chg_par (soil1(ielem)%hact(ly)%n, chg_typ, chg_val, absmin, absmax)
END DOLine 1006
CASE ("hum_c_p") Lines 1008-1012
DO jj = 1, soil(ielem)%nly Lines 1009-1011
1010 soil1(ielem)%hact(ly)%p = chg_par (soil1(ielem)%hact(ly)%p, chg_typ, chg_val, absmin, absmax)
END DOLine 1011
END SELECTLine 1013
1015 return
Allocations
n/a
Calls
Procedures Called
List of procedures called by this Subroutine.
curno
amin1
soil_awc_init
soil_text_init
Call Graph
Visual representation of procedures called by this Subroutine.
Variables
Type Visibility Attributes Name Initial
integer, public :: ielem
integer, public :: ly
character(len=16), public :: chg_parm
character(len=16), public :: chg_typ
real, public :: chg_val
real, public :: absmin
real, public :: absmax
integer, public :: num_db
Call graph
cal_parm_select calls amin1, curno, soil_awc_init, soil_text_init