calsoft_sed – TestDataProject
calsoft_sed Subroutine
164 statements
Source File
subroutine calsoft_sed()
Called From
n/a
Arguments
n/a
Outside Variables and Types
type(soil_profile) (1 attribute from soil_module)
Attribute Name Description
soil
type(soft_calib_parms) (1 attribute from calibration_data_module)
Attribute Name Description
ls_prms
type(soft_calib_ls_processes) (1 attribute from calibration_data_module)
Attribute Name Description
lscal_z
to zero values
type(soft_data_calib_landscape) (1 attribute from calibration_data_module)
Attribute Name Description
lscal
dimension by region for hru"s
type(cataloging_units) (1 attribute from calibration_data_module)
Attribute Name Description
region
dimension by region for hru"s
type (2 attributes from hydrograph_module)
Attribute Name Description
sp_ob%hru None
db_mx%cha_reg None
type(hydrologic_response_unit) (1 attribute from hru_module)
Attribute Name Description
hru
integer (1 attribute from hru_module)
Attribute Name Description
ihru
none |HRU number
Read more…
real (1 attribute from hru_module)
Attribute Name Description
tconc
Uses
basin_module
sd_channel_module
conditional_module
soil_module
calibration_data_module
hydrograph_module
maximum_data_module
aquifer_module
reservoir_module
hru_module
channel_module
organic_mineral_mass_module
plant_module
hru_lte_module
ru_module
I/O
n/a
Local Variables
Type Visibility Attributes Name Initial
integer, public :: isim = 0
integer, public :: ireg = 0
integer, public :: ilum = 0
integer, public :: iihru = 0
integer, public :: ihru_s = 0
integer, public :: iter = 0
integer, public :: isl = 0
real, public :: rmeas = 0.
real, public :: denom = 0.
real, public :: soft = 0.
real, public :: diff = 0.
real, public :: chg_val = 0.
real, public :: xm = 0.
real, public :: sin_sl = 0.
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure. Use mouse wheel to zoom, drag to pan.
Reset Zoom Help
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
  39 isim = 0
DO ireg = 1, db_mx%cha_reg Lines 40-84
DO ilum = 1, region(ireg)%nlum Lines 41-83
  42 soft = lscal(ireg)%lum(ilum)%meas%sed
  43 diff = 0.
  44 if (soft > 1.e-6) diff = abs((soft - lscal(ireg)%lum(ilum)%aa%sed) / soft)
IF (diff > .1 .and. lscal(ireg)%lum(ilum)%ha > 1.e-6 .and. lscal(ireg)%lum(ilum)%prm_lim%tconc < 1.e-6) THEN Lines 45-82
  46 isim = 1
  79 lscal(ireg)%lum(ilum)%nbyr = 0
  80 lscal(ireg)%lum(ilum)%precip_aa = 0.
  81 lscal(ireg)%lum(ilum)%aa = lscal_z
DO ihru_s = 1, region(ireg)%num_tot Lines 47-78
  48 iihru = region(ireg)%num(ihru_s)
IF (lscal(ireg)%lum(ilum)%meas%name == hru(ihru)%lum_group_c) THEN Lines 49-77
re-initialize all objects (line 50)
  51 call re_initialize
  54 lscal(ireg)%lum(ilum)%prm_prev = lscal(ireg)%lum(ilum)%prm
  55 lscal(ireg)%lum(ilum)%prev = lscal(ireg)%lum(ilum)%aa
  57 chg_val = lscal(ireg)%lum(ilum)%meas%sed / lscal(ireg)%lum(ilum)%aa%sed
  58 chg_val = chg_val ** 1.7857
  59 lscal(ireg)%lum(ilum)%prm_prev%tconc = lscal(ireg)%lum(ilum)%prm_prev%tconc
  60 lscal(ireg)%lum(ilum)%prm_prev%tconc = lscal(ireg)%lum(ilum)%prm_prev%tconc + chg_val
  61 lscal(ireg)%lum(ilum)%prev%sed = lscal(ireg)%lum(ilum)%aa%sed
  74 tconc(iihru) = tconc(iihru) / chg_val
  75 tconc(iihru) = amin1 (tconc(iihru), 1400.)
  76 tconc(iihru) = Max (tconc(iihru), 0.)
IF (lscal(ireg)%lum(ilum)%prm_prev%tconc >= ls_prms(1)%pos) THEN Lines 63-67
  64 chg_val = ls_prms(6)%pos - lscal(ireg)%lum(ilum)%prm_prev%tconc
  65 lscal(ireg)%lum(ilum)%prm_prev%tconc = ls_prms(6)%pos
  66 lscal(ireg)%lum(ilum)%prm_lim%tconc = 1.
END IFLine 67
IF (lscal(ireg)%lum(ilum)%prm_prev%tconc <= ls_prms(6)%neg) THEN Lines 68-72
  69 chg_val = ls_prms(6)%pos - lscal(ireg)%lum(ilum)%prm_prev%tconc
  70 lscal(ireg)%lum(ilum)%prm_prev%tconc = ls_prms(6)%neg
  71 lscal(ireg)%lum(ilum)%prm_lim%tconc = 1.
END IFLine 72
END IFLine 77
END DOLine 78
END IFLine 82
END DOLine 83
END DOLine 84
  86 if (isim > 0) call time_control
DO iter = 1, 2
DO isl = 1, 3
 122 call time_control
 123 end do      ! tc
 166 call time_control
DO ireg = 1, db_mx%cha_reg Lines 91-120
DO ilum = 1, region(ireg)%nlum Lines 92-119
 116 lscal(ireg)%lum(ilum)%nbyr = 0
 117 lscal(ireg)%lum(ilum)%precip_aa = 0.
 118 lscal(ireg)%lum(ilum)%aa = lscal_z
DO ihru_s = 1, region(ireg)%num_tot Lines 93-115
  94 iihru = region(ireg)%num(ihru_s)
IF (lscal(ireg)%lum(ilum)%meas%name == hru(ihru)%lum_group_c) THEN Lines 95-114
re-initialize all objects (line 96)
  97 call re_initialize
 100 lscal(ireg)%lum(ilum)%prm_prev = lscal(ireg)%lum(ilum)%prm
 101 lscal(ireg)%lum(ilum)%prev = lscal(ireg)%lum(ilum)%aa
 103 rmeas = lscal(ireg)%lum(ilum)%meas%sed
 104 chg_val = - (lscal(ireg)%lum(ilum)%prm_prev%tconc - lscal(ireg)%lum(ilum)%prm_prev%tconc)                  &
 105 * (lscal(ireg)%lum(ilum)%aa%sed - rmeas) / (lscal(ireg)%lum(ilum)%prev%sed - rmeas)
 106 chg_val = amin1 (chg_val, ls_prms(6)%pos)
 107 chg_val = Max (chg_val, ls_prms(6)%neg)
 108 lscal(ireg)%lum(ilum)%prm%tconc = chg_val
IF (chg_val > .001) THEN Lines 109-113
 110 tconc(iihru) = tconc(iihru) / chg_val
 111 tconc(iihru) = amin1 (tconc(iihru), 1400.)
 112 tconc(iihru) = Max (tconc(iihru), 0.)
END IFLine 113
END IFLine 114
END DOLine 115
END DOLine 119
END DOLine 120
DO ireg = 1, db_mx%cha_reg Lines 126-164
DO ilum = 1, region(ireg)%nlum Lines 127-163
 160 lscal(ireg)%lum(ilum)%nbyr = 0
 161 lscal(ireg)%lum(ilum)%precip_aa = 0.
 162 lscal(ireg)%lum(ilum)%aa = lscal_z
DO iihru = 1, sp_ob%hru Lines 129-159
IF (lscal(ireg)%lum(ilum)%meas%name == hru(ihru)%lum_group_c) THEN Lines 131-158
re-initialize all objects (line 132)
 133 call re_initialize
 136 lscal(ireg)%lum(ilum)%prm_prev = lscal(ireg)%lum(ilum)%prm
 137 lscal(ireg)%lum(ilum)%prev = lscal(ireg)%lum(ilum)%aa
 139 denom = lscal(ireg)%lum(ilum)%prev%srr - lscal(ireg)%lum(ilum)%aa%srr
 146 chg_val = amin1 (chg_val, ls_prms(5)%pos)
 147 chg_val = Max (chg_val, ls_prms(5)%neg)
 148 lscal(ireg)%lum(ilum)%prm%slope = chg_val
 150 hru(iihru)%topo%slope = hru(iihru)%topo%slope - chg_val
 151 hru(iihru)%topo%slope = amin1 (hru(iihru)%topo%slope, 2.)
 152 hru(iihru)%topo%slope = Max (hru(iihru)%topo%slope, .0000001)
 153 xm = 0.6 * (1. - Exp(-35.835 * hru(iihru)%topo%slope))
 154 sin_sl = Sin(Atan(hru(iihru)%topo%slope))
 155 hru(iihru)%lumv%usle_ls = (hru(iihru)%topo%slope / 22.128) ** xm * (65.41 * sin_sl * sin_sl + 4.56 * sin_sl +.065)
 156 hru(iihru)%lumv%usle_mult = soil(iihru)%phys(1)%rock * soil(iihru)%usle_k * hru(iihru)%lumv%usle_p * &
 157 hru(iihru)%lumv%usle_ls * 11.8
IF (abs(denom) > 1.e-6) THEN Lines 140-141
 141 chg_val = lscal(ireg)%lum(ilum)%meas%sed / lscal(ireg)%lum(ilum)%aa%sed
END IFLine 141
ELSE Lines 142-144
 143 chg_val = diff / 200.
END IF Line 144
END IFLine 158
END DOLine 159
END DOLine 163
END DOLine 164
DO isl = 1, 2
 206 call time_control
 209 end do      ! isl
 210 end do      ! iter
 212 return
DO ireg = 1, db_mx%cha_reg Lines 170-204
DO ilum = 1, region(ireg)%nlum Lines 171-203
 200 lscal(ireg)%lum(ilum)%nbyr = 0
 201 lscal(ireg)%lum(ilum)%precip_aa = 0.
 202 lscal(ireg)%lum(ilum)%aa = lscal_z
DO iihru = 1, sp_ob%hru Lines 173-199
IF (lscal(ireg)%lum(ilum)%meas%name == hru(ihru)%lum_group_c) THEN Lines 175-198
re-initialize all objects (line 176)
 177 call re_initialize
 180 lscal(ireg)%lum(ilum)%prm_prev = lscal(ireg)%lum(ilum)%prm
 181 lscal(ireg)%lum(ilum)%prev = lscal(ireg)%lum(ilum)%aa
 183 rmeas = lscal(ireg)%lum(ilum)%meas%sed
 184 chg_val = - (lscal(ireg)%lum(ilum)%prm_prev%slope - lscal(ireg)%lum(ilum)%prm_prev%slope)                  &
 185 * (lscal(ireg)%lum(ilum)%aa%sed - rmeas) / (lscal(ireg)%lum(ilum)%prev%sed - rmeas)
 186 chg_val = amin1 (chg_val, ls_prms(5)%pos)
 187 chg_val = Max (chg_val, ls_prms(5)%neg)
 188 lscal(ireg)%lum(ilum)%prm%slope = chg_val
 190 hru(iihru)%topo%slope = hru(iihru)%topo%slope - chg_val
 191 hru(iihru)%topo%slope = amin1 (hru(iihru)%topo%slope, 2.)
 192 hru(iihru)%topo%slope = Max (hru(iihru)%topo%slope, .0000001)
 193 xm = 0.6 * (1. - Exp(-35.835 * hru(iihru)%topo%slope))
 194 sin_sl = Sin(Atan(hru(iihru)%topo%slope))
 195 hru(iihru)%lumv%usle_ls = (hru(iihru)%topo%slope / 22.128) ** xm * (65.41 * sin_sl * sin_sl + 4.56 * sin_sl +.065)
 196 hru(iihru)%lumv%usle_mult = soil(iihru)%phys(1)%rock * soil(iihru)%usle_k * hru(iihru)%lumv%usle_p * &
 197 hru(iihru)%lumv%usle_ls * 11.8
END IFLine 198
END DOLine 199
END DOLine 203
END DOLine 204
END DO
END DO
END DO
Allocations
n/a
Calls
Procedures Called
List of procedures called by this Subroutine.
re_initialize
amin1
time_control
Call Graph
Visual representation of procedures called by this Subroutine.
Call graph
calsoft_sed calls amin1, re_initialize, time_control