calsoft_hyd_bfr_surq – TestDataProject
calsoft_hyd_bfr_surq Subroutine
136 statements
Source File
subroutine calsoft_hyd_bfr_surq()
Called From
n/a
Arguments
n/a
Outside Variables and Types
type(soft_calib_parms) (1 attribute from calibration_data_module)
Attribute Name Description
ls_prms
type(soft_calib_ls_processes) (1 attribute from calibration_data_module)
Attribute Name Description
lscal_z
to zero values
type(soft_data_calib_landscape) (1 attribute from calibration_data_module)
Attribute Name Description
lscal
dimension by region for hru"s
type(cataloging_units) (1 attribute from calibration_data_module)
Attribute Name Description
region
dimension by region for hru"s
character(len=29) (1 attribute from time_module)
Attribute Name Description
cal_sim
real (2 attributes from time_module)
Attribute Name Description
cal_adj
cn2
type (1 attribute from maximum_data_module)
Attribute Name Description
db_mx%lsu_reg None
type(hydrologic_response_unit) (2 attributes from hru_module)
Attribute Name Description
hru
hru_init
Uses
basin_module
sd_channel_module
conditional_module
soil_module
calibration_data_module
hydrograph_module
time_module
maximum_data_module
aquifer_module
reservoir_module
hru_module
channel_module
organic_mineral_mass_module
plant_module
hru_lte_module
ru_module
I/O
n/a
Local Variables
Type Visibility Attributes Name Initial
integer, public :: isim = 0
integer, public :: ireg = 0
integer, public :: ilum = 0
integer, public :: iihru = 0
integer, public :: icn = 0
integer, public :: ihru_s = 0
integer, public :: iter_ind = 0
real, public :: rmeas = 0.
real, public :: denom = 0.
real, public :: soft = 0.
real, public :: diff = 0.
real, public :: chg_val = 0.
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure. Use mouse wheel to zoom, drag to pan.
Reset Zoom Help
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
  36 iter_ind = 1
  39 isim = 0
DO ireg = 1, db_mx%lsu_reg Lines 40-92
DO ilum = 1, region(ireg)%nlum Lines 41-91
  42 soft = lscal(ireg)%lum(ilum)%meas%srr * lscal(ireg)%lum(ilum)%precip_aa
  43 diff = 0.
  44 if (soft > 1.e-6) diff = abs((soft - lscal(ireg)%lum(ilum)%aa%srr) / soft)
IF (diff > .02 .and. lscal(ireg)%lum(ilum)%ha > 1.e-6 .and. lscal(ireg)%lum(ilum)%prm_lim%cn3_swf < 1.e-6) THEN Lines 45-90
  46 isim = 1
  48 lscal(ireg)%lum(ilum)%prm_prev = lscal(ireg)%lum(ilum)%prm
  49 lscal(ireg)%lum(ilum)%prev = lscal(ireg)%lum(ilum)%aa
  51 diff = lscal(ireg)%lum(ilum)%meas%srr * lscal(ireg)%lum(ilum)%precip_aa - lscal(ireg)%lum(ilum)%aa%srr
  52 chg_val = - diff / 100.     !assume 10 mm runoff for .1 cn3_swf
  54 lscal(ireg)%lum(ilum)%prm_prev%cn3_swf = lscal(ireg)%lum(ilum)%prm%cn3_swf
  55 lscal(ireg)%lum(ilum)%prm%cn3_swf = lscal(ireg)%lum(ilum)%prm%cn3_swf + chg_val
  56 lscal(ireg)%lum(ilum)%prev%srr = lscal(ireg)%lum(ilum)%aa%srr
  83 lscal(ireg)%lum(ilum)%nbyr = 0
  84 lscal(ireg)%lum(ilum)%precip_aa = 0.
  85 lscal(ireg)%lum(ilum)%aa = lscal_z
IF (lscal(ireg)%lum(ilum)%prm%cn3_swf >= ls_prms(10)%pos) THEN Lines 58-62
  59 chg_val = ls_prms(10)%pos - lscal(ireg)%lum(ilum)%prm_prev%cn3_swf
  60 lscal(ireg)%lum(ilum)%prm%cn3_swf = ls_prms(10)%pos
  61 lscal(ireg)%lum(ilum)%prm_lim%cn3_swf = 1.
END IFLine 62
IF (lscal(ireg)%lum(ilum)%prm%cn3_swf <= ls_prms(10)%neg) THEN Lines 63-67
  64 chg_val = ls_prms(10)%neg - lscal(ireg)%lum(ilum)%prm_prev%cn3_swf
  65 lscal(ireg)%lum(ilum)%prm%cn3_swf = ls_prms(10)%neg
  66 lscal(ireg)%lum(ilum)%prm_lim%cn3_swf = 1.
END IFLine 67
DO ihru_s = 1, region(ireg)%num_tot Lines 69-82
  70 iihru = region(ireg)%num(ihru_s)
IF (lscal(ireg)%lum(ilum)%meas%name == hru(iihru)%lum_group_c .or. lscal(ireg)%lum(ilum)%meas%name == "basin") THEN Lines 71-81
don't change for tile ***Mike (line 73)
don't change for tile ***Mike (line 73)
IF (hru(iihru)%tiledrain == 0) THEN Lines 74-80
  75 hru(iihru)%hyd%cn3_swf = hru(iihru)%hyd%cn3_swf + chg_val
  76 hru(iihru)%hyd%cn3_swf = amin1 (hru(iihru)%hyd%cn3_swf, ls_prms(10)%up)
  77 hru(iihru)%hyd%cn3_swf = Max (hru(iihru)%hyd%cn3_swf, ls_prms(10)%lo)
  78 hru_init(iihru)%hyd%cn3_swf = hru(iihru)%hyd%cn3_swf
  79 call curno (cn2(iihru), iihru)
END IFLine 80
END IFLine 81
END DOLine 82
END IFLine 90
END DOLine 91
END DOLine 92
re-initialize all objects (line 94)
  95 call re_initialize
IF (isim > 0) THEN Lines 98-102
  99 cal_sim =  " first cn3_swf adj "
 100 cal_adj = chg_val
 101 call time_control
END IFLine 102
DO icn = 1, 2 !iter_ind
re-initialize all objects (line 164)
 106 isim = 0
 165 call re_initialize
 175 end do      ! icn
 177 return
DO ireg = 1, db_mx%lsu_reg Lines 107-162
DO ilum = 1, region(ireg)%nlum Lines 108-161
 109 soft = lscal(ireg)%lum(ilum)%meas%srr * lscal(ireg)%lum(ilum)%precip_aa
 110 diff = 0.
 111 if (soft > 1.e-6) diff = abs((soft - lscal(ireg)%lum(ilum)%aa%srr) / soft)
IF (diff > .02 .and. lscal(ireg)%lum(ilum)%ha > 1.e-6) then ! .and. lscal(ireg)%lum(ilum)%prm_lim%cn3_swf < 1.e-6) THEN Lines 112-160
 113 isim = 1
 115 rmeas = lscal(ireg)%lum(ilum)%meas%srr * lscal(ireg)%lum(ilum)%precip_aa
 116 denom = lscal(ireg)%lum(ilum)%prev%srr - lscal(ireg)%lum(ilum)%aa%srr
 123 lscal(ireg)%lum(ilum)%prm_prev%cn3_swf = lscal(ireg)%lum(ilum)%prm%cn3_swf
 124 lscal(ireg)%lum(ilum)%prm%cn3_swf = lscal(ireg)%lum(ilum)%prm%cn3_swf + chg_val
 125 lscal(ireg)%lum(ilum)%prev%srr = lscal(ireg)%lum(ilum)%aa%srr
 153 lscal(ireg)%lum(ilum)%nbyr = 0
 154 lscal(ireg)%lum(ilum)%precip_aa = 0.
 155 lscal(ireg)%lum(ilum)%aa = lscal_z
IF (abs(denom) > 1.) THEN Lines 117-119
 118 chg_val = - (lscal(ireg)%lum(ilum)%prm_prev%cn3_swf - lscal(ireg)%lum(ilum)%prm%cn3_swf)                  &
 119 * (lscal(ireg)%lum(ilum)%aa%srr - rmeas) / denom
END IFLine 119
ELSE Lines 120-122
 121 chg_val = - diff / 10.
END IF Line 122
IF (lscal(ireg)%lum(ilum)%prm%cn3_swf >= ls_prms(10)%pos) THEN Lines 127-131
 128 chg_val = ls_prms(10)%pos - lscal(ireg)%lum(ilum)%prm_prev%cn3_swf
 129 lscal(ireg)%lum(ilum)%prm%cn3_swf = ls_prms(10)%pos
 130 lscal(ireg)%lum(ilum)%prm_lim%cn3_swf = 1.
END IFLine 131
IF (lscal(ireg)%lum(ilum)%prm%cn3_swf <= ls_prms(10)%neg) THEN Lines 132-136
 133 chg_val = ls_prms(10)%neg - lscal(ireg)%lum(ilum)%prm_prev%cn3_swf
 134 lscal(ireg)%lum(ilum)%prm%cn3_swf = ls_prms(10)%neg
 135 lscal(ireg)%lum(ilum)%prm_lim%cn3_swf = 1.
END IFLine 136
DO ihru_s = 1, region(ireg)%num_tot Lines 139-152
 140 iihru = region(ireg)%num(ihru_s)
IF (lscal(ireg)%lum(ilum)%meas%name == hru(iihru)%lum_group_c .or. lscal(ireg)%lum(ilum)%meas%name == "basin") THEN Lines 141-151
don't change for tile *********************Mike (line 143)
don't change for tile *********************Mike (line 143)
IF (hru(iihru)%tiledrain == 0) THEN Lines 144-150
 145 hru(iihru)%hyd%cn3_swf = hru(iihru)%hyd%cn3_swf + chg_val
 146 hru(iihru)%hyd%cn3_swf = amin1 (hru(iihru)%hyd%cn3_swf, ls_prms(10)%up)
 147 hru(iihru)%hyd%cn3_swf = Max (hru(iihru)%hyd%cn3_swf, ls_prms(10)%lo)
 148 hru_init(iihru)%hyd%cn3_swf = hru(iihru)%hyd%cn3_swf
 149 call curno (cn2(iihru), iihru)
END IFLine 150
END IFLine 151
END DOLine 152
END IFLine 160
END DOLine 161
END DOLine 162
IF (isim > 0) THEN Lines 168-174
 169 cal_sim =  " cn3_swf adj "
 170 cal_adj = chg_val
 173 call time_control
END IFLine 174
END DO
Allocations
n/a
Calls
Procedures Called
List of procedures called by this Subroutine.
amin1
curno
re_initialize
time_control
Call Graph
Visual representation of procedures called by this Subroutine.
Call graph
calsoft_hyd_bfr_surq calls amin1, curno, re_initialize, time_control