calsoft_hyd_bfr_pet – TestDataProject
calsoft_hyd_bfr_pet Subroutine
90 statements
Source File
subroutine calsoft_hyd_bfr_pet()
Called From
n/a
Arguments
n/a
Outside Variables and Types
type(soft_calib_parms) (1 attribute from calibration_data_module)
Attribute Name Description
ls_prms
type(soft_calib_ls_processes) (1 attribute from calibration_data_module)
Attribute Name Description
lscal_z
to zero values
type(soft_data_calib_landscape) (1 attribute from calibration_data_module)
Attribute Name Description
lscal
dimension by region for hru"s
type(cataloging_units) (1 attribute from calibration_data_module)
Attribute Name Description
region
dimension by region for hru"s
character(len=29) (1 attribute from time_module)
Attribute Name Description
cal_sim
real (1 attribute from time_module)
Attribute Name Description
cal_adj
type (1 attribute from maximum_data_module)
Attribute Name Description
db_mx%lsu_reg None
type(hydrologic_response_unit) (2 attributes from hru_module)
Attribute Name Description
hru
hru_init
Uses
basin_module
sd_channel_module
conditional_module
soil_module
calibration_data_module
hydrograph_module
time_module
maximum_data_module
aquifer_module
reservoir_module
hru_module
channel_module
organic_mineral_mass_module
plant_module
hru_lte_module
ru_module
I/O
n/a
Local Variables
Type Visibility Attributes Name Initial
integer, public :: isim = 0
integer, public :: ireg = 0
integer, public :: ilum = 0
integer, public :: iihru = 0
integer, public :: ihru_s = 0
integer, public :: iter_ind = 0
integer, public :: ietco = 0
real, public :: rmeas = 0.
real, public :: denom = 0.
real, public :: soft = 0.
real, public :: diff = 0.
real, public :: chg_val = 0.
real, public :: pred = 0.
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure. Use mouse wheel to zoom, drag to pan.
Reset Zoom Help
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
  33 iter_ind = 1
DO ietco = 1, 2 !iter_ind
re-initialize all objects (line 86)
  36 isim = 0
  87 call re_initialize
  94 end do    ! petco iterations
  95 return
DO ireg = 1, db_mx%lsu_reg Lines 37-85
DO ilum = 1, region(ireg)%nlum Lines 38-84
  39 soft = lscal(ireg)%lum(ilum)%meas%wyr * lscal(ireg)%lum(ilum)%precip_aa
  40 pred = lscal(ireg)%lum(ilum)%aa%wyr
  41 diff = 0.
  42 if (soft > 1.e-6) diff = abs((soft - pred) / soft)
IF (diff > .01 .and. lscal(ireg)%lum(ilum)%ha > 1.e-6) THEN Lines 43-83
  44 isim = 1
  45 lscal(ireg)%lum(ilum)%prm_prev = lscal(ireg)%lum(ilum)%prm
  46 lscal(ireg)%lum(ilum)%prev = lscal(ireg)%lum(ilum)%aa
  52 lscal(ireg)%lum(ilum)%prm_prev%petco = lscal(ireg)%lum(ilum)%prm%petco
  58 lscal(ireg)%lum(ilum)%prm_prev%petco = pred
  80 lscal(ireg)%lum(ilum)%nbyr = 0
  81 lscal(ireg)%lum(ilum)%precip_aa = 0.
  82 lscal(ireg)%lum(ilum)%aa = lscal_z
IF (soft < pred) THEN Lines 47-48
  48 chg_val = 1. + abs((soft - pred) / soft)
END IFLine 48
ELSE Lines 49-51
  50 chg_val = 1. - abs((pred - soft) / pred)
END IF Line 51
IF (ietco == 1) THEN Lines 53-54
  54 lscal(ireg)%lum(ilum)%prm%petco = chg_val
END IFLine 54
ELSE Lines 55-57
  56 lscal(ireg)%lum(ilum)%prm%petco = lscal(ireg)%lum(ilum)%prm%petco * chg_val
END IF Line 57
IF (lscal(ireg)%lum(ilum)%prm%petco >= ls_prms(4)%pos) THEN Lines 59-63
  60 chg_val = ls_prms(4)%pos
  61 lscal(ireg)%lum(ilum)%prm%petco = ls_prms(4)%pos
  62 lscal(ireg)%lum(ilum)%prm_lim%petco = 1.
END IFLine 63
IF (lscal(ireg)%lum(ilum)%prm%petco <= ls_prms(4)%neg) THEN Lines 64-68
  65 chg_val = ls_prms(4)%neg
  66 lscal(ireg)%lum(ilum)%prm%petco = ls_prms(4)%neg
  67 lscal(ireg)%lum(ilum)%prm_lim%petco = 1.
END IFLine 68
DO ihru_s = 1, region(ireg)%num_tot Lines 70-79
  71 iihru = region(ireg)%num(ihru_s)
IF (lscal(ireg)%lum(ilum)%meas%name == hru(iihru)%lum_group_c .or. lscal(ireg)%lum(ilum)%meas%name == "basin") THEN Lines 72-78
  74 hru(iihru)%hyd%pet_co = hru(iihru)%hyd%pet_co * chg_val
  75 hru(iihru)%hyd%pet_co = amin1 (hru(iihru)%hyd%pet_co, ls_prms(4)%up)
  76 hru(iihru)%hyd%pet_co = Max (hru(iihru)%hyd%pet_co, ls_prms(4)%lo)
  77 hru_init(iihru)%hyd%pet_co = hru(iihru)%hyd%pet_co
END IFLine 78
END DOLine 79
END IFLine 83
END DOLine 84
END DOLine 85
IF (isim > 0) THEN Lines 89-93
  90 cal_sim =  " first pet adj "
  91 cal_adj = chg_val
  92 call time_control
END IFLine 93
END DO
Allocations
n/a
Calls
Procedures Called
List of procedures called by this Subroutine.
amin1
re_initialize
time_control
Call Graph
Visual representation of procedures called by this Subroutine.
Call graph
calsoft_hyd_bfr_pet calls amin1, re_initialize, time_control