calsoft_hyd_bfr_perc – test-src-project
calsoft_hyd_bfr_perc Subroutine
154 statements
Source File
subroutine calsoft_hyd_bfr_perc()
Uses
aquifer_module
sd_channel_module
ru_module
channel_module
hru_lte_module
hru_module
conditional_module
basin_module
hydrograph_module
soil_module
maximum_data_module
plant_module
reservoir_module
time_module
calibration_data_module
organic_mineral_mass_module
Arguments
n/a
I/O
n/a
Outside Variables and Types
type(hydrologic_response_unit) (2 attributes from hru_module)
Attribute Name Description
hru
hru_init
type (1 attribute from maximum_data_module)
Attribute Name Description
db_mx%lsu_reg None
character(len=29) (1 attribute from time_module)
Attribute Name Description
cal_sim
real (1 attribute from time_module)
Attribute Name Description
cal_adj
type(soft_calib_parms) (1 attribute from calibration_data_module)
Attribute Name Description
ls_prms
type(soft_calib_ls_processes) (1 attribute from calibration_data_module)
Attribute Name Description
lscal_z
to zero values
type(soft_data_calib_landscape) (1 attribute from calibration_data_module)
Attribute Name Description
lscal
dimension by region for hru"s
type(cataloging_units) (1 attribute from calibration_data_module)
Attribute Name Description
region
dimension by region for hru"s
!! Bang Comments
don't change for tile ***Mike re-initialize all objects don't change for tile ***Mike re-initialize all objects
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure.
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
  37 iter_ind = 3
  40 isim = 0
DO ireg = 1, db_mx%lsu_reg Lines 41-99
DO ilum = 1, region(ireg)%nlum Lines 42-98
  44 soft = lscal(ireg)%lum(ilum)%meas%bfr * lscal(ireg)%lum(ilum)%precip_aa
  45 diff = 0.
  46 if (soft > 1.e-6) diff = abs((soft - lscal(ireg)%lum(ilum)%aa%bfr) / soft)
IF (diff > .05 .and. lscal(ireg)%lum(ilum)%ha > 1.e-6 .and. lscal(ireg)%lum(ilum)%prm_lim%perco < 1.e-6) THEN Lines 47-94
  48 isim = 1
  51 lscal(ireg)%lum(ilum)%prm_prev = lscal(ireg)%lum(ilum)%prm
  52 lscal(ireg)%lum(ilum)%prev = lscal(ireg)%lum(ilum)%aa
  55 chg_val = 0.001 * (soft - lscal(ireg)%lum(ilum)%aa%bfr)
  56 lscal(ireg)%lum(ilum)%prm_prev%perco = lscal(ireg)%lum(ilum)%prm%perco
  57 lscal(ireg)%lum(ilum)%prm%perco = lscal(ireg)%lum(ilum)%prm%perco + chg_val
  58 lscal(ireg)%lum(ilum)%prev%bfr = lscal(ireg)%lum(ilum)%aa%bfr
  92 lscal(ireg)%lum(ilum)%nbyr = 0
  93 lscal(ireg)%lum(ilum)%precip_aa = 0.
  94 lscal(ireg)%lum(ilum)%aa = lscal_z
IF (lscal(ireg)%lum(ilum)%prm%perco >= ls_prms(8)%pos) THEN Lines 60-64
  61 lscal(ireg)%lum(ilum)%prm%perco = ls_prms(8)%pos
  62 chg_val = ls_prms(8)%pos
  63 lscal(ireg)%lum(ilum)%prm_lim%perco = 1.
END IFLine 64
IF (lscal(ireg)%lum(ilum)%prm%perco <= ls_prms(8)%neg) THEN Lines 65-69
  66 lscal(ireg)%lum(ilum)%prm%perco = ls_prms(8)%neg
  67 chg_val = ls_prms(8)%neg
  68 lscal(ireg)%lum(ilum)%prm_lim%perco = 1.
END IFLine 69
DO ihru_s = 1, region(ireg)%num_tot Lines 71-90
  72 iihru = region(ireg)%num(ihru_s)
IF (lscal(ireg)%lum(ilum)%meas%name == hru(iihru)%lum_group_c .or. lscal(ireg)%lum(ilum)%meas%name == "basin") THEN Lines 73-89
IF (hru(iihru)%tiledrain == 0) THEN Lines 75-88
  76 hru(iihru)%hyd%perco = hru(iihru)%hyd%perco + chg_val
  77 hru(iihru)%hyd%perco = amin1 (hru(iihru)%hyd%perco, ls_prms(8)%up)
  78 hru(iihru)%hyd%perco = Max (hru(iihru)%hyd%perco, ls_prms(8)%lo)
  79 hru_init(iihru)%hyd%perco = hru(iihru)%hyd%perco
  87 hru_init(iihru)%hyd%perco_lim = hru(iihru)%hyd%perco_lim
IF (hru(iihru)%hyd%perco > 1.e-9) THEN Lines 80-83
  81 perc_ln_func = 1.0052 * log(-log(hru(iihru)%hyd%perco - 1.e-6)) + 5.6862
  82 hru(iihru)%hyd%perco_lim = exp(-perc_ln_func)
  83 hru(iihru)%hyd%perco_lim = amin1 (1., hru(iihru)%hyd%perco_lim)
END IFLine 83
ELSE Lines 84-86
  85 hru(iihru)%hyd%perco_lim = 0.
END IF Line 86
END IFLine 88
END IFLine 89
END DOLine 90
END IFLine 94
ELSE Lines 95-97
  96 lscal(ireg)%lum(ilum)%prm_lim%perco = 1.
END IF Line 97
END DOLine 98
END DOLine 99
 112 call re_initialize
IF (isim > 0) THEN Lines 115-119
 116 cal_sim =  " first perco adj "
 117 cal_adj = chg_val
 118 call time_control
END IFLine 119
DO iperco = 1, 3 !iter_ind
 123 isim = 0
 187 call re_initialize
 196 end do      ! iperco
 198 return
DO ireg = 1, db_mx%lsu_reg Lines 124-184
DO ilum = 1, region(ireg)%nlum Lines 125-183
 126 soft = lscal(ireg)%lum(ilum)%meas%bfr * lscal(ireg)%lum(ilum)%precip_aa
 127 diff = 0.
 128 if (soft > 1.e-6) diff = abs((soft - lscal(ireg)%lum(ilum)%aa%bfr) / soft)
IF (diff > .05 .and. lscal(ireg)%lum(ilum)%ha > 1.e-6) THEN Lines 129-179
 130 isim = 1
 132 rmeas = lscal(ireg)%lum(ilum)%meas%bfr * lscal(ireg)%lum(ilum)%precip_aa
 133 denom = lscal(ireg)%lum(ilum)%prev%bfr - lscal(ireg)%lum(ilum)%aa%bfr
 140 lscal(ireg)%lum(ilum)%prm_prev%perco = lscal(ireg)%lum(ilum)%prm%perco
 141 lscal(ireg)%lum(ilum)%prm%perco = lscal(ireg)%lum(ilum)%prm%perco + chg_val
 142 lscal(ireg)%lum(ilum)%prev%bfr = lscal(ireg)%lum(ilum)%aa%bfr
 177 lscal(ireg)%lum(ilum)%nbyr = 0
 178 lscal(ireg)%lum(ilum)%precip_aa = 0.
 179 lscal(ireg)%lum(ilum)%aa = lscal_z
IF (abs(denom) > 2.) THEN Lines 134-136
 135 chg_val = - (lscal(ireg)%lum(ilum)%prm_prev%perco - lscal(ireg)%lum(ilum)%prm%perco)                  &
 136 * (lscal(ireg)%lum(ilum)%aa%bfr - rmeas) / denom
END IFLine 136
ELSE Lines 137-139
 138 chg_val = 0.
END IF Line 139
IF (lscal(ireg)%lum(ilum)%prm%perco >= ls_prms(8)%pos) THEN Lines 144-148
 145 lscal(ireg)%lum(ilum)%prm%perco = ls_prms(8)%pos
 146 chg_val = ls_prms(8)%pos
 147 lscal(ireg)%lum(ilum)%prm_lim%perco = 1.
END IFLine 148
IF (lscal(ireg)%lum(ilum)%prm%perco <= ls_prms(8)%neg) THEN Lines 149-153
 150 lscal(ireg)%lum(ilum)%prm%perco = ls_prms(8)%neg
 151 chg_val = ls_prms(8)%neg
 152 lscal(ireg)%lum(ilum)%prm_lim%perco = 1.
END IFLine 153
DO ihru_s = 1, region(ireg)%num_tot Lines 155-175
 156 iihru = region(ireg)%num(ihru_s)
IF (lscal(ireg)%lum(ilum)%meas%name == hru(iihru)%lum_group_c .or. lscal(ireg)%lum(ilum)%meas%name == "basin") THEN Lines 157-174
IF (hru(iihru)%tiledrain == 0) THEN Lines 160-173
 161 hru(iihru)%hyd%perco = hru(iihru)%hyd%perco + chg_val
 162 hru(iihru)%hyd%perco = amin1 (hru(iihru)%hyd%perco, ls_prms(8)%up)
 163 hru(iihru)%hyd%perco = Max (hru(iihru)%hyd%perco, ls_prms(8)%lo)
 164 hru_init(iihru)%hyd%perco = hru(iihru)%hyd%perco
 172 hru_init(iihru)%hyd%perco_lim = hru(iihru)%hyd%perco_lim
IF (hru(iihru)%hyd%perco > 1.e-9) THEN Lines 165-168
 166 perc_ln_func = 1.0052 * log(-log(hru(iihru)%hyd%perco - 1.e-6)) + 5.6862
 167 hru(iihru)%hyd%perco_lim = exp(-perc_ln_func)
 168 hru(iihru)%hyd%perco_lim = amin1 (1., hru(iihru)%hyd%perco_lim)
END IFLine 168
ELSE Lines 169-171
 170 hru(iihru)%hyd%perco_lim = 0.
END IF Line 171
END IFLine 173
END IFLine 174
END DOLine 175
END IFLine 179
ELSE Lines 180-182
 181 lscal(ireg)%lum(ilum)%prm_lim%perco = 1.
END IF Line 182
END DOLine 183
END DOLine 184
IF (isim > 0) THEN Lines 190-194
 191 cal_sim =  " perco adj "
 192 cal_adj = chg_val
 193 call time_control
END IFLine 194
END DO
Allocations
n/a
Calls
Calls
Procedures called by this subroutine.
Local Variables
Type Visibility Attributes Name Initial
integer, private :: isim
integer, private :: ireg
integer, private :: ilum
integer, private :: iihru
integer, private :: ihru_s
integer, private :: iter_ind
integer, private :: iperco
real, private :: rmeas
real, private :: denom
real, private :: soft
real, private :: diff
real, private :: chg_val
real, private :: perc_ln_func
Call graph
calsoft_hyd_bfr_perc calls amin1, re_initialize, time_control