calsoft_plant – TestDataProject
calsoft_plant Subroutine
413 statements
Source File
subroutine calsoft_plant()
Called From
n/a
Arguments
n/a
Outside Variables and Types
type(plant_community) (2 attributes from plant_module)
Attribute Name Description
pcom
pcom_init
type(pl_parm_region) (1 attribute from calibration_data_module)
Attribute Name Description
pl_prms
dimension by region for hru"s
type(soft_data_calib_plant) (1 attribute from calibration_data_module)
Attribute Name Description
plcal
dimension by region for plants
type (1 attribute from maximum_data_module)
Attribute Name Description
db_mx%plcal_reg None
type(hydrologic_response_unit) (2 attributes from hru_module)
Attribute Name Description
hru
hru_init
integer (1 attribute from hru_module)
Attribute Name Description
ipl
Uses
basin_module
plant_module
sd_channel_module
conditional_module
soil_module
calibration_data_module
hydrograph_module
output_landscape_module
maximum_data_module
reservoir_module
hru_module
channel_module
ru_module
hru_lte_module
aquifer_module
I/O
n/a
Local Variables
Type Visibility Attributes Name Initial
integer, public :: iter_all = 0
integer, public :: iterall = 0
integer, public :: isim = 0
integer, public :: ireg = 0
integer, public :: ilum = 0
integer, public :: iihru = 0
integer, public :: ihru_s = 0
integer, public :: iter_ind = 0
integer, public :: ist = 0
integer, public :: ipl = 0
integer, public :: nvar = 0
real, public :: rmeas = 0.
real, public :: denom = 0.
real, public :: soft = 0.
real, public :: diff = 0.
real, public :: chg_val = 0.
real, public :: perc_ln_func = 0.
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure. Use mouse wheel to zoom, drag to pan.
Reset Zoom Help
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
  40 iter_all = 1
  41 iter_ind = 1
  42 nvar = 1
  45 isim = 0
DO ireg = 1, db_mx%plcal_reg
DO ilum = 1, plcal(ireg)%lum_num
  48 soft = plcal(ireg)%lum(ilum)%meas%yield
IF (soft > 1.e-6) THEN
if yields are greater than 20% low (line 51)
if yields are greater than 20% low (line 51)
  50 diff = (plcal(ireg)%lum(ilum)%aa%yield - soft) / soft
IF (diff < -.2) THEN
DO ihru_s = 1, plcal(ireg)%num_tot
  54 iihru = plcal(ireg)%num(ihru_s)
  70 end do  !ihru_s
  72 end if    !diff > .2
  73 end if    !soft > 0
  75 end do    !ilum
  76 end do    !ireg
IF (hru(iihru)%tiledrain == 0 .and. hru(iihru)%strsa > 50.) THEN Lines 55-69
  56 isim = 1
  68 hru(iihru)%strsa = 0.
DO ipl = 1, pcom(iihru)%npl Lines 57-67
IF (plcal(ireg)%lum(ilum)%meas%name == pcom(iihru)%pl(ipl)) THEN Lines 58-66
  60 hru(iihru)%hyd%perco = 0.95
  61 perc_ln_func = 1.0052 * log(-log(hru(iihru)%hyd%perco - 1.e-6)) + 5.6862
  62 hru(iihru)%hyd%perco_lim = exp(-perc_ln_func)
  63 hru(iihru)%hyd%perco_lim = amin1 (1., hru(iihru)%hyd%perco_lim)
  64 hru_init(iihru)%hyd%perco = hru(iihru)%hyd%perco
  65 hru_init(iihru)%hyd%perco_lim = hru(iihru)%hyd%perco_lim
END IFLine 66
END DOLine 67
END IFLine 69
IF (isim > 0) THEN Lines 79-83
  80 cal_sim =  " crop perco adj "
  81 call calsoft_plant_zero
  82 call time_control
END IFLine 83
DO iterall = 1, iter_all
  89 isim = 0
 224 isim = 0
 283 isim = 0
DO ireg = 1, db_mx%plcal_reg Lines 90-152
  91 nvar = plcal(ireg)%lum_num    ! epco is second variable
DO ilum = 1, plcal(ireg)%lum_num Lines 92-151
use actual value for epco and not change in value like other parms (line 93)
use actual value for epco and not change in value like other parms (line 93)
  98 soft = plcal(ireg)%lum(ilum)%meas%yield
  99 diff = 0.
 100 if (soft > 1.e-6) diff = abs((soft - plcal(ireg)%lum(ilum)%aa%yield) / soft)
IF (iterall == 1) THEN Lines 94-96
  95 plcal(ireg)%lum(ilum)%prm%epco = pl_prms(ireg)%prm(ilum)%init_val
END IFLine 96
IF (diff > .03 .and. plcal(ireg)%lum(ilum)%ha > 1.e-6) THEN Lines 101-150
assume starting at 1.0 - don't see large change until 0.25 so linear decrease from 0.25 (line 108)
assume starting at 1.0 - don't see large change until 0.25 so linear decrease from 0.25 (line 108)
set upper and lower limits for following iterations (line 115)
re-initialize all objects (line 134)
 102 isim = 1
 104 plcal(ireg)%lum(ilum)%prm_prev = plcal(ireg)%lum(ilum)%prm
 105 plcal(ireg)%lum(ilum)%prev = plcal(ireg)%lum(ilum)%aa
 107 diff = (plcal(ireg)%lum(ilum)%aa%yield - soft) / soft
 116 plcal(ireg)%lum(ilum)%prm_lowlim%epco = 0.
 117 plcal(ireg)%lum(ilum)%prm_uplim%epco = 1.
 119 plcal(ireg)%lum(ilum)%prm_prev%epco = plcal(ireg)%lum(ilum)%prm%epco
 120 plcal(ireg)%lum(ilum)%prm%epco = chg_val
 121 plcal(ireg)%lum(ilum)%prev%yield = plcal(ireg)%lum(ilum)%aa%yield
 135 call re_initialize
IF (diff > 0.1) THEN Lines 109-110
 110 chg_val = -.01 * diff + 0.06
END IFLine 110
ELSE Lines 111-114
 112 chg_val = 1.
 113 plcal(ireg)%lum(ilum)%prm_lim%epco = 1.
END IF Line 114
IF (plcal(ireg)%lum(ilum)%prm%epco >= pl_prms(ireg)%prm(ilum+nvar)%pos) THEN Lines 123-127
 124 chg_val = pl_prms(ireg)%prm(ilum+nvar)%pos
 125 plcal(ireg)%lum(ilum)%prm%epco = pl_prms(ireg)%prm(ilum+nvar)%pos
 126 plcal(ireg)%lum(ilum)%prm_lim%epco = 1.
END IFLine 127
IF (plcal(ireg)%lum(ilum)%prm%epco <= pl_prms(ireg)%prm(ilum+nvar)%neg) THEN Lines 128-132
 129 chg_val = pl_prms(ireg)%prm(ilum+nvar)%neg
 130 plcal(ireg)%lum(ilum)%prm%epco = pl_prms(ireg)%prm(ilum+nvar)%neg
 131 plcal(ireg)%lum(ilum)%prm_lim%epco = 1.
END IFLine 132
DO ihru_s = 1, plcal(ireg)%num_tot Lines 137-148
 138 iihru = plcal(ireg)%num(ihru_s)
DO ipl = 1, pcom(iihru)%npl Lines 139-147
IF (plcal(ireg)%lum(ilum)%meas%name == pcom(iihru)%pl(ipl)) THEN Lines 140-146
 142 pcom(iihru)%plcur(ipl)%epco = plcal(ireg)%lum(ilum)%prm%epco
 143 pcom(iihru)%plcur(ipl)%epco = amin1 (pcom(iihru)%plcur(ipl)%epco, pl_prms(ireg)%prm(ilum+nvar)%up)
 144 pcom(iihru)%plcur(ipl)%epco = Max (pcom(iihru)%plcur(ipl)%epco, pl_prms(ireg)%prm(ilum+nvar)%lo)
 145 pcom_init(iihru)%plcur(ipl)%epco = pcom(iihru)%plcur(ipl)%epco
END IFLine 146
END DOLine 147
END DOLine 148
END IFLine 150
END DOLine 151
END DOLine 152
IF (isim > 0) THEN Lines 154-158
 155 cal_sim =  " 1st epco adj "
 156 call calsoft_plant_zero
 157 call time_control
END IFLine 158
DO ist = 1, 4 !iter_ind Lines 161-221
 162 isim = 0
DO ireg = 1, db_mx%plcal_reg Lines 163-214
 164 nvar = plcal(ireg)%lum_num    ! epco is second variable
DO ilum = 1, plcal(ireg)%lum_num Lines 165-212
 166 soft = plcal(ireg)%lum(ilum)%meas%yield
 167 diff = 0.
 168 if (soft > 1.e-6) diff = abs((soft - plcal(ireg)%lum(ilum)%aa%yield) / soft)
IF (diff > .03 .and. plcal(ireg)%lum(ilum)%ha > 1.e-6 .or. plcal(ireg)%lum(ilum)%prm_lim%epco > 1.e-6) THEN Lines 169-210
IF (plcal(ireg)%lum(ilum)%prm_lim%epco < 1.e-6) THEN Lines 170-209
re-initialize all objects (line 193)
 171 isim = 1
 178 plcal(ireg)%lum(ilum)%prm%epco = .333 * (plcal(ireg)%lum(ilum)%prm_uplim%epco -   &
 179 plcal(ireg)%lum(ilum)%prm_lowlim%epco) + plcal(ireg)%lum(ilum)%prm_lowlim%epco
 181 plcal(ireg)%lum(ilum)%prm_prev%epco = plcal(ireg)%lum(ilum)%prm%epco
 182 plcal(ireg)%lum(ilum)%prev%yield = plcal(ireg)%lum(ilum)%aa%yield
 194 call re_initialize
IF (plcal(ireg)%lum(ilum)%aa%yield > soft) THEN Lines 173-174
 174 plcal(ireg)%lum(ilum)%prm_uplim%epco = plcal(ireg)%lum(ilum)%prm%epco
END IFLine 174
ELSE Lines 175-177
 176 plcal(ireg)%lum(ilum)%prm_lowlim%epco = plcal(ireg)%lum(ilum)%prm%epco
END IF Line 177
IF (plcal(ireg)%lum(ilum)%prm%epco >= pl_prms(ireg)%prm(ilum+nvar)%pos) THEN Lines 184-187
 185 plcal(ireg)%lum(ilum)%prm%epco = pl_prms(ireg)%prm(ilum+nvar)%pos
 186 plcal(ireg)%lum(ilum)%prm_lim%epco = 1.
END IFLine 187
IF (plcal(ireg)%lum(ilum)%prm%epco <= pl_prms(ireg)%prm(ilum+nvar)%neg) THEN Lines 188-191
 189 plcal(ireg)%lum(ilum)%prm%epco = pl_prms(ireg)%prm(ilum+nvar)%neg
 190 plcal(ireg)%lum(ilum)%prm_lim%epco = 1.
END IFLine 191
DO ihru_s = 1, plcal(ireg)%num_tot Lines 196-207
 197 iihru = plcal(ireg)%num(ihru_s)
DO ipl = 1, pcom(iihru)%npl Lines 198-206
IF (plcal(ireg)%lum(ilum)%meas%name == pcom(iihru)%pl(ipl)) THEN Lines 199-205
 201 pcom(iihru)%plcur(ipl)%epco = plcal(ireg)%lum(ilum)%prm%epco
 202 pcom(iihru)%plcur(ipl)%epco = amin1 (pcom(iihru)%plcur(ipl)%epco, pl_prms(ireg)%prm(ilum+nvar)%up)
 203 pcom(iihru)%plcur(ipl)%epco = Max (pcom(iihru)%plcur(ipl)%epco, pl_prms(ireg)%prm(ilum+nvar)%lo)
 204 pcom_init(iihru)%plcur(ipl)%epco = pcom(iihru)%plcur(ipl)%epco
END IFLine 205
END DOLine 206
END DOLine 207
END IFLine 209
END IFLine 210
END DOLine 212
END DOLine 214
IF (isim > 0) THEN Lines 216-220
 217 cal_sim =  " epco adj "
 218 call calsoft_plant_zero
 219 call time_control
END IFLine 220
END DOLine 221
DO ireg = 1, db_mx%plcal_reg Lines 225-273
DO ilum = 1, plcal(ireg)%lum_num Lines 226-272
 227 soft = plcal(ireg)%lum(ilum)%meas%yield
 228 diff = 0.
 229 if (soft > 1.e-6) diff = abs((soft - plcal(ireg)%lum(ilum)%aa%yield) / soft)
IF (diff > .03 .and. plcal(ireg)%lum(ilum)%ha > 1.e-6) THEN Lines 230-270
re-initialize all objects (line 254)
 231 isim = 1
 233 plcal(ireg)%lum(ilum)%prm_prev = plcal(ireg)%lum(ilum)%prm
 234 plcal(ireg)%lum(ilum)%prev = plcal(ireg)%lum(ilum)%aa
 236 diff = (plcal(ireg)%lum(ilum)%aa%yield - soft) / soft
 237 chg_val = diff
 239 plcal(ireg)%lum(ilum)%prm_prev%pest_stress = plcal(ireg)%lum(ilum)%prm%pest_stress
 240 plcal(ireg)%lum(ilum)%prm%pest_stress = plcal(ireg)%lum(ilum)%prm%pest_stress + chg_val
 241 plcal(ireg)%lum(ilum)%prev%yield = plcal(ireg)%lum(ilum)%aa%yield
 255 call re_initialize
IF (plcal(ireg)%lum(ilum)%prm%pest_stress >= pl_prms(ireg)%prm(ilum)%pos) THEN Lines 243-247
 244 chg_val = pl_prms(ireg)%prm(ilum)%pos
 245 plcal(ireg)%lum(ilum)%prm%pest_stress = pl_prms(ireg)%prm(ilum)%pos
 246 plcal(ireg)%lum(ilum)%prm_lim%pest_stress = 1.
END IFLine 247
IF (plcal(ireg)%lum(ilum)%prm%pest_stress <= pl_prms(ireg)%prm(ilum)%neg) THEN Lines 248-252
 249 chg_val = pl_prms(ireg)%prm(ilum)%neg
 250 plcal(ireg)%lum(ilum)%prm%pest_stress = pl_prms(ireg)%prm(ilum)%neg
 251 plcal(ireg)%lum(ilum)%prm_lim%pest_stress = 1.
END IFLine 252
DO ihru_s = 1, plcal(ireg)%num_tot Lines 257-268
 258 iihru = plcal(ireg)%num(ihru_s)
DO ipl = 1, pcom(iihru)%npl Lines 259-267
IF (plcal(ireg)%lum(ilum)%meas%name == pcom(iihru)%pl(ipl)) THEN Lines 260-266
 262 pcom(iihru)%plcur(ipl)%pest_stress = pcom(iihru)%plcur(ipl)%pest_stress + chg_val
 263 pcom(iihru)%plcur(ipl)%pest_stress = amin1 (pcom(iihru)%plcur(ipl)%pest_stress, pl_prms(ireg)%prm(ilum)%up)
 264 pcom(iihru)%plcur(ipl)%pest_stress = Max (pcom(iihru)%plcur(ipl)%pest_stress, pl_prms(ireg)%prm(ilum)%lo)
 265 pcom_init(iihru)%plcur(ipl)%pest_stress = pcom(iihru)%plcur(ipl)%pest_stress
END IFLine 266
END DOLine 267
END DOLine 268
END IFLine 270
END DOLine 272
END DOLine 273
IF (isim > 0) THEN Lines 275-279
 276 cal_sim =  " pest stress adj "
 277 call calsoft_plant_zero
 278 call time_control
END IFLine 279
DO ireg = 1, db_mx%plcal_reg Lines 284-332
 285 nvar = 2 * plcal(ireg)%lum_num    ! lai_pot is second variable
DO ilum = 1, plcal(ireg)%lum_num Lines 286-331
 287 soft = plcal(ireg)%lum(ilum)%meas%yield
 288 diff = 0.
 289 if (soft > 1.e-6) diff = abs((soft - plcal(ireg)%lum(ilum)%aa%yield) / soft)
IF (diff > .03 .and. plcal(ireg)%lum(ilum)%ha > 1.e-6) THEN Lines 290-329
re-initialize all objects (line 313)
 291 isim = 1
 293 plcal(ireg)%lum(ilum)%prm_prev = plcal(ireg)%lum(ilum)%prm
 294 plcal(ireg)%lum(ilum)%prev = plcal(ireg)%lum(ilum)%aa
 296 diff = (soft - plcal(ireg)%lum(ilum)%aa%yield) / soft
 297 chg_val =  diff * 5.     !assume 1 lai for every 20% difference in yield
 298 plcal(ireg)%lum(ilum)%prm_prev%lai_pot = plcal(ireg)%lum(ilum)%prm%lai_pot
 299 plcal(ireg)%lum(ilum)%prm%lai_pot = plcal(ireg)%lum(ilum)%prm%lai_pot + chg_val
 300 plcal(ireg)%lum(ilum)%prev%yield = plcal(ireg)%lum(ilum)%aa%yield
 314 call re_initialize
IF (plcal(ireg)%lum(ilum)%prm%lai_pot >= pl_prms(ireg)%prm(ilum+nvar)%pos) THEN Lines 302-306
 303 chg_val = pl_prms(ireg)%prm(ilum+nvar)%pos - plcal(ireg)%lum(ilum)%prm_prev%lai_pot
 304 plcal(ireg)%lum(ilum)%prm%lai_pot = pl_prms(ireg)%prm(ilum+nvar)%pos
 305 plcal(ireg)%lum(ilum)%prm_lim%lai_pot = 1.
END IFLine 306
IF (plcal(ireg)%lum(ilum)%prm%lai_pot <= pl_prms(ireg)%prm(ilum+nvar)%neg) THEN Lines 307-311
 308 chg_val = pl_prms(ireg)%prm(ilum+nvar)%neg - plcal(ireg)%lum(ilum)%prm_prev%lai_pot
 309 plcal(ireg)%lum(ilum)%prm%lai_pot = pl_prms(ireg)%prm(ilum+nvar)%neg
 310 plcal(ireg)%lum(ilum)%prm_lim%lai_pot = 1.
END IFLine 311
DO ihru_s = 1, plcal(ireg)%num_tot Lines 316-327
 317 iihru = plcal(ireg)%num(ihru_s)
DO ipl = 1, pcom(iihru)%npl Lines 318-326
IF (plcal(ireg)%lum(ilum)%meas%name == pcom(iihru)%pl(ipl)) THEN Lines 319-325
 321 pcom(iihru)%plcur(ipl)%lai_pot = pcom(iihru)%plcur(ipl)%lai_pot + chg_val
 322 pcom(iihru)%plcur(ipl)%lai_pot = amin1 (pcom(iihru)%plcur(ipl)%lai_pot, pl_prms(ireg)%prm(ilum+nvar)%up)
 323 pcom(iihru)%plcur(ipl)%lai_pot = Max (pcom(iihru)%plcur(ipl)%lai_pot, pl_prms(ireg)%prm(ilum+nvar)%lo)
 324 pcom_init(iihru)%plcur(ipl)%lai_pot = pcom(iihru)%plcur(ipl)%lai_pot
END IFLine 325
END DOLine 326
END DOLine 327
END IFLine 329
END DOLine 331
END DOLine 332
IF (isim > 0) THEN Lines 335-339
 336 cal_sim =  " first lai potential adj "
 337 call calsoft_plant_zero
 338 call time_control
END IFLine 339
DO ist = 1, 2 !iter_ind
 343 isim = 0
 406 end do      ! ist
 410 isim = 0
DO ireg = 1, db_mx%plcal_reg Lines 344-398
 345 nvar = 2 * plcal(ireg)%lum_num    ! lai_pot is second variable
DO ilum = 1, plcal(ireg)%lum_num Lines 346-396
 347 soft = plcal(ireg)%lum(ilum)%meas%yield
 348 diff = 0.
 349 if (soft > 1.e-6) diff = abs((soft - plcal(ireg)%lum(ilum)%aa%yield) / soft)
IF (diff > .03 .and. plcal(ireg)%lum(ilum)%ha > 1.e-6) THEN Lines 350-394
re-initialize all objects (line 378)
 351 isim = 1
 353 rmeas = plcal(ireg)%lum(ilum)%meas%yield
 354 denom = plcal(ireg)%lum(ilum)%prev%yield - plcal(ireg)%lum(ilum)%aa%yield
 362 diff = (soft - plcal(ireg)%lum(ilum)%aa%yield) / soft
 363 chg_val =  diff * 5.     !assume 1 lai for every 20% difference in yield
 365 plcal(ireg)%lum(ilum)%prm_prev%lai_pot = plcal(ireg)%lum(ilum)%prm%lai_pot
 366 plcal(ireg)%lum(ilum)%prm%lai_pot = plcal(ireg)%lum(ilum)%prm%lai_pot + chg_val
 367 plcal(ireg)%lum(ilum)%prev%yield = plcal(ireg)%lum(ilum)%aa%yield
 379 call re_initialize
IF (abs(denom) > 1.e-6) THEN Lines 355-357
 356 chg_val = - (plcal(ireg)%lum(ilum)%prm_prev%lai_pot - plcal(ireg)%lum(ilum)%prm%lai_pot) *                &
 357 (plcal(ireg)%lum(ilum)%aa%yield - rmeas) / denom
END IFLine 357
ELSE Lines 358-360
 359 chg_val = diff / 5.     !assume 1 lai for every 20% difference in yield
END IF Line 360
IF (plcal(ireg)%lum(ilum)%prm%lai_pot >= pl_prms(ireg)%prm(ilum+nvar)%pos) THEN Lines 369-372
 370 plcal(ireg)%lum(ilum)%prm%lai_pot = pl_prms(ireg)%prm(ilum+nvar)%pos
 371 plcal(ireg)%lum(ilum)%prm_lim%lai_pot = 1.
END IFLine 372
IF (plcal(ireg)%lum(ilum)%prm%lai_pot <= pl_prms(ireg)%prm(ilum+nvar)%neg) THEN Lines 373-376
 374 plcal(ireg)%lum(ilum)%prm%lai_pot = pl_prms(ireg)%prm(ilum+nvar)%neg
 375 plcal(ireg)%lum(ilum)%prm_lim%lai_pot = 1.
END IFLine 376
DO ihru_s = 1, plcal(ireg)%num_tot Lines 381-392
 382 iihru = plcal(ireg)%num(ihru_s)
DO ipl = 1, pcom(iihru)%npl Lines 383-391
IF (plcal(ireg)%lum(ilum)%meas%name == pcom(iihru)%pl(ipl)) THEN Lines 384-390
 386 pcom(iihru)%plcur(ipl)%lai_pot = pcom(iihru)%plcur(ipl)%lai_pot + chg_val
 387 pcom(iihru)%plcur(ipl)%lai_pot = amin1 (pcom(iihru)%plcur(ipl)%lai_pot, pl_prms(ireg)%prm(ilum+nvar)%up)
 388 pcom(iihru)%plcur(ipl)%lai_pot = Max (pcom(iihru)%plcur(ipl)%lai_pot, pl_prms(ireg)%prm(ilum+nvar)%lo)
 389 pcom_init(iihru)%plcur(ipl)%lai_pot = pcom(iihru)%plcur(ipl)%lai_pot
END IFLine 390
END DOLine 391
END DOLine 392
END IFLine 394
END DOLine 396
END DOLine 398
IF (isim > 0) THEN Lines 401-405
 402 cal_sim =  " lai potential adj "
 403 call calsoft_plant_zero
 404 call time_control
END IFLine 405
DO ireg = 1, db_mx%plcal_reg Lines 411-459
 412 nvar = 3 * plcal(ireg)%lum_num    ! harv_idx is third variable
DO ilum = 1, plcal(ireg)%lum_num Lines 413-458
 414 soft = plcal(ireg)%lum(ilum)%meas%yield
 415 diff = 0.
 416 if (soft > 1.e-6) diff = abs((soft - plcal(ireg)%lum(ilum)%aa%yield) / soft)
IF (diff > .03 .and. plcal(ireg)%lum(ilum)%ha > 1.e-6) THEN Lines 417-456
re-initialize all objects (line 440)
 418 isim = 1
 420 plcal(ireg)%lum(ilum)%prm_prev = plcal(ireg)%lum(ilum)%prm
 421 plcal(ireg)%lum(ilum)%prev = plcal(ireg)%lum(ilum)%aa
 423 diff = (plcal(ireg)%lum(ilum)%meas%yield - plcal(ireg)%lum(ilum)%aa%yield) / plcal(ireg)%lum(ilum)%meas%yield
 424 chg_val = diff / 2.     !assume frac diff over 4.
 425 plcal(ireg)%lum(ilum)%prm_prev%harv_idx = plcal(ireg)%lum(ilum)%prm%harv_idx
 426 plcal(ireg)%lum(ilum)%prm%harv_idx = plcal(ireg)%lum(ilum)%prm%harv_idx + chg_val
 427 plcal(ireg)%lum(ilum)%prev%yield = plcal(ireg)%lum(ilum)%aa%yield
 441 call re_initialize
IF (plcal(ireg)%lum(ilum)%prm%harv_idx >= pl_prms(ireg)%prm(ilum+nvar)%pos) THEN Lines 429-433
 430 chg_val = pl_prms(ireg)%prm(ilum+nvar)%pos - plcal(ireg)%lum(ilum)%prm_prev%harv_idx
 431 plcal(ireg)%lum(ilum)%prm%harv_idx = pl_prms(ireg)%prm(ilum+nvar)%pos
 432 plcal(ireg)%lum(ilum)%prm_lim%harv_idx = 1.
END IFLine 433
IF (plcal(ireg)%lum(ilum)%prm%harv_idx <= pl_prms(ireg)%prm(ilum+nvar)%neg) THEN Lines 434-438
 435 chg_val = pl_prms(ireg)%prm(ilum+nvar)%neg - plcal(ireg)%lum(ilum)%prm_prev%harv_idx
 436 plcal(ireg)%lum(ilum)%prm%harv_idx = pl_prms(ireg)%prm(ilum+nvar)%neg
 437 plcal(ireg)%lum(ilum)%prm_lim%harv_idx = 1.
END IFLine 438
DO ihru_s = 1, plcal(ireg)%num_tot Lines 443-454
 444 iihru = plcal(ireg)%num(ihru_s)
DO ipl = 1, pcom(iihru)%npl Lines 445-453
IF (plcal(ireg)%lum(ilum)%meas%name == pcom(iihru)%pl(ipl)) THEN Lines 446-452
 448 pcom(iihru)%plcur(ipl)%harv_idx = pcom(iihru)%plcur(ipl)%harv_idx + chg_val
 449 pcom(iihru)%plcur(ipl)%harv_idx = amin1 (pcom(iihru)%plcur(ipl)%harv_idx, pl_prms(ireg)%prm(ilum+nvar)%up)
 450 pcom(iihru)%plcur(ipl)%harv_idx = Max (pcom(iihru)%plcur(ipl)%harv_idx, pl_prms(ireg)%prm(ilum+nvar)%lo)
 451 pcom_init(iihru)%plcur(ipl)%harv_idx = pcom(iihru)%plcur(ipl)%harv_idx
END IFLine 452
END DOLine 453
END DOLine 454
END IFLine 456
END DOLine 458
END DOLine 459
IF (isim > 0) THEN Lines 462-466
 463 cal_sim = " first harvest index adj "
 464 call calsoft_plant_zero
 465 call time_control
END IFLine 466
DO ist = 1, 2 !iter_ind
 470 isim = 0
 531 end do      ! ist
 533 end do    ! iter_all loop
 534 return
DO ireg = 1, db_mx%plcal_reg Lines 471-523
 472 nvar = 3 * plcal(ireg)%lum_num    ! harv_idx is third variable
DO ilum = 1, plcal(ireg)%lum_num Lines 473-522
 474 soft = plcal(ireg)%lum(ilum)%meas%yield
 475 diff = 0.
 476 if (soft > 1.e-6) diff = abs((soft - plcal(ireg)%lum(ilum)%aa%yield) / soft)
IF (diff > .03 .and. plcal(ireg)%lum(ilum)%ha > 1.e-6) THEN Lines 477-520
re-initialize all objects (line 504)
 478 isim = 1
 486 diff = (plcal(ireg)%lum(ilum)%meas%yield - plcal(ireg)%lum(ilum)%aa%yield) / plcal(ireg)%lum(ilum)%meas%yield
 487 chg_val = diff / 2.
 489 plcal(ireg)%lum(ilum)%prm_prev%harv_idx = plcal(ireg)%lum(ilum)%prm%harv_idx
 490 plcal(ireg)%lum(ilum)%prm%harv_idx = plcal(ireg)%lum(ilum)%prm%harv_idx + chg_val
 491 plcal(ireg)%lum(ilum)%prev%yield = plcal(ireg)%lum(ilum)%aa%yield
 505 call re_initialize
IF (plcal(ireg)%lum(ilum)%prm%harv_idx >= pl_prms(ireg)%prm(ilum+nvar)%pos) THEN Lines 493-497
 494 chg_val = pl_prms(ireg)%prm(ilum+nvar)%pos - plcal(ireg)%lum(ilum)%prm_prev%harv_idx
 495 plcal(ireg)%lum(ilum)%prm%harv_idx = pl_prms(ireg)%prm(ilum+nvar)%pos
 496 plcal(ireg)%lum(ilum)%prm_lim%harv_idx = 1.
END IFLine 497
IF (plcal(ireg)%lum(ilum)%prm%harv_idx <= pl_prms(ireg)%prm(ilum+nvar)%neg) THEN Lines 498-502
 499 chg_val = pl_prms(ireg)%prm(ilum+nvar)%neg - plcal(ireg)%lum(ilum)%prm_prev%harv_idx
 500 plcal(ireg)%lum(ilum)%prm%harv_idx = pl_prms(ireg)%prm(ilum+nvar)%neg
 501 plcal(ireg)%lum(ilum)%prm_lim%harv_idx = 1.
END IFLine 502
DO ihru_s = 1, plcal(ireg)%num_tot Lines 507-518
 508 iihru = plcal(ireg)%num(ihru_s)
DO ipl = 1, pcom(iihru)%npl Lines 509-517
IF (plcal(ireg)%lum(ilum)%meas%name == pcom(iihru)%pl(ipl)) THEN Lines 510-516
 512 pcom(iihru)%plcur(ipl)%harv_idx = pcom(iihru)%plcur(ipl)%harv_idx + chg_val
 513 pcom(iihru)%plcur(ipl)%harv_idx = amin1 (pcom(iihru)%plcur(ipl)%harv_idx, pl_prms(ireg)%prm(ilum+nvar)%up)
 514 pcom(iihru)%plcur(ipl)%harv_idx = Max (pcom(iihru)%plcur(ipl)%harv_idx, pl_prms(ireg)%prm(ilum+nvar)%lo)
 515 pcom_init(iihru)%plcur(ipl)%harv_idx = pcom(iihru)%plcur(ipl)%harv_idx
END IFLine 516
END DOLine 517
END DOLine 518
END IFLine 520
END DOLine 522
END DOLine 523
IF (isim > 0) THEN Lines 526-530
 527 cal_sim = " harvest index adj "
 528 call calsoft_plant_zero
 529 call time_control
END IFLine 530
END DO
END DO
END DO
END DO
END IF
END IF
END DO
END DO
Allocations
n/a
Calls
Procedures Called
List of procedures called by this Subroutine.
amin1
calsoft_plant_zero
time_control
re_initialize
Call Graph
Visual representation of procedures called by this Subroutine.
Call graph
calsoft_plant calls amin1, calsoft_plant_zero, re_initialize, time_control