calsoft_hyd_bfr_latq – TestDataProject
calsoft_hyd_bfr_latq Subroutine
130 statements
Source File
subroutine calsoft_hyd_bfr_latq()
Called From
n/a
Arguments
n/a
Outside Variables and Types
type(soft_calib_parms) (1 attribute from calibration_data_module)
Attribute Name Description
ls_prms
type(soft_calib_ls_processes) (1 attribute from calibration_data_module)
Attribute Name Description
lscal_z
to zero values
type(soft_data_calib_landscape) (1 attribute from calibration_data_module)
Attribute Name Description
lscal
dimension by region for hru"s
type(cataloging_units) (1 attribute from calibration_data_module)
Attribute Name Description
region
dimension by region for hru"s
character(len=29) (1 attribute from time_module)
Attribute Name Description
cal_sim
real (1 attribute from time_module)
Attribute Name Description
cal_adj
type (1 attribute from maximum_data_module)
Attribute Name Description
db_mx%lsu_reg None
type(hydrologic_response_unit) (2 attributes from hru_module)
Attribute Name Description
hru
hru_init
Uses
basin_module
sd_channel_module
conditional_module
soil_module
calibration_data_module
hydrograph_module
time_module
maximum_data_module
aquifer_module
reservoir_module
hru_module
channel_module
organic_mineral_mass_module
plant_module
hru_lte_module
ru_module
I/O
n/a
Local Variables
Type Visibility Attributes Name Initial
integer, public :: isim = 0
integer, public :: ireg = 0
integer, public :: ilum = 0
integer, public :: iihru = 0
integer, public :: ihru_s = 0
integer, public :: iter_ind = 0
integer, public :: ik = 0
real, public :: rmeas = 0.
real, public :: denom = 0.
real, public :: soft = 0.
real, public :: diff = 0.
real, public :: chg_val = 0.
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure. Use mouse wheel to zoom, drag to pan.
Reset Zoom Help
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
  36 iter_ind = 1
  39 isim = 0
DO ireg = 1, db_mx%lsu_reg Lines 40-93
DO ilum = 1, region(ireg)%nlum Lines 41-92
  43 soft = lscal(ireg)%lum(ilum)%meas%lfr * lscal(ireg)%lum(ilum)%precip_aa
  44 diff = 0.
  45 if (soft > 1.e-6) diff = abs((soft - lscal(ireg)%lum(ilum)%aa%lfr) / soft)
IF (diff > .1 .and. lscal(ireg)%lum(ilum)%ha > 1.e-6) THEN Lines 46-91
  47 isim = 1
  49 lscal(ireg)%lum(ilum)%prm_prev = lscal(ireg)%lum(ilum)%prm
  50 lscal(ireg)%lum(ilum)%prev = lscal(ireg)%lum(ilum)%aa
  52 diff = lscal(ireg)%lum(ilum)%meas%lfr * lscal(ireg)%lum(ilum)%precip_aa - lscal(ireg)%lum(ilum)%aa%lfr
  53 chg_val =  0.005 * diff
  59 lscal(ireg)%lum(ilum)%prm_prev%lat_len = lscal(ireg)%lum(ilum)%prm%lat_len
  60 lscal(ireg)%lum(ilum)%prm%lat_len = lscal(ireg)%lum(ilum)%prm%lat_len + chg_val
  61 lscal(ireg)%lum(ilum)%prev%lfr = lscal(ireg)%lum(ilum)%aa%lfr
  84 lscal(ireg)%lum(ilum)%nbyr = 0
  85 lscal(ireg)%lum(ilum)%precip_aa = 0.
  86 lscal(ireg)%lum(ilum)%aa = lscal_z
IF (lscal(ireg)%lum(ilum)%prm%lat_len >= ls_prms(3)%pos) THEN Lines 63-67
  64 lscal(ireg)%lum(ilum)%prm%lat_len = ls_prms(3)%pos
  65 chg_val = ls_prms(3)%pos
  66 lscal(ireg)%lum(ilum)%prm_lim%lat_len = 1.
END IFLine 67
IF (lscal(ireg)%lum(ilum)%prm%lat_len <= ls_prms(3)%neg) THEN Lines 68-72
  69 lscal(ireg)%lum(ilum)%prm%lat_len = ls_prms(3)%neg
  70 chg_val = ls_prms(3)%neg
  71 lscal(ireg)%lum(ilum)%prm_lim%lat_len = 1.
END IFLine 72
DO ihru_s = 1, region(ireg)%num_tot Lines 74-83
  75 iihru = region(ireg)%num(ihru_s)
IF (lscal(ireg)%lum(ilum)%meas%name == hru(iihru)%lum_group_c .or. lscal(ireg)%lum(ilum)%meas%name == "basin") THEN Lines 76-82
  78 hru(iihru)%hyd%latq_co = hru(iihru)%hyd%latq_co + chg_val
  79 hru(iihru)%hyd%latq_co = amin1 (hru(iihru)%hyd%latq_co, ls_prms(3)%up)
  80 hru(iihru)%hyd%latq_co = Max (hru(iihru)%hyd%latq_co, ls_prms(3)%lo)
  81 hru_init(iihru)%hyd%latq_co = hru(iihru)%hyd%latq_co
END IFLine 82
END DOLine 83
END IFLine 91
END DOLine 92
END DOLine 93
re-initialize all objects (line 95)
  96 call re_initialize
IF (isim > 0) THEN Lines 99-103
 100 cal_sim =  " first latq_co adj "
 101 cal_adj = chg_val
 102 call time_control
END IFLine 103
DO ik = 1, 2 !iter_ind Lines 106-170
re-initialize all objects (line 161)
 107 isim = 0
 162 call re_initialize
DO ireg = 1, db_mx%lsu_reg Lines 108-159
DO ilum = 1, region(ireg)%nlum Lines 109-158
 110 soft = lscal(ireg)%lum(ilum)%meas%lfr * lscal(ireg)%lum(ilum)%precip_aa
 111 diff = 0.
 112 if (soft > 1.e-6) diff = abs((soft - lscal(ireg)%lum(ilum)%aa%lfr) / soft)
IF (diff > .05 .and. lscal(ireg)%lum(ilum)%ha > 1.e-6) THEN Lines 113-157
 114 isim = 1
 116 rmeas = lscal(ireg)%lum(ilum)%meas%lfr * lscal(ireg)%lum(ilum)%precip_aa
 117 denom = lscal(ireg)%lum(ilum)%prev%lfr - lscal(ireg)%lum(ilum)%aa%lfr
 124 lscal(ireg)%lum(ilum)%prm_prev%lat_len = lscal(ireg)%lum(ilum)%prm%lat_len
 125 lscal(ireg)%lum(ilum)%prm%lat_len = lscal(ireg)%lum(ilum)%prm%lat_len + chg_val
 126 lscal(ireg)%lum(ilum)%prev%lfr = lscal(ireg)%lum(ilum)%aa%lfr
 150 lscal(ireg)%lum(ilum)%nbyr = 0
 151 lscal(ireg)%lum(ilum)%precip_aa = 0.
 152 lscal(ireg)%lum(ilum)%aa = lscal_z
IF (abs(denom) > 1.) THEN Lines 118-120
 119 chg_val = - (lscal(ireg)%lum(ilum)%prm_prev%lat_len - lscal(ireg)%lum(ilum)%prm%lat_len)                  &
 120 * (lscal(ireg)%lum(ilum)%aa%lfr - rmeas) / denom
END IFLine 120
ELSE Lines 121-123
 122 chg_val = - diff
END IF Line 123
IF (lscal(ireg)%lum(ilum)%prm%lat_len >= ls_prms(3)%pos) THEN Lines 128-132
 129 lscal(ireg)%lum(ilum)%prm%lat_len = ls_prms(3)%pos
 130 chg_val = ls_prms(3)%pos
 131 lscal(ireg)%lum(ilum)%prm_lim%lat_len = 1.
END IFLine 132
IF (lscal(ireg)%lum(ilum)%prm%lat_len <= ls_prms(3)%neg) THEN Lines 133-137
 134 lscal(ireg)%lum(ilum)%prm%lat_len = ls_prms(3)%neg
 135 chg_val = ls_prms(3)%neg
 136 lscal(ireg)%lum(ilum)%prm_lim%lat_len = 1.
END IFLine 137
DO ihru_s = 1, region(ireg)%num_tot Lines 140-149
 141 iihru = region(ireg)%num(ihru_s)
IF (lscal(ireg)%lum(ilum)%meas%name == hru(iihru)%lum_group_c .or. lscal(ireg)%lum(ilum)%meas%name == "basin") THEN Lines 142-148
 144 hru(iihru)%hyd%latq_co = hru(iihru)%hyd%latq_co + chg_val
 145 hru(iihru)%hyd%latq_co = amin1 (hru(iihru)%hyd%latq_co, ls_prms(3)%up)
 146 hru(iihru)%hyd%latq_co = Max (hru(iihru)%hyd%latq_co, ls_prms(3)%lo)
 147 hru_init(iihru)%hyd%latq_co = hru(iihru)%hyd%latq_co
END IFLine 148
END DOLine 149
END IFLine 157
END DOLine 158
END DOLine 159
IF (isim > 0) THEN Lines 165-169
 166 cal_sim =  " latq_co adj "
 167 cal_adj = chg_val
 168 call time_control
END IFLine 169
END DOLine 170
 172 return
Allocations
n/a
Calls
Procedures Called
List of procedures called by this Subroutine.
amin1
re_initialize
time_control
Call Graph
Visual representation of procedures called by this Subroutine.
Call graph
calsoft_hyd_bfr_latq calls amin1, re_initialize, time_control