calsoft_hyd – TestDataProject
calsoft_hyd Subroutine
618 statements
Source File
subroutine calsoft_hyd()
Called From
n/a
Arguments
n/a
Outside Variables and Types
type(soft_calib_parms) (1 attribute from calibration_data_module)
Attribute Name Description
ls_prms
type(soft_calib_ls_processes) (1 attribute from calibration_data_module)
Attribute Name Description
lscal_z
to zero values
type(soft_data_calib_landscape) (1 attribute from calibration_data_module)
Attribute Name Description
lscal
dimension by region for hru"s
type(cataloging_units) (1 attribute from calibration_data_module)
Attribute Name Description
region
dimension by region for hru"s
character(len=29) (1 attribute from time_module)
Attribute Name Description
cal_sim
real (2 attributes from time_module)
Attribute Name Description
cal_adj
cn2
type (1 attribute from maximum_data_module)
Attribute Name Description
db_mx%lsu_reg None
type(hydrologic_response_unit) (2 attributes from hru_module)
Attribute Name Description
hru
hru_init
Uses
basin_module
sd_channel_module
conditional_module
soil_module
calibration_data_module
hydrograph_module
time_module
maximum_data_module
aquifer_module
reservoir_module
hru_module
channel_module
organic_mineral_mass_module
plant_module
hru_lte_module
ru_module
I/O
n/a
Local Variables
Type Visibility Attributes Name Initial
integer, public :: iter_all = 0
integer, public :: iterall = 0
integer, public :: isim = 0
integer, public :: ireg = 0
integer, public :: ilum = 0
integer, public :: iihru = 0
integer, public :: icn = 0
integer, public :: ihru_s = 0
integer, public :: iter_ind = 0
integer, public :: ietco = 0
integer, public :: ik = 0
integer, public :: iperco = 0
real, public :: rmeas = 0.
real, public :: denom = 0.
real, public :: soft = 0.
real, public :: diff = 0.
real, public :: chg_val = 0.
real, public :: perc_ln_func = 0.
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure. Use mouse wheel to zoom, drag to pan.
Reset Zoom Help
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
  42 iter_all = 1
  43 iter_ind = 1
DO iterall = 1, iter_all
re-initialize all objects (line 104)
  48 isim = 0
 105 call re_initialize
DO ireg = 1, db_mx%lsu_reg Lines 49-102
DO ilum = 1, region(ireg)%nlum Lines 50-101
  51 soft = lscal(ireg)%lum(ilum)%meas%etr * lscal(ireg)%lum(ilum)%precip_aa
  52 diff = 0.
  53 if (soft > 1.e-6) diff = abs((soft - lscal(ireg)%lum(ilum)%aa%etr) / soft)
IF (diff > .01 .and. lscal(ireg)%lum(ilum)%ha > 1.e-6 .and. lscal(ireg)%lum(ilum)%prm_lim%etco < 1.e-6) THEN Lines 54-100
  55 isim = 1
  57 lscal(ireg)%lum(ilum)%prm_prev = lscal(ireg)%lum(ilum)%prm
  58 lscal(ireg)%lum(ilum)%prev = lscal(ireg)%lum(ilum)%aa
  60 diff = lscal(ireg)%lum(ilum)%meas%etr * lscal(ireg)%lum(ilum)%precip_aa - lscal(ireg)%lum(ilum)%aa%etr
  61 chg_val = diff / 500.     ! increment etco .4 for every 100 mm difference
  62 lscal(ireg)%lum(ilum)%prm_prev%etco = lscal(ireg)%lum(ilum)%prm%etco
  63 lscal(ireg)%lum(ilum)%prm%etco = lscal(ireg)%lum(ilum)%prm%etco + chg_val
  64 lscal(ireg)%lum(ilum)%prev%etr = lscal(ireg)%lum(ilum)%aa%etr
  91 lscal(ireg)%lum(ilum)%nbyr = 0
  92 lscal(ireg)%lum(ilum)%precip_aa = 0.
  93 lscal(ireg)%lum(ilum)%aa = lscal_z
IF (lscal(ireg)%lum(ilum)%prm%etco >= ls_prms(2)%pos) THEN Lines 66-70
  67 chg_val = ls_prms(2)%pos - lscal(ireg)%lum(ilum)%prm_prev%etco
  68 lscal(ireg)%lum(ilum)%prm%etco = ls_prms(2)%pos
  69 lscal(ireg)%lum(ilum)%prm_lim%etco = 1.
END IFLine 70
IF (lscal(ireg)%lum(ilum)%prm%etco <= ls_prms(2)%neg) THEN Lines 71-75
  72 chg_val = lscal(ireg)%lum(ilum)%prm_prev%etco + ls_prms(2)%neg
  73 lscal(ireg)%lum(ilum)%prm%etco = ls_prms(2)%neg
  74 lscal(ireg)%lum(ilum)%prm_lim%etco = 1.
END IFLine 75
DO ihru_s = 1, region(ireg)%num_tot Lines 77-90
  78 iihru = region(ireg)%num(ihru_s)
IF (lscal(ireg)%lum(ilum)%meas%name == hru(iihru)%lum_group_c .or. lscal(ireg)%lum(ilum)%meas%name == "basin") THEN Lines 79-89
  81 hru(iihru)%hyd%esco = hru(iihru)%hyd%esco + chg_val
  82 hru(iihru)%hyd%esco = amin1 (hru(iihru)%hyd%esco, ls_prms(2)%up)
  83 hru(iihru)%hyd%esco = Max (hru(iihru)%hyd%esco, ls_prms(2)%lo)
  84 hru_init(iihru)%hyd%esco = hru(iihru)%hyd%esco
END IFLine 89
END DOLine 90
END IFLine 100
END DOLine 101
END DOLine 102
IF (isim > 0) THEN Lines 108-112
 109 cal_sim =  " first esco adj "
 110 cal_adj = chg_val
 111 call time_control
END IFLine 112
DO ietco = 1, 2 !iter_ind
re-initialize all objects (line 178)
re-initialize all objects (line 181)
 116 isim = 0
 179 call re_initialize
 182 call re_initialize
 191 end do      ! iesco
DO ireg = 1, db_mx%lsu_reg Lines 117-176
DO ilum = 1, region(ireg)%nlum Lines 118-175
 120 soft = lscal(ireg)%lum(ilum)%meas%etr * lscal(ireg)%lum(ilum)%precip_aa
 121 diff = 0.
 122 if (soft > 1.e-6) diff = abs((soft - lscal(ireg)%lum(ilum)%aa%etr) / soft)
IF (diff > .01 .and. lscal(ireg)%lum(ilum)%ha > 1.e-6 .and. lscal(ireg)%lum(ilum)%prm_lim%etco < 0.99) THEN Lines 123-174
 124 isim = 1
 126 rmeas = lscal(ireg)%lum(ilum)%meas%etr * lscal(ireg)%lum(ilum)%precip_aa
 127 denom = lscal(ireg)%lum(ilum)%prev%etr - lscal(ireg)%lum(ilum)%aa%etr
 138 lscal(ireg)%lum(ilum)%prm_prev%etco = lscal(ireg)%lum(ilum)%prm%etco
 139 lscal(ireg)%lum(ilum)%prm%etco = lscal(ireg)%lum(ilum)%prm%etco + chg_val
 140 lscal(ireg)%lum(ilum)%prev%etr = lscal(ireg)%lum(ilum)%aa%etr
 167 lscal(ireg)%lum(ilum)%nbyr = 0
 168 lscal(ireg)%lum(ilum)%precip_aa = 0.
 169 lscal(ireg)%lum(ilum)%aa = lscal_z
IF (abs(denom) > 1.e-6) THEN Lines 128-130
 129 chg_val = - (lscal(ireg)%lum(ilum)%prm_prev%etco - lscal(ireg)%lum(ilum)%prm%etco)                  &
 130 * (lscal(ireg)%lum(ilum)%aa%etr - rmeas) / denom
END IFLine 130
ELSE Lines 131-134
 132 diff = lscal(ireg)%lum(ilum)%meas%etr * lscal(ireg)%lum(ilum)%precip_aa - lscal(ireg)%lum(ilum)%aa%etr
 133 chg_val = diff / 200.
END IF Line 134
IF (lscal(ireg)%lum(ilum)%prm%etco >= ls_prms(2)%pos) THEN Lines 142-146
 143 chg_val = ls_prms(2)%pos - lscal(ireg)%lum(ilum)%prm_prev%etco
 144 lscal(ireg)%lum(ilum)%prm%etco = ls_prms(2)%pos
 145 lscal(ireg)%lum(ilum)%prm_lim%etco = 1.
END IFLine 146
IF (lscal(ireg)%lum(ilum)%prm%etco <= ls_prms(2)%neg) THEN Lines 147-151
 148 chg_val = ls_prms(2)%neg - lscal(ireg)%lum(ilum)%prm_prev%etco
 149 lscal(ireg)%lum(ilum)%prm%etco = ls_prms(2)%neg
 150 lscal(ireg)%lum(ilum)%prm_lim%etco = 1.
END IFLine 151
DO ihru_s = 1, region(ireg)%num_tot Lines 153-166
 154 iihru = region(ireg)%num(ihru_s)
IF (lscal(ireg)%lum(ilum)%meas%name == hru(iihru)%lum_group_c .or. lscal(ireg)%lum(ilum)%meas%name == "basin") THEN Lines 155-165
 157 hru(iihru)%hyd%esco = hru(iihru)%hyd%esco + chg_val
 158 hru(iihru)%hyd%esco = amin1 (hru(iihru)%hyd%esco, ls_prms(2)%up)
 159 hru(iihru)%hyd%esco = Max (hru(iihru)%hyd%esco, ls_prms(2)%lo)
 160 hru_init(iihru)%hyd%esco = hru(iihru)%hyd%esco
END IFLine 165
END DOLine 166
END IFLine 174
END DOLine 175
END DOLine 176
IF (isim > 0) THEN Lines 185-189
 186 cal_sim =  " esco adj "
 187 cal_adj = chg_val
 188 call time_control
END IFLine 189
DO ietco = 1, 2 !iter_ind
re-initialize all objects (line 251)
re-initialize all objects (line 319)
 195 isim = 0
 252 call re_initialize
 261 end do    ! petco iterations
 264 isim = 0
 320 call re_initialize
DO ireg = 1, db_mx%lsu_reg Lines 196-249
DO ilum = 1, region(ireg)%nlum Lines 197-248
 199 soft = lscal(ireg)%lum(ilum)%meas%etr * lscal(ireg)%lum(ilum)%precip_aa
 200 diff = 0.
 201 if (soft > 1.e-6) diff = abs((soft - lscal(ireg)%lum(ilum)%aa%etr) / soft)
IF (diff > .01 .and. lscal(ireg)%lum(ilum)%ha > 1.e-6) THEN Lines 202-247
 203 isim = 1
 205 lscal(ireg)%lum(ilum)%prm_prev = lscal(ireg)%lum(ilum)%prm
 206 lscal(ireg)%lum(ilum)%prev = lscal(ireg)%lum(ilum)%aa
 213 lscal(ireg)%lum(ilum)%prm_prev%petco = lscal(ireg)%lum(ilum)%prm%petco
 219 lscal(ireg)%lum(ilum)%prm_prev%petco = lscal(ireg)%lum(ilum)%aa%etr
 244 lscal(ireg)%lum(ilum)%nbyr = 0
 245 lscal(ireg)%lum(ilum)%precip_aa = 0.
 246 lscal(ireg)%lum(ilum)%aa = lscal_z
IF (soft < lscal(ireg)%lum(ilum)%aa%etr) THEN Lines 208-209
 209 chg_val = 1. / (abs((soft - lscal(ireg)%lum(ilum)%aa%etr) / soft) + 1.05)
END IFLine 209
ELSE Lines 210-212
 211 chg_val = abs((lscal(ireg)%lum(ilum)%aa%etr - soft) / lscal(ireg)%lum(ilum)%aa%etr) + 1.05
END IF Line 212
IF (ietco == 1) THEN Lines 214-215
 215 lscal(ireg)%lum(ilum)%prm%petco = chg_val
END IFLine 215
ELSE Lines 216-218
 217 lscal(ireg)%lum(ilum)%prm%petco = lscal(ireg)%lum(ilum)%prm%petco * chg_val
END IF Line 218
IF (lscal(ireg)%lum(ilum)%prm%petco >= ls_prms(4)%pos) THEN Lines 221-225
 222 chg_val = ls_prms(4)%pos
 223 lscal(ireg)%lum(ilum)%prm%petco = ls_prms(4)%pos
 224 lscal(ireg)%lum(ilum)%prm_lim%petco = 1.
END IFLine 225
IF (lscal(ireg)%lum(ilum)%prm%petco <= ls_prms(4)%neg) THEN Lines 226-230
 227 chg_val = ls_prms(4)%neg
 228 lscal(ireg)%lum(ilum)%prm%petco = ls_prms(4)%neg
 229 lscal(ireg)%lum(ilum)%prm_lim%petco = 1.
END IFLine 230
DO ihru_s = 1, region(ireg)%num_tot Lines 233-242
 234 iihru = region(ireg)%num(ihru_s)
IF (lscal(ireg)%lum(ilum)%meas%name == hru(iihru)%lum_group_c .or. lscal(ireg)%lum(ilum)%meas%name == "basin") THEN Lines 235-241
 237 hru(iihru)%hyd%pet_co = chg_val * hru(iihru)%hyd%pet_co
 238 hru(iihru)%hyd%pet_co = amin1 (hru(iihru)%hyd%pet_co, ls_prms(4)%up)
 239 hru(iihru)%hyd%pet_co = Max (hru(iihru)%hyd%pet_co, ls_prms(4)%lo)
 240 hru_init(iihru)%hyd%pet_co = hru(iihru)%hyd%pet_co
END IFLine 241
END DOLine 242
END IFLine 247
END DOLine 248
END DOLine 249
IF (isim > 0) THEN Lines 255-259
 256 cal_sim =  " pet adj "
 257 cal_adj = chg_val
 258 call time_control
END IFLine 259
DO ireg = 1, db_mx%lsu_reg Lines 265-317
DO ilum = 1, region(ireg)%nlum Lines 266-316
 267 soft = lscal(ireg)%lum(ilum)%meas%srr * lscal(ireg)%lum(ilum)%precip_aa
 268 diff = 0.
 269 if (soft > 1.e-6) diff = abs((soft - lscal(ireg)%lum(ilum)%aa%srr) / soft)
IF (diff > .02 .and. lscal(ireg)%lum(ilum)%ha > 1.e-6 .and. lscal(ireg)%lum(ilum)%prm_lim%cn3_swf < 1.e-6) THEN Lines 270-315
 271 isim = 1
 273 lscal(ireg)%lum(ilum)%prm_prev = lscal(ireg)%lum(ilum)%prm
 274 lscal(ireg)%lum(ilum)%prev = lscal(ireg)%lum(ilum)%aa
 276 diff = lscal(ireg)%lum(ilum)%meas%srr * lscal(ireg)%lum(ilum)%precip_aa - lscal(ireg)%lum(ilum)%aa%srr
 277 chg_val = - diff / 100.     !assume 10 mm runoff for .1 cn3_swf
 279 lscal(ireg)%lum(ilum)%prm_prev%cn3_swf = lscal(ireg)%lum(ilum)%prm%cn3_swf
 280 lscal(ireg)%lum(ilum)%prm%cn3_swf = lscal(ireg)%lum(ilum)%prm%cn3_swf + chg_val
 281 lscal(ireg)%lum(ilum)%prev%srr = lscal(ireg)%lum(ilum)%aa%srr
 308 lscal(ireg)%lum(ilum)%nbyr = 0
 309 lscal(ireg)%lum(ilum)%precip_aa = 0.
 310 lscal(ireg)%lum(ilum)%aa = lscal_z
IF (lscal(ireg)%lum(ilum)%prm%cn3_swf >= ls_prms(10)%pos) THEN Lines 283-287
 284 chg_val = ls_prms(10)%pos - lscal(ireg)%lum(ilum)%prm_prev%cn3_swf
 285 lscal(ireg)%lum(ilum)%prm%cn3_swf = ls_prms(10)%pos
 286 lscal(ireg)%lum(ilum)%prm_lim%cn3_swf = 1.
END IFLine 287
IF (lscal(ireg)%lum(ilum)%prm%cn3_swf <= ls_prms(10)%neg) THEN Lines 288-292
 289 chg_val = ls_prms(10)%neg - lscal(ireg)%lum(ilum)%prm_prev%cn3_swf
 290 lscal(ireg)%lum(ilum)%prm%cn3_swf = ls_prms(10)%neg
 291 lscal(ireg)%lum(ilum)%prm_lim%cn3_swf = 1.
END IFLine 292
DO ihru_s = 1, region(ireg)%num_tot Lines 294-307
 295 iihru = region(ireg)%num(ihru_s)
IF (lscal(ireg)%lum(ilum)%meas%name == hru(iihru)%lum_group_c .or. lscal(ireg)%lum(ilum)%meas%name == "basin") THEN Lines 296-306
don't change for tile ***Mike (line 298)
don't change for tile ***Mike (line 298)
IF (hru(iihru)%tiledrain == 0) THEN Lines 299-305
 300 hru(iihru)%hyd%cn3_swf = hru(iihru)%hyd%cn3_swf + chg_val
 301 hru(iihru)%hyd%cn3_swf = amin1 (hru(iihru)%hyd%cn3_swf, ls_prms(10)%up)
 302 hru(iihru)%hyd%cn3_swf = Max (hru(iihru)%hyd%cn3_swf, ls_prms(10)%lo)
 303 hru_init(iihru)%hyd%cn3_swf = hru(iihru)%hyd%cn3_swf
 304 call curno (cn2(iihru), iihru)
END IFLine 305
END IFLine 306
END DOLine 307
END IFLine 315
END DOLine 316
END DOLine 317
IF (isim > 0) THEN Lines 323-327
 324 cal_sim =  " first cn3_swf adj "
 325 cal_adj = chg_val
 326 call time_control
END IFLine 327
DO icn = 1, 2 !iter_ind
re-initialize all objects (line 389)
re-initialize all objects (line 459)
re-initialize all objects (line 607)
 331 isim = 0
 390 call re_initialize
 400 end do      ! icn
 403 isim = 0
 460 call re_initialize
 536 isim = 0
 608 call re_initialize
DO ireg = 1, db_mx%lsu_reg Lines 332-387
DO ilum = 1, region(ireg)%nlum Lines 333-386
 334 soft = lscal(ireg)%lum(ilum)%meas%srr * lscal(ireg)%lum(ilum)%precip_aa
 335 diff = 0.
 336 if (soft > 1.e-6) diff = abs((soft - lscal(ireg)%lum(ilum)%aa%srr) / soft)
IF (diff > .02 .and. lscal(ireg)%lum(ilum)%ha > 1.e-6) then ! .and. lscal(ireg)%lum(ilum)%prm_lim%cn3_swf < 1.e-6) THEN Lines 337-385
 338 isim = 1
 340 rmeas = lscal(ireg)%lum(ilum)%meas%srr * lscal(ireg)%lum(ilum)%precip_aa
 341 denom = lscal(ireg)%lum(ilum)%prev%srr - lscal(ireg)%lum(ilum)%aa%srr
 348 lscal(ireg)%lum(ilum)%prm_prev%cn3_swf = lscal(ireg)%lum(ilum)%prm%cn3_swf
 349 lscal(ireg)%lum(ilum)%prm%cn3_swf = lscal(ireg)%lum(ilum)%prm%cn3_swf + chg_val
 350 lscal(ireg)%lum(ilum)%prev%srr = lscal(ireg)%lum(ilum)%aa%srr
 378 lscal(ireg)%lum(ilum)%nbyr = 0
 379 lscal(ireg)%lum(ilum)%precip_aa = 0.
 380 lscal(ireg)%lum(ilum)%aa = lscal_z
IF (abs(denom) > .0001) THEN Lines 342-344
 343 chg_val = - (lscal(ireg)%lum(ilum)%prm_prev%cn3_swf - lscal(ireg)%lum(ilum)%prm%cn3_swf)              &
 344 * (lscal(ireg)%lum(ilum)%aa%srr - rmeas) / denom
END IFLine 344
ELSE Lines 345-347
 346 chg_val = - diff / 10.
END IF Line 347
IF (lscal(ireg)%lum(ilum)%prm%cn3_swf >= ls_prms(10)%pos) THEN Lines 352-356
 353 chg_val = ls_prms(10)%pos - lscal(ireg)%lum(ilum)%prm_prev%cn3_swf
 354 lscal(ireg)%lum(ilum)%prm%cn3_swf = ls_prms(10)%pos
 355 lscal(ireg)%lum(ilum)%prm_lim%cn3_swf = 1.
END IFLine 356
IF (lscal(ireg)%lum(ilum)%prm%cn3_swf <= ls_prms(10)%neg) THEN Lines 357-361
 358 chg_val = ls_prms(10)%neg - lscal(ireg)%lum(ilum)%prm_prev%cn3_swf
 359 lscal(ireg)%lum(ilum)%prm%cn3_swf = ls_prms(10)%neg
 360 lscal(ireg)%lum(ilum)%prm_lim%cn3_swf = 1.
END IFLine 361
DO ihru_s = 1, region(ireg)%num_tot Lines 364-377
 365 iihru = region(ireg)%num(ihru_s)
IF (lscal(ireg)%lum(ilum)%meas%name == hru(iihru)%lum_group_c .or. lscal(ireg)%lum(ilum)%meas%name == "basin") THEN Lines 366-376
don't change for tile *********************Mike (line 368)
don't change for tile *********************Mike (line 368)
IF (hru(iihru)%tiledrain == 0) THEN Lines 369-375
 370 hru(iihru)%hyd%cn3_swf = hru(iihru)%hyd%cn3_swf + chg_val
 371 hru(iihru)%hyd%cn3_swf = amin1 (hru(iihru)%hyd%cn3_swf, ls_prms(10)%up)
 372 hru(iihru)%hyd%cn3_swf = Max (hru(iihru)%hyd%cn3_swf, ls_prms(10)%lo)
 373 hru_init(iihru)%hyd%cn3_swf = hru(iihru)%hyd%cn3_swf
 374 call curno (cn2(iihru), iihru)
END IFLine 375
END IFLine 376
END DOLine 377
END IFLine 385
END DOLine 386
END DOLine 387
IF (isim > 0) THEN Lines 393-399
 394 cal_sim =  " cn3_swf adj "
 395 cal_adj = chg_val
 398 call time_control
END IFLine 399
DO ireg = 1, db_mx%lsu_reg Lines 404-457
DO ilum = 1, region(ireg)%nlum Lines 405-456
 407 soft = lscal(ireg)%lum(ilum)%meas%lfr * lscal(ireg)%lum(ilum)%precip_aa
 408 diff = 0.
 409 if (soft > 1.e-6) diff = abs((soft - lscal(ireg)%lum(ilum)%aa%lfr) / soft)
IF (diff > .1 .and. lscal(ireg)%lum(ilum)%ha > 1.e-6 .and. lscal(ireg)%lum(ilum)%prm_lim%lat_len < 1.e-6) THEN Lines 410-455
 411 isim = 1
 413 lscal(ireg)%lum(ilum)%prm_prev = lscal(ireg)%lum(ilum)%prm
 414 lscal(ireg)%lum(ilum)%prev = lscal(ireg)%lum(ilum)%aa
 416 diff = lscal(ireg)%lum(ilum)%meas%lfr * lscal(ireg)%lum(ilum)%precip_aa - lscal(ireg)%lum(ilum)%aa%lfr
 417 chg_val =  0.0025 * diff        ! increment lst_len by 2 m for 1 mm difference
 423 lscal(ireg)%lum(ilum)%prm_prev%lat_len = lscal(ireg)%lum(ilum)%prm%lat_len
 424 lscal(ireg)%lum(ilum)%prm%lat_len = lscal(ireg)%lum(ilum)%prm%lat_len + chg_val
 425 lscal(ireg)%lum(ilum)%prev%lfr = lscal(ireg)%lum(ilum)%aa%lfr
 448 lscal(ireg)%lum(ilum)%nbyr = 0
 449 lscal(ireg)%lum(ilum)%precip_aa = 0.
 450 lscal(ireg)%lum(ilum)%aa = lscal_z
IF (lscal(ireg)%lum(ilum)%prm%lat_len >= ls_prms(3)%pos) THEN Lines 427-431
 428 lscal(ireg)%lum(ilum)%prm%lat_len = ls_prms(3)%pos
 429 chg_val = ls_prms(3)%pos
 430 lscal(ireg)%lum(ilum)%prm_lim%lat_len = 1.
END IFLine 431
IF (lscal(ireg)%lum(ilum)%prm%lat_len <= ls_prms(3)%neg) THEN Lines 432-436
 433 lscal(ireg)%lum(ilum)%prm%lat_len = ls_prms(3)%neg
 434 chg_val = ls_prms(3)%neg
 435 lscal(ireg)%lum(ilum)%prm_lim%lat_len = 1.
END IFLine 436
DO ihru_s = 1, region(ireg)%num_tot Lines 438-447
 439 iihru = region(ireg)%num(ihru_s)
IF (lscal(ireg)%lum(ilum)%meas%name == hru(iihru)%lum_group_c .or. lscal(ireg)%lum(ilum)%meas%name == "basin") THEN Lines 440-446
 442 hru(iihru)%hyd%latq_co = hru(iihru)%hyd%latq_co + chg_val
 443 hru(iihru)%hyd%latq_co = amin1 (hru(iihru)%hyd%latq_co, ls_prms(3)%up)
 444 hru(iihru)%hyd%latq_co = Max (hru(iihru)%hyd%latq_co, ls_prms(3)%lo)
 445 hru_init(iihru)%hyd%latq_co = hru(iihru)%hyd%latq_co
END IFLine 446
END DOLine 447
END IFLine 455
END DOLine 456
END DOLine 457
IF (isim > 0) THEN Lines 463-466
 464 cal_sim =  " first latq_co adj "
 465 call time_control
END IFLine 466
DO ik = 1, iter_ind Lines 469-533
re-initialize all objects (line 524)
 470 isim = 0
 525 call re_initialize
DO ireg = 1, db_mx%lsu_reg Lines 471-522
DO ilum = 1, region(ireg)%nlum Lines 472-521
 473 soft = lscal(ireg)%lum(ilum)%meas%lfr * lscal(ireg)%lum(ilum)%precip_aa
 474 diff = 0.
 475 if (soft > 1.e-6) diff = abs((soft - lscal(ireg)%lum(ilum)%aa%lfr) / soft)
IF (diff > .05 .and. lscal(ireg)%lum(ilum)%ha > 1.e-6 .and. lscal(ireg)%lum(ilum)%prm_lim%lat_len < 1.e-6) THEN Lines 476-520
 477 isim = 1
 479 rmeas = lscal(ireg)%lum(ilum)%meas%lfr * lscal(ireg)%lum(ilum)%precip_aa
 480 denom = lscal(ireg)%lum(ilum)%prev%lfr - lscal(ireg)%lum(ilum)%aa%lfr
 487 lscal(ireg)%lum(ilum)%prm_prev%lat_len = lscal(ireg)%lum(ilum)%prm%lat_len
 488 lscal(ireg)%lum(ilum)%prm%lat_len = lscal(ireg)%lum(ilum)%prm%lat_len + chg_val
 489 lscal(ireg)%lum(ilum)%prev%lfr = lscal(ireg)%lum(ilum)%aa%lfr
 513 lscal(ireg)%lum(ilum)%nbyr = 0
 514 lscal(ireg)%lum(ilum)%precip_aa = 0.
 515 lscal(ireg)%lum(ilum)%aa = lscal_z
IF (abs(denom) > 1.e-6) THEN Lines 481-483
 482 chg_val = - (lscal(ireg)%lum(ilum)%prm_prev%lat_len - lscal(ireg)%lum(ilum)%prm%lat_len)                  &
 483 * (lscal(ireg)%lum(ilum)%aa%lfr - rmeas) / denom
END IFLine 483
ELSE Lines 484-486
 485 chg_val = - diff    ! 1 m for each mm
END IF Line 486
IF (lscal(ireg)%lum(ilum)%prm%lat_len >= ls_prms(3)%pos) THEN Lines 491-495
 492 lscal(ireg)%lum(ilum)%prm%lat_len = ls_prms(3)%pos
 493 chg_val = ls_prms(3)%pos
 494 lscal(ireg)%lum(ilum)%prm_lim%lat_len = 1.
END IFLine 495
IF (lscal(ireg)%lum(ilum)%prm%lat_len <= ls_prms(3)%neg) THEN Lines 496-500
 497 lscal(ireg)%lum(ilum)%prm%lat_len = ls_prms(3)%neg
 498 chg_val = ls_prms(3)%neg
 499 lscal(ireg)%lum(ilum)%prm_lim%lat_len = 1.
END IFLine 500
DO ihru_s = 1, region(ireg)%num_tot Lines 503-512
 504 iihru = region(ireg)%num(ihru_s)
IF (lscal(ireg)%lum(ilum)%meas%name == hru(iihru)%lum_group_c .or. lscal(ireg)%lum(ilum)%meas%name == "basin") THEN Lines 505-511
 507 hru(iihru)%hyd%latq_co = hru(iihru)%hyd%latq_co + chg_val
 508 hru(iihru)%hyd%latq_co = amin1 (hru(iihru)%hyd%latq_co, ls_prms(3)%up)
 509 hru(iihru)%hyd%latq_co = Max (hru(iihru)%hyd%latq_co, ls_prms(3)%lo)
 510 hru_init(iihru)%hyd%latq_co = hru(iihru)%hyd%latq_co
END IFLine 511
END DOLine 512
END IFLine 520
END DOLine 521
END DOLine 522
IF (isim > 0) THEN Lines 528-532
 529 cal_sim =  " latq_co adj "
 530 cal_adj = chg_val
 531 call time_control
END IFLine 532
END DOLine 533
DO ireg = 1, db_mx%lsu_reg Lines 537-595
DO ilum = 1, region(ireg)%nlum Lines 538-594
 540 soft = lscal(ireg)%lum(ilum)%meas%pcr * lscal(ireg)%lum(ilum)%precip_aa
 541 diff = 0.
 542 if (soft > 1.e-6) diff = abs((soft - lscal(ireg)%lum(ilum)%aa%pcr) / soft)
IF (diff > .05 .and. lscal(ireg)%lum(ilum)%ha > 1.e-6 .and. lscal(ireg)%lum(ilum)%prm_lim%perco < 1.e-6) THEN Lines 543-590
 544 isim = 1
 547 lscal(ireg)%lum(ilum)%prm_prev = lscal(ireg)%lum(ilum)%prm
 548 lscal(ireg)%lum(ilum)%prev = lscal(ireg)%lum(ilum)%aa
 551 chg_val = 0.001 * (soft - lscal(ireg)%lum(ilum)%aa%pcr)
 552 lscal(ireg)%lum(ilum)%prm_prev%perco = lscal(ireg)%lum(ilum)%prm%perco
 553 lscal(ireg)%lum(ilum)%prm%perco = lscal(ireg)%lum(ilum)%prm%perco + chg_val
 554 lscal(ireg)%lum(ilum)%prev%pcr = lscal(ireg)%lum(ilum)%aa%pcr
 588 lscal(ireg)%lum(ilum)%nbyr = 0
 589 lscal(ireg)%lum(ilum)%precip_aa = 0.
 590 lscal(ireg)%lum(ilum)%aa = lscal_z
IF (lscal(ireg)%lum(ilum)%prm%perco >= ls_prms(8)%pos) THEN Lines 556-560
 557 lscal(ireg)%lum(ilum)%prm%perco = ls_prms(8)%pos
 558 chg_val = ls_prms(8)%pos
 559 lscal(ireg)%lum(ilum)%prm_lim%perco = 1.
END IFLine 560
IF (lscal(ireg)%lum(ilum)%prm%perco <= ls_prms(8)%neg) THEN Lines 561-565
 562 lscal(ireg)%lum(ilum)%prm%perco = ls_prms(8)%neg
 563 chg_val = ls_prms(8)%neg
 564 lscal(ireg)%lum(ilum)%prm_lim%perco = 1.
END IFLine 565
DO ihru_s = 1, region(ireg)%num_tot Lines 567-586
 568 iihru = region(ireg)%num(ihru_s)
IF (lscal(ireg)%lum(ilum)%meas%name == hru(iihru)%lum_group_c .or. lscal(ireg)%lum(ilum)%meas%name == "basin") THEN Lines 569-585
don't change for tile *********************Mike (line 570)
don't change for tile *********************Mike (line 570)
IF (hru(iihru)%tiledrain == 0) THEN Lines 571-584
 572 hru(iihru)%hyd%perco = hru(iihru)%hyd%perco + chg_val
 573 hru(iihru)%hyd%perco = amin1 (hru(iihru)%hyd%perco, ls_prms(8)%up)
 574 hru(iihru)%hyd%perco = Max (hru(iihru)%hyd%perco, ls_prms(8)%lo)
 575 hru_init(iihru)%hyd%perco = hru(iihru)%hyd%perco
 583 hru_init(iihru)%hyd%perco_lim = hru(iihru)%hyd%perco_lim
IF (hru(iihru)%hyd%perco > 1.e-9) THEN Lines 576-579
 577 perc_ln_func = 1.0052 * log(-log(hru(iihru)%hyd%perco - 1.e-6)) + 5.6862
 578 hru(iihru)%hyd%perco_lim = exp(-perc_ln_func)
 579 hru(iihru)%hyd%perco_lim = amin1 (1., hru(iihru)%hyd%perco_lim)
END IFLine 579
ELSE Lines 580-582
 581 hru(iihru)%hyd%perco_lim = 0.
END IF Line 582
END IFLine 584
END IFLine 585
END DOLine 586
END IFLine 590
ELSE Lines 591-593
 592 lscal(ireg)%lum(ilum)%prm_lim%perco = 1.
END IF Line 593
END DOLine 594
END DOLine 595
IF (isim > 0) THEN Lines 611-615
 612 cal_sim =  " first perco adj "
 613 cal_adj = chg_val
 614 call time_control
END IFLine 615
DO iperco = 1, 3 !iter_ind
re-initialize all objects (line 692)
re-initialize all objects (line 760)
 619 isim = 0
 693 call re_initialize
 702 end do      ! iperco
 705 isim = 0
 761 call re_initialize
DO ireg = 1, db_mx%lsu_reg Lines 620-680
DO ilum = 1, region(ireg)%nlum Lines 621-679
 622 soft = lscal(ireg)%lum(ilum)%meas%pcr * lscal(ireg)%lum(ilum)%precip_aa
 623 diff = 0.
 624 if (soft > 1.e-6) diff = abs((soft - lscal(ireg)%lum(ilum)%aa%pcr) / soft)
IF (diff > .05 .and. lscal(ireg)%lum(ilum)%ha > 1.e-6) THEN Lines 625-675
 626 isim = 1
 628 rmeas = lscal(ireg)%lum(ilum)%meas%pcr * lscal(ireg)%lum(ilum)%precip_aa
 629 denom = lscal(ireg)%lum(ilum)%prev%pcr - lscal(ireg)%lum(ilum)%aa%pcr
 636 lscal(ireg)%lum(ilum)%prm_prev%perco = lscal(ireg)%lum(ilum)%prm%perco
 637 lscal(ireg)%lum(ilum)%prm%perco = lscal(ireg)%lum(ilum)%prm%perco + chg_val
 638 lscal(ireg)%lum(ilum)%prev%pcr = lscal(ireg)%lum(ilum)%aa%pcr
 673 lscal(ireg)%lum(ilum)%nbyr = 0
 674 lscal(ireg)%lum(ilum)%precip_aa = 0.
 675 lscal(ireg)%lum(ilum)%aa = lscal_z
IF (abs(denom) > 2.) THEN Lines 630-632
 631 chg_val = - (lscal(ireg)%lum(ilum)%prm_prev%perco - lscal(ireg)%lum(ilum)%prm%perco)                  &
 632 * (lscal(ireg)%lum(ilum)%aa%pcr - rmeas) / denom
END IFLine 632
ELSE Lines 633-635
 634 chg_val = 0.
END IF Line 635
IF (lscal(ireg)%lum(ilum)%prm%perco >= ls_prms(8)%pos) THEN Lines 640-644
 641 lscal(ireg)%lum(ilum)%prm%perco = ls_prms(8)%pos
 642 chg_val = ls_prms(8)%pos
 643 lscal(ireg)%lum(ilum)%prm_lim%perco = 1.
END IFLine 644
IF (lscal(ireg)%lum(ilum)%prm%perco <= ls_prms(8)%neg) THEN Lines 645-649
 646 lscal(ireg)%lum(ilum)%prm%perco = ls_prms(8)%neg
 647 chg_val = ls_prms(8)%neg
 648 lscal(ireg)%lum(ilum)%prm_lim%perco = 1.
END IFLine 649
DO ihru_s = 1, region(ireg)%num_tot Lines 651-671
 652 iihru = region(ireg)%num(ihru_s)
IF (lscal(ireg)%lum(ilum)%meas%name == hru(iihru)%lum_group_c .or. lscal(ireg)%lum(ilum)%meas%name == "basin") THEN Lines 653-670
don't change for tile *********************Mike (line 655)
don't change for tile *********************Mike (line 655)
IF (hru(iihru)%tiledrain == 0) THEN Lines 656-669
 657 hru(iihru)%hyd%perco = hru(iihru)%hyd%perco + chg_val
 658 hru(iihru)%hyd%perco = amin1 (hru(iihru)%hyd%perco, ls_prms(8)%up)
 659 hru(iihru)%hyd%perco = Max (hru(iihru)%hyd%perco, ls_prms(8)%lo)
 660 hru_init(iihru)%hyd%perco = hru(iihru)%hyd%perco
 668 hru_init(iihru)%hyd%perco_lim = hru(iihru)%hyd%perco_lim
IF (hru(iihru)%hyd%perco > 1.e-9) THEN Lines 661-664
 662 perc_ln_func = 1.0052 * log(-log(hru(iihru)%hyd%perco - 1.e-6)) + 5.6862
 663 hru(iihru)%hyd%perco_lim = exp(-perc_ln_func)
 664 hru(iihru)%hyd%perco_lim = amin1 (1., hru(iihru)%hyd%perco_lim)
END IFLine 664
ELSE Lines 665-667
 666 hru(iihru)%hyd%perco_lim = 0.
END IF Line 667
END IFLine 669
END IFLine 670
END DOLine 671
END IFLine 675
ELSE Lines 676-678
 677 lscal(ireg)%lum(ilum)%prm_lim%perco = 1.
END IF Line 678
END DOLine 679
END DOLine 680
IF (isim > 0) THEN Lines 696-700
 697 cal_sim =  " perco adj "
 698 cal_adj = chg_val
 699 call time_control
END IFLine 700
DO ireg = 1, db_mx%lsu_reg Lines 706-758
DO ilum = 1, region(ireg)%nlum Lines 707-757
 708 soft = lscal(ireg)%lum(ilum)%meas%srr * lscal(ireg)%lum(ilum)%precip_aa
 709 diff = 0.
 710 if (soft > 1.e-6) diff = abs((soft - lscal(ireg)%lum(ilum)%aa%srr) / soft)
IF (diff > .02 .and. lscal(ireg)%lum(ilum)%ha > 1.e-6 .and. lscal(ireg)%lum(ilum)%prm_lim%cn3_swf < 1.e-6) THEN Lines 711-756
 712 isim = 1
 714 lscal(ireg)%lum(ilum)%prm_prev = lscal(ireg)%lum(ilum)%prm
 715 lscal(ireg)%lum(ilum)%prev = lscal(ireg)%lum(ilum)%aa
 717 diff = lscal(ireg)%lum(ilum)%meas%srr * lscal(ireg)%lum(ilum)%precip_aa - lscal(ireg)%lum(ilum)%aa%srr
 718 chg_val = - diff / 100.     !assume 10 mm runoff for .1 cn3_swf
 720 lscal(ireg)%lum(ilum)%prm_prev%cn3_swf = lscal(ireg)%lum(ilum)%prm%cn3_swf
 721 lscal(ireg)%lum(ilum)%prm%cn3_swf = lscal(ireg)%lum(ilum)%prm%cn3_swf + chg_val
 722 lscal(ireg)%lum(ilum)%prev%srr = lscal(ireg)%lum(ilum)%aa%srr
 749 lscal(ireg)%lum(ilum)%nbyr = 0
 750 lscal(ireg)%lum(ilum)%precip_aa = 0.
 751 lscal(ireg)%lum(ilum)%aa = lscal_z
IF (lscal(ireg)%lum(ilum)%prm%cn3_swf >= ls_prms(10)%pos) THEN Lines 724-728
 725 chg_val = ls_prms(10)%pos - lscal(ireg)%lum(ilum)%prm_prev%cn3_swf
 726 lscal(ireg)%lum(ilum)%prm%cn3_swf = ls_prms(10)%pos
 727 lscal(ireg)%lum(ilum)%prm_lim%cn3_swf = 1.
END IFLine 728
IF (lscal(ireg)%lum(ilum)%prm%cn3_swf <= ls_prms(10)%neg) THEN Lines 729-733
 730 chg_val = ls_prms(10)%neg - lscal(ireg)%lum(ilum)%prm_prev%cn3_swf
 731 lscal(ireg)%lum(ilum)%prm%cn3_swf = ls_prms(10)%neg
 732 lscal(ireg)%lum(ilum)%prm_lim%cn3_swf = 1.
END IFLine 733
DO ihru_s = 1, region(ireg)%num_tot Lines 735-748
 736 iihru = region(ireg)%num(ihru_s)
IF (lscal(ireg)%lum(ilum)%meas%name == hru(iihru)%lum_group_c .or. lscal(ireg)%lum(ilum)%meas%name == "basin") THEN Lines 737-747
don't change for tile ***Mike (line 739)
don't change for tile ***Mike (line 739)
IF (hru(iihru)%tiledrain == 0) THEN Lines 740-746
 741 hru(iihru)%hyd%cn3_swf = hru(iihru)%hyd%cn3_swf + chg_val
 742 hru(iihru)%hyd%cn3_swf = amin1 (hru(iihru)%hyd%cn3_swf, ls_prms(10)%up)
 743 hru(iihru)%hyd%cn3_swf = Max (hru(iihru)%hyd%cn3_swf, ls_prms(10)%lo)
 744 hru_init(iihru)%hyd%cn3_swf = hru(iihru)%hyd%cn3_swf
 745 call curno (cn2(iihru), iihru)
END IFLine 746
END IFLine 747
END DOLine 748
END IFLine 756
END DOLine 757
END DOLine 758
IF (isim > 0) THEN Lines 764-768
 765 cal_sim =  " first cn3_swf adj "
 766 cal_adj = chg_val
 767 call time_control
END IFLine 768
DO icn = 1, 2 !iter_ind
re-initialize all objects (line 830)
 772 isim = 0
 831 call re_initialize
 841 end do      ! icn
 843 end do    ! iter_all loop
 847 return
DO ireg = 1, db_mx%lsu_reg Lines 773-828
DO ilum = 1, region(ireg)%nlum Lines 774-827
 775 soft = lscal(ireg)%lum(ilum)%meas%srr * lscal(ireg)%lum(ilum)%precip_aa
 776 diff = 0.
 777 if (soft > 1.e-6) diff = abs((soft - lscal(ireg)%lum(ilum)%aa%srr) / soft)
IF (diff > .02 .and. lscal(ireg)%lum(ilum)%ha > 1.e-6) then ! .and. lscal(ireg)%lum(ilum)%prm_lim%cn3_swf < 1.e-6) THEN Lines 778-826
 779 isim = 1
 781 rmeas = lscal(ireg)%lum(ilum)%meas%srr * lscal(ireg)%lum(ilum)%precip_aa
 782 denom = lscal(ireg)%lum(ilum)%prev%srr - lscal(ireg)%lum(ilum)%aa%srr
 789 lscal(ireg)%lum(ilum)%prm_prev%cn3_swf = lscal(ireg)%lum(ilum)%prm%cn3_swf
 790 lscal(ireg)%lum(ilum)%prm%cn3_swf = lscal(ireg)%lum(ilum)%prm%cn3_swf + chg_val
 791 lscal(ireg)%lum(ilum)%prev%srr = lscal(ireg)%lum(ilum)%aa%srr
 819 lscal(ireg)%lum(ilum)%nbyr = 0
 820 lscal(ireg)%lum(ilum)%precip_aa = 0.
 821 lscal(ireg)%lum(ilum)%aa = lscal_z
IF (abs(denom) > .0001) THEN Lines 783-785
 784 chg_val = - (lscal(ireg)%lum(ilum)%prm_prev%cn3_swf - lscal(ireg)%lum(ilum)%prm%cn3_swf)                  &
 785 * (lscal(ireg)%lum(ilum)%aa%srr - rmeas) / denom
END IFLine 785
ELSE Lines 786-788
 787 chg_val = - diff / 10.
END IF Line 788
IF (lscal(ireg)%lum(ilum)%prm%cn3_swf >= ls_prms(10)%pos) THEN Lines 793-797
 794 chg_val = ls_prms(10)%pos - lscal(ireg)%lum(ilum)%prm_prev%cn3_swf
 795 lscal(ireg)%lum(ilum)%prm%cn3_swf = ls_prms(10)%pos
 796 lscal(ireg)%lum(ilum)%prm_lim%cn3_swf = 1.
END IFLine 797
IF (lscal(ireg)%lum(ilum)%prm%cn3_swf <= ls_prms(10)%neg) THEN Lines 798-802
 799 chg_val = ls_prms(10)%neg - lscal(ireg)%lum(ilum)%prm_prev%cn3_swf
 800 lscal(ireg)%lum(ilum)%prm%cn3_swf = ls_prms(10)%neg
 801 lscal(ireg)%lum(ilum)%prm_lim%cn3_swf = 1.
END IFLine 802
DO ihru_s = 1, region(ireg)%num_tot Lines 805-818
 806 iihru = region(ireg)%num(ihru_s)
IF (lscal(ireg)%lum(ilum)%meas%name == hru(iihru)%lum_group_c .or. lscal(ireg)%lum(ilum)%meas%name == "basin") THEN Lines 807-817
don't change for tile *********************Mike (line 809)
don't change for tile *********************Mike (line 809)
IF (hru(iihru)%tiledrain == 0) THEN Lines 810-816
 811 hru(iihru)%hyd%cn3_swf = hru(iihru)%hyd%cn3_swf + chg_val
 812 hru(iihru)%hyd%cn3_swf = amin1 (hru(iihru)%hyd%cn3_swf, ls_prms(10)%up)
 813 hru(iihru)%hyd%cn3_swf = Max (hru(iihru)%hyd%cn3_swf, ls_prms(10)%lo)
 814 hru_init(iihru)%hyd%cn3_swf = hru(iihru)%hyd%cn3_swf
 815 call curno (cn2(iihru), iihru)
END IFLine 816
END IFLine 817
END DOLine 818
END IFLine 826
END DOLine 827
END DOLine 828
IF (isim > 0) THEN Lines 834-840
 835 cal_sim =  " cn3_swf adj "
 836 cal_adj = chg_val
 839 call time_control
END IFLine 840
END DO
END DO
END DO
END DO
END DO
END DO
Allocations
n/a
Calls
Procedures Called
List of procedures called by this Subroutine.
amin1
re_initialize
time_control
curno
Call Graph
Visual representation of procedures called by this Subroutine.
Call graph
calsoft_hyd calls amin1, curno, re_initialize, time_control