calsoft_control – TestDataProject
calsoft_control Subroutine
104 statements
Source File
subroutine calsoft_control()
Called From
n/a
Arguments
n/a
Outside Variables and Types
type (11 attributes from basin_module)
Attribute Name Description
pco%wb_bsn%a None
pco%nyskip None
cal_codes%sed None
cal_codes%chsed None
cal_codes%hyd_hru None
cal_codes%hyd_hrul None
cal_codes%plt None
sp_ob%hru None
sp_ob%hru_lte None
db_mx%lsu_reg None
db_mx%ch_reg None
type(basin_print_codes) (1 attribute from basin_module)
Attribute Name Description
pco_init
type(soft_calib_parms) (1 attribute from calibration_data_module)
Attribute Name Description
ch_prms
type(soft_data_calib_landscape) (2 attributes from calibration_data_module)
Attribute Name Description
lscal
dimension by region for hru"s
lscalt
dimension by region for hru_lte"s
type(cataloging_units) (1 attribute from calibration_data_module)
Attribute Name Description
region
dimension by region for hru"s
type(soft_data_calib_channel) (1 attribute from calibration_data_module)
Attribute Name Description
chcal
dimension by region
type(hydrologic_response_unit) (1 attribute from hru_module)
Attribute Name Description
hru
integer (1 attribute from hru_module)
Attribute Name Description
ihru
none |HRU number
Read more…
real (1 attribute from hru_module)
Attribute Name Description
cn2
type(hydrology) (1 attribute from hru_module)
Attribute Name Description
hydrology None
type(swatdeg_hru_data) (1 attribute from hru_lte_module)
Attribute Name Description
hlt_db
type(swatdeg_hru_dynamic) (1 attribute from hru_lte_module)
Attribute Name Description
hlt
Uses
basin_module
sd_channel_module
time_module
calibration_data_module
hydrograph_module
soil_module
maximum_data_module
hru_module
hru_lte_module
I/O
I/O units used in this subroutine.
Unit Type Filename
unit_4999 Output not specified
unit_5001 Output not specified
unit_5000 Output not specified
Local Variables
Type Visibility Attributes Name Initial
integer, public :: ireg = 0
integer, public :: ilum = 0
integer, public :: icvmax = 0
integer, public :: nyskip = 0
integer, public :: ihru = 0
integer, public :: isdh = 0
integer, public :: idb = 0
integer, public :: iord = 0
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure. Use mouse wheel to zoom, drag to pan.
Reset Zoom Help
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
  24 icvmax = 0
  25 nyskip = pco%nyskip
  26 pco = pco_init
  27 pco%wb_bsn%a = "y"
  28 pco%nyskip = nyskip
IF (cal_codes%hyd_hru /= "n") THEN Lines 36-58
IF (cal_codes%hyd_hru == "a") THEN Lines 37-38
  38 call calsoft_hyd        !calibrate all components
END IFLine 38
ELSE Lines 39-41
  40 call calsoft_hyd_bfr    !calibrate total and baseflow
END IF Line 41
DO ireg = 1, db_mx%lsu_reg Lines 44-56
DO ilum = 1, region(ireg)%nlum Lines 45-55
  46 lscal(ireg)%lum(ilum)%meas%srr = lscal(ireg)%lum(ilum)%precip_aa_sav * lscal(ireg)%lum(ilum)%meas%srr
  47 lscal(ireg)%lum(ilum)%meas%lfr = lscal(ireg)%lum(ilum)%precip_aa_sav * lscal(ireg)%lum(ilum)%meas%lfr
  48 lscal(ireg)%lum(ilum)%meas%pcr = lscal(ireg)%lum(ilum)%precip_aa_sav * lscal(ireg)%lum(ilum)%meas%pcr
  49 lscal(ireg)%lum(ilum)%meas%etr = lscal(ireg)%lum(ilum)%precip_aa_sav * lscal(ireg)%lum(ilum)%meas%etr
  50 lscal(ireg)%lum(ilum)%meas%tfr = lscal(ireg)%lum(ilum)%precip_aa_sav * lscal(ireg)%lum(ilum)%meas%tfr
END DOLine 55
END DOLine 56
END IFLine 58
IF (cal_codes%hyd_hrul == "y") THEN Lines 61-89
  62 call caltsoft_hyd
DO ireg = 1, db_mx%lsu_reg Lines 64-76
DO ilum = 1, lscalt(ireg)%lum_num Lines 65-75
  66 lscalt(ireg)%lum(ilum)%meas%srr = lscalt(ireg)%lum(ilum)%precip_aa_sav * lscalt(ireg)%lum(ilum)%meas%srr
  67 lscalt(ireg)%lum(ilum)%meas%lfr = lscalt(ireg)%lum(ilum)%precip_aa_sav * lscalt(ireg)%lum(ilum)%meas%lfr
  68 lscalt(ireg)%lum(ilum)%meas%pcr = lscalt(ireg)%lum(ilum)%precip_aa_sav * lscalt(ireg)%lum(ilum)%meas%pcr
  69 lscalt(ireg)%lum(ilum)%meas%etr = lscalt(ireg)%lum(ilum)%precip_aa_sav * lscalt(ireg)%lum(ilum)%meas%etr
  70 lscalt(ireg)%lum(ilum)%meas%tfr = lscalt(ireg)%lum(ilum)%precip_aa_sav * lscalt(ireg)%lum(ilum)%meas%tfr
END DOLine 75
END DOLine 76
DO isdh = 1, sp_ob%hru_lte Lines 78-88
  79 idb = hlt(isdh)%props
  80 write (4999,*) hlt(isdh)%name, hlt_db(idb)%dakm2, hlt(isdh)%cn2, hlt(isdh)%cn3_swf, hlt_db(idb)%tc,       &
  81 hlt_db(idb)%soildep, hlt(isdh)%perco, hlt_db(isdh)%slope, hlt_db(idb)%slopelen,                         &
  82 hlt(isdh)%etco, hlt_db(idb)%sy, hlt_db(idb)%abf, hlt(idb)%revapc,                                       &
  83 hlt_db(idb)%percc, hlt_db(idb)%sw, hlt_db(idb)%gw, hlt_db(idb)%gwflow,                                  &
  84 hlt_db(idb)%gwdeep, hlt_db(idb)%snow, hlt_db(idb)%xlat, hlt_db(idb)%text,                               &
  85 hlt_db(idb)%tropical, hlt_db(idb)%igrow1, hlt_db(idb)%igrow2, hlt_db(idb)%plant, hlt(isdh)%stress,      &
  86 hlt_db(idb)%ipet, hlt_db(idb)%irr, hlt_db(idb)%irrsrc, hlt_db(idb)%tdrain,                              &
  87 hlt_db(idb)%uslek, hlt_db(idb)%uslec, hlt_db(idb)%uslep, hlt_db(idb)%uslels
END DOLine 88
END IFLine 89
IF (cal_codes%plt == "y") THEN Lines 92-94
  93 call calsoft_plant
END IFLine 94
IF (cal_codes%sed == "y") THEN Lines 97-99
  98 call calsoft_sed
END IFLine 99
IF (cal_codes%chsed == "y") THEN Lines 106-113
DO ireg = 1, db_mx%ch_reg Lines 107-112
DO iord = 1, chcal(ireg)%ord_num Lines 108-111
channel sediment parms (line 109)
 110 if (chcal(ireg)%ord(iord)%aa%chw > 1.e-6) icvmax = icvmax + 1
END DOLine 111
END DOLine 112
END IFLine 113
IF (cal_codes%hyd_hru /= "n") THEN Lines 116-124
 117 write (5001,*) " hydrology-cal.hyd developed from soft data calibration"
 120 write (5001,5010)
DO ihru = 1, sp_ob%hru Lines 121-123
 122 write (5001,*) hru(ihru)%hyd
END DOLine 123
END IFLine 124
IF (cal_codes%plt == "y") THEN
write perco to hydrology-cal.hyd (line 130)
channel sediment parms (line 152)
channel sediment parms (line 152)
 128 call pl_write_parms_cal
 131 write (5001,*) " hydrology-cal.hyd developed from soft data calibration"
 134 write (5001,5010)
 135 5010    format (1x,'NAME',38x,'LAT_TTIME',12x,'LAT_SED',8x,'CAN_MAX',11x,'ESCO',7x,'EPCO',8x,        &
 136 'ORGN_ENRICH',4x,'ORGP_ENRICH',4x,'CN3_SWF',8x,'BIO_MIX',10x,'PERCO',11x,'LAT_ORGN',7x,      &
 137 'LAT_ORGP',5x,'PET_CO',8x,'LATQ_CO',7x,'NOT_USED')
 141 end if      ! plant parms
DO ihru = 1, sp_ob%hru Lines 138-140
 139 write (5001,*) hru(ihru)%hyd
END DOLine 140
IF (cal_codes%chsed == "y") THEN Lines 143-150
DO ireg = 1, db_mx%ch_reg Lines 144-149
DO iord = 1, chcal(ireg)%ord_num Lines 145-148
channel sediment parms (line 146)
 147 if (chcal(ireg)%ord(iord)%aa%chw > 1.e-6) icvmax = icvmax + 1
END DOLine 148
END DOLine 149
END IFLine 150
IF (cal_codes%chsed == "y") THEN
 162 end if      ! channel sediment parms
 165 503 format (2a16,f12.5,a)
 167 return
DO ireg = 1, db_mx%ch_reg Lines 154-161
DO iord = 1, chcal(ireg)%ord_num Lines 155-160
IF (abs(chcal(ireg)%ord(iord)%aa%chw) > 1.e-6) THEN Lines 156-159
 157 write (5000,503) ch_prms(1)%name, ch_prms(1)%chg_typ, chcal(ireg)%ord(iord)%prm%erod,          &
 158 "     0      0      0      0      0      0      0      0      0"
END IFLine 159
END DOLine 160
END DOLine 161
END IF
END IF
Allocations
n/a
Calls
Procedures Called
List of procedures called by this Subroutine.
calsoft_hyd
calsoft_hyd_bfr
caltsoft_hyd
calsoft_plant
calsoft_sed
pl_write_parms_cal
Call Graph
Visual representation of procedures called by this Subroutine.
Call graph
calsoft_control calls calsoft_hyd, calsoft_hyd_bfr, calsoft_plant, calsoft_sed, caltsoft_hyd, pl_write_parms_cal