calsoft_hyd_bfr_et – TestDataProject
calsoft_hyd_bfr_et Subroutine
135 statements
Source File
subroutine calsoft_hyd_bfr_et()
Called From
n/a
Arguments
n/a
Outside Variables and Types
type(soft_calib_parms) (1 attribute from calibration_data_module)
Attribute Name Description
ls_prms
type(soft_calib_ls_processes) (1 attribute from calibration_data_module)
Attribute Name Description
lscal_z
to zero values
type(soft_data_calib_landscape) (1 attribute from calibration_data_module)
Attribute Name Description
lscal
dimension by region for hru"s
type(cataloging_units) (1 attribute from calibration_data_module)
Attribute Name Description
region
dimension by region for hru"s
character(len=29) (1 attribute from time_module)
Attribute Name Description
cal_sim
real (1 attribute from time_module)
Attribute Name Description
cal_adj
type (1 attribute from maximum_data_module)
Attribute Name Description
db_mx%lsu_reg None
type(hydrologic_response_unit) (2 attributes from hru_module)
Attribute Name Description
hru
hru_init
Uses
basin_module
sd_channel_module
conditional_module
soil_module
calibration_data_module
hydrograph_module
time_module
maximum_data_module
aquifer_module
reservoir_module
hru_module
channel_module
organic_mineral_mass_module
plant_module
hru_lte_module
ru_module
I/O
n/a
Local Variables
Type Visibility Attributes Name Initial
integer, public :: isim = 0
integer, public :: ireg = 0
integer, public :: ilum = 0
integer, public :: iihru = 0
integer, public :: ihru_s = 0
integer, public :: iter_ind = 0
integer, public :: ietco = 0
real, public :: rmeas = 0.
real, public :: denom = 0.
real, public :: soft = 0.
real, public :: diff = 0.
real, public :: chg_val = 0.
real, public :: pred = 0.
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure. Use mouse wheel to zoom, drag to pan.
Reset Zoom Help
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
  37 iter_ind = 1
  50 isim = 0
DO ireg = 1, db_mx%lsu_reg Lines 51-105
DO ilum = 1, region(ireg)%nlum Lines 52-104
  53 soft = (lscal(ireg)%lum(ilum)%meas%wyr + lscal(ireg)%lum(ilum)%meas%pcr) * lscal(ireg)%lum(ilum)%precip_aa
  54 pred = lscal(ireg)%lum(ilum)%aa%wyr
  55 diff = 0.
  56 if (soft > 1.e-6) diff = abs((soft - pred) / soft)
IF (diff > .01 .and. lscal(ireg)%lum(ilum)%ha > 1.e-6 .and. lscal(ireg)%lum(ilum)%prm_lim%etco < 1.e-6) THEN Lines 57-103
  58 isim = 1
  60 lscal(ireg)%lum(ilum)%prm_prev = lscal(ireg)%lum(ilum)%prm
  61 lscal(ireg)%lum(ilum)%prev = lscal(ireg)%lum(ilum)%aa
  63 diff = soft - pred
  64 chg_val = - diff / 250.     ! increment etco .4 for every 100 mm difference
  65 lscal(ireg)%lum(ilum)%prm_prev%etco = lscal(ireg)%lum(ilum)%prm%etco
  66 lscal(ireg)%lum(ilum)%prm%etco = lscal(ireg)%lum(ilum)%prm%etco + chg_val
  67 lscal(ireg)%lum(ilum)%prev%wyr = lscal(ireg)%lum(ilum)%aa%wyr
  94 lscal(ireg)%lum(ilum)%nbyr = 0
  95 lscal(ireg)%lum(ilum)%precip_aa = 0.
  96 lscal(ireg)%lum(ilum)%aa = lscal_z
IF (lscal(ireg)%lum(ilum)%prm%etco >= ls_prms(2)%pos) THEN Lines 69-73
  70 chg_val = ls_prms(2)%pos - lscal(ireg)%lum(ilum)%prm_prev%etco
  71 lscal(ireg)%lum(ilum)%prm%etco = ls_prms(2)%pos
  72 lscal(ireg)%lum(ilum)%prm_lim%etco = 1.
END IFLine 73
IF (lscal(ireg)%lum(ilum)%prm%etco <= ls_prms(2)%neg) THEN Lines 74-78
  75 chg_val = lscal(ireg)%lum(ilum)%prm_prev%etco + ls_prms(2)%neg
  76 lscal(ireg)%lum(ilum)%prm%etco = ls_prms(2)%neg
  77 lscal(ireg)%lum(ilum)%prm_lim%etco = 1.
END IFLine 78
DO ihru_s = 1, region(ireg)%num_tot Lines 80-93
  81 iihru = region(ireg)%num(ihru_s)
IF (lscal(ireg)%lum(ilum)%meas%name == hru(iihru)%lum_group_c .or. lscal(ireg)%lum(ilum)%meas%name == "basin") THEN Lines 82-92
  84 hru(iihru)%hyd%esco = hru(iihru)%hyd%esco + chg_val
  85 hru(iihru)%hyd%esco = amin1 (hru(iihru)%hyd%esco, ls_prms(2)%up)
  86 hru(iihru)%hyd%esco = Max (hru(iihru)%hyd%esco, ls_prms(2)%lo)
  87 hru_init(iihru)%hyd%esco = hru(iihru)%hyd%esco
END IFLine 92
END DOLine 93
END IFLine 103
END DOLine 104
END DOLine 105
re-initialize all objects (line 107)
 108 call re_initialize
IF (isim > 0) THEN Lines 111-115
 112 cal_sim =  " first esco adj "
 113 cal_adj = chg_val
 114 call time_control
END IFLine 115
DO ietco = 1, 2 !iter_ind
re-initialize all objects (line 181)
re-initialize all objects (line 184)
 119 isim = 0
 182 call re_initialize
 185 call re_initialize
 194 end do      ! iesco
 196 return
DO ireg = 1, db_mx%lsu_reg Lines 120-179
DO ilum = 1, region(ireg)%nlum Lines 121-178
 122 soft = (lscal(ireg)%lum(ilum)%meas%wyr + lscal(ireg)%lum(ilum)%meas%pcr) * lscal(ireg)%lum(ilum)%precip_aa
 123 pred = lscal(ireg)%lum(ilum)%aa%wyr
 124 diff = 0.
 125 if (soft > 1.e-6) diff = abs((soft - pred) / soft)
IF (diff > .01 .and. lscal(ireg)%lum(ilum)%ha > 1.e-6 .and. lscal(ireg)%lum(ilum)%prm_lim%etco < 1.e-6) THEN Lines 126-177
 127 isim = 1
 129 rmeas = soft
 130 denom = lscal(ireg)%lum(ilum)%prev%wyr - lscal(ireg)%lum(ilum)%aa%wyr
 141 lscal(ireg)%lum(ilum)%prm_prev%etco = lscal(ireg)%lum(ilum)%prm%etco
 142 lscal(ireg)%lum(ilum)%prm%etco = lscal(ireg)%lum(ilum)%prm%etco + chg_val
 143 lscal(ireg)%lum(ilum)%prev%wyr = lscal(ireg)%lum(ilum)%aa%wyr
 170 lscal(ireg)%lum(ilum)%nbyr = 0
 171 lscal(ireg)%lum(ilum)%precip_aa = 0.
 172 lscal(ireg)%lum(ilum)%aa = lscal_z
IF (abs(denom) > 1.) THEN Lines 131-133
 132 chg_val = - (lscal(ireg)%lum(ilum)%prm_prev%etco - lscal(ireg)%lum(ilum)%prm%etco)                &
 133 * (pred - rmeas) / denom
END IFLine 133
ELSE Lines 134-137
 135 diff = soft - pred
 136 chg_val = - diff / 200.
END IF Line 137
IF (lscal(ireg)%lum(ilum)%prm%etco >= ls_prms(2)%pos) THEN Lines 145-149
 146 chg_val = ls_prms(2)%pos - lscal(ireg)%lum(ilum)%prm_prev%etco
 147 lscal(ireg)%lum(ilum)%prm%etco = ls_prms(2)%pos
 148 lscal(ireg)%lum(ilum)%prm_lim%etco = 1.
END IFLine 149
IF (lscal(ireg)%lum(ilum)%prm%etco <= ls_prms(2)%neg) THEN Lines 150-154
 151 chg_val = ls_prms(2)%neg - lscal(ireg)%lum(ilum)%prm_prev%etco
 152 lscal(ireg)%lum(ilum)%prm%etco = ls_prms(2)%neg
 153 lscal(ireg)%lum(ilum)%prm_lim%etco = 1.
END IFLine 154
DO ihru_s = 1, region(ireg)%num_tot Lines 156-169
 157 iihru = region(ireg)%num(ihru_s)
IF (lscal(ireg)%lum(ilum)%meas%name == hru(iihru)%lum_group_c .or. lscal(ireg)%lum(ilum)%meas%name == "basin") THEN Lines 158-168
 160 hru(iihru)%hyd%esco = hru(iihru)%hyd%esco + chg_val
 161 hru(iihru)%hyd%esco = amin1 (hru(iihru)%hyd%esco, ls_prms(2)%up)
 162 hru(iihru)%hyd%esco = Max (hru(iihru)%hyd%esco, ls_prms(2)%lo)
 163 hru_init(iihru)%hyd%esco = hru(iihru)%hyd%esco
END IFLine 168
END DOLine 169
END IFLine 177
END DOLine 178
END DOLine 179
IF (isim > 0) THEN Lines 188-192
 189 cal_sim =  " esco adj "
 190 cal_adj = chg_val
 191 call time_control
END IFLine 192
END DO
Allocations
n/a
Calls
Procedures Called
List of procedures called by this Subroutine.
amin1
re_initialize
time_control
Call Graph
Visual representation of procedures called by this Subroutine.
Call graph
calsoft_hyd_bfr_et calls amin1, re_initialize, time_control