caltsoft_hyd – test-src-project
caltsoft_hyd Subroutine
616 statements
Source File
subroutine caltsoft_hyd()
Uses
aquifer_module
channel_module
hru_lte_module
ru_module
conditional_module
basin_module
hydrograph_module
maximum_data_module
sd_channel_module
reservoir_module
calibration_data_module
Arguments
n/a
I/O
I/O units used in this subroutine.
Unit Type Filename
unit_4304 Output not specified
Outside Variables and Types
type(swatdeg_hru_dynamic) (2 attributes from hru_lte_module)
Attribute Name Description
hlt
hlt_init
type (3 attributes from maximum_data_module)
Attribute Name Description
db_mx%lsu_reg None
db_mx%plcal_reg None
cal_codes%hyd_hru None
type(soft_calib_parms) (1 attribute from calibration_data_module)
Attribute Name Description
ls_prms
type(soft_calib_ls_processes) (1 attribute from calibration_data_module)
Attribute Name Description
lscal_z
to zero values
type(soft_data_calib_landscape) (1 attribute from calibration_data_module)
Attribute Name Description
lscalt
dimension by region for hru_lte"s
type(cataloging_units) (1 attribute from calibration_data_module)
Attribute Name Description
region
dimension by region for hru"s
type(soft_calib_pl_processes) (1 attribute from calibration_data_module)
Attribute Name Description
plcal_z
to zero values
type(soft_data_calib_plant) (1 attribute from calibration_data_module)
Attribute Name Description
plcal
dimension by region for plants
!! Bang Comments
calculate shape parameters calculate shape parameters calculate shape parameters calculate shape parameters
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure.
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
  43 iter_all = 1
  44 iter_ind = 1
DO iterall = 1, iter_all
  48 isim = 0
DO ireg = 1, db_mx%lsu_reg Lines 49-105
DO ilum = 1, lscalt(ireg)%lum_num Lines 50-104
  51 soft = lscalt(ireg)%lum(ilum)%meas%srr * lscalt(ireg)%lum(ilum)%precip_aa
  52 diff = 0.
  53 if (soft > 1.e-6) diff = abs((soft - lscalt(ireg)%lum(ilum)%aa%srr) / soft)
IF (diff > .02 .and. lscalt(ireg)%lum(ilum)%ha > 1.e-6 .and. lscalt(ireg)%lum(ilum)%prm_lim%cn < 1.e-6) THEN Lines 54-103
  55 isim = 1
  57 lscalt(ireg)%lum(ilum)%prm_prev = lscalt(ireg)%lum(ilum)%prm
  58 lscalt(ireg)%lum(ilum)%prev = lscalt(ireg)%lum(ilum)%aa
  60 diff = lscalt(ireg)%lum(ilum)%meas%srr * lscalt(ireg)%lum(ilum)%precip_aa - lscalt(ireg)%lum(ilum)%aa%srr
  61 chg_val = diff / 15.     !assume 10 mm runoff for 1 cn
  62 lscalt(ireg)%lum(ilum)%prm_prev%cn = lscalt(ireg)%lum(ilum)%prm%cn
  63 lscalt(ireg)%lum(ilum)%prm%cn = lscalt(ireg)%lum(ilum)%prm%cn + chg_val
  64 lscalt(ireg)%lum(ilum)%prev%srr = lscalt(ireg)%lum(ilum)%aa%srr
 100 lscalt(ireg)%lum(ilum)%nbyr = 0
 101 lscalt(ireg)%lum(ilum)%precip_aa = 0.
 102 lscalt(ireg)%lum(ilum)%aa = lscal_z
IF (lscalt(ireg)%lum(ilum)%prm%cn >= ls_prms(1)%pos) THEN Lines 66-70
  67 chg_val = ls_prms(1)%pos - lscalt(ireg)%lum(ilum)%prm_prev%cn
  68 lscalt(ireg)%lum(ilum)%prm%cn = ls_prms(1)%pos
  69 lscalt(ireg)%lum(ilum)%prm_lim%cn = 1.
END IFLine 70
IF (lscalt(ireg)%lum(ilum)%prm%cn <= ls_prms(1)%neg) THEN Lines 71-75
  72 chg_val = ls_prms(1)%neg - lscalt(ireg)%lum(ilum)%prm_prev%cn
  73 lscalt(ireg)%lum(ilum)%prm%cn = ls_prms(1)%neg
  74 lscalt(ireg)%lum(ilum)%prm_lim%cn = 1.
END IFLine 75
DO ihru_s = 1, region(ireg)%num_tot Lines 77-99
  78 iihru = region(ireg)%num(ihru_s)
  81 hlt(iihru)= hlt_init(iihru)
  82 hlt(iihru)%cn2 = hlt(iihru)%cn2 + chg_val
  83 hlt(iihru)%cn2 = amin1 (hlt(iihru)%cn2, ls_prms(1)%up)
  84 hlt(iihru)%cn2 = Max (hlt(iihru)%cn2, ls_prms(1)%lo)
  85 qn1 = hlt(iihru)%cn2 - (20. * (100. - hlt(iihru)%cn2)) /                     &
  86 (100. - hlt(iihru)%cn2 + EXP(2.533 - .063 * (100. - hlt(iihru)%cn2)))
  87 qn1 = Max(qn1, .4 * hlt(iihru)%cn2)
  88 qn3 = hlt(iihru)%cn2 * EXP(.00673 * (100. - hlt(iihru)%cn2))
  89 hlt(iihru)%smx = 254. * (100. / qn1 - 1.)
  90 s3 = 254. * (100. / qn3 - 1.)
  91 rto3 = 1. - s3 / hlt(iihru)%smx
  92 rtos = 1. - 2.54 / hlt(iihru)%smx
  93 sumul = hlt(iihru)%por
  94 sumfc = hlt(iihru)%awc + hlt(iihru)%cn3_swf * (sumul - hlt(iihru)%awc)
  96 call ascrv(rto3, rtos, sumfc, sumul, hlt(iihru)%wrt1, hlt(iihru)%wrt2)
  97 hlt_init(iihru) = hlt(iihru)
END DOLine 99
END IFLine 103
END DOLine 104
END DOLine 105
DO ireg = 1, db_mx%plcal_reg Lines 108-114
DO ilum = 1, plcal(ireg)%lum_num Lines 109-113
 110 plcal(ireg)%lum(ilum)%nbyr = 0
 111 plcal(ireg)%lum(ilum)%precip_aa = 0.
 112 plcal(ireg)%lum(ilum)%aa = plcal_z
END DOLine 113
END DOLine 114
IF (isim > 0) THEN Lines 116-119
 117 write (4304,*) " first cn2 adj "
 118 call time_control
END IFLine 119
DO icn = 1, iter_ind
 123 isim = 0
 199 end do      ! icn
 202 isim = 0
DO ireg = 1, db_mx%lsu_reg Lines 124-184
DO ilum = 1, lscalt(ireg)%lum_num Lines 125-183
 126 soft = lscalt(ireg)%lum(ilum)%meas%srr * lscalt(ireg)%lum(ilum)%precip_aa
 127 diff = 0.
 128 if (soft > 1.e-6) diff = abs((soft - lscalt(ireg)%lum(ilum)%aa%srr) / soft)
IF (diff > .02 .and. lscalt(ireg)%lum(ilum)%ha > 1.e-6 .and. lscalt(ireg)%lum(ilum)%prm_lim%cn < 1.e-6) THEN Lines 129-182
 130 isim = 1
 132 rmeas = lscalt(ireg)%lum(ilum)%meas%srr * lscalt(ireg)%lum(ilum)%precip_aa
 133 denom = lscalt(ireg)%lum(ilum)%prev%srr - lscalt(ireg)%lum(ilum)%aa%srr
 140 lscalt(ireg)%lum(ilum)%prm_prev%cn = lscalt(ireg)%lum(ilum)%prm%cn
 141 lscalt(ireg)%lum(ilum)%prm%cn = lscalt(ireg)%lum(ilum)%prm%cn + chg_val
 142 lscalt(ireg)%lum(ilum)%prev%srr = lscalt(ireg)%lum(ilum)%aa%srr
 179 lscalt(ireg)%lum(ilum)%nbyr = 0
 180 lscalt(ireg)%lum(ilum)%precip_aa = 0.
 181 lscalt(ireg)%lum(ilum)%aa = lscal_z
IF (abs(denom) > 1.e-6) THEN Lines 134-136
 135 chg_val = - (lscalt(ireg)%lum(ilum)%prm_prev%cn - lscalt(ireg)%lum(ilum)%prm%cn)                  &
 136 * (lscalt(ireg)%lum(ilum)%aa%srr - rmeas) / denom
END IFLine 136
ELSE Lines 137-139
 138 chg_val = diff / 200.
END IF Line 139
IF (lscalt(ireg)%lum(ilum)%prm%cn >= ls_prms(1)%pos) THEN Lines 144-148
 145 chg_val = ls_prms(1)%pos - lscalt(ireg)%lum(ilum)%prm_prev%cn
 146 lscalt(ireg)%lum(ilum)%prm%cn = ls_prms(1)%pos
 147 lscalt(ireg)%lum(ilum)%prm_lim%cn = 1.
END IFLine 148
IF (lscalt(ireg)%lum(ilum)%prm%cn <= ls_prms(1)%neg) THEN Lines 149-153
 150 chg_val = lscalt(ireg)%lum(ilum)%prm_prev%cn - ls_prms(1)%neg
 151 lscalt(ireg)%lum(ilum)%prm%cn = ls_prms(1)%neg
 152 lscalt(ireg)%lum(ilum)%prm_lim%cn = 1.
END IFLine 153
DO ihru_s = 1, region(ireg)%num_tot Lines 156-178
 157 iihru = region(ireg)%num(ihru_s)
 160 hlt(iihru)= hlt_init(iihru)
 161 hlt(iihru)%cn2 = hlt(iihru)%cn2 + chg_val
 162 hlt(iihru)%cn2 = amin1 (hlt(iihru)%cn2, ls_prms(1)%up)
 163 hlt(iihru)%cn2 = Max (hlt(iihru)%cn2, ls_prms(1)%lo)
 164 qn1 = hlt(iihru)%cn2 - (20. * (100. - hlt(iihru)%cn2)) /                     &
 165 (100. - hlt(iihru)%cn2 + EXP(2.533 - .063 * (100. - hlt(iihru)%cn2)))
 166 qn1 = Max(qn1, .4 * hlt(iihru)%cn2)
 167 qn3 = hlt(iihru)%cn2 * EXP(.00673 * (100. - hlt(iihru)%cn2))
 168 hlt(iihru)%smx = 254. * (100. / qn1 - 1.)
 169 s3 = 254. * (100. / qn3 - 1.)
 170 rto3 = 1. - s3 / hlt(iihru)%smx
 171 rtos = 1. - 2.54 / hlt(iihru)%smx
 172 sumul = hlt(iihru)%por
 173 sumfc = hlt(iihru)%awc + hlt(iihru)%cn3_swf * (sumul - hlt(iihru)%awc)
 175 call ascrv(rto3, rtos, sumfc, sumul, hlt(iihru)%wrt1, hlt(iihru)%wrt2)
 176 hlt_init(iihru) = hlt(iihru)
END DOLine 178
END IFLine 182
END DOLine 183
END DOLine 184
DO ireg = 1, db_mx%plcal_reg Lines 187-193
DO ilum = 1, plcal(ireg)%lum_num Lines 188-192
 189 plcal(ireg)%lum(ilum)%nbyr = 0
 190 plcal(ireg)%lum(ilum)%precip_aa = 0.
 191 plcal(ireg)%lum(ilum)%aa = plcal_z
END DOLine 192
END DOLine 193
IF (isim > 0) THEN Lines 195-198
 196 write (4304,*) " cn2 adj "
 197 call time_control
END IFLine 198
DO ireg = 1, db_mx%lsu_reg Lines 203-248
DO ilum = 1, lscalt(ireg)%lum_num Lines 204-247
 206 soft = lscalt(ireg)%lum(ilum)%meas%etr * lscalt(ireg)%lum(ilum)%precip_aa
 207 diff = 0.
 208 if (soft > 1.e-6) diff = abs((soft - lscalt(ireg)%lum(ilum)%aa%etr) / soft)
IF (diff > .02 .and. lscalt(ireg)%lum(ilum)%ha > 1.e-6 .and. lscalt(ireg)%lum(ilum)%prm_lim%etco < 1.e-6) THEN Lines 209-246
 210 isim = 1
 212 lscalt(ireg)%lum(ilum)%prm_prev = lscalt(ireg)%lum(ilum)%prm
 213 lscalt(ireg)%lum(ilum)%prev = lscalt(ireg)%lum(ilum)%aa
 215 diff = lscalt(ireg)%lum(ilum)%meas%etr * lscalt(ireg)%lum(ilum)%precip_aa - lscalt(ireg)%lum(ilum)%aa%etr
 216 chg_val = diff / 200.     ! increment etco .05 for every 10 mm difference
 217 lscalt(ireg)%lum(ilum)%prm_prev%etco = lscalt(ireg)%lum(ilum)%prm%etco
 218 lscalt(ireg)%lum(ilum)%prm%etco = lscalt(ireg)%lum(ilum)%prm%etco + chg_val
 219 lscalt(ireg)%lum(ilum)%prev%etr = lscalt(ireg)%lum(ilum)%aa%etr
 243 lscalt(ireg)%lum(ilum)%nbyr = 0
 244 lscalt(ireg)%lum(ilum)%precip_aa = 0.
 245 lscalt(ireg)%lum(ilum)%aa = lscal_z
IF (lscalt(ireg)%lum(ilum)%prm%etco >= ls_prms(7)%pos) THEN Lines 221-225
 222 chg_val = ls_prms(7)%pos - lscalt(ireg)%lum(ilum)%prm_prev%etco
 223 lscalt(ireg)%lum(ilum)%prm%etco = ls_prms(7)%pos
 224 lscalt(ireg)%lum(ilum)%prm_lim%etco = 1.
END IFLine 225
IF (lscalt(ireg)%lum(ilum)%prm%etco <= ls_prms(7)%neg) THEN Lines 226-230
 227 chg_val = lscalt(ireg)%lum(ilum)%prm_prev%etco - ls_prms(7)%neg
 228 lscalt(ireg)%lum(ilum)%prm%etco = ls_prms(7)%neg
 229 lscalt(ireg)%lum(ilum)%prm_lim%etco = 1.
END IFLine 230
DO ihru_s = 1, region(ireg)%num_tot Lines 232-242
 233 iihru = region(ireg)%num(ihru_s)
 236 hlt(iihru)= hlt_init(iihru)
 237 hlt(iihru)%etco = hlt(iihru)%etco + chg_val
 238 hlt(iihru)%etco = amin1 (hlt(iihru)%etco, ls_prms(7)%up)
 239 hlt(iihru)%etco = Max (hlt(iihru)%etco, ls_prms(7)%lo)
 240 hlt_init(iihru) = hlt(iihru)
END DOLine 242
END IFLine 246
END DOLine 247
END DOLine 248
DO ireg = 1, db_mx%plcal_reg Lines 251-257
DO ilum = 1, plcal(ireg)%lum_num Lines 252-256
 253 plcal(ireg)%lum(ilum)%nbyr = 0
 254 plcal(ireg)%lum(ilum)%precip_aa = 0.
 255 plcal(ireg)%lum(ilum)%aa = plcal_z
END DOLine 256
END DOLine 257
IF (isim > 0) THEN Lines 259-262
 260 write (4304,*) " first etco adj "
 261 call time_control
END IFLine 262
DO ietco = 1, iter_ind
 266 isim = 0
 331 end do      ! ietco
 334 isim = 0
DO ireg = 1, db_mx%lsu_reg Lines 267-315
DO ilum = 1, lscalt(ireg)%lum_num Lines 268-314
 270 soft = lscalt(ireg)%lum(ilum)%meas%etr * lscalt(ireg)%lum(ilum)%precip_aa
 271 diff = 0.
 272 if (soft > 1.e-6) diff = abs((soft - lscalt(ireg)%lum(ilum)%aa%etr) / soft)
IF (diff > .02 .and. lscalt(ireg)%lum(ilum)%ha > 1.e-6 .and. lscalt(ireg)%lum(ilum)%prm_lim%etco < 1.e-6) THEN Lines 273-313
 274 isim = 1
 276 rmeas = lscalt(ireg)%lum(ilum)%meas%etr * lscalt(ireg)%lum(ilum)%precip_aa
 277 denom = lscalt(ireg)%lum(ilum)%prev%etr - lscalt(ireg)%lum(ilum)%aa%etr
 284 lscalt(ireg)%lum(ilum)%prm_prev%etco = lscalt(ireg)%lum(ilum)%prm%etco
 285 lscalt(ireg)%lum(ilum)%prm%etco = lscalt(ireg)%lum(ilum)%prm%etco + chg_val
 286 lscalt(ireg)%lum(ilum)%prev%etr = lscalt(ireg)%lum(ilum)%aa%etr
 310 lscalt(ireg)%lum(ilum)%nbyr = 0
 311 lscalt(ireg)%lum(ilum)%precip_aa = 0.
 312 lscalt(ireg)%lum(ilum)%aa = lscal_z
IF (abs(denom) > 1.e-6) THEN Lines 278-280
 279 chg_val = - (lscalt(ireg)%lum(ilum)%prm_prev%etco - lscalt(ireg)%lum(ilum)%prm%etco)                  &
 280 * (lscalt(ireg)%lum(ilum)%aa%etr - rmeas) / denom
END IFLine 280
ELSE Lines 281-283
 282 chg_val = diff / 200.
END IF Line 283
IF (lscalt(ireg)%lum(ilum)%prm%etco >= ls_prms(7)%pos) THEN Lines 288-292
 289 chg_val = ls_prms(7)%pos - lscalt(ireg)%lum(ilum)%prm_prev%etco
 290 lscalt(ireg)%lum(ilum)%prm%etco = ls_prms(7)%pos
 291 lscalt(ireg)%lum(ilum)%prm_lim%etco = 1.
END IFLine 292
IF (lscalt(ireg)%lum(ilum)%prm%etco <= ls_prms(7)%neg) THEN Lines 293-297
 294 chg_val = lscalt(ireg)%lum(ilum)%prm_prev%etco - ls_prms(7)%neg
 295 lscalt(ireg)%lum(ilum)%prm%etco = ls_prms(7)%neg
 296 lscalt(ireg)%lum(ilum)%prm_lim%etco = 1.
END IFLine 297
DO ihru_s = 1, region(ireg)%num_tot Lines 299-309
 300 iihru = region(ireg)%num(ihru_s)
 303 hlt(iihru)= hlt_init(iihru)
 304 hlt(iihru)%etco = hlt(iihru)%etco + chg_val
 305 hlt(iihru)%etco = amin1 (hlt(iihru)%etco, ls_prms(7)%up)
 306 hlt(iihru)%etco = Max (hlt(iihru)%etco, ls_prms(7)%lo)
 307 hlt_init(iihru) = hlt(iihru)
END DOLine 309
END IFLine 313
END DOLine 314
END DOLine 315
DO ireg = 1, db_mx%plcal_reg Lines 318-324
DO ilum = 1, plcal(ireg)%lum_num Lines 319-323
 320 plcal(ireg)%lum(ilum)%nbyr = 0
 321 plcal(ireg)%lum(ilum)%precip_aa = 0.
 322 plcal(ireg)%lum(ilum)%aa = plcal_z
END DOLine 323
END DOLine 324
IF (isim > 0) THEN Lines 326-329
 327 write (4304,*) " etco adj "
 328 call time_control
END IFLine 329
DO ireg = 1, db_mx%lsu_reg Lines 335-384
DO ilum = 1, lscalt(ireg)%lum_num Lines 336-383
 338 soft = lscalt(ireg)%lum(ilum)%meas%pcr * lscalt(ireg)%lum(ilum)%precip_aa
 339 diff = 0.
 340 if (soft > 1.e-6) diff = abs((soft - lscalt(ireg)%lum(ilum)%aa%pcr) / soft)
IF (diff > .1 .and. lscalt(ireg)%lum(ilum)%ha > 1.e-6 .and. lscalt(ireg)%lum(ilum)%prm_lim%perco < 1.e-6) THEN Lines 341-379
 342 isim = 1
 344 lscalt(ireg)%lum(ilum)%prm_prev = lscalt(ireg)%lum(ilum)%prm
 345 lscalt(ireg)%lum(ilum)%prev = lscalt(ireg)%lum(ilum)%aa
 347 chg_val = (soft - lscalt(ireg)%lum(ilum)%aa%pcr) / 200.      ! .5 increase for every 100 mm difference
 348 lscalt(ireg)%lum(ilum)%prm_prev%perco = lscalt(ireg)%lum(ilum)%prm%perco
 349 lscalt(ireg)%lum(ilum)%prm%perco = lscalt(ireg)%lum(ilum)%prm%perco + chg_val
 350 lscalt(ireg)%lum(ilum)%prev%pcr = lscalt(ireg)%lum(ilum)%aa%pcr
 377 lscalt(ireg)%lum(ilum)%nbyr = 0
 378 lscalt(ireg)%lum(ilum)%precip_aa = 0.
 379 lscalt(ireg)%lum(ilum)%aa = lscal_z
IF (lscalt(ireg)%lum(ilum)%prm%perco >= ls_prms(8)%pos) THEN Lines 352-356
 353 lscalt(ireg)%lum(ilum)%prm%perco = ls_prms(8)%pos
 354 chg_val = ls_prms(8)%pos
 355 lscalt(ireg)%lum(ilum)%prm_lim%perco = 1.
END IFLine 356
IF (lscalt(ireg)%lum(ilum)%prm%perco <= ls_prms(8)%neg) THEN Lines 357-361
 358 lscalt(ireg)%lum(ilum)%prm%perco = ls_prms(8)%neg
 359 chg_val = ls_prms(8)%neg
 360 lscalt(ireg)%lum(ilum)%prm_lim%perco = 1.
END IFLine 361
DO ihru_s = 1, region(ireg)%num_tot Lines 363-376
 364 iihru = region(ireg)%num(ihru_s)
 367 hlt(iihru)= hlt_init(iihru)
 368 hlt(iihru)%perco = hlt(iihru)%perco - chg_val
 369 hlt(iihru)%perco = amin1 (hlt(iihru)%perco, ls_prms(8)%up)
 370 hlt(iihru)%perco = Max (hlt(iihru)%perco, ls_prms(8)%lo)
 371 hlt_init(iihru) = hlt(iihru)
END DOLine 376
END IFLine 379
ELSE Lines 380-382
 381 lscalt(ireg)%lum(ilum)%prm_lim%perco = 1.
END IF Line 382
END DOLine 383
END DOLine 384
DO ireg = 1, db_mx%plcal_reg Lines 387-393
DO ilum = 1, plcal(ireg)%lum_num Lines 388-392
 389 plcal(ireg)%lum(ilum)%nbyr = 0
 390 plcal(ireg)%lum(ilum)%precip_aa = 0.
 391 plcal(ireg)%lum(ilum)%aa = plcal_z
END DOLine 392
END DOLine 393
IF (isim > 0) THEN Lines 395-398
 396 write (4304,*) " first perco adj "
 397 call time_control
END IFLine 398
DO iperco = 1, iter_ind
 402 isim = 0
 472 end do      ! iperco
 475 isim = 0
 608 isim = 0
DO ireg = 1, db_mx%lsu_reg Lines 403-456
DO ilum = 1, lscalt(ireg)%lum_num Lines 404-455
 405 soft = lscalt(ireg)%lum(ilum)%meas%pcr * lscalt(ireg)%lum(ilum)%precip_aa
 406 diff = 0.
 407 if (soft > 1.e-6) diff = abs((soft - lscalt(ireg)%lum(ilum)%aa%pcr) / soft)
IF (diff > .1 .and. lscalt(ireg)%lum(ilum)%ha > 1.e-6 .and. lscalt(ireg)%lum(ilum)%prm_lim%perco < 1.e-6) THEN Lines 408-451
 409 isim = 1
 411 rmeas = lscalt(ireg)%lum(ilum)%meas%pcr * lscalt(ireg)%lum(ilum)%precip_aa
 412 denom = lscalt(ireg)%lum(ilum)%prev%pcr - lscalt(ireg)%lum(ilum)%aa%pcr
 419 lscalt(ireg)%lum(ilum)%prm%perco = lscalt(ireg)%lum(ilum)%prm%perco + chg_val
 420 lscalt(ireg)%lum(ilum)%prm_prev%perco = lscalt(ireg)%lum(ilum)%prm%perco
 421 lscalt(ireg)%lum(ilum)%prev%pcr = lscalt(ireg)%lum(ilum)%aa%pcr
 449 lscalt(ireg)%lum(ilum)%nbyr = 0
 450 lscalt(ireg)%lum(ilum)%precip_aa = 0.
 451 lscalt(ireg)%lum(ilum)%aa = lscal_z
IF (abs(denom) > 1.e-6) THEN Lines 413-415
 414 chg_val = - (lscalt(ireg)%lum(ilum)%prm_prev%perco - lscalt(ireg)%lum(ilum)%prm%perco) *         &
 415 (lscalt(ireg)%lum(ilum)%aa%pcr - rmeas) / denom
END IFLine 415
ELSE Lines 416-418
 417 chg_val = (soft - lscalt(ireg)%lum(ilum)%aa%pcr) / 200.
END IF Line 418
IF (lscalt(ireg)%lum(ilum)%prm%perco >= ls_prms(8)%pos) THEN Lines 423-427
 424 chg_val = lscalt(ireg)%lum(ilum)%prm_prev%perco - ls_prms(8)%pos
 425 lscalt(ireg)%lum(ilum)%prm%perco = ls_prms(8)%pos
 426 lscalt(ireg)%lum(ilum)%prm_lim%perco = 1.
END IFLine 427
IF (lscalt(ireg)%lum(ilum)%prm%perco <= ls_prms(8)%neg) THEN Lines 428-432
 429 chg_val = lscalt(ireg)%lum(ilum)%prm_prev%perco - ls_prms(8)%neg
 430 lscalt(ireg)%lum(ilum)%prm%perco = ls_prms(8)%neg
 431 lscalt(ireg)%lum(ilum)%prm_lim%perco = 1.
END IFLine 432
DO ihru_s = 1, region(ireg)%num_tot Lines 435-448
 436 iihru = region(ireg)%num(ihru_s)
 439 hlt(iihru)= hlt_init(iihru)
 440 hlt(iihru)%perco = hlt(iihru)%perco - chg_val
 441 hlt(iihru)%perco = amin1 (hlt(iihru)%perco, ls_prms(8)%up)
 442 hlt(iihru)%perco = Max (hlt(iihru)%perco, ls_prms(8)%lo)
 443 hlt_init(iihru) = hlt(iihru)
END DOLine 448
END IFLine 451
ELSE Lines 452-454
 453 lscalt(ireg)%lum(ilum)%prm_lim%perco = 1.
END IF Line 454
END DOLine 455
END DOLine 456
DO ireg = 1, db_mx%plcal_reg Lines 459-465
DO ilum = 1, plcal(ireg)%lum_num Lines 460-464
 461 plcal(ireg)%lum(ilum)%nbyr = 0
 462 plcal(ireg)%lum(ilum)%precip_aa = 0.
 463 plcal(ireg)%lum(ilum)%aa = plcal_z
END DOLine 464
END DOLine 465
IF (isim > 0) THEN Lines 467-470
 468 write (4304,*) " perco adj "
 469 call time_control
END IFLine 470
DO ireg = 1, db_mx%lsu_reg Lines 476-522
DO ilum = 1, lscalt(ireg)%lum_num Lines 477-521
 479 soft = lscalt(ireg)%lum(ilum)%meas%lfr * lscalt(ireg)%lum(ilum)%precip_aa
 480 diff = 0.
 481 if (soft > 1.e-6) diff = abs((soft - lscalt(ireg)%lum(ilum)%aa%lfr) / soft)
IF (diff > .1 .and. lscalt(ireg)%lum(ilum)%ha > 1.e-6 .and. lscalt(ireg)%lum(ilum)%prm_lim%revapc < 1.e-6) THEN Lines 482-520
 483 isim = 1
 485 lscalt(ireg)%lum(ilum)%prm_prev = lscalt(ireg)%lum(ilum)%prm
 486 lscalt(ireg)%lum(ilum)%prev = lscalt(ireg)%lum(ilum)%aa
 488 diff = lscalt(ireg)%lum(ilum)%meas%lfr * lscalt(ireg)%lum(ilum)%precip_aa - lscalt(ireg)%lum(ilum)%aa%lfr
 489 chg_val =  diff / 250.      ! increment revapc by 0.4 for 100 mm difference
 490 lscalt(ireg)%lum(ilum)%prm_prev%revapc = lscalt(ireg)%lum(ilum)%prm%revapc
 491 lscalt(ireg)%lum(ilum)%prm%revapc = lscalt(ireg)%lum(ilum)%prm%revapc - chg_val
 492 lscalt(ireg)%lum(ilum)%prev%lfr = lscalt(ireg)%lum(ilum)%aa%lfr
 517 lscalt(ireg)%lum(ilum)%nbyr = 0
 518 lscalt(ireg)%lum(ilum)%precip_aa = 0.
 519 lscalt(ireg)%lum(ilum)%aa = lscal_z
IF (lscalt(ireg)%lum(ilum)%prm%revapc >= ls_prms(9)%pos) THEN Lines 494-498
 495 lscalt(ireg)%lum(ilum)%prm%revapc = ls_prms(9)%pos
 496 chg_val = ls_prms(9)%pos
 497 lscalt(ireg)%lum(ilum)%prm_lim%revapc = 1.
END IFLine 498
IF (lscalt(ireg)%lum(ilum)%prm%revapc <= ls_prms(9)%neg) THEN Lines 499-503
 500 lscalt(ireg)%lum(ilum)%prm%revapc = ls_prms(9)%neg
 501 chg_val = ls_prms(9)%neg
 502 lscalt(ireg)%lum(ilum)%prm_lim%revapc = 1.
END IFLine 503
DO ihru_s = 1, region(ireg)%num_tot Lines 505-516
 506 iihru = region(ireg)%num(ihru_s)
 509 hlt(iihru)= hlt_init(iihru)
 510 hlt(iihru)%revapc = hlt(iihru)%revapc + chg_val
 511 hlt(iihru)%revapc = amin1 (hlt(iihru)%revapc, ls_prms(9)%up)
 512 hlt(iihru)%revapc = Max (hlt(iihru)%revapc, ls_prms(9)%lo)
 513 hlt_init(iihru)%revapc = hlt(iihru)%revapc
 514 hlt_init(iihru) = hlt(iihru)
END DOLine 516
END IFLine 520
END DOLine 521
END DOLine 522
DO ireg = 1, db_mx%plcal_reg Lines 525-531
DO ilum = 1, plcal(ireg)%lum_num Lines 526-530
 527 plcal(ireg)%lum(ilum)%nbyr = 0
 528 plcal(ireg)%lum(ilum)%precip_aa = 0.
 529 plcal(ireg)%lum(ilum)%aa = plcal_z
END DOLine 530
END DOLine 531
IF (isim > 0) THEN Lines 533-536
 534 write (4304,*) " first revapc adj "
 535 call time_control
END IFLine 536
DO ik = 1, iter_ind Lines 539-605
 540 isim = 0
DO ireg = 1, db_mx%lsu_reg Lines 541-590
DO ilum = 1, lscalt(ireg)%lum_num Lines 542-589
 543 soft = lscalt(ireg)%lum(ilum)%meas%lfr * lscalt(ireg)%lum(ilum)%precip_aa
 544 diff = 0.
 545 if (soft > 1.e-6) diff = abs((soft - lscalt(ireg)%lum(ilum)%aa%lfr) / soft)
IF (diff > .1 .and. lscalt(ireg)%lum(ilum)%ha > 1.e-6 .and. lscalt(ireg)%lum(ilum)%prm_lim%revapc < 1.e-6) THEN Lines 546-588
 547 isim = 1
 549 rmeas = lscalt(ireg)%lum(ilum)%meas%lfr * lscalt(ireg)%lum(ilum)%precip_aa
 550 denom = lscalt(ireg)%lum(ilum)%prev%lfr - lscalt(ireg)%lum(ilum)%aa%lfr
 557 lscalt(ireg)%lum(ilum)%prm_prev%revapc = lscalt(ireg)%lum(ilum)%prm%revapc
 558 lscalt(ireg)%lum(ilum)%prm%revapc = lscalt(ireg)%lum(ilum)%prm%revapc + chg_val
 559 lscalt(ireg)%lum(ilum)%prev%lfr = lscalt(ireg)%lum(ilum)%aa%lfr
 585 lscalt(ireg)%lum(ilum)%nbyr = 0
 586 lscalt(ireg)%lum(ilum)%precip_aa = 0.
 587 lscalt(ireg)%lum(ilum)%aa = lscal_z
IF (abs(denom) > 1.e-6) THEN Lines 551-553
 552 chg_val = - (lscalt(ireg)%lum(ilum)%prm_prev%revapc - lscalt(ireg)%lum(ilum)%prm%revapc)                  &
 553 * (lscalt(ireg)%lum(ilum)%aa%lfr - rmeas) / denom
END IFLine 553
ELSE Lines 554-556
 555 chg_val = diff / 250.
END IF Line 556
IF (lscalt(ireg)%lum(ilum)%prm%revapc >= ls_prms(9)%pos) THEN Lines 561-565
 562 lscalt(ireg)%lum(ilum)%prm%revapc = ls_prms(9)%pos
 563 chg_val = ls_prms(9)%pos
 564 lscalt(ireg)%lum(ilum)%prm_lim%revapc = 1.
END IFLine 565
IF (lscalt(ireg)%lum(ilum)%prm%revapc <= ls_prms(9)%neg) THEN Lines 566-570
 567 lscalt(ireg)%lum(ilum)%prm%revapc = ls_prms(9)%neg
 568 chg_val = ls_prms(9)%neg
 569 lscalt(ireg)%lum(ilum)%prm_lim%revapc = 1.
END IFLine 570
DO ihru_s = 1, region(ireg)%num_tot Lines 573-584
 574 iihru = region(ireg)%num(ihru_s)
 577 hlt(iihru)= hlt_init(iihru)
 578 hlt(iihru)%revapc = hlt(iihru)%revapc + chg_val
 579 hlt(iihru)%revapc = amin1 (hlt(iihru)%revapc, ls_prms(9)%up)
 580 hlt(iihru)%revapc = Max (hlt(iihru)%revapc, ls_prms(9)%lo)
 581 hlt_init(iihru)%revapc = hlt(iihru)%revapc
 582 hlt_init(iihru) = hlt(iihru)
END DOLine 584
END IFLine 588
END DOLine 589
END DOLine 590
DO ireg = 1, db_mx%plcal_reg Lines 593-599
DO ilum = 1, plcal(ireg)%lum_num Lines 594-598
 595 plcal(ireg)%lum(ilum)%nbyr = 0
 596 plcal(ireg)%lum(ilum)%precip_aa = 0.
 597 plcal(ireg)%lum(ilum)%aa = plcal_z
END DOLine 598
END DOLine 599
IF (isim > 0) THEN Lines 601-604
 602 write (4304,*) " revapc adj "
 603 call time_control
END IFLine 604
END DOLine 605
DO ireg = 1, db_mx%lsu_reg Lines 609-666
DO ilum = 1, lscalt(ireg)%lum_num Lines 610-665
 611 soft = lscalt(ireg)%lum(ilum)%meas%srr * lscalt(ireg)%lum(ilum)%precip_aa
 612 diff = 0.
 613 if (soft > 1.e-6) diff = abs((soft - lscalt(ireg)%lum(ilum)%aa%srr) / soft)
IF (diff > .02 .and. lscalt(ireg)%lum(ilum)%ha > 1.e-6 .and. lscalt(ireg)%lum(ilum)%prm_lim%cn3_swf < 1.e-6) THEN Lines 614-664
 615 isim = 1
 617 lscalt(ireg)%lum(ilum)%prm_prev = lscalt(ireg)%lum(ilum)%prm
 618 lscalt(ireg)%lum(ilum)%prev = lscalt(ireg)%lum(ilum)%aa
 620 diff = lscalt(ireg)%lum(ilum)%meas%srr * lscalt(ireg)%lum(ilum)%precip_aa - lscalt(ireg)%lum(ilum)%aa%srr
 621 chg_val = diff / 300.     !assume 10 mm runoff for .3 cn3_swf
 622 lscalt(ireg)%lum(ilum)%prm_prev%cn3_swf = lscalt(ireg)%lum(ilum)%prm%cn3_swf
 623 lscalt(ireg)%lum(ilum)%prm%cn3_swf = lscalt(ireg)%lum(ilum)%prm%cn3_swf + chg_val
 624 lscalt(ireg)%lum(ilum)%prev%srr = lscalt(ireg)%lum(ilum)%aa%srr
 661 lscalt(ireg)%lum(ilum)%nbyr = 0
 662 lscalt(ireg)%lum(ilum)%precip_aa = 0.
 663 lscalt(ireg)%lum(ilum)%aa = lscal_z
IF (lscalt(ireg)%lum(ilum)%prm%cn3_swf >= ls_prms(10)%pos) THEN Lines 626-630
 627 chg_val = ls_prms(10)%pos - lscalt(ireg)%lum(ilum)%prm_prev%cn3_swf
 628 lscalt(ireg)%lum(ilum)%prm%cn3_swf = ls_prms(10)%pos
 629 lscalt(ireg)%lum(ilum)%prm_lim%cn3_swf = 1.
END IFLine 630
IF (lscalt(ireg)%lum(ilum)%prm%cn3_swf <= ls_prms(10)%neg) THEN Lines 631-635
 632 chg_val = ls_prms(10)%neg - lscalt(ireg)%lum(ilum)%prm_prev%cn3_swf
 633 lscalt(ireg)%lum(ilum)%prm%cn3_swf = ls_prms(10)%neg
 634 lscalt(ireg)%lum(ilum)%prm_lim%cn3_swf = 1.
END IFLine 635
DO ihru_s = 1, region(ireg)%num_tot Lines 637-660
 638 iihru = region(ireg)%num(ihru_s)
 641 hlt(iihru)= hlt_init(iihru)
 642 hlt(iihru)%cn3_swf = hlt(iihru)%cn3_swf - chg_val
 643 hlt(iihru)%cn3_swf = amin1 (hlt(iihru)%cn3_swf, ls_prms(10)%up)
 644 hlt(iihru)%cn3_swf = Max (hlt(iihru)%cn3_swf, ls_prms(10)%lo)
 645 qn1 = hlt(iihru)%cn2 - (20. * (100. - hlt(iihru)%cn2)) /                     &
 646 (100. - hlt(iihru)%cn2 + EXP(2.533 - .063 * (100. - hlt(iihru)%cn2)))
 647 qn1 = Max(qn1, .4 * hlt(iihru)%cn2)
 648 qn3 = hlt(iihru)%cn2 * EXP(.00673 * (100. - hlt(iihru)%cn2))
 649 hlt(iihru)%smx = 254. * (100. / qn1 - 1.)
 650 s3 = 254. * (100. / qn3 - 1.)
 651 rto3 = 1. - s3 / hlt(iihru)%smx
 652 rtos = 1. - 2.54 / hlt(iihru)%smx
 653 sumul = hlt(iihru)%por
 654 sumfc = hlt(iihru)%awc + hlt(iihru)%cn3_swf * (sumul - hlt(iihru)%awc)
 655 sumfc = Max (sumfc, .5 * hlt(iihru)%awc)
 657 call ascrv(rto3, rtos, sumfc, sumul, hlt(iihru)%wrt1, hlt(iihru)%wrt2)
 658 hlt_init(iihru) = hlt(iihru)
END DOLine 660
END IFLine 664
END DOLine 665
END DOLine 666
DO ireg = 1, db_mx%plcal_reg Lines 669-675
DO ilum = 1, plcal(ireg)%lum_num Lines 670-674
 671 plcal(ireg)%lum(ilum)%nbyr = 0
 672 plcal(ireg)%lum(ilum)%precip_aa = 0.
 673 plcal(ireg)%lum(ilum)%aa = plcal_z
END DOLine 674
END DOLine 675
IF (isim > 0) THEN Lines 677-680
 678 write (4304,*) " first cn3_swf adj "
 679 call time_control
END IFLine 680
DO icn = 1, iter_ind
 684 isim = 0
 761 end do      ! icn
 763 end do    ! iter_all loop
 765 cal_codes%hyd_hru = "n"
 767 return
DO ireg = 1, db_mx%lsu_reg Lines 685-746
DO ilum = 1, lscalt(ireg)%lum_num Lines 686-745
 687 soft = lscalt(ireg)%lum(ilum)%meas%srr * lscalt(ireg)%lum(ilum)%precip_aa
 688 diff = 0.
 689 if (soft > 1.e-6) diff = abs((soft - lscalt(ireg)%lum(ilum)%aa%srr) / soft)
IF (diff > .02 .and. lscalt(ireg)%lum(ilum)%ha > 1.e-6 .and. lscalt(ireg)%lum(ilum)%prm_lim%cn3_swf < 1.e-6) THEN Lines 690-744
 691 isim = 1
 693 rmeas = lscalt(ireg)%lum(ilum)%meas%srr * lscalt(ireg)%lum(ilum)%precip_aa
 694 denom = lscalt(ireg)%lum(ilum)%prev%srr - lscalt(ireg)%lum(ilum)%aa%srr
 701 lscalt(ireg)%lum(ilum)%prm_prev%cn3_swf = lscalt(ireg)%lum(ilum)%prm%cn3_swf
 702 lscalt(ireg)%lum(ilum)%prm%cn3_swf = lscalt(ireg)%lum(ilum)%prm%cn3_swf + chg_val
 703 lscalt(ireg)%lum(ilum)%prev%srr = lscalt(ireg)%lum(ilum)%aa%srr
 741 lscalt(ireg)%lum(ilum)%nbyr = 0
 742 lscalt(ireg)%lum(ilum)%precip_aa = 0.
 743 lscalt(ireg)%lum(ilum)%aa = lscal_z
IF (abs(denom) > 1.e-6) THEN Lines 695-697
 696 chg_val = - (lscalt(ireg)%lum(ilum)%prm_prev%cn3_swf - lscalt(ireg)%lum(ilum)%prm%cn3_swf)                  &
 697 * (lscalt(ireg)%lum(ilum)%aa%srr - rmeas) / denom
END IFLine 697
ELSE Lines 698-700
 699 chg_val = diff / 300.
END IF Line 700
IF (lscalt(ireg)%lum(ilum)%prm%cn3_swf >= ls_prms(1)%pos) THEN Lines 705-709
 706 chg_val = ls_prms(1)%pos - lscalt(ireg)%lum(ilum)%prm_prev%cn3_swf
 707 lscalt(ireg)%lum(ilum)%prm%cn3_swf = ls_prms(1)%pos
 708 lscalt(ireg)%lum(ilum)%prm_lim%cn3_swf = 1.
END IFLine 709
IF (lscalt(ireg)%lum(ilum)%prm%cn3_swf <= ls_prms(1)%neg) THEN Lines 710-714
 711 chg_val = lscalt(ireg)%lum(ilum)%prm_prev%cn3_swf - ls_prms(1)%neg
 712 lscalt(ireg)%lum(ilum)%prm%cn3_swf = ls_prms(1)%neg
 713 lscalt(ireg)%lum(ilum)%prm_lim%cn3_swf = 1.
END IFLine 714
DO ihru_s = 1, region(ireg)%num_tot Lines 717-740
 718 iihru = region(ireg)%num(ihru_s)
 721 hlt(iihru)= hlt_init(iihru)
 722 hlt(iihru)%cn3_swf = hlt(iihru)%cn3_swf - chg_val
 723 hlt(iihru)%cn3_swf = amin1 (hlt(iihru)%cn3_swf, ls_prms(10)%up)
 724 hlt(iihru)%cn3_swf = Max (hlt(iihru)%cn3_swf, ls_prms(10)%lo)
 725 qn1 = hlt(iihru)%cn2 - (20. * (100. - hlt(iihru)%cn2)) /                     &
 726 (100. - hlt(iihru)%cn2 + EXP(2.533 - .063 * (100. - hlt(iihru)%cn2)))
 727 qn1 = Max(qn1, .4 * hlt(iihru)%cn2)
 728 qn3 = hlt(iihru)%cn2 * EXP(.00673 * (100. - hlt(iihru)%cn2))
 729 hlt(iihru)%smx = 254. * (100. / qn1 - 1.)
 730 s3 = 254. * (100. / qn3 - 1.)
 731 rto3 = 1. - s3 / hlt(iihru)%smx
 732 rtos = 1. - 2.54 / hlt(iihru)%smx
 733 sumul = hlt(iihru)%por
 734 sumfc = hlt(iihru)%awc + hlt(iihru)%cn3_swf * (sumul - hlt(iihru)%awc)
 735 sumfc = Max (sumfc, .5 * hlt(iihru)%awc)
 737 call ascrv(rto3, rtos, sumfc, sumul, hlt(iihru)%wrt1, hlt(iihru)%wrt2)
 738 hlt_init(iihru) = hlt(iihru)
END DOLine 740
END IFLine 744
END DOLine 745
END DOLine 746
DO ireg = 1, db_mx%plcal_reg Lines 749-755
DO ilum = 1, plcal(ireg)%lum_num Lines 750-754
 751 plcal(ireg)%lum(ilum)%nbyr = 0
 752 plcal(ireg)%lum(ilum)%precip_aa = 0.
 753 plcal(ireg)%lum(ilum)%aa = plcal_z
END DOLine 754
END DOLine 755
IF (isim > 0) THEN Lines 757-760
 758 write (4304,*) " cn3_swf adj "
 759 call time_control
END IFLine 760
END DO
END DO
END DO
END DO
END DO
Allocations
n/a
Calls
Calls
Procedures called by this subroutine.
Local Variables
Type Visibility Attributes Name Initial
integer, private :: iter_all
integer, private :: iterall
integer, private :: isim
integer, private :: ireg
integer, private :: ilum
integer, private :: iihru
integer, private :: icn
integer, private :: ihru_s
integer, private :: iter_ind
integer, private :: ietco
integer, private :: ik
integer, private :: iperco
real, private :: rmeas
real, private :: denom
real, private :: soft
real, private :: diff
real, private :: chg_val
real, private :: qn1
real, private :: qn3
real, private :: s3
real, private :: rto3
real, private :: rtos
real, private :: sumul
real, private :: sumfc
Call graph
caltsoft_hyd calls amin1, ascrv, time_control