channel_control – TestDataProject
channel_control Subroutine
122 statements
Source File
subroutine channel_control()
Called From
n/a
Arguments
n/a
Outside Variables and Types
type (2 attributes from basin_module)
Attribute Name Description
bsn_cc%rte None
time%step None
integer (6 attributes from hydrograph_module)
Attribute Name Description
jrch
none |reach number
Read more…
iwst
|
icmd
|
jhyd
units |description
Read more…
jsed
units |description
Read more…
jnut
units |description
Read more…
type(hyd_output) (4 attributes from hydrograph_module)
Attribute Name Description
hd
hz
fp_dep
ch_dep
type(timestep) (1 attribute from hydrograph_module)
Attribute Name Description
ts
type(object_connectivity) (1 attribute from hydrograph_module)
Attribute Name Description
ob
real (17 attributes from channel_module)
Attribute Name Description
ben_area
m2 |benthic area (bottom sediments)
Read more…
rchdep
m |depth of flow on day
Read more…
rtevp
m^3 H2O |evaporation from reach on day
Read more…
rttlc
m^3 H2O |transmission losses from reach on day
Read more…
pet_ch
mm |potential evaporation from reach on day
Read more…
hrtwtr
m^3 H2O |water leaving reach
Read more…
sedrch
metric tons |sediment transported out of reach on day
Read more…
rch_san
rch_sil
rch_cla
rch_sag
rtwtr_d
m^3 H2O |water leaving reach during day
Read more…
rt_delt
calculation time step in days
rch_lag
rch_gra
rtwtr
m^3 H2O |water leaving reach on day
Read more…
wtrin
m^3 |water entering reach during day
Read more…
type(channel) (1 attribute from channel_module)
Attribute Name Description
ch
type(ch_output) (1 attribute from channel_module)
Attribute Name Description
ch_d
type(channel_data) (1 attribute from channel_data_module)
Attribute Name Description
ch_dat
type(channel_hyd_data) (1 attribute from channel_data_module)
Attribute Name Description
ch_hyd
type(channel_sed_data) (1 attribute from channel_data_module)
Attribute Name Description
ch_sed
type(weather_daily) (1 attribute from climate_module)
Attribute Name Description
w
type(weather_station) (1 attribute from climate_module)
Attribute Name Description
wst
Uses
basin_module
time_module
constituent_mass_module
hydrograph_module
channel_module
channel_data_module
climate_module
I/O
n/a
Local Variables
Type Visibility Attributes Name Initial
integer, public :: ii = 0
real, public :: qdbank = 0.
real, public :: revapday = 0.
real, public :: chlin = 0.
real, public :: algin = 0.
real, public :: orgnin = 0.
real, public :: ammoin = 0.
real, public :: nitratin = 0.
real, public :: nitritin = 0.
real, public :: orgpin = 0.
real, public :: dispin = 0.
real, public :: cbodin = 0.
real, public :: disoxin = 0.
real, public :: cinn = 0.
real, public :: rttlc_d = 0.
real, public :: rtevp_d = 0.
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure. Use mouse wheel to zoom, drag to pan.
Reset Zoom Help
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
~ ~ ~ PURPOSE ~ ~ ~ (line 3)
this subroutine simulates channel routing (line 4)
~ ~ ~ INCOMING VARIABLES ~ ~ ~ (line 6)
name |units |definition (line 7)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ (line 8)
bankst(:) |m^3 H2O |bank storage (line 9)
inum1 |none |reach number (line 10)
inum2 |none |inflow hydrograph storage location number (line 11)
pet_ch |mm H2O |potential evapotranspiration on day (line 12)
rchdep |m |depth of flow on day (line 13)
rttlc |m^3 H2O |transmission losses from reach on day (line 14)
rtwtr |m^3 H2O |water leaving reach on day (line 15)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ (line 16)
~ ~ ~ OUTGOING VARIABLES ~ ~ ~ (line 17)
name |units |definition (line 18)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ (line 19)
revapday |m^3 H2O |amount of water moving from bank storage (line 20)
|into the soil profile or being taken (line 21)
|up by plant roots in the bank storage zone (line 22)
rtwtr |m^3 H2O |water leaving reach on day (line 23)
qdbank |m^3 H2O |streamflow contribution from bank storage (line 24)
sedrch |metric tons |sediment transported out of reach on day (line 25)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ (line 26)
~ ~ ~ LOCAL DEFINITIONS ~ ~ ~ (line 28)
name |units |definition (line 29)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ (line 30)
ii |none |counter (line 31)
jrch |none |reach number (line 32)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ (line 33)
~ ~ ~ SUBROUTINES/FUNCTIONS CALLED ~ ~ ~ (line 35)
Intrinsic: Min (line 36)
SWAT: rchinit, rtover, rtday, rtmusk, rthourly, rtsed, rthsed, watqual (line 37)
SWAT: noqual, hhwatqual, hhnoqual, rtpest, rthpest (line 38)
SWAT: rchuse, reachout (line 39)
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~ (line 41)
initialize variables for route command loop (line 83)
zero flow out variables (line 86)
  72 ch_d(jrch)%flo_out = 0.
  73 ch_d(jrch)%evap = 0.
  74 jhyd = ch_dat(jrch)%hyd
  75 jsed = ch_dat(jrch)%sed
  76 jnut = ch_dat(jrch)%nut
  78 iwst = ob(icmd)%wst
  79 pet_ch = wst(iwst)%weat%pet
  80 qdbank = 0.
  81 revapday = 0.
  84 call ch_rchinit
  87 ob(icmd)%hd(1) = hz
IF (time%step > 0) THEN Lines 88-92
DO ii = 1, time%step Lines 89-91
  90 ob(icmd)%ts(1,ii) = hz
END DOLine 91
END IFLine 92
route water through reach (line 115)
route water through reach (line 120)
  94 ch(jrch)%vel_chan = 0.
  95 ch(jrch)%dep_chan = 0.
  96 sedrch = 0.
  97 rch_san = 0.
  98 rch_sil = 0.
  99 rch_cla = 0.
 100 rch_sag = 0.
 101 rch_lag = 0.
 102 rch_gra = 0.
 103 wtrin = 0.
 104 chlin = 0.
 105 algin = 0.
 106 orgnin = 0.
 107 ammoin = 0.
 108 nitritin = 0.
 109 nitratin = 0.
 110 orgpin = 0.
 111 dispin = 0.
 112 cbodin = 0.
 113 disoxin = 0.
 114 cinn = 0.
 116 rtwtr_d=0.
 117 rttlc_d=0.
 118 rtevp_d =0.
IF (time%step == 0) THEN Lines 121-138
initialize inflow concentrations (line 124)
 122 rt_delt = 1.
 123 wtrin = ob(icmd)%hin%flo
 126 if (bsn_cc%rte == 0) call ch_rtday
 127 if (bsn_cc%rte == 1) call ch_rtmusk
 129 ben_area = ch_hyd(jhyd)%l *ch_hyd(jhyd)%w
 136 rtwtr_d = rtwtr
 137 rttlc_d = rttlc
 138 rtevp_d = rtevp
END IFLine 138
ELSE Lines 139-161
 140 rt_delt = 1. / time%step
 141 wtrin = ob(icmd)%hin%flo * rt_delt
 142 rtwtr = 0.
DO ii = 1, time%step Lines 143-160
 145 call ch_rtday
 147 rtwtr_d=rtwtr_d+rtwtr
 148 rttlc_d=rttlc_d+ rttlc
 149 rtevp_d =rtevp_d+ rtevp
 153 rch_san = 0.
 155 rch_cla = 0.
 156 rch_sag = 0.
 157 rch_lag = 0.
 158 rch_gra = 0.
END DOLine 160
END IF Line 161
average daily water depth for sandi doty 09/26/07 (line 163)
add transmission losses to bank storage/deep aquifer in subbasin (line 167)
 164 ch(jrch)%dep_chan = rchdep
IF (rttlc > 0.) THEN Lines 168-170
 169 ch(jrch)%bankst = ch(jrch)%bankst + rttlc
END IFLine 170
compute revap from bank storage (line 172)
compute contribution of water in bank storage to streamflow (line 177)
 173 revapday = 0.6 * pet_ch *ch_hyd(jhyd)%l *ch_hyd(jhyd)%w
 174 revapday = Min(revapday, ch(jrch)%bankst)
 175 ch(jrch)%bankst = ch(jrch)%bankst - revapday
 178 qdbank = ch(jrch)%bankst * (1. - ch_hyd(jhyd)%alpha_bnk)
 179 ch(jrch)%bankst = ch(jrch)%bankst - qdbank
 180 rtwtr_d = rtwtr_d + qdbank
IF (time%step > 0) THEN Lines 181-185
DO ii = 1, time%step Lines 182-184
 183 hrtwtr(ii) = hrtwtr(ii) + qdbank / real(time%step)
END DOLine 184
END IFLine 185
IF (ch(jrch)%depch >= ch(jrch)%depprch) THEN Lines 188-189
 189 ch_d(jrch)%ch_dep = ch(jrch)%depch - ch(jrch)%depprch
END IFLine 189
ELSE Lines 190-192
 191 ch_d(jrch)%ch_dep = 0.
END IF Line 192
IF (ch(jrch)%depfp >= ch(jrch)%depprfp) THEN Lines 194-195
 195 ch_d(jrch)%fp_dep = ch(jrch)%depfp - ch(jrch)%depprfp
END IFLine 195
ELSE Lines 196-198
 197 ch_d(jrch)%fp_dep = 0.
END IF Line 198
IF (ch_sed(jsed)%eqn == 0) THEN Lines 200-201
 201 ch_d(jrch)%tot_ssed = sedrch
END IFLine 201
ELSE Lines 202-204
 203 ch_d(jrch)%tot_ssed = rch_sil + rch_cla
END IF Line 204
 206 return
Allocations
n/a
Calls
Procedures Called
List of procedures called by this Subroutine.
ch_rchinit
ch_rtday
ch_rtmusk
Call Graph
Visual representation of procedures called by this Subroutine.
Call graph
channel_control calls ch_rchinit, ch_rtday, ch_rtmusk