cli_precip_control – TestDataProject
cli_precip_control Subroutine
70 statements
Source File
subroutine cli_precip_control(istart)
Called From
n/a
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: istart
Outside Variables and Types
type (5 attributes from time_module)
Attribute Name Description
time%yrs None
time%step None
time%day_end_yr None
time%day None
db_mx%wst None
integer (1 attribute from hydrograph_module)
Attribute Name Description
iwst
|
type(timestep) (1 attribute from hydrograph_module)
Attribute Name Description
ts
type(weather_station) (1 attribute from climate_module)
Attribute Name Description
wst
type(climate_measured_data) (1 attribute from climate_module)
Attribute Name Description
pcp
Uses
basin_module
time_module
hydrograph_module
maximum_data_module
climate_module
I/O
n/a
Local Variables
Type Visibility Attributes Name Initial
integer, public :: iwgn = 0
integer, public :: ipg = 0
integer, public :: ist = 0
integer, public :: yrs_to_start = 0
integer, public :: cur_day = 0
character(len=1), public :: out_bounds = 'n'
Precipitation:
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure. Use mouse wheel to zoom, drag to pan.
Reset Zoom Help
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
DO iwst = 1, db_mx%wst Lines 53-122
set current day to next day (that was previously calculated) (line 55)
sum to get ave annual precip for SWIFT input (line 116)
sum to get ave annual precip for SWIFT input (line 116)
  56 wst(iwst)%weat%precip = wst(iwst)%weat%precip_next
  57 wst(iwst)%weat%precip_next = 0.
  58 wst(iwst)%weat%ts = wst(iwst)%weat%ts_next
  60 iwgn = wst(iwst)%wco%wgn
  61 ipg = wst(iwst)%wco%pgage
IF (wst(iwst)%wco_c%pgage == "sim") THEN Lines 62-68
simulated precip (line 63)
  64 call cli_pgen(iwgn)
IF (time%step > 1) THEN Lines 65-68
  66 call cli_pgenhr
  67 wst(iwst)%weat%precip_next = sum (wst(iwst)%weat%ts(:))
END IFLine 68
END IFLine 68
ELSE Lines 69-114
measured precip (line 70)
check to see if out of bounds (simulation starts before or ends after precip data) (line 71)
  72 out_bounds = "n"
  73 cur_day = time%day + istart
  74 yrs_to_start = time%yrs - pcp(ipg)%yrs_start
  79 call cli_bounds_check (pcp(ipg)%start_day, pcp(ipg)%start_yr,       &
  80 pcp(ipg)%end_day, pcp(ipg)%end_yr, out_bounds)
  81 if (yrs_to_start > pcp(ipg)%end_yr - pcp(ipg)%start_yr + 1) out_bounds = "y"
IF (cur_day > time%day_end_yr) THEN Lines 75-78
  76 cur_day = 1
  77 yrs_to_start = yrs_to_start + 1
END IFLine 78
IF (pcp(ipg)%tstep > 0) THEN Lines 83-99
subdaily precip (line 84)
subdaily precip (line 84)
  88 wst(iwst)%weat%precip_next = 0.
  99 wst(iwst)%weat%precip_next = sum (pcp(ipg)%tss(:,cur_day,time%yrs))
IF (out_bounds == "y") THEN Lines 85-87
  86 wst(iwst)%weat%ts_next = -98.
END IFLine 87
DO ist = 1, time%step Lines 89-98
  90 wst(iwst)%weat%ts_next(ist) = pcp(ipg)%tss(ist,cur_day,time%yrs)
  97 wst(iwst)%weat%precip_next = wst(iwst)%weat%precip_next + wst(iwst)%weat%ts_next(ist)
IF (wst(iwst)%weat%ts_next(ist) <= -97.) THEN Lines 91-96
simulate missing data (line 92)
  93 call cli_pgen(iwgn)
  94 call cli_pgenhr
  95 exit
END IFLine 96
END DOLine 98
END IFLine 99
ELSE Lines 100-113
daily precip (line 101)
daily precip (line 101)
simulate missing data (line 108)
simulate missing data (line 108)
IF (out_bounds == "y") THEN Lines 102-103
 103 wst(iwst)%weat%precip_next = -98.
END IFLine 103
ELSE Lines 104-106
 105 wst(iwst)%weat%precip_next = pcp(ipg)%ts(cur_day, yrs_to_start)
END IF Line 106
IF (wst(iwst)%weat%precip_next <= -97.) THEN Lines 109-112
 110 call cli_pgen(iwgn)
 111 pcp(ipg)%days_gen = pcp(ipg)%days_gen + 1
END IFLine 112
END IF Line 113
END IF Line 114
IF (istart > 0) THEN Lines 117-120
 118 wst(iwst)%precip_aa = wst(iwst)%precip_aa + wst(iwst)%weat%precip
 119 wst(iwst)%pet_aa = wst(iwst)%pet_aa + wst(iwst)%weat%pet
END IFLine 120
END DOLine 122
 124 return
Allocations
n/a
Calls
Procedures Called
List of procedures called by this Subroutine.
cli_pgen
cli_pgenhr
cli_bounds_check
Call Graph
Visual representation of procedures called by this Subroutine.
Variables
Type Visibility Attributes Name Initial
integer, public :: istart
Call graph
cli_precip_control calls cli_bounds_check, cli_pgen, cli_pgenhr