climate_control – test-src-project
climate_control Subroutine
201 statements
Source File
subroutine climate_control()
Uses
basin_module
climate_module
hydrograph_module
maximum_data_module
time_module
Arguments
n/a
I/O
n/a
Outside Variables and Types
integer (4 attributes from climate_module)
Attribute Name Description
ppet_ndays
none |number of days for precip/pet sum
Read more…
ppet_mce
none |current element in precip/pet linked list
Read more…
rndseed
none |random number generator seeds
Read more…
iwst
|
type(wgn_parms) (1 attribute from climate_module)
Attribute Name Description
wgn_pms
type(weather_station) (1 attribute from climate_module)
Attribute Name Description
wst
type(climate_measured_data) (5 attributes from climate_module)
Attribute Name Description
tmp
slr
hmd
wnd
petm
type(timestep) (1 attribute from hydrograph_module)
Attribute Name Description
ts
type (7 attributes from hydrograph_module)
Attribute Name Description
w_temp%airlag_d None
db_mx%wst None
time%end_yr None
time%mo None
time%day None
time%step None
time%yrs None
!! Bang Comments
~ ~ ~ PURPOSE ~ ~ ~ this subroutine controls weather inputs to SWAT. Precipitation and temperature data is read in and the weather generator is called to fill in radiation, wind speed and relative humidity as well as missing precipitation and temperatures. Adjustments for climate changes studies are also made in this subroutine.
~ ~ ~ INCOMING VARIABLES ~ ~ ~ name |units |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ elevp(:) |m |elevation of precipitation gage station elevt(:) |m |elevation of temperature gage station welev(:) |m |elevation of weather station used to compile |weather generator data ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ OUTGOING VARIABLES ~ ~ ~ name |units |definition ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ LOCAL DEFINITIONS ~ ~ ~ name |units |definition ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ SUBROUTINES/FUNCTIONS CALLED ~ ~ ~ Intrinsic: Max, Min SWAT: pmeas, tmeas, smeas, hmeas, wmeas SWAT: pgen, tgen, weatgn, clgen, slrgen, rhgen, wndgen
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~
Temperature: Solar Radiation: Relative Humidity: simple dewpoint eqn from Lawrence 2005. Bull. Amer. Meteor. Soc. Wind Speed: Potential ET: Read in data !! if using a measured data Use HARGREAVES POTENTIAL EVAPOTRANSPIRATION METHOD Update CMI and Precip minus PET 30 day moving sum calculate climatic moisture index - cumulative p/pet Use Hargreaves Potential ET Method subtract the 30 day previous and add the current day precip/pet Calculate air temperature lag day for stream temperature replace current day temperature lag day is the next variable in array Calculate maximum half-hour rainfall fraction Base Zero Heat Units Climate Change Adjustments !!
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure.
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
  66 call cli_precip_control (1)
DO iwst = 1, db_mx%wst Lines 69-95
  70 iwgn = wst(iwst)%wco%wgn
  71 call cli_weatgn(iwgn)
  94 wst(iwst)%weat%tave = (wst(iwst)%weat%tmax + wst(iwst)%weat%tmin) / 2.
IF (wst(iwst)%wco_c%tgage == "sim") THEN Lines 72-73
  73 call cli_tgen(iwgn)
END IFLine 73
ELSE Lines 74-93
  75 ig = wst(iwst)%wco%tgage
  76 out_bounds = "n"
  77 cur_day = time%day
  78 call cli_bounds_check (tmp(ig)%start_day, tmp(ig)%start_yr,       &
  79 tmp(ig)%end_day, tmp(ig)%end_yr, out_bounds)
IF (out_bounds == "y") THEN Lines 80-82
  81 wst(iwst)%weat%tmax = -98.
  82 wst(iwst)%weat%tmin = -98.
END IFLine 82
ELSE Lines 83-87
  84 yrs_to_start = time%yrs - tmp(ig)%yrs_start
  85 wst(iwst)%weat%tmax = tmp(ig)%ts(time%day,yrs_to_start)
  86 wst(iwst)%weat%tmin = tmp(ig)%ts2(time%day,yrs_to_start)
END IF Line 87
IF (wst(iwst)%weat%tmax <= -97. .or. wst(iwst)%weat%tmin <= -97.) THEN Lines 88-92
  89 call cli_weatgn(iwgn)
  90 call cli_tgen(iwgn)
  91 tmp(ig)%days_gen = tmp(ig)%days_gen + 1
END IFLine 92
END IF Line 93
END DOLine 95
DO iwst = 1, db_mx%wst Lines 98-120
  99 iwgn = wst(iwst)%wco%wgn
 100 call cli_clgen(iwgn)
IF (wst(iwst)%wco_c%sgage== "sim") THEN Lines 101-102
 102 call cli_slrgen(iwgn)
END IFLine 102
ELSE Lines 103-119
 104 ig = wst(iwst)%wco%sgage
 105 out_bounds = "n"
 106 cur_day = time%day
 107 call cli_bounds_check (slr(ig)%start_day, slr(ig)%start_yr,       &
 108 slr(ig)%end_day, slr(ig)%end_yr, out_bounds)
IF (out_bounds == "y") THEN Lines 109-110
 110 wst(iwst)%weat%solrad = -98.
END IFLine 110
ELSE Lines 111-114
 112 yrs_to_start = time%yrs - slr(ig)%yrs_start
 113 wst(iwst)%weat%solrad = slr(ig)%ts(time%day,yrs_to_start)
END IF Line 114
IF (wst(iwst)%weat%solrad <= -97.) THEN Lines 115-118
 116 call cli_slrgen(iwgn)
 117 slr(ig)%days_gen = slr(ig)%days_gen + 1
END IFLine 118
END IF Line 119
END DOLine 120
DO iwst = 1, db_mx%wst Lines 123-146
 124 iwgn = wst(iwst)%wco%wgn
 145 wst(iwst)%weat%dewpt = wst(iwst)%weat%tave - (1. - wst(iwst)%weat%rhum) / 5.
IF (wst(iwst)%wco_c%hgage == "sim") THEN Lines 125-126
 126 call cli_rhgen(iwgn)
END IFLine 126
ELSE Lines 127-143
 128 ig = wst(iwst)%wco%hgage
 129 out_bounds = "n"
 130 cur_day = time%day
 131 call cli_bounds_check (hmd(ig)%start_day, hmd(ig)%start_yr,       &
 132 hmd(ig)%end_day, hmd(ig)%end_yr, out_bounds)
IF (out_bounds == "y") THEN Lines 133-134
 134 wst(iwst)%weat%rhum = -98.
END IFLine 134
ELSE Lines 135-138
 136 yrs_to_start = time%yrs - hmd(ig)%yrs_start
 137 wst(iwst)%weat%rhum = hmd(ig)%ts(time%day,yrs_to_start)
END IF Line 138
IF (wst(iwst)%weat%rhum <= -97.) THEN Lines 139-142
 140 call cli_rhgen(iwgn)
 141 hmd(ig)%days_gen = hmd(ig)%days_gen + 1
END IFLine 142
END IF Line 143
END DOLine 146
DO iwst = 1, db_mx%wst Lines 149-170
 150 iwgn = wst(iwst)%wco%wgn
IF (wst(iwst)%wco_c%wgage == "sim") THEN Lines 151-152
 152 call cli_wndgen(iwgn)
END IFLine 152
ELSE Lines 153-169
 154 ig = wst(iwst)%wco%wgage
 155 out_bounds = "n"
 156 cur_day = time%day
 157 call cli_bounds_check (wnd(ig)%start_day, wnd(ig)%start_yr,       &
 158 wnd(ig)%end_day, wnd(ig)%end_yr, out_bounds)
IF (out_bounds == "y") THEN Lines 159-160
 160 wst(iwst)%weat%windsp = -98.
END IFLine 160
ELSE Lines 161-164
 162 yrs_to_start = time%yrs - wnd(ig)%yrs_start
 163 wst(iwst)%weat%windsp = wnd(ig)%ts(time%day,yrs_to_start)
END IF Line 164
IF (wst(iwst)%weat%windsp <= -97.) THEN Lines 165-168
 166 call cli_wndgen(iwgn)
 167 wnd(ig)%days_gen = wnd(ig)%days_gen + 1
END IFLine 168
END IF Line 169
END DOLine 170
DO iwst = 1, db_mx%wst Lines 173-201
 174 iwgn = wst(iwst)%wco%wgn
 175 ig = wst(iwst)%wco%petgage
IF (ig > 0) THEN Lines 177-200
 178 out_bounds = "n"
 179 cur_day = time%day
 180 call cli_bounds_check (petm(ig)%start_day, petm(ig)%start_yr,       &
 181 petm(ig)%end_day, petm(ig)%end_yr, out_bounds)
IF (out_bounds == "y") THEN Lines 182-183
 183 wst(iwst)%weat%pet = -98.
END IFLine 183
ELSE Lines 184-187
 185 yrs_to_start = time%yrs - petm(ig)%yrs_start
 186 wst(iwst)%weat%pet = petm(ig)%ts(time%day,yrs_to_start)
END IF Line 187
IF (wst(iwst)%weat%pet <= -97.) THEN Lines 188-199
 190 ramm = wst(iwst)%weat%solradmx * 37.59 / 30.
IF (wst(iwst)%weat%tmax > wst(iwst)%weat%tmin) THEN Lines 191-195
 192 xl = 2.501 - 2.361e-3 * wst(iwst)%weat%tave
 193 wst(iwst)%weat%pet = .0023 * (ramm / xl) * (wst(iwst)%weat%tave      &
 194 + 17.8) * (wst(iwst)%weat%tmax - wst(iwst)%weat%tmin) ** 0.5
 195 wst(iwst)%weat%pet = Max(0., wst(iwst)%weat%pet)
END IFLine 195
ELSE Lines 196-198
 197 wst(iwst)%weat%pet = 0.
END IF Line 198
END IFLine 199
END IFLine 200
END DOLine 201
 204 ppet_mce = ppet_mce + 1
 205 if (ppet_mce > ppet_ndays) ppet_mce = 1
DO iwst = 1, db_mx%wst Lines 206-236
 209 ramm = wst(iwst)%weat%solradmx * 37.59 / 30.
 222 iwgn = wst(iwst)%wco%wgn
 223 wgn_pms(iwgn)%precip_sum = wgn_pms(iwgn)%precip_sum + wst(iwst)%weat%precip - wgn_pms(iwgn)%precip_mce(ppet_mce)
 224 wgn_pms(iwgn)%pet_sum = wgn_pms(iwgn)%pet_sum + wst(iwst)%weat%pet - wgn_pms(iwgn)%pet_mce(ppet_mce)
 225 wgn_pms(iwgn)%p_pet_rto = wgn_pms(iwgn)%precip_sum / wgn_pms(iwgn)%pet_sum
 226 wgn_pms(iwgn)%precip_mce(ppet_mce) = wst(iwst)%weat%precip
 227 wgn_pms(iwgn)%pet_mce(ppet_mce) = wst(iwst)%weat%pet
 231 wst(iwst)%tlag(wst(iwst)%tlag_mne) = wst(iwst)%weat%tave
 233 wst(iwst)%tlag_mne = wst(iwst)%tlag_mne + 1
 234 if (wst(iwst)%tlag_mne > w_temp%airlag_d) wst(iwst)%tlag_mne = 1
 235 wst(iwst)%airlag_temp = wst(iwst)%tlag(wst(iwst)%tlag_mne)
IF (wst(iwst)%weat%tmax > wst(iwst)%weat%tmin) THEN Lines 210-214
 211 xl = 2.501 - 2.361e-3 * wst(iwst)%weat%tave
 212 wst(iwst)%weat%pet = .0023 * (ramm / xl) * (wst(iwst)%weat%tave      &
 213 + 17.8) * (wst(iwst)%weat%tmax - wst(iwst)%weat%tmin) ** 0.5
 214 wst(iwst)%weat%pet = Max(0.01, wst(iwst)%weat%pet)
END IFLine 214
ELSE Lines 215-217
 216 wst(iwst)%weat%pet = 0.01
END IF Line 217
IF (wst(iwst)%weat%pet > 0.1) THEN Lines 218-220
 219 wst(iwst)%weat%ppet = wst(iwst)%weat%ppet + wst(iwst)%weat%precip / wst(iwst)%weat%pet
END IFLine 220
END DOLine 236
DO iwst = 1, db_mx%wst Lines 239-245
 240 iwgn = wst(iwst)%wco%wgn
 241 half_hr_mn = 0.02083
 242 xx = (-125. / (wst(iwst)%weat%precip + 5.))
 243 half_hr_mx = 1. - Exp(xx)
 244 wst(iwst)%weat%precip_half_hr = Atri(half_hr_mn, wgn_pms(iwgn)%amp_r(time%mo), half_hr_mx, rndseed(10,iwgn))
END DOLine 245
DO iwst = 1, db_mx%wst Lines 248-257
 249 iwgn = wst(iwst)%wco%wgn
 256 if (time%end_yr == 1) wst(iwst)%weat%phubase0 = 0.
IF (wgn_pms(iwgn)%phutot > 0.) THEN Lines 250-252
 251 if (wst(iwst)%weat%tave > 0.) wst(iwst)%weat%phubase0 = wst(iwst)%weat%phubase0   &
 252 + wst(iwst)%weat%tave / wgn_pms(iwgn)%phutot
END IFLine 252
ELSE Lines 253-255
 254 wst(iwst)%weat%phubase0 = 0.
END IF Line 255
END DOLine 257
DO iwst = 1, db_mx%wst Lines 260-276
 261 wst(iwst)%weat%precip = wst(iwst)%weat%precip * (1. + wst(iwst)%rfinc(time%mo) / 100.)
 262 if (wst(iwst)%weat%precip < 0.) wst(iwst)%weat%precip = 0.
 269 wst(iwst)%weat%tmax = wst(iwst)%weat%tmax + wst(iwst)%tmpinc(time%mo)
 270 wst(iwst)%weat%tmin = wst(iwst)%weat%tmin + wst(iwst)%tmpinc(time%mo)
 271 wst(iwst)%weat%solrad = wst(iwst)%weat%solrad + wst(iwst)%radinc(time%mo)
 272 wst(iwst)%weat%solrad = Max(0.,wst(iwst)%weat%solrad)
 273 wst(iwst)%weat%rhum = wst(iwst)%weat%rhum + wst(iwst)%huminc(time%mo)
 274 wst(iwst)%weat%rhum = Max(0.01,wst(iwst)%weat%rhum)
 275 wst(iwst)%weat%rhum = Min(0.99,wst(iwst)%weat%rhum)
IF (time%step > 1) THEN Lines 263-268
DO ii = 1, time%step Lines 264-267
 265 wst(iwst)%weat%ts(ii) = wst(iwst)%weat%ts(ii) * (1. + wst(iwst)%rfinc(time%mo) / 100.)
 266 if (wst(iwst)%weat%ts(ii) < 0.) wst(iwst)%weat%ts(ii) = 0.
END DOLine 267
END IFLine 268
END DOLine 276
 278 return
Allocations
n/a
Calls
Calls
Procedures called by this subroutine.
Local Variables
Type Visibility Attributes Name Initial
integer, private :: ii
integer, private :: iyp
integer, private :: idap
real, private :: petmeas
real, private :: half_hr_mn
real, private :: half_hr_mx
integer, private :: iwgn
integer, private :: ipet
integer, private :: ig
integer, private :: yrs_to_start
integer, private :: cur_day
real, private :: ramm
real, private :: xl
real, private :: atri
integer, private :: ifirstpet
real, private :: xx
Call graph
climate_control calls cli_bounds_check, cli_clgen, cli_precip_control, cli_rhgen, cli_slrgen, cli_tgen, cli_weatgn, cli_wndgen