command – TestDataProject
command Subroutine
474 statements
Source File
subroutine command()
Called From
n/a
Arguments
n/a
Outside Variables and Types
type (44 attributes from basin_module)
Attribute Name Description
bsn_cc%gwflow None
bsn_cc%swift_out None
pco%cb_hru%d None
pco%cb_vars_hru%y None
pco%cb_hru%y None
pco%nyskip None
pco%cb_vars_hru%m None
pco%fdcout None
pco%cb_hru%m None
pco%cb_vars_hru%d None
time%yrs None
time%end_mo None
time%day None
time%step None
time%end_yr None
time%yrc None
time%mo None
cs_db%num_salts None
cs_db%num_cs None
cs_db%num_pests None
cs_db%num_tot None
ht1%flo None
hdsep1%flo_satex None
hdsep1%flo_latq None
hdsep1%flo_tile None
hdsep1%flo_surq None
hdsep1%flo_satexsw None
hdsep1%flo_swgw None
hdsep1%flo_gwsw None
sp_ob%recall None
sp_ob%hru_lte None
sp_ob%gwflow None
sp_ob%chandeg None
sp_ob%aqu None
sp_ob%chan None
sp_ob%hru None
sp_ob%res None
sp_ob%ru None
sp_ob1%objs None
db_mx%aqu_elem None
db_mx%lsu_elem None
db_mx%lsu_out None
db_mx%mallo_db None
db_mx%wallo_db None
real (3 attributes from sd_channel_module)
Attribute Name Description
peakrate
hyd_sep_array
peakr
type(swatdeg_channel_dynamic) (1 attribute from sd_channel_module)
Attribute Name Description
sd_ch
type(sd_ch_output) (1 attribute from sd_channel_module)
Attribute Name Description
chsd_d
type(constituent_mass) (4 attributes from constituent_mass_module)
Attribute Name Description
hcs1
hcs2
hcs3
hin_csz
type(all_constituent_hydrograph) (1 attribute from constituent_mass_module)
Attribute Name Description
obcs
integer (10 attributes from constituent_mass_module)
Attribute Name Description
obcs_alloc
jrch
none |reach number
Read more…
isdch
|
icmd
|
isd_chsur
|
ihru
none |HRU number
Read more…
gw_daycount
!simulation day counter (for pumping time series)
hydsep_flag
out_hyd_sep
iru
none |counter
Read more…
type(hyd_output) (8 attributes from hydrograph_module)
Attribute Name Description
hd
rec_d
hz
aqu
res
ch_in_d
ch_out_d
dr
delivery ratio for objects- chan, res, lu
type(object_connectivity) (1 attribute from hydrograph_module)
Attribute Name Description
ob
type(recall_hydrograph_inputs) (1 attribute from hydrograph_module)
Attribute Name Description
recall
type(hydrologic_response_unit) (1 attribute from hru_module)
Attribute Name Description
hru
type(ru_parameters) (1 attribute from ru_module)
Attribute Name Description
ru
Uses
basin_module
sd_channel_module
time_module
constituent_mass_module
hydrograph_module
soil_module
maximum_data_module
aquifer_module
reservoir_module
organic_mineral_mass_module
channel_module
hru_module
gwflow_module
hru_lte_module
ru_module
I/O
I/O units used in this subroutine.
Unit Type Filename
unit_out_hyd_sep Output not specified
Local Variables
Type Visibility Attributes Name Initial
real, public, dimension(time%step) :: hyd_flo
integer, public :: in = 0
integer, public :: iob = 0
integer, public :: iday = 0
integer, public :: isd = 0
integer, public :: ires = 0
integer, public :: irec = 0
integer, public :: iout = 0
integer, public :: ihtyp = 0
integer, public :: iaq = 0
integer, public :: j = 0
integer, public :: nly = 0
integer, public :: ly = 0
integer, public :: ihyd = 0
integer, public :: idr = 0
integer, public :: iwro = 0
real, public :: conv = 0.
real, public :: frac_in = 0.
integer, public :: ts1 = 0
integer, public :: ts2 = 0
integer, public :: i_count = 0
integer, public :: i_mfl = 0
integer, public :: i_chan = 0
real, public :: sumflo = 0.
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure. Use mouse wheel to zoom, drag to pan.
Reset Zoom Help
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
~ ~ ~ PURPOSE ~ ~ ~ (line 3)
for every day of simulation, this subroutine steps through the command (line 4)
lines in the watershed configuration (.fig) file. Depending on the (line 5)
command code on the .fig file line, a command loop is accessed (line 6)
~ ~ ~ SUBROUTINES/FUNCTIONS CALLED ~ ~ ~ (line 7)
SWAT: subbasin, route, routres, transfer, recmon (line 8)
SWAT: recepic, save, recday, recyear (line 9)
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~ (line 11)
  55 icmd = sp_ob1%objs
DO while (icmd /= 0)
  75 ob(icmd)%hin = hz
  76 ob(icmd)%hin_sur = hz
  77 ob(icmd)%hin_lat = hz
  78 ob(icmd)%hin_til = hz
  79 ht1 = hz
  86 hcs1 = hin_csz
  87 hcs2 = hin_csz
  88 hcs3 = hin_csz
  89 ob(icmd)%tsin = 0.
  90 ob(icmd)%peakrate = 0.
  91 hyd_flo = 0.
IF (ob(icmd)%typ == "hru" .or. ob(icmd)%typ == "ru") THEN Lines 59-62
hru and ru can have hyrdographs that lag into next day (line 60)
  61 ob(icmd)%day_cur = ob(icmd)%day_cur + 1
  62 if (ob(icmd)%day_cur > ob(icmd)%day_max) ob(icmd)%day_cur = 1
END IFLine 62
ELSE Lines 63-69
assume only one day is saved for all other objects (line 64)
  65 ob(icmd)%day_cur = 1
  67 ob(icmd)%day_cur = ob(icmd)%day_cur + 1
  68 if (ob(icmd)%day_cur > ob(icmd)%day_max) ob(icmd)%day_cur = 1
END IF Line 69
IF (cs_db%num_tot > 0 .and. obcs_alloc(icmd).eq.1) THEN Lines 80-85
  81 obcs(icmd)%hin = hin_csz
  82 obcs(icmd)%hin_sur = hin_csz
  83 obcs(icmd)%hin_lat = hin_csz
  84 obcs(icmd)%hin_til = hin_csz
END IFLine 85
IF (ob(icmd)%rcv_tot > 0) THEN
write object output for entire simulation (line 419)
print all output files (line 422)
print all output files (line 422)
 420 call obj_output
DO in = 1, ob(icmd)%rcv_tot Lines 94-417
multiply inflow hyd by the fraction of incoming (line 238)
add flow hydrographs for each incoming object (line 240)
  95 iob = ob(icmd)%obj_in(in)
  96 ihyd = ob(icmd)%ihtyp_in(in)
  97 frac_in = ob(icmd)%frac_in(in)
  98 ob(icmd)%peakrate = ob(iob)%peakrate
 171 ht1 = frac_in * ob(iob)%hd(ihyd)
 172 ob(icmd)%hin = ob(icmd)%hin + ht1
 175 hdsep1%flo_surq = frac_in * (ob(iob)%hdsep%flo_surq)
 176 hdsep1%flo_latq = frac_in * (ob(iob)%hdsep%flo_latq)
 177 hdsep1%flo_gwsw = frac_in * (ob(iob)%hdsep%flo_gwsw)
 178 hdsep1%flo_swgw = frac_in * (ob(iob)%hdsep%flo_swgw)
 179 hdsep1%flo_satex = frac_in * (ob(iob)%hdsep%flo_satex)
 180 hdsep1%flo_satexsw = frac_in * (ob(iob)%hdsep%flo_satexsw)
 181 hdsep1%flo_tile = frac_in * (ob(iob)%hdsep%flo_tile)
 182 ob(icmd)%hdsep_in%flo_surq = ob(icmd)%hdsep_in%flo_surq + hdsep1%flo_surq
 183 ob(icmd)%hdsep_in%flo_latq = ob(icmd)%hdsep_in%flo_latq + hdsep1%flo_latq
 184 ob(icmd)%hdsep_in%flo_gwsw = ob(icmd)%hdsep_in%flo_gwsw + hdsep1%flo_gwsw
 185 ob(icmd)%hdsep_in%flo_swgw = ob(icmd)%hdsep_in%flo_swgw + hdsep1%flo_swgw
 186 ob(icmd)%hdsep_in%flo_satex = ob(icmd)%hdsep_in%flo_satex + hdsep1%flo_satex
 187 ob(icmd)%hdsep_in%flo_satexsw = ob(icmd)%hdsep_in%flo_satexsw + hdsep1%flo_satexsw
 188 ob(icmd)%hdsep_in%flo_tile = ob(icmd)%hdsep_in%flo_tile + hdsep1%flo_tile
 195 ob(icmd)%hin_d(in) = ht1        !for hydrograph output
 203 iday = ob(iob)%day_cur
 239 hyd_flo = frac_in * hyd_flo
 241 ob(icmd)%tsin = ob(icmd)%tsin + hyd_flo
 245 end do    ! in = 1, ob(icmd)%rcv_tot
 248 if (ob(icmd)%typ == "hru" .or. ob(icmd)%typ == "ru") then  !only convert hru and subbasin hyds for routing
 249 conv = ob(icmd)%area_ha
 250 ob(icmd)%hin_sur = ob(icmd)%hin_sur / conv
 251 ob(icmd)%hin_sur%flo = ob(icmd)%hin_sur%flo / 10.      ! m3/10*ha = mm
 252 ob(icmd)%hin_lat = ob(icmd)%hin_lat / conv
 253 ob(icmd)%hin_lat%flo = ob(icmd)%hin_lat%flo / 10.      ! m3/10*ha = mm
 254 ob(icmd)%hin_til = ob(icmd)%hin_til / conv
 255 ob(icmd)%hin_til%flo = ob(icmd)%hin_til%flo / 10.      ! m3/10*ha = mm
 415 icmd = ob(icmd)%cmd_next
IF (ob(icmd)%typ == "hru" .or. ob(icmd)%typ == "ru" .or. ob(icmd)%typ == "hru_lte") THEN Lines 102-159
if incoming object is not an hru or ru, send total hyd to surface runoff (line 104)
 105 if (ob(icmd)%obtyp_in(in) == "hru" .or. ob(icmd)%obtyp_in(in) == "ru" .or.          &
 106 ob(icmd)%obtyp_in(in) == "hru_lte") then
IF (ob(icmd)%htyp_in(in) == "tot") THEN Lines 108-124
 111 ob(icmd)%hin_sur = ob(icmd)%hin_sur + frac_in * ob(iob)%hd(3)
 116 ob(icmd)%hin_til = ob(icmd)%hin_til + frac_in * ob(iob)%hd(5)
 121 ob(icmd)%hin_lat = ob(icmd)%hin_lat + frac_in * ob(iob)%hd(4)
IF (cs_db%num_tot > 0 .and. obcs_alloc(icmd).eq.1) THEN Lines 112-114
 113 obcs(icmd)%hin_sur(1) = obcs(icmd)%hin_sur(1) + frac_in * obcs(iob)%hd(3)
END IFLine 114
IF (cs_db%num_tot > 0 .and. obcs_alloc(icmd).eq.1) THEN Lines 117-119
 118 obcs(icmd)%hin_til(1) = obcs(icmd)%hin_til(1) + frac_in * obcs(iob)%hd(5)
END IFLine 119
IF (cs_db%num_tot > 0 .and. obcs_alloc(icmd).eq.1) THEN Lines 122-124
 123 obcs(icmd)%hin_lat(1) = obcs(icmd)%hin_lat(1) + frac_in * obcs(iob)%hd(4)
END IFLine 124
END IFLine 124
ELSE Lines 125-159
SELECT CASE (ob(icmd)%htyp_in(in)) Lines 127-158
IF (cs_db%num_tot > 0 .and. obcs_alloc(icmd).eq.1) THEN Lines 131-133
 132 obcs(icmd)%hin_til(1) = obcs(icmd)%hin_til(1) + frac_in * obcs(iob)%hd(ihyd)
END IFLine 133
IF (cs_db%num_tot > 0 .and. obcs_alloc(icmd).eq.1) THEN Lines 137-139
 138 obcs(icmd)%hin_sur(1) = obcs(icmd)%hin_sur(1) + frac_in * obcs(iob)%hd(ihyd)
END IFLine 139
IF (cs_db%num_tot > 0 .and. obcs_alloc(icmd).eq.1) THEN Lines 143-145
 144 obcs(icmd)%hin_lat(1) = obcs(icmd)%hin_lat(1) + frac_in * obcs(iob)%hd(ihyd)
END IFLine 145
IF (cs_db%num_tot > 0 .and. obcs_alloc(icmd).eq.1) THEN Lines 149-151
 150 obcs(icmd)%hin_til(1) = obcs(icmd)%hin_til(1) + frac_in * obcs(iob)%hd(ihyd)
END IFLine 151
IF (cs_db%num_tot > 0 .and. obcs_alloc(icmd).eq.1) THEN Lines 155-157
 156 obcs(icmd)%hin_aqu(1) = obcs(icmd)%hin_aqu(1) + frac_in * obcs(iob)%hd(ihyd)
END IFLine 157
END SELECTLine 158
END IF Line 159
END IFLine 159
ELSE Lines 160-166
 162 ob(icmd)%hin_sur = ob(icmd)%hin_sur + frac_in * ob(iob)%hd(1)
IF (cs_db%num_tot > 0 .and. obcs_alloc(icmd).eq.1) THEN Lines 163-165
 164 obcs(icmd)%hin_sur(1) = obcs(icmd)%hin_sur(1) + frac_in * obcs(iob)%hd(1)
END IFLine 165
END IF Line 166
IF (cs_db%num_tot > 0 .and. obcs_alloc(icmd).eq.1) THEN Lines 191-194
 192 hcs1 = frac_in * obcs(iob)%hd(ihyd)
 193 obcs(icmd)%hin(1) = obcs(icmd)%hin(1) + hcs1
END IFLine 194
IF (cs_db%num_tot > 0 .and. obcs_alloc(icmd).eq.1) THEN Lines 196-198
 197 obcs(icmd)%hcsin_d(in) = hcs1   !for constituent hydrograph output
END IFLine 198
IF (ob(iob)%typ == "hru" .or. ob(iob)%typ == "ru") THEN Lines 204-217
SELECT CASE (ob(icmd)%htyp_in(in)) Lines 205-216
END SELECTLine 216
END IFLine 217
SELECT CASE (ob(iob)%typ) Lines 218-236
END SELECTLine 236
SELECT CASE (ob(icmd)%typ) Lines 260-394
DO i_mfl = 1,sp_ob%gwflow Lines 279-281
 280 icmd = icmd + 1
END DOLine 281
IF (ob(icmd)%rcv_tot > 0) THEN Lines 298-300
 299 call res_control (ires)
END IFLine 300
SELECT CASE (recall(irec)%typ) Lines 304-334
IF (time%yrc >= recall(irec)%start_yr .and. time%yrc <= recall(irec)%end_yr) THEN Lines 311-316
 312 ob(icmd)%hd(1) = recall(irec)%hd(time%day,time%yrs)
IF (recall(irec)%hd(time%day,time%yrs)%flo < 0) THEN Lines 314-316
 315 call recall_nut(irec)
END IFLine 316
END IFLine 316
ELSE Lines 317-319
 318 ob(icmd)%hd(1) = hz
END IF Line 319
IF (time%yrc >= recall(irec)%start_yr .and. time%yrc <= recall(irec)%end_yr) THEN Lines 321-322
 322 ob(icmd)%hd(1) = recall(irec)%hd(time%mo,time%yrs)
END IFLine 322
ELSE Lines 323-325
 324 ob(icmd)%hd(1) = hz
END IF Line 325
IF (time%yrc >= recall(irec)%start_yr .or. time%yrc <= recall(irec)%end_yr) THEN Lines 327-328
 328 ob(icmd)%hd(1) = recall(irec)%hd(1,time%yrs)
END IFLine 328
ELSE Lines 329-331
 330 ob(icmd)%hd(1) = hz
END IF Line 331
END SELECTLine 334
IF (cs_db%num_tot > 0) THEN Lines 346-350
 347 idr = ob(iob)%props
 349 call constit_hyd_mult (icmd, idr)
END IFLine 350
IF (cs_db%num_tot > 0 .and. obcs_alloc(icmd).eq.1) THEN Lines 354-356
 355 obcs(icmd)%hd(1) = obcs(icmd)%hin(1) !rtb salt/cs
END IFLine 356
IF (sd_ch(isdch)%chl > 1.e-3) THEN Lines 361-362
 362 call sd_channel_control3
END IFLine 362
ELSE Lines 363-392
artificial channel - length=0 - no transformations (line 364)
output channel morphology (line 372)
 365 ob(icmd)%hd(1) = ob(icmd)%hin
 367 ch_in_d(isdch) = ht1                        !set inflow om hydrograph
 368 chsd_d(isdch)%flo_in = ht1%flo / 86400.     !flow for morphology output
 369 ch_in_d(isdch)%flo = ht1%flo / 86400.       !flow for om output
 370 ch_out_d(isdch) = ht1                       !set inflow om hydrograph
 371 ch_out_d(isdch)%flo = ht1%flo / 86400.      !m3 -> m3/s
 373 chsd_d(isdch)%flo = ht1%flo / 86400.        !adjust if overbank flooding is moved to landscape
 374 chsd_d(isdch)%peakr = 0.
 375 chsd_d(isdch)%sed_in = ob(icmd)%hin%sed
 376 chsd_d(isdch)%sed_out = ob(icmd)%hin%sed
 377 chsd_d(isdch)%washld = 0.
 378 chsd_d(isdch)%bedld = 0.
 379 chsd_d(isdch)%dep = 0.
 380 chsd_d(isdch)%deg_btm = .0
 381 chsd_d(isdch)%deg_bank = 0.
 382 chsd_d(isdch)%hc_sed = 0.
 383 chsd_d(isdch)%width = sd_ch(isdch)%chw
 384 chsd_d(isdch)%depth = sd_ch(isdch)%chd
 385 chsd_d(isdch)%slope = sd_ch(isdch)%chs
 386 chsd_d(isdch)%deg_btm_m = 0.
 387 chsd_d(isdch)%deg_bank_m = 0.
 388 chsd_d(isdch)%hc_m = 0.
IF (cs_db%num_tot > 0 .and. obcs_alloc(icmd).eq.1) THEN Lines 389-391
 390 obcs(icmd)%hd(1) = obcs(icmd)%hin(1)
END IFLine 391
END IF Line 392
END SELECTLine 394
IF (pco%fdcout == "y" .and. ob(icmd)%typ == "chandeg") THEN Lines 395-401
compute flashiness index (line 397)
 396 call flow_dur_curve
 398 ob(icmd)%flash_idx%sum_q_q1 = ob(icmd)%flash_idx%sum_q_q1 + (ob(icmd)%hd(1)%flo - ob(icmd)%flash_idx%q_prev)
 399 ob(icmd)%flash_idx%q_prev = ob(icmd)%hd(1)%flo
 400 ob(icmd)%flash_idx%sum_q = ob(icmd)%flash_idx%sum_q + ob(icmd)%hd(1)%flo
END IFLine 401
IF (time%yrs > pco%nyskip) THEN Lines 404-412
IF (ob(icmd)%src_tot > 0) THEN Lines 405-411
DO iout = 1, ob(icmd)%src_tot Lines 406-410
 407 ihtyp = ob(icmd)%ihtyp_out(iout)
 408 ht1 = ob(icmd)%frac_out(iout) * ob(icmd)%hd(ihtyp)
 409 call hydout_output (iout)
END DOLine 410
END IFLine 411
END IFLine 412
END DOLine 417
IF (time%yrs > pco%nyskip) THEN
print water allocation output (line 425)
print manure allocation output (line 430)
DO iwro =1, db_mx%wallo_db Lines 426-428
 427 call water_allocation_output (iwro)
END DOLine 428
DO iwro =1, db_mx%mallo_db Lines 431-434
 432 call manure_source_output (iwro)
 433 call manure_demand_output (iwro)
END DOLine 434
DO isd = 1, sp_ob%hru_lte Lines 436-438
 437 call hru_lte_output (isd)
END DOLine 438
DO ihru = 1, sp_ob%hru
 441 call hru_output (ihru)
 442 call hru_carbon_output (ihru)
 448 if (cs_db%num_cs > 0) then !rtb cs
 449 call wet_cs_output(ihru)
 456 if (cs_db%num_salts > 0) then !rtb salt
 457 call hru_salt_output(ihru)
 459 if (cs_db%num_cs > 0) then !rtb cs
 460 call hru_cs_output(ihru)
 470 if (pco%cb_hru%d == "y") call soil_nutcarb_write(" d")
 471 if (pco%cb_hru%d == "l") call soil_nutcarb_write("dl")
 472 if (pco%cb_hru%m == "y" .and. time%end_mo == 1) call soil_nutcarb_write(" m")
 473 if (pco%cb_hru%m == "l" .and. time%end_mo == 1) call soil_nutcarb_write("ml")
 474 if (pco%cb_hru%y == "y" .and. time%end_yr == 1) call soil_nutcarb_write(" y")
 475 if (pco%cb_hru%y == "l" .and. time%end_yr == 1) call soil_nutcarb_write("yl")
 477 if (pco%cb_vars_hru%d == "y") call soil_carbvar_write("d")
 478 if (pco%cb_vars_hru%m == "y" .and. time%end_mo == 1) call soil_carbvar_write("m")
 479 if (pco%cb_vars_hru%y == "y" .and. time%end_yr == 1) call soil_carbvar_write("y")
 482 end do      ! hru loop
 549 call hydin_output   !if all output is no, then don"t call
 551 if (sp_ob%chandeg > 0 .and. cs_db%num_pests > 0) call basin_ch_pest_output
 552 if (sp_ob%res > 0 .and. cs_db%num_pests > 0) call basin_res_pest_output
 553 if (sp_ob%hru > 0 .and. cs_db%num_pests > 0) call basin_ls_pest_output
 554 if (sp_ob%aqu > 0 .and. cs_db%num_pests > 0) call basin_aqu_pest_output
 555 if (db_mx%lsu_elem > 0) call basin_output
 556 if (db_mx%lsu_out > 0) call lsu_output
 557 if (db_mx%aqu_elem > 0) call basin_aquifer_output
 559 if (sp_ob%res > 0) call basin_reservoir_output
 560 if (sp_ob%chan > 0) call basin_channel_output
 561 if (sp_ob%chandeg > 0) call basin_chanmorph_output
 562 if (sp_ob%chandeg > 0) call basin_chanbud_output
 563 if (sp_ob%chandeg > 0) call basin_sdchannel_output
 564 if (sp_ob%recall > 0) call basin_recall_output
 572 if(cs_db%num_salts > 0) call salt_balance !rtb salt
 573 if(cs_db%num_cs > 0) call cs_balance !rtb cs
 577 gw_daycount = gw_daycount + 1
 589 icmd = sp_ob1%objs
 608 102   format(i6,11x,i3,8x,i5,5x,1000(f16.4))
 609 103   format(4i6,2i8,2x,a,35f12.3)
 612 return
 613 end
IF (hru(ihru)%dbs%surf_stor > 0) THEN Lines 443-447
 444 call wetland_output(ihru)
 445 if (cs_db%num_salts > 0) then !rtb salt
 446 call wet_salt_output(ihru)
END IFLine 447
IF (cs_db%num_tot > 0) THEN Lines 452-455
 453 call hru_pesticide_output (ihru)
 454 call hru_pathogen_output (ihru)
END IFLine 455
IF (bsn_cc%swift_out == 1) THEN Lines 463-468
 464 icmd = hru(ihru)%obj_no
DO ihyd = 1, 5 Lines 465-467
 466 ob(icmd)%hd_aa(ihyd) = ob(icmd)%hd_aa(ihyd) + ob(icmd)%hd(ihyd)
END DOLine 467
END IFLine 468
DO iaq = 1, sp_ob%aqu Lines 484-495
 485 call aquifer_output (iaq)
 486 if (cs_db%num_salts > 0) then !rtb salt
 487 call aqu_salt_output (iaq)
 489 if (cs_db%num_cs > 0) then !rtb cs
 490 call aqu_cs_output(iaq)
IF (cs_db%num_tot > 0) THEN Lines 492-494
 493 call aqu_pesticide_output (iaq)
END IFLine 494
END DOLine 495
DO jrch = 1, sp_ob%chan Lines 497-499
 498 call channel_output (jrch)
END DOLine 499
DO jrch = 1, sp_ob%chandeg Lines 501-515
 502 call sd_chanmorph_output (jrch)
 503 call sd_chanbud_output (jrch)
 504 call sd_channel_output (jrch)
 509 if (cs_db%num_salts > 0) then !rtb salt
 510 call ch_salt_output (jrch)
IF (cs_db%num_tot > 0) THEN Lines 505-508
 506 call cha_pesticide_output (jrch)
END IFLine 508
IF (cs_db%num_cs > 0) THEN Lines 512-514
 513 call ch_cs_output (jrch) !rtb cs
END IFLine 514
END DOLine 515
IF (cs_db%num_cs > 0) THEN Lines 516-518
 517 call cs_str_output !rtb cs
END IFLine 518
DO j = 1, sp_ob%res Lines 521-533
 522 call reservoir_output(j)
 528 if (cs_db%num_cs > 0) then !rtb cs
 529 call res_cs_output (j)
IF (cs_db%num_tot > 0) THEN Lines 523-527
 524 call res_pesticide_output (j)
 525 if (cs_db%num_salts > 0) then !rtb salt
 526 call res_salt_output (j)
END IFLine 527
END DOLine 533
DO j = 1, sp_ob%ru Lines 535-543
 536 call ru_output(j)
 537 if(cs_db%num_salts > 0) then !rtb salt
 538 call ru_salt_output(j)
 540 if(cs_db%num_cs > 0) then !rtb cs
 541 call ru_cs_output(j)
END DOLine 543
DO j = 1, sp_ob%recall Lines 545-547
 546 call recall_output (j)
END DOLine 547
IF (bsn_cc%gwflow == 1) THEN Lines 581-587
DO i_chan=1,sp_ob%chandeg Lines 582-586
IF (hydsep_flag(i_chan) == 1) THEN Lines 583-585
 584 write(out_hyd_sep,102) time%yrc,time%day,i_chan,(hyd_sep_array(i_chan,i_count),i_count=1,7)
END IFLine 585
END DOLine 586
END IFLine 587
DO while (icmd /= 0) Lines 590-606
 591 ob(icmd)%hdsep%flo_surq = 0.
 592 ob(icmd)%hdsep%flo_latq = 0.
 593 ob(icmd)%hdsep%flo_gwsw = 0.
 594 ob(icmd)%hdsep%flo_swgw = 0.
 595 ob(icmd)%hdsep%flo_satex = 0.
 596 ob(icmd)%hdsep%flo_satexsw = 0.
 597 ob(icmd)%hdsep%flo_tile = 0.
 598 ob(icmd)%hdsep_in%flo_surq = 0.
 599 ob(icmd)%hdsep_in%flo_latq = 0.
 600 ob(icmd)%hdsep_in%flo_gwsw = 0.
 601 ob(icmd)%hdsep_in%flo_swgw = 0.
 602 ob(icmd)%hdsep_in%flo_satex = 0.
 603 ob(icmd)%hdsep_in%flo_satexsw = 0.
 604 ob(icmd)%hdsep_in%flo_tile = 0.
 605 icmd = ob(icmd)%cmd_next
END DOLine 606
END DO
END IF
END IF
END DO
Allocations
n/a
Calls
Procedures Called
List of procedures called by this Subroutine.
hru_control
hyddep_output
hru_lte_control
ru_control
gwflow_simulate
aqu_1d_control
res_control
recall_nut
recall_salt
recall_cs
constit_hyd_mult
sd_channel_control3
flow_dur_curve
hydout_output
obj_output
water_allocation_output
manure_source_output
manure_demand_output
hru_lte_output
hru_output
hru_carbon_output
wetland_output
wet_salt_output
wet_cs_output
hru_pesticide_output
hru_pathogen_output
hru_salt_output
hru_cs_output
soil_nutcarb_write
soil_carbvar_write
aquifer_output
aqu_salt_output
aqu_cs_output
aqu_pesticide_output
channel_output
sd_chanmorph_output
sd_chanbud_output
sd_channel_output
cha_pesticide_output
ch_salt_output
ch_cs_output
cs_str_output
reservoir_output
res_pesticide_output
res_salt_output
res_cs_output
ru_output
ru_salt_output
ru_cs_output
recall_output
hydin_output
basin_ch_pest_output
basin_res_pest_output
basin_ls_pest_output
basin_aqu_pest_output
basin_output
lsu_output
basin_aquifer_output
basin_reservoir_output
basin_channel_output
basin_chanmorph_output
basin_chanbud_output
basin_sdchannel_output
basin_recall_output
salt_balance
cs_balance
1000
Call Graph
Visual representation of procedures called by this Subroutine.
Call graph
command calls 1000, aqu_1d_control, aqu_cs_output, aqu_pesticide_output, aqu_salt_output, aquifer_output, basin_aqu_pest_output, basin_aquifer_output, basin_ch_pest_output, basin_chanbud_output, basin_chanmorph_output, basin_channel_output, basin_ls_pest_output, basin_output, basin_recall_output, basin_res_pest_output, basin_reservoir_output, basin_sdchannel_output, ch_cs_output, ch_salt_output, cha_pesticide_output, channel_output, constit_hyd_mult, cs_balance, cs_str_output, flow_dur_curve, gwflow_simulate, hru_carbon_output, hru_control, hru_cs_output, hru_lte_control, hru_lte_output, hru_output, hru_pathogen_output, hru_pesticide_output, hru_salt_output, hyddep_output, hydin_output, hydout_output, lsu_output, manure_demand_output, manure_source_output, obj_output, recall_cs, recall_nut, recall_output, recall_salt, res_control, res_cs_output, res_pesticide_output, res_salt_output, reservoir_output, ru_control, ru_cs_output, ru_output, ru_salt_output, salt_balance, sd_chanbud_output, sd_chanmorph_output, sd_channel_control3, sd_channel_output, soil_carbvar_write, soil_nutcarb_write, water_allocation_output, wet_cs_output, wet_salt_output, wetland_output