conditions – test-src-project
conditions Subroutine
619 statements
Source File
subroutine conditions(ob_cur, idtbl)
Uses
aquifer_module
sd_channel_module
output_landscape_module
mgt_operations_module
water_allocation_module
hru_module
conditional_module
reservoir_data_module
climate_module
hydrograph_module
soil_module
plant_module
reservoir_module
time_module
organic_mineral_mass_module
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: ob_cur
integer, intent(in) :: idtbl
I/O
n/a
Outside Variables and Types
type(aquifer_dynamic) (1 attribute from aquifer_module)
Attribute Name Description
aqu_d
type(swatdeg_channel_dynamic) (1 attribute from sd_channel_module)
Attribute Name Description
sd_ch
type(output_waterbal) (1 attribute from output_landscape_module)
Attribute Name Description
hwb_d
type(management_schedule) (1 attribute from mgt_operations_module)
Attribute Name Description
sched
type(water_allocation) (1 attribute from water_allocation_module)
Attribute Name Description
wallo
dimension by water allocation objects
type(hydrologic_response_unit) (1 attribute from hru_module)
Attribute Name Description
hru
integer (4 attributes from hru_module)
Attribute Name Description
ipl
mgt_ops
rndseed_cond
random number seed for dtbl conditional
iwst
|
real (1 attribute from hru_module)
Attribute Name Description
qtile
type(decision_table) (1 attribute from conditional_module)
Attribute Name Description
dtbl_lum
type (24 attributes from conditional_module)
Attribute Name Description
d_tbl%hru_ha_cur None
d_tbl%hru_lu None
d_tbl%hru_lu_cur None
d_tbl%conds None
d_tbl%act_hit None
d_tbl%cond None
d_tbl%con_act None
d_tbl%prob_cum None
d_tbl%days_prob None
d_tbl%alt None
d_tbl%day_prev None
d_tbl%frac_app None
d_tbl%alts None
sp_ob1%hru_lte None
sp_ob1%res None
sp_ob1%hru None
sp_ob1%chandeg None
time%yrc None
time%day_end_yr None
time%yrc_start None
time%mo None
time%day None
time%day_start None
time%yrs None
type(wgn_parms) (1 attribute from climate_module)
Attribute Name Description
wgn_pms
type(weather_station) (1 attribute from climate_module)
Attribute Name Description
wst
type(climate_measured_data) (1 attribute from climate_module)
Attribute Name Description
tmp
type(hyd_output) (3 attributes from hydrograph_module)
Attribute Name Description
hd
res
wet
type(object_connectivity) (1 attribute from hydrograph_module)
Attribute Name Description
ob
type(irrigation_water_transfer) (1 attribute from hydrograph_module)
Attribute Name Description
irrig
dimension by hru
type(soil_profile) (1 attribute from soil_module)
Attribute Name Description
soil
type(plant_community) (1 attribute from plant_module)
Attribute Name Description
pcom
type(reservoir) (1 attribute from reservoir_module)
Attribute Name Description
res_ob
type(wetland) (1 attribute from reservoir_module)
Attribute Name Description
wet_ob
type(soil_profile_mass) (1 attribute from organic_mineral_mass_module)
Attribute Name Description
soil1
type(plant_community_mass) (1 attribute from organic_mineral_mass_module)
Attribute Name Description
pl_mass
!! Bang Comments
find average water stress of all growing plants find average water stress of all growing plants find average water stress of all growing plants use labile P concentration of upper (10 mm) layer set application day if first day of application window update cumulative probability if new day reset if first day of window check if window is over - days_prob are the number of days left in window cumulative prob of uniform distribution on current day of the window
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure.
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
  60 d_tbl%act_hit = "y"
DO ic = 1, d_tbl%conds Lines 61-836
SELECT CASE (d_tbl%cond(ic)%var) Lines 62-835
CASE ("w_stress") Lines 65-85
  66 ob_num = d_tbl%cond(ic)%ob_num
  67 if (ob_num == 0) ob_num = ob_cur
  69 pl_sum = 0
  70 strs_sum = 0.
  83 call cond_real (ic, strs_sum, d_tbl%cond(ic)%lim_const, idtbl)
DO ipl = 1, pcom(ob_num)%npl Lines 71-76
IF (pcom(ob_num)%plcur(ipl)%gro == "y") THEN Lines 72-75
  73 pl_sum = pl_sum + 1
  74 strs_sum = strs_sum + pcom(ob_num)%plstr(ipl)%strsw
END IFLine 75
END DOLine 76
IF (pl_sum > 0) THEN Lines 77-78
  78 strs_sum = strs_sum / pl_sum
END IFLine 78
ELSE Lines 79-81
  80 strs_sum = 1.
END IF Line 81
CASE ("n_stress") Lines 86-102
  87 ob_num = d_tbl%cond(ic)%ob_num
  88 if (ob_num == 0) ob_num = ob_cur
  90 pl_sum = 0
  91 strs_sum = 0.
  98 if (pl_sum > 0) strs_sum = strs_sum / pl_sum
 100 call cond_real (ic, strs_sum, d_tbl%cond(ic)%lim_const, idtbl)
DO ipl = 1, pcom(ob_num)%npl Lines 92-97
IF (pcom(ob_num)%plcur(ipl)%gro == "y") THEN Lines 93-96
  94 pl_sum = pl_sum + 1
  95 strs_sum = strs_sum + pcom(ob_num)%plstr(ipl)%strsn
END IFLine 96
END DOLine 97
CASE ("p_stress") Lines 103-119
 104 ob_num = d_tbl%cond(ic)%ob_num
 105 if (ob_num == 0) ob_num = ob_cur
 107 pl_sum = 0
 108 strs_sum = 0.
 115 if (pl_sum > 0) strs_sum = strs_sum / pl_sum
 117 call cond_real (ic, strs_sum, d_tbl%cond(ic)%lim_const, idtbl)
DO ipl = 1, pcom(ob_num)%npl Lines 109-114
IF (pcom(ob_num)%plcur(ipl)%gro == "y") THEN Lines 110-113
 111 pl_sum = pl_sum + 1
 112 strs_sum = strs_sum + pcom(ob_num)%plstr(ipl)%strsp
END IFLine 113
END DOLine 114
CASE ("phu_plant") Lines 120-142
 121 ob_num = d_tbl%cond(ic)%ob_num
 122 if (ob_num == 0) ob_num = ob_cur
 140 call cond_real (ic, pcom(ob_num)%plcur(ipl)%phuacc, d_tbl%cond(ic)%lim_const, idtbl)
DO ialt = 1, d_tbl%alts Lines 124-138
IF (pcom(ob_num)%npl == 0) THEN Lines 126-127
 127 d_tbl%act_hit(ialt) = "n"
END IFLine 127
ELSE Lines 128-137
 130 ipl = 1
DO iipl = 1, pcom(ob_num)%npl Lines 131-136
IF (pcom(ob_num)%plcur(iipl)%phuacc > 1.e-6) THEN Lines 132-135
 133 ipl = iipl
 134 exit
END IFLine 135
END DOLine 136
END IF Line 137
END DOLine 138
CASE ("phu_base0") Lines 143-157
 144 ob_num = d_tbl%cond(ic)%ob_num
 145 if (ob_num == 0) ob_num = ob_cur
 153 iwst = ob(iob)%wst
 155 call cond_real (ic, wst(iwst)%weat%phubase0, d_tbl%cond(ic)%lim_const, idtbl)
IF (d_tbl%cond(ic)%ob == "hru") THEN Lines 147-149
 148 iob = sp_ob1%hru + ob_num - 1
END IFLine 149
IF (d_tbl%cond(ic)%ob == "hlt") THEN Lines 150-152
 151 iob = sp_ob1%hru_lte + ob_num - 1
END IFLine 152
CASE ("precip_cur") Lines 158-172
 159 ob_num = d_tbl%cond(ic)%ob_num
 160 if (ob_num == 0) ob_num = ob_cur
 168 iwst = ob(iob)%wst
 170 call cond_real (ic, wst(iwst)%weat%precip, d_tbl%cond(ic)%lim_const, idtbl)
IF (d_tbl%cond(ic)%ob == "hru") THEN Lines 162-164
 163 iob = sp_ob1%hru + ob_num - 1
END IFLine 164
IF (d_tbl%cond(ic)%ob == "hlt") THEN Lines 165-167
 166 iob = sp_ob1%hru_lte + ob_num - 1
END IFLine 167
CASE ("precip_next") Lines 173-187
 174 ob_num = d_tbl%cond(ic)%ob_num
 175 if (ob_num == 0) ob_num = ob_cur
 183 iwst = ob(iob)%wst
 185 call cond_real (ic, wst(iwst)%weat%precip_next, d_tbl%cond(ic)%lim_const, idtbl)
IF (d_tbl%cond(ic)%ob == "hru") THEN Lines 177-179
 178 iob = sp_ob1%hru + ob_num - 1
END IFLine 179
IF (d_tbl%cond(ic)%ob == "hlt") THEN Lines 180-182
 181 iob = sp_ob1%hru_lte + ob_num - 1
END IFLine 182
CASE ("plant_gro") Lines 188-200
 189 ob_num = d_tbl%cond(ic)%ob_num
 190 if (ob_num == 0) ob_num = ob_cur
 191 ipl = Max (Int(d_tbl%cond(ic)%lim_const), 1)
DO ialt = 1, d_tbl%alts Lines 192-198
 193 if (d_tbl%alt(ic,ialt) == "=") then    !determine if growing (y) or not (n)
IF (pcom(ob_num)%plcur(ipl)%gro == "n") THEN Lines 194-196
 195 d_tbl%act_hit(ialt) = "n"
END IFLine 196
END DOLine 198
CASE ("plant_name_gro") Lines 201-224
 202 ob_num = d_tbl%cond(ic)%ob_num
 203 if (ob_num == 0) ob_num = ob_cur
 204 ipl = 0
DO iipl = 1, pcom(ob_num)%npl Lines 205-209
IF (d_tbl%cond(ic)%lim_var == pcom(ob_num)%pl(iipl)) THEN Lines 206-208
 207 ipl = iipl
END IFLine 208
END DOLine 209
IF (ipl == 0) THEN Lines 211-212
 212 d_tbl%act_hit(ialt) = "n"
END IFLine 212
ELSE Lines 213-222
DO ialt = 1, d_tbl%alts Lines 215-221
 216 if (d_tbl%alt(ic,ialt) == "=") then    !determine if growing (y) or not (n)
IF (pcom(ob_num)%plcur(ipl)%gro == "n") THEN Lines 217-219
 218 d_tbl%act_hit(ialt) = "n"
END IFLine 219
END DOLine 221
END IF Line 222
CASE ("days_plant") Lines 225-233
 226 ob_num = d_tbl%cond(ic)%ob_num
 227 if (ob_num == 0) ob_num = ob_cur
 229 ivar_cur = pcom(ob_num)%days_plant
 230 ivar_tbl = int(d_tbl%cond(ic)%lim_const)
 231 call cond_integer (ic, ivar_cur, ivar_tbl)
CASE ("days_harv") Lines 234-242
 235 ob_num = d_tbl%cond(ic)%ob_num
 236 if (ob_num == 0) ob_num = ob_cur
 238 ivar_cur = pcom(ob_num)%days_harv
 239 ivar_tbl = int(d_tbl%cond(ic)%lim_const)
 240 call cond_integer (ic, ivar_cur, ivar_tbl)
CASE ("days_irr") Lines 243-251
 244 ob_num = d_tbl%cond(ic)%ob_num
 245 if (ob_num == 0) ob_num = ob_cur
 247 ivar_cur = pcom(ob_num)%days_irr
 248 ivar_tbl = int(d_tbl%cond(ic)%lim_const)
 249 call cond_integer (ic, ivar_cur, ivar_tbl)
CASE ("days_act") Lines 252-261
 253 ob_num = d_tbl%cond(ic)%ob_num
 254 if (ob_num == 0) ob_num = ob_cur
 256 iac = d_tbl%con_act(ic)
 257 ivar_cur = pcom(ob_num)%dtbl(idtbl)%days_act(iac)
 258 ivar_tbl = int(d_tbl%cond(ic)%lim_const) + 2
 259 call cond_integer (ic, ivar_cur, ivar_tbl)
CASE ("day_start") Lines 262-267
 263 ivar_cur = time%day_start
 264 ivar_tbl = int(d_tbl%cond(ic)%lim_const)
 265 call cond_integer (ic, ivar_cur, ivar_tbl)
CASE ("irr_year") Lines 268-274
 269 ob_num = d_tbl%cond(ic)%ob_num
 270 if (ob_num == 0) ob_num = ob_cur
 272 call cond_real (ic, hru(ob_num)%irr_yr, d_tbl%cond(ic)%lim_const, idtbl)
CASE ("slope") Lines 275-281
 276 ob_num = d_tbl%cond(ic)%ob_num
 277 if (ob_num == 0) ob_num = ob_cur
 279 call cond_real (ic, hru(ob_num)%topo%slope, d_tbl%cond(ic)%lim_const, idtbl)
CASE ("soil_water") Lines 282-311
 284 ob_num = d_tbl%cond(ic)%ob_num
 285 if (ob_num == 0) ob_num = ob_cur
 287 targ_val = 0.
 309 call cond_real (ic, soil(ob_num)%sw, targ, idtbl)
SELECT CASE (d_tbl%cond(ic)%lim_var) Lines 288-295
CASE ("ul") !upper limit (porosity) Lines 293-294
 294 targ_val = soil(ob_num)%sumul
END SELECTLine 295
SELECT CASE ((d_tbl%cond(ic)%lim_op)) Lines 298-307
CASE ("*") Lines 299-300
 300 targ = targ_val * d_tbl%cond(ic)%lim_const
CASE ("+") Lines 301-302
 302 targ = targ_val + d_tbl%cond(ic)%lim_const
CASE ("-") Lines 303-304
 304 targ = targ_val - d_tbl%cond(ic)%lim_const
CASE ("/") Lines 305-306
 306 targ = targ_val / d_tbl%cond(ic)%lim_const
END SELECTLine 307
CASE ("jday") Lines 312-317
 313 ivar_cur = time%day
 314 ivar_tbl = int(d_tbl%cond(ic)%lim_const)
 315 call cond_integer (ic, ivar_cur, ivar_tbl)
CASE ("month") Lines 318-323
 319 ivar_cur = time%mo
 320 ivar_tbl = int(d_tbl%cond(ic)%lim_const)
 321 call cond_integer (ic, ivar_cur, ivar_tbl)
CASE ("year_rot") Lines 324-332
 325 ob_num = d_tbl%cond(ic)%ob_num
 326 if (ob_num == 0) ob_num = ob_cur
 328 ivar_cur = pcom(ob_num)%rot_yr
 329 ivar_tbl = int(d_tbl%cond(ic)%lim_const)
 330 call cond_integer (ic, ivar_cur, ivar_tbl)
CASE ("year_gro") Lines 333-341
 334 ob_num = d_tbl%cond(ic)%ob_num
 335 if (ob_num == 0) ob_num = ob_cur
 337 ivar_cur = pcom(ob_num)%plcur(1)%curyr_mat
 338 ivar_tbl = int(d_tbl%cond(ic)%lim_const)
 339 call cond_integer (ic, ivar_cur, ivar_tbl)
CASE ("year_cal") Lines 342-347
 343 ivar_cur = time%yrc
 344 ivar_tbl = int(d_tbl%cond(ic)%lim_const)
 345 call cond_integer (ic, ivar_cur, ivar_tbl)
CASE ("year_seq") Lines 348-353
 349 ivar_cur = time%yrs
 350 ivar_tbl = int(d_tbl%cond(ic)%lim_const)
 351 call cond_integer (ic, ivar_cur, ivar_tbl)
CASE ("year_start") Lines 354-359
 355 ivar_cur = time%yrc_start
 356 ivar_tbl = int(d_tbl%cond(ic)%lim_const)
 357 call cond_integer (ic, ivar_cur, ivar_tbl)
CASE ("cur_yrs_mat") Lines 360-368
 361 ob_num = d_tbl%cond(ic)%ob_num
 362 if (ob_num == 0) ob_num = ob_cur
 364 ivar_cur = pcom(ob_num)%plcur(1)%curyr_mat
 365 ivar_tbl = int(d_tbl%cond(ic)%lim_const)
 366 call cond_integer (ic, ivar_cur, ivar_tbl)
CASE ("biomass") Lines 369-375
 370 ob_num = d_tbl%cond(ic)%ob_num
 371 if (ob_num == 0) ob_num = ob_cur
 373 call cond_real (ic, pl_mass(ob_num)%ab_gr_com%m, d_tbl%cond(ic)%lim_const, idtbl)
CASE ("leaf_area") Lines 376-382
 377 ob_num = d_tbl%cond(ic)%ob_num
 378 if (ob_num == 0) ob_num = ob_cur
 380 call cond_real (ic, pcom(ob_num)%lai_sum, d_tbl%cond(ic)%lim_const, idtbl)
CASE ("ground_cov") Lines 383-389
 384 ob_num = d_tbl%cond(ic)%ob_num
 385 if (ob_num == 0) ob_num = ob_cur
 387 call cond_real (ic, pl_mass(ob_num)%ab_gr_com%m, d_tbl%cond(ic)%lim_const, idtbl)
CASE ("p_factor") Lines 390-396
 391 ob_num = d_tbl%cond(ic)%ob_num
 392 if (ob_num == 0) ob_num = ob_cur
 394 call cond_real (ic, hru(ob_num)%lumv%usle_p, d_tbl%cond(ic)%lim_const, idtbl)
CASE ("k_factor") Lines 397-403
 398 ob_num = d_tbl%cond(ic)%ob_num
 399 if (ob_num == 0) ob_num = ob_cur
 401 call cond_real (ic, soil(ob_num)%ly(1)%usle_k, d_tbl%cond(ic)%lim_const, idtbl)
CASE ("hyd_soil_group") Lines 404-415
 405 ob_num = d_tbl%cond(ic)%ob_num
 406 if (ob_num == 0) ob_num = ob_cur
DO ialt = 1, d_tbl%alts Lines 407-413
IF (d_tbl%alt(ic,ialt) == "=") THEN Lines 408-412
IF (soil(ob_num)%hydgrp /= d_tbl%cond(ic)%lim_var) THEN Lines 409-411
 410 d_tbl%act_hit(ialt) = "n"
END IFLine 411
END IFLine 412
END DOLine 413
CASE ("p_pet") Lines 416-423
 417 ob_num = d_tbl%cond(ic)%ob_num
 418 if (ob_num == 0) ob_num = ob_cur
 419 iwst = ob(ob_num)%wst
 420 iwgn = wst(iwst)%wco%wgn
 421 call cond_real (ic, wgn_pms(iwgn)%p_pet_rto, d_tbl%cond(ic)%lim_const, idtbl)
CASE ("p_lab_150") Lines 424-445
 425 ob_num = d_tbl%cond(ic)%ob_num
 426 if (ob_num == 0) ob_num = ob_cur
 429 wt_tot = soil(ob_num)%phys(1)%bd * soil(ob_num)%phys(1)%thick / 100.    ! mg/kg => kg/ha
 430 p_lab_tot =  soil1(ob_num)%mp(1)%lab / wt_tot
 441 p_lab_ppm = p_lab_tot / wt_tot
 443 call cond_real (ic, p_lab_ppm, d_tbl%cond(ic)%lim_const, idtbl)
DO ly = 2, soil(ob_num)%nly Lines 431-440
 437 wt_tot = wt_tot + soil(ob_num)%phys(ly)%bd * soil(ob_num)%phys(ly)%thick / 100.    ! mg/kg => kg/ha
 438 p_lab_tot = p_lab_tot + soil1(ob_num)%mp(ly)%lab
 439 exit
IF (soil(ob_num)%phys(ly)%d > 150.) THEN Lines 432-433
 433 rto = (150. - soil(ob_num)%phys(ly-1)%d) / (soil(ob_num)%phys(ly)%d - soil(ob_num)%phys(ly-1)%d)
END IFLine 433
ELSE Lines 434-436
 435 rto = 1.
END IF Line 436
END DOLine 440
CASE ("soil_temp2") Lines 446-452
 447 ob_num = d_tbl%cond(ic)%ob_num
 448 if (ob_num == 0) ob_num = ob_cur
 450 call cond_real (ic, soil(ob_num)%phys(2)%tmp, d_tbl%cond(ic)%lim_const, idtbl)
CASE ("soil_carbon") Lines 453-459
 454 ob_num = d_tbl%cond(ic)%ob_num
 455 if (ob_num == 0) ob_num = ob_cur
 457 call cond_real (ic, soil1(ob_num)%cbn(1), d_tbl%cond(ic)%lim_const, idtbl)
CASE ("tile_drained") Lines 460-477
 461 ob_num = d_tbl%cond(ic)%ob_num
 462 if (ob_num == 0) ob_num = ob_cur
DO ialt = 1, d_tbl%alts Lines 464-475
IF (d_tbl%alt(ic,ialt) == "=") THEN Lines 465-469
IF (hru(ob_num)%tiledrain == 0) THEN Lines 466-468
 467 d_tbl%act_hit(ialt) = "n"
END IFLine 468
END IFLine 469
IF (d_tbl%alt(ic,ialt) == "/") THEN Lines 470-474
IF (hru(ob_num)%tiledrain == 1) THEN Lines 471-473
 472 d_tbl%act_hit(ialt) = "n"
END IFLine 473
END IFLine 474
END DOLine 475
CASE ("prob") Lines 478-484
 480 ran_num = Aunif(rndseed_cond)
 482 call cond_real (ic, ran_num, d_tbl%cond(ic)%lim_const, idtbl)
CASE ("prob_unif") Lines 485-526
IF (time%day == d_tbl%cond(ic)%ob_num) THEN Lines 487-516
IF (d_tbl%cond(ic)%lim_const > d_tbl%cond(ic)%ob_num) THEN Lines 489-498
 491 ran_num = Aunif(rndseed_cond)
IF (ran_num < d_tbl%frac_app) THEN Lines 492-495
 493 days_tot = d_tbl%cond(ic)%lim_const - d_tbl%cond(ic)%ob_num + 1
 494 ran_num = Aunif(rndseed_cond)
 495 pcom(ob_cur)%dtbl(idtbl)%apply_day = int(ran_num * days_tot) + d_tbl%cond(ic)%ob_num + 1
END IFLine 495
ELSE Lines 496-498
 497 pcom(ob_cur)%dtbl(idtbl)%apply_day = 0.
END IF Line 498
END IFLine 498
ELSE Lines 499-515
 501 ran_num = Aunif(rndseed_cond)
IF (ran_num < d_tbl%frac_app) THEN Lines 502-511
IF (time%day >= d_tbl%cond(ic)%lim_const) THEN Lines 503-506
 504 days_tot = time%day_end_yr - d_tbl%cond(ic)%ob_num + 1
 505 ran_num = Aunif(rndseed_cond)
 506 pcom(ob_cur)%dtbl(idtbl)%apply_day = int(ran_num * days_tot) + d_tbl%cond(ic)%ob_num + 1
END IFLine 506
ELSE Lines 507-511
 508 days_tot = d_tbl%cond(ic)%lim_const
 509 ran_num = Aunif(rndseed_cond)
 510 pcom(ob_cur)%dtbl(idtbl)%apply_day = int(ran_num * days_tot) + 1
END IF Line 511
END IFLine 511
ELSE Lines 512-514
 513 pcom(ob_cur)%dtbl(idtbl)%apply_day = 0.
END IF Line 514
END IF Line 515
END IFLine 516
IF (time%day /= pcom(ob_cur)%dtbl(idtbl)%apply_day) THEN Lines 518-524
DO ialt = 1, d_tbl%alts Lines 519-523
IF (d_tbl%alt(ic,ialt) == "=") THEN Lines 520-522
 521 d_tbl%act_hit(ialt) = "n"
END IFLine 522
END DOLine 523
END IFLine 524
CASE ("prob_unif1") Lines 527-556
 547 ran_num = Aunif(rndseed_cond)
IF (time%day /= d_tbl%day_prev .and. d_tbl%days_prob > 0) THEN Lines 529-545
 535 d_tbl%day_prev = time%day
IF (time%yrc == d_tbl%cond(ic)%ob_num .and. time%day == 1) THEN Lines 531-534
 532 d_tbl%days_prob = d_tbl%cond(ic)%lim_const
 533 d_tbl%prob_cum = 0.
END IFLine 534
IF (d_tbl%days_prob >= 1) THEN Lines 537-540
 539 d_tbl%prob_cum = 1. / float(d_tbl%days_prob)
 540 d_tbl%days_prob = d_tbl%days_prob - 1
END IFLine 540
ELSE Lines 541-544
 542 d_tbl%days_prob = 0.
 543 d_tbl%prob_cum = 0.
END IF Line 544
END IFLine 545
IF (ran_num > d_tbl%prob_cum) THEN Lines 548-554
DO ialt = 1, d_tbl%alts Lines 549-553
IF (d_tbl%alt(ic,ialt) == "=") THEN Lines 550-552
 551 d_tbl%act_hit(ialt) = "n"
END IFLine 552
END DOLine 553
END IFLine 554
CASE ("prob_unif_lu") Lines 557-609
 558 prob_cum = 0.
IF (d_tbl%cond(ic)%lim_const > d_tbl%cond(ic)%ob_num) THEN Lines 560-564
IF (time%day <= d_tbl%cond(ic)%lim_const .and. time%day >= d_tbl%cond(ic)%ob_num) THEN Lines 561-564
 563 prob_cum = (time%day - d_tbl%cond(ic)%ob_num + 1) / (d_tbl%cond(ic)%lim_const - d_tbl%cond(ic)%ob_num)
END IFLine 564
END IFLine 564
ELSE Lines 565-576
IF (time%day >= d_tbl%cond(ic)%lim_const .or. time%day <= d_tbl%cond(ic)%ob_num) THEN Lines 566-575
 567 days_tot = time%day_end_yr - d_tbl%cond(ic)%lim_const + d_tbl%cond(ic)%ob_num
IF (time%day >= d_tbl%cond(ic)%lim_const) THEN Lines 568-570
 570 prob_cum = (time%day - d_tbl%cond(ic)%lim_const) / days_tot
END IFLine 570
ELSE Lines 571-574
 573 prob_cum = (time%day_end_yr - d_tbl%cond(ic)%lim_const + time%day + 1) / days_tot
END IF Line 574
END IFLine 575
END IF Line 576
IF (prob_cum > 0.) THEN Lines 577-595
 578 ran_num = Aunif(rndseed_cond)
 579 hru_exp_left = d_tbl%hru_lu - (prob_cum * d_tbl%hru_lu)
 580 hru_act_left = d_tbl%hru_lu - d_tbl%hru_lu_cur
 581 prob_apply = (hru_act_left - hru_exp_left) / (hru_act_left + 1)
IF (ran_num > prob_apply) THEN Lines 583-588
DO ialt = 1, d_tbl%alts Lines 584-588
IF (d_tbl%alt(ic,ialt) == "=") THEN Lines 585-587
 586 d_tbl%act_hit(ialt) = "n"
END IFLine 587
END DOLine 588
END IFLine 588
ELSE Lines 589-595
 594 ipl = 1
END IF Line 595
END IFLine 595
ELSE Lines 596-602
DO ialt = 1, d_tbl%alts Lines 597-601
IF (d_tbl%alt(ic,ialt) == "=") THEN Lines 598-600
 599 d_tbl%act_hit(ialt) = "n"
END IFLine 600
END DOLine 601
END IF Line 602
IF (time%day > d_tbl%cond(ic)%lim_const) THEN Lines 604-607
 605 d_tbl%hru_lu_cur = 0
 606 d_tbl%hru_ha_cur = 0.
END IFLine 607
CASE ("channel_flo") Lines 610-618
 611 ob_num = d_tbl%cond(ic)%ob_num
 612 if (ob_num == 0) ob_num = ob_cur
 614 iob = sp_ob1%chandeg + ob_num - 1
 615 flo_m3 = ob(iob)%hd(1)%flo / 86400.
 616 call cond_real (ic, flo_m3, d_tbl%cond(ic)%lim_const, idtbl)
CASE ("tile_flo") Lines 619-625
 620 ob_num = d_tbl%cond(ic)%ob_num
 621 if (ob_num == 0) ob_num = ob_cur
 623 call cond_real (ic, hwb_d(ob_num)%qtile, d_tbl%cond(ic)%lim_const, idtbl)
CASE ("irr_demand") Lines 626-632
 627 ob_num = d_tbl%cond(ic)%ob_num
 628 if (ob_num == 0) ob_num = ob_cur
 630 call cond_real (ic, irrig(ob_num)%demand, d_tbl%cond(ic)%lim_const, idtbl)
CASE ("irr_demand_wro") Lines 633-639
 634 ob_num = d_tbl%cond(ic)%ob_num
 635 if (ob_num == 0) ob_num = ob_cur
 637 call cond_real (ic, wallo(ob_num)%tot%demand, d_tbl%cond(ic)%lim_const, idtbl)
CASE ("aqu_dep") Lines 640-646
 641 ob_num = d_tbl%cond(ic)%ob_num
 642 if (ob_num == 0) ob_num = ob_cur
 644 call cond_real (ic, aqu_d(ob_num)%dep_wt, d_tbl%cond(ic)%lim_const, idtbl)
CASE ("land_use") Lines 647-659
 648 ob_num = d_tbl%cond(ic)%ob_num
 649 if (ob_num == 0) ob_num = ob_cur
DO ialt = 1, d_tbl%alts Lines 651-657
IF (d_tbl%alt(ic,ialt) == "=") THEN Lines 652-656
IF (hru(ob_num)%land_use_mgt_c /= d_tbl%cond(ic)%lim_var) THEN Lines 653-655
 654 d_tbl%act_hit(ialt) = "n"
END IFLine 655
END IFLine 656
END DOLine 657
CASE ("cal_group") Lines 660-670
 661 ob_num = d_tbl%cond(ic)%ob_num
 662 if (ob_num == 0) ob_num = ob_cur
DO ialt = 1, d_tbl%alts Lines 663-669
IF (d_tbl%alt(ic,ialt) == "=") THEN Lines 664-668
IF (hru(ob_num)%cal_group /= d_tbl%cond(ic)%lim_var) THEN Lines 665-667
 666 d_tbl%act_hit(ialt) = "n"
END IFLine 667
END IFLine 668
END DOLine 669
CASE ("tillage") Lines 671-689
 672 ob_num = d_tbl%cond(ic)%ob_num
 673 if (ob_num == 0) ob_num = ob_cur
DO ialt = 1, d_tbl%alts Lines 675-687
 676 pl_chk = "n"
 686 if (pl_chk == "n") d_tbl%act_hit(ialt) = "n"
IF (d_tbl%alt(ic,ialt) == "=") THEN Lines 677-685
 678 isched = hru(ob_num)%mgt_ops
DO iauto = 1, sched(isched)%num_autos Lines 679-684
 680 id = sched(isched)%num_db(iauto)
IF (dtbl_lum(id)%name == d_tbl%cond(ic)%lim_var) THEN Lines 681-683
 682 pl_chk = "y"
END IFLine 683
END DOLine 684
END IFLine 685
END DOLine 687
CASE ("plant_com") Lines 690-718
 691 ob_num = d_tbl%cond(ic)%ob_num
 692 if (ob_num == 0) ob_num = ob_cur
DO ialt = 1, d_tbl%alts Lines 694-716
IF (d_tbl%alt(ic,ialt) /= "-") THEN Lines 696-715
IF (d_tbl%alt(ic,ialt) == "=") THEN Lines 698-706
 699 pl_chk = "n"
 705 if (pl_chk == "n") d_tbl%act_hit(ialt) = "n"
DO ipl = 1, pcom(ob_num)%npl Lines 700-704
IF (pcom(ob_num)%pl(ipl) == d_tbl%cond(ic)%lim_var) THEN Lines 701-703
 702 pl_chk = "y"
END IFLine 703
END DOLine 704
END IFLine 706
IF (d_tbl%alt(ic,ialt) == "/") THEN Lines 708-714
DO ipl = 1, pcom(ob_num)%npl Lines 709-713
IF (pcom(ob_num)%pl(ipl) == d_tbl%cond(ic)%lim_var) THEN Lines 710-712
 711 d_tbl%act_hit(ialt) = "n"
END IFLine 712
END DOLine 713
END IFLine 714
END IFLine 715
END DOLine 716
CASE ("ch_order") Lines 719-731
 720 ob_num = d_tbl%cond(ic)%ob_num
 721 if (ob_num == 0) ob_num = ob_cur
DO ialt = 1, d_tbl%alts Lines 723-729
IF (d_tbl%alt(ic,ialt) == "=") THEN Lines 724-728
IF (sd_ch(ob_num)%order /= d_tbl%cond(ic)%lim_var) THEN Lines 725-727
 726 d_tbl%act_hit(ialt) = "n"
END IFLine 727
END IFLine 728
END DOLine 729
CASE ("vol") Lines 732-772
 734 ires = d_tbl%cond(ic)%ob_num
 735 if (ires == 0) ires = ob_cur
 770 call cond_real (ic, res(ires)%flo, targ, idtbl)
SELECT CASE (d_tbl%cond(ic)%lim_var) Lines 737-767
SELECT CASE ((d_tbl%cond(ic)%lim_op)) Lines 744-753
CASE ("*") Lines 745-746
 746 targ = targ_val * d_tbl%cond(ic)%lim_const
CASE ("+") Lines 747-748
 748 targ = targ_val + 10000. * d_tbl%cond(ic)%lim_const
CASE ("-") Lines 749-750
 750 targ = targ_val - 10000. * d_tbl%cond(ic)%lim_const   !convert ha-m to m3
CASE ("/") Lines 751-752
 752 targ = targ_val / d_tbl%cond(ic)%lim_const
END SELECTLine 753
SELECT CASE ((d_tbl%cond(ic)%lim_op)) Lines 757-766
CASE ("*") Lines 758-759
 759 targ = targ_val * d_tbl%cond(ic)%lim_const
CASE ("+") Lines 760-761
 761 targ = targ_val + 10000. * d_tbl%cond(ic)%lim_const
CASE ("-") Lines 762-763
 763 targ = targ_val - 10000. * d_tbl%cond(ic)%lim_const   !convert ha-m to m3
CASE ("/") Lines 764-765
 765 targ = targ_val / d_tbl%cond(ic)%lim_const
END SELECTLine 766
END SELECTLine 767
CASE ("res_inflo") Lines 773-781
 775 ob_num = d_tbl%cond(ic)%ob_num
 776 if (ob_num == 0) ob_num = ob_cur
 777 iob = sp_ob1%res + ob_num - 1
 778 flo_m3 = ob(iob)%hin%flo / 86400.
 779 call cond_real (ic, flo_m3, d_tbl%cond(ic)%lim_const, idtbl)
CASE ("wet_depth") Lines 782-793
 784 ires = d_tbl%cond(ic)%ob_num
 785 if (ires == 0) ires = ob_cur
 788 targ = d_tbl%cond(ic)%lim_const/1000.
 791 call cond_real (ic, wet_ob(ires)%depth, targ, idtbl)
CASE ("weirh") Lines 794-807
 796 ires = d_tbl%cond(ic)%ob_num
 797 if (ires == 0) ires = ob_cur
 800 targ = d_tbl%cond(ic)%lim_const/1000.
 803 call cond_real (ic, wet_ob(ires)%weir_hgt, targ, idtbl)
CASE ("vol_wet") Lines 808-834
 810 ires = d_tbl%cond(ic)%ob_num
 811 if (ires == 0) ires = ob_cur
 833 call cond_real (ic, wet(ires)%flo, targ, idtbl)
SELECT CASE (d_tbl%cond(ic)%lim_var) Lines 813-818
END SELECTLine 818
SELECT CASE ((d_tbl%cond(ic)%lim_op)) Lines 821-830
CASE ("*") Lines 822-823
 823 targ = targ_val * d_tbl%cond(ic)%lim_const
CASE ("+") Lines 824-825
 825 targ = targ_val + d_tbl%cond(ic)%lim_const
CASE ("-") Lines 826-827
 827 targ = targ_val - d_tbl%cond(ic)%lim_const
CASE ("/") Lines 828-829
 829 targ = targ_val / d_tbl%cond(ic)%lim_const
END SELECTLine 830
END SELECTLine 835
END DOLine 836
 838 return
Allocations
n/a
Calls
Calls
Procedures called by this subroutine.
Local Variables
Type Visibility Attributes Name Initial
integer, private :: ob_num
integer, private :: ic
integer, private :: ialt
integer, private :: iac
integer, private :: iob
real, private :: targ_val
real, private :: ran_num
real, private :: aunif
integer, private :: ires
integer, private :: ipl
integer, private :: iipl
integer, private :: id
integer, private :: isched
integer, private :: iauto
integer, private :: ivar_cur
integer, private :: ivar_tbl
real, private :: targ
integer, private :: pl_sum
integer, private :: days_tot
integer, private :: iwgn
integer, private :: ly
real, private :: strs_sum
real, private :: prob_cum
real, private :: prob_apply
real, private :: hru_exp_left
real, private :: hru_act_left
real, private :: flo_m3
real, private :: wt_tot
real, private :: p_lab_tot
real, private :: p_lab_ppm
real, private :: rto
real, private :: var_cur
Variables
Type Visibility Attributes Name Initial
integer, public :: ob_cur
integer, public :: idtbl
Call graph
conditions calls cond_integer, cond_real, float