dr_db_read – test-src-project
dr_db_read Subroutine
49 statements
Source File
subroutine dr_db_read()
Uses
input_file_module
dr_module
maximum_data_module
constituent_mass_module
Arguments
n/a
I/O
I/O units used in this subroutine.
Unit Type Filename
in_delr%del_ratio Input not specified
Outside Variables and Types
type (6 attributes from input_file_module)
Attribute Name Description
in_delr%del_ratio None
db_mx%dr None
cs_db%num_salts None
cs_db%num_pests None
cs_db%num_metals None
cs_db%num_paths None
type(delivery_ratio_datafiles) (1 attribute from dr_module)
Attribute Name Description
dr_db
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure.
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
  18 eof = 0
  21 inquire (file=in_delr%del_ratio, exist=i_exist)
IF (i_exist .or. in_delr%del_ratio /= "null") THEN Lines 22-52
  23 do
  24 open (107,file=in_delr%del_ratio)
  25 read (107,*,iostat=eof) titldum
  26 if (eof < 0) exit
  27 read (107,*,iostat=eof) header
  28 if (eof < 0) exit
  29 imax = 0
  36 db_mx%dr = imax
  38 allocate (dr_db(imax))
  39 rewind (107)
  40 read (107,*,iostat=eof) titldum
  41 if (eof < 0) exit
  42 read (107,*,iostat=eof) header
  43 if (eof < 0) exit
  49 close (107)
  50 exit
DO while (eof == 0) Lines 30-34
  31 read (107,*,iostat=eof) titldum
  32 if (eof < 0) exit
  33 imax = imax + 1
END DOLine 34
DO ii = 1, imax Lines 45-48
  46 read (107,*,iostat=eof) dr_db(ii)
  47 if (eof < 0) exit
END DOLine 48
END IFLine 52
  55 call dr_read_om
  56 if (cs_db%num_pests > 0) call dr_read_pest
  57 if (cs_db%num_paths > 0) call dr_path_read
  58 if (cs_db%num_metals > 0) call dr_read_hmet
  59 if (cs_db%num_salts > 0) call dr_read_salt
  61 return
Allocations
Memory allocations and deallocations grouped by variable.
Variable Allocations Deallocations
dr_db line 38 none
Calls
Calls
Procedures called by this subroutine.
Local Variables
Type Visibility Attributes Name Initial
character, private :: titldum
character, private :: header
integer, private :: eof
integer, private :: imax
logical, private :: i_exist
integer, private :: ii
Call graph
dr_db_read calls dr_path_read, dr_read_hmet, dr_read_om, dr_read_pest, dr_read_salt