exco_db_read – test-src-project
exco_db_read Subroutine
49 statements
Source File
subroutine exco_db_read()
Uses
exco_module
maximum_data_module
input_file_module
constituent_mass_module
Arguments
n/a
I/O
I/O units used in this subroutine.
Unit Type Filename
in_exco%exco Input not specified
Outside Variables and Types
type(export_coefficient_datafiles) (1 attribute from exco_module)
Attribute Name Description
exco_db
type (6 attributes from maximum_data_module)
Attribute Name Description
db_mx%exco None
in_exco%exco None
cs_db%num_salts None
cs_db%num_pests None
cs_db%num_metals None
cs_db%num_paths None
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure.
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
  17 eof = 0
  20 inquire (file=in_exco%exco, exist=i_exist)
IF (i_exist .or. in_exco%exco /= "null") THEN Lines 21-51
  22 do
  23 open (107,file=in_exco%exco)
  24 read (107,*,iostat=eof) titldum
  25 if (eof < 0) exit
  26 read (107,*,iostat=eof) header
  27 if (eof < 0) exit
  28 imax = 0
  35 db_mx%exco = imax
  37 allocate (exco_db(0:imax))
  38 rewind (107)
  39 read (107,*,iostat=eof) titldum
  40 if (eof < 0) exit
  41 read (107,*,iostat=eof) header
  42 if (eof < 0) exit
  48 close (107)
  49 exit
DO while (eof == 0) Lines 29-33
  30 read (107,*,iostat=eof) titldum
  31 if (eof < 0) exit
  32 imax = imax + 1
END DOLine 33
DO ii = 1, imax Lines 44-47
  45 read (107,*,iostat=eof) exco_db(ii)
  46 if (eof < 0) exit
END DOLine 47
END IFLine 51
  54 call exco_read_om
  55 if (cs_db%num_pests > 0) call exco_read_pest
  56 if (cs_db%num_paths > 0) call exco_read_path
  57 if (cs_db%num_metals > 0) call exco_read_hmet
  58 if (cs_db%num_salts > 0) call exco_read_salt
  60 return
Allocations
Memory allocations and deallocations grouped by variable.
Variable Allocations Deallocations
exco_db line 37 none
Calls
Calls
Procedures called by this subroutine.
Local Variables
Type Visibility Attributes Name Initial
character, private :: titldum
character, private :: header
integer, private :: eof
integer, private :: imax
logical, private :: i_exist
integer, private :: ii
Call graph
exco_db_read calls exco_read_hmet, exco_read_om, exco_read_path, exco_read_pest, exco_read_salt