hru_hyds – TestDataProject
hru_hyds Subroutine
176 statements
Source File
subroutine hru_hyds()
Called From
n/a
Arguments
n/a
Outside Variables and Types
type (11 attributes from basin_module)
Attribute Name Description
bsn_cc%gampt None
time%step None
time%dtm None
cs_db%num_paths None
cs_db%num_salts None
cs_db%num_tot None
cs_db%num_cs None
cs_db%num_pests None
w_temp%sno_mlt None
w_temp%sur_lat None
w%tave None
type(constituent_mass) (1 attribute from constituent_mass_module)
Attribute Name Description
hin_csz
type(all_constituent_hydrograph) (1 attribute from constituent_mass_module)
Attribute Name Description
obcs
integer (2 attributes from hydrograph_module)
Attribute Name Description
icmd
|
ihru
none |HRU number
Read more…
type(hyd_output) (2 attributes from hydrograph_module)
Attribute Name Description
hd
hz
type(object_connectivity) (1 attribute from hydrograph_module)
Attribute Name Description
ob
type(output_losses) (1 attribute from output_landscape_module)
Attribute Name Description
hls_d
type(hydrologic_response_unit) (1 attribute from hru_module)
Attribute Name Description
hru
real (40 attributes from hru_module)
Attribute Name Description
qday
mm |surface runoff that reaches main channel during day in HRU
Read more…
satexq_chan
mm |saturation excess runoff that reaches main channel during day in HRU
Read more
…
Read more…
qp_cms
snomlt
qtile
sanyld
silyld
clayld
sagyld
lagyld
tconc
surqsolp
doxq
percn
cbodu
chl_a
latno3
latq
tileno3
sedminpa
sedminps
sedorgn
sedorgp
sedyld
sepbtm
surqno3
surqsalt
latqsalt
tilesalt
percsalt
urbqsalt
wetqsalt
surqcs
rtb cs
latqcs
rtb cs
tilecs
rtb cs
perccs
rtb cs
urbqcs
rtb cs
sedmcs
rtb cs
wetqcs
rtb cs
hhsurfq
type(object_pesticide_balance) (1 attribute from output_ls_pesticide_module)
Attribute Name Description
hpestb_d
Uses
basin_module
time_module
constituent_mass_module
hydrograph_module
output_landscape_module
hru_module
climate_module
output_ls_pesticide_module
I/O
n/a
Local Variables
Type Visibility Attributes Name Initial
integer, public :: j = 0
real, public :: cnv_m3 = 0.
real, public :: cnv_kg = 0.
real, public :: cnv_ppm = 0.
integer, public :: iob = 0
integer, public :: ihyd = 0
integer, public :: ipest = 0
integer, public :: ipath = 0
integer, public :: isalt = 0
integer, public :: ics = 0
integer, public :: istep = 0
integer, public :: istep_bak = 0
integer, public :: day_cur = 0
integer, public :: day_next = 0
integer, public :: tinc = 0
integer, public :: inext_step = 0
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure. Use mouse wheel to zoom, drag to pan.
Reset Zoom Help
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
~ ~ ~ PURPOSE ~ ~ ~ (line 3)
this subroutine summarizes data for subbasins with multiple HRUs and (line 4)
prints the daily output.hru file (line 5)
assign reach loadings for subbasin (line 43)
zero out hydrograph storage locations (line 44)
   8 sagyld, sanyld, silyld, sedminpa, sedminps, sedorgn, sedorgp, sepbtm, surqno3, surqsolp, tileno3,     &
   9 sedyld, latno3, qtile, tconc, satexq_chan, surqsalt, latqsalt, tilesalt, percsalt, urbqsalt,          & !rtb salt
  10 snomlt, wetqsalt,                                                                                     &
  11 surqcs, latqcs, tilecs, perccs, sedmcs, urbqcs, wetqcs !rtb cs
  39 j = ihru
  40 cnv_m3 = hru(j)%area_ha * 10.
  41 cnv_kg = hru(j)%area_ha
  45 iob = icmd
  46 ob(icmd)%hd(1) = hz
  47 ob(icmd)%hd(2) = hz
  48 ob(icmd)%hd(3) = hz
  49 ob(icmd)%hd(4) = hz
  50 ob(icmd)%hd(5) = hz
IF (cs_db%num_tot > 0) THEN Lines 51-57
  52 obcs(icmd)%hd(1) = hin_csz
  53 obcs(icmd)%hd(2) = hin_csz
  54 obcs(icmd)%hd(3) = hin_csz
  55 obcs(icmd)%hd(4) = hin_csz
  56 obcs(icmd)%hd(5) = hin_csz
END IFLine 57
surface runoff hydrograph (3) (line 59)
  60 ob(icmd)%hdsep%flo_surq = qday * cnv_m3            !!rtb gwflow - hydrograph separation (surface runoff)
  61 ob(icmd)%hdsep%flo_satexsw = satexq_chan * cnv_m3  !!rtb gwflow - hydrograph separation (saturation excess runoff)
  62 ob(icmd)%peakrate = qp_cms
  63 ob(icmd)%hd(3)%temp = 5. + .75 * w%tave         !!wtmp
  64 ob(icmd)%hd(3)%flo = qday * cnv_m3              !!qdr m3/d
  65 ob(icmd)%hd(3)%sed = sedyld(j)                  !!sedyld
  66 ob(icmd)%hd(3)%orgn = sedorgn(j) * cnv_kg       !!sedorgn
  67 ob(icmd)%hd(3)%sedp = (sedorgp(j) + sedminpa(j) +                 &
  68 sedminps(j)) * cnv_kg         !!sedorgp & sedminps
  69 ob(icmd)%hd(3)%no3 = surqno3(j) * cnv_kg        !!surqno3 & latno3 & no3gw
  70 ob(icmd)%hd(3)%solp = (surqsolp(j) + hls_d(j)%tilelabp) * cnv_kg      !!surqsolp & sedminpa
  71 ob(icmd)%hd(3)%chla = chl_a(j) *cnv_kg          !!chl_a
  72 ob(icmd)%hd(3)%nh3 = 0.                         !! NH3
  73 ob(icmd)%hd(3)%no2 = 0.                         !! NO2
IF (ob(icmd)%hd(3)%flo > 0.01) THEN Lines 74-75
  75 cnv_ppm = 1. / (1000. * ob(icmd)%hd(3)%flo)
END IFLine 75
ELSE Lines 76-78
  77 cnv_ppm = 0.
END IF Line 78
  79 ob(icmd)%hd(3)%cbod = cbodu(j) * cnv_ppm        !!cbodu
  80 ob(icmd)%hd(3)%dox = doxq(j) * cnv_ppm          !!doxq & soxy
  82 ob(icmd)%hd(3)%san = sanyld(j)                  !! detached sand
  83 ob(icmd)%hd(3)%sil = silyld(j)                  !! detached silt
  84 ob(icmd)%hd(3)%cla = clayld(j)                  !! detached clay
  85 ob(icmd)%hd(3)%sag = sagyld(j)                  !! detached small aggregates
  86 ob(icmd)%hd(3)%lag = lagyld(j)                  !! detached large aggregates
DO ipest = 1, cs_db%num_pests Lines 89-91
  90 obcs(icmd)%hd(3)%pest(ipest) = (hpestb_d(j)%pest(ipest)%surq + hpestb_d(j)%pest(ipest)%sed) * cnv_kg
END DOLine 91
DO ipath = 1, cs_db%num_paths Lines 92-94
  93 obcs(icmd)%hd(3)%path(ipath) = 0
END DOLine 94
DO isalt = 1, cs_db%num_salts !rtb salt Lines 95-97
  96 obcs(icmd)%hd(3)%salt(isalt) = (surqsalt(j,isalt)+urbqsalt(j,isalt)+wetqsalt(j,isalt)) * cnv_kg !kg of each salt ion
END DOLine 97
DO ics = 1, cs_db%num_cs !rtb cs Lines 98-100
  99 obcs(icmd)%hd(3)%cs(ics) = (surqcs(j,ics)+sedmcs(j,ics)+urbqcs(j,ics)+wetqcs(j,ics)) * cnv_kg !kg of each constituent (surface runoff + attached)
END DOLine 100
 103 ob(icmd)%hd(2)%flo = sepbtm(j) * cnv_m3           !! recharge flow
 104 ob(icmd)%hd(2)%no3 = percn(j) * cnv_kg            !! recharge nitrate
DO ipest = 1, cs_db%num_pests Lines 106-108
 107 obcs(icmd)%hd(2)%pest(ipest) = hpestb_d(j)%pest(ipest)%perc * cnv_kg
END DOLine 108
DO ipath = 1, cs_db%num_paths Lines 109-111
 110 obcs(icmd)%hd(2)%path(ipath) = 0
END DOLine 111
DO isalt = 1, cs_db%num_salts !rtb salt Lines 112-114
 113 obcs(icmd)%hd(2)%salt(isalt) = percsalt(j,isalt) * cnv_kg !kg of each salt ion
END DOLine 114
DO ics = 1, cs_db%num_cs !rtb cs Lines 115-117
 116 obcs(icmd)%hd(2)%cs(ics) = perccs(j,ics) * cnv_kg !kg of each constituent
END DOLine 117
 120 ob(icmd)%hd(4)%flo = latq(j) * cnv_m3                 !! lateral flow
 121 ob(icmd)%hdsep%flo_latq = latq(j) * cnv_m3            !!rtb gwflow - hydrograph separation
 122 ob(icmd)%hd(4)%no3 = latno3(j) * cnv_kg
DO ipest = 1, cs_db%num_pests Lines 124-126
 125 obcs(icmd)%hd(4)%pest(ipest) = hpestb_d(j)%pest(ipest)%latq * cnv_kg
END DOLine 126
DO ipath = 1, cs_db%num_paths Lines 127-129
 128 obcs(icmd)%hd(4)%path(ipath) = 0
END DOLine 129
DO isalt = 1, cs_db%num_salts !rtb salt Lines 130-132
 131 obcs(icmd)%hd(4)%salt(isalt) = latqsalt(j,isalt) * cnv_kg !kg of each salt ion
END DOLine 132
DO ics = 1, cs_db%num_cs !rtb cs Lines 133-135
 134 obcs(icmd)%hd(4)%cs(ics) = latqcs(j,ics) * cnv_kg !kg of each constituent
END DOLine 135
 138 ob(icmd)%hd(5)%flo = qtile * cnv_m3               !! tile flow
 139 ob(icmd)%hd(5)%no3 = tileno3(j) * cnv_kg          !! tile flow nitrate
DO ipest = 1, cs_db%num_pests Lines 141-143
 142 obcs(icmd)%hd(5)%pest(ipest) = hpestb_d(j)%pest(ipest)%tileq * cnv_kg
END DOLine 143
DO ipath = 1, cs_db%num_paths Lines 144-146
 145 obcs(icmd)%hd(5)%path(ipath) = 0.
END DOLine 146
 150 ob(icmd)%hd(2)%temp = w_temp%sur_lat
IF (snomlt > 0.1) THEN Lines 152-153
 153 ob(icmd)%hd(3)%temp = w_temp%sno_mlt
END IFLine 153
ELSE Lines 154-156
 155 ob(icmd)%hd(3)%temp = w_temp%sur_lat
END IF Line 156
 158 ob(icmd)%hd(4)%temp = w_temp%sur_lat
 160 ob(icmd)%hd(5)%temp = w_temp%sur_lat
DO isalt = 1, cs_db%num_salts !rtb salt Lines 161-163
 162 obcs(icmd)%hd(5)%salt(isalt) = tilesalt(j,isalt) * cnv_kg !kg of each salt ion
END DOLine 163
DO ics = 1, cs_db%num_cs !rtb cs Lines 164-166
 165 obcs(icmd)%hd(5)%cs(ics) = tilecs(j,ics) * cnv_kg !kg of each constituent
END DOLine 166
DO ihyd = 3, 5 Lines 169-171
 170 ob(icmd)%hd(1) = ob(icmd)%hd(1) + ob(icmd)%hd(ihyd)
END DOLine 171
DO ipest = 1, cs_db%num_pests Lines 174-177
 175 obcs(icmd)%hd(1)%pest(ipest) = obcs(icmd)%hd(3)%pest(ipest) + obcs(icmd)%hd(4)%pest(ipest) +    &
 176 obcs(icmd)%hd(5)%pest(ipest)
END DOLine 177
DO ipath = 1, cs_db%num_paths Lines 178-180
 179 obcs(icmd)%hd(1)%path(ipath) = 0
END DOLine 180
DO isalt = 1, cs_db%num_salts !rtb salt Lines 181-184
 182 obcs(icmd)%hd(1)%salt(isalt) = obcs(icmd)%hd(3)%salt(isalt) + obcs(icmd)%hd(4)%salt(isalt) +    &  !total = surface runoff + lateral flow + tile flow
 183 obcs(icmd)%hd(5)%salt(isalt)
END DOLine 184
DO ics = 1, cs_db%num_cs !rtb cs Lines 185-188
 186 obcs(icmd)%hd(1)%cs(ics) = obcs(icmd)%hd(3)%cs(ics) + obcs(icmd)%hd(4)%cs(ics) +    &  !total = surface runoff + lateral flow + tile flow
 187 obcs(icmd)%hd(5)%cs(ics)
END DOLine 188
set subdaily hydrographs (line 190)
set previous and next days for adding previous and translating to next (line 191)
 192 day_cur = ob(icmd)%day_cur
 193 day_next = day_cur + 1
 194 if (day_next > ob(icmd)%day_max) day_next = 1
IF (time%step > 1) THEN Lines 196-225
IF (bsn_cc%gampt == 1) THEN Lines 197-220
hhsurfq from sq_greenampt - mm (line 198)
translate the hydrogrpah by time of concentration - no attenuation (line 201)
 199 ob(icmd)%hyd_flo(day_cur,:) = ob(icmd)%hyd_flo(day_cur,:) + hhsurfq(j,:) * cnv_m3
 202 ob(icmd)%hyd_flo(day_next,:) = 0.
IF (tconc(j) * 60. > time%dtm) THEN Lines 203-220
move to next days hydrograph (line 206)
shift current day hydrograph (line 211)
 204 tinc = int (tconc(j) * 60. / time%dtm)
 205 tinc = min1 (float(time%step), float(tinc))
DO istep = 1, tinc Lines 207-210
 208 inext_step = time%step - tinc + istep
 209 ob(icmd)%hyd_flo(day_next,istep) = ob(icmd)%hyd_flo(day_cur,inext_step)
END DOLine 210
DO istep = 1, time%step Lines 212-219
 213 istep_bak = time%step - istep + 1
IF (istep_bak <= tinc) THEN Lines 214-215
 215 ob(icmd)%hyd_flo(day_cur,istep_bak) = 0.
END IFLine 215
ELSE Lines 216-218
 217 ob(icmd)%hyd_flo(day_cur,istep_bak) = ob(icmd)%hyd_flo(day_cur,istep_bak-tinc)
END IF Line 218
END DOLine 219
END IFLine 220
END IFLine 220
ELSE Lines 221-225
use unit hydrograph and daily runoff (line 222)
 223 call flow_hyd_ru_hru (ob(icmd)%day_cur, ob(icmd)%hd(3)%flo, ob(icmd)%hd(4)%flo,     &
 224 ob(icmd)%hd(5)%flo, ob(icmd)%uh, ob(icmd)%hyd_flo)
END IF Line 225
END IFLine 225
ELSE Lines 226-229
set to total runoff needed when summing incoming in command (line 227)
 228 ob(icmd)%hyd_flo(day_cur,1) = ob(icmd)%hd(1)%flo
END IF Line 229
 231 return
Allocations
n/a
Calls
Procedures Called
List of procedures called by this Subroutine.
min1
float
flow_hyd_ru_hru
Call Graph
Visual representation of procedures called by this Subroutine.
Call graph
hru_hyds calls float, flow_hyd_ru_hru, min1