hru_control – test-src-project
hru_control Subroutine
625 statements
Source File
subroutine hru_control()
Uses
output_ls_pesticide_module
hru_module
constituent_mass_module
reservoir_module
cs_module
septic_data_module
mgt_operations_module
output_landscape_module
plant_module
gwflow_module
plant_data_module
salt_module
conditional_module
climate_module
carbon_module
tillage_data_module
reservoir_data_module
time_module
organic_mineral_mass_module
basin_module
hydrograph_module
soil_module
water_body_module
Arguments
n/a
I/O
I/O units used in this subroutine.
Unit Type Filename
unit_100100 Output not specified
Outside Variables and Types
type(object_pesticide_balance) (1 attribute from output_ls_pesticide_module)
Attribute Name Description
hpestb_d
integer (18 attributes from hru_module)
Attribute Name Description
isep
|
ulu
|
iwgen
|
ipl
iseptic
septic variables for output.std
ihru
none |HRU number
Read more…
nd_30
i_sep
yr_skip
grz_days
igrz
ndeat
mgt_ops
tillage_switch
tillage_days
gw_solute_flag
|main flag
iwst
|
icmd
|
type (31 attributes from hru_module)
Attribute Name Description
luse%urb_lu None
cs_db%num_salts None
cs_db%num_paths None
cs_db%num_pests None
cs_db%num_cs None
d_tbl%acts None
w%tmax None
w%windsp None
w%tave None
w%rhum None
w%precip None
w%ts None
w%tmin None
w%solrad None
time%yrc None
time%end_yr None
time%mo None
time%day None
time%day_mo None
time%step None
pl_yield%m None
bsn_cc%gwflow None
bsn_cc%crk None
bsn_cc%cswat None
bsn_cc%sol_P_model None
bsn_cc%lapse None
ht2%flo None
ht2%sed None
ht2%no3 None
sp_ob%gwflow None
sp_ob1%ru None
type(hydrologic_response_unit) (1 attribute from hru_module)
Attribute Name Description
hru
real (80 attributes from hru_module)
Attribute Name Description
precip_eff
mm |daily effective precip for runoff calculations = precipday + ls_overq + snomlt - canstor |precip_eff = precipday + ls_overq - snofall + snomlt - canstor
Read more…
qday
mm |surface runoff that reaches main channel during day in HRU
Read more…
satexq_chan
mm |saturation excess runoff that reaches main channel during day in HRU
Read more
…
Read more…
strsa_av
strsn_av
strsp_av
strstmp_av
qp_cms
snomlt
snofall
fixn
qtile
inflpcp
mm |amount of precipitation that infiltrates
Read more…
fertn
fertp
grazn
grazp
canev
usle
pet_day
ep_day
es_day
ls_overq
latqrunon
etday
sed_con
orgn_con
orgp_con
soln_con
solp_con
filterw
cnday
usle_cfac
surqsolp
pplnt
brt
percn
qdr
latno3
latq
nplnt
tileno3
sedminpa
sedminps
sedorgn
sedorgp
sedyld
sepbtm
surfq
surqno3
surqsalt
latqsalt
tilesalt
percsalt
gwupsalt
urbqsalt
wetqsalt
wtspsalt
surqcs
rtb cs
latqcs
rtb cs
tilecs
rtb cs
perccs
rtb cs
gwupcs
rtb cs
urbqcs
rtb cs
sedmcs
rtb cs
wetqcs
rtb cs
wtspcs
rtb cs
phubase
bss
surf_bs
gwsoilq
rtb gwflow
satexq
rtb gwflow
bss_ex
rtb gwflow
gwsoiln
rtb gwflow
gwsoilp
rtb gwflow
satexn
rtb gwflow
gwflow_perc
|
Read more…
etremain
|
gwflow_percsol
kg/ha |solute mass leaving the soil profile
Read more…
bmix_eff
|none |biological mixing efficieny
Read more…
type(soil_constituent_mass) (1 attribute from constituent_mass_module)
Attribute Name Description
cs_soil
type(wetland) (1 attribute from reservoir_module)
Attribute Name Description
wet_ob
type(object_cs_balance) (1 attribute from cs_module)
Attribute Name Description
hcsb_d
type(septic_system) (1 attribute from septic_data_module)
Attribute Name Description
sep
type(management_schedule) (1 attribute from mgt_operations_module)
Attribute Name Description
sched
type(output_waterbal) (1 attribute from output_landscape_module)
Attribute Name Description
hwb_d
type(output_nutbal) (1 attribute from output_landscape_module)
Attribute Name Description
hnb_d
type(output_losses) (1 attribute from output_landscape_module)
Attribute Name Description
hls_d
type(output_plantweather) (1 attribute from output_landscape_module)
Attribute Name Description
hpw_d
type(plant_community) (1 attribute from plant_module)
Attribute Name Description
pcom
type(plant_db) (1 attribute from plant_data_module)
Attribute Name Description
pldb
type(object_salt_balance) (1 attribute from salt_module)
Attribute Name Description
hsaltb_d
type(decision_table) (2 attributes from conditional_module)
Attribute Name Description
dtbl_lum
dtbl_flo
type(wgn_parms) (1 attribute from climate_module)
Attribute Name Description
wgn_pms
type(weather_station) (1 attribute from climate_module)
Attribute Name Description
wst
type(climate_measured_data) (1 attribute from climate_module)
Attribute Name Description
tmp
character(len=1) (2 attributes from climate_module)
Attribute Name Description
salt_atmo
cs_atmo
type(carbon_soil_transformations) (2 attributes from carbon_module)
Attribute Name Description
hscfz
hru soil carbon transformations
hscf_d
type(carbon_soil_gain_losses) (2 attributes from carbon_module)
Attribute Name Description
hscz
hru soil carbon gains and losses
hsc_d
type(carbon_residue_gain_losses) (2 attributes from carbon_module)
Attribute Name Description
hrcz
hru residue carbon gains and losses
hrc_d
type(carbon_plant_gain_losses) (2 attributes from carbon_module)
Attribute Name Description
hpcz
hru plant carbon gains and losses
hpc_d
type(reservoir_data_char_input) (1 attribute from reservoir_data_module)
Attribute Name Description
wet_dat_c
type(soil_profile_mass) (1 attribute from organic_mineral_mass_module)
Attribute Name Description
soil1
type(plant_community_mass) (1 attribute from organic_mineral_mass_module)
Attribute Name Description
pl_mass
type(organic_mass) (1 attribute from organic_mineral_mass_module)
Attribute Name Description
plt_mass_z
type(hyd_output) (5 attributes from hydrograph_module)
Attribute Name Description
hz
ht1
res
wet
wet_stor
wetland storage in flood plain
type(object_connectivity) (1 attribute from hydrograph_module)
Attribute Name Description
ob
type(irrigation_water_transfer) (1 attribute from hydrograph_module)
Attribute Name Description
irrig
dimension by hru
type(soil_profile) (1 attribute from soil_module)
Attribute Name Description
soil
!! Bang Comments
~ ~ ~ PURPOSE ~ ~ ~
this subroutine controls the simulation of the land phase of the
hydrologic cycle
adjust precip and temperature for elevation using lapse rates zero pesticide balance variables zero all variables except pest in soil and in/on plant ht1== deposition: write to deposition.out ht2== outflow from inflow: added to hru generated flows check auto operations check day of future fertilizer application if end of year, reset the one time operation per year increment days since last plant and harvest update base zero total heat units zero stresses calculate albedo for day calculate soil temperature for soil layers compute canopy interception compute snow melt route overland flow across hru - add tile flow if not subirrigation or saturated buffer route incoming surface runoff add surface runon to wetland route across hru - infiltrate and deposit sediment add lateral flow soil water Route incoming lateral soil flow add tile flow to tile (saturated buffer) add aquifer flow to bottom soil layer and redistribute upwards Route incoming aquifer flow compute crack volume compute evapotranspiration perform management operations compute surface runoff processes if wetland - no runoff or sediment yield - all constituents transported in surface runoff and sediment will be zero ht2%sed==sediment routed across hru from surface runon check wetland/paddy continuous irrigation Jaehak 2023 manual irrigation on if ponding depth is lower than the threshold depth wetland/paddy processes compute effective rainfall (amount that percs into soil) for wetland use seepage into soil from ponded water no wetland (no ponded water) add irrigation to subdaily effective precip perform soil water routing compute peak rate similar to swat-deg using SCS triangular unit hydrograph
graze only if adequate biomass in HRU if total above ground biomass is available - graze check to set if grazing period is over compute residue decomposition and nitrogen and phosphorus mineralization compute residue decomposition and nitrogen and phosphorus mineralization compute biozone processes in septic HRUs if 1) current is septic hru and 2) soil temperature is above zero compute plant community partitions check irrigation demand decision table for water allocation (after adding irrigation) iauto points to pcom(j)%dtbl(iauto) for days between operation check monsoon season for tropical plants compute plant biomass, leaf, root and seed growth reset harvested biomass and number of harvests for yearly yield output compute total parms for all plants in the community compute aoil water content to 300 mm depth compute actual ET for day in HRU compute pesticide washoff
compute pesticide uptake compute pesticide degradation compute pesticide movement in soil sum total pesticide in soil static carbon organic n in runoff C-Farm (Armen) c and organic n in runoff SWAT-C Xuesong -- c and organic n in runoff add nitrate in rainfall to soil profile compute nitrate movement leaching compute phosphorus movement compute pathogen transport compute loadings from urban areas compute sediment loading in lateral flow and add to sedyld lag nutrients and sediment in surface runoff lag subsurface flow and nitrate in subsurface flow compute reduction in pollutants due to edge-of-field filter strip compute reduction in pollutants due to in field grass waterway compute reduction in pollutants due to in fixed BMP eff ht2%flo is outflow from wetland or total saturation excess if no wetland mm = m3/ha ha/10000m2 1000mm/m calculate amount of surface runoff during day (qday) and store the remainder check if hru is a source for a saturated buffer use decision table set amount of tile flow to send to buffer hru convert to mm of the receiving hru and adjust for fraction of incoming hru compute water yield for HRU compute chl-a, CBOD and dissolved oxygen loadings add evap from impounded water (wetland) to et and esoil set hydrographs for direct routing or landscape unit
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure.
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
   8 tillage_days, ndeat, qdr, phubase, sedyld, surfq, grz_days,                              &
   9 yr_skip, latq, sepbtm, igrz, iseptic, i_sep, filterw, sed_con, soln_con, solp_con,       &
  10 orgn_con, orgp_con, cnday, percn, tileno3, sedorgn, sedorgp, surqno3, latno3,            &
  11 surqsolp, sedminpa, sedminps, fertn, fertp, fixn, grazn, grazp, ipl, qp_cms, qtile,      &
  12 snofall, snomlt, usle, canev, ep_day, es_day, etday, inflpcp, isep, iwgen, ls_overq,     &
  13 nd_30, pet_day, precip_eff, qday, latqrunon, gwsoilq, satexq, surf_bs, bss, bss_ex, brt, &
  14 gwsoiln, gwsoilp, satexn, satexq_chan, surqsalt, latqsalt, tilesalt, percsalt, urbqsalt, & !rtb gwflow; rtb salt
  15 wetqsalt, wtspsalt,gwupsalt, usle_cfac,                                                  &
  16 surqcs, latqcs, tilecs, perccs, gwupcs, sedmcs, urbqcs, wetqcs, wtspcs                         !rtb cs
  87 j = ihru
  90 sw_volume_begin = 0.
DO j1=1,soil(j)%nly Lines 91-93
  92 sw_volume_begin = sw_volume_begin + soil(j)%phys(j1)%st
END DOLine 93
  98 ulu = hru(j)%luse%urb_lu
  99 iob = hru(j)%obj_no
 100 iwst = ob(iob)%wst
 101 iwgen = wst(iwst)%wco%wgn
 102 ith = hru(j)%dbs%topo
 103 iwgn = wst(iwst)%wco%wgn
 104 ires =  hru(j)%dbs%surf_stor
 105 isched = hru(j)%mgt_ops
 107 w = wst(iwst)%weat
IF (bsn_cc%lapse == 1) THEN Lines 109-115
 110 w%precip = w%precip + ob(iob)%plaps
 111 w%precip = max (0., w%precip)
 112 w%tmax = w%tmax + ob(iob)%tlaps
 113 w%tmin = w%tmin + ob(iob)%tlaps
 114 w%tave = w%tave + ob(iob)%tlaps
END IFLine 115
 116 precip_eff = w%precip
 118 hsc_d(j) = hscz
 119 hrc_d(j) = hrcz
 120 hpc_d(j) = hpcz
 121 hscf_d(j) = hscfz
 122 hru(j)%water_seep = 0.
 123 irrig(j)%demand = 0.
 124 hnb_d(j)%nuptake = 0.
 125 hnb_d(j)%puptake = 0.
 126 hwb_d(j)%wet_out = 0.
 127 hnb_d(j)%denit = 0.
IF (bsn_cc%cswat == 2) THEN Lines 129-140
IF (tillage_switch(ihru) .eq. 1) THEN Lines 130-139
IF (tillage_days(ihru) .ge. 30) THEN Lines 131-133
 132 tillage_switch(ihru) = 0
 133 tillage_days(ihru) = 0
END IFLine 133
ELSE Lines 134-136
 135 tillage_days(ihru) = tillage_days(ihru) + 1
END IF Line 136
END IFLine 139
END IFLine 140
IF (cs_db%num_pests > 0) THEN Lines 143-148
DO ipest = 1, cs_db%num_pests Lines 144-147
 146 hpestb_d(j)%pest(ipest) = hpestb_d(j)%pest(ipest) * 0.
END DOLine 147
END IFLine 148
 150 call varinit
 151 nd_30 = nd_30 + 1
 152 if (nd_30 > 30) nd_30 = 1
 156 ht1 = hz
 157 ht2 = hz
IF (sched(isched)%num_autos > 0) THEN Lines 160-197
DO iauto = 1, sched(isched)%num_autos Lines 161-185
 162 id = sched(isched)%num_db(iauto)
 163 jj = j
 164 d_tbl => dtbl_lum(id)
 165 call conditions (jj, iauto)
 166 call actions (jj, iob, iauto)
IF (pcom(ihru)%fert_fut_num > 0) THEN Lines 169-177
DO ifrt = 1, pcom(ihru)%fert_fut_num Lines 170-176
IF (pcom(ihru)%fert_fut(ifrt)%day_fert == time%day) THEN Lines 171-175
 172 call pl_fert (pcom(ihru)%fert_fut(ifrt)%fertnum,                       &
 173 pcom(ihru)%fert_fut(ifrt)%fert_kg, pcom(ihru)%fert_fut(ifrt)%appnum)
 174 pcom(ihru)%fert_fut(ifrt)%day_fert = 0
END IFLine 175
END DOLine 176
END IFLine 177
IF (time%end_yr == 1) THEN Lines 180-184
DO iac = 1, d_tbl%acts Lines 181-183
 182 pcom(j)%dtbl(iauto)%num_actions(iac) = 1
END DOLine 183
END IFLine 184
END DOLine 185
IF (time%end_yr == 1) THEN Lines 186-188
 187 pcom(j)%rot_yr = pcom(j)%rot_yr + 1
END IFLine 188
DO iauto = 1, sched(isched)%num_autos Lines 189-196
 190 id = sched(isched)%num_db(iauto)
DO iac = 1, dtbl_lum(id)%acts Lines 191-195
IF (pcom(j)%dtbl(iauto)%days_act(iac) > 0) THEN Lines 192-194
 193 pcom(j)%dtbl(iauto)%days_act(iac) = pcom(j)%dtbl(iauto)%days_act(iac) + 1
END IFLine 194
END DOLine 195
END DOLine 196
END IFLine 197
 200 pcom(j)%days_plant = pcom(j)%days_plant + 1
 201 pcom(j)%days_harv = pcom(j)%days_harv + 1
 202 pcom(j)%days_kill = pcom(j)%days_kill + 1
 203 pcom(j)%days_irr = pcom(j)%days_irr + 1
IF (w%tave > 0. .and. wgn_pms(iwgn)%phutot > 0.01) THEN Lines 206-208
 207 phubase(j) = phubase(j) + w%tave / wgn_pms(iwgn)%phutot
END IFLine 208
DO ipl = 1, pcom(j)%npl Lines 211-218
 212 pcom(j)%plstr(ipl)%strsw = 1.
 213 pcom(j)%plstr(ipl)%strst = 1.
 214 pcom(j)%plstr(ipl)%strsn = 1.
 215 pcom(j)%plstr(ipl)%strsp = 1.
 216 pcom(j)%plstr(ipl)%strsa = 1.
 217 pcom(j)%plstr(ipl)%strss = 1.
END DOLine 218
 221 call albedo
IF (cs_db%num_salts > 0) THEN Lines 224-226
 225 call salt_chem_hru
END IFLine 226
IF (cs_db%num_cs > 0) THEN Lines 229-232
 230 call cs_rctn_hru
 231 call cs_sorb_hru
END IFLine 232
 235 call stmp_solt
 238 call sq_canopyint
 241 call sq_snom
 244 tile_fr_surf = 1.   !assume all tile goes overland until get saturated buffer dtbl
IF (ob(icmd)%hin_sur%flo > 1.e-6) THEN Lines 245-255
IF (ires > 0) THEN Lines 247-250
 249 ht1 = ob(icmd)%hin_sur + tile_fr_surf * ob(icmd)%hin_til
 250 wet(j) = wet(j) + ht1
END IFLine 250
ELSE Lines 251-254
 253 call rls_routesurf (icmd, tile_fr_surf)
END IF Line 254
END IFLine 255
IF (ob(icmd)%hin_lat%flo > 0) THEN Lines 258-261
 260 call rls_routesoil (icmd)
END IFLine 261
IF (hru(j)%sb%sb_db%hru_rcv == j) THEN Lines 264-266
 265 call rls_routetile (icmd, tile_fr_surf)
END IFLine 266
IF (ob(icmd)%hin_aqu%flo > 0) THEN Lines 269-272
 271 call rls_routeaqu (icmd)
END IFLine 272
 275 if (bsn_cc%crk == 1) call sq_crackvol
 278 call et_pot
 279 call et_act
 282 if (yr_skip(j) == 0) call mgt_operatn
IF (ires == 0) THEN Lines 285-286
 286 call surface
END IFLine 286
ELSE Lines 287-293
 290 surfq(j) = 0.
 291 irrig(j)%runoff = 0.
 292 sedyld(j) = 0.
END IF Line 293
 296 sedyld(j) = sedyld(j) + ht2%sed
IF (hru(j)%paddy_irr > 0) THEN Lines 300-304
IF (wet_ob(j)%depth < hru(j)%irr_hmin / 1000.) THEN Lines 301-303
 302 call wet_irrp
END IFLine 303
END IFLine 304
 307 ht2 = hz
 308 wet_outflow = 0.
IF (ires > 0) THEN Lines 309-310
 310 call wetland_control
END IFLine 310
ELSE Lines 311-314
 312 ht2%flo = wet(j)%flo * hru(j)%area_ha * 10.
 313 wet(j)%flo = 0.
END IF Line 314
IF (ires > 0) THEN Lines 317-319
 319 inflpcp = hru(j)%water_seep
END IFLine 319
ELSE Lines 320-323
 322 inflpcp = precip_eff - surfq(j)
END IF Line 323
 324 inflpcp = Max(0., inflpcp)
IF (time%step > 1) THEN Lines 327-329
 328 w%ts(:) = w%ts(:) + irrig(j)%applied / time%step
END IFLine 329
 332 call swr_percmain
 335 bss_ex(1,j) = bss_ex(1,j) + satexq(j)
 336 satexq_chan = bss_ex(1,j) * brt(j)
 337 bss_ex(1,j) = bss_ex(1,j) - satexq_chan
IF (igrz(j) == 1) THEN Lines 347-356
 348 ndeat(j) = ndeat(j) + 1
 350 call pl_graze
IF (ndeat(j) == grz_days(j)) THEN Lines 352-355
 353 igrz(j) = 0
 354 ndeat(j) = 0
END IFLine 355
END IFLine 356
IF (bsn_cc%cswat == 0) THEN Lines 359-362
 360 call nut_nminrl
 361 call nut_nitvol
END IFLine 362
IF (bsn_cc%cswat == 2) THEN Lines 365-369
 366 if (bmix_eff > 1.e-6) call mgt_newtillmix (ihru, bmix_eff, 0)
 367 call cbn_rsd_decomp      ! added by JC and FG, modified from nut_minrln.f90
 368 call cbn_zhang2
END IFLine 369
 371 call nut_nitvol
IF (bsn_cc%sol_P_model == 1) THEN Lines 373-374
 374 call nut_pminrl2
END IFLine 374
ELSE Lines 375-377
 376 call nut_pminrl
END IF Line 377
 381 isep = iseptic(j)
IF (sep(isep)%opt /= 0. .and. time%yrc >= sep(isep)%yr) THEN Lines 382-384
 383 if (soil(j)%phys(i_sep(j))%tmp > 0.) call sep_biozone
END IFLine 384
 387 call pl_community
IF (hru(j)%irr_dmd_dtbl > 0) THEN Lines 397-405
 398 id = hru(j)%irr_dmd_dtbl
 399 jj = j
 400 d_tbl => dtbl_lum(id)
 402 iauto = hru(j)%irr_dmd_iauto
 403 call conditions (jj, iauto)
 404 call actions (jj, iob, iauto)
END IFLine 405
 407 soil_prof_labp = 0.
DO ly = 1, soil(j)%nly Lines 408-410
 409 soil_prof_labp = soil_prof_labp + soil1(j)%mp(ly)%lab
END DOLine 410
DO ipl = 1, pcom(j)%npl Lines 413-425
IF (pcom(j)%plcur(ipl)%mseas == "y") THEN Lines 414-424
 415 idp = pcom(j)%plcur(ipl)%idplt
IF (pldb(idp)%trig == "moisture_gro") THEN Lines 416-423
IF (wgn_pms(iwgn)%p_pet_rto > 0.5) THEN Lines 417-422
 418 pcom(j)%plcur(ipl)%phuacc = 0.
 419 pcom(j)%plcur(ipl)%gro = "y"
 420 pcom(j)%plcur(ipl)%idorm = "n"
 421 pcom(j)%plcur(ipl)%mseas = "n"
END IFLine 422
END IFLine 423
END IFLine 424
END DOLine 425
 428 call pl_grow
IF (time%end_yr == 1) THEN Lines 431-436
DO ipl = 1, pcom(j)%npl Lines 432-435
 433 pl_mass(j)%yield_yr(ipl) = plt_mass_z
 434 pcom(j)%plcur(ipl)%harv_num_yr = 0
END DOLine 435
END IFLine 436
 439 strsw_av = 0.; strsa_av = 0.; strsn_av = 0.; strsp_av = 0.; strstmp_av = 0.
 440 strss_av = 0.
 441 npl_gro = 0
DO ipl = 1, pcom(j)%npl Lines 442-453
 443 if (pcom(j)%plcur(ipl)%gro == 'y' .and. pcom(j)%plcur(ipl)%idorm == 'n'       &
 444 .and. pcom(j)%plcur(ipl)%phuacc <= 1.) then
 445 npl_gro = npl_gro + 1
 446 strsw_av = strsw_av + (1. - pcom(j)%plstr(ipl)%strsw)
 447 strsa_av = strsa_av + (1. - pcom(j)%plstr(ipl)%strsa)
 448 strsn_av = strsn_av + (1. - pcom(j)%plstr(ipl)%strsn)
 449 strsp_av = strsp_av + (1. - pcom(j)%plstr(ipl)%strsp)
 450 strss_av = strss_av + (1. - pcom(j)%plstr(ipl)%strss)
 451 strstmp_av = strstmp_av + (1. - pcom(j)%plstr(ipl)%strst)
END DOLine 453
IF (npl_gro > 0) THEN Lines 454-460
 455 strsw_av = strsw_av / npl_gro
 456 strsa_av = strsa_av / npl_gro
 457 strsn_av = strsn_av / npl_gro
 458 strsp_av = strsp_av / npl_gro
 459 strstmp_av = strstmp_av / npl_gro
END IFLine 460
 463 soil(j)%sw_300 = 0.
DO ly = 1, soil(j)%nly Lines 464-477
IF (ly == 1) THEN Lines 465-466
 466 dep = 0.
END IFLine 466
ELSE Lines 467-469
 468 dep = soil(j)%phys(ly-1)%d
END IF Line 469
IF (soil(j)%phys(ly)%d >= 300.) THEN Lines 470-473
 471 soil(j)%sw_300 = soil(j)%sw_300 + soil(j)%phys(ly)%st *         &
 472 (300. - dep) / soil(j)%phys(ly)%thick
 473 exit
END IFLine 473
ELSE Lines 474-476
 475 soil(j)%sw_300 = soil(j)%sw_300 + soil(j)%phys(ly)%st
END IF Line 476
END DOLine 477
 480 etday = ep_day + es_day + canev
 481 es_day = es_day
IF (bsn_cc%gwflow.eq.1) THEN Lines 484-486
 485 etremain(j) = pet_day - etday
END IFLine 486
 489 if (w%precip >= 2.54) call pest_washp
 492 call pest_pl_up
 495 call pest_decay
 498 call pest_lch
 501 call pest_soil_tot
IF (surfq(j) > 0. .and. qp_cms > 1.e-6) THEN Lines 503-524
IF (precip_eff > 0.) THEN Lines 504-523
 505 call pest_enrsb
 506 if (sedyld(j) > 0.) call pest_pesty
 522 call nut_psed
IF (bsn_cc%cswat == 0) THEN Lines 509-511
 510 call nut_orgn
END IFLine 511
IF (bsn_cc%cswat == 1) THEN Lines 514-516
 515 call nut_orgnc
END IFLine 516
IF (bsn_cc%cswat == 2) THEN Lines 519-521
 520 call nut_orgnc2
END IFLine 521
END IFLine 523
END IFLine 524
 527 call nut_nrain
 530 call nut_nlch
IF (ires > 0) THEN Lines 531-544
IF (wet(j)%flo>0) THEN Lines 532-533
 533 sedppm=wet(j)%sed/wet(j)%flo*1000000.
END IFLine 533
ELSE Lines 534-536
 535 sedppm=0.
END IF Line 536
IF (wet_dat_c(ires)%hyd.eq.'paddy') then !.and.time%yrs > pco%nyskip) THEN Lines 537-543
IF (wet_ob(j)%depth > 100.) THEN Lines 538-542
 539 write(100100,'(4(I6,","),20(f20.1,","))') time%yrc,time%mo,time%day_mo,j,w%precip,irrig(j)%applied,hru(j)%water_seep,     &
 540 pet_day,etday,wet_ob(j)%weir_hgt*1000,wet_ob(j)%depth*1000.,ht2%flo/(hru(j)%area_ha*10.),soil(j)%sw,sedppm,ht2%sed*1000, &
 541 wet(j)%no3,ht2%no3,pcom(j)%lai_sum,saltcon
END IFLine 542
END IFLine 543
END IFLine 544
 547 call nut_solp
IF (cs_db%num_salts > 0) THEN Lines 550-556
 554 call salt_roadsalt !add salt in applied road salt to soil profile
 555 call salt_lch ! compute salt leaching
IF (salt_atmo == "y") THEN Lines 551-553
 552 call salt_rain !add salt in atmospheric deposition to soil profile
END IFLine 553
END IFLine 556
IF (cs_db%num_cs > 0) THEN Lines 559-564
 563 call cs_lch
IF (cs_atmo == "y") THEN Lines 560-562
 561 call cs_rain
END IFLine 562
END IFLine 564
IF (cs_db%num_paths > 0.) THEN Lines 567-571
 568 call path_ls_swrouting
 569 call path_ls_runoff
 570 call path_ls_process
END IFLine 571
IF (hru(j)%luse%urb_lu > 0) THEN Lines 574-580
IF (time%step == 1) THEN Lines 575-576
 576 call hru_urban ! daily simulation
END IFLine 576
ELSE Lines 577-579
 578 call hru_urbanhr ! subdaily simulation J.Jeong 4/20/2009
END IF Line 579
END IFLine 580
 583 call swr_latsed
 586 call stor_surfstor
 589 call swr_substor
IF (hru(j)%lumv%vfsi > 0.) THEN Lines 592-595
 593 call smp_filter
 594 if (filterw(j) > 0.) call smp_buffer
END IFLine 595
IF (hru(j)%lumv%grwat_i == 1) THEN Lines 598-600
 599 call smp_grass_wway
END IFLine 600
IF (hru(j)%lumv%bmp_flag == 1) THEN Lines 603-605
 604 call smp_bmpfixed
END IFLine 605
IF (ht2%flo > 0.) THEN Lines 608-613
 609 wet_outflow = ht2%flo / hru(j)%area_ha / 10.   !! mm = m3/ha *ha/10000m2 *1000mm/m
 610 qday = qday + wet_outflow
 611 qdr(j) = qdr(j) + wet_outflow
 612 ht2%flo = 0.
END IFLine 613
 616 call sq_surfst
IF (hru(j)%sb%sb_db%hru_src == j) THEN Lines 619-634
 621 id = hru(j)%sb%dtbl
 622 d_tbl => dtbl_flo(id)
 623 call conditions (j, id)
 624 call actions (j, iob, id)
 627 hru_rcv = hru(j)%sb%sb_db%hru_rcv
 629 rto =  hru(hru_rcv)%area_ha / hru(j)%area_ha
 630 hru(hru_rcv)%sb%inflo = rto * hru(j)%sb%sb_db%frac_src * hru(hru_rcv)%sb%inflo
 631 qtile = (1. - hru(j)%sb%sb_db%frac_src) * hru(hru_rcv)%sb%inflo
 632 hru(hru_rcv)%sb%no3 = hru(j)%sb%sb_db%frac_src * tileno3(j)
 633 tileno3(j) = (1. - hru(j)%sb%sb_db%frac_src) * tileno3(j)
END IFLine 634
 638 qdr(j) = qday + latq(j) + qtile
 640 if (qdr(j) < 0.) qdr(j) = 0.
 643 call swr_subwq
 645 xx = sed_con(j) + soln_con(j) + solp_con(j) + orgn_con(j) + orgp_con(j)
IF (xx > 1.e-6) THEN Lines 646-648
 647 call hru_urb_bmp
END IFLine 648
 652 iob_out = iob
IF (ob(iob)%ru_tot > 0) THEN Lines 654-656
 655 iob_out = sp_ob1%ru + ob(iob)%ru(1) - 1
END IFLine 656
 657 qsurf=surfq(j)
 659 hwb_d(j)%surq_cha = 0.
 660 hwb_d(j)%latq_cha = 0.
 661 hwb_d(j)%surq_res = 0.
 662 hwb_d(j)%latq_res = 0.
 663 hwb_d(j)%surq_ls = 0.
 664 hwb_d(j)%latq_ls = 0.
DO iout = 1, ob(iob_out)%src_tot Lines 666-711
SELECT CASE (ob(iob_out)%obtyp_out(iout)) Lines 667-710
CASE ("cha") Lines 668-674
IF (ob(iob_out)%htyp_out(iout) == "sur" .or. ob(iob_out)%htyp_out(iout) == "tot") THEN Lines 669-671
 670 hwb_d(j)%surq_cha = hwb_d(j)%surq_cha + surfq(j) * ob(iob_out)%frac_out(iout)
END IFLine 671
IF (ob(iob_out)%htyp_out(iout) == "lat" .or. ob(iob_out)%htyp_out(iout) == "tot") THEN Lines 672-674
 673 hwb_d(j)%latq_cha = hwb_d(j)%latq_cha + latq(j) * ob(iob_out)%frac_out(iout)
END IFLine 674
CASE ("sdc") Lines 675-681
IF (ob(iob_out)%htyp_out(iout) == "sur" .or. ob(iob_out)%htyp_out(iout) == "tot") THEN Lines 676-678
 677 hwb_d(j)%surq_cha = hwb_d(j)%surq_cha + surfq(j) * ob(iob_out)%frac_out(iout)
END IFLine 678
IF (ob(iob_out)%htyp_out(iout) == "lat" .or. ob(iob_out)%htyp_out(iout) == "tot") THEN Lines 679-681
 680 hwb_d(j)%latq_cha = hwb_d(j)%latq_cha + latq(j) * ob(iob_out)%frac_out(iout)
END IFLine 681
CASE ("res") Lines 682-688
IF (ob(iob_out)%htyp_out(iout) == "sur" .or. ob(iob_out)%htyp_out(iout) == "tot") THEN Lines 683-685
 684 hwb_d(j)%surq_res = hwb_d(j)%surq_res + surfq(j) * ob(iob_out)%frac_out(iout)
END IFLine 685
IF (ob(iob_out)%htyp_out(iout) == "lat" .or. ob(iob_out)%htyp_out(iout) == "tot") THEN Lines 686-688
 687 hwb_d(j)%latq_res = hwb_d(j)%latq_res + latq(j) * ob(iob_out)%frac_out(iout)
END IFLine 688
CASE ("hru") Lines 689-695
IF (ob(iob_out)%htyp_out(iout) == "sur" .or. ob(iob_out)%htyp_out(iout) == "tot") THEN Lines 690-692
 691 hwb_d(j)%surq_ls = hwb_d(j)%surq_ls + surfq(j) * ob(iob_out)%frac_out(iout)
END IFLine 692
IF (ob(iob_out)%htyp_out(iout) == "lat" .or. ob(iob_out)%htyp_out(iout) == "tot") THEN Lines 693-695
 694 hwb_d(j)%latq_ls = hwb_d(j)%latq_ls + latq(j) * ob(iob_out)%frac_out(iout)
END IFLine 695
CASE ("ru") Lines 696-702
IF (ob(iob_out)%htyp_out(iout) == "sur" .or. ob(iob_out)%htyp_out(iout) == "tot") THEN Lines 697-699
 698 hwb_d(j)%surq_ls = hwb_d(j)%surq_ls + surfq(j) * ob(iob_out)%frac_out(iout)
END IFLine 699
IF (ob(iob_out)%htyp_out(iout) == "lat" .or. ob(iob_out)%htyp_out(iout) == "tot") THEN Lines 700-702
 701 hwb_d(j)%latq_ls = hwb_d(j)%latq_ls + latq(j) * ob(iob_out)%frac_out(iout)
END IFLine 702
CASE ("hlt") Lines 703-709
IF (ob(iob_out)%htyp_out(iout) == "sur" .or. ob(iob_out)%htyp_out(iout) == "tot") THEN Lines 704-706
 705 hwb_d(j)%surq_ls = hwb_d(j)%surq_ls + surfq(j) * ob(iob_out)%frac_out(iout)
END IFLine 706
IF (ob(iob_out)%htyp_out(iout) == "lat" .or. ob(iob_out)%htyp_out(iout) == "tot") THEN Lines 707-709
 708 hwb_d(j)%latq_ls = hwb_d(j)%latq_ls + latq(j) * ob(iob_out)%frac_out(iout)
END IFLine 709
END SELECTLine 710
END DOLine 711
 714 hwb_d(j)%precip = w%precip
 715 hwb_d(j)%snofall = snofall
 716 hwb_d(j)%snomlt = snomlt
 717 hwb_d(j)%surq_gen = qday
 718 hwb_d(j)%latq = latq(j)
 719 hwb_d(j)%wateryld = qdr(j)
 720 hwb_d(j)%perc = sepbtm(j)
IF (sp_ob%gwflow > 0) THEN Lines 721-723
 722 gwflow_perc(j) = sepbtm(j)
END IFLine 723
 725 hwb_d(j)%et = etday + hru(j)%water_evap
 726 hwb_d(j)%ecanopy = canev
 727 hwb_d(j)%eplant = ep_day
 728 hwb_d(j)%esoil = es_day + hru(j)%water_evap
 729 hwb_d(j)%wet_evap = hru(j)%water_evap
 730 hwb_d(j)%wet_out = wet_outflow
 731 hwb_d(j)%wet_stor = wet(j)%flo / (10. * hru(j)%area_ha)
 732 hwb_d(j)%surq_cont = surfq(j)
IF (j==1 .and. surfq(j) > 1.) THEN Lines 733-735
 734 icn = 0
END IFLine 735
 736 hwb_d(j)%cn = cnday(j)
 737 hwb_d(j)%sw = soil(j)%sw
 738 hwb_d(j)%sw_final = soil(j)%sw
 739 hwb_d(j)%sw_300 = soil(j)%sw_300
 740 hwb_d(j)%snopack = hru(j)%sno_mm
 741 hwb_d(j)%pet = pet_day
 742 hwb_d(j)%qtile = qtile
 743 hwb_d(j)%irr = irrig(j)%applied
 744 irrig(j)%applied = 0.
 745 irrig(j)%runoff = 0.
 746 hwb_d(j)%surq_runon = ls_overq
 747 hwb_d(j)%latq_runon = latqrunon
 748 hwb_d(j)%overbank = hru(j)%wet_obank_in
 749 hru(j)%wet_obank_in = 0.
 751 hwb_d(j)%gwsoil = gwsoilq(j) !rtb gwflow - groundwater transferred to soil profile
 752 if (ires<1) hwb_d(j)%satex = satexq(j) !rtb gwflow - saturation excess generated from high water table
 753 hwb_d(j)%satex_chan = satexq_chan !rtb gwflow - saturation excess generated from high water table
 754 hwb_d(j)%delsw = soil(j)%sw - sw_volume_begin
 755 hwb_d(j)%lagsurf = surf_bs(1,j)
 756 hwb_d(j)%laglatq = bss(1,j)
 757 hwb_d(j)%lagsatex = bss_ex(1,j)
 758 satexq(j) = 0. !zero out for next day
 762 hnb_d(j)%grazn = grazn
 763 hnb_d(j)%grazp = grazp
 764 hnb_d(j)%fertn = fertn
 765 hnb_d(j)%fertp = fertp
 766 hnb_d(j)%fixn = fixn
 767 hnb_d(j)%gwsoiln = gwsoiln(j) !rtb gwflow
 768 hnb_d(j)%gwsoilp = gwsoilp(j) !rtb gwflow
DO isalt=1,cs_db%num_salts Lines 771-788
 772 hsaltb_d(j)%salt(isalt)%surq = surqsalt(j,isalt)
 773 hsaltb_d(j)%salt(isalt)%latq = latqsalt(j,isalt)
 774 hsaltb_d(j)%salt(isalt)%urbq = urbqsalt(j,isalt)
 775 hsaltb_d(j)%salt(isalt)%wetq = wetqsalt(j,isalt)
 776 hsaltb_d(j)%salt(isalt)%wtsp = wtspsalt(j,isalt)
 777 hsaltb_d(j)%salt(isalt)%tile = tilesalt(j,isalt)
 778 hsaltb_d(j)%salt(isalt)%perc = percsalt(j,isalt)
 779 hsaltb_d(j)%salt(isalt)%gwup = gwupsalt(j,isalt)
 780 sum_conc = 0.
 781 sum_mass = 0.
 786 hsaltb_d(j)%salt(isalt)%conc = sum_conc / soil(j)%nly !mg/L (average)
 787 hsaltb_d(j)%salt(isalt)%soil = sum_mass !kg/ha (total salt in soil profile)
DO jj=1,soil(j)%nly !loop through soil layers Lines 782-785
 783 sum_conc = sum_conc + cs_soil(j)%ly(jj)%saltc(isalt) !mg/L
 784 sum_mass = sum_mass + cs_soil(j)%ly(jj)%salt(isalt) !kg/ha
END DOLine 785
END DOLine 788
DO ics=1,cs_db%num_cs Lines 791-821
 792 sum_conc = 0.
 793 sum_mass = 0.
 794 sum_sorb = 0.
 800 hcsb_d(j)%cs(ics)%conc = sum_conc / soil(j)%nly !mg/L (average)
 801 hcsb_d(j)%cs(ics)%soil = sum_mass !kg/ha (total constituent mass in soil water)
 802 hcsb_d(j)%cs(ics)%srbd = sum_sorb !kg/ha (total constituent mass sorbed to soil)
 803 hcsb_d(j)%cs(ics)%surq = surqcs(j,ics)
 804 hcsb_d(j)%cs(ics)%sedm = sedmcs(j,ics)
 805 hcsb_d(j)%cs(ics)%latq = latqcs(j,ics)
 806 hcsb_d(j)%cs(ics)%urbq = urbqcs(j,ics)
 807 hcsb_d(j)%cs(ics)%wetq = wetqcs(j,ics)
 808 hcsb_d(j)%cs(ics)%wtsp = wtspcs(j,ics)
 809 hcsb_d(j)%cs(ics)%tile = tilecs(j,ics)
 810 hcsb_d(j)%cs(ics)%perc = perccs(j,ics)
 811 hcsb_d(j)%cs(ics)%gwup = gwupcs(j,ics)
DO jj=1,soil(j)%nly !loop through soil layers Lines 795-799
 796 sum_conc = sum_conc + cs_soil(j)%ly(jj)%csc(ics) !mg/L
 797 sum_mass = sum_mass + cs_soil(j)%ly(jj)%cs(ics) !kg/ha
 798 sum_sorb = sum_sorb + cs_soil(j)%ly(jj)%cs_sorb(ics) !kg/ha
END DOLine 799
END DOLine 821
 824 hpw_d(j)%lai = pcom(j)%lai_sum
 825 hpw_d(j)%bioms = pl_mass(j)%tot_com%m
IF (pl_mass(j)%tot_com%m < 0.) THEN Lines 826-828
 827 pl_mass(j)%tot_com%m = 0.
END IFLine 828
 829 hpw_d(j)%residue = soil1(j)%rsd(1)%m
 830 hpw_d(j)%yield = pl_yield%m
 831 pl_yield = plt_mass_z
 832 hpw_d(j)%sol_tmp =  soil(j)%phys(2)%tmp
 833 hpw_d(j)%strsw = strsw_av
 834 hpw_d(j)%strsa = strsa_av
 835 hpw_d(j)%strstmp = strstmp_av
 836 hpw_d(j)%strsn = strsn_av
 837 hpw_d(j)%strsp = strsp_av
 838 hpw_d(j)%strss = strss_av
 839 hpw_d(j)%nplnt = pl_mass(j)%tot_com%n
 840 hpw_d(j)%percn = percn(j)
IF (bsn_cc%gwflow == 1 .and. gw_solute_flag == 1) THEN Lines 842-844
 843 gwflow_percsol(j,1) = percn(j)
END IFLine 844
 845 hpw_d(j)%pplnt = pl_mass(j)%tot_com%p
 846 hpw_d(j)%tmx = w%tmax
 847 hpw_d(j)%tmn = w%tmin
 848 hpw_d(j)%tmpav = w%tave
 849 hpw_d(j)%solrad = w%solrad
 850 hpw_d(j)%wndspd = w%windsp
 851 hpw_d(j)%rhum = w%rhum
 852 hpw_d(j)%phubase0 = phubase(j)
 855 hls_d(j)%sedyld = sedyld(j) / hru(j)%area_ha
 856 hls_d(j)%sedorgn = sedorgn(j)
 857 hls_d(j)%sedorgp = sedorgp(j)
 858 hls_d(j)%surqno3 = surqno3(j)
 859 hls_d(j)%latno3 = latno3(j)
 860 hls_d(j)%surqsolp = surqsolp(j)
 861 hls_d(j)%usle = usle
 862 hls_d(j)%sedminp = sedminpa(j) + sedminps(j)
 863 hls_d(j)%tileno3 = tileno3(j)
 866 call hru_hyds
 870 return
Allocations
n/a
Calls
Calls
Procedures called by this subroutine.
Local Variables
Type Visibility Attributes Name Initial
integer, private :: j
integer, private :: j1
integer, private :: ulu
integer, private :: iob
integer, private :: ith
integer, private :: iwgn
integer, private :: ires
integer, private :: isched
integer, private :: isalt
integer, private :: ics
integer, private :: iauto
integer, private :: id
integer, private :: jj
integer, private :: ly
integer, private :: ipest
real, private :: strsa_av
integer, private :: icn
real, private :: xx
integer, private :: iob_out
integer, private :: iout
integer, private :: iac
integer, private :: npl_gro
real, private :: dep
real, private :: strsw_av
real, private :: strsn_av
real, private :: strsp_av
real, private :: strss_av
real, private :: strstmp_av
real, private :: wet_outflow
real, private :: tile_fr_surf
integer, private :: ifrt
integer, private :: idp
integer, private :: hru_rcv
real, private :: rto
real, private :: sw_volume_begin
real, private :: soil_prof_labp
real, private :: sum_conc
real, private :: sum_mass
real, private :: sum_sorb
real, private :: saltcon
real, private :: qsurf
real, private :: sedppm
Call graph
hru_control calls actions, albedo, cbn_rsd_decomp, cbn_zhang2, conditions, cs_lch, cs_rain, cs_rctn_hru, cs_sorb_hru, et_act, et_pot, hru_hyds, hru_urb_bmp, hru_urban, hru_urbanhr, mgt_newtillmix, mgt_operatn, nut_nitvol, nut_nlch, nut_nminrl, nut_nrain, nut_orgn, nut_orgnc, nut_orgnc2, nut_pminrl, nut_pminrl2, nut_psed, nut_solp, path_ls_process, path_ls_runoff, path_ls_swrouting, pest_decay, pest_enrsb, pest_lch, pest_pesty, pest_pl_up, pest_soil_tot, pest_washp, pl_community, pl_fert, pl_graze, pl_grow, rls_routeaqu, rls_routesoil, rls_routesurf, rls_routetile, salt_chem_hru, salt_lch, salt_rain, salt_roadsalt, sep_biozone, smp_bmpfixed, smp_buffer, smp_filter, smp_grass_wway, sq_canopyint, sq_crackvol, sq_snom, sq_surfst, stmp_solt, stor_surfstor, surface, swr_latsed, swr_percmain, swr_substor, swr_subwq, varinit, wet_irrp, wetland_control