hyd_connect – TestDataProject
hyd_connect Subroutine
436 statements
Source File
subroutine hyd_connect()
Called From
n/a
Arguments
n/a
Outside Variables and Types
type (80 attributes from basin_module)
Attribute Name Description
bsn_prm%day_lag_mx None
cs_db%num_metals None
cs_db%num_paths None
cs_db%num_salts None
cs_db%num_cs None
cs_db%num_pests None
hcs1%pest None
hcs1%path None
hcs1%salt None
hcs1%hmet None
hcs1%cs None
hcs2%pest None
hcs2%path None
hcs2%salt None
hcs2%hmet None
hcs2%cs None
hcs3%pest None
hcs3%path None
hcs3%salt None
hcs3%hmet None
hcs3%cs None
hin_csz%pest None
hin_csz%path None
hin_csz%salt None
hin_csz%hmet None
hin_csz%cs None
in_con%exco_con None
in_con%rec_con None
in_con%delr_con None
in_con%hru_con None
in_con%ru_con None
in_con%hruez_con None
in_con%out_con None
in_con%chan_con None
in_con%chandeg_con None
in_con%gwflow_con None
in_con%res_con None
in_con%aqu_con None
sp_ob%outlet None
sp_ob%recall None
sp_ob%dr None
sp_ob%canal None
sp_ob%hru_lte None
sp_ob%gwflow None
sp_ob%exco None
sp_ob%aqu None
sp_ob%pump None
sp_ob%hru None
sp_ob%chan None
sp_ob%chandeg None
sp_ob%res None
sp_ob%ru None
sp_ob%objs None
sp_ob1%outlet None
sp_ob1%recall None
sp_ob1%dr None
sp_ob1%canal None
sp_ob1%hru_lte None
sp_ob1%gwflow None
sp_ob1%exco None
sp_ob1%aqu None
sp_ob1%pump None
sp_ob1%hru None
sp_ob1%chan None
sp_ob1%chandeg None
sp_ob1%res None
sp_ob1%ru None
sp_ob1%objs None
hd_tot%outlet None
hd_tot%recall None
hd_tot%dr None
hd_tot%hru_lte None
hd_tot%exco None
hd_tot%chandeg None
hd_tot%aqu None
hd_tot%gwflow None
hd_tot%chan None
hd_tot%hru None
hd_tot%res None
hd_tot%ru None
type(all_constituent_hydrograph) (1 attribute from constituent_mass_module)
Attribute Name Description
obcs
integer (6 attributes from hydrograph_module)
Attribute Name Description
ich
none |object number
Read more…
rcv_sum
|
dfn_sum
|
ru_seq
|
nat_model
iru
none |counter
Read more…
type(hyd_output) (4 attributes from hydrograph_module)
Attribute Name Description
aqu
res
dr
delivery ratio for objects- chan, res, lu
exco
export coefficient
type(object_connectivity) (1 attribute from hydrograph_module)
Attribute Name Description
ob
type(recall_hydrograph_inputs) (1 attribute from hydrograph_module)
Attribute Name Description
recall
type(routing_unit_data) (1 attribute from hydrograph_module)
Attribute Name Description
ru_def
type(routing_unit_elements) (1 attribute from hydrograph_module)
Attribute Name Description
ru_elem
type(ru_parameters) (1 attribute from ru_module)
Attribute Name Description
ru
Uses
basin_module
constituent_mass_module
input_file_module
hydrograph_module
organic_mineral_mass_module
gwflow_module
recall_module
ru_module
I/O
I/O units used in this subroutine.
Unit Type Filename
looping.con",recl = 8000 Unknown not specified
unit_* Output not specified
unit_9004 Output not specified
Local Variables
Type Visibility Attributes Name Initial
integer, public :: eof = 0
integer, public :: imax = 0
character(len=3), public :: iob_out = ""
character(len=3), public :: iobtyp = ""
integer, public :: nspu = 0
integer, public :: cmdno = 0
integer, public :: idone = 0
integer, public :: cmd_prev = 0
integer, public :: ob1 = 0
integer, public :: ob2 = 0
integer, public :: iobj_tot = 0
real, public :: mexco_sp = 0.
integer, public :: i = 0
integer, public :: ii = 0
integer, public :: ielem = 0
integer, public :: k = 0
integer, public :: iob = 0
integer, public :: kk = 0
integer, public :: j = 0
integer, public :: ielem_db = 0
integer, public :: jj = 0
integer, public :: iord = 0
integer, public :: isrc_tot = 0
integer, public :: iorder = 0
integer, public :: ircv = 0
integer, public :: ircv_ob = 0
integer, public :: max
logical, public :: i_exist
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure. Use mouse wheel to zoom, drag to pan.
Reset Zoom Help
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
~ ~ ~ PURPOSE ~ ~ ~ (line 3)
reads in the routing information from the watershed configuration (line 4)
input file (.fig) and calculates the number of subbasins, reaches, (line 5)
and reservoirs (line 6)
set first object number of each type (line 61)
  49 eof = 0
  50 imax = 0
  51 mexco_sp = 0
  52 cmd_prev = 0
  54 allocate (rcv_sum(sp_ob%objs), source = 0)
  55 allocate (dfn_sum(sp_ob%objs), source = 0)
  56 allocate (ru_seq(sp_ob%objs), source = 0)
  57 rcv_sum = 0
  58 dfn_sum = 0
  59 ru_seq = 0
  62 nspu = 1
  63 if (sp_ob%hru > 0) then         ! 1==hru
  64 sp_ob1%hru = nspu
  65 nspu = sp_ob%hru + nspu
  67 if (sp_ob%hru_lte > 0) then     ! 2==hru_lte
  68 sp_ob1%hru_lte = nspu
  69 nspu = sp_ob%hru_lte + nspu
  71 if (sp_ob%ru > 0) then         ! 3==subbasin
  72 sp_ob1%ru = nspu
  73 nspu = sp_ob%ru + nspu
  75 if (sp_ob%gwflow > 0) then     ! 4==gwflow
  76 sp_ob1%gwflow = nspu
  77 nspu = sp_ob%gwflow + nspu
  78 inquire(file='gwflow.huc12cell',exist=i_exist)
  80 if (sp_ob%aqu > 0) then         ! 5==aquifer
  81 sp_ob1%aqu = nspu
  82 nspu = sp_ob%aqu + nspu
  84 if (sp_ob%chan > 0) then        ! 6==channel
  85 sp_ob1%chan = nspu
  86 nspu = sp_ob%chan + nspu
  88 if (sp_ob%res > 0) then         ! 7==reservoir
  89 sp_ob1%res = nspu
  90 nspu = sp_ob%res + nspu
  92 if (sp_ob%recall > 0) then      ! 8==recall
  93 sp_ob1%recall = nspu
  94 nspu = sp_ob%recall + nspu
  96 if (sp_ob%exco > 0) then        ! 11==exco
  97 sp_ob1%exco = nspu
  98 nspu = sp_ob%exco + nspu
 100 if (sp_ob%dr > 0) then          ! 12==dr
 101 sp_ob1%dr = nspu
 102 nspu = sp_ob%dr + nspu
 104 if (sp_ob%canal > 0) then       ! 13==canal
 105 sp_ob1%canal = nspu
 106 nspu = sp_ob%canal + nspu
 108 if (sp_ob%pump > 0) then        ! 14==pump
 109 sp_ob1%pump = nspu
 110 nspu = sp_ob%pump + nspu
 112 if (sp_ob%outlet > 0) then      ! 15==outlet
 113 sp_ob1%outlet = nspu
 114 nspu = sp_ob%outlet + nspu
 116 if (sp_ob%chandeg > 0) then     ! 16==swat-deg channel
 117 sp_ob1%chandeg = nspu
 118 nspu = sp_ob%chandeg + nspu
IF (sp_ob%hru > 0) THEN Lines 126-128
 127 call hyd_read_connect(in_con%hru_con, "hru     ", sp_ob1%hru, sp_ob%hru, hd_tot%hru, bsn_prm%day_lag_mx)
END IFLine 128
IF (sp_ob%hru_lte > 0) THEN Lines 131-133
 132 call hyd_read_connect(in_con%hruez_con, "hru_lte ", sp_ob1%hru_lte, sp_ob%hru_lte, hd_tot%hru_lte, bsn_prm%day_lag_mx)
END IFLine 133
IF (sp_ob%ru > 0) THEN Lines 136-140
 137 call hyd_read_connect(in_con%ru_con, "ru      ", sp_ob1%ru, sp_ob%ru, hd_tot%ru, bsn_prm%day_lag_mx)
 138 call ru_read
 139 call ru_read_elements
END IFLine 140
IF (sp_ob%aqu > 0) THEN Lines 143-146
 144 call hyd_read_connect(in_con%aqu_con, "aqu     ", sp_ob1%aqu, sp_ob%aqu, hd_tot%aqu, 1)
 145 call aqu2d_read
END IFLine 146
IF (sp_ob%chan > 0) THEN Lines 149-152
 150 call hyd_read_connect(in_con%chan_con, "chan    ", sp_ob1%chan, sp_ob%chan, hd_tot%chan, bsn_prm%day_lag_mx)
 151 call overbank_read
END IFLine 152
IF (sp_ob%res > 0) THEN Lines 155-157
 156 call hyd_read_connect(in_con%res_con, "res     ", sp_ob1%res, sp_ob%res, hd_tot%res, 1)
END IFLine 157
IF (sp_ob%recall > 0) THEN Lines 160-165
 161 call hyd_read_connect(in_con%rec_con, "recall  ", sp_ob1%recall, sp_ob%recall, hd_tot%recall, 1)
 162 call recall_read
 163 call recall_read_salt !rtb salt
 164 call recall_read_cs !rtb cs
END IFLine 165
IF (sp_ob%exco > 0) THEN Lines 168-170
 169 call hyd_read_connect(in_con%exco_con, "exco    ", sp_ob1%exco, sp_ob%exco, hd_tot%exco, 1)
END IFLine 170
IF (sp_ob%dr > 0) THEN Lines 173-176
 174 call hyd_read_connect(in_con%delr_con, "dr      ", sp_ob1%dr, sp_ob%dr, hd_tot%dr, 1)
 175 call dr_db_read
END IFLine 176
IF (sp_ob%outlet > 0) THEN Lines 179-181
 180 call hyd_read_connect(in_con%out_con, "outlet  ", sp_ob1%outlet, sp_ob%outlet, hd_tot%outlet, bsn_prm%day_lag_mx)
END IFLine 181
IF (sp_ob%chandeg > 0) THEN Lines 184-186
 185 call hyd_read_connect(in_con%chandeg_con, "chandeg ", sp_ob1%chandeg, sp_ob%chandeg, hd_tot%chandeg, bsn_prm%day_lag_mx)
END IFLine 186
IF (sp_ob%gwflow > 0) THEN Lines 189-193
 190 call gwflow_chan_read !first, read in channel cell information
 191 call hyd_read_connect(in_con%gwflow_con, "gwflow  ", sp_ob1%gwflow, sp_ob%gwflow, hd_tot%gwflow, 1)
 192 call gwflow_read
END IFLine 193
DO i = 1, sp_ob%objs Lines 196-201
 197 nspu = ob(i)%ru_tot
IF (nspu > 0) THEN Lines 198-200
 199 allocate (ob(i)%obj_subs(nspu), source = 0)
END IFLine 200
END DOLine 201
DO iru = 1, sp_ob%ru Lines 203-215
determine subbasin the hrus are in and add subbasin area to basin area (line 204)
DO ii = 1, ru_def(iru)%num_tot Lines 205-214
only have hrus set up - need to add other objects (line 206)
 207 ielem = ru_def(iru)%num(ii)        !points to element in sub_element
 208 k = ru_elem(ielem)%obj              !object type number of element (ie hru)
 209 iob = sp_ob1%ru + iru - 1         !object number of the routing unit
 210 ru_seq(k) = ru_seq(k) + 1           !sequential number of routing unit the element is in
 211 kk = ru_seq(k)
 212 ob(k)%obj_subs(kk) = iob            !routing unit the element is in
 213 dfn_sum(iob) = dfn_sum(iob) + 1     !sum of elements in the routing unit object
END DOLine 214
END DOLine 215
DO i = 1, sp_ob%objs Lines 218-296
DO ii = 1, ob(i)%src_tot Lines 219-295
 220 iob_out = ob(i)%obtyp_out(ii)          !object type out
SELECT CASE (iob_out) Lines 221-281
DO kk = 1, ru_def(iru)%num_tot Lines 235-239
 236 ielem = ru_def(iru)%num(kk)
 237 iob = ru_elem(ielem)%obj
 238 ob(iob)%rcv_tot = ob(iob)%rcv_tot + 1
END DOLine 239
IF (ob(i)%typ == "modflow" .and. ob(i)%obtypno_out(ii) <= 0) THEN Lines 250-255
DO ich = 1, sp_ob%chan Lines 251-255
 252 ob(i)%obj_out(ii) = sp_ob1%chan + ich - 1
 253 j = ob(i)%obj_out(ii)
 254 ob(j)%rcv_tot = ob(j)%rcv_tot + 1
END DOLine 255
END IFLine 255
ELSE Lines 256-260
 257 ob(i)%obj_out(ii) = sp_ob1%chan +ob(i)%obtypno_out(ii) - 1
 258 j = ob(i)%obj_out(ii)
 259 ob(j)%rcv_tot = ob(j)%rcv_tot + 1
END IF Line 260
END SELECTLine 281
SELECT CASE (ob(i)%htyp_out(ii)) Lines 283-294
END SELECTLine 294
END DOLine 295
END DOLine 296
allocate zero arrays for constituents (line 298)
allocate receiving arrays (line 329)
 299 allocate (hin_csz%pest(cs_db%num_pests), source = 0.)
 300 allocate (hin_csz%path(cs_db%num_paths), source = 0.)
 301 allocate (hin_csz%hmet(cs_db%num_metals), source = 0.)
 302 allocate (hin_csz%salt(cs_db%num_salts), source = 0.) !rtb salt
 303 allocate (hin_csz%cs(cs_db%num_cs), source = 0.) !rtb se
 305 allocate (hcs1%pest(cs_db%num_pests), source = 0.)
 306 allocate (hcs1%path(cs_db%num_paths), source = 0.)
 307 allocate (hcs1%hmet(cs_db%num_metals), source = 0.)
 308 allocate (hcs1%salt(cs_db%num_salts), source = 0.) !rtb salt
 309 allocate (hcs1%cs(cs_db%num_cs), source = 0.) !rtb cs
 311 allocate (hcs2%pest(cs_db%num_pests), source = 0.)
 312 allocate (hcs2%path(cs_db%num_paths), source = 0.)
 313 allocate (hcs2%hmet(cs_db%num_metals), source = 0.)
 314 allocate (hcs2%salt(cs_db%num_salts), source = 0.) !rtb salt
 315 allocate (hcs2%cs(cs_db%num_cs), source = 0.) !rtb cs
 317 allocate (hcs3%pest(cs_db%num_pests), source = 0.)
 318 allocate (hcs3%path(cs_db%num_paths), source = 0.)
 319 allocate (hcs3%hmet(cs_db%num_metals), source = 0.)
 320 allocate (hcs3%salt(cs_db%num_salts), source = 0.) !rtb salt
 321 allocate (hcs3%cs(cs_db%num_cs), source = 0.) !rtb cs
 323 hin_csz%pest = 0.
 324 hin_csz%path = 0.
 325 hin_csz%hmet = 0.
 326 hin_csz%salt = 0. !rtb salt
 327 hin_csz%cs = 0. !rtb cs
DO i = 1, sp_ob%objs Lines 330-356
IF (ob(i)%rcv_tot > 0) THEN Lines 331-355
allocate unit hyd for all incoming hyd's (line 340)
 332 nspu = ob(i)%rcv_tot
 333 allocate (ob(i)%obj_in(nspu), source = 0)
 334 allocate (ob(i)%obtyp_in(nspu))
 335 allocate (ob(i)%obtypno_in(nspu), source = 0)
 336 allocate (ob(i)%htyp_in(nspu))
 337 allocate (ob(i)%ihtyp_in(nspu), source = 0)
 338 allocate (ob(i)%frac_in(nspu), source = 0.)
 339 allocate (ob(i)%hin_uh(nspu))
 347 allocate (ob(i)%hin_d(nspu))
 348 allocate (ob(i)%hin_m(nspu))
 349 allocate (ob(i)%hin_y(nspu))
 350 allocate (ob(i)%hin_a(nspu))
 351 allocate (obcs(i)%hcsin_d(nspu))
 352 allocate (obcs(i)%hcsin_m(nspu))
 353 allocate (obcs(i)%hcsin_y(nspu))
 354 allocate (obcs(i)%hcsin_a(nspu))
DO ii = 1, nspu Lines 341-346
 342 allocate (ob(i)%hin_uh(ii)%uh(bsn_prm%day_lag_mx,time%step), source = 0.)
 343 allocate (ob(i)%hin_uh(ii)%hyd_flo(bsn_prm%day_lag_mx,time%step), source = 0.)
 344 ob(i)%hin_uh(ii)%uh = 0.
 345 ob(i)%hin_uh(ii)%hyd_flo = 0.
END DOLine 346
END IFLine 355
END DOLine 356
DO i = 1, sp_ob%objs ! i=object number of source object Lines 359-403
DO ii = 1, ob(i)%src_tot ! ii=sequential source number Lines 360-402
if modflow object and set for all channels (line 361)
if modflow object and set for all channels (line 361)
IF (ob(i)%obtyp_out(ii) == "cha" .and. ob(i)%obtypno_out(ii) <= 0) THEN Lines 362-373
set all incoming channel object data to modflow (line 363)
DO ich = 1, sp_ob%chan Lines 364-373
 365 kk = sp_ob1%chan + ich - 1
 366 rcv_sum(kk) = rcv_sum(kk) + 1                   ! setting sequential inflow number
 367 jj = rcv_sum(kk)                                ! jj=sequential receiving number
 368 ob(kk)%obj_in(jj) = i                           ! source object number (for receiving unit)
 369 ob(kk)%obtyp_in(jj) = ob(i)%typ
 370 ob(kk)%htyp_in(jj) = ob(i)%htyp_out(ii)
 371 ob(kk)%ihtyp_in(jj) = ob(i)%ihtyp_out(ii)
 372 ob(kk)%frac_in(jj) = ob(i)%frac_out(ii)
END DOLine 373
END IFLine 373
ELSE Lines 374-401
for subbasins, set receiving objects for each element (need for parallelization order) (line 385)
for subbasins, set receiving objects for each element (need for parallelization order) (line 385)
 375 kk = ob(i)%obj_out(ii)                          ! kk=object number of outflow object
 376 rcv_sum(kk) = rcv_sum(kk) + 1                   ! setting sequential receiving hyd number
 377 jj = rcv_sum(kk)                                ! jj=sequential receiving number
 378 ob(kk)%obj_in(jj) = i                           ! source object number (for receiving unit)
 379 ob(kk)%obtyp_in(jj) = ob(i)%typ
 380 ob(kk)%obtypno_in(jj) = ob(i)%num
 381 ob(kk)%htyp_in(jj) = ob(i)%htyp_out(ii)
 382 ob(kk)%ihtyp_in(jj) = ob(i)%ihtyp_out(ii)
 383 ob(kk)%frac_in(jj) = ob(i)%frac_out(ii)
 384 ob(i)%rcvob_inhyd(ii) = jj
IF (ob(kk)%typ == "ru") THEN Lines 386-400
 387 iru = ob(kk)%num
DO ielem = 1, ru_def(iru)%num_tot Lines 388-399
if routing over ru - the hru frac is included (line 396)
 389 ielem_db = ru_def(iru)%num(ielem)
 390 kk = ru_elem(ielem_db)%obj
 391 ob(kk)%obj_in(jj) = i                       ! source object number (for receiving unit)
 392 ob(kk)%obtyp_in(jj) = ob(i)%typ
 393 ob(kk)%obtypno_in(jj) = ob(i)%props
 394 ob(kk)%htyp_in(jj) = ob(i)%htyp_out(ii)
 395 ob(kk)%ihtyp_in(jj) = ob(i)%ihtyp_out(ii)
 397 ob(kk)%frac_in(jj) = ob(i)%frac_out(ii) * ru_elem(ielem_db)%frac
 398 ob(i)%rcvob_inhyd(ii) = jj
END DOLine 399
END IFLine 400
END IF Line 401
END DOLine 402
END DOLine 403
loop through again to set command (object) sequence (line 405)
 406 cmdno = 0
 407 idone = 0
 408 iobj_tot = 0
 409 rcv_sum = 0
 410 iord = 1
 411 dfn_sum = 0
DO while (idone == 0) Lines 413-532
 531 iord = iord + 1
DO i = 1, sp_ob%objs Lines 414-530
 433 if (rcv_sum(i) == ob(i)%rcv_tot .and.                        &
 434 dfn_sum(i) == ob(i)%dfn_tot) then
IF (iord > 5000) THEN Lines 416-428
 417 open (9002,file="looping.con",recl = 8000)
 418 write (9002, *) "LOOPING.CON CHECKING INFINITE LOOPS"
 426 write (*,1002)
 427 call exit(1)
DO iob = 1, sp_ob%objs Lines 419-425
IF (ob(iob)%fired == 0 .and. ob(iob)%rcv_tot > 0) THEN Lines 420-424
 421 kk=1
 422 write (9002, *) ob(iob)%typ, ob(iob)%num, ob(iob)%rcv_tot, (ob(iob)%obtyp_in(jj),  &
 423 ob(iob)%obtypno_in(jj), jj = 1, ob(iob)%rcv_tot)
END IFLine 424
END DOLine 425
END IFLine 428
IF (ob(i)%fired == 0) THEN Lines 435-528
calculate drainage area to compare to input area - need reservoir surface area (line 438)
 436 ob(i)%fired = 1
 457 iobj_tot = iobj_tot + 1    ! check to see if all objects are done
 458 if (iobj_tot == sp_ob%objs) idone = 1
 466 isrc_tot = Max(ob(i)%src_tot, 1)  !force to go through once
DO ircv = 1, ob(i)%rcv_tot Lines 439-455
 440 if (ob(i)%obtyp_in(ircv) == "hru" .or. ob(i)%obtyp_in(ircv) == "ru" .or.      &
 441 ob(i)%obtyp_in(ircv) == "chandeg" .or. ob(i)%obtyp_in(ircv) == "recall" &
 442 .or. ob(i)%obtyp_in(ircv) == "res" .or. ob(i)%obtyp_in(ircv) == "outlet") then
 444 ob1 = ob(i)%obj_in(ircv)
 445 ob(i)%area_ha_calc = ob(i)%area_ha_calc + ob(ob1)%area_ha_calc * ob(i)%frac_in(ircv)
END DOLine 455
DO k = 1, ob(i)%ru_tot Lines 460-464
 461 dfn_sum(ob(i)%obj_subs(k)) = dfn_sum(ob(i)%obj_subs(k)) + 1
END DOLine 464
DO ii = 1, isrc_tot Lines 467-527
add receiving object for single objects (line 468)
add receiving object for single objects (line 468)
compute object order for parallelization (similar to stream order) (line 498)
compute object order for parallelization (similar to stream order) (line 498)
 515 if (ob(i)%typ /= "exco") then   !exco"s are not commands
 516 ob(i)%cmd_prev = cmd_prev
 522 cmd_prev = i
 524 ob(i)%cmd_order = iord
 525 end if  !exco"s are not commands
IF (ob(i)%src_tot > 0) THEN Lines 469-482
IF (ob(i)%obtypno_out(ii) > 0) THEN Lines 470-482
add subbasin elements (line 473)
add subbasin elements (line 473)
 471 k = ob(i)%obj_out(ii)
 472 rcv_sum(k) = rcv_sum(k) + 1
IF (ob(k)%typ == "ru") THEN Lines 474-481
 475 iru = ob(k)%props
DO jj = 1, ru_def(iru)%num_tot Lines 476-480
 477 ielem = ru_def(iru)%num(jj)
 478 iob = ru_elem(ielem)%obj
 479 rcv_sum(iob) = rcv_sum(iob) + 1
END DOLine 480
END IFLine 481
END IFLine 482
END IFLine 482
ELSE Lines 483-496
modflow - for all inflow objects (line 484)
modflow - for all inflow objects (line 484)
IF (ob(i)%typ == "modflow") THEN Lines 485-495
add receiving for all channels from modflow (line 487)
add receiving for all channels from modflow (line 487)
 486 iobtyp = ob(i)%obtyp_out(ii)
IF (iobtyp == "cha") THEN Lines 488-494
 489 ob1 = sp_ob1%chan
 490 ob2 = sp_ob1%chan + sp_ob%chan - 1
DO ich = ob1, ob2 Lines 491-493
 492 rcv_sum(ich) = rcv_sum(ich) + 1
END DOLine 493
END IFLine 494
END IFLine 495
END IF Line 496
IF (ob(i)%rcv_tot == 0 .and. ob(i)%typ /= "ru") THEN Lines 499-500
 500 ob(i)%cmd_order = 1
END IFLine 500
ELSE Lines 501-513
compute object order of highest receiving object and add 1 (line 503)
subbasin has to be in parallel order after elements in the subbasin (line 508)
subbasin has to be in parallel order after elements in the subbasin (line 508)
 502 iorder = 0
 512 ob(i)%cmd_order = iorder + 1
DO ircv = 1, ob(i)%rcv_tot Lines 504-507
 505 ircv_ob = ob(i)%obj_in(ircv)
 506 iorder = Max (iorder, ob(ircv_ob)%cmd_order)
END DOLine 507
IF (ob(i)%typ == "ru" .and. ob(i)%rcv_tot == 0) THEN Lines 509-511
 510 iorder = 1
END IFLine 511
END IF Line 513
IF (cmd_prev > 0) THEN Lines 517-518
 518 ob(cmd_prev)%cmd_next = i
END IFLine 518
ELSE Lines 519-521
 520 sp_ob1%objs = i  !first command number
END IF Line 521
END DOLine 527
END IFLine 528
END DOLine 530
END DOLine 532
DO iob = 1, sp_ob%objs Lines 535-542
IF (ob(iob)%typ /= "hru" .and. ob(iob)%typ /= "ru") THEN Lines 536-541
 537 write (9004,*) iob, ob(iob)%typ, ob(iob)%num, ob(iob)%area_ha, ob(iob)%area_ha_calc,             &
 538 ob(iob)%rcv_tot, (ob(iob)%obtyp_in(jj), ob(iob)%obtypno_in(jj), ob(iob)%obj_in(jj),             &
 539 ob(iob)%frac_in(jj), &
 540 ob(ob(iob)%obj_in(jj))%area_ha, ob(ob(iob)%obj_in(jj))%area_ha_calc, jj = 1, ob(iob)%rcv_tot)
END IFLine 541
END DOLine 542
 544 1002  format (5x,/,"ERROR - An infinite loop is detected in the connect file(s)",/, 15x, "the simulation will end",       &
 545 /, 9x, "(review looping.con file for more info)",/)
 546 return
Allocations
Memory allocations and deallocations grouped by variable.
Variable Allocations Deallocations
rcv_sum line 54 none
dfn_sum line 55 none
ru_seq line 56 none
ob line 199, line 333, line 334, line 335, line 336, line 337, line 338, line 339, line 342, line 343, line 347, line 348, line 349, line 350 none
hin_csz line 299, line 300, line 301, line 302, line 303 none
hcs1 line 305, line 306, line 307, line 308, line 309 none
hcs2 line 311, line 312, line 313, line 314, line 315 none
hcs3 line 317, line 318, line 319, line 320, line 321 none
obcs line 351, line 352, line 353, line 354 none
Calls
Procedures Called
List of procedures called by this Subroutine.
hyd_read_connect
ru_read
ru_read_elements
aqu2d_read
overbank_read
recall_read
recall_read_salt
recall_read_cs
dr_db_read
gwflow_chan_read
gwflow_read
Call Graph
Visual representation of procedures called by this Subroutine.
Call graph
hyd_connect calls aqu2d_read, dr_db_read, gwflow_chan_read, gwflow_read, hyd_read_connect, overbank_read, recall_read, recall_read_cs, recall_read_salt, ru_read, ru_read_elements