hyd_convert_mass_to_conc – test-src-project
hyd_convert_mass_to_conc Subroutine
24 statements
Source File
public subroutine hyd_convert_mass_to_conc(hyd1)
Arguments
Type Intent Optional Attributes Name
type(hyd_output), intent(inout) :: hyd1
I/O
n/a
Outside Variables and Types
n/a
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure.
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
   3 hyd1%flo = hyd1%flo
IF (hyd1%flo > 0.01) THEN Lines 5-22
   6 hyd1%sed = 1000000. * hyd1%sed / hyd1%flo
   8 hyd1%orgn = 1000. * hyd1%orgn / hyd1%flo
   9 hyd1%sedp = 1000. * hyd1%sedp / hyd1%flo
  10 hyd1%no3 = 1000. * hyd1%no3 / hyd1%flo
  11 hyd1%solp = 1000. * hyd1%solp / hyd1%flo
  12 hyd1%chla = 1000. * hyd1%chla / hyd1%flo
  13 hyd1%nh3 = 1000. * hyd1%nh3 / hyd1%flo
  14 hyd1%no2 = 1000. * hyd1%no2 / hyd1%flo
  15 hyd1%cbod = 1000. * hyd1%cbod / hyd1%flo
  16 hyd1%dox = 1000. * hyd1%dox / hyd1%flo
  17 hyd1%san = 0.  !1000000. * hyd1%san / hyd1%flo
  18 hyd1%sil = 0.  !1000000. * hyd1%sil / hyd1%flo
  19 hyd1%cla = 0.  !1000000. * hyd1%cla / hyd1%flo
  20 hyd1%sag = 0.  !1000000. * hyd1%sag / hyd1%flo
  21 hyd1%lag = 0.  !1000000. * hyd1%lag / hyd1%flo
  22 hyd1%grv = 0.  !1000000. * hyd1%grv / hyd1%flo
END IFLine 22
ELSE Lines 23-25
  24 hyd1 = hz
END IF Line 25
Allocations
n/a
Calls
Called By
Procedures that call this subroutine.
Variables
Type Visibility Attributes Name Initial
type(hyd_output), public :: hyd1
Call graph
sd_channel_control calls hyd_convert_mass_to_conc
sd_channel_control2 calls hyd_convert_mass_to_conc
swift_output calls hyd_convert_mass_to_conc