mallo_control – test-src-project
mallo_control Subroutine
53 statements
Source File
subroutine mallo_control(imallo)
Uses
manure_allocation_module
hru_module
conditional_module
basin_module
soil_module
plant_module
time_module
organic_mineral_mass_module
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: imallo
I/O
I/O units used in this subroutine.
Unit Type Filename
unit_2612 Output not specified
Outside Variables and Types
type(manure_demand_amount) (1 attribute from manure_allocation_module)
Attribute Name Description
manure_amtz
type(source_manure_output) (1 attribute from manure_allocation_module)
Attribute Name Description
malloz
type(manure_allocation) (1 attribute from manure_allocation_module)
Attribute Name Description
mallo
dimension by water allocation objects
integer (2 attributes from hru_module)
Attribute Name Description
ipl
ihru
none |HRU number
Read more…
real (8 attributes from hru_module)
Attribute Name Description
fertno3
fertnh3
fertorgn
fertsolp
fertorgp
sol_sumno3
sol_sumsolp
phubase
type(decision_table) (2 attributes from conditional_module)
Attribute Name Description
dtbl_lum
d_tbl
type (4 attributes from basin_module)
Attribute Name Description
pco%mgtout None
time%yrc None
time%day_mo None
time%mo None
type(soil_profile) (1 attribute from soil_module)
Attribute Name Description
soil
type(plant_community) (1 attribute from plant_module)
Attribute Name Description
pcom
type(soil_profile_mass) (1 attribute from organic_mineral_mass_module)
Attribute Name Description
soil1
type(plant_community_mass) (1 attribute from organic_mineral_mass_module)
Attribute Name Description
pl_mass
!! Bang Comments
zero demand, withdrawal, and unmet for entire allocation object add manure produced on the first day of the month loop through each demand object for manure demand check decision table for manure application loop through each demand object again and subtract from source if available subtract manure from source set daily withdrawal and source
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure.
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
  23 isrc = 0
  24 frt_kg = 0.
  27 mallo(imallo)%tot = malloz
IF (time%day_mo == 1) THEN Lines 30-34
  31 mallo(imallo)%src(isrc)%bal_d%stor = mallo(imallo)%src(isrc)%bal_d%stor +   &
  32 mallo(imallo)%src(isrc)%prod_mon(time%day_mo)
  33 mallo(imallo)%src(isrc)%bal_d%prod = mallo(imallo)%src(isrc)%prod_mon(time%day_mo)
END IFLine 34
DO idmd = 1, mallo(imallo)%dmd_obs Lines 37-46
IF (mallo(imallo)%dmd(idmd)%dtbl /= "null" .and. mallo(imallo)%dmd(idmd)%dtbl_num /= 0) THEN Lines 39-45
  40 j = mallo(imallo)%dmd(idmd)%ob_num
  41 id = mallo(imallo)%dmd(idmd)%dtbl_num
  42 d_tbl => dtbl_lum(id)
  43 call conditions (j, id)
  44 call actions (j, idmd, id)
END IFLine 45
END DOLine 46
DO idmd = 1, mallo(imallo)%dmd_obs Lines 49-75
  50 if (mallo(imallo)%dmd(idmd)%manure_amt%app_t_ha > 0. .and.      &
  51 frt_kg > mallo(imallo)%src(isrc)%bal_d%stor) then
  52 isrc = mallo(imallo)%dmd(idmd)%manure_amt%src_obj         !source object
  53 ifrt = mallo(imallo)%src(isrc)%fertdb                     !fertilizer type from fert data base
  54 frt_kg = mallo(imallo)%dmd(idmd)%manure_amt%app_t_ha      !amount applied in kg/ha
  55 ifertop = mallo(imallo)%dmd(idmd)%manure_amt%app_method   !surface application fraction from chem app data base
  56 ihru = mallo(imallo)%dmd(idmd)%ob_num                        !hru number
  57 call pl_fert (ifrt, frt_kg, ifertop)
  58 mallo(imallo)%dmd(idmd)%manure_amt = manure_amtz
  61 mallo(imallo)%src(isrc)%bal_d%stor = mallo(imallo)%src(isrc)%bal_d%stor - frt_kg
  62 mallo(imallo)%src(isrc)%bal_d%withdr = frt_kg
  65 mallo(imallo)%dmd(idmd)%withdr(isrc) = frt_kg
IF (pco%mgtout == "y") THEN Lines 67-72
  68 write (2612, *) j, time%yrc, time%mo, time%day_mo, fertdb(ifrt)%fertnm, "    MANU",       &
  69 phubase(j),pcom(j)%plcur(ipl)%phuacc, soil(j)%sw, pl_mass(j)%tot(ipl)%m,            &
  70 soil1(j)%rsd(1)%m, sol_sumno3(j), sol_sumsolp(j), frt_kg, fertno3, fertnh3,        &
  71 fertorgn, fertsolp, fertorgp
END IFLine 72
END DOLine 75
  77 return
Allocations
n/a
Calls
Calls
Procedures called by this subroutine.
Local Variables
Type Visibility Attributes Name Initial
integer, private :: idmd
integer, private :: isrc
integer, private :: j
integer, private :: id
integer, private :: ifrt
integer, private :: ifertop
real, private :: frt_kg
Variables
Type Visibility Attributes Name Initial
integer, public :: imallo
Call graph
mallo_control calls actions, conditions, pl_fert