mgt_transplant – TestDataProject
mgt_transplant Subroutine
38 statements
Source File
subroutine mgt_transplant(itrans)
Called From
n/a
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: itrans
Outside Variables and Types
type(plant_db) (1 attribute from plant_data_module)
Attribute Name Description
pldb
type(plant_cp) (1 attribute from plant_data_module)
Attribute Name Description
plcp
type(plant_community_db) (1 attribute from plant_data_module)
Attribute Name Description
pcomdb
type(plant_transplant_db) (1 attribute from plant_data_module)
Attribute Name Description
transpl
type(hydrologic_response_unit) (1 attribute from hru_module)
Attribute Name Description
hru
integer (2 attributes from hru_module)
Attribute Name Description
ipl
ihru
none |HRU number
Read more…
type(plant_community) (1 attribute from plant_module)
Attribute Name Description
pcom
type(plant_community_mass) (1 attribute from organic_mineral_mass_module)
Attribute Name Description
pl_mass
Uses
plant_data_module
hru_module
plant_module
organic_mineral_mass_module
I/O
n/a
Local Variables
Type Visibility Attributes Name Initial
integer, public :: j = 0
integer, public :: icom = 0
integer, public :: idp = 0
real, public :: xx = 0.
real, public :: laimx_pop = 0.
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure. Use mouse wheel to zoom, drag to pan.
Reset Zoom Help
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
check plant population to set max lai (line 44)
  17 j = ihru
  18 icom = hru(j)%plant_cov
  19 idp = pcom(j)%plcur(ipl)%idplt
  22 pcom(j)%plcur(ipl)%phuacc = transpl(itrans)%phuacc
  23 pcom(j)%plcur(ipl)%phuacc_p = transpl(itrans)%fr_yrmat + (pcom(j)%plcur(ipl)%phumat *         &
  24 transpl(itrans)%phuacc) / pcom(j)%plcur(ipl)%phumat_p
  25 pcom(j)%plg(ipl)%laimxfr = pcom(j)%plcur(ipl)%phuacc / (pcom(j)%plcur(ipl)%phuacc +           &
  26 Exp(plcp(idp)%leaf1 - plcp(idp)%leaf2 * pcom(j)%plcur(ipl)%phuacc))
  27 pcom(j)%plg(ipl)%laimxfr_p = pcom(j)%plcur(ipl)%phuacc_p / (pcom(j)%plcur(ipl)%phuacc_p +     &
  28 Exp(plcp(idp)%leaf1 - plcp(idp)%leaf2 * pcom(j)%plcur(ipl)%phuacc_p))
  30 pl_mass(j)%tot(ipl)%m = transpl(itrans)%bioms
  31 pcom(j)%plcur(ipl)%curyr_mat = int (transpl(itrans)%fr_yrmat * float(pldb(idp)%mat_yrs))
  32 pcom(j)%plcur(ipl)%curyr_mat = max (1, pcom(j)%plcur(ipl)%curyr_mat)
  33 pcom(j)%plcur(ipl)%idplt = pcomdb(icom)%pl(ipl)%db_num
  34 pcom(j)%plm(ipl)%p_fr = (pldb(idp)%pltpfr1-pldb(idp)%pltpfr3)*            &
  35 (1. - pcom(j)%plcur(ipl)%phuacc/(pcom(j)%plcur(ipl)%phuacc +          &
  36 Exp(plcp(idp)%pup1 - plcp(idp)%pup2 *                                 &
  37 pcom(j)%plcur(ipl)%phuacc))) + pldb(idp)%pltpfr3
  38 pl_mass(j)%tot(ipl)%n = pcom(j)%plm(ipl)%n_fr * pl_mass(j)%tot(ipl)%m
  39 pcom(j)%plm(ipl)%n_fr = (pldb(idp)%pltnfr1- pldb(idp)%pltnfr3) *          &
  40 (1.- pcom(j)%plcur(ipl)%phuacc/(pcom(j)%plcur(ipl)%phuacc +           &
  41 Exp(plcp(idp)%nup1 - plcp(idp)%nup2 *                                 &
  42 pcom(j)%plcur(ipl)%phuacc))) + pldb(idp)%pltnfr3
IF (transpl(itrans)%pop < 1.e-6) THEN Lines 45-46
  46 laimx_pop = pldb(idp)%blai
END IFLine 46
ELSE Lines 47-50
  48 xx = transpl(itrans)%pop
  49 laimx_pop = pldb(idp)%blai * xx / (xx + exp(plcp(idp)%popsc1 - plcp(idp)%popsc2 * xx))
END IF Line 50
initialize plant mass (line 53)
  51 pcom(j)%plcur(ipl)%lai_pot = laimx_pop
  54 call pl_root_gro(j)
  55 call pl_seed_gro(j)
  56 call pl_partition(j, 1)
  58 return
Allocations
n/a
Calls
Procedures Called
List of procedures called by this Subroutine.
float
pl_root_gro
pl_seed_gro
pl_partition
Call Graph
Visual representation of procedures called by this Subroutine.
Variables
Type Visibility Attributes Name Initial
integer, public :: itrans
Call graph
mgt_transplant calls float, pl_partition, pl_root_gro, pl_seed_gro