mgt_sched – test-src-project
mgt_sched Subroutine
410 statements
Source File
subroutine mgt_sched(isched)
Uses
aquifer_module
plant_module
maximum_data_module
hru_module
basin_module
reservoir_data_module
tillage_data_module
hydrograph_module
soil_module
constituent_mass_module
mgt_operations_module
reservoir_module
time_module
calibration_data_module
organic_mineral_mass_module
plant_data_module
Arguments
Type Intent Optional Attributes Name
integer :: isched
I/O
I/O units used in this subroutine.
Unit Type Filename
unit_2612 Output not specified
Outside Variables and Types
type(plant_community) (1 attribute from plant_module)
Attribute Name Description
pcom
type(plant_stress) (1 attribute from plant_module)
Attribute Name Description
plstrz
type(basin_crop_yields) (1 attribute from plant_module)
Attribute Name Description
bsn_crop_yld
type (21 attributes from maximum_data_module)
Attribute Name Description
db_mx%tillparm None
db_mx%transplant None
db_mx%pudl_db None
pco%mgtout None
sp_ob%hru None
cs_db%pests None
cs_db%num_pests None
sweepop%fr_curb None
sweepop%eff None
mgt%op_char None
mgt%op3 None
mgt%op1 None
mgt%op2 None
mgt%op_plant None
mgt%op None
mgt%op4 None
time%day_mo None
time%yrc None
time%mo None
cal_codes%plt None
pl_yield%m None
type(hydrologic_response_unit) (1 attribute from hru_module)
Attribute Name Description
hru
integer (7 attributes from hru_module)
Attribute Name Description
ipl
ihru
none |HRU number
Read more…
yr_skip
grz_days
igrz
ndeat
mgt_ops
real (11 attributes from hru_module)
Attribute Name Description
fertno3
fertnh3
fertorgn
fertsolp
fertorgp
sol_sumno3
sol_sumsolp
sweepeff
cn2
phubase
irrp
rtb irrig (irrigation nutrient mass)
Read more
…
Read more…
type(tillage_db) (1 attribute from tillage_data_module)
Attribute Name Description
tilldb
type(hyd_output) (1 attribute from hydrograph_module)
Attribute Name Description
wet
type(irrigation_water_transfer) (1 attribute from hydrograph_module)
Attribute Name Description
irrig
dimension by hru
type(soil_profile) (1 attribute from soil_module)
Attribute Name Description
soil
type(irrigation_operation) (1 attribute from mgt_operations_module)
Attribute Name Description
irrop_db
type(puddle_operation) (1 attribute from mgt_operations_module)
Attribute Name Description
pudl_db
type(chemical_application_operation) (1 attribute from mgt_operations_module)
Attribute Name Description
chemapp_db
type(harvest_operation) (1 attribute from mgt_operations_module)
Attribute Name Description
harvop_db
type(grazing_operation) (2 attributes from mgt_operations_module)
Attribute Name Description
grazeop_db
graze
type(streetsweep_operation) (1 attribute from mgt_operations_module)
Attribute Name Description
sweepop_db
type(management_schedule) (1 attribute from mgt_operations_module)
Attribute Name Description
sched
type(wetland) (1 attribute from reservoir_module)
Attribute Name Description
wet_ob
type(soft_data_calib_plant) (1 attribute from calibration_data_module)
Attribute Name Description
plcal
dimension by region for plants
type(soil_profile_mass) (1 attribute from organic_mineral_mass_module)
Attribute Name Description
soil1
type(plant_community_mass) (1 attribute from organic_mineral_mass_module)
Attribute Name Description
pl_mass
type(fertilizer_mass) (1 attribute from organic_mineral_mass_module)
Attribute Name Description
fert
dimension to number of fertilzers in database
type(organic_mass) (1 attribute from organic_mineral_mass_module)
Attribute Name Description
manure
dimension to number of manures in database
type(plant_db) (1 attribute from plant_data_module)
Attribute Name Description
pldb
type(plant_community_db) (1 attribute from plant_data_module)
Attribute Name Description
pcomdb
type(plant_transplant_db) (1 attribute from plant_data_module)
Attribute Name Description
transpl
!! Bang Comments
plant one plant or entire community check to see if the crop is already growing plant if the crop is not growing don't plant if the crop is already growing begin and end monsoon initiation period if precip/pet ratio was not triggered during monsoon season - reset phenology harvest only operation sum yield and number of harvest to calc ave yields sum basin crop yields and area harvested sum regional crop yields for soft calibration kill operation harvest and kill operation sum yield and num. of harvest to calc ave yields sum basin crop yields and area harvested sum regional crop yields for soft calibration tillage operation date scheduled irrigation operation fertilizer operation fertilizer operation pesticide operation
grazing operation fertilizer operation burning street sweeping (only if iurban=2) set drain depth for drainage water management added below changed plcur(ipl) to plcur(j) and plm(ipl) to plm(j) gsm 1/30/2018 set/adjust weir height
set weir height and adjust principal spillway storage and depth continuous irrigation to maintain surface ponding in rice fields Jaehak 2022 date scheduled irrigation operation for rice fields Puddling operation Jaehak 2022 xwalk with puddling ops names skip a year
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure.
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
   9 yr_skip, sol_sumno3, sol_sumsolp, fertnh3, fertno3, fertorgn,  &
  10 fertorgp, fertsolp, ipl, sweepeff, yr_skip
  56 j = ihru
  57 ires= hru(j)%dbs%surf_stor ! for paddy management Jaehak 2022
  58 iob = hru(j)%obj_no
  59 wsa1 = hru(ihru)%area_ha * 10.
IF (mgt%op /= "fert ") THEN Lines 62-75
  63 mgt%op2 = 0
  64 icom = pcom(j)%pcomdb
IF (icom > 0) THEN Lines 65-74
IF (pcom(j)%npl > 1) THEN Lines 66-73
DO ipl = 1, pcom(j)%npl Lines 67-72
IF (mgt%op_char == pcomdb(icom)%pl(ipl)%cpnm) THEN Lines 68-71
  69 mgt%op2 = ipl
  70 exit
END IFLine 71
END DOLine 72
END IFLine 73
END IFLine 74
END IFLine 75
SELECT CASE (mgt%op) Lines 77-539
DO ipl = 1, pcom(j)%npl Lines 83-118
  85 idp = pcomdb(icom)%pl(ipl)%db_num
IF (mgt%op_char == pcomdb(icom)%pl(ipl)%cpnm) THEN Lines 86-117
IF (pcom(j)%plcur(ipl)%gro == "n") THEN Lines 88-107
  90 pcom(j)%plcur(ipl)%gro = "y"
  91 pcom(j)%plcur(ipl)%idorm = "n"
  92 call mgt_plantop
IF (mgt%op3 > 0) THEN Lines 93-101
 100 if (itr > 0) call mgt_transplant (itr)
DO idb = 1, db_mx%transplant Lines 94-99
IF (mgt%op_plant == transpl(idb)%name) THEN Lines 95-98
  96 itr = idb
  97 exit
END IFLine 98
END DOLine 99
END IFLine 101
IF (pco%mgtout == "y") THEN Lines 102-107
 103 write (2612, *) j, time%yrc, time%mo, time%day_mo, pldb(idp)%plantnm,  "    PLANT ",    &
 104 phubase(j), pcom(j)%plcur(ipl)%phuacc,  soil(j)%sw,                                   &
 105 pl_mass(j)%tot(ipl)%m, soil1(j)%rsd(1)%m, sol_sumno3(j),                              &
 106 sol_sumsolp(j),pcom(j)%plg(ipl)%lai, pcom(j)%plcur(ipl)%lai_pot
END IFLine 107
END IFLine 107
ELSE Lines 108-116
IF (pco%mgtout == "y") THEN Lines 110-115
 111 write (2612, *) j, time%yrc, time%mo, time%day_mo, pldb(idp)%plantnm,       &
 112 "    PLANT_ALREADY_GROWING", phubase(j), pcom(j)%plcur(ipl)%phuacc,       &
 113 soil(j)%sw, pl_mass(j)%tot(ipl)%m, soil1(j)%rsd(1)%m, sol_sumno3(j),      &
 114 sol_sumsolp(j),pcom(j)%plg(ipl)%lai, pcom(j)%plcur(ipl)%lai_pot
END IFLine 115
END IF Line 116
END IFLine 117
END DOLine 118
DO ipl = 1, pcom(j)%npl Lines 121-135
 122 idp = pcom(j)%plcur(ipl)%idplt
IF (pldb(idp)%trig == "moisture_gro") THEN Lines 123-134
 133 if (mgt%op3 == 1) pcom(j)%plcur(ipl)%mseas = "y"
IF (mgt%op3 == 0) THEN Lines 124-132
IF (pcom(j)%plcur(ipl)%gro == "n") THEN Lines 126-131
 127 pcom(j)%plcur(ipl)%phuacc = 0.
 128 pcom(j)%plcur(ipl)%gro = "y"
 129 pcom(j)%plcur(ipl)%idorm = "n"
 130 pcom(j)%plcur(ipl)%mseas = "n"
END IFLine 131
END IFLine 132
END IFLine 134
END DOLine 135
DO ipl = 1, pcom(j)%npl Lines 140-205
IF (pcom(j)%plcur(ipl)%gro == "y") THEN Lines 141-204
 142 biomass = pl_mass(j)%tot(ipl)%m
IF (mgt%op_char == pcomdb(icom)%pl(ipl)%cpnm .or. mgt%op_char == "all") THEN Lines 143-202
 144 pcom(j)%days_harv = 1       !reset days since last harvest
 171 pl_mass(j)%yield_tot(ipl) = pl_mass(j)%yield_tot(ipl) + pl_yield
 172 pl_mass(j)%yield_yr(ipl) = pl_mass(j)%yield_yr(ipl) + pl_yield
 173 pcom(j)%plcur(ipl)%harv_num = pcom(j)%plcur(ipl)%harv_num + 1
 174 pcom(j)%plcur(ipl)%harv_num_yr = pcom(j)%plcur(ipl)%harv_num_yr + 1
 177 iplt_bsn = pcom(j)%plcur(ipl)%bsn_num
 178 bsn_crop_yld(iplt_bsn)%area_ha = bsn_crop_yld(iplt_bsn)%area_ha + hru(j)%area_ha
 179 bsn_crop_yld(iplt_bsn)%yield = bsn_crop_yld(iplt_bsn)%yield + pl_yield%m * hru(j)%area_ha / 1000.
 194 idp = pcom(j)%plcur(ipl)%idplt
IF (biomass > harvop_db(iharvop)%bm_min) THEN Lines 147-168
SELECT CASE (harvop_db(iharvop)%typ) Lines 149-167
CASE ("biomass") Lines 150-151
 151 call mgt_harvbiomass (j, ipl, iharvop)
CASE ("grain") Lines 152-153
 153 call mgt_harvgrain (j, ipl, iharvop)
CASE ("residue") Lines 154-156
 155 harveff = mgt%op3
 156 call mgt_harvresidue (j, harveff)
CASE ("tree") Lines 157-158
 158 call mgt_harvbiomass (j, ipl, iharvop)
CASE ("tuber") Lines 159-160
 160 call mgt_harvtuber (j, ipl, iharvop)
CASE ("peanuts") Lines 161-162
 162 call mgt_harvtuber (j, ipl, iharvop)
CASE ("stripper") Lines 163-164
 164 call mgt_harvbiomass (j, ipl, iharvop)
CASE ("picker") Lines 165-166
 166 call mgt_harvgrain (j, ipl, iharvop)
END SELECTLine 167
END IFLine 168
IF (cal_codes%plt == "y") THEN Lines 182-192
IF (hru(j)%crop_reg > 0) THEN Lines 183-191
 184 ireg = hru(j)%crop_reg
DO ilum = 1, plcal(ireg)%lum_num Lines 185-190
IF (plcal(ireg)%lum(ilum)%meas%name == mgt%op_char) THEN Lines 186-189
 187 plcal(ireg)%lum(ilum)%ha = plcal(ireg)%lum(ilum)%ha + hru(j)%area_ha
 188 plcal(ireg)%lum(ilum)%sim%yield = plcal(ireg)%lum(ilum)%sim%yield + pl_yield%m * hru(j)%area_ha / 1000.
END IFLine 189
END DOLine 190
END IFLine 191
END IFLine 192
IF (pco%mgtout == "y") THEN Lines 195-201
 196 write (2612, *) j, time%yrc, time%mo, time%day_mo,  pldb(idp)%plantnm, "    HARVEST ",    &
 197 phubase(j), pcom(j)%plcur(ipl)%phuacc, soil(j)%sw, biomass, soil1(j)%rsd(1)%m,   &
 198 sol_sumno3(j), sol_sumsolp(j), pl_yield%m, pcom(j)%plstr(ipl)%sum_n,              &
 199 pcom(j)%plstr(ipl)%sum_p, pcom(j)%plstr(ipl)%sum_tmp, pcom(j)%plstr(ipl)%sum_w,   &
 200 pcom(j)%plstr(ipl)%sum_a
END IFLine 201
END IFLine 202
END IFLine 204
END DOLine 205
DO ipl = 1, pcom(j)%npl Lines 208-224
 209 biomass = pl_mass(j)%tot(ipl)%m
 223 pcom(j)%plcur(ipl)%phuacc = 0.
IF (mgt%op_char == pcomdb(icom)%pl(ipl)%cpnm .or. mgt%op_char == "all") THEN Lines 210-222
 211 pcom(j)%days_kill = 1       !reset days since last kill
 212 call mgt_killop (j, ipl)
 214 idp = pcom(j)%plcur(ipl)%idplt
IF (pco%mgtout == "y") THEN Lines 215-221
 216 write (2612, *) j, time%yrc, time%mo, time%day_mo,  pldb(idp)%plantnm, "    KILL ",  &
 217 phubase(j), pcom(j)%plcur(ipl)%phuacc, soil(j)%sw, biomass, soil1(j)%rsd(1)%m,   &
 218 sol_sumno3(j), sol_sumsolp(j), pl_yield%m, pcom(j)%plstr(ipl)%sum_n,              &
 219 pcom(j)%plstr(ipl)%sum_p, pcom(j)%plstr(ipl)%sum_tmp, pcom(j)%plstr(ipl)%sum_w,   &
 220 pcom(j)%plstr(ipl)%sum_a
END IFLine 221
END IFLine 222
END DOLine 224
DO ipl = 1, pcom(j)%npl Lines 229-294
 230 biomass = pl_mass(j)%tot(ipl)%m
 291 pcom(j)%plstr(ipl) = plstrz
 292 pcom(j)%plcur(ipl)%phuacc = 0.
 293 phubase(j) = 0.
IF (mgt%op_char == pcomdb(icom)%pl(ipl)%cpnm .or. mgt%op_char == "all") THEN Lines 231-290
 232 pcom(j)%days_harv = 1       !reset days since last harvest
 233 pcom(j)%days_kill = 1       !reset days since last kill
 258 call mgt_killop (j, ipl)
 261 pl_mass(j)%yield_tot(ipl) = pl_mass(j)%yield_tot(ipl) + pl_yield
 262 pl_mass(j)%yield_yr(ipl) = pl_mass(j)%yield_yr(ipl) + pl_yield
 263 pcom(j)%plcur(ipl)%harv_num = pcom(j)%plcur(ipl)%harv_num + 1
 264 pcom(j)%plcur(ipl)%harv_num_yr = pcom(j)%plcur(ipl)%harv_num_yr + 1
 267 iplt_bsn = pcom(j)%plcur(ipl)%bsn_num
 268 bsn_crop_yld(iplt_bsn)%area_ha = bsn_crop_yld(iplt_bsn)%area_ha + hru(j)%area_ha
 269 bsn_crop_yld(iplt_bsn)%yield = bsn_crop_yld(iplt_bsn)%yield + pl_yield%m * hru(j)%area_ha / 1000.
 282 idp = pcom(j)%plcur(ipl)%idplt
IF (biomass > harvop_db(iharvop)%bm_min) THEN Lines 236-256
SELECT CASE (harvop_db(iharvop)%typ) Lines 238-255
CASE ("biomass") Lines 239-240
 240 call mgt_harvbiomass (j, ipl, iharvop)
CASE ("grain") Lines 241-242
 242 call mgt_harvgrain (j, ipl, iharvop)
CASE ("residue") Lines 243-245
 244 harveff = mgt%op3
 245 call mgt_harvresidue (j, harveff)
CASE ("tree") Lines 246-246
CASE ("tuber") Lines 247-248
 248 call mgt_harvtuber (j, ipl, iharvop)
CASE ("peanuts") Lines 249-250
 250 call mgt_harvtuber (j, ipl, iharvop)
CASE ("stripper") Lines 251-252
 252 call mgt_harvgrain (j, ipl, iharvop)
CASE ("picker") Lines 253-254
 254 call mgt_harvgrain (j, ipl, iharvop)
END SELECTLine 255
END IFLine 256
IF (cal_codes%plt == "y") THEN Lines 272-280
 273 ireg = hru(j)%crop_reg
DO ilum = 1, plcal(ireg)%lum_num Lines 274-279
IF (plcal(ireg)%lum(ilum)%meas%name == mgt%op_char) THEN Lines 275-278
 276 plcal(ireg)%lum(ilum)%ha = plcal(ireg)%lum(ilum)%ha + hru(j)%area_ha
 277 plcal(ireg)%lum(ilum)%sim%yield = plcal(ireg)%lum(ilum)%sim%yield + pl_yield%m * hru(j)%area_ha / 1000.
END IFLine 278
END DOLine 279
END IFLine 280
IF (pco%mgtout == "y") THEN Lines 283-289
 284 write (2612, *) j, time%yrc, time%mo, time%day_mo,  pldb(idp)%plantnm, "    HARV/KILL ",      &
 285 phubase(j), pcom(j)%plcur(ipl)%phuacc, soil(j)%sw, biomass, soil1(j)%rsd(1)%m,           &
 286 sol_sumno3(j), sol_sumsolp(j), pl_yield%m, pcom(j)%plstr(ipl)%sum_n,                      &
 287 pcom(j)%plstr(ipl)%sum_p, pcom(j)%plstr(ipl)%sum_tmp, pcom(j)%plstr(ipl)%sum_w,           &
 288 pcom(j)%plstr(ipl)%sum_a
END IFLine 289
END IFLine 290
END DOLine 294
IF (pco%mgtout == "y") THEN Lines 300-304
 301 write (2612, *) j, time%yrc, time%mo, time%day_mo, tilldb(idtill)%tillnm, "    TILLAGE ", &
 302 phubase(j), pcom(j)%plcur(ipl)%phuacc, soil(j)%sw, pl_mass(j)%tot(ipl)%m,         &
 303 soil1(j)%rsd(1)%m, sol_sumno3(j), sol_sumsolp(j), tilldb(idtill)%effmix
END IFLine 304
IF (pco%mgtout == "y") THEN Lines 317-321
 318 write (2612, *) j, time%yrc, time%mo, time%day_mo, irrop_db(irrop)%name, "IRRIGATE ", phubase(j),   &
 319 pcom(j)%plcur(ipl)%phuacc, soil(j)%sw,pl_mass(j)%tot(ipl)%m, soil1(j)%rsd(1)%m,      &
 320 sol_sumno3(j), sol_sumsolp(j), irrig(j)%applied, irrig(j)%runoff
END IFLine 321
IF (pco%mgtout == "y") THEN Lines 332-337
 333 write (2612,*) j, time%yrc, time%mo, time%day_mo, mgt%op_char, " FERT-WET", &
 334 phubase(j), pcom(j)%plcur(ipl)%phuacc, soil(j)%sw, pl_mass(j)%tot(ipl)%m,           &
 335 soil1(j)%rsd(1)%m, sol_sumno3(j), sol_sumsolp(j), frt_kg, fertno3, fertnh3,         &
 336 fertorgn, fertsolp, fertorgp
END IFLine 337
IF (pco%mgtout == "y") THEN Lines 342-347
 343 write (2612,*) j, time%yrc, time%mo, time%day_mo, mgt%op_char, "    FERT ", &
 344 phubase(j), pcom(j)%plcur(ipl)%phuacc, soil(j)%sw, pl_mass(j)%tot(ipl)%m,           &
 345 soil1(j)%rsd(1)%m, sol_sumno3(j), sol_sumsolp(j), frt_kg, fertno3, fertnh3,         &
 346 fertorgn, fertsolp, fertorgp
END IFLine 347
IF (pco%mgtout == "y") THEN Lines 358-363
 359 write (2612,*) j, time%yrc, time%mo, time%day_mo, mgt%op_char, " MANURE ", &
 360 phubase(j), pcom(j)%plcur(ipl)%phuacc, soil(j)%sw, pl_mass(j)%tot(ipl)%m,           &
 361 soil1(j)%rsd(1)%m, sol_sumno3(j), sol_sumsolp(j), frt_kg, fertno3, fertnh3,         &
 362 fertorgn, fertsolp, fertorgp
END IFLine 363
DO ipestcom = 1, cs_db%num_pests Lines 368-373
IF (cs_db%pests(ipestcom) == mgt%op_char) THEN Lines 369-372
 370 mgt%op1 = ipestcom
 371 exit
END IFLine 372
END DOLine 373
IF (pco%mgtout == "y") THEN Lines 381-385
 382 write (2612, *) j, time%yrc, time%mo, time%day_mo, mgt%op_char, "    PEST ", &
 383 phubase(j), pcom(j)%plcur(ipl)%phuacc, soil(j)%sw,pl_mass(j)%tot(ipl)%m,   &
 384 soil1(j)%rsd(1)%m, sol_sumno3(j), sol_sumsolp(j), pest_kg
END IFLine 385
IF (pco%mgtout == "y") THEN Lines 394-398
 395 write (2612, *) j, time%yrc, time%mo, time%day_mo, mgt%op_char, "    GRAZE ",         &
 396 phubase(j), pcom(j)%plcur(ipl)%phuacc, soil(j)%sw,pl_mass(j)%tot(ipl)%m,        &
 397 soil1(j)%rsd(1)%m, sol_sumno3(j), sol_sumsolp(j), grazeop_db(mgt%op1)%eat, grazeop_db(mgt%op1)%manure
END IFLine 398
IF (pco%mgtout == "y") THEN Lines 407-411
 408 write (2612,*) j, time%yrc, time%mo, time%day_mo, mgt%op_char, "    CNUP ", &
 409 phubase(j), pcom(j)%plcur(ipl)%phuacc, soil(j)%sw, pl_mass(j)%tot(ipl)%m,           &
 410 soil1(j)%rsd(1)%m, sol_sumno3(j), sol_sumsolp(j), mgt%op3, cn2(j)
END IFLine 411
IF (pco%mgtout == "y") THEN Lines 417-423
DO ipl = 1, pcom(j)%npl Lines 418-422
 419 write (2612, *) j, time%yrc, time%mo, time%day_mo, mgt%op_char, "    BURN ", phubase(j),   &
 420 pcom(j)%plcur(ipl)%phuacc, soil(j)%sw, pl_mass(j)%tot(ipl)%m, soil1(j)%rsd(1)%m,      &
 421 sol_sumno3(j), sol_sumsolp(j)
END DOLine 422
END IFLine 423
CASE ("swep") !! street sweeping (only if iurban=2) Lines 425-538
 426 ipl = Max(1, mgt%op2)
 427 sweepop = sweepop_db(mgt%op1)
 428 sweepeff = sweepop%eff
 429 fr_curb = sweepop%fr_curb
 437 case ("dwm")    !! set drain depth for drainage water management
 438 hru(j)%lumv%sdr_dep = mgt%op3
 454 case ("weir")    !! set/adjust weir height
 457 wet_ob(j)%weir_hgt = mgt%op3 / 1000. !weir height, m
 458 wet_ob(j)%pvol = hru(j)%area_ha * wet_ob(j)%weir_hgt * 10000. !m3
 463 case ("irrp")  !! continuous irrigation to maintain surface ponding in rice fields Jaehak 2022
 464 hru(j)%irr_src = mgt%op_plant                   !irrigation source: cha; res; aqu; or unlim
 465 hru(j)%irr_isc = mgt%op3                        !irrigation source object ID: cha; res; aqu; or unlim
 466 hru(j)%irr_hmax = irrop_db(mgt%op1)%amt_mm     !irrigation amount in irr.org, mm
 467 hru(j)%irr_hmin = hru(j)%irr_hmax * 0.9        !threshold ponding depth, mm
 468 irrig(j)%eff = irrop_db(mgt%op1)%eff
 469 irrig(j)%frac_surq = irrop_db(mgt%op1)%surq
 470 irrig(j)%salt = irrop_db(mgt%op1)%salt  !ppm salt  Jaehak 2023
 471 irrig(j)%no3 = irrop_db(mgt%op1)%no3 !ppm  no3
 472 pcom(j)%days_irr = 1            ! reset days since last irrigation
 493 case ("irpm")  !! date scheduled irrigation operation for rice fields
 494 ipl = 1
 495 irrop = mgt%op1                        !irrigation amount (mm) from irr.ops data base
 496 irrig(j)%applied = irrop_db(irrop)%amt_mm * irrop_db(irrop)%eff * (1. - irrop_db(irrop)%surq)
 497 irrig(j)%runoff = irrop_db(irrop)%amt_mm * irrop_db(irrop)%surq
 498 pcom(j)%days_irr = 1            ! reset days since last irrigation
 501 hru(j)%irr_yr = hru(j)%irr_yr + irrig(j)%applied
 510 case ("pudl")    !! Puddling operation Jaehak 2022
 519 if (pudl_db(ipud)%wet_hc>0) hru(j)%wet_hc = pudl_db(ipud)%wet_hc
 521 wet(j)%sed = pudl_db(ipud)%sed * wet(j)%flo / 1000000.      ! t = ppm (1 t/1000000 m3) * m3
 536 case ("skip")    !! skip a year
 537 yr_skip(j) = 1
IF (pco%mgtout == "y") THEN Lines 431-435
 432 write (2612, *) j, time%yrc, time%mo, time%day_mo, mgt%op_char, "STREET_SWEEP ", phubase(j),    &
 433 pcom(j)%plcur(ipl)%phuacc, soil(j)%sw, pl_mass(j)%tot(ipl)%m, soil1(j)%rsd(1)%m,          &
 434 sol_sumno3(j), sol_sumsolp(j)
END IFLine 435
IF (hru(j)%lumv%sdr_dep > 0) THEN Lines 439-443
DO jj = 1, soil(j)%nly Lines 440-443
 441 if (hru(j)%lumv%sdr_dep < soil(j)%phys(jj)%d) hru(j)%lumv%ldrain = jj
 442 if (hru(j)%lumv%sdr_dep < soil(j)%phys(jj)%d) exit
END DOLine 443
END IFLine 443
ELSE Lines 444-446
 445 hru(j)%lumv%ldrain = 0
END IF Line 446
IF (pco%mgtout == "y") THEN Lines 448-452
 449 write (2612, *) j, time%yrc, time%mo, time%day_mo, pldb(idp)%plantnm,  "  DRAIN_CONTROL",         &
 450 phubase(j), pcom(j)%plcur(j)%phuacc,  soil(j)%sw, pl_mass(j)%tot(j)%m, soil1(j)%rsd(1)%m,    &
 451 sol_sumno3(j), sol_sumsolp(j),hru(j)%lumv%sdr_dep
END IFLine 452
IF (wet_ob(j)%evol < wet_ob(j)%pvol*1.1) THEN Lines 459-461
 460 wet_ob(j)%evol = wet_ob(j)%pvol * 1.1
END IFLine 461
IF (mgt%op3 < 0) THEN Lines 473-475
 474 hru(j)%irr_hmax = irrop_db(mgt%op1)%amt_mm     !irrigation amount in irr.org, mm
 475 if (hru(j)%irr_hmax>0) hru(j)%paddy_irr = 1 !paddy irrigation is on with manual scheduling
END IFLine 475
ELSE Lines 476-484
 477 hru(j)%irr_hmax = mgt%op3       !target ponding depth, mm
IF (mgt%op3 > 0) THEN Lines 478-479
 479 hru(j)%paddy_irr = 1 !paddy irrigation is on with manual scheduling
END IFLine 479
ELSE Lines 480-483
 481 hru(j)%paddy_irr = 0!paddy irrigation is off
 482 hru(j)%irr_hmin = 0
END IF Line 483
END IF Line 484
IF (pco%mgtout == "y") THEN Lines 487-491
 488 write (2612, *) j, time%yrc, time%mo, time%day_mo, mgt%op_char, "BEGIN_PADDY_IRRIGATION ", phubase(j),   &
 489 pcom(j)%plcur(ipl)%phuacc, soil(j)%sw,pl_mass(j)%tot(ipl)%m, soil1(j)%rsd(1)%m,      &
 490 sol_sumno3(j), sol_sumsolp(j), mgt%op3, mgt%op4
END IFLine 491
IF (pco%mgtout == "y") THEN Lines 504-508
 505 write (2612, *) j, time%yrc, time%mo, time%day_mo,  mgt%op_char, "IRRIGATE ", phubase(j),   &
 506 pcom(j)%plcur(ipl)%phuacc, soil(j)%sw,pl_mass(j)%tot(ipl)%m, soil1(j)%rsd(1)%m,      &
 507 sol_sumno3(j), sol_sumsolp(j), irrig(j)%applied, irrig(j)%runoff
END IFLine 508
DO ipdl = 1, db_mx%pudl_db Lines 512-516
IF (pudl_db(ipdl)%name == mgt%op_plant) THEN Lines 513-515
 514 ipud = ipdl
END IFLine 515
END DOLine 516
DO idb = 1, db_mx%tillparm Lines 523-528
IF (tilldb(idb)%tillnm == mgt%op_char) THEN Lines 524-527
 525 idtill = idb
 526 exit
END IFLine 527
END DOLine 528
IF (wet_ob(j)%depth > 0.001) THEN Lines 530-531
 531 call mgt_newtillmix_wet(j,idtill)
END IFLine 531
ELSE Lines 532-534
 533 call mgt_newtillmix(j,0.,idtill)
END IF Line 534
END SELECTLine 539
 541 if (mgt%op /= "skip") hru(j)%cur_op = hru(j)%cur_op + 1  !don't increment if skip year
IF (hru(j)%cur_op > sched(isched)%num_ops) THEN Lines 542-544
 543 hru(j)%cur_op = 1
END IFLine 544
 546 mgt = sched(isched)%mgt_ops(hru(j)%cur_op)
 548 return
Allocations
n/a
Calls
Calls
Procedures called by this subroutine.
Local Variables
Type Visibility Attributes Name Initial
integer, private :: icom
integer, private :: idp
integer, private :: j
integer, private :: iharvop
integer, private :: idtill
integer, private :: ifrt
integer, private :: iob
integer, private :: ipestcom
integer, private :: ipest
integer, private :: ipestop
integer, private :: irrop
integer, private :: jj
integer, private :: iburn
integer, private :: ifertop
integer, private :: iplt_bsn
integer, private :: ireg
integer, private :: ilum
real, private :: fr_curb
integer, private :: ires
integer, private :: ipud
integer, private :: ipdl
real, private :: biomass
real, private :: frt_kg
real, private :: pest_kg
real, private :: chg_par
real, private :: wsa1
real, private :: harveff
integer, private :: idb
integer, private :: itr
Variables
Type Visibility Attributes Name Initial
integer, public :: isched
Call graph
mgt_sched calls cs_fert, cs_fert_wet, curno, mgt_harvbiomass, mgt_harvgrain, mgt_harvresidue, mgt_harvtuber, mgt_killop, mgt_newtillmix, mgt_newtillmix_wet, mgt_plantop, mgt_transplant, pest_apply, pl_burnop, pl_fert, pl_fert_wet, pl_manure, salt_fert, salt_fert_wet