pl_biomass_gro – TestDataProject
pl_biomass_gro Subroutine
99 statements
Source File
subroutine pl_biomass_gro()
Called From
n/a
Arguments
n/a
Outside Variables and Types
type (7 attributes from basin_module)
Attribute Name Description
bsn_cc%cswat None
bsn_cc%nostress None
bsn_prm%co2 None
cs_db%num_salts None
cs_db%num_cs None
pl_mass_up%c None
pl_mass_up%m None
type(plant_db) (1 attribute from plant_data_module)
Attribute Name Description
pldb
type(plant_cp) (1 attribute from plant_data_module)
Attribute Name Description
plcp
integer (5 attributes from hydrograph_module)
Attribute Name Description
iwst
|
salt_uptake_on
flag for simulating salt uptake
salt_effect
|1 = applied after other stresses; 2 = included with other stresses (min)
ipl
ihru
none |HRU number
Read more…
type(object_connectivity) (1 attribute from hydrograph_module)
Attribute Name Description
ob
type(output_plantweather) (1 attribute from output_landscape_module)
Attribute Name Description
hpw_d
type(hydrologic_response_unit) (1 attribute from hru_module)
Attribute Name Description
hru
real (12 attributes from hru_module)
Attribute Name Description
rto_no3
rto_solp
uno3d_tot
uapd_tot
sum_no3
sum_solp
uno3d
uapd
par
bioday
vpd
co2y
type(carbon_plant_gain_losses) (1 attribute from carbon_module)
Attribute Name Description
hpc_d
type(plant_community) (1 attribute from plant_module)
Attribute Name Description
pcom
type(weather_station) (1 attribute from climate_module)
Attribute Name Description
wst
Uses
basin_module
plant_data_module
constituent_mass_module
hydrograph_module
output_landscape_module
salt_module
salt_data_module
hru_module
organic_mineral_mass_module
carbon_module
plant_module
climate_module
I/O
n/a
Local Variables
Type Visibility Attributes Name Initial
integer, public :: j = 0
real, public :: ruedecl = 0.
real, public :: beadj = 0.
real, public :: rto = 0.
integer, public :: idp = 0
integer, public :: iob = 0
integer, public :: iwgn = 0
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure. Use mouse wheel to zoom, drag to pan.
Reset Zoom Help
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
if plant hasn't reached maturity (line 36)
   6 ihru, ipl, rto_no3, rto_solp, sum_no3, sum_solp, uapd_tot, uno3d_tot, vpd
  30 j = ihru
  31 idp = pcom(j)%plcur(ipl)%idplt
  32 iwst = ob(j)%wst
  33 iwgn = wst(iwst)%wco%wgn
  34 rto = 1.
IF (pcom(j)%plcur(ipl)%phuacc <= 1.) THEN Lines 37-133
calculate optimal biomass (line 39)
adjust radiation-use efficiency for CO2 (line 40)
calculate optimal biomass (line 39)
adjust radiation-use efficiency for CO2 (line 40)
adjust radiation-use efficiency for vapor pressure deficit (line 48)
assumes vapor pressure threshold of 1.0 kPa (line 49)
adjust radiation-use efficiency for vapor pressure deficit (line 48)
assumes vapor pressure threshold of 1.0 kPa (line 49)
adjust radiation-use efficiency for day length (line 58)
compute temperature stress (line 66)
compute n and p uptake and stresses (line 69)
compute n and p uptake and stresses (line 69)
try water stress as function of precip/pet (line 94)
code to turn off all plant stress (line 104)
try water stress as function of precip/pet (line 94)
code to turn off all plant stress (line 104)
code to turn off nutrient plant stress only (line 114)
code to turn off nutrient plant stress only (line 114)
reduce predicted biomass due to stress on plant (line 125)
reduce predicted biomass due to salt stress on plant (rtb salt) (line 130)
reduce predicted biomass due to salt stress on plant (rtb salt) (line 130)
  59 iob = hru(j)%obj_no
  60 iwst = ob(iob)%wst
  63 bioday = beadj * par(ipl)
  64 if (bioday < 0.) bioday = 0.
  67 call pl_tstr
  81 uno3d(ipl) = Min(4. * pldb(idp)%pltnfr3 * bioday, uno3d(ipl))
  87 call pl_nup
  88 call pl_pup
  92 if(cs_db%num_cs > 0) call cs_uptake !rtb cs
 126 if(salt_effect == 1) then !salinity stress applied after other stresses
 127 pcom(j)%plstr(ipl)%reg = Min(pcom(j)%plstr(ipl)%strsw, pcom(j)%plstr(ipl)%strst,      &
 128 pcom(j)%plstr(ipl)%strsn, pcom(j)%plstr(ipl)%strsp,      &
 129 pcom(j)%plstr(ipl)%strsa)
IF (bsn_prm%co2 > 350.) THEN Lines 41-43
  42 beadj = 100. * co2y(time%yrs) / (co2y(time%yrs) +        &
  43 Exp(plcp(idp)%ruc1 - co2y(time%yrs) * plcp(idp)%ruc2))
END IFLine 43
ELSE Lines 44-46
  45 beadj = pldb(idp)%bio_e
END IF Line 46
IF (vpd > 1.0) THEN Lines 50-54
  51 ruedecl = vpd - 1.0
  52 beadj = beadj - pldb(idp)%wavp * ruedecl
  53 beadj = Max(beadj, 0.27 * pldb(idp)%bio_e)
END IFLine 54
IF (uno3d_tot > sum_no3) THEN Lines 70-71
  71 rto_no3 = uno3d(ipl) / uno3d_tot
END IFLine 71
ELSE Lines 72-74
  73 rto_no3 = 1.
END IF Line 74
IF (uapd_tot > sum_solp) THEN Lines 75-76
  76 rto_solp = uapd(ipl) / uapd_tot
END IFLine 76
ELSE Lines 77-79
  78 rto_solp = 1.
END IF Line 79
IF (uapd(ipl) > 10.) THEN Lines 82-84
  83 uapd(ipl) = Min(4. * pldb(idp)%pltpfr3 * bioday, uapd(ipl))
END IFLine 84
IF (cs_db%num_salts > 0 .and. salt_uptake_on == 1) THEN Lines 89-91
  90 call salt_uptake !rtb salt
END IFLine 91
IF (bsn_cc%nostress == 1) THEN Lines 105-112
 106 pcom(j)%plstr(ipl)%strsw = 1.
 107 pcom(j)%plstr(ipl)%strst = 1.
 108 pcom(j)%plstr(ipl)%strsn = 1.
 109 pcom(j)%plstr(ipl)%strsp = 1.
 110 pcom(j)%plstr(ipl)%strsa = 1.
 111 pcom(j)%plstr(ipl)%strss = 1. !rtb salt
END IFLine 112
IF (bsn_cc%nostress == 2) THEN Lines 115-118
 116 pcom(j)%plstr(ipl)%strsn = 1.
 117 pcom(j)%plstr(ipl)%strsp = 1.
END IFLine 118
IF (cs_db%num_salts > 0) THEN Lines 131-133
 132 pcom(j)%plstr(ipl)%reg = pcom(j)%plstr(ipl)%reg * pcom(j)%plstr(ipl)%strss
END IFLine 133
END IFLine 133
ELSE Lines 134-138
 135 pcom(j)%plstr(ipl)%reg = Min(pcom(j)%plstr(ipl)%strsw, pcom(j)%plstr(ipl)%strst,      &
 136 pcom(j)%plstr(ipl)%strsn, pcom(j)%plstr(ipl)%strsp,      &
 137 pcom(j)%plstr(ipl)%strsa, pcom(j)%plstr(ipl)%strss)
END IF Line 138
increase in plant c (line 147)
 139 if (pcom(j)%plstr(ipl)%reg < 0.) pcom(j)%plstr(ipl)%reg = 0.
 140 if (pcom(j)%plstr(ipl)%reg > 1.) pcom(j)%plstr(ipl)%reg = 1.
 142 pl_mass_up%m = bioday * pcom(j)%plstr(ipl)%reg
 143 pl_mass_up%c = 0.42 * bioday * pcom(j)%plstr(ipl)%reg
 144 hpw_d(j)%bm_grow = hpw_d(j)%bm_grow + pl_mass_up%m
 145 hpw_d(j)%c_gro = hpw_d(j)%c_gro + pl_mass_up%c
IF (bsn_cc%cswat == 2) THEN Lines 148-150
 149 hpc_d(j)%npp_c = hpc_d(j)%npp_c + pl_mass_up%c
END IFLine 150
sum plant stresses (line 152)
 153 pcom(j)%plstr(ipl)%sum_w = pcom(j)%plstr(ipl)%sum_w + (1. - pcom(j)%plstr(ipl)%strsw)
 154 pcom(j)%plstr(ipl)%sum_tmp = pcom(j)%plstr(ipl)%sum_tmp + (1.-pcom(j)%plstr(ipl)%strst)
 155 pcom(j)%plstr(ipl)%sum_n = pcom(j)%plstr(ipl)%sum_n + (1. - pcom(j)%plstr(ipl)%strsn)
 156 pcom(j)%plstr(ipl)%sum_p = pcom(j)%plstr(ipl)%sum_p + (1. - pcom(j)%plstr(ipl)%strsp)
 157 pcom(j)%plstr(ipl)%sum_a = pcom(j)%plstr(ipl)%sum_a + (1. - pcom(j)%plstr(ipl)%strsa)
 161 return
Allocations
n/a
Calls
Procedures Called
List of procedures called by this Subroutine.
pl_tstr
pl_nup
pl_pup
salt_uptake
cs_uptake
Call Graph
Visual representation of procedures called by this Subroutine.
Call graph
pl_biomass_gro calls cs_uptake, pl_nup, pl_pup, pl_tstr, salt_uptake