pl_grow – test-src-project
pl_grow Subroutine
36 statements
Source File
subroutine pl_grow()
Uses
output_landscape_module
hru_module
basin_module
carbon_module
plant_module
time_module
organic_mineral_mass_module
plant_data_module
Arguments
n/a
I/O
n/a
Outside Variables and Types
type(output_plantweather) (1 attribute from output_landscape_module)
Attribute Name Description
hpw_d
integer (2 attributes from hru_module)
Attribute Name Description
ipl
ihru
none |HRU number
Read more…
type(plant_community) (1 attribute from plant_module)
Attribute Name Description
pcom
type (1 attribute from time_module)
Attribute Name Description
time%end_yr None
type(organic_mass) (2 attributes from organic_mineral_mass_module)
Attribute Name Description
pl_mass_up
kg/ha |daily biomass and c increase; n and p uptake
Read more…
plt_mass_z
type(plant_db) (1 attribute from plant_data_module)
Attribute Name Description
pldb
!! Bang Comments
zero biomass increase and nutrient uptake check for start and end of dormancy of temp-based growth plant plant will not undergo stress if dormant
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure.
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
  17 j = ihru
  19 call pl_nut_demand
  21 hpw_d(j)%bm_grow = 0.0
  22 hpw_d(j)%c_gro = 0.0
DO ipl = 1, pcom(j)%npl
  26 pl_mass_up = plt_mass_z
  54 if (time%end_yr == 1) call pl_mortality
  56 end do    ! loop for number of plants
  58 return
IF (pcom(j)%plcur(ipl)%gro == "y") THEN Lines 29-34
  30 idp = pcom(j)%plcur(ipl)%idplt
IF (pldb(idp)%trig == "temp_gro") THEN Lines 31-33
  32 call pl_dormant
END IFLine 33
END IFLine 34
IF (pcom(j)%plcur(ipl)%idorm == "n" .and. pcom(j)%plcur(ipl)%gro == "y") THEN Lines 38-52
  40 call pl_biomass_gro
  42 call pl_root_gro(j)
  44 call pl_leaf_gro
  46 call pl_leaf_senes
  48 call pl_seed_gro(j)
  50 call pl_partition(j, 0)
END IFLine 52
END DO
Allocations
n/a
Calls
Calls
Procedures called by this subroutine.
Local Variables
Type Visibility Attributes Name Initial
integer, private :: j
integer, private :: idp
Call graph
pl_grow calls pl_biomass_gro, pl_dormant, pl_leaf_gro, pl_leaf_senes, pl_mortality, pl_nut_demand, pl_partition, pl_root_gro, pl_seed_gro