pl_leaf_gro – test-src-project
pl_leaf_gro Subroutine
70 statements
Source File
subroutine pl_leaf_gro()
Uses
hru_module
basin_module
carbon_module
plant_module
organic_mineral_mass_module
plant_data_module
Arguments
n/a
I/O
n/a
Outside Variables and Types
integer (2 attributes from hru_module)
Attribute Name Description
ipl
ihru
none |HRU number
Read more…
type(plant_community) (1 attribute from plant_module)
Attribute Name Description
pcom
type(plant_db) (1 attribute from plant_data_module)
Attribute Name Description
pldb
type(plant_cp) (1 attribute from plant_data_module)
Attribute Name Description
plcp
!! Bang Comments
~ ~ ~ PURPOSE ~ ~ ~
this subroutine adjusts plant biomass, leaf area index, and canopy height
taking into account the effect of water, temperature and nutrient stresses
on the plant
~ ~ ~ INCOMING VARIABLES ~ ~ ~
name        |units            |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
blai(:)     |none             |maximum (potential) leaf area index
bio_e(:)    |(kg/ha)/(MJ/m**2)|biomass-energy ratio
                              |The potential (un stressed) growth rate per
                              |unit of intercepted photosynthetically
                              |active radiation.
dlai(:)     |none             |fraction of growing season when leaf
                              |area declines
ep_day      |mm H2O           |actual amount of transpiration that occurs
                              |on day in HRU
es_day      |mm H2O           |actual amount of evaporation (soil et) that
                              |occurs on day in HRU
hvsti(:)    |(kg/ha)/(kg/ha)  |harvest index: crop yield/aboveground
                              |biomass
ihru        |none             |HRU number
leaf1(:)    |none             |1st shape parameter for leaf area
                              |development equation.
leaf2(:)    |none             |2nd shape parameter for leaf area
                              |development equation.
pet_day     |mm H2O           |potential evapotranspiration on current day
                              |in HRU
t_base(:)   |deg C            |minimum temperature for plant growth
vpd         |kPa              |vapor pressure deficit
ruc1(:)    |none             |1st shape parameter for radiation use
                              |efficiency equation.
ruc2(:)    |none             |2nd shape parameter for radiation use
                              |efficiency equation.
wavp(:)     |none             |Rate of decline in radiation use efficiency
                              |as a function of vapor pressure deficit
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ OUTGOING VARIABLES ~ ~ ~
name        |units         |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
bioday      |kg            |biomass generated on current day in HRU
rsr1c(:)    |              |initial root to shoot ratio at beg of growing season
rsr2c(:)    |              |root to shoot ratio at end of growing season
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ LOCAL DEFINITIONS ~ ~ ~
name        |units            |definition
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
par         |MJ/m^2           |photosynthetically active radiation
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
~ ~ ~ SUBROUTINES/FUNCTIONS CALLED ~ ~ ~
Intrinsic: Exp, Max, Min, Sqrt
SWAT: tstr, nup, npup, anfert
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~
calculate new leaf area index when phuacc < dlai calculate new canopy height calculate fraction of above ground tree biomass that is leaf ***needs to be a plants.plt parameter only apply water stress to lai
adjust lai increment for plant competition
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure.
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
  83 j = ihru
  84 idp = pcom(j)%plcur(ipl)%idplt
  86 f = pcom(j)%plcur(ipl)%phuacc / (pcom(j)%plcur(ipl)%phuacc +                  &
  87 Exp(plcp(idp)%leaf1 - plcp(idp)%leaf2 * pcom(j)%plcur(ipl)%phuacc))
  88 pcom(j)%plg(ipl)%laimxfr = amin1 (f, pcom(j)%plg(ipl)%laimxfr)    !dormancy and grazing lower phuacc
  89 ff = f - pcom(j)%plg(ipl)%laimxfr
  90 pcom(j)%plg(ipl)%laimxfr = f
  92 exponent = plcp(idp)%leaf1 - plcp(idp)%leaf2 * pcom(j)%plcur(ipl)%phuacc_p  ! fg added to check value
  94 if (exponent < -16.0) exponent = -16.0                                      ! fg added to check value
  99 f_p = pcom(j)%plcur(ipl)%phuacc_p / (pcom(j)%plcur(ipl)%phuacc_p +            &  ! fg change
 100 Exp(exponent))
IF (pcom(j)%plcur(ipl)%phuacc < pldb(idp)%dlai) THEN
 108 laimax = 0.
 109 deltalai = 0.
 133 if (pcom(j)%plg(ipl)%lai > laimax) pcom(j)%plg(ipl)%lai = laimax
 135 deltalai = ff * laimax * (1.0 - Exp(5.0 * (pcom(j)%plg(ipl)%lai - laimax))) * Sqrt(pcom(j)%plstr(ipl)%strsw)
 137 sumlaiht = 0.
 146 deltalai = deltalai * rto
 147 pcom(j)%plg(ipl)%lai = pcom(j)%plg(ipl)%lai + deltalai
 149 if (pcom(j)%plg(ipl)%lai > laimax) pcom(j)%plg(ipl)%lai = laimax
 150 pcom(j)%plg(ipl)%olai = pcom(j)%plg(ipl)%lai
 151 pcom(j)%plg(ipl)%dphu = pcom(j)%plcur(ipl)%phuacc
 152 end if    ! phu < dlai
 154 return
IF (pldb(idp)%typ == "perennial") THEN Lines 110-116
 111 if (pcom(j)%plcur(ipl)%curyr_mat < 1) pcom(j)%plcur(ipl)%curyr_mat = 1
 112 rto_lin = float(pcom(j)%plcur(ipl)%curyr_mat) / float(pldb(idp)%mat_yrs)
 113 rto = alog10 (rto_lin)
 114 lai_exp = rto * pldb(idp)%laixco_tree
 115 laimax = pcom(j)%plcur(ipl)%lai_pot * 10. ** lai_exp
 116 laimax = Min (laimax, pcom(j)%plcur(ipl)%lai_pot)
END IFLine 116
ELSE Lines 117-119
 118 laimax = pcom(j)%plcur(ipl)%lai_pot
END IF Line 119
IF (pldb(idp)%typ == "perennial") THEN Lines 122-123
 123 pcom(j)%plg(ipl)%cht = pldb(idp)%chtmx * Sqrt(f_p)
END IFLine 123
ELSE Lines 124-126
 125 pcom(j)%plg(ipl)%cht = pldb(idp)%chtmx * Sqrt(f)
END IF Line 126
IF (pldb(idp)%typ == "perennial") THEN Lines 129-131
 130 pcom(j)%plg(ipl)%leaf_frac = 0.03     !!***needs to be a plants.plt parameter
END IFLine 131
DO jpl = 1, pcom(j)%npl Lines 138-140
 139 sumlaiht = sumlaiht + pcom(j)%plg(ipl)%lai * pcom(j)%plg(jpl)%cht
END DOLine 140
IF (sumlaiht > 1.e-6) THEN Lines 141-142
 142 rto = (pcom(j)%plg(ipl)%lai * pcom(j)%plg(ipl)%cht) / sumlaiht
END IFLine 142
ELSE Lines 143-145
 144 rto = 1.
END IF Line 145
END IF
Allocations
n/a
Calls
Calls
Procedures called by this subroutine.
Local Variables
Type Visibility Attributes Name Initial
integer, private :: j
integer, private :: idp
real, private :: f
real, private :: f_p
real, private :: ff
real, private :: deltalai
real, private :: laimax
real, private :: lai_exp
real, private :: rto_lin
real, private :: rto
real, private :: sumlaiht
real, private :: exponent
integer, private :: jpl
Call graph
pl_leaf_gro calls alog10, amin1, float