pl_nup – TestDataProject
pl_nup Subroutine
64 statements
Source File
subroutine pl_nup()
Called From
n/a
Arguments
n/a
Outside Variables and Types
type (3 attributes from basin_module)
Attribute Name Description
bsn_prm%n_updis None
pl_mass_up%n None
uptake%n_norm None
type(plant_db) (1 attribute from plant_data_module)
Attribute Name Description
pldb
type(soil_profile) (1 attribute from soil_module)
Attribute Name Description
soil
type(output_nutbal) (1 attribute from output_landscape_module)
Attribute Name Description
hnb_d
type(soil_profile_mass) (1 attribute from organic_mineral_mass_module)
Attribute Name Description
soil1
type(plant_community_mass) (1 attribute from organic_mineral_mass_module)
Attribute Name Description
pl_mass
integer (2 attributes from hru_module)
Attribute Name Description
ipl
ihru
none |HRU number
Read more…
real (5 attributes from hru_module)
Attribute Name Description
rto_no3
uno3d
un2
fixn
nplnt
type(plant_community) (1 attribute from plant_module)
Attribute Name Description
pcom
Uses
basin_module
plant_data_module
soil_module
output_landscape_module
organic_mineral_mass_module
hru_module
plant_module
I/O
n/a
Local Variables
Type Visibility Attributes Name Initial
integer, public :: j = 0
integer, public :: l = 0
real, public :: uno3l = 0.
integer, public :: idp = 0
real, public :: root_depth = 0.
real, public :: unmx = 0.
real, public :: soil_depth = 0.
real, public :: xx = 0.
integer, public :: max
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure. Use mouse wheel to zoom, drag to pan.
Reset Zoom Help
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
~ ~ ~ PURPOSE ~ ~ ~ (line 3)
This subroutine calculates plant nitrogen uptake (line 4)
~ ~ ~ INCOMING VARIABLES ~ ~ ~ (line 6)
name |units |definition (line 7)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ (line 8)
nup1(:) |none |1st shape parameter for plant N uptake (line 9)
|equation (line 10)
nup2(:) |none |2nd shape parameter for plant N uptake (line 11)
|equation (line 12)
ihru |none |HRU number (line 13)
pltnfr(1,:) |kg N/kg biomass|nitrogen uptake parameter #1: normal fraction (line 14)
|of N in crop biomass at emergence (line 15)
pltnfr(3,:) |kg N/kg biomass|nitrogen uptake parameter #3: normal fraction (line 16)
|of N in crop biomass at maturity (line 17)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ (line 18)
~ ~ ~ OUTGOING VARIABLES ~ ~ ~ (line 20)
name |units |definition (line 21)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ (line 22)
uno3d |kg N/ha |plant nitrogen deficiency for day in HRU (line 23)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ (line 24)
~ ~ ~ LOCAL DEFINITIONS ~ ~ ~ (line 26)
name |units |definition (line 27)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ (line 28)
un2 |kg N/ha |ideal plant nitrogen content (line 29)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ (line 30)
~ ~ ~ SUBROUTINES/FUNCTIONS CALLED ~ ~ ~ (line 32)
Intrinsic: Exp, Min (line 33)
SWAT: nfix, nuts (line 34)
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~ (line 36)
find depth of soil layer the roots are into (line 65)
  58 j = ihru
  60 idp = pcom(j)%plcur(ipl)%idplt
  61 pcom(j)%plstr(ipl)%strsn = 1.
  62 hnb_d(j)%nuptake = 0.
  63 if (uno3d(ipl) < 1.e-6) return
  66 root_depth = max (10.1, pcom(j)%plg(ipl)%root_dep)
  67 soil_depth = 0.
DO l = 1, soil(j)%nly Lines 68-74
  69 soil_depth = soil(j)%phys(l)%d
IF (root_depth < soil_depth) THEN Lines 70-73
  71 root_depth = soil(j)%phys(l)%d
  72 exit
END IFLine 73
END DOLine 74
DO l = 1, soil(j)%nly Lines 76-85
  77 soil_depth = soil(j)%phys(l)%d
  78 if (root_depth < soil_depth) exit
  79 unmx = uno3d(ipl) * rto_no3 * (1. - Exp(-bsn_prm%n_updis * soil_depth / root_depth)) / uptake%n_norm
  80 uno3l = Min(unmx - nplnt(j), soil1(j)%mn(l)%no3)
  82 nplnt(j) = nplnt(j) + uno3l
  83 soil1(j)%mn(l)%no3 = soil1(j)%mn(l)%no3 - uno3l
END DOLine 85
if crop is a legume, call nitrogen fixation routine (line 88)
  86 if (nplnt(j) < 0.) nplnt(j) = 0.
IF (pldb(idp)%nfix_co > 1.e-6) THEN Lines 89-91
  90 call pl_nfix
END IFLine 91
compute nitrogen stress (line 100)
  93 nplnt(j) = nplnt(j) + fixn
  94 pl_mass(j)%tot(ipl)%n = pl_mass(j)%tot(ipl)%n + nplnt(j)
  95 pl_mass(j)%ab_gr(ipl)%n = pl_mass(j)%ab_gr(ipl)%n + nplnt(j) * (1. - pcom(j)%plg(ipl)%root_frac)
  96 pl_mass(j)%root(ipl)%n = pl_mass(j)%root(ipl)%n + nplnt(j) * pcom(j)%plg(ipl)%root_frac
  97 pl_mass_up%n = nplnt(j)
  98 hnb_d(j)%nuptake = hnb_d(j)%nuptake + nplnt(j)
IF (pldb(idp)%nfix_co > 1.e-6) THEN Lines 102-103
 103 pcom(j)%plstr(ipl)%strsn = 1.
END IFLine 103
ELSE Lines 104-113
 105 call nuts (pl_mass(j)%tot(ipl)%n, un2(ipl), pcom(j)%plstr(ipl)%strsn)
 111 pcom(j)%plstr(ipl)%strsn = Max(pcom(j)%plstr(ipl)%strsn, xx)
 112 pcom(j)%plstr(ipl)%strsn = amin1(pcom(j)%plstr(ipl)%strsn, 1.)
IF (uno3d(ipl) > 1.e-5) THEN Lines 106-107
 107 xx = nplnt(j) / uno3d(ipl)
END IFLine 107
ELSE Lines 108-110
 109 xx = 1.
END IF Line 110
END IF Line 113
 115 return
Allocations
n/a
Calls
Procedures Called
List of procedures called by this Subroutine.
pl_nfix
nuts
amin1
Call Graph
Visual representation of procedures called by this Subroutine.
Call graph
pl_nup calls amin1, nuts, pl_nfix