plant_init – TestDataProject
plant_init Subroutine
327 statements
Source File
subroutine plant_init(init, iihru)
Called From
n/a
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: init
integer, intent(in) :: iihru
Outside Variables and Types
type(plant_db) (1 attribute from plant_data_module)
Attribute Name Description
pldb
type(plant_cp) (1 attribute from plant_data_module)
Attribute Name Description
plcp
type(plant_community_db) (1 attribute from plant_data_module)
Attribute Name Description
pcomdb
type(soil_profile) (1 attribute from soil_module)
Attribute Name Description
soil
type (14 attributes from time_module)
Attribute Name Description
time%day_start None
db_mx%urban None
db_mx%ovn None
luse%urb_ro None
luse%urb_lu None
luse%ovn None
rsd_meta%c None
rsd_meta%p None
rsd_meta%m None
rsd_meta%n None
rsd_str%c None
rsd_str%p None
rsd_str%m None
rsd_str%n None
integer (4 attributes from hydrograph_module)
Attribute Name Description
iwst
|
ipl
mo
mgt_ops
type(object_connectivity) (1 attribute from hydrograph_module)
Attribute Name Description
ob
type(land_use_management) (1 attribute from landuse_data_module)
Attribute Name Description
lum
type(land_use_structures) (1 attribute from landuse_data_module)
Attribute Name Description
lum_str
type(conservation_practice_table) (1 attribute from landuse_data_module)
Attribute Name Description
cons_prac
type(overlandflow_n_table) (1 attribute from landuse_data_module)
Attribute Name Description
overland_n
type(management_schedule) (1 attribute from mgt_operations_module)
Attribute Name Description
sched
type(urban_db) (1 attribute from urban_data_module)
Attribute Name Description
urbdb
type(uptake_parameters) (1 attribute from hru_module)
Attribute Name Description
uptake
type(hydrologic_response_unit) (1 attribute from hru_module)
Attribute Name Description
hru
real (2 attributes from hru_module)
Attribute Name Description
cvm_com
rsdco_plcom
type(soil_profile_mass) (1 attribute from organic_mineral_mass_module)
Attribute Name Description
soil1
type(plant_community_mass) (1 attribute from organic_mineral_mass_module)
Attribute Name Description
pl_mass
type(organic_mass) (1 attribute from organic_mineral_mass_module)
Attribute Name Description
plt_mass_z
type(plant_community) (1 attribute from plant_module)
Attribute Name Description
pcom
type(weather_generator_db) (1 attribute from climate_module)
Attribute Name Description
wgn
type(wgn_parms) (1 attribute from climate_module)
Attribute Name Description
wgn_pms
type(weather_station) (1 attribute from climate_module)
Attribute Name Description
wst
Uses
plant_data_module
conditional_module
soil_module
time_module
hydrograph_module
landuse_data_module
maximum_data_module
mgt_operations_module
urban_data_module
hru_module
organic_mineral_mass_module
plant_module
climate_module
I/O
n/a
Local Variables
Type Visibility Attributes Name Initial
integer, public :: day_mo = 0
integer, public :: icom = 0
integer, public :: idp = 0
integer, public :: j = 0
integer, public :: iob = 0
integer, public :: iwgn = 0
integer, public :: mo = 0
integer, public :: iday = 0
integer, public :: icp = 0
integer, public :: ilum = 0
integer, public :: idb = 0
integer, public :: isched = 0
integer, public :: iop = 0
integer, public :: irot = 0
integer, public :: igrow = 0
integer, public :: iday_sum = 0
integer, public :: iday_sh = 0
integer, public :: jday_prev = 0
real, public :: phutot = 0.
real, public :: tave = 0.
real, public :: phuday = 0.
real, public :: xx = 0.
real, public :: xm = 0.
real, public :: sin_sl = 0.
real, public :: sl_len = 0.
real, public :: phu0 = 0.
real, public :: sd = 0.
real, public :: sdlat = 0.
real, public :: h = 0.
real, public :: daylength = 0.
real, public :: laimx_pop = 0.
real, public :: matur_frac = 0.
real, public :: f = 0.
real, public :: dd = 0.
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure. Use mouse wheel to zoom, drag to pan.
Reset Zoom Help
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
allocate plants (line 61)
  59 j = iihru
  62 icom = hru(j)%plant_cov
IF (icom == 0) THEN Lines 63-64
  64 pcom(j)%npl = 0
END IFLine 64
ELSE
allocate water uptake by layer (line 97)
  82 pcom(j)%npl = pcomdb(icom)%plants_com
  83 ipl = pcom(j)%npl
  84 allocate (pcom(j)%pl(ipl))
  85 allocate (pcom(j)%plg(ipl))
  86 allocate (pcom(j)%plm(ipl))
  87 allocate (pl_mass(j)%tot(ipl))
  88 allocate (pl_mass(j)%ab_gr(ipl))
  89 allocate (pl_mass(j)%leaf(ipl))
  90 allocate (pl_mass(j)%stem(ipl))
  91 allocate (pl_mass(j)%seed(ipl))
  92 allocate (pl_mass(j)%root(ipl))
  93 allocate (pl_mass(j)%yield_tot(ipl))
  94 allocate (pl_mass(j)%yield_yr(ipl))
  95 allocate (pcom(j)%plstr(ipl))
  96 allocate (pcom(j)%plcur(ipl))
 103 pcom(j)%rsd_covfac = 0.
 104 cvm_com(j) = 0.
 105 rsdco_plcom(j) = 0.
 106 pcom(j)%pcomdb = icom
 107 pcom(j)%rot_yr = 1
 108 pcom(j)%laimx_sum = 0.
 111 soil1(j)%rsd(1) = plt_mass_z
 112 soil1(j)%meta(1) = plt_mass_z
 113 soil1(j)%str(1) = plt_mass_z
 114 soil1(j)%lig(1) = plt_mass_z
IF (init > 0) THEN Lines 66-80
  67 deallocate (pcom(j)%pl)
  68 deallocate (pcom(j)%plg)
  69 deallocate (pcom(j)%plm)
  70 deallocate (pl_mass(j)%tot)
  71 deallocate (pl_mass(j)%ab_gr)
  72 deallocate (pl_mass(j)%leaf)
  73 deallocate (pl_mass(j)%stem)
  74 deallocate (pl_mass(j)%seed)
  75 deallocate (pl_mass(j)%root)
  76 deallocate (pl_mass(j)%yield_tot)
  77 deallocate (pl_mass(j)%yield_yr)
  78 deallocate (pcom(j)%plstr)
  79 deallocate (pcom(j)%plcur)
END IFLine 80
DO ipl = 1, pcom(j)%npl Lines 98-101
  99 allocate (pcom(j)%plcur(ipl)%uptake(soil(j)%nly), source = 0.)
 100 pcom(j)%plcur(ipl)%uptake = 0.
END DOLine 101
DO ipl = 1, pcom(j)%npl
initialize static and century fresh organic carbon pools (line 122)
initialize static and century fresh organic carbon pools (line 122)
set fraction to maturity and initial canopy height for annuals and perennials (line 305)
set fraction to maturity and initial canopy height for annuals and perennials (line 305)
set initial n and p contents in total plant (line 335)
initialize plant mass if plant growing (line 354)
initialize plant mass if plant growing (line 354)
get average residue cover factor for community (line 363)
get average residue cover factor for community (line 363)
set epco parameter for each crop (line 376)
set p factor and slope length (ls factor) (line 381)
xwalk urban land use type with urban name in urban.urb (line 390)
xwalk overland n with name in ovn_table.lum (line 399)
 117 pcom(j)%pl(ipl) = pcomdb(icom)%pl(ipl)%cpnm
 118 pcom(j)%plcur(ipl)%gro = pcomdb(icom)%pl(ipl)%igro
 119 pcom(j)%plcur(ipl)%idorm = "y"
 120 idp = pcomdb(icom)%pl(ipl)%db_num
 157 iob = hru(j)%obj_no
 158 iwst = ob(iob)%wst
 159 iwgn = wst(iwst)%wco%wgn
 160 phu0 = 0.
 166 iday_sh = 181
 254 phutot = 0.
 273 pcom(j)%plcur(ipl)%phumat = phutot
 277 isched = hru(j)%mgt_ops
 298 hru(j)%cur_op = sched(isched)%first_op
 300 pcom(j)%name = pcomdb(icom)%name
 302 pcom(j)%rot_yr = pcomdb(icom)%rot_yr_ini
 304 pcom(j)%plcur(ipl)%phuacc = pcomdb(icom)%pl(ipl)%phuacc
 316 pcom(j)%plg(ipl)%laimxfr = matur_frac / (matur_frac +     &
 317 Exp(plcp(idp)%leaf1 - plcp(idp)%leaf2 * matur_frac))
 323 pcom(j)%laimx_sum = pcom(j)%laimx_sum + pldb(idp)%blai
 324 pl_mass(j)%tot(ipl)%m = pcomdb(icom)%pl(ipl)%bioms
 325 pcom(j)%plcur(ipl)%curyr_mat = int (pcomdb(icom)%pl(ipl)%fr_yrmat * float(pldb(idp)%mat_yrs))
 326 pcom(j)%plcur(ipl)%curyr_mat = max (1, pcom(j)%plcur(ipl)%curyr_mat)
 328 pcom(j)%plcur(ipl)%phumat_p = pcom(j)%plcur(ipl)%phumat * pldb(idp)%mat_yrs
 330 cvm_com(j) = plcp(idp)%cvm + cvm_com(j)
 331 pcom(j)%rsd_covfac = pcom(j)%rsd_covfac + pldb(idp)%rsd_covfac
 332 rsdco_plcom(j) = rsdco_plcom(j) + pldb(idp)%rsdco_pl
 333 pcom(j)%plcur(ipl)%idplt = pcomdb(icom)%pl(ipl)%db_num
 336 pcom(j)%plm(ipl)%n_fr = (pldb(idp)%pltnfr1- pldb(idp)%pltnfr3) *              &
 337 (1.- matur_frac /(matur_frac + Exp(plcp(idp)%nup1 - plcp(idp)%nup2 *       &
 338 matur_frac))) + pldb(idp)%pltnfr3
 339 pl_mass(j)%tot(ipl)%n = pcom(j)%plm(ipl)%n_fr * pl_mass(j)%tot(ipl)%m
 340 pcom(j)%plm(ipl)%p_fr = (pldb(idp)%pltpfr1-pldb(idp)%pltpfr3)*                &
 341 (1. - matur_frac / (matur_frac + Exp(plcp(idp)%pup1 - plcp(idp)%pup2 *     &
 342 matur_frac))) + pldb(idp)%pltpfr3
 343 pl_mass(j)%tot(ipl)%p = pcom(j)%plm(ipl)%p_fr * pl_mass(j)%tot(ipl)%m
 351 pcom(j)%plcur(ipl)%harv_idx = pldb(idp)%hvsti
 352 pcom(j)%plcur(ipl)%lai_pot = laimx_pop
 361 end do   ! ipl loop
 372 end if   ! icom > 0
 374 ilum = hru(iihru)%land_use_mgt
 382 icp = lum_str(ilum)%cons_prac
 383 xm = .6 * (1. - Exp(-35.835 * hru(iihru)%topo%slope))
 384 sin_sl = Sin(Atan(hru(iihru)%topo%slope))
 385 sl_len = amin1 (hru(iihru)%topo%slope_len, cons_prac(icp)%sl_len_mx)
 386 hru(iihru)%lumv%usle_ls = (hru(iihru)%topo%slope_len / 22.128) ** xm *          &
 387 (65.41 * sin_sl * sin_sl + 4.56 * sin_sl + .065)
 388 hru(iihru)%lumv%usle_p = cons_prac(icp)%pfac
 391 hru(iihru)%luse%urb_ro = lum(ilum)%urb_ro
 407 return
IF (bsn_cc%cswat == 0) THEN Lines 123-128
 124 soil1(j)%rsd(1)%m = soil1(j)%rsd(1)%m + pcomdb(icom)%pl(ipl)%rsdin
 125 soil1(j)%rsd(1)%c = soil1(j)%rsd(1)%c + 0.42 * pcomdb(icom)%pl(ipl)%rsdin
 126 soil1(j)%rsd(1)%n = soil1(j)%rsd(1)%n + 0.42 * pcomdb(icom)%pl(ipl)%rsdin / 10.
 127 soil1(j)%rsd(1)%p = soil1(j)%rsd(1)%p + 0.42 * pcomdb(icom)%pl(ipl)%rsdin / 100.
END IFLine 128
IF (bsn_cc%cswat == 2) THEN Lines 130-153
metabolic residue (line 131)
structural residue (line 138)
lignin residue (line 145)
total residue pools (line 151)
 132 rsd_meta%m = 0.85 * pcomdb(icom)%pl(ipl)%rsdin
 133 rsd_meta%c = 0.357 * pcomdb(icom)%pl(ipl)%rsdin !0.357=0.42*0.85
 134 rsd_meta%n = rsd_meta%c / 10.           !assume 10:1 C:N ratio (EPIC)
 135 rsd_meta%p = rsd_meta%c / 100.
 136 soil1(j)%meta(1) = soil1(j)%meta(1) + rsd_meta
 139 rsd_str%m = 0.15 * pcomdb(icom)%pl(ipl)%rsdin
 140 rsd_str%c = 0.063 * pcomdb(icom)%pl(ipl)%rsdin   !0.063=0.42*0.15
 141 rsd_str%n = rsd_str%c / 150.             !assume 150:1 C:N ratio (EPIC)
 142 rsd_str%p = rsd_str%c / 1500.
 143 soil1(j)%str(1) = soil1(j)%str(1) + rsd_str
 146 soil1(j)%lig(1)%m = soil1(j)%lig(1)%m + 0.8 * rsd_str%m
 147 soil1(j)%lig(1)%c = soil1(j)%lig(1)%c + 0.8 * rsd_str%c              !assume 80% Structural C is lig
 148 soil1(j)%lig(1)%n = soil1(j)%lig(1)%n + 0.2 * rsd_str%n
 149 soil1(j)%lig(1)%p = soil1(j)%lig(1)%p + 0.02 * rsd_str%p
 152 soil1(j)%rsd(1) = soil1(j)%rsd(1) + rsd_meta + rsd_str
END IFLine 153
DO iday = 1, 365 Lines 161-165
 162 call xmon (iday, mo, day_mo)
 163 tave = (wgn(iwgn)%tmpmx(mo) + wgn(iwgn)%tmpmn(mo)) / 2.
 164 if (tave > 0.) phu0 = phu0 + tave
END DOLine 165
IF (pldb(idp)%days_mat < 1.e-6 .and. pldb(idp)%days_mat > -1.e-6) THEN Lines 169-180
 171 phutot = 0.
 180 pcom(j)%plcur(ipl)%phumat = .95 * phutot
DO iday = 1, 365 Lines 172-179
 173 call xmon (iday, mo, day_mo)
 174 tave = (wgn(iwgn)%tmpmx(mo) + wgn(iwgn)%tmpmn(mo)) / 2.
 175 phuday = tave - pldb(idp)%t_base
IF (phuday > 0.) THEN Lines 176-178
 177 phutot = phutot + phuday
END IFLine 178
END DOLine 179
END IFLine 180
ELSE IF (pldb(idp)%days_mat < 2.e-6) THEN Lines 181-183
 183 pcom(j)%plcur(ipl)%phumat = -pcom(j)%plcur(ipl)%phumat
END IF Line 183
ELSE Lines 184-219
 187 if (pldb(idp)%typ == "warm_annual" .or. pldb(idp)%typ == "warm_annual_tuber" .or.   &
 188 pldb(idp)%typ == "cold_annual" .or. pldb(idp)%typ == "cold_annual_tuber") then
 189 iday_sum = 181
 190 phutot = 0.
 191 phu0 = 0.15 * phu0    !assume planting at 0.15 base 0 heat units
DO iday = 1, 365 Lines 192-218
 205 tave = (wgn(iwgn)%tmpmx(mo) + wgn(iwgn)%tmpmn(mo)) / 2.
 206 phuday = tave
IF (wgn(iwgn)%lat > 0.) THEN Lines 193-194
 194 call xmon (iday, mo, day_mo)
END IFLine 194
ELSE Lines 195-204
 197 iday_sum = iday_sum + 1
 203 call xmon (iday_sh, mo, day_mo)
IF (iday_sum > 365) THEN Lines 198-199
 199 iday_sh = iday_sum - 365
END IFLine 199
ELSE Lines 200-202
 201 iday_sh = iday_sum
END IF Line 202
END IF Line 204
IF (phuday > 0.) THEN Lines 207-209
 208 phutot = phutot + phuday
END IFLine 209
IF (phutot > phu0) THEN Lines 210-217
 216 exit   ! exit on plant day at 0.15 base 0 heat units
IF (wgn(iwgn)%lat > 0.) THEN Lines 211-212
 212 igrow = iday
END IFLine 212
ELSE Lines 213-215
 214 igrow = iday_sh
END IF Line 215
END IFLine 217
END DOLine 218
END IF Line 219
IF (pldb(idp)%typ == "null" .or. pldb(idp)%typ == "null1") THEN Lines 222-251
 250 igrow = iday
IF (wgn(iwgn)%lat > 0.) THEN Lines 223-224
 224 igrow = 1
END IFLine 224
ELSE Lines 225-227
 226 igrow = 181
END IF Line 227
DO iday = igrow, igrow + 180 Lines 228-249
start accumulating hu at end of dormancy (daylength) (line 233)
calculate solar declination: equation 2.1.2 in SWAT manual (line 234)
calculate the relative distance of the earth from the sun the eccentricity of the orbit (line 236)
 229 call xmon (iday, mo, day_mo)
 230 tave = (wgn(iwgn)%tmpmx(mo) + wgn(iwgn)%tmpmn(mo)) / 2.
 231 phuday = tave - pldb(idp)%t_base
 235 sd = Asin(.4 * Sin((Real(iday) - 82.) / 58.09))  !!365/2pi = 58.09
 237 dd = 1.0 + 0.033 * Cos(Real(iday) / 58.09)
 238 sdlat = -wgn_pms(iwgn)%latsin * Tan(sd) / wgn_pms(iwgn)%latcos
 239 if (sdlat > 1.) then    !! sdlat will be >= 1. if latitude exceeds +/- 66.5 deg in winter
 240 h = 0.
 242 h = Acos(sdlat)
 244 h = 3.1416         !! latitude exceeds +/- 66.5 deg in summer
 246 daylength = 7.6394 * h
 247 if (daylength - wgn_pms(iwgn)%daylth >= wgn_pms(iwgn)%daylmn) exit
END DOLine 249
END IFLine 251
DO iday = igrow, igrow + pldb(idp)%days_mat Lines 255-272
 267 tave = (wgn(iwgn)%tmpmx(mo) + wgn(iwgn)%tmpmn(mo)) / 2.
 268 phuday = tave - pldb(idp)%t_base
IF (wgn(iwgn)%lat > 0.) THEN Lines 256-257
 257 call xmon (iday, mo, day_mo)
END IFLine 257
ELSE Lines 258-266
 265 call xmon (iday_sh, mo, day_mo)
IF (iday > 365) THEN Lines 260-261
 261 iday_sh = iday - 365
END IFLine 261
ELSE Lines 262-264
 263 iday_sh = iday
END IF Line 264
END IF Line 266
IF (phuday > 0.) THEN Lines 269-271
 270 phutot = phutot + phuday
END IFLine 271
END DOLine 272
IF (sched(isched)%num_ops > 0) THEN Lines 278-297
IF (sched(isched)%mgt_ops(1)%jday > 0) THEN Lines 279-293
 280 irot = 1
 281 jday_prev = sched(isched)%mgt_ops(1)%jday
 292 sched(isched)%first_op = min (iop-1, sched(isched)%num_ops)
 293 sched(isched)%first_op = max (1, sched(isched)%first_op)
DO iop = 1, sched(isched)%num_ops Lines 282-291
 290 jday_prev = sched(isched)%mgt_ops(iop)%jday
IF (irot == pcomdb(icom)%rot_yr_ini .and. time%day_start <= sched(isched)%mgt_ops(iop)%jday) THEN Lines 283-284
 284 exit
END IFLine 284
ELSE Lines 285-289
IF (sched(isched)%mgt_ops(iop)%op == "skip" .or. sched(isched)%mgt_ops(iop)%jday < jday_prev) THEN Lines 286-288
 287 irot = irot + 1
END IFLine 288
END IF Line 289
END DOLine 291
END IFLine 293
ELSE Lines 294-296
 295 sched(isched)%first_op = 1
END IF Line 296
END IFLine 297
IF (pldb(idp)%typ == "perennial") THEN Lines 306-314
 307 matur_frac = pcomdb(icom)%pl(ipl)%fr_yrmat
 308 pcom(j)%plg(ipl)%cht = matur_frac * pldb(idp)%chtmx
 309 else  !annuals
 310 matur_frac = pcomdb(icom)%pl(ipl)%phuacc
 311 f = pcom(j)%plcur(ipl)%phuacc / (pcom(j)%plcur(ipl)%phuacc +     &
 312 Exp(plcp(idp)%leaf1 - plcp(idp)%leaf2 * pcom(j)%plcur(ipl)%phuacc))
 313 pcom(j)%plg(ipl)%cht = pldb(idp)%chtmx * Sqrt(f)
END IFLine 314
IF (pcomdb(icom)%pl(ipl)%igro == "y") THEN Lines 318-319
 319 pcom(j)%plg(ipl)%lai = pcomdb(icom)%pl(ipl)%lai
END IFLine 319
ELSE Lines 320-322
 321 pcom(j)%plg(ipl)%lai = 0.
END IF Line 322
IF (pcom(j)%plcur(ipl)%pop_com < 1.e-6) THEN Lines 345-346
 346 laimx_pop = pldb(idp)%blai
END IFLine 346
ELSE Lines 347-350
 348 xx = pcom(j)%plcur(ipl)%pop_com / 1001.
 349 laimx_pop = pldb(idp)%blai * xx / (xx + exp(pldb(idp)%pop1 - pldb(idp)%pop2 * xx))
END IF Line 350
IF (pcom(j)%plcur(ipl)%gro == "y") THEN Lines 355-359
 356 call pl_root_gro(j)
 357 call pl_seed_gro(j)
 358 call pl_partition(j, 1)
END IFLine 359
IF (pcom(j)%npl > 0) THEN Lines 364-366
 365 pcom(j)%rsd_covfac = pcom(j)%rsd_covfac / pcom(j)%npl
 366 cvm_com(j) = cvm_com(j) / pcom(j)%npl
END IFLine 366
ELSE Lines 367-370
 368 pcom(j)%rsd_covfac = 0.
 369 cvm_com(j) = 0.
END IF Line 370
DO ipl = 1, pcom(iihru)%npl Lines 377-379
 378 pcom(iihru)%plcur(ipl)%epco = hru(iihru)%hyd%epco
END DOLine 379
DO idb = 1, db_mx%urban Lines 392-397
IF (lum(ilum)%urb_lu == urbdb(idb)%urbnm) THEN Lines 393-396
 394 hru(iihru)%luse%urb_lu = idb
 395 exit
END IFLine 396
END DOLine 397
DO idb = 1, db_mx%ovn Lines 400-405
IF (lum(ilum)%ovn == overland_n(idb)%name) THEN Lines 401-404
 402 hru(iihru)%luse%ovn = overland_n(idb)%ovn
 403 exit
END IFLine 404
END DOLine 405
END DO
END IF
Allocations
Memory allocations and deallocations grouped by variable.
Variable Allocations Deallocations
pcom line 84, line 85, line 86, line 95, line 96, line 99 line 67, line 68, line 69, line 78, line 79
pl_mass line 87, line 88, line 89, line 90, line 91, line 92, line 93, line 94 line 70, line 71, line 72, line 73, line 74, line 75, line 76, line 77
Calls
Procedures Called
List of procedures called by this Subroutine.
xmon
float
pl_root_gro
pl_seed_gro
pl_partition
amin1
Call Graph
Visual representation of procedures called by this Subroutine.
Variables
Type Visibility Attributes Name Initial
integer, public :: init
integer, public :: iihru
Call graph
plant_init calls amin1, float, pl_partition, pl_root_gro, pl_seed_gro, xmon