proc_cal – test-src-project
proc_cal Subroutine
21 statements
Source File
subroutine proc_cal()
Uses
calibration_data_module
hydrograph_module
Arguments
n/a
I/O
n/a
Outside Variables and Types
character(len=1) (2 attributes from calibration_data_module)
Attribute Name Description
cal_soft
if y, calibrate at least one balance
cal_hard
if y, perform hard calibration
!! Bang Comments
need to read plant parms before calibrating read soft calibration parameters
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure.
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
   9 call cal_parm_read
  10 call cal_parmchg_read
  13 call pl_read_regions_cal      !soft data for plant parms (lai_pot and harv_idx) calibration
  14 call pl_read_parms_cal
  15 call cal_conditions
  18 call calsoft_read_codes
  21 call lcu_read_softcal         !soft data for landscape calibration (needs to be renamed)***
  22 call ls_read_lsparms_cal
  23 call aqu_read_elements        !defining regions by aquifer
  24 call ch_read_elements         !defining regions by channel
  25 call res_read_elements        !defining regions by reservoir
  26 call rec_read_elements        !defining regions by recall object (point source, gage data, model output, etc)
  27 call ch_read_orders_cal
  28 call ch_read_parms_cal
  30 if (cal_soft == "y" .or. cal_hard == "y") call cal_allo_init
  32 return
Allocations
n/a
Calls
Calls
Procedures called by this subroutine.
Call graph
proc_cal calls aqu_read_elements, cal_allo_init, cal_conditions, cal_parm_read, cal_parmchg_read, calsoft_read_codes, ch_read_elements, ch_read_orders_cal, ch_read_parms_cal, lcu_read_softcal, ls_read_lsparms_cal, pl_read_parms_cal, pl_read_regions_cal, rec_read_elements, res_read_elements