proc_cha – TestDataProject
proc_cha Subroutine
29 statements
Source File
subroutine proc_cha()
Called From
n/a
Arguments
n/a
Outside Variables and Types
integer (1 attribute from hydrograph_module)
Attribute Name Description
ich
none |object number
Read more…
type(object_connectivity) (1 attribute from hydrograph_module)
Attribute Name Description
ob
type (2 attributes from hydrograph_module)
Attribute Name Description
sp_ob%chan None
sp_ob1%chan None
Uses
hydrograph_module
I/O
n/a
Local Variables
Type Visibility Attributes Name Initial
integer, public :: irch = 0
integer, public :: idat = 0
integer, public :: i = 0
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure. Use mouse wheel to zoom, drag to pan.
Reset Zoom Help
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
initialize stream-aquifer interactions for geomorphic baseflow (line 24)
aquifer to channel flow (line 25)
  11 call ch_read_init
  12 call ch_read_init_cs
  14 call sd_hydsed_read
  15 call ch_read_hyd
  16 call ch_read_sed
  17 call ch_read_nut
  18 call ch_read
  19 call sd_channel_read
  20 call sd_hydsed_init
  26 call aqu2d_init
DO ich = 1, sp_ob%chan Lines 28-31
initialize flow routing variables (line 29)
  30 call ch_ttcoef (ich)
END DOLine 31
DO irch = 1, sp_ob%chan Lines 33-37
  34 i = sp_ob1%chan + irch - 1
  35 idat = ob(i)%props
  36 call ch_initial (idat, irch)
END DOLine 37
  40 call overbank_read
  41 call sd_channel_surf_link
  43 call time_conc_init
  45 return
Allocations
n/a
Calls
Procedures Called
List of procedures called by this Subroutine.
ch_read_init
ch_read_init_cs
sd_hydsed_read
ch_read_hyd
ch_read_sed
ch_read_nut
ch_read
sd_channel_read
sd_hydsed_init
aqu2d_init
ch_ttcoef
ch_initial
overbank_read
sd_channel_surf_link
time_conc_init
Call Graph
Visual representation of procedures called by this Subroutine.
Call graph
proc_cha calls aqu2d_init, ch_initial, ch_read, ch_read_hyd, ch_read_init, ch_read_init_cs, ch_read_nut, ch_read_sed, ch_ttcoef, overbank_read, sd_channel_read, sd_channel_surf_link, sd_hydsed_init, sd_hydsed_read, time_conc_init