proc_hru – TestDataProject
proc_hru Subroutine
52 statements
Source File
subroutine proc_hru()
Called From
n/a
Arguments
n/a
Outside Variables and Types
type(erosion_output) (1 attribute from erosion_module)
Attribute Name Description
ero_output
dimensioned by hru
type(erosion_output_header) (1 attribute from erosion_module)
Attribute Name Description
ero_hdr
type(erosion_header_units) (1 attribute from erosion_module)
Attribute Name Description
ero_hdr_units
type(soil_profile) (1 attribute from soil_module)
Attribute Name Description
soil
type (5 attributes from constituent_mass_module)
Attribute Name Description
cs_db%num_paths None
cs_db%num_cs None
cs_db%num_pests None
cs_db%num_salts None
sp_ob%hru None
type(output_checker_header) (1 attribute from hydrograph_module)
Attribute Name Description
chk_hdr
type(output_checker_unit) (1 attribute from hydrograph_module)
Attribute Name Description
chk_unit
type(land_use_management) (1 attribute from landuse_data_module)
Attribute Name Description
lum
type(land_use_structures) (1 attribute from landuse_data_module)
Attribute Name Description
lum_str
type(hydrologic_response_unit) (1 attribute from hru_module)
Attribute Name Description
hru
Uses
erosion_module
soil_module
constituent_mass_module
hydrograph_module
landuse_data_module
maximum_data_module
hru_module
I/O
I/O units used in this subroutine.
Unit Type Filename
erosion.out",recl=1200 Unknown not specified
checker.out",recl=1200 Unknown not specified
unit_9000 Output not specified
Local Variables
Type Visibility Attributes Name Initial
integer, public :: j = 0
integer, public :: ilum = 0
set the object number for each hru-to point to weather station
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure. Use mouse wheel to zoom, drag to pan.
Reset Zoom Help
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
IF (sp_ob%hru > 0) THEN Lines 17-65
septic has to be set before soils are initialized (making a soil layer for the septic zone) (line 26)
allocate erosion output and open file (line 44)
!!! new checker.out file - always prints (line 51)
  18 call hru_allo
  19 call hru_read
  20 call hrudb_init
  21 call hru_lum_init_all
  22 call topohyd_init
  23 call hru_output_allo
  24 call carbon_read
  34 call soils_init
  35 call structure_init
  36 call plant_all_init
  37 call cn2_init_all
  38 call hydro_init
  39 if (cs_db%num_pests > 0) call pesticide_init
  40 if (cs_db%num_paths > 0) call pathogen_init
  41 if (cs_db%num_salts > 0) call salt_hru_init !rtb salt
  42 if (cs_db%num_cs > 0) call cs_hru_init !rtb cs
  45 allocate (ero_output(sp_ob%hru))
  46 open (4001,file = "erosion.out",recl=1200)
  47 write (4001,*) bsn%name, prog
  48 write (4001,*) ero_hdr
  49 write (4001,*) ero_hdr_units
  52 open (4000,file = "checker.out",recl=1200)
  53 write (4000,*) bsn%name, prog
  54 write (4000,*) chk_hdr
  55 write (4000,*) chk_unit
  56 write (9000,*) "CHK                       checker.out"
DO j = 1, sp_ob%hru Lines 27-32
  28 ilum = hru(j)%land_use_mgt
IF (lum(ilum)%septic /= "null") THEN Lines 29-31
  30 call structure_set_parms("septic          ", lum_str(ilum)%septic, j)
END IFLine 31
END DOLine 32
DO j = 1, sp_ob%hru Lines 58-62
  59 write (4000,100) soil(j)%snam, soil(j)%hydgrp, soil(j)%zmx, soil(j)%usle_k, soil(j)%sumfc,  &
  60 soil(j)%sumul, hru(j)%lumv%usle_p, hru(j)%lumv%usle_ls, hru(j)%hyd%esco, hru(j)%hyd%epco,      &
  61 hru(j)%hyd%cn3_swf, hru(j)%hyd%perco, hru(j)%hyd%latq_co, hru(j)%tiledrain
END DOLine 62
END IFLine 65
!!! new checker.out file - always prints (line 63)
  67 call rte_read_nut
  69 100   format(2a16,11f12.4,i12)
  71 return
Allocations
Memory allocations and deallocations grouped by variable.
Variable Allocations Deallocations
ero_output line 45 none
Calls
Procedures Called
List of procedures called by this Subroutine.
hru_allo
hru_read
hrudb_init
hru_lum_init_all
topohyd_init
hru_output_allo
carbon_read
structure_set_parms
soils_init
structure_init
plant_all_init
cn2_init_all
hydro_init
pesticide_init
pathogen_init
salt_hru_init
cs_hru_init
rte_read_nut
Call Graph
Visual representation of procedures called by this Subroutine.
Call graph
proc_hru calls carbon_read, cn2_init_all, cs_hru_init, hru_allo, hru_lum_init_all, hru_output_allo, hru_read, hrudb_init, hydro_init, pathogen_init, pesticide_init, plant_all_init, rte_read_nut, salt_hru_init, soils_init, structure_init, structure_set_parms, topohyd_init