proc_bsn – TestDataProject
proc_bsn Subroutine
20 statements
Source File
subroutine proc_bsn()
Called From
n/a
Arguments
n/a
Outside Variables and Types
type (2 attributes from time_module)
Attribute Name Description
time%dtm None
time%step None
Uses
time_module
I/O
I/O units used in this subroutine.
Unit Type Filename
files_out.out Unknown not specified
diagnostics.out", recl=8000 Unknown not specified
area_calc.out", recl=8000 Unknown not specified
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure. Use mouse wheel to zoom, drag to pan.
Reset Zoom Help
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
! open file to print all output files that are written (line 7)
! open diagnostics.out file to print problems with various files (line 10)
! open drainage areas output file (line 13)
   8 open (9000,file="files_out.out")
   9 write (9000,*) "files_out.out - OUTPUT FILES WRITTEN"
  11 open (9001,file="diagnostics.out", recl=8000)  !!ext to 8000 recl per email 8/2/21 - Kai-Uwe
  12 write (9001,*) "DIAGNOSTICS.OUT FILE"
  14 open (9004,file="area_calc.out", recl=8000)
  16 call basin_read_cc
  17 call basin_read_objs
  18 call time_read
  21 time%dtm = 1440. / time%step
  24 call readcio_read
  26 call basin_read_prm
  27 call basin_prm_default
  28 call basin_print_codes_read
  29 call co2_read
  30 call carbon_coef_read
  32 return
Allocations
n/a
Calls
Procedures Called
List of procedures called by this Subroutine.
basin_read_cc
basin_read_objs
time_read
readcio_read
basin_read_prm
basin_prm_default
basin_print_codes_read
co2_read
carbon_coef_read
Call Graph
Visual representation of procedures called by this Subroutine.
Call graph
proc_bsn calls basin_print_codes_read, basin_prm_default, basin_read_cc, basin_read_objs, basin_read_prm, carbon_coef_read, co2_read, readcio_read, time_read