proc_date_time – TestDataProject
proc_date_time Subroutine
42 statements
Source File
subroutine proc_date_time()
Called From
n/a
Arguments
n/a
Outside Variables and Types
type(time_current) (1 attribute from time_module)
Attribute Name Description
time
Uses
time_module
I/O
I/O units used in this subroutine.
Unit Type Filename
unit_* Output not specified
unit_9003 Output not specified
Local Variables
Type Visibility Attributes Name Initial
integer, public :: date_time(8) = 0
character(len=10), public :: b(3)
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure. Use mouse wheel to zoom, drag to pan.
Reset Zoom Help
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
  12 call DATE_AND_TIME (b(1), b(2), b(3), date_time)
  13 write (*,1234) date_time(2), date_time(3), date_time(1), date_time(5), date_time(6), date_time(7)
  14 write (9003,1234) date_time(2), date_time(3), date_time(1), date_time(5), date_time(6), date_time(7)
  15 1234  format(/,"  Date of Sim", 2x,i2,"/",i2,"/",i4, " Time",2x,i2,":",i2,":",i2)
  17 write (*,111) "reading from pet file              ", date_time(5), date_time(6), date_time(7)
  18 write (9003,111) "reading from pet file              ", date_time(5), date_time(6), date_time(7)
  19 call DATE_AND_TIME (b(1), b(2), b(3), date_time)
  20 call cli_petmeas
  22 write (*,111) "reading from precipitation file    ", date_time(5), date_time(6), date_time(7)
  23 write (9003,111) "reading from precipitation file    ", date_time(5), date_time(6), date_time(7)
  24 call cli_pmeas
  25 write (*,111) "reading from temperature file      ", date_time(5), date_time(6), date_time(7)
  26 write (9003,111) "reading from temperature file      ", date_time(5), date_time(6), date_time(7)
  27 call DATE_AND_TIME (b(1), b(2), b(3), date_time)
  28 call cli_tmeas
  29 write (*,111) "reading from solar radiation file  ", date_time(5), date_time(6), date_time(7)
  30 write (9003,111) "reading from solar radiation file  ", date_time(5), date_time(6), date_time(7)
  31 call DATE_AND_TIME (b(1), b(2), b(3), date_time)
  32 call cli_smeas
  33 write (*,111) "reading from relative humidity file", date_time(5), date_time(6), date_time(7)
  34 write (9003,111) "reading from relative humidity file", date_time(5), date_time(6), date_time(7)
  35 call DATE_AND_TIME (b(1), b(2), b(3), date_time)
  36 call cli_hmeas
  37 write (*,111) "reading from wind file             ", date_time(5), date_time(6), date_time(7)
  38 write (9003,111) "reading from wind file             ", date_time(5), date_time(6), date_time(7)
  39 call DATE_AND_TIME (b(1), b(2), b(3), date_time)
  40 call cli_wmeas
  41 write (*,111) "reading from wgn file              ", date_time(5), date_time(6), date_time(7)
  42 write (9003,111) "reading from wgn file              ", date_time(5), date_time(6), date_time(7)
  43 call DATE_AND_TIME (b(1), b(2), b(3), date_time)
  44 call cli_wgnread
  45 write (*,111) "reading from wx station file       ", date_time(5), date_time(6), date_time(7)
  46 write (9003,111) "reading from wx station file       ", date_time(5), date_time(6), date_time(7)
  47 call DATE_AND_TIME (b(1), b(2), b(3), date_time)
  49 111   format (1x,a, 5x,"Time",2x,i2,":",i2,":",i2)
  51 return
Allocations
n/a
Calls
Procedures Called
List of procedures called by this Subroutine.
cli_petmeas
cli_pmeas
cli_tmeas
cli_smeas
cli_hmeas
cli_wmeas
cli_wgnread
Call Graph
Visual representation of procedures called by this Subroutine.
Call graph
proc_date_time calls cli_hmeas, cli_petmeas, cli_pmeas, cli_smeas, cli_tmeas, cli_wgnread, cli_wmeas