proc_db – test-src-project
proc_db Subroutine
33 statements
Source File
subroutine proc_db()
Arguments
n/a
I/O
n/a
Outside Variables and Types
n/a
!! Bang Comments
databases used by all spatial modules read the plant parameter database initialize plant parameters read plant transplant data read the tillage database read the pesticide database read the fertilizer/nutrient database read the manure database - includes pathogens/antibiotics read the urban land types database read the pathogen data parameters read management scheduling and data files
read structural operations files read the plant community database
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure.
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
   6 call plant_parm_read                          !! read the plant parameter database
   7 call plantparm_init                           !! initialize plant parameters
   8 call plant_transplant_read                    !! read plant transplant data
   9 call till_parm_read                           !! read the tillage database
  10 call pest_parm_read                           !! read the pesticide database
  11 call fert_parm_read                           !! read the fertilizer/nutrient database
  12 call manure_parm_read                         !! read the manure database - includes pathogens/antibiotics
  13 call urban_parm_read                          !! read the urban land types database
  14 call path_parm_read                           !! read the pathogen data parameters
  15 call septic_parm_read
  18 call mgt_read_irrops
  19 call mgt_read_chemapp
  20 call mgt_read_harvops
  21 call mgt_read_grazeops
  22 call mgt_read_sweepops
  23 call mgt_read_fireops
  24 call mgt_read_mgtops
  25 call mgt_read_puddle
  28 call sdr_read
  29 call sep_read
  30 call scen_read_grwway
  31 call scen_read_filtstrip
  32 call scen_read_bmpuser
  33 call sat_buff_read
  36 call readpcom
  38 call cntbl_read
  39 call cons_prac_read
  40 call overland_n_read
  41 call landuse_read
  43 return
Allocations
n/a
Calls
Calls
Procedures called by this subroutine.
Call graph
proc_db calls cntbl_read, cons_prac_read, fert_parm_read, landuse_read, manure_parm_read, mgt_read_chemapp, mgt_read_fireops, mgt_read_grazeops, mgt_read_harvops, mgt_read_irrops, mgt_read_mgtops, mgt_read_puddle, mgt_read_sweepops, overland_n_read, path_parm_read, pest_parm_read, plant_parm_read, plant_transplant_read, plantparm_init, readpcom, sat_buff_read, scen_read_bmpuser, scen_read_filtstrip, scen_read_grwway, sdr_read, sep_read, septic_parm_read, till_parm_read, urban_parm_read