res_control – TestDataProject
res_control Subroutine
125 statements
Source File
subroutine res_control(jres)
Called From
n/a
Arguments
Type Intent Optional Attributes Name
integer :: jres
Outside Variables and Types
type (17 attributes from basin_module)
Attribute Name Description
bsn_cc%gwflow None
bsn_cc%lapse None
pco%nyskip None
time%yrs None
time%yrc None
time%step None
time%mo None
cs_db%num_salts None
cs_db%num_cs None
cs_db%num_pests None
cs_db%num_tot None
hcs2%pest None
hcs2%salt None
hcs2%cs None
ht1%flo None
ht2%flo None
wbody%flo None
type(reservoir_data) (1 attribute from reservoir_data_module)
Attribute Name Description
res_dat
type(reservoir_hyd_data) (1 attribute from reservoir_data_module)
Attribute Name Description
res_hyd
type(water_body_data_parameters) (2 attributes from reservoir_data_module)
Attribute Name Description
res_prm
wbody_prm
used for reservoir and wetlands
type(decision_table) (2 attributes from conditional_module)
Attribute Name Description
dtbl_res
d_tbl
type(constituent_mass) (1 attribute from constituent_mass_module)
Attribute Name Description
hin_csz
type(all_constituent_hydrograph) (1 attribute from constituent_mass_module)
Attribute Name Description
obcs
integer (2 attributes from hydrograph_module)
Attribute Name Description
iwst
|
icmd
|
type(hyd_output) (5 attributes from hydrograph_module)
Attribute Name Description
hd
res
resz
res_in_d
res_out_d
type(timestep) (1 attribute from hydrograph_module)
Attribute Name Description
ts
type(object_connectivity) (1 attribute from hydrograph_module)
Attribute Name Description
ob
type(reservoir) (1 attribute from reservoir_module)
Attribute Name Description
res_ob
type(water_body) (2 attributes from water_body_module)
Attribute Name Description
res_wat_d
wbody_wb
used for reservoir and wetlands
type(weather_daily) (1 attribute from climate_module)
Attribute Name Description
w
type(weather_station) (1 attribute from climate_module)
Attribute Name Description
wst
Uses
basin_module
reservoir_data_module
conditional_module
time_module
constituent_mass_module
hydrograph_module
reservoir_module
water_body_module
climate_module
I/O
n/a
Local Variables
Type Visibility Attributes Name Initial
integer, public :: ii = 0
integer, public :: idat = 0
integer, public :: irel = 0
integer, public :: iob = 0
integer, public :: ictbl = 0
integer, public :: icon = 0
nbs
real, public :: pvol_m3 = 0.
real, public :: evol_m3 = 0.
real, public :: dep = 0.
real, public :: weir_hgt = 0.
real, public :: alpha_up = 0.
real, public :: alpha_down = 0.
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure. Use mouse wheel to zoom, drag to pan.
Reset Zoom Help
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
adjust precip and temperature for elevation using lapse rates (line 38)
set water body pointer to res (line 43)
add incoming flow to reservoir (line 48)
perform reservoir water/sediment balance (line 51)
  29 ht1 = ob(icmd)%hin    !! set incoming flow
  30 ht2 = resz            !! zero outgoing flow, sediment and nutrients
  31 hcs2 = hin_csz        !! zero outgoing constituents
  33 if (time%yrc > res_hyd(jres)%iyres .or. (time%mo >= res_hyd(jres)%mores   &
  34 .and. time%yrc == res_hyd(jres)%iyres)) then
  35 iob = res_ob(jres)%ob
  36 iwst = ob(iob)%wst
  39 w = wst(iwst)%weat
  40 if (bsn_cc%lapse == 1) call cli_lapse
  41 wst(iwst)%weat = w
  44 wbody => res(jres)
  45 wbody_wb => res_wat_d(jres)
  46 wbody_prm => res_prm(jres)
  49 res(jres) = res(jres) + ht1
  52 idat = res_ob(jres)%props
IF (res_ob(jres)%rel_tbl == "d") THEN Lines 53-79
determine reservoir outflow (line 54)
new lag to smooth condition jumps (volume or month conditions) (line 68)
lag outflow when flows are receding (line 71)
lag outflow when flows are receding (line 71)
  55 irel = res_dat(idat)%release
  56 d_tbl => dtbl_res(irel)
  57 pvol_m3 = 0.5 * res_ob(jres)%pvol
  58 evol_m3 = 0.5 * res_ob(jres)%evol
  64 weir_hgt = res_ob(jres)%weir_hgt
  65 call conditions (jres, irel)
  66 call res_hydro (jres, irel, pvol_m3, evol_m3)
  69 alpha_up = Exp(-res_ob(jres)%lag_up)
  70 alpha_down = Exp(-res_ob(jres)%lag_down)
  77 res_ob(jres)%prev_flo = ht2%flo
  79 call res_sediment
IF (res_wat_d(jres)%area_ha > 1.e-6) THEN Lines 59-60
  60 dep = wbody%flo / res_wat_d(jres)%area_ha / 10000.     !m = m3 / ha / 10000m2/ha
END IFLine 60
ELSE Lines 61-63
  62 dep = 0.
END IF Line 63
IF (res_ob(jres)%prev_flo < ht2%flo) THEN Lines 72-73
  73 ht2%flo = ht2%flo * alpha_up + res_ob(jres)%prev_flo * (1. - alpha_up)
END IFLine 73
ELSE Lines 74-76
  75 ht2%flo = ht2%flo * alpha_down + res_ob(jres)%prev_flo * (1. - alpha_down)
END IF Line 76
END IFLine 79
ELSE Lines 80-84
  81 ictbl = res_dat(idat)%release                              !! Osvaldo
  82 call res_rel_conds (ictbl, res(jres)%flo, ht1%flo, 0.)
END IF Line 84
calculate water balance for day (line 86)
add precip to reservoir storage (line 93)
subtract outflow from reservoir storage (line 96)
  87 res_wat_d(jres)%evap = 10. * res_hyd(jres)%evrsv * wst(iwst)%weat%pet * res_wat_d(jres)%area_ha
  88 res_wat_d(jres)%precip = 10. * wst(iwst)%weat%precip * res_wat_d(jres)%area_ha
  89 if(bsn_cc%gwflow == 0) then !if gwflow active, seepage calculated in gwflow_simulate (rtb gwflow)
  90 res_wat_d(jres)%seep = 240. * res_hyd(jres)%k * res_wat_d(jres)%area_ha
  94 res(jres)%flo = res(jres)%flo + res_wat_d(jres)%precip
  97 res(jres)%flo = res(jres)%flo - ht2%flo
IF (res(jres)%flo < 0.) THEN Lines 98-101
  99 ht2%flo = ht2%flo + res(jres)%flo
 100 res(jres)%flo = 0.
END IFLine 101
subtract evaporation from reservoir storage (line 103)
 104 res(jres)%flo = res(jres)%flo - res_wat_d(jres)%evap
IF (res(jres)%flo < 0.) THEN Lines 105-108
 106 res_wat_d(jres)%evap = res_wat_d(jres)%evap + res(jres)%flo
 107 res(jres)%flo = 0.
END IFLine 108
subtract seepage from reservoir storage (line 110)
 111 res(jres)%flo = res(jres)%flo - res_wat_d(jres)%seep
IF (res(jres)%flo < 0.) THEN Lines 112-115
 113 res_wat_d(jres)%seep = res_wat_d(jres)%seep + res(jres)%flo
 114 res(jres)%flo = 0.
END IFLine 115
IF (res(jres)%flo > 0.) THEN Lines 118-119
 119 res_wat_d(jres)%area_ha = res_ob(jres)%br1 * res(jres)%flo ** res_ob(jres)%br2
END IFLine 119
ELSE Lines 120-122
 121 res_wat_d(jres)%area_ha = 0.
END IF Line 122
subtract sediment leaving from reservoir (line 124)
perform reservoir nutrient balance (line 129)
perform reservoir pesticide transformations (line 132)
 130 call res_nutrient (iob)
IF (cs_db%num_pests > 0) THEN Lines 133-136
 134 call res_pest (jres)
 135 obcs(icmd)%hd(1)%pest = hcs2%pest
END IFLine 136
IF (cs_db%num_salts > 0) THEN Lines 139-142
 140 call res_salt(jres)
 141 obcs(icmd)%hd(1)%salt = hcs2%salt
END IFLine 142
IF (cs_db%num_cs > 0) THEN Lines 145-149
 146 icon = res_dat(idat)%cs
 147 call res_cs(jres, icon, iob)
 148 obcs(icmd)%hd(1)%cs = hcs2%cs
END IFLine 149
set values for outflow variables (line 151)
 152 ob(icmd)%hd(1) = ht2
IF (cs_db%num_tot > 0) THEN Lines 153-155
 154 obcs(icmd)%hd(1) = hcs2
END IFLine 155
total incoming to output to SWIFT (line 157)
total outgoing to output to SWIFT (line 159)
 158 ob(icmd)%hin_tot = ob(icmd)%hin_tot + ob(icmd)%hin
 160 ob(icmd)%hout_tot = ob(icmd)%hout_tot + ht2
IF (time%step > 1) THEN Lines 162-166
DO ii = 1, time%step Lines 163-165
 164 ob(icmd)%ts(1,ii) = ht2 / real(time%step)
END DOLine 165
END IFLine 166
IF (time%yrs > pco%nyskip) THEN Lines 169-177
 170 res_in_d(jres) = ht1
 171 res_out_d(jres) = ht2
END IFLine 177
reservoir has not been constructed yet (line 180)
 181 ob(icmd)%hd(1) = ob(icmd)%hin
 182 if (cs_db%num_tot > 0) obcs(icmd)%hd(1) = obcs(icmd)%hin(1)
 187 return
Allocations
n/a
Calls
Procedures Called
List of procedures called by this Subroutine.
cli_lapse
conditions
res_hydro
res_sediment
res_rel_conds
res_nutrient
res_pest
res_salt
res_cs
Call Graph
Visual representation of procedures called by this Subroutine.
Variables
Type Visibility Attributes Name Initial
integer, public :: jres
Call graph
res_control calls cli_lapse, conditions, res_cs, res_hydro, res_nutrient, res_pest, res_rel_conds, res_salt, res_sediment