salt_chem_soil_single – test-src-project
salt_chem_soil_single Subroutine
148 statements
Source File
subroutine salt_chem_soil_single(hru_num, lay_num, waterC)
Uses
salt_module
hru_module
basin_module
soil_module
salt_data_module
constituent_mass_module
time_module
Arguments
Type Intent Optional Attributes Name
integer :: hru_num
integer :: lay_num
real :: waterC
I/O
n/a
Outside Variables and Types
type(hydrologic_response_unit) (1 attribute from hru_module)
Attribute Name Description
hru
integer (6 attributes from hru_module)
Attribute Name Description
ihru
none |HRU number
Read more…
c11
c22
salt_c3
salt_c4
c5
type(soil_profile) (1 attribute from soil_module)
Attribute Name Description
soil
double precision (32 attributes from salt_data_module)
Attribute Name Description
Sul_Conc(2000)
Cal_Conc(2000)
Mg_Conc(2000)
Sod_Conc(2000)
Pot_Conc(2000)
Cl_Conc(2000)
Car_Conc(2000)
BiCar_Conc(2000)
salt_K1
salt_K2
salt_K3
salt_K4
salt_K5
Ksp11
Ksp21
Ksp31
Ksp41
Ksp51
upion1
upion2
upion3
upion4
upion5
upion6
upion7
upion8
Sol_CaCO3(1000)
Sol_MgCO3(1000)
Sol_CaSO4(1000)
Sol_MgSO4(1000)
Sol_NaCl(1000)
LAMDA(7)
real (1 attribute from salt_data_module)
Attribute Name Description
soil_salt_conc(8)
generic array to hold salt ion concentrations
type(soil_constituent_mass) (1 attribute from constituent_mass_module)
Attribute Name Description
cs_soil
!! Bang Comments
~ ~ ~ PURPOSE ~ ~ ~
this subroutine calculates salt ion concentrations based on equilibrium chemical reactions
(precipitation-dissolution, complexation, cation exchange), for a specified HRU, for a specified layer
*** End Precipitation-Dissolution Package *****
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure.
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
  47 K_ADJ1,K_ADJ2,K_ADJ3,K_ADJ4,K_ADJ5,&
  48 error1ST,error2ND,error3RD,errorTotal
  52 j = hru_num
  55 jj = lay_num
  58 Sol_CaCO3_p(1) = cs_soil(j)%ly(jj)%salt_min(1)
  59 Sol_MgCO3_p(1) = cs_soil(j)%ly(jj)%salt_min(2)
  60 Sol_CaSO4_p(1) = cs_soil(j)%ly(jj)%salt_min(3)
  61 Sol_MgSO4_p(1) = cs_soil(j)%ly(jj)%salt_min(4)
  62 Sol_NaCl_p(1)  = cs_soil(j)%ly(jj)%salt_min(5)
  65 sol_bd = soil(j)%phys(jj)%bd
  66 Sol_CaCO3(1) = (Sol_CaCO3_p(1)/100) *(sol_bd/(waterC*100.0))*1000.0
  67 Sol_MgCO3(1) = (Sol_MgCO3_p(1)/100) *(sol_bd/(waterC*84.31))*1000.0
  68 Sol_CaSO4(1) = (Sol_CaSO4_p(1)/100) *(sol_bd/(waterC*136.14))*1000.0
  69 Sol_MgSO4(1) = (Sol_MgSO4_p(1)/100) *(sol_bd/(waterC*120.36))*1000.0
  70 Sol_NaCl(1)  = (Sol_NaCl_p(1)/100) *(sol_bd/(waterC*58.44))*1000.0
  73 ion1 = soil_salt_conc(1) !sulfate
  74 ion2 = soil_salt_conc(2) !calcium
  75 ion3 = soil_salt_conc(3) !magnesium
  76 ion4 = soil_salt_conc(4) !sodium
  77 ion5 = soil_salt_conc(5) !potassium
  78 ion6 = soil_salt_conc(6) !chloride
  79 ion7 = soil_salt_conc(7) !carbonate
  80 ion8 = soil_salt_conc(8) !bicarbonate
  81 Sul_Conc(1) = ion1*((1.0/1000)*(1.0/96.06)) !sulfate
  82 Cal_Conc(1) = ion2*((1.0/1000)*(1.0/40.078)) !calcium
  83 Mg_Conc(1) = ion3*((1.0/1000)*(1.0/24.305)) !magnesium
  84 Sod_Conc(1) = ion4*((1.0/1000)*(1.0/23.0)) !sodium
  85 Pot_Conc(1) = ion5*((1.0/1000)*(1.0/39.0)) !potassium
  86 Cl_Conc(1) = ion6*((1.0/1000)*(1.0/35.45)) !chloride
  87 Car_Conc(1) = ion7*((1.0/1000)*(1.0/60.01)) !carbonate
  88 BiCar_Conc(1) = ion8*((1.0/1000)*(1.0/61.01)) !bicarbonate
  91 call Ionic_strength(IS_temp,Cal_Conc(1),Sul_Conc(1),Car_Conc(1),&
  92 BiCar_Conc(1),Mg_Conc(1),Sod_Conc(1),Pot_Conc(1))
  93 IonStr = IS_temp
  94 I_Prep_in = IonStr
  95 I_diff = 1
  98 c11 = 1
  99 c22 = 1
 100 salt_c3 = 1
 101 salt_c4 = 1
 102 c5 = 1
 104 call activity_coefficient(I_Prep_in)
 107 K_ADJ1 = LAMDA(1)*LAMDA(3)
 108 K_ADJ2 = LAMDA(5)*LAMDA(3)
 109 K_ADJ3 = LAMDA(1)*LAMDA(2)
 110 K_ADJ4 = LAMDA(5)*LAMDA(2)
 111 K_ADJ5 = LAMDA(6)*LAMDA(6)
IF (K_ADJ1.gt.0.) THEN Lines 113-114
 114 salt_K1 = Ksp11/K_ADJ1
END IFLine 114
ELSE Lines 115-117
 116 salt_K1 = 0.
END IF Line 117
IF (K_ADJ2.gt.0.) THEN Lines 118-119
 119 salt_K2 = Ksp21/K_ADJ2
END IFLine 119
ELSE Lines 120-122
 121 salt_K2 = 0.
END IF Line 122
IF (K_ADJ3.gt.0.) THEN Lines 123-124
 124 salt_K3 = Ksp31/K_ADJ3
END IFLine 124
ELSE Lines 125-127
 126 salt_K3 = 0.
END IF Line 127
IF (K_ADJ4.gt.0.) THEN Lines 128-129
 129 salt_K4 = Ksp41/K_ADJ4
END IFLine 129
ELSE Lines 130-132
 131 salt_K4 = 0.
END IF Line 132
IF (K_ADJ5.gt.0.) THEN Lines 133-134
 134 salt_K5 = Ksp51/K_ADJ5
END IFLine 134
ELSE Lines 135-137
 136 salt_K5 = 0.
END IF Line 137
 139 errorTotal = 1
 142 iter_count = 1
DO while (errorTotal.GE.1e-3) Lines 143-170
 144 call CaCO3
 145 call MgCO3
 146 call CaSO4
 147 call MgSO4
 148 call NaCl
 151 error1ST = Car_Conc(c22+1)-Car_Conc(c22+2)
 152 error2ND = Cal_Conc(c11+1)-Cal_Conc(c11+2)
 153 error3RD = Sul_Conc(salt_c4+1)-Sul_Conc(salt_c4+2)
 155 errorTotal = max(abs(error1ST),abs(error2ND),abs(error3RD))
 158 c11 = c11 + 2
 159 c22 = c22 + 2
 160 salt_c3 = salt_c3 + 2
 161 salt_c4 = salt_c4 + 2
 162 c5 = c5 + 1
 165 iter_count = iter_count + 1
IF (iter_count.gt.500) THEN Lines 166-168
 167 goto 10
END IFLine 168
END DOLine 170
 174 10    upion1 = Sul_Conc(salt_c4)
 175 upion2 = Cal_Conc(c11)
 176 upion3 = Mg_Conc(salt_c3)
 177 upion4 = Sod_Conc(c5)
 178 upion5 = Pot_Conc(1)
 179 upion6 = Cl_Conc(c5)
 180 upion7 = Car_Conc(c22)
 181 upion8 = BiCar_Conc(1)
 184 soil_salt_conc(1) = Sul_Conc(salt_c4)*(96.06*1000.0)
 185 soil_salt_conc(2) = Cal_Conc(c11)*(40.078*1000.0)
 186 soil_salt_conc(3) = Mg_Conc(salt_c3)*(24.305*1000.0)
 187 soil_salt_conc(4) = Sod_Conc(c5)*(23.0*1000.0)
 188 soil_salt_conc(5) = Pot_Conc(1)*(39.0*1000.0)
 189 soil_salt_conc(6) = Cl_Conc(c5)*(35.45*1000.0)
 190 soil_salt_conc(7) = Car_Conc(c22)*(60.01*1000.0)
 191 soil_salt_conc(8) = BiCar_Conc(1)*(61.01*1000.0)
 193 return
 194 end !salt_chem_soil_single
Allocations
n/a
Calls
Calls
Procedures called by this subroutine.
Local Variables
Type Visibility Attributes Name Initial
integer, private :: j
integer, private :: jj
integer, private :: m
integer, private :: n
integer, private :: dum
integer, private :: iter_count
real, private :: ion1
real, private :: ion2
real, private :: ion3
real, private :: ion4
real, private :: ion5
real, private :: ion6
real, private :: ion7
real, private :: ion8
real, private :: sol_water
real, private :: sol_thick
real, private :: sol_bd
real, private :: Sol_CaCO3_p
real, private :: Sol_MgCO3_p
real, private :: Sol_CaSO4_p
real, private :: Sol_MgSO4_p
real, private :: Sol_NaCl_p
real, private :: I_Prep_in
real, private :: I_diff
real, private :: SkipedIEX
Variables
Type Visibility Attributes Name Initial
integer, public :: hru_num
integer, public :: lay_num
real, public :: waterC
Call graph
salt_chem_soil_single calls activity_coefficient, caco3, caso4, ionic_strength, mgco3, mgso4, nacl