salt_chem_hru – TestDataProject
salt_chem_hru Subroutine
249 statements
Source File
subroutine salt_chem_hru()
Called From
n/a
Arguments
n/a
Outside Variables and Types
type(soil_profile) (1 attribute from soil_module)
Attribute Name Description
soil
type (1 attribute from constituent_mass_module)
Attribute Name Description
cs_db%num_salts None
type(soil_constituent_mass) (1 attribute from constituent_mass_module)
Attribute Name Description
cs_soil
type(object_salt_balance) (1 attribute from salt_module)
Attribute Name Description
hsaltb_d
double precision (32 attributes from salt_data_module)
Attribute Name Description
Sul_Conc(2000)
Cal_Conc(2000)
Mg_Conc(2000)
Sod_Conc(2000)
Pot_Conc(2000)
Cl_Conc(2000)
Car_Conc(2000)
BiCar_Conc(2000)
salt_K1
salt_K2
salt_K3
salt_K4
salt_K5
Ksp11
Ksp21
Ksp31
Ksp41
Ksp51
upion1
upion2
upion3
upion4
upion5
upion6
upion7
upion8
Sol_CaCO3(1000)
Sol_MgCO3(1000)
Sol_CaSO4(1000)
Sol_MgSO4(1000)
Sol_NaCl(1000)
LAMDA(7)
integer (6 attributes from salt_data_module)
Attribute Name Description
c11
c22
salt_c3
salt_c4
c5
ihru
none |HRU number
Read more…
type(hydrologic_response_unit) (1 attribute from hru_module)
Attribute Name Description
hru
Uses
basin_module
soil_module
constituent_mass_module
time_module
salt_module
salt_data_module
hru_module
I/O
n/a
Local Variables
Type Visibility Attributes Name Initial
integer, public :: j = 0
integer, public :: jj = 0
integer, public :: m = 0
integer, public :: iter_count = 0
real, public :: ion1 = 0.
real, public :: ion2 = 0.
real, public :: ion3 = 0.
real, public :: ion4 = 0.
real, public :: ion5 = 0.
real, public :: ion6 = 0.
real, public :: ion7 = 0.
real, public :: ion8 = 0.
real, public :: hru_area_m2 = 0.
real, public :: water_volume = 0.
real, public :: sol_water = 0.
real, public :: sol_thick = 0.
real, public :: waterC = 0.
real, public :: Sol_CaCO3_p(1000) = 0.
real, public :: Sol_MgCO3_p(1000) = 0.
real, public :: Sol_CaSO4_p(1000) = 0.
real, public :: Sol_MgSO4_p(1000) = 0.
real, public :: Sol_NaCl_p(1000) = 0.
real, public :: I_Prep_in = 0.
real, public :: I_diff = 0.
real, public :: SkipedIEX = 0.
real, public :: soil_volume = 0.
real, public :: mass_before = 0.
real, public :: mass_after = 0.
real, public :: salt_mass_kg = 0.
real, public :: soil_mass = 0.
real, public :: sol_bd = 0.
real, public :: mass_before_dis = 0.
real, public :: mass_before_sol = 0.
real, public :: total_before = 0.
real, public :: mass_after_dis = 0.
real, public :: mass_after_sol = 0.
real, public :: total_after = 0.
double precision, public :: IonStr
double precision, public :: IS_temp
double precision, public :: K_ADJ1
double precision, public :: K_ADJ2
double precision, public :: K_ADJ3
double precision, public :: K_ADJ4
double precision, public :: K_ADJ5
double precision, public :: error1ST
double precision, public :: error2ND
double precision, public :: error3RD
double precision, public :: errorTotal
real, private :: CharBal
real, private :: CharBal
real, private :: a_size
integer, private :: ii
real, private :: A
real, private :: B
real, private :: CEC
real, private :: Sel_K1
real, private :: Sel_K2
real, private :: Sel_K3
real, private :: Sel_K4
real, private :: Sel_K5
real, private :: Sel_K6
real, private :: XCAINI
real, private :: XMGINI
real, private :: XNAINI
real, private :: XKINI
real, private :: DeltaX_Ca
real, private :: DeltaX_Mg
real, private :: DeltaX_Na
real, private :: DeltaX_K
real, private :: Con_Ca
real, private :: Con_Mg
real, private :: Con_Na
real, private :: Con_K
real, private :: X_Ca
real, private :: X_Mg
real, private :: X_Na
real, private :: X_K
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure. Use mouse wheel to zoom, drag to pan.
Reset Zoom Help
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
~ ~ ~ PURPOSE ~ ~ ~ (line 3)
this subroutine calculates salt ion concentrations based on equilibrium chemical reactions, for an HRU (line 4)
(precipitation-dissolution, complexation, cation exchange) (line 5)
~ ~ ~ INCOMING VARIABLES ~ ~ ~ (line 7)
name |units |definition (line 8)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ (line 9)
ihru |none |HRU number (line 10)
sol_csalt |mg Salt/L |concentration of salt ions in solution in each soil layer (line 11)
saltgw_conc !mg Salt/L |concentration of salt ions in groundwater (line 12)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ (line 13)
~ ~ ~ OUTGOING VARIABLES ~ ~ ~ (line 15)
name |units |definition (line 16)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ (line 17)
sol_csalt |mg Salt/L |concentration of salt ions in solution in each soil layer (line 18)
saltgw_conc !mg Salt/L |concentration of salt ions in groundwater (line 19)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ (line 20)
  71 K_ADJ1,K_ADJ2,K_ADJ3,K_ADJ4,K_ADJ5,&
  72 error1ST,error2ND,error3RD,errorTotal
  74 SkipedIEX = 0.
  77 j = ihru
  80 hru_area_m2 = hru(j)%area_ha * 10000.
  83 mass_before = 0.
  84 mass_after = 0.
  86 mass_before_dis = 0.
  87 mass_before_sol = 0.
  88 mass_after_dis = 0.
  89 mass_after_sol = 0.
  90 total_before = 0.
  91 total_after = 0.
DO jj = 1,soil(j)%nly
  96 sol_water = soil(j)%phys(jj)%st
  97 sol_thick = soil(j)%phys(jj)%thick
  98 waterC = sol_water / sol_thick
 101 Sol_CaCO3_p(1) = cs_soil(j)%ly(jj)%salt_min(1)
 102 Sol_MgCO3_p(1) = cs_soil(j)%ly(jj)%salt_min(2)
 103 Sol_CaSO4_p(1) = cs_soil(j)%ly(jj)%salt_min(3)
 104 Sol_MgSO4_p(1) = cs_soil(j)%ly(jj)%salt_min(4)
 105 Sol_NaCl_p(1)  = cs_soil(j)%ly(jj)%salt_min(5)
 108 soil_volume = hru_area_m2 * (sol_thick/1000.) !m3 of soil
 109 soil_mass = soil_volume * (soil(j)%phys(jj)%bd*1000.) !kg of soil
 116 sol_bd = soil(j)%phys(jj)%bd
 117 if(waterC.eq.0.) waterC = 0.05
 118 Sol_CaCO3(1) = (Sol_CaCO3_p(1)/100) *&
 119 (sol_bd/(waterC*100.0))*1000.0
 120 Sol_MgCO3(1) = (Sol_MgCO3_p(1)/100) *&
 121 (sol_bd/(waterC*84.31))*1000.0
 122 Sol_CaSO4(1) = (Sol_CaSO4_p(1)/100) *&
 123 (sol_bd/(waterC*136.14))*1000.0
 124 Sol_MgSO4(1) = (Sol_MgSO4_p(1)/100) *&
 125 (sol_bd/(waterC*120.36))*1000.0
 126 Sol_NaCl(1)  = (Sol_NaCl_p(1)/100) *&
 127 (sol_bd/(waterC*58.44))*1000.0
 130 water_volume = (soil(j)%phys(jj)%st/1000.) * hru_area_m2
 149 mass_before_dis = mass_before_dis + mass_before
 152 total_before = total_before + (mass_before_dis+mass_before_sol)
 155 ion1 = cs_soil(j)%ly(jj)%saltc(1) !sulfate
 156 ion2 = cs_soil(j)%ly(jj)%saltc(2) !calcium
 157 ion3 = cs_soil(j)%ly(jj)%saltc(3) !magnesium
 158 ion4 = cs_soil(j)%ly(jj)%saltc(4) !sodium
 159 ion5 = cs_soil(j)%ly(jj)%saltc(5) !potassium
 160 ion6 = cs_soil(j)%ly(jj)%saltc(6) !chloride
 161 ion7 = cs_soil(j)%ly(jj)%saltc(7) !carbonate
 162 ion8 = cs_soil(j)%ly(jj)%saltc(8)!bicarbonate
 164 Sul_Conc(1) = ion1*((1.0/1000)*(1.0/96.06)) !sulfate
 165 Cal_Conc(1) = ion2*((1.0/1000)*(1.0/40.078)) !calcium
 166 Mg_Conc(1) = ion3*((1.0/1000)*(1.0/24.305)) !magnesium
 167 Sod_Conc(1) = ion4*((1.0/1000)*(1.0/23.0)) !sodium
 168 Pot_Conc(1) = ion5*((1.0/1000)*(1.0/39.0)) !potassium
 169 Cl_Conc(1) = ion6*((1.0/1000)*(1.0/35.45)) !chloride
 170 Car_Conc(1) = ion7*((1.0/1000)*(1.0/60.01)) !carbonate
 171 BiCar_Conc(1) = ion8*((1.0/1000)*(1.0/61.01)) !bicarbonate
 174 call Ionic_strength(IS_temp,Cal_Conc(1),Sul_Conc(1),Car_Conc(1),&
 175 BiCar_Conc(1),Mg_Conc(1),Sod_Conc(1),&
 176 Pot_Conc(1))
 177 IonStr = IS_temp
 178 I_Prep_in = IonStr
 179 I_diff = 1
 182 c11 = 1
 183 c22 = 1
 184 salt_c3 = 1
 185 salt_c4 = 1
 186 c5 = 1
 191 call activity_coefficient(I_Prep_in)
 194 K_ADJ1 = LAMDA(1)*LAMDA(3)
 195 K_ADJ2 = LAMDA(5)*LAMDA(3)
 196 K_ADJ3 = LAMDA(1)*LAMDA(2)
 197 K_ADJ4 = LAMDA(5)*LAMDA(2)
 198 K_ADJ5 = LAMDA(6)*LAMDA(6)
 226 errorTotal = 1
 229 iter_count = 1
 261 10        upion1 = Sul_Conc(salt_c4)
 262 upion2 = Cal_Conc(c11)
 263 upion3 = Mg_Conc(salt_c3)
 264 upion4 = Sod_Conc(c5)
 265 upion5 = Pot_Conc(1)
 266 upion6 = Cl_Conc(c5)
 267 upion7 = Car_Conc(c22)
 268 upion8 = BiCar_Conc(1)
 273 upion1 = Sul_Conc(salt_c4)*(96.06*1000.0)
 274 upion2 = Cal_Conc(c11)*(40.078*1000.0)
 275 upion3 = Mg_Conc(salt_c3)*(24.305*1000.0)
 276 upion4 = Sod_Conc(c5)*(23.0*1000.0)
 277 upion5 = Pot_Conc(1)*(39.0*1000.0)
 278 upion6 = Cl_Conc(c5)*(35.45*1000.0)
 279 upion7 = Car_Conc(c22)*(60.01*1000.0)
 280 upion8= BiCar_Conc(1)*(61.01*1000.0)
 283 call cationexchange
 286 if (upion2.le.0 .or. upion3.le.0 .or. upion4.le.0 .or. &
 287 upion5.le.0) then
 288 upion2 = Cal_Conc(c11)*(40.078*1000.0)
 289 upion3 = Mg_Conc(salt_c3)*(24.305*1000.0)
 290 upion4 = Sod_Conc(c5)*(23.0*1000.0)
 291 upion5 = Pot_Conc(1)*(39.0*1000.0)
 292 SkipedIEX = SkipedIEX + 1
 294 upion2 = upion2
 295 upion3 = upion3
 296 upion4 = upion4
 297 upion5 = upion5
 301 cs_soil(j)%ly(jj)%saltc(1) = upion1
 302 cs_soil(j)%ly(jj)%saltc(2) = upion2
 303 cs_soil(j)%ly(jj)%saltc(3) = upion3
 304 cs_soil(j)%ly(jj)%saltc(4) = upion4
 305 cs_soil(j)%ly(jj)%saltc(5) = upion5
 306 cs_soil(j)%ly(jj)%saltc(6) = upion6
 307 cs_soil(j)%ly(jj)%saltc(7) = upion7
 308 cs_soil(j)%ly(jj)%saltc(8) = upion8
 311 hru_area_m2 = hru(j)%area_ha * 10000. !ha --> m2
 312 water_volume = (soil(j)%phys(jj)%st/1000.) * hru_area_m2
 326 mass_after_dis = mass_after_dis + mass_after
 329 sol_bd = soil(j)%phys(jj)%bd
 330 Sol_CaCO3_p(c5) = (Sol_CaCO3(c5)*100.0)&
 331 /((sol_bd/(waterC*100.0))*1000.0)
 332 Sol_MgCO3_p(c5) = (Sol_MgCO3(c5)*100.0)&
 333 /((sol_bd/(waterC*84.31))*1000.0)
 334 Sol_CaSO4_p(c5) = (Sol_CaSO4(c5)*100.0)&
 335 /((sol_bd/(waterC*136.14))*1000.0)
 336 Sol_MgSO4_p(c5) = (Sol_MgSO4(c5)*100.0)&
 337 /((sol_bd/(waterC*120.36))*1000.0)
 338 Sol_NaCl_p(c5)  = (Sol_NaCl(c5)*100.0)&
 339 /((sol_bd/(waterC*58.44))*1000.0)
 342 cs_soil(j)%ly(jj)%salt_min(1) = Sol_CaCO3_p(c5)
 343 cs_soil(j)%ly(jj)%salt_min(2) = Sol_MgCO3_p(c5)
 344 cs_soil(j)%ly(jj)%salt_min(3) = Sol_CaSO4_p(c5)
 345 cs_soil(j)%ly(jj)%salt_min(4) = Sol_MgSO4_p(c5)
 346 cs_soil(j)%ly(jj)%salt_min(5) = Sol_NaCl_p(c5)
 360 total_after = total_after + (mass_after_dis + mass_after_sol)
 362 enddo !go to next soil layer
 365 mass_before = mass_before / hru(j)%area_ha !kg/ha
 366 mass_after = mass_after / hru(j)%area_ha !kg/ha
 367 hsaltb_d(j)%salt(1)%diss = mass_after - mass_before
 371 return
 372 end
 378 subroutine Ionic_Strength(IS_temp,A,B,C,D,E,F,G)
 387 DATA CharBal/2.0, -2.0, -2.0, -1.0, 2.0, 1.0, 1.0/
 389 IS_temp = 0.5*(CharBal(1)**2*A&
 390 +CharBal(2)**2*B&
 391 +CharBal(3)**2*C&
 392 +CharBal(4)**2*D&
 393 +CharBal(5)**2*E&
 394 +CharBal(6)**2*F&
 395 +CharBal(7)**2*G)
 397 return
 398 end
 405 subroutine activity_coefficient(I_Prep_in)
 413 DATA CharBal/2.0, -2.0, -2.0, -1.0, 2.0, 1.0, 1.0/
 414 DATA a_size/6.0, 4.0, 4.5, 4.0, 8.0, 4.5, 3.0/
 418 A = 0.5 !at 298 K
 419 B = 0.33 !at 298 K
 439 return
 440 end
 451 subroutine CaSO4
 459 PosSolv,CalSul_Prep,Solid_CaSO4,Dissolved_Solid,&
 460 Calcium_Conc,Sulfate_Conc
 462 M1 = Sol_CaSO4(c5)
 463 M2 = Cal_Conc(c11+1)
 464 M3 = Sul_Conc(salt_c4)
 465 Ksp = salt_K3
 467 Solv = 0.5*(-(M2+M3)+sqrt((M2+M3)**2-4*(M2*M3-Ksp)))
 468 Trial_Ksp = M2 * M3
 503 Sol_CaSO4(c5+1) = Solid_CaSO4
 504 Cal_Conc(c11+2) = Calcium_Conc
 505 Sul_Conc(salt_c4+1) = Sulfate_Conc
 507 return
 508 end
 519 subroutine MgCO3
 527 PosSolv,MgCar_Prep,Solid_MgCO3,Dissolved_Solid,&
 528 Mag_Conc,Carbonate_Conc
 530 M1 = Sol_MgCO3(c5)
 531 M2 = Mg_Conc(salt_c3)
 532 M3 = Car_Conc(c22+1)
 533 Ksp = salt_K2
 534 Solv = 0.5*(-(M2+M3)+sqrt((M2+M3)**2-4*(M2*M3-Ksp)))
 535 Trial_Ksp=M2*M3
 571 Sol_MgCO3(c5+1) = Solid_MgCO3
 572 Mg_Conc(salt_c3+1) =   Mag_Conc
 573 Car_Conc(c22+2) =  Carbonate_Conc
 575 return
 576 end
 587 subroutine NaCl
 595 PosSolv,SodiumChloride_Prep,Solid_NaCl,Dissolved_Solid,&
 596 Sodium_Conc,Chloride_Conc
 598 M1 = Sol_NaCl(c5)
 599 M2 = Sod_Conc(c5)
 600 M3 = Cl_Conc(c5)
 601 Ksp = salt_K5
 603 Solv = 0.5*(-(M2+M3)+sqrt((M2+M3)**2-4*(M2*M3-Ksp)))
 604 Trial_Ksp=M2*M3
 640 Sol_NaCl(c5+1) = Solid_NaCl
 641 Sod_Conc(c5+1) = Sodium_Conc
 642 Cl_Conc(c5+1) = Chloride_Conc
 644 return
 645 end
 656 subroutine MgSO4
 664 PosSolv,MgSul_Prep,Solid_MgSO4,Dissolved_Solid,&
 665 Mag_Conc,Sulfate_Conc
 667 M1 = Sol_MgSO4(c5)
 668 M2 = Mg_Conc(salt_c3+1)
 669 M3 = Sul_Conc(salt_c4+1)
 670 Ksp = salt_K4
 672 Solv = 0.5*(-(M2+M3)+sqrt((M2+M3)**2-4*(M2*M3-Ksp)))
 673 Trial_Ksp=M2*M3
 709 Sol_MgSO4(c5+1) = Solid_MgSO4
 710 Mg_Conc(salt_c3+2) = Mag_Conc
 711 Sul_Conc(salt_c4+2) = Sulfate_Conc
 713 return
 714 end
 725 subroutine CaCO3
 731 PosSolv,CalCar_Prep,Solid_CaCO3,Dissolved_Solid,&
 732 Calcium_Conc,Carbonate_Conc
 734 M1 = Sol_CaCO3(c5)
 735 M2 = Cal_Conc(c11)
 736 M3 = Car_Conc(c22)
 737 Ksp = salt_K1
 738 Solv = 0.5*(-(M2+M3)+sqrt((M2+M3)**2-4*(M2*M3-Ksp)))
 739 Trial_Ksp=M2*M3
 775 Sol_CaCO3(c5+1) = Solid_CaCO3
 776 Cal_Conc(c11+1) =  Calcium_Conc
 777 Car_Conc(c22+1) = Carbonate_Conc
 779 return
 780 end
 795 subroutine cationexchange
 826 CEC = 15 ! meq/100g soil
 829 Con_Ca = upion2/40  ! mmol/liter water
 830 Con_Mg = upion3/24  ! mmol/liter water
 831 Con_Na = upion4/23  ! mmol/liter water
 832 Con_K  = upion5/39  ! mmol/liter water
 834 if(Con_Ca.gt.0 .and. Con_Mg.gt.0 .and. &
 835 Con_Na.gt.0 .and. Con_K.gt.0) then
 838 Sel_K1 = 0.7
 839 Sel_K2 = 6
 840 Sel_K3 = 0.4
 841 Sel_K4 = 0.2
 842 Sel_K5 = 4
 843 Sel_K6 = 16
 846 XCAINI = 13.6  ! meg/100g soil
 847 XMGINI = 0.17  !meq/100g soil
 848 XNAINI = 0.25 !meq/100g soil
 849 XKINI = 0.18 !meq/100g soil
 850 X_Ca = CEC/(1+((Sel_K1*(Con_Mg)**0.5)/((Con_Ca)**0.5))+&
 851 ((Con_Na)/(Sel_K2*(Con_Ca)**0.5))+&
 852 ((Con_K)/(Sel_K3*(Con_Ca)**0.5)))
 853 X_Mg = CEC/(((Con_Ca)**0.5/(Sel_K1*(Con_Mg)**0.5))+1+&
 854 ((Con_Na)/(Sel_K4*(Con_Mg)**0.5))+&
 855 ((Con_K)/(Sel_K5*(Con_Mg)**0.5)))
 856 X_Na = CEC/(((Sel_K2*(Con_Ca)**0.5)/(Con_Na))+&
 857 ((Sel_K5*(Con_Mg)**0.5)/(Con_Na))+1+((Sel_K6*Con_K)/(Con_Na)))
 858 X_K = CEC/(((Sel_K3*(Con_Ca)**0.5)/(Con_K))+&
 859 ((Sel_K4*(Con_Mg)**0.5)/(Con_K))+(Con_Na/(Sel_K6*Con_K))+1)
 878 DeltaX_Ca = X_Ca - XCAINI
 879 DeltaX_Mg = X_Mg - XMGINI
 880 DeltaX_Na = X_Na - XNAINI
 881 DeltaX_K = X_K - XKINI
 883 upion2 = Con_Ca*40 - DeltaX_Ca*200*1.65/0.3 ! 0.3 = water content
 884 upion3 = Con_Mg*24 - DeltaX_Mg*120*1.65/0.3
 885 upion4 = Con_Na*23 - DeltaX_Na*230*1.65/0.3
 886 upion5 = Con_K*39 - DeltaX_K*390*1.65/0.3
 903 return
 904 end ! end subroutine cation exchange
DO m=1,5 Lines 110-113
 111 mass_before_sol = mass_before_sol + &
 112 (soil_mass*(cs_soil(j)%ly(jj)%salt_min(m)/100.))
END DOLine 113
DO m=1,cs_db%num_salts Lines 131-146
 138 salt_mass_kg = cs_soil(j)%ly(jj)%salt(m) * hru(j)%area_ha !kg of salt
 139 mass_before = mass_before + salt_mass_kg
IF (cs_soil(j)%ly(jj)%salt(m).lt.0) THEN Lines 132-134
 133 cs_soil(j)%ly(jj)%salt(m) = 0.
END IFLine 134
IF (cs_soil(j)%ly(jj)%saltc(m).lt.0) THEN Lines 135-137
 136 cs_soil(j)%ly(jj)%saltc(m) = 0.
END IFLine 137
IF (water_volume.gt.0) THEN Lines 140-142
 141 cs_soil(j)%ly(jj)%saltc(m) = (salt_mass_kg * 1000.) / &
 142 water_volume                   !g/m3 = mg/L
END IFLine 142
ELSE Lines 143-145
 144 cs_soil(j)%ly(jj)%saltc(m) = 0.
END IF Line 145
END DOLine 146
IF (K_ADJ1.gt.0.) THEN Lines 200-201
 201 salt_K1 = Ksp11/K_ADJ1
END IFLine 201
ELSE Lines 202-204
 203 salt_K1 = 0.
END IF Line 204
IF (K_ADJ2.gt.0.) THEN Lines 205-206
 206 salt_K2 = Ksp21/K_ADJ2
END IFLine 206
ELSE Lines 207-209
 208 salt_K2 = 0.
END IF Line 209
IF (K_ADJ3.gt.0.) THEN Lines 210-211
 211 salt_K3 = Ksp31/K_ADJ3
END IFLine 211
ELSE Lines 212-214
 213 salt_K3 = 0.
END IF Line 214
IF (K_ADJ4.gt.0.) THEN Lines 215-216
 216 salt_K4 = Ksp41/K_ADJ4
END IFLine 216
ELSE Lines 217-219
 218 salt_K4 = 0.
END IF Line 219
IF (K_ADJ5.gt.0.) THEN Lines 220-221
 221 salt_K5 = Ksp51/K_ADJ5
END IFLine 221
ELSE Lines 222-224
 223 salt_K5 = 0.
END IF Line 224
DO while (errorTotal.GE.1e-3) Lines 230-257
 231 call CaCO3
 232 call MgCO3
 233 call CaSO4
 234 call MgSO4
 235 call NaCl
 238 error1ST = Car_Conc(c22+1)-Car_Conc(c22+2)
 239 error2ND = Cal_Conc(c11+1)-Cal_Conc(c11+2)
 240 error3RD = Sul_Conc(salt_c4+1)-Sul_Conc(salt_c4+2)
 242 errorTotal = max(abs(error1ST),abs(error2ND),abs(error3RD))
 245 c11 = c11 + 2
 246 c22 = c22 + 2
 247 salt_c3 = salt_c3 + 2
 248 salt_c4 = salt_c4 + 2
 249 c5 = c5 + 1
 252 iter_count = iter_count + 1
IF (iter_count.gt.500) THEN Lines 253-255
 254 goto 10
END IFLine 255
END DOLine 257
DO m=1,cs_db%num_salts Lines 313-317
 314 cs_soil(j)%ly(jj)%salt(m) = &
 315 (cs_soil(j)%ly(jj)%saltc(m)/1000.) * water_volume&
 316 / hru(j)%area_ha
END DOLine 317
DO m=1,cs_db%num_salts !total salt mass in soil layer Lines 320-323
 321 salt_mass_kg = cs_soil(j)%ly(jj)%salt(m) * hru(j)%area_ha !kg of salt
 322 mass_after = mass_after + salt_mass_kg
END DOLine 323
DO m=1,5 Lines 347-351
IF (cs_soil(j)%ly(jj)%salt_min(m) > 100.) THEN Lines 348-350
 349 cs_soil(j)%ly(jj)%salt_min(m) = 100.
END IFLine 350
END DOLine 351
DO m=1,5 Lines 354-357
 355 mass_after_sol = mass_after_sol + &
 356 (soil_mass*(cs_soil(j)%ly(jj)%salt_min(m)/100.))
END DOLine 357
IF (I_Prep_in.LE.1e-1) THEN Lines 421-425
DO ii = 1,7 Lines 422-425
 423 LAMDA(ii)= 10.0**(-A*CharBal(ii)**2.0  &
 424 *(I_Prep_in**0.5/(1+B*a_size(ii)*I_Prep_in**0.5)))
END DOLine 425
END IFLine 425
ELSE IF (I_Prep_in.GE.5) THEN Lines 426-431
 427 I_Prep_in = 0.5
DO ii = 1,7 Lines 428-431
 429 LAMDA(ii)= 10.0**(-A*CharBal(ii)**2.0  &
 430 *(I_Prep_in**0.5/(1+I_Prep_in**0.5)-0.3*I_Prep_in))
END DOLine 431
END IF Line 431
ELSE Lines 432-437
DO ii = 1,7 Lines 433-436
 434 LAMDA(ii)= 10.0**(-A*CharBal(ii)**2.0  &
 435 *(I_Prep_in**0.5/(1+I_Prep_in**0.5)-0.3*I_Prep_in))
END DOLine 436
END IF Line 437
IF (Trial_Ksp.gt.Ksp) THEN Lines 470-479
 473 PosSolv = abs(Solv)
 474 CalSul_Prep = PosSolv
 475 Solid_CaSO4 = M1+CalSul_Prep
 476 Dissolved_Solid = 0
 477 Calcium_Conc = M2-CalSul_Prep
 478 Sulfate_Conc = M3-CalSul_Prep
END IFLine 479
ELSE IF (M1.gt.Solv) THEN Lines 480-492
 483 PosSolv = Solv
 488 Calcium_Conc = (M2+PosSolv)
 489 Sulfate_Conc = (M3+PosSolv)
 490 Dissolved_Solid = PosSolv
 491 Solid_CaSO4 = (M1-PosSolv)
END IF Line 492
ELSE Lines 493-501
 497 Calcium_Conc = (M1+M2)
 498 Sulfate_Conc = (M1+M3)
 499 Dissolved_Solid = M1
 500 Solid_CaSO4 = 0
END IF Line 501
IF (Trial_Ksp.GT.Ksp) THEN Lines 537-546
 540 PosSolv = abs(Solv)
 541 MgCar_Prep = PosSolv
 542 Solid_MgCO3 = M1+MgCar_Prep
 543 Dissolved_Solid = 0
 544 Mag_Conc = M2-MgCar_Prep
 545 Carbonate_Conc = M3-MgCar_Prep
END IFLine 546
ELSE IF (M1.GT.Solv) THEN Lines 547-559
 550 PosSolv = Solv
 555 Mag_Conc = (M2+PosSolv)
 556 Carbonate_Conc = (M3+PosSolv)
 557 Dissolved_Solid = PosSolv
 558 Solid_MgCO3 = (M1-PosSolv)
END IF Line 559
ELSE Lines 560-569
 564 Mag_Conc = (M1+M2)
 565 Carbonate_Conc = (M1+M3)
 566 Dissolved_Solid = M1
 567 Solid_MgCO3= 0
END IF Line 569
IF (Trial_Ksp.GT.Ksp) THEN Lines 606-615
 609 PosSolv = abs(Solv)
 610 SodiumChloride_Prep = PosSolv
 611 Solid_NaCl = M1+SodiumChloride_Prep
 612 Dissolved_Solid = 0
 613 Sodium_Conc = M2-SodiumChloride_Prep
 614 Chloride_Conc  = M3-SodiumChloride_Prep
END IFLine 615
ELSE IF (M1.GT.Solv) THEN Lines 616-628
 619 PosSolv = Solv
 624 Sodium_Conc = (M2+PoSSolv)
 625 Chloride_Conc  = (M3+PosSolv)
 626 Dissolved_Solid = PosSolv
 627 Solid_NaCl = (M1-PosSolv)
END IF Line 628
ELSE Lines 629-638
 633 Sodium_Conc = (M1+M2)
 634 Chloride_Conc  = (M1+M3)
 635 Dissolved_Solid = M1
 636 Solid_NaCl= 0
END IF Line 638
IF (Trial_Ksp.GT.Ksp) THEN Lines 675-684
 678 PosSolv = abs(Solv)
 679 MgSul_Prep = PosSolv
 680 Solid_MgSO4 = M1+MgSul_Prep
 681 Dissolved_Solid = 0
 682 Mag_Conc = M2-MgSul_Prep
 683 Sulfate_Conc = M3-MgSul_Prep
END IFLine 684
ELSE IF (M1.GT.Solv) THEN Lines 685-697
 688 PosSolv = Solv
 693 Mag_Conc = (M2+PosSolv)
 694 Sulfate_Conc = (M3+PosSolv)
 695 Dissolved_Solid = PosSolv
 696 Solid_MgSO4 = (M1-PosSolv)
END IF Line 697
ELSE Lines 698-707
 702 Mag_Conc = (M1+M2)
 703 Sulfate_Conc = (M1+M3)
 704 Dissolved_Solid = M1
 705 Solid_MgSO4= 0
END IF Line 707
IF (Trial_Ksp.GT.Ksp) THEN Lines 741-750
 744 PosSolv = abs(Solv)
 745 CalCar_Prep = PosSolv
 746 Solid_CaCO3 = M1+CalCar_Prep
 747 Dissolved_Solid = 0
 748 Calcium_Conc = M2-CalCar_Prep
 749 Carbonate_Conc = M3-CalCar_Prep
END IFLine 750
ELSE IF (M1.GT.Solv) THEN Lines 751-763
 754 PosSolv = Solv
 759 Calcium_Conc = (M2+Solv)
 760 Carbonate_Conc = (M3+Solv)
 761 Dissolved_Solid = Solv
 762 Solid_CaCO3 = (M1-Solv)
END IF Line 763
ELSE Lines 764-773
 768 Calcium_Conc = (M1+M2)
 769 Carbonate_Conc = (M1+M3)
 770 Dissolved_Solid = M1
 771 Solid_CaCO3= 0
END IF Line 773
IF (Con_Ca.LE.0) THEN Lines 888-890
 889 upion2 = -10
END IFLine 890
IF (Con_Mg.LE.0) THEN Lines 891-893
 892 upion3 = -10
END IFLine 893
IF (Con_Na.LE.0) THEN Lines 894-896
 895 upion4 = -10
END IFLine 896
IF (Con_K.LE.0) THEN Lines 897-899
 898 upion5 = -10
END IFLine 899
END DO
Allocations
n/a
Calls
Procedures Called
List of procedures called by this Subroutine.
ionic_strength
activity_coefficient
caco3
mgco3
caso4
mgso4
nacl
cationexchange
Call Graph
Visual representation of procedures called by this Subroutine.
Call graph
salt_chem_hru calls activity_coefficient, caco3, caso4, cationexchange, ionic_strength, mgco3, mgso4, nacl