salt_chem_aqu – TestDataProject
salt_chem_aqu Subroutine
182 statements
Source File
subroutine salt_chem_aqu()
Called From
n/a
Arguments
n/a
Outside Variables and Types
type (1 attribute from constituent_mass_module)
Attribute Name Description
cs_db%num_salts None
type(constituent_mass) (1 attribute from constituent_mass_module)
Attribute Name Description
cs_aqu
integer (6 attributes from hydrograph_module)
Attribute Name Description
icmd
|
c11
c22
salt_c3
salt_c4
c5
type(object_connectivity) (1 attribute from hydrograph_module)
Attribute Name Description
ob
double precision (32 attributes from salt_data_module)
Attribute Name Description
Sul_Conc(2000)
Cal_Conc(2000)
Mg_Conc(2000)
Sod_Conc(2000)
Pot_Conc(2000)
Cl_Conc(2000)
Car_Conc(2000)
BiCar_Conc(2000)
salt_K1
salt_K2
salt_K3
salt_K4
salt_K5
Ksp12
Ksp22
Ksp32
Ksp42
Ksp52
upion1
upion2
upion3
upion4
upion5
upion6
upion7
upion8
Sol_CaCO3(1000)
Sol_MgCO3(1000)
Sol_CaSO4(1000)
Sol_MgSO4(1000)
Sol_NaCl(1000)
LAMDA(7)
type(object_salt_balance_aqu) (1 attribute from salt_aquifer)
Attribute Name Description
asaltb_d
type(aquifer_dynamic) (1 attribute from aquifer_module)
Attribute Name Description
aqu_d
Uses
basin_module
soil_module
constituent_mass_module
hydrograph_module
salt_module
salt_data_module
salt_aquifer
aquifer_module
I/O
n/a
Local Variables
Type Visibility Attributes Name Initial
integer, public :: iaq = 0
integer, public :: m = 0
integer, public :: iter_count = 0
real, public :: ion1 = 0.
real, public :: ion2 = 0.
real, public :: ion3 = 0.
real, public :: ion4 = 0.
real, public :: ion5 = 0.
real, public :: ion6 = 0.
real, public :: ion7 = 0.
real, public :: ion8 = 0.
real, public :: hru_area_m2 = 0.
real, public :: gw_volume = 0.
real, public :: waterC = 0.
real, public :: Sol_CaCO3_p(1000) = 0.
real, public :: Sol_MgCO3_p(1000) = 0.
real, public :: Sol_CaSO4_p(1000) = 0.
real, public :: Sol_MgSO4_p(1000) = 0.
real, public :: Sol_NaCl_p(1000) = 0.
real, public :: I_Prep_in = 0.
real, public :: I_diff = 0.
real, public :: SkipedIEX = 0.
real, public :: mass_before = 0.
real, public :: mass_after = 0.
double precision, public :: IonStr
double precision, public :: IS_temp
double precision, public :: K_ADJ1
double precision, public :: K_ADJ2
double precision, public :: K_ADJ3
double precision, public :: K_ADJ4
double precision, public :: K_ADJ5
double precision, public :: error1ST
double precision, public :: error2ND
double precision, public :: error3RD
double precision, public :: errorTotal
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure. Use mouse wheel to zoom, drag to pan.
Reset Zoom Help
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
~ ~ ~ PURPOSE ~ ~ ~ (line 3)
this subroutine calculates salt ion concentrations based on equilibrium chemical reactions, for an HRU (line 4)
(precipitation-dissolution, complexation, cation exchange) (line 5)
~ ~ ~ INCOMING VARIABLES ~ ~ ~ (line 7)
name |units |definition (line 8)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ (line 9)
ihru |none |HRU number (line 10)
sol_csalt |mg Salt/L |concentration of salt ions in solution in each soil layer (line 11)
saltgw_conc !mg Salt/L |concentration of salt ions in groundwater (line 12)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ (line 13)
~ ~ ~ OUTGOING VARIABLES ~ ~ ~ (line 15)
name |units |definition (line 16)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ (line 17)
sol_csalt |mg Salt/L |concentration of salt ions in solution in each soil layer (line 18)
saltgw_conc !mg Salt/L |concentration of salt ions in groundwater (line 19)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ (line 20)
  60 SkipedIEX = 0.
  63 iaq = ob(icmd)%num
  66 hru_area_m2 = ob(icmd)%area_ha * 10000.
  68 mass_before = 0.
  69 mass_after = 0.
  72 waterC = 0.25 !for now, set equal to an assumed value of porosity
  75 Sol_CaCO3_p(1) = cs_aqu(iaq)%salt_min(1)
  76 Sol_MgCO3_p(1) = cs_aqu(iaq)%salt_min(2)
  77 Sol_CaSO4_p(1) = cs_aqu(iaq)%salt_min(3)
  78 Sol_MgSO4_p(1) = cs_aqu(iaq)%salt_min(4)
  79 Sol_NaCl_p(1)  = cs_aqu(iaq)%salt_min(5)
  80 Sol_CaCO3(1) = (Sol_CaCO3_p(1)/100) *(1.855/(waterC*100.0))*1000.0
  81 Sol_MgCO3(1) = (Sol_MgCO3_p(1)/100) *(1.855/(waterC*84.31))*1000.0
  82 Sol_CaSO4(1) = (Sol_CaSO4_p(1)/100) *(1.855/(waterC*136.14))*1000.0
  83 Sol_MgSO4(1) = (Sol_MgSO4_p(1)/100) *(1.855/(waterC*120.36))*1000.0
  84 Sol_NaCl(1)  = (Sol_NaCl_p(1)/100) *(1.855/(waterC*58.44))*1000.0
  87 gw_volume = (aqu_d(iaq)%stor/1000.)*(ob(icmd)%area_ha*10000.) !m3 of groundwater
DO m=1,cs_db%num_salts Lines 88-101
  95 mass_before = mass_before + cs_aqu(iaq)%salt(m) !kg of salt
IF (cs_aqu(iaq)%salt(m).lt.0) THEN Lines 89-91
  90 cs_aqu(iaq)%salt(m) = 0.
END IFLine 91
IF (cs_aqu(iaq)%saltc(m).lt.0) THEN Lines 92-94
  93 cs_aqu(iaq)%saltc(m) = 0.
END IFLine 94
IF (gw_volume.gt.0) THEN Lines 96-97
  97 cs_aqu(iaq)%saltc(m) = (cs_aqu(iaq)%salt(m) * 1000.) / gw_volume !g/m3 = mg/L
END IFLine 97
ELSE Lines 98-100
  99 cs_aqu(iaq)%saltc(m) = 0.
END IF Line 100
END DOLine 101
 104 ion1 = cs_aqu(iaq)%saltc(1) !sulfate
 105 ion2 = cs_aqu(iaq)%saltc(2) !calcium
 106 ion3 = cs_aqu(iaq)%saltc(3) !magnesium
 107 ion4 = cs_aqu(iaq)%saltc(4) !sodium
 108 ion5 = cs_aqu(iaq)%saltc(5) !potassium
 109 ion6 = cs_aqu(iaq)%saltc(6) !chloride
 110 ion7 = cs_aqu(iaq)%saltc(7) !carbonate
 111 ion8 = cs_aqu(iaq)%saltc(8) !bicarbonate
 112 Sul_Conc(1) = ion1*((1.0/1000)*(1.0/96.06)) !sulfate
 113 Cal_Conc(1) = ion2*((1.0/1000)*(1.0/40.078)) !calcium
 114 Mg_Conc(1) = ion3*((1.0/1000)*(1.0/24.305)) !magnesium
 115 Sod_Conc(1) = ion4*((1.0/1000)*(1.0/23.0)) !sodium
 116 Pot_Conc(1) = ion5*((1.0/1000)*(1.0/39.0)) !potassium
 117 Cl_Conc(1) = ion6*((1.0/1000)*(1.0/35.45)) !chloride
 118 Car_Conc(1) = ion7*((1.0/1000)*(1.0/60.01)) !carbonate
 119 BiCar_Conc(1) = ion8*((1.0/1000)*(1.0/61.01)) !bicarbonate
 122 call Ionic_strength(IS_temp,Cal_Conc(1),Sul_Conc(1),Car_Conc(1),BiCar_Conc(1),Mg_Conc(1),Sod_Conc(1),&
 123 Pot_Conc(1))
 124 IonStr = IS_temp
 125 I_Prep_in = IonStr
 126 I_diff = 1
 129 c11 = 1
 130 c22 = 1
 131 salt_c3 = 1
 132 salt_c4 = 1
 133 c5 = 1
 139 call activity_coefficient(I_Prep_in)
 142 K_ADJ1 = LAMDA(1)*LAMDA(3)
 143 K_ADJ2 = LAMDA(5)*LAMDA(3)
 144 K_ADJ3 = LAMDA(1)*LAMDA(2)
 145 K_ADJ4 = LAMDA(5)*LAMDA(2)
 146 K_ADJ5 = LAMDA(6)*LAMDA(6)
 148 salt_K1 = Ksp12/K_ADJ1
 149 salt_K2 = Ksp22/K_ADJ2
 150 salt_K3 = Ksp32/K_ADJ3
 151 salt_K4 = Ksp42/K_ADJ4
 152 salt_K5 = Ksp52/K_ADJ5
 154 errorTotal = 1
 157 iter_count = 1
DO while (errorTotal.GE.1e-3) Lines 158-185
 159 call CaCO3
 160 call MgCO3
 161 call CaSO4
 162 call MgSO4
 163 call NaCl
 166 error1ST = Car_Conc(c22+1)-Car_Conc(c22+2)
 167 error2ND = Cal_Conc(c11+1)-Cal_Conc(c11+2)
 168 error3RD = Sul_Conc(salt_c4+1)-Sul_Conc(salt_c4+2)
 170 errorTotal = max(abs(error1ST),abs(error2ND),abs(error3RD))
 173 c11 = c11 + 2
 174 c22 = c22 + 2
 175 salt_c3 = salt_c3 + 2
 176 salt_c4 = salt_c4 + 2
 177 c5 = c5 + 1
 180 iter_count = iter_count + 1
IF (iter_count.gt.500) THEN Lines 181-183
 182 goto 20
END IFLine 183
END DOLine 185
 188 20      upion1 = Sul_Conc(salt_c4)
 189 upion2 = Cal_Conc(c11)
 190 upion3 = Mg_Conc(salt_c3)
 191 upion4 = Sod_Conc(c5)
 192 upion5 = Pot_Conc(1)
 193 upion6 = Cl_Conc(c5)
 194 upion7 = Car_Conc(c22)
 195 upion8 = BiCar_Conc(1)
 200 upion1 = Sul_Conc(salt_c4)*(96.06*1000.0)
 201 upion2 = Cal_Conc(c11)*(40.078*1000.0)
 202 upion3 = Mg_Conc(salt_c3)*(24.305*1000.0)
 203 upion4 = Sod_Conc(c5)*(23.0*1000.0)
 204 upion5 = Pot_Conc(1)*(39.0*1000.0)
 205 upion6 = Cl_Conc(c5)*(35.45*1000.0)
 206 upion7 = Car_Conc(c22)*(60.01*1000.0)
 207 upion8= BiCar_Conc(1)*(61.01*1000.0)
 210 call cationexchange
IF (upion2.le.0 .or. upion3.le.0 .or. upion4.le.0 .or. upion5.le.0) THEN Lines 213-218
 214 upion2 = Cal_Conc(c11)*(40.078*1000.0)
 215 upion3 = Mg_Conc(salt_c3)*(24.305*1000.0)
 216 upion4 = Sod_Conc(c5)*(23.0*1000.0)
 217 upion5 = Pot_Conc(1)*(39.0*1000.0)
 218 SkipedIEX = SkipedIEX + 1
END IFLine 218
ELSE Lines 219-224
 220 upion2 = upion2
 221 upion3 = upion3
 222 upion4 = upion4
 223 upion5 = upion5
END IF Line 224
 227 cs_aqu(iaq)%saltc(1) = upion1
 228 cs_aqu(iaq)%saltc(2) = upion2
 229 cs_aqu(iaq)%saltc(3) = upion3
 230 cs_aqu(iaq)%saltc(4) = upion4
 231 cs_aqu(iaq)%saltc(5) = upion5
 232 cs_aqu(iaq)%saltc(6) = upion6
 233 cs_aqu(iaq)%saltc(7) = upion7
 234 cs_aqu(iaq)%saltc(8) = upion8
 237 gw_volume = (aqu_d(iaq)%stor/1000.)*(ob(icmd)%area_ha*10000.) !m3 of groundwater in HRU aquifer
DO m=1,cs_db%num_salts Lines 238-240
 239 cs_aqu(iaq)%salt(m) = (cs_aqu(iaq)%saltc(m)*gw_volume) / 1000. !kg of salt
END DOLine 240
DO m=1,cs_db%num_salts !total salt mass in soil layer Lines 243-245
 244 mass_after = mass_after + cs_aqu(iaq)%salt(m) !kg of salt
END DOLine 245
 248 Sol_CaCO3_p(c5) = (Sol_CaCO3(c5)*100.0)/((1.855/(waterC*100.0))*1000.0)
 249 Sol_MgCO3_p(c5) = (Sol_MgCO3(c5)*100.0)/((1.855/(waterC*84.31))*1000.0)
 250 Sol_CaSO4_p(c5) = (Sol_CaSO4(c5)*100.0)/((1.855/(waterC*136.14))*1000.0)
 251 Sol_MgSO4_p(c5) = (Sol_MgSO4(c5)*100.0)/((1.855/(waterC*120.36))*1000.0)
 252 Sol_NaCl_p(c5)  = (Sol_NaCl(c5)*100.0)/((1.855/(waterC*58.44))*1000.0)
 255 cs_aqu(iaq)%salt_min(1) = Sol_CaCO3_p(c5)
 256 cs_aqu(iaq)%salt_min(2) = Sol_MgCO3_p(c5)
 257 cs_aqu(iaq)%salt_min(3) = Sol_CaSO4_p(c5)
 258 cs_aqu(iaq)%salt_min(4) = Sol_MgSO4_p(c5)
 259 cs_aqu(iaq)%salt_min(5) = Sol_NaCl_p(c5)
 262 asaltb_d(iaq)%salt(1)%diss = mass_after - mass_before
 264 return
 265 end
Allocations
n/a
Calls
Procedures Called
List of procedures called by this Subroutine.
ionic_strength
activity_coefficient
caco3
mgco3
caso4
mgso4
nacl
cationexchange
Call Graph
Visual representation of procedures called by this Subroutine.
Call graph
salt_chem_aqu calls activity_coefficient, caco3, caso4, cationexchange, ionic_strength, mgco3, mgso4, nacl