sd_channel_control – test-src-project
sd_channel_control Subroutine
613 statements
Source File
subroutine sd_channel_control()
Uses
water_body_module
channel_data_module
ch_pesticide_module
channel_module
water_allocation_module
ch_salt_module
gwflow_module
conditional_module
basin_module
climate_module
channel_velocity_module
ch_cs_module
hydrograph_module
constituent_mass_module
sd_channel_module
time_module
Arguments
n/a
I/O
n/a
Outside Variables and Types
type(water_body) (1 attribute from water_body_module)
Attribute Name Description
ch_wat_d
real (13 attributes from ch_pesticide_module)
Attribute Name Description
frsol
none |fraction of pesticide in reach that is soluble
Read more…
frsrb
none |fraction of pesticide in reach that is sorbed
Read more…
rttime
hr |reach travel time
Read more…
ben_area
m2 |benthic area (bottom sediments)
Read more…
rchdep
m |depth of flow on day
Read more…
peakr
rcharea
rt_delt
calculation time step in days
hyd_sep_array
wtemp
stream water temperature C
peakrate
hyd_rad
m^2 |hydraulic radius for each hydrograph time step
Read more…
timeint
days |time spent in each hydrograph time step
Read more…
type(ch_pesticide_output) (1 attribute from ch_pesticide_module)
Attribute Name Description
chpst_d
type (44 attributes from ch_pesticide_module)
Attribute Name Description
chpst%pest None
bsn_cc%gwflow None
bsn_cc%lapse None
bsn_prm%scoef None
bsn_prm%evrch None
hd%flo None
ht1%flo None
ht1%sed None
ht1%temp None
ht2%temp None
ht2%solp None
ht2%sedp None
ht2%flo None
ht2%sed None
ht2%orgn None
hdsep1%flo_tile None
hdsep1%flo_surq None
hdsep1%flo_swgw None
hdsep1%flo_satexsw None
hdsep1%flo_gwsw None
hdsep1%flo_latq None
hdsep1%flo_satex None
hdsep2%flo_tile None
hdsep2%flo_surq None
hdsep2%flo_swgw None
hdsep2%flo_satexsw None
hdsep2%flo_gwsw None
hdsep2%flo_latq None
hdsep2%flo_satex None
cs_db%num_salts None
cs_db%num_tot None
cs_db%num_cs None
cs_db%num_pests None
hcs1%salt None
hcs1%cs None
hcs2%salt None
hcs2%cs None
hcs2%pest None
hcs3%salt None
hcs3%cs None
rcurv%dep None
rcurv%xsec_area None
rcurv%wet_perim None
time%step None
integer (8 attributes from channel_module)
Attribute Name Description
jnut
units |description
Read more…
flood_freq
|
jrch
none |reach number
Read more…
iwst
|
isdch
|
icmd
|
ich
none |object number
Read more…
maxint
number of intervals in hydrograph for degradation
type(channel) (1 attribute from channel_module)
Attribute Name Description
ch
type(water_allocation) (1 attribute from water_allocation_module)
Attribute Name Description
wallo
dimension by water allocation objects
type(ch_salt_output) (1 attribute from ch_salt_module)
Attribute Name Description
chsalt_d
type(decision_table) (2 attributes from conditional_module)
Attribute Name Description
dtbl_flo
d_tbl
type(weather_daily) (1 attribute from climate_module)
Attribute Name Description
w
type(weather_station) (1 attribute from climate_module)
Attribute Name Description
wst
type(channel_velocity_parameters) (1 attribute from channel_velocity_module)
Attribute Name Description
sd_ch_vel
type(ch_cs_output) (1 attribute from ch_cs_module)
Attribute Name Description
chcs_d
type(hyd_output) (6 attributes from hydrograph_module)
Attribute Name Description
hz
ht3
wet
ch_stor
channel storage - max bankfull
ch_in_d
ch_out_d
type(hyd_sep) (1 attribute from hydrograph_module)
Attribute Name Description
ch_stor_hdsep
type(object_connectivity) (1 attribute from hydrograph_module)
Attribute Name Description
ob
type(routing_unit_data) (1 attribute from hydrograph_module)
Attribute Name Description
ru_def
type(routing_unit_elements) (1 attribute from hydrograph_module)
Attribute Name Description
ru_elem
type(channel_surface_elements) (1 attribute from hydrograph_module)
Attribute Name Description
ch_sur
type(channel_aquifer_elements) (1 attribute from hydrograph_module)
Attribute Name Description
aq_ch
sorted by drainage area (smallest first)
type(constituent_mass) (2 attributes from constituent_mass_module)
Attribute Name Description
ch_water
ch_benthic
type(all_constituent_hydrograph) (1 attribute from constituent_mass_module)
Attribute Name Description
obcs
type(gw_load_hydrograph) (1 attribute from constituent_mass_module)
Attribute Name Description
aq_chcs
type(swatdeg_datafiles) (1 attribute from sd_channel_module)
Attribute Name Description
sd_dat
type(swatdeg_channel_dynamic) (1 attribute from sd_channel_module)
Attribute Name Description
sd_ch
type(channel_rating_curve) (1 attribute from sd_channel_module)
Attribute Name Description
ch_rcurv
type(sd_ch_output) (1 attribute from sd_channel_module)
Attribute Name Description
chsd_d
!! Bang Comments
! nbs added 7-20-23 set ht1 to incoming hydrograph add water transfer adjust precip and temperature for elevation using lapse rates if connected to aquifer - add flow set inflow hyds for printing set outgoing flow and sediment - ht2 compute changes in channel dimensions compute flow and travel time at bankfull depth OVERBANK FLOOD
estimate overbank flow - assume a triangular hyd add overbank to wetland storage of hru(s) assume the element is an hru CHANNELIZED FLOW find the crossectional area and depth for volrt by iteration method at 1cm interval depth find the depth until the discharge rate is equal to volrt
adjust peak rate for headcut advance -also adjusts CEAP gully from edge-of-field to trib (assuming rectangular shape and constant tc) new q*qp (m3 * m3/s) equation for entire runoff event
compute sediment yield from headcut- assume bd = 1.2 t/m3 assume channel dimensions are same as data file
Peters latest channel erosion model vel = 1.37 * (sd_ch(ich)%chs ** 0.31) * (12. * sd_ch(ich)%chw) ** 0.32 !annual ave for SWIFT mean daily to peak ratio developed from GARDAY - THE STUDY OF MOST PROBABLE MEAN DAILY BANKFULL RUNOFF VOLUMES IN SMALL WATERSHEDS DOMINATED BY CONVECTIVE/FRONTAL CHANNEL FORMING EVENTS AND THE CO-INCIDENT INNER BERM CHANNELS PART I. Another eq from Peter - Qmax=Qmean(1+2.66Drainage Area^-.3) interpolate rating curve using peak rate use peakrate as flow rate calc soil cohesion vel_cr = log10(8.8 * rcurv%dep / 0.004) * (0.0004 * ((1377.-1000.) * 9.81 * 0.004 + 0.021 * cohes + veg)) ** 0.5 calculate radius of curvature calc mass of sediment eroded -> t = bankcut (m) * depth (m) * lengthcut (m) * bd (t/m3) arc length = 0.33 * meander wavelength * sinuosity -> protected length no downcutting below equilibrium slope calc critical shear and shear on bottom of channel Pa = N/m^2 * m * m/m if bottom shear > d50 -> downcut - widen to maintain width depth ratio calc mass of sediment eroded -> t = cm * m/100cm * width (m) * length (km) * 1000 m/km * bd (t/m3) adjust for incoming bedload and compute deposition stream is completely filled in compute flood plain deposition deposit Particulate P and N in the floodplain
compute sediment leaving the channel - washload only set values for outflow hydrograph calculate flow velocity and travel time ht2 = ht1 use modified qual-2e routines total incoming to output to SWIFT convert mass to concentration convert storage hyd - mass to concentration convert outflow and storage hyds - concentration to mass compute nutrient losses using 2-stage ditch model
reset sed to tons subtract nutrients deposited in floodplain add nutrients from bank erosion - t * mg/kg (ppm) * kg/1000 mg * 1000 kg/t = kg route constituents call mike winchell's new routine for pesticide routing
compute water balance - precip, evap and seep km * m * 1000 m/km * ha/10000 m2 = ha m3 = 10. * mm * ha add precip subtract seepage subtract evaporation adjust entire hydrograph for losses total outgoing to output to SWIFT calculate hydrograph leaving reach and storage in channel
travel time < timestep -- route all stored and frac of incoming travel time > timestep -- then all incoming is stored and frac of stored is routed travel time < timestep -- route all stored and frac of incoming check decision table for flow control - water diversion check decision table for water allocation set outflow hyd to ht2 after diverting water calculate stream temperature set constituents for routing output channel organic-mineral output channel morphology set pesticide output variables set values for recharge hydrograph - should be trans losses
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure.
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
 111 ich = isdch
 112 isd_db = sd_dat(ich)%hyd
 113 iwst = ob(icmd)%wst
 114 ebtm_m = 0.
 115 ebank_m = 0.
 116 erode_bank_cut = 0.
 117 ebtm_t = 0.
 118 ebank_t = 0.
 119 sedout = 0.
 120 washld = 0.
 121 bedld = 0.
 122 dep = 0.
 123 hc = 0.
 124 hc_sed = 0.
 132 if(bsn_cc%gwflow.eq.1) flood_freq(ich) = 0
 136 ht1 = ob(icmd)%hin
IF (ob(icmd)%trans%flo > 1.e-6) THEN Lines 138-141
 139 ht1 = ht1 + ob(icmd)%trans
 140 ob(icmd)%trans = hz
END IFLine 141
IF (cs_db%num_tot > 0) THEN Lines 144-146
 145 hcs1 = obcs(icmd)%hin(1)
END IFLine 146
 148 chsd_d(ich)%flo_in = ht1%flo / 86400.     !flow for morphology output
 149 ch_in_d(ich) = ht1                        !set inflow om hydrograph
 150 ch_in_d(ich)%flo = ht1%flo / 86400.       !flow for om output
 153 hdsep1%flo_surq = ob(icmd)%hdsep_in%flo_surq
 154 hdsep1%flo_latq = ob(icmd)%hdsep_in%flo_latq
 155 hdsep1%flo_gwsw = ob(icmd)%hdsep_in%flo_gwsw
 156 hdsep1%flo_swgw = ob(icmd)%hdsep_in%flo_swgw
 157 hdsep1%flo_satex = ob(icmd)%hdsep_in%flo_satex
 158 hdsep1%flo_satexsw = ob(icmd)%hdsep_in%flo_satexsw
 159 hdsep1%flo_tile = ob(icmd)%hdsep_in%flo_tile
 163 w = wst(iwst)%weat
 164 if (bsn_cc%lapse == 1) call cli_lapse
 165 wst(iwst)%weat = w
 166 ht1%temp = 5.0 + 0.75 * wst(iwst)%weat%tave
 167 wtemp = 5.0 + 0.75 * wst(iwst)%weat%tave
IF (sd_ch(ich)%aqu_link > 0) THEN Lines 170-191
 171 iaq = sd_ch(ich)%aqu_link
 172 iaq_ch = sd_ch(ich)%aqu_link_ch
IF (aq_ch(iaq)%ch(iaq_ch)%flo_fr > 0.) THEN Lines 173-190
 174 chsd_d(ich)%aqu_in = (aq_ch(iaq)%ch(iaq_ch)%flo_fr * aq_ch(iaq)%hd%flo) / 86400.
 175 chsd_d(ich)%aqu_in_mm = (aq_ch(iaq)%ch(iaq_ch)%flo_fr * aq_ch(iaq)%hd%flo) / (10. * ob(icmd)%area_ha)
 176 ht1 = ht1 + aq_ch(iaq)%ch(iaq_ch)%flo_fr * aq_ch(iaq)%hd
 189 aq_ch(iaq)%ch(iaq_ch)%flo_fr = 0.
DO isalt=1,cs_db%num_salts Lines 178-182
 179 gw_salt_in = aq_ch(iaq)%ch(iaq_ch)%flo_fr * aq_chcs(iaq)%hd(1)%salt(isalt) !kg
 180 chsalt_d(ich)%salt(isalt)%gw_in = gw_salt_in !kg
 181 hcs1%salt(isalt) = hcs1%salt(isalt) + gw_salt_in !kg
END DOLine 182
DO ics=1,cs_db%num_cs Lines 184-188
 185 gw_cs_in = aq_ch(iaq)%ch(iaq_ch)%flo_fr * aq_chcs(iaq)%hd(1)%cs(ics) !kg
 186 chcs_d(ich)%cs(ics)%gw_in = gw_cs_in !kg
 187 hcs1%cs(ics) = hcs1%cs(ics) + gw_cs_in !kg
END DOLine 188
END IFLine 190
END IFLine 191
IF (bsn_cc%gwflow.eq.1) THEN Lines 194-199
 195 call gwflow_gwsw(ich) !channel <--> groundwater
 196 call gwflow_canl(ich) !channel --> canal seepage
 197 call gwflow_tile(ich) !groundwater --> channel
 198 call gwflow_satx(ich) !groundwater --> channel
END IFLine 199
 202 chsd_d(ich)%flo_in = ht1%flo / 86400.     !flow for morphology output - m3/s
 203 chsd_d(ich)%flo_in_mm = ht1%flo / (10. * ob(icmd)%area_ha)   !flow in mm
 204 ch_in_d(ich) = ht1                        !set inflow om hydrograph
 205 ch_in_d(ich)%flo = ht1%flo / 86400.       !flow for om output - m3/s
 208 ht2 = hz
 209 peakrate = 0.
 210 hyd_rad = 0.
 211 timeint = 0.
 214 peakrate = 2. * ht1%flo / (1.5 * 60.)     !sd_chd(isd_db)%tc)
 215 peakrate = peakrate / 60.   !convert min to sec
IF (peakrate > 1.e-9) THEN Lines 216-354
 218 chside = sd_ch(ich)%chss
 219 b = sd_ch(ich)%chw
 220 sd_ch_vel(ich)%wid_btm = b
 221 sd_ch_vel(ich)%dep_bf = sd_ch(ich)%chd
 224 p = b + 2. * sd_ch(ich)%chd * Sqrt(chside * chside + 1.)
 225 a = b * sd_ch(ich)%chd + chside * sd_ch(ich)%chd * sd_ch(ich)%chd
 226 rh = a / p
 227 sd_ch_vel(ich)%area = a
 228 sd_ch_vel(ich)%vel_bf = Qman (a, rh, sd_ch(ich)%chn, sd_ch(ich)%chs)
IF (peakrate > sd_ch_vel(ich)%vel_bf) THEN Lines 230-354
 239 sd_ch(ich)%overbank = "ob"
 240 rcharea = sd_ch_vel(ich)%area
 241 rchdep = sd_ch(ich)%chd
 243 flo_rt = 0.
 244 rchdep = 0.
 245 valint = 1. / float(maxint)
 246 ivalint = 1
 247 tbase = 1.5 * 3600.     !sd_chd(isd_db)%tc * 60.   !hydrograph base time in s
 248 tb_pr = tbase
 249 iter = 0
 270 tbase = 1.5 * 3600.     !sd_chd(isd_db)%tc * 60.  !seconds
 271 vol_ovb = 0.5 * (peakrate - sd_ch_vel(ich)%vel_bf) * sd_ch_vel(ich)%vel_bf / peakrate * tbase
 272 vol_ovb = amin1(vol_ovb, ht1%flo)
 273 vol_ovb = peakrate - sd_ch_vel(ich)%vel_bf
 274 const = vol_ovb / peakrate
 275 ob(icmd)%hd(3) = const * ob(icmd)%hin
 278 ics = ob(icmd)%props2
 279 if (ics > 0) then   ! flood elements are specified - link to surface elements
 280 ht1 = hz
 281 ob_const = const
 287 ht1 = ht1 + ob(icmd)%hd(3)
IF (bsn_cc%gwflow.eq.1) THEN Lines 234-237
 235 flood_freq(ich) = 1 !flag to indicate the water is in the floodplain
 236 call gwflow_fpln(ich)
END IFLine 237
DO WHILE (flo_rt < peakrate) Lines 250-267
 251 rchdep = rchdep + 0.01
 252 rcharea = (sd_ch_vel(ich)%wid_btm + chside * rchdep) * rchdep
 253 p = sd_ch_vel(ich)%wid_btm + 2. * rchdep * Sqrt (1. + chside *chside)
 254 rh = rcharea / p
 255 flo_rt = Qman(rcharea, rh, sd_ch(ich)%chn, sd_ch(ich)%chs)
 265 iter = iter + 1
 266 if (iter > 100) exit
IF (flo_rt > valint * peakrate) THEN Lines 257-264
 258 hyd_rad(ivalint) = rh
 259 tb = (peakrate - flo_rt) * tbase / peakrate
 260 timeint(ivalint) = (tb_pr - tb) / 3600.   !sec to hr
 261 tb_pr = tb
 262 ivalint = ivalint + 1
 263 valint = float (ivalint) / float (maxint)
END IFLine 264
END DOLine 267
DO ii = 1, ch_sur(ics)%num Lines 282-284
 283 ht1 = ht1 + ch_sur(ics)%hd(ii)
END DOLine 284
IF (ht1%flo > ch_sur(ics)%flood_volmx(0)) THEN Lines 288-353
 290 sum_vol = 0.
 312 flood_dep = dep + ch_sur(ics)%dep(ic-1)
 334 rto = sum_vol / ht1%flo  !ensure water balance is maintained
DO ii = 1, ch_sur(ics)%num Lines 291-310
IF (ht1%flo < ch_sur(ics)%flood_volmx(ii)) THEN Lines 292-302
 294 a = sd_ch(ich)%chl * 1000. / sd_ch(ich)%chs
 295 b = ch_sur(ics)%wid(ii-1) * sd_ch(ich)%chl * 1000.
 296 c =  ch_sur(ics)%flood_volmx(ii-1) - ht1%flo
 297 xx = b ** 2 - 4. * a * c
 298 dep = (-b + sqrt(xx)) / (2. * a)
 299 dep = Max(0., dep)
 300 ic = ii
 301 exit
END IFLine 302
IF (ii == ch_sur(ics)%num) THEN Lines 303-309
 305 ic = ch_sur(ics)%num
 306 vol_overmx = ht1%flo - ch_sur(ics)%flood_volmx(ii)
 307 dep = ch_sur(ics)%dep(ic) + (vol_overmx / (sd_ch(ich)%chl *  &
 308 (sd_ch(ich)%chw + 2. * ch_sur(ics)%wid(ic))))
END IFLine 309
END DOLine 310
DO ii = 1, ch_sur(ics)%num Lines 314-332
 330 ch_sur(ics)%hd(ii)%flo = amin1 (ch_sur(ics)%hd(ii)%flo, ch_sur(ics)%flood_volmx(ii))
 331 sum_vol = sum_vol + ch_sur(ics)%hd(ii)%flo
IF (flood_dep < ch_sur(ics)%dep(ii-1)) THEN Lines 317-319
 319 ch_sur(ics)%hd(ii)%flo = 0.
END IFLine 319
ELSE IF (flood_dep < ch_sur(ics)%dep(ii)) THEN Lines 320-323
 322 dep_e = flood_dep - ch_sur(ics)%dep(ii-1)
 323 ch_sur(ics)%hd(ii)%flo = dep_e ** 2 / sd_ch(ich)%chs * sd_ch(ich)%chl
END IF Line 323
ELSE Lines 324-329
 326 ch_sur(ics)%hd(ii)%flo = 2. * sd_ch(ich)%chw *             &
 327 (flood_dep - ch_sur(ics)%dep(ii)) + sd_ch(ich)%chw *     &
 328 (ch_sur(ics)%dep(ii) - ch_sur(ics)%dep(ii-1))
END IF Line 329
END DOLine 332
DO ii = 1, ch_sur(ics)%num Lines 335-352
 336 const = rto * ch_sur(ics)%hd(ii)%flo / ht1%flo
 337 ch_sur(ics)%hd(ii) = const * ht1
IF (ch_sur(ics)%obtyp(ii) == "hru") THEN Lines 339-342
 340 ihru = ch_sur(ics)%obtypno(ii)
 341 wet(ihru) = wet(ihru) + ch_sur(ics)%hd(ii)
END IFLine 342
IF (ch_sur(ics)%obtyp(ii) == "ru") THEN Lines 343-351
 344 iru = ch_sur(ics)%obtypno(ii)
DO ielem = 1, ru_def(iru)%num_tot Lines 345-350
 346 ise = ru_def(iru)%num(ielem)
 348 ihru = ru_elem(ise)%obtypno
 349 wet(ihru) = wet(ihru) + ru_elem(ise)%frac * ch_sur(ics)%hd(ii)
END DOLine 350
END IFLine 351
END DOLine 352
END IFLine 353
END IFLine 354
END IFLine 354
ELSE Lines 355-390
 361 sd_ch(ich)%overbank = "ib"
 362 ob(icmd)%hd(3) = hz
 363 ob_const = 1.
 364 flo_rt = 0.
 365 rchdep = 0.
 366 sumtime = 0.
 367 valint = 1. / float(maxint)
 368 ivalint = 1
 369 tbase = 1.5 * 3600.     !sd_chd(isd_db)%tc * 60.   !hydrograph base time in s
 370 tb_pr = tbase
 389 timeint = timeint / sumtime
DO WHILE (flo_rt < peakrate) Lines 371-388
 372 rchdep = rchdep + 0.01
 373 rcharea = (sd_ch_vel(ich)%wid_btm + chside * rchdep) * rchdep
 374 p = sd_ch_vel(ich)%wid_btm + 2. * rchdep * Sqrt(1. + chside * chside)
 375 rh = rcharea / p
 377 flo_rt = Qman(rcharea, rh, sd_ch(ich)%chn, sd_ch(ich)%chs)
IF (flo_rt > valint * peakrate) THEN Lines 379-387
 380 hyd_rad(ivalint) = rh
 381 tb = (peakrate - flo_rt) * tbase / peakrate
 382 timeint(ivalint) = (tb_pr - tb) / 3600.   !sec to hr
 383 sumtime = sumtime + timeint(ivalint)
 384 tb_pr = tb
 385 ivalint = ivalint + 1
 386 valint = float (ivalint) / float(maxint)
END IFLine 387
END DOLine 388
END IF Line 390
 394 pr_ratio = (sd_ch(ich)%chl - sd_ch(ich)%hc_len / 1000.) / sd_ch(ich)%chl
 395 pr_ratio = Max(pr_ratio, 0.)
 420 pk_rto = 0.2 + 0.5 / 250. * ob(icmd)%area_ha
 421 pk_rto = amin1 (1., pk_rto)
 422 peakrate = ht1%flo / 86400. / pk_rto    !m3/s
 425 call rcurv_interp_flo (ich, peakrate)
 428 qcms = peakrate
 429 vel = qcms / rcurv%xsec_area
 431 cla = sd_ch(ich)%ch_clay
IF (cla - 7.123 > 0.001) THEN Lines 434-436
 436 cohes = -87. + (42.8 * cla) - (0.26 * cla ** 2) + (0.029 * cla ** 3)
END IFLine 436
ELSE Lines 437-439
 438 cohes = 0.
END IF Line 439
 440 cohes = max (0., cohes)
 441 veg = 0.    !Pa 200-10000.
IF (1.177 + 0.021 * cohes + veg > 0.001) THEN Lines 442-444
 444 vel_cr = log10(8.8 * rcurv%dep / 0.004) * (0.0004 * (14.79 + 0.021 * cohes + veg)) ** 0.5
END IFLine 444
ELSE Lines 445-447
 446 vel_cr = 0.
END IF Line 447
 450 rad_curv = ((12. * sd_ch(ich)%chw) * sd_ch(ich)%sinu ** 1.5) / (13. * (sd_ch(ich)%sinu -1.) ** 0.5)
 451 vel_bend = log10(rad_curv / sd_ch(ich)%chw)
 452 vel_bend = vel * (1.74 - 0.52 * log10(rad_curv / sd_ch(ich)%chw))
 453 vel_rch = 0.33 * vel_bend + 0.66 * vel
 454 b_coef = 2.2    ! 8.53 / (1. + exp((-29.11 + 1.8 * cla) ** 0.0248))
IF (vel_cr > 1.e-6 .and. rcurv%dep / sd_ch(ich)%chd > 0.25) THEN Lines 455-456
 456 ebank_m = 0.00233 * (vel_rch / vel_cr) ** b_coef    !bank erosion m/yr
END IFLine 456
ELSE Lines 457-459
 458 ebank_m = 0.
END IF Line 459
 463 arc_len = 0.33 *  (12. * sd_ch(ich)%chw) * sd_ch(ich)%sinu
 464 hyd_radius = rcurv%xsec_area / rcurv%wet_perim
 465 prot_len = 0.71 * (rchdep ** 1.1666) / sd_ch(ich)%chn
 466 sd_ch(ich)%cov = 0.2
 467 ebank_t = ebank_m * sd_ch(ich)%chd * sd_ch(ich)%cov * sd_ch(ich)%chl * 1000. * sd_ch(ich)%ch_bd
 468 ebank_t = 0.8 * ebank_t     !assume 80% wash load and 20% bed deposition
 469 ebank_t = max (0., ebank_t)
IF (sd_ch(ich)%chs > 0.000001) then !sd_ch(ich)%chseq) THEN Lines 472-482
 474 shear_btm_cr = sd_ch(ich)%d50
 475 shear_btm = 9800. * rcurv%dep * sd_ch(ich)%chs   !! Pa = N/m^2 * m * m/m
IF (shear_btm > shear_btm_cr) THEN Lines 477-481
 480 ebtm_t = 10. * ebtm_m * sd_ch(ich)%chw * sd_ch(ich)%chl * sd_ch(ich)%ch_bd
END IFLine 481
END IFLine 482
 485 sd_ch(ich)%chd = sd_ch(ich)%chd + ebtm_m !/ 100.
IF (sd_ch(ich)%chd < 0.) THEN Lines 486-489
 488 sd_ch(ich)%chd = 0.01
END IFLine 489
 492 bf_flow = sd_ch(ich)%bankfull_flo * ch_rcurv(ich)%elev(2)%flo_rate
IF (peakrate > bf_flow) THEN Lines 493-498
END IFLine 498
 501 sedout = ht1%sed - dep + hc_sed + ebank_t     !  + ebtm_t
 505 ht2%flo = ht1%flo
 506 idb = ob(icmd)%props
 507 jrch = ich
 508 vc = 0.001
IF (rcharea > 1.e-4 .and. ht1%flo > 1.e-4) THEN Lines 509-556
 510 vc = peakrate / rcharea
 512 rttime = sd_ch(ich)%chl * 1000. / (3600. * vc)
 513 if (time%step == 1) rt_delt = 1.
 516 ht3 = ht1
 518 ob(icmd)%hin_tot = ob(icmd)%hin_tot + ht1
 520 call hyd_convert_mass_to_conc (ht3)
 521 jnut = sd_dat(ich)%nut
 522 ben_area = sd_ch(ich)%chw * sd_ch(ich)%chl
 530 call ch_watqual4
 532 call hyd_convert_conc_to_mass (ht2)
 533 call hyd_convert_conc_to_mass (ch_stor(ich))
 541 ht2%sed = sedout
 544 ht2%sedp = ht2%sedp - sedp_dep   !MJW 2024
 545 ht2%orgn = ht2%orgn - orgn_dep   !MJW 2024
 547 ht2%orgn = ht2%orgn + ebank_t * sd_ch(ich)%n_conc
 548 ht2%sedp = ht2%sedp + ebank_t * sd_ch(ich)%p_conc
 549 ht2%solp = ht2%solp + ebank_t * sd_ch(ich)%p_bio
 552 call ch_rtpest
 555 call ch_rtpath
IF (ch_stor(ich)%flo > 0.001) THEN Lines 524-525
 525 call hyd_convert_mass_to_conc (ch_stor(ich))
END IFLine 525
ELSE Lines 526-528
 527 ch_stor(ich) = hz
END IF Line 528
END IFLine 556
 558 end if    ! peakrate > 0
 560 flo_ls = ht2%flo
 563 ch_wat_d(ich)%area_ha = sd_ch(ich)%chl * sd_ch(ich)%chw / 10.
 565 ch_wat_d(ich)%precip = 10. * wst(iwst)%weat%precip * ch_wat_d(ich)%area_ha
 566 ch_wat_d(ich)%evap = 10. * bsn_prm%evrch * wst(iwst)%weat%pet * ch_wat_d(ich)%area_ha
 567 ch_wat_d(ich)%seep = 10. * sd_ch(ich)%chk * ch_wat_d(ich)%area_ha      !k units to mm/d
 571 ht2%flo = ht2%flo + ch_wat_d(ich)%precip
IF (cs_db%num_salts > 0 .or. cs_db%num_cs > 0) THEN Lines 574-590
 575 hcs2 = hcs1 !set outflow to inflow
DO isalt=1,cs_db%num_salts Lines 576-582
IF (ht2%flo > 0) THEN Lines 577-578
 578 salt_conc(isalt) = (hcs2%salt(isalt) * 1000.) / ht2%flo !g/m3 = mg/L
END IFLine 578
ELSE Lines 579-581
 580 salt_conc(isalt) = 0.
END IF Line 581
END DOLine 582
DO ics=1,cs_db%num_cs Lines 583-589
IF (ht2%flo > 0) THEN Lines 584-585
 585 cs_conc(ics) = (hcs2%cs(ics) * 1000.) / ht2%flo !g/m3 = mg/L
END IFLine 585
ELSE Lines 586-588
 587 cs_conc(ics) = 0.
END IF Line 588
END DOLine 589
END IFLine 590
IF (ht2%flo < ch_wat_d(ich)%seep) THEN Lines 593-595
 594 ch_wat_d(ich)%seep = ht2%flo
 595 ht2%flo = 0.
END IFLine 595
ELSE Lines 596-598
 597 ht2%flo = ht2%flo - ch_wat_d(ich)%seep
END IF Line 598
DO isalt=1,cs_db%num_salts Lines 601-609
 602 seep_mass = salt_conc(isalt) * ch_wat_d(ich)%seep !g/m3 * m3 = g
 603 seep_mass = seep_mass / 1000. !kg
 607 hcs2%salt(isalt) = hcs2%salt(isalt) - seep_mass !kg
 608 chsalt_d(ich)%salt(isalt)%seep = seep_mass !kg (channel salt output)
IF (seep_mass > hcs2%salt(isalt)) THEN Lines 604-606
 605 seep_mass = hcs2%salt(isalt)
END IFLine 606
END DOLine 609
DO ics=1,cs_db%num_cs Lines 612-620
 613 seep_mass = cs_conc(ics) * ch_wat_d(ich)%seep !g/m3 * m3 = g
 614 seep_mass = seep_mass / 1000. !kg
 618 hcs2%cs(ics) = hcs2%cs(ics) - seep_mass !kg
 619 chcs_d(ich)%cs(ics)%seep = seep_mass !kg (channel constituent output)
IF (seep_mass > hcs2%cs(ics)) THEN Lines 615-617
 616 seep_mass = hcs2%cs(ics)
END IFLine 617
END DOLine 620
IF (ht2%flo < ch_wat_d(ich)%evap) THEN Lines 623-625
 624 ch_wat_d(ich)%evap = ht2%flo
 625 ht2%flo = 0.
END IFLine 625
ELSE Lines 626-628
 627 ht2%flo = ht2%flo - ch_wat_d(ich)%evap
END IF Line 628
IF (flo_ls > 1.e-6) THEN Lines 631-635
 632 rto = ht2%flo / flo_ls
 633 if (rto < 1.0) ht2 = rto * ht2
 634 ht2%flo = flo_ls
END IFLine 635
 638 ob(icmd)%hout_tot = ob(icmd)%hout_tot + ht2
 642 rt_delt = 1.
 643 det = 24.* rt_delt
 644 scoef = bsn_prm%scoef * det / (rttime + det)
 645 scoef = max (0., scoef)
 646 scoef = amin1 (1., scoef)
 647 frac = 1. - scoef
 654 ht3 = ht2 + ch_stor(ich)
 655 ht2 = scoef * ht3
 656 ch_stor(ich) = ht3 - ht2    !incoming + initial storage - outflow
IF (cs_db%num_salts > 0 .or. cs_db%num_cs > 0) THEN Lines 659-661
 660 hcs3 = hcs2 + ch_water(ich) !incoming + storage
END IFLine 661
 664 if (rttime > det) then      ! ht1 = incoming + storage
 666 hdsep2%flo_surq = scoef * ch_stor_hdsep(ich)%flo_surq
 667 hdsep2%flo_latq = scoef * ch_stor_hdsep(ich)%flo_latq
 668 hdsep2%flo_gwsw = scoef * ch_stor_hdsep(ich)%flo_gwsw
 669 hdsep2%flo_swgw = scoef * ch_stor_hdsep(ich)%flo_swgw
 670 hdsep2%flo_satex = scoef * ch_stor_hdsep(ich)%flo_satex
 671 hdsep2%flo_satexsw = scoef * ch_stor_hdsep(ich)%flo_satexsw
 672 hdsep2%flo_tile = scoef * ch_stor_hdsep(ich)%flo_tile
 673 ch_stor_hdsep(ich)%flo_surq = (frac*ch_stor_hdsep(ich)%flo_surq) + hdsep1%flo_surq
 674 ch_stor_hdsep(ich)%flo_latq = (frac*ch_stor_hdsep(ich)%flo_latq) + hdsep1%flo_latq
 675 ch_stor_hdsep(ich)%flo_gwsw = (frac*ch_stor_hdsep(ich)%flo_gwsw) + hdsep1%flo_gwsw
 676 ch_stor_hdsep(ich)%flo_swgw = (frac*ch_stor_hdsep(ich)%flo_swgw) + hdsep1%flo_swgw
 677 ch_stor_hdsep(ich)%flo_satex = (frac*ch_stor_hdsep(ich)%flo_satex) + hdsep1%flo_satex
 678 ch_stor_hdsep(ich)%flo_satexsw = (frac*ch_stor_hdsep(ich)%flo_satexsw) + hdsep1%flo_satexsw
 679 ch_stor_hdsep(ich)%flo_tile = (frac*ch_stor_hdsep(ich)%flo_tile) + hdsep1%flo_tile
 682 hdsep2%flo_surq = scoef * hdsep1%flo_surq
 683 hdsep2%flo_latq = scoef * hdsep1%flo_latq
 684 hdsep2%flo_gwsw = scoef * hdsep1%flo_gwsw
 685 hdsep2%flo_swgw = scoef * hdsep1%flo_swgw
 686 hdsep2%flo_satex = scoef * hdsep1%flo_satex
 687 hdsep2%flo_satexsw = scoef * hdsep1%flo_satexsw
 688 hdsep2%flo_tile = scoef * hdsep1%flo_tile
 689 hdsep2%flo_surq = hdsep2%flo_surq + ch_stor_hdsep(ich)%flo_surq
 690 hdsep2%flo_latq = hdsep2%flo_latq + ch_stor_hdsep(ich)%flo_latq
 691 hdsep2%flo_gwsw = hdsep2%flo_gwsw + ch_stor_hdsep(ich)%flo_gwsw
 692 hdsep2%flo_swgw = hdsep2%flo_swgw + ch_stor_hdsep(ich)%flo_swgw
 693 hdsep2%flo_satex = hdsep2%flo_satex + ch_stor_hdsep(ich)%flo_satex
 694 hdsep2%flo_satexsw = hdsep2%flo_satexsw + ch_stor_hdsep(ich)%flo_satexsw
 695 hdsep2%flo_tile = hdsep2%flo_tile + ch_stor_hdsep(ich)%flo_tile
 696 ch_stor_hdsep(ich)%flo_surq = frac * hdsep1%flo_surq
 697 ch_stor_hdsep(ich)%flo_latq = frac * hdsep1%flo_latq
 698 ch_stor_hdsep(ich)%flo_gwsw = frac * hdsep1%flo_gwsw
 699 ch_stor_hdsep(ich)%flo_swgw = frac * hdsep1%flo_swgw
 700 ch_stor_hdsep(ich)%flo_satex = frac * hdsep1%flo_satex
 701 ch_stor_hdsep(ich)%flo_satexsw = frac * hdsep1%flo_satexsw
 702 ch_stor_hdsep(ich)%flo_tile = frac * hdsep1%flo_tile
 704 ob(icmd)%hdsep%flo_surq = hdsep2%flo_surq
 705 ob(icmd)%hdsep%flo_latq = hdsep2%flo_latq
 706 ob(icmd)%hdsep%flo_gwsw = hdsep2%flo_gwsw
 707 ob(icmd)%hdsep%flo_swgw = hdsep2%flo_swgw
 708 ob(icmd)%hdsep%flo_satex = hdsep2%flo_satex
 709 ob(icmd)%hdsep%flo_satexsw = hdsep2%flo_satexsw
 710 ob(icmd)%hdsep%flo_tile = hdsep2%flo_tile
 712 hyd_sep_array(ich,1) = hdsep2%flo_surq / 86400.
 713 hyd_sep_array(ich,2) = hdsep2%flo_latq / 86400.
 714 hyd_sep_array(ich,3) = hdsep2%flo_gwsw / 86400.
 715 hyd_sep_array(ich,4) = hdsep2%flo_swgw / 86400.
 716 hyd_sep_array(ich,5) = hdsep2%flo_satex / 86400.
 717 hyd_sep_array(ich,6) = hdsep2%flo_satexsw / 86400.
 718 hyd_sep_array(ich,7) = 0. !hdsep2%flo_tile / 86400.
 722 ich = isdch
IF (ob(icmd)%ruleset /= "null" .and. ob(icmd)%ruleset /= "0") THEN Lines 725-730
 726 id = ob(icmd)%flo_dtbl
 727 d_tbl => dtbl_flo(id)
 728 call conditions (ich, id)
 729 call actions (ich, icmd, id)
END IFLine 730
IF (sd_ch(isdch)%wallo > 0) THEN Lines 733-735
 734 call wallo_control (sd_ch(isdch)%wallo)
END IFLine 735
 738 ob(icmd)%hd(1) = ht2
IF (cs_db%num_salts > 0) THEN Lines 741-746
DO isalt=1,cs_db%num_salts Lines 742-745
 743 hcs2%salt(isalt) = scoef * hcs3%salt(isalt)
 744 ch_water(ich)%salt(isalt) = hcs3%salt(isalt) - hcs2%salt(isalt)
END DOLine 745
END IFLine 746
IF (cs_db%num_cs > 0) THEN Lines 749-754
DO ics=1,cs_db%num_cs Lines 750-753
 751 hcs2%cs(ics) = scoef * hcs3%cs(ics)
 752 ch_water(ich)%cs(ics) = hcs3%cs(ics) - hcs2%cs(ics)
END DOLine 753
END IFLine 754
 757 ob(icmd)%hd(1)%temp = 5. + .75 * wst(iwst)%weat%tave
 758 ht2%temp = 5. + .75 * wst(iwst)%weat%tave
 759 ch_stor(isdch)%temp = 5. + .75 * wst(iwst)%weat%tave
IF (cs_db%num_pests > 0) THEN Lines 762-764
 763 obcs(icmd)%hd(1)%pest = hcs2%pest
END IFLine 764
 765 if (cs_db%num_salts > 0) then !rtb salt
 766 obcs(icmd)%hd(1)%salt = hcs2%salt
 768 if (cs_db%num_cs > 0) then !rtb cs
 769 obcs(icmd)%hd(1)%cs = hcs2%cs
 773 ch_out_d(isdch) = ob(icmd)%hd(1)                       !set outflow om hydrograph
 774 ch_out_d(isdch)%flo = ob(icmd)%hd(1)%flo / 86400.      !m3 -> m3/s
 777 chsd_d(isdch)%flo = ob(icmd)%hd(1)%flo / 86400.        !adjust if overbank flooding is moved to landscape
 778 chsd_d(isdch)%flo_mm = ob(icmd)%hd(1)%flo / (10. * ob(icmd)%area_ha)   !flow out in mm
 779 chsd_d(isdch)%peakr = peakrate
 780 chsd_d(isdch)%sed_in = ob(icmd)%hin%sed
 781 chsd_d(isdch)%sed_out = sedout
 782 chsd_d(isdch)%sed_stor = ch_stor(isdch)%sed
 783 chsd_d(isdch)%washld = washld
 784 chsd_d(isdch)%bedld = bedld
 785 chsd_d(isdch)%dep = dep
 786 chsd_d(isdch)%deg_btm = ebtm_t
 787 chsd_d(isdch)%deg_bank = ebank_t
 788 chsd_d(isdch)%hc_sed = hc_sed
 789 chsd_d(isdch)%width = sd_ch(isdch)%chw
 790 chsd_d(isdch)%depth = sd_ch(isdch)%chd
 791 chsd_d(isdch)%slope = sd_ch(isdch)%chs
 792 chsd_d(isdch)%deg_btm_m = ebtm_m
 793 chsd_d(isdch)%deg_bank_m = ebank_m
 794 chsd_d(isdch)%n_tot = ob(icmd)%hd(1)%orgn + ob(icmd)%hd(1)%no3 + ob(icmd)%hd(1)%nh3 + ob(icmd)%hd(1)%no2
 795 chsd_d(isdch)%p_tot = ob(icmd)%hd(1)%sedp + ob(icmd)%hd(1)%solp
 796 chsd_d(ich)%dep_bf = sd_ch_vel(ich)%dep_bf
 797 chsd_d(ich)%velav_bf = sd_ch_vel(ich)%vel_bf
DO ipest = 1, cs_db%num_pests Lines 800-813
 801 chpst_d(isdch)%pest(ipest)%tot_in = obcs(icmd)%hin(1)%pest(ipest)
 802 chpst_d(isdch)%pest(ipest)%sol_out = frsol * obcs(icmd)%hd(1)%pest(ipest)
 803 chpst_d(isdch)%pest(ipest)%sor_out = frsrb * obcs(icmd)%hd(1)%pest(ipest)
 804 chpst_d(isdch)%pest(ipest)%react = chpst%pest(ipest)%react
 805 chpst_d(isdch)%pest(ipest)%volat = chpst%pest(ipest)%volat
 806 chpst_d(isdch)%pest(ipest)%settle = chpst%pest(ipest)%settle
 807 chpst_d(isdch)%pest(ipest)%resus = chpst%pest(ipest)%resus
 808 chpst_d(isdch)%pest(ipest)%difus = chpst%pest(ipest)%difus
 809 chpst_d(isdch)%pest(ipest)%react_bot = chpst%pest(ipest)%react_bot
 810 chpst_d(isdch)%pest(ipest)%bury = chpst%pest(ipest)%bury
 811 chpst_d(isdch)%pest(ipest)%water = ch_water(ich)%pest(ipest)
 812 chpst_d(isdch)%pest(ipest)%benthic = ch_benthic(ich)%pest(ipest)
END DOLine 813
DO isalt = 1, cs_db%num_salts Lines 816-826
 817 chsalt_d(ich)%salt(isalt)%tot_in = hcs1%salt(isalt) + chsalt_d(ich)%salt(isalt)%gw_in !mass entering the channel (upstream + groundwater)
 818 chsalt_d(ich)%salt(isalt)%tot_out = hcs2%salt(isalt) !mass leaving the channel (for current day)
 819 chsalt_d(ich)%salt(isalt)%water = ch_water(ich)%salt(isalt) !mass stored in channel (for current day)
IF (ht2%flo > 0) THEN Lines 821-822
 822 chsalt_d(ich)%salt(isalt)%conc = (hcs2%salt(isalt) * 1000.) / ht2%flo !g/m3 = mg/L
END IFLine 822
ELSE Lines 823-825
 824 chsalt_d(ich)%salt(isalt)%conc = 0.
END IF Line 825
END DOLine 826
DO ics = 1, cs_db%num_cs Lines 829-838
 830 chcs_d(ich)%cs(ics)%tot_in = hcs1%cs(ics) + chcs_d(ich)%cs(ics)%gw_in !mass entering the channel (upstream + groundwater)
 831 chcs_d(ich)%cs(ics)%tot_out = hcs2%cs(ics) !kg mass leaving the channel (for current day)
 832 chcs_d(ich)%cs(ics)%water = ch_water(ich)%cs(ics) !kg mass stored in channel (for current day)
 833 if(ht2%flo > 0) then !concentration of outflow water
 834 chcs_d(ich)%cs(ics)%conc = (hcs2%cs(ics) * 1000.) / ht2%flo !g/m3 = mg/L
 836 chcs_d(ich)%cs(ics)%conc = 0.
END DOLine 838
 844 return
Allocations
n/a
Calls
Calls
Procedures called by this subroutine.
Local Variables
Type Visibility Attributes Name Initial
real, private :: flo_rt
integer, private :: isd_db
integer, private :: iob
integer, private :: idb
integer, private :: ihyd
integer, private :: ipest
integer, private :: isalt
integer, private :: ihru
integer, private :: iru
integer, private :: ise
integer, private :: ielem
integer, private :: id
integer, private :: iter
real, private :: ebtm_m
real, private :: ebank_m
real, private :: erode_bank_cut
real, private :: ebtm_t
real, private :: ebank_t
real, private :: sedout
real, private :: washld
real, private :: bedld
real, private :: dep
real, private :: sedp_dep
real, private :: orgn_dep
real, private :: hc_sed
real, private :: chside
real, private :: a
real, private :: b
real, private :: c
real, private :: p
real, private :: rh
real, private :: qman
real, private :: frac
real, private :: valint
integer, private :: ivalint
real, private :: tbase
real, private :: tb_pr
real, private :: tb
real, private :: vol_ovb
real, private :: const
integer, private :: ics
real, private :: ob_const
integer, private :: ii
real, private :: sum_vol
real, private :: xx
integer, private :: ic
real, private :: vol_overmx
real, private :: flood_dep
real, private :: dep_e
real, private :: rto
real, private :: sumtime
real, private :: vc
real, private :: pr_ratio
real, private :: shear_btm_cr
real, private :: shear_btm
real, private :: hc
integer, private :: max
integer, private :: iaq
integer, private :: iaq_ch
real, private :: det
real, private :: scoef
real, private :: flo_ls
real, private :: vel
real, private :: cohes
real, private :: vel_cr
real, private :: b_coef
real, private :: qcms
real, private :: veg
real, private :: rad_curv
real, private :: cla
real, private :: pk_rto
real, private :: vel_bend
real, private :: vel_rch
real, private :: arc_len
real, private :: hyd_radius
real, private :: prot_len
real, private :: gw_salt_in
real, private :: gw_cs_in
real, private :: seep_mass
real, private :: salt_conc
real, private :: cs_conc
real, private :: bf_flow
Call graph
sd_channel_control calls actions, amin1, ch_rtpath, ch_rtpest, ch_watqual4, cli_lapse, conditions, float, gwflow_canl, gwflow_fpln, gwflow_gwsw, gwflow_satx, gwflow_tile, hyd_convert_conc_to_mass, hyd_convert_mass_to_conc, rcurv_interp_flo, wallo_control