sd_channel_control3 – test-src-project
sd_channel_control3 Subroutine
432 statements
Source File
subroutine sd_channel_control3()
Uses
water_body_module
channel_data_module
ch_pesticide_module
channel_module
water_allocation_module
ch_salt_module
gwflow_module
conditional_module
basin_module
climate_module
channel_velocity_module
ch_cs_module
hydrograph_module
constituent_mass_module
sd_channel_module
time_module
Arguments
n/a
I/O
n/a
Outside Variables and Types
type(water_body) (1 attribute from water_body_module)
Attribute Name Description
ch_wat_d
real (8 attributes from ch_pesticide_module)
Attribute Name Description
frsol
none |fraction of pesticide in reach that is soluble
Read more…
frsrb
none |fraction of pesticide in reach that is sorbed
Read more…
rttime
hr |reach travel time
Read more…
ben_area
m2 |benthic area (bottom sediments)
Read more…
peakr
hyd_sep_array
wtemp
stream water temperature C
peakrate
type(ch_pesticide_output) (1 attribute from ch_pesticide_module)
Attribute Name Description
chpst_d
type (68 attributes from ch_pesticide_module)
Attribute Name Description
chpst%pest None
bsn_cc%qual2e None
bsn_cc%gwflow None
bsn_cc%lapse None
hd%flo None
ht1%temp None
ht1%solp None
ht1%sedp None
ht1%flo None
ht1%no3 None
ht1%orgn None
ht2%temp None
ht2%solp None
ht2%sedp None
ht2%flo None
ht2%sed None
ht2%no3 None
ht2%orgn None
ht3%flo None
fp_dep%solp None
fp_dep%sedp None
fp_dep%sed None
fp_dep%no3 None
fp_dep%orgn None
ch_dep%sed None
ch_dep%sedp None
ch_dep%orgn None
bank_ero%solp None
bank_ero%sedp None
bank_ero%sed None
bank_ero%no3 None
bank_ero%orgn None
bed_ero%solp None
bed_ero%sedp None
bed_ero%sed None
bed_ero%no3 None
bed_ero%orgn None
ch_trans%sedp None
ch_trans%solp None
ch_trans%no3 None
ch_trans%orgn None
hdsep1%flo_tile None
hdsep1%flo_surq None
hdsep1%flo_swgw None
hdsep1%flo_satexsw None
hdsep1%flo_gwsw None
hdsep1%flo_latq None
hdsep1%flo_satex None
hdsep2%flo_tile None
hdsep2%flo_surq None
hdsep2%flo_swgw None
hdsep2%flo_satexsw None
hdsep2%flo_gwsw None
hdsep2%flo_latq None
hdsep2%flo_satex None
cs_db%num_salts None
cs_db%num_tot None
cs_db%num_cs None
cs_db%num_pests None
hcs1%salt None
hcs1%cs None
hcs2%salt None
hcs2%cs None
hcs2%pest None
hcs3%salt None
hcs3%cs None
rcurv%ttime None
time%dtm None
integer (7 attributes from channel_module)
Attribute Name Description
jnut
units |description
Read more…
flood_freq
|
jrch
none |reach number
Read more…
iwst
|
isdch
|
icmd
|
ich
none |object number
Read more…
type(channel) (1 attribute from channel_module)
Attribute Name Description
ch
type(water_allocation) (1 attribute from water_allocation_module)
Attribute Name Description
wallo
dimension by water allocation objects
type(ch_salt_output) (1 attribute from ch_salt_module)
Attribute Name Description
chsalt_d
type(decision_table) (2 attributes from conditional_module)
Attribute Name Description
dtbl_flo
d_tbl
type(weather_daily) (1 attribute from climate_module)
Attribute Name Description
w
type(weather_station) (1 attribute from climate_module)
Attribute Name Description
wst
type(channel_velocity_parameters) (1 attribute from channel_velocity_module)
Attribute Name Description
sd_ch_vel
type(ch_cs_output) (1 attribute from ch_cs_module)
Attribute Name Description
chcs_d
type(hyd_output) (4 attributes from hydrograph_module)
Attribute Name Description
hz
ch_stor
channel storage - max bankfull
ch_in_d
ch_out_d
type(hyd_sep) (1 attribute from hydrograph_module)
Attribute Name Description
ch_stor_hdsep
type(object_connectivity) (1 attribute from hydrograph_module)
Attribute Name Description
ob
type(channel_aquifer_elements) (1 attribute from hydrograph_module)
Attribute Name Description
aq_ch
sorted by drainage area (smallest first)
type(constituent_mass) (3 attributes from constituent_mass_module)
Attribute Name Description
ch_water
ch_benthic
hin_csz
type(all_constituent_hydrograph) (1 attribute from constituent_mass_module)
Attribute Name Description
obcs
type(gw_load_hydrograph) (1 attribute from constituent_mass_module)
Attribute Name Description
aq_chcs
type(channel_sediment_budget_output) (2 attributes from sd_channel_module)
Attribute Name Description
ch_sed_bud
ch_sed_budz
type(swatdeg_datafiles) (1 attribute from sd_channel_module)
Attribute Name Description
sd_dat
type(swatdeg_channel_dynamic) (1 attribute from sd_channel_module)
Attribute Name Description
sd_ch
type(channel_rating_curve) (1 attribute from sd_channel_module)
Attribute Name Description
ch_rcurv
type(sd_ch_output) (1 attribute from sd_channel_module)
Attribute Name Description
chsd_d
!! Bang Comments
! nbs added 7-20-23 set ht1 to incoming daily hydrograph zero outgoing flow and sediment - ht2 zero daily in/out morphology and sediment budget output add water transfer adjust precip and temperature for elevation using lapse rates if connected to aquifer - add flow add aquifer flow to inflow set inflow hyds for printing zero outgoing flow and sediment - ht2 route constituents call mike winchell's new routine for pesticide routing
don't route constituents if flow is zero compute max flow depth and corresponding travel time during day compute channel water quality new nutrient channel transformations - overrides qual2e route constituents call mike winchell's new routine for pesticide routing
total outgoing to output to SWIFT route pathogens Variable Storage Coefficient method - sc=2dt/(2ttime+dt) - ttime=(in2+out1)/2 travel time > timestep -- then all incoming is stored and frac of stored is routed travel time < timestep -- route all stored and frac of incoming check decision table for flow control - water diversion check decision table for water allocation set outflow hyd to ht2 after diverting water calculate stream temperature set constituents for routing output channel organic-mineral channel sediment budget for output channel nutrient budget for output output channel morphology output flow to channel morphology set pesticide output variables set values for recharge hydrograph - should be trans losses
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure.
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
 112 ich = isdch
 113 isd_db = sd_dat(ich)%hyd
 114 iwst = ob(icmd)%wst
 117 if(bsn_cc%gwflow.eq.1) flood_freq(ich) = 0
 120 ht1 = ob(icmd)%hin
 123 ht2 = hz
 124 obcs(icmd)%hd(:) = hin_csz
 127 ch_sed_bud(ich) = ch_sed_budz
IF (ob(icmd)%trans%flo > 1.e-6) THEN Lines 132-135
 133 ht1 = ht1 + ob(icmd)%trans
 134 ob(icmd)%trans = hz
END IFLine 135
IF (cs_db%num_tot > 0) THEN Lines 138-140
 139 hcs1 = obcs(icmd)%hin(1)
END IFLine 140
 142 chsd_d(ich)%flo_in = ht1%flo / 86400.     !flow for morphology output
 143 ch_in_d(ich) = ht1                        !set inflow om hydrograph
 144 ch_in_d(ich)%flo = ht1%flo / 86400.       !flow for om output
 147 hdsep1%flo_surq = ob(icmd)%hdsep_in%flo_surq
 148 hdsep1%flo_latq = ob(icmd)%hdsep_in%flo_latq
 149 hdsep1%flo_gwsw = ob(icmd)%hdsep_in%flo_gwsw
 150 hdsep1%flo_swgw = ob(icmd)%hdsep_in%flo_swgw
 151 hdsep1%flo_satex = ob(icmd)%hdsep_in%flo_satex
 152 hdsep1%flo_satexsw = ob(icmd)%hdsep_in%flo_satexsw
 153 hdsep1%flo_tile = ob(icmd)%hdsep_in%flo_tile
 157 w = wst(iwst)%weat
 158 if (bsn_cc%lapse == 1) call cli_lapse
 159 wst(iwst)%weat = w
 160 ht1%temp = 5.0 + 0.75 * wst(iwst)%weat%tave
 161 wtemp = 5.0 + 0.75 * wst(iwst)%weat%tave
IF (sd_ch(ich)%msk%nsteps == 1) THEN Lines 163-165
 164 ob(icmd)%tsin(1) = ht1%flo
END IFLine 165
IF (sd_ch(ich)%aqu_link > 0) THEN Lines 168-193
 169 iaq = sd_ch(ich)%aqu_link
 170 iaq_ch = sd_ch(ich)%aqu_link_ch
IF (aq_ch(iaq)%ch(iaq_ch)%flo_fr > 0.) THEN Lines 171-192
 172 chsd_d(ich)%aqu_in = (aq_ch(iaq)%ch(iaq_ch)%flo_fr * aq_ch(iaq)%hd%flo) / 86400.
 173 chsd_d(ich)%aqu_in_mm = (aq_ch(iaq)%ch(iaq_ch)%flo_fr * aq_ch(iaq)%hd%flo) / (10. * ob(icmd)%area_ha)
 175 aqu_inflo = aq_ch(iaq)%ch(iaq_ch)%flo_fr * aq_ch(iaq)%hd%flo
 176 rto = aqu_inflo / ht1%flo
 177 ob(icmd)%tsin(:) = (1. + rto) * ob(icmd)%tsin(:)
 178 ht1 = ht1 + aq_ch(iaq)%ch(iaq_ch)%flo_fr * aq_ch(iaq)%hd
 191 aq_ch(iaq)%ch(iaq_ch)%flo_fr = 0.
DO isalt=1,cs_db%num_salts Lines 180-184
 181 gw_salt_in = aq_ch(iaq)%ch(iaq_ch)%flo_fr * aq_chcs(iaq)%hd(1)%salt(isalt) !kg
 182 chsalt_d(ich)%salt(isalt)%gw_in = gw_salt_in !kg
 183 hcs1%salt(isalt) = hcs1%salt(isalt) + gw_salt_in !kg
END DOLine 184
DO ics=1,cs_db%num_cs Lines 186-190
 187 gw_cs_in = aq_ch(iaq)%ch(iaq_ch)%flo_fr * aq_chcs(iaq)%hd(1)%cs(ics) !kg
 188 chcs_d(ich)%cs(ics)%gw_in = gw_cs_in !kg
 189 hcs1%cs(ics) = hcs1%cs(ics) + gw_cs_in !kg
END DOLine 190
END IFLine 192
END IFLine 193
IF (bsn_cc%gwflow.eq.1) THEN Lines 196-201
 197 call gwflow_gwsw(ich) !channel <--> groundwater
 198 call gwflow_canl(ich) !channel --> canal seepage
 199 call gwflow_tile(ich) !groundwater --> channel
 200 call gwflow_satx(ich) !groundwater --> channel
END IFLine 201
 204 chsd_d(ich)%flo_in = ht1%flo / 86400.     !flow for morphology output - m3/s
 205 chsd_d(ich)%flo_in_mm = ht1%flo / (10. * ob(icmd)%area_ha)   !flow in mm
 206 ch_in_d(ich) = ht1                        !set inflow om hydrograph
 207 ch_in_d(ich)%flo = ht1%flo / 86400.       !flow for om output - m3/s
IF (cs_db%num_tot > 0) THEN Lines 210-212
 211 hcs1 = obcs(icmd)%hin(1)
END IFLine 212
 214 ht2 = hz
 217 call sd_channel_sediment3
 220 call ch_rtmusk
 223 call ch_rtpest
 226 call ch_rtpath
IF (cs_db%num_salts > 0 .or. cs_db%num_cs > 0) THEN Lines 229-245
 230 hcs2 = hcs1 !set outflow to inflow
DO isalt=1,cs_db%num_salts Lines 231-237
IF (ht2%flo > 0) THEN Lines 232-233
 233 salt_conc(isalt) = (hcs2%salt(isalt) * 1000.) / ht2%flo !g/m3 = mg/L
END IFLine 233
ELSE Lines 234-236
 235 salt_conc(isalt) = 0.
END IF Line 236
END DOLine 237
DO ics=1,cs_db%num_cs Lines 238-244
IF (ht2%flo > 0) THEN Lines 239-240
 240 cs_conc(ics) = (hcs2%cs(ics) * 1000.) / ht2%flo !g/m3 = mg/L
END IFLine 240
ELSE Lines 241-243
 242 cs_conc(ics) = 0.
END IF Line 243
END DOLine 244
END IFLine 245
IF (ht1%flo > 1.e-6) THEN Lines 248-340
 250 jnut = sd_dat(ich)%nut
 251 ben_area = sd_ch(ich)%chw * sd_ch(ich)%chl
 254 inflo_rate = ht3%flo / 86400.
 255 call rcurv_interp_flo (jrch, inflo_rate)
 258 call ch_watqual4
 299 call ch_rtpest
 307 ob(icmd)%hout_tot = ob(icmd)%hout_tot + ht2
 309 call ch_rtpath
 320 end if        ! ht1%flo > 0.
 323 if (rttime > time%dtm / 60.) then      ! travel time > routing time step (hours)
 325 scoef = 24. / (ch_rcurv(jrch)%in2%ttime + ch_rcurv(jrch)%out1%ttime + 24.)
 327 hdsep2%flo_surq = scoef * ch_stor_hdsep(ich)%flo_surq
 328 hdsep2%flo_latq = scoef * ch_stor_hdsep(ich)%flo_latq
 329 hdsep2%flo_gwsw = scoef * ch_stor_hdsep(ich)%flo_gwsw
 330 hdsep2%flo_swgw = scoef * ch_stor_hdsep(ich)%flo_swgw
 331 hdsep2%flo_satex = scoef * ch_stor_hdsep(ich)%flo_satex
 332 hdsep2%flo_satexsw = scoef * ch_stor_hdsep(ich)%flo_satexsw
 333 hdsep2%flo_tile = scoef * ch_stor_hdsep(ich)%flo_tile
 334 ch_stor_hdsep(ich)%flo_surq = (frac*ch_stor_hdsep(ich)%flo_surq) + hdsep1%flo_surq
 335 ch_stor_hdsep(ich)%flo_latq = (frac*ch_stor_hdsep(ich)%flo_latq) + hdsep1%flo_latq
 336 ch_stor_hdsep(ich)%flo_gwsw = (frac*ch_stor_hdsep(ich)%flo_gwsw) + hdsep1%flo_gwsw
 337 ch_stor_hdsep(ich)%flo_swgw = (frac*ch_stor_hdsep(ich)%flo_swgw) + hdsep1%flo_swgw
 338 ch_stor_hdsep(ich)%flo_satex = (frac*ch_stor_hdsep(ich)%flo_satex) + hdsep1%flo_satex
 339 ch_stor_hdsep(ich)%flo_satexsw = (frac*ch_stor_hdsep(ich)%flo_satexsw) + hdsep1%flo_satexsw
 340 ch_stor_hdsep(ich)%flo_tile = (frac*ch_stor_hdsep(ich)%flo_tile) + hdsep1%flo_tile
IF (bsn_cc%qual2e == 1) THEN Lines 260-275
 262 conc_chng = 1. - exp(-sd_ch(ich)%n_sol_part * rcurv%ttime)
 263 ch_trans%orgn = conc_chng * ht1%orgn
 264 ch_trans%orgn = Min (ht1%no3, ch_trans%orgn)
 265 ch_trans%no3 = ch_trans%orgn
 266 ht2%orgn = ht1%orgn + ch_trans%orgn
 267 ht2%no3 = ht1%no3 - ch_trans%no3
 269 conc_chng = 1. - exp(-sd_ch(ich)%p_sol_part * rcurv%ttime)
 270 ch_trans%sedp = conc_chng * ht1%sedp
 271 ch_trans%sedp = Min (ht1%solp, ch_trans%sedp)
 272 ch_trans%solp = ch_trans%sedp
 273 ht2%sedp = ht1%sedp + ch_trans%sedp
 274 ht2%solp = ht1%solp - ch_trans%solp
END IFLine 275
DO isalt=1,cs_db%num_salts Lines 278-286
 279 seep_mass = salt_conc(isalt) * ch_wat_d(ich)%seep !g/m3 * m3 = g
 280 seep_mass = seep_mass / 1000. !kg
 284 hcs2%salt(isalt) = hcs2%salt(isalt) - seep_mass !kg
 285 chsalt_d(ich)%salt(isalt)%seep = seep_mass !kg (channel salt output)
IF (seep_mass > hcs2%salt(isalt)) THEN Lines 281-283
 282 seep_mass = hcs2%salt(isalt)
END IFLine 283
END DOLine 286
DO ics=1,cs_db%num_cs Lines 289-297
 290 seep_mass = cs_conc(ics) * ch_wat_d(ich)%seep !g/m3 * m3 = g
 291 seep_mass = seep_mass / 1000. !kg
 295 hcs2%cs(ics) = hcs2%cs(ics) - seep_mass !kg
 296 chcs_d(ich)%cs(ics)%seep = seep_mass !kg (channel constituent output)
IF (seep_mass > hcs2%cs(ics)) THEN Lines 292-294
 293 seep_mass = hcs2%cs(ics)
END IFLine 294
END DOLine 297
IF (cs_db%num_pests > 0) THEN Lines 302-304
 303 obcs(icmd)%hd(1)%pest = hcs2%pest
END IFLine 304
IF (cs_db%num_salts > 0 .or. cs_db%num_cs > 0) THEN Lines 316-318
 317 hcs3 = hcs2 + ch_water(ich) !incoming + storage
END IFLine 318
END IFLine 340
ELSE Lines 341-364
 343 hdsep2%flo_surq = scoef * hdsep1%flo_surq
 344 hdsep2%flo_latq = scoef * hdsep1%flo_latq
 345 hdsep2%flo_gwsw = scoef * hdsep1%flo_gwsw
 346 hdsep2%flo_swgw = scoef * hdsep1%flo_swgw
 347 hdsep2%flo_satex = scoef * hdsep1%flo_satex
 348 hdsep2%flo_satexsw = scoef * hdsep1%flo_satexsw
 349 hdsep2%flo_tile = scoef * hdsep1%flo_tile
 350 hdsep2%flo_surq = hdsep2%flo_surq + ch_stor_hdsep(ich)%flo_surq
 351 hdsep2%flo_latq = hdsep2%flo_latq + ch_stor_hdsep(ich)%flo_latq
 352 hdsep2%flo_gwsw = hdsep2%flo_gwsw + ch_stor_hdsep(ich)%flo_gwsw
 353 hdsep2%flo_swgw = hdsep2%flo_swgw + ch_stor_hdsep(ich)%flo_swgw
 354 hdsep2%flo_satex = hdsep2%flo_satex + ch_stor_hdsep(ich)%flo_satex
 355 hdsep2%flo_satexsw = hdsep2%flo_satexsw + ch_stor_hdsep(ich)%flo_satexsw
 356 hdsep2%flo_tile = hdsep2%flo_tile + ch_stor_hdsep(ich)%flo_tile
 357 ch_stor_hdsep(ich)%flo_surq = frac * hdsep1%flo_surq
 358 ch_stor_hdsep(ich)%flo_latq = frac * hdsep1%flo_latq
 359 ch_stor_hdsep(ich)%flo_gwsw = frac * hdsep1%flo_gwsw
 360 ch_stor_hdsep(ich)%flo_swgw = frac * hdsep1%flo_swgw
 361 ch_stor_hdsep(ich)%flo_satex = frac * hdsep1%flo_satex
 362 ch_stor_hdsep(ich)%flo_satexsw = frac * hdsep1%flo_satexsw
 363 ch_stor_hdsep(ich)%flo_tile = frac * hdsep1%flo_tile
END IF Line 364
 365 ob(icmd)%hdsep%flo_surq = hdsep2%flo_surq
 366 ob(icmd)%hdsep%flo_latq = hdsep2%flo_latq
 367 ob(icmd)%hdsep%flo_gwsw = hdsep2%flo_gwsw
 368 ob(icmd)%hdsep%flo_swgw = hdsep2%flo_swgw
 369 ob(icmd)%hdsep%flo_satex = hdsep2%flo_satex
 370 ob(icmd)%hdsep%flo_satexsw = hdsep2%flo_satexsw
 371 ob(icmd)%hdsep%flo_tile = hdsep2%flo_tile
 373 hyd_sep_array(ich,1) = hdsep2%flo_surq / 86400.
 374 hyd_sep_array(ich,2) = hdsep2%flo_latq / 86400.
 375 hyd_sep_array(ich,3) = hdsep2%flo_gwsw / 86400.
 376 hyd_sep_array(ich,4) = hdsep2%flo_swgw / 86400.
 377 hyd_sep_array(ich,5) = hdsep2%flo_satex / 86400.
 378 hyd_sep_array(ich,6) = hdsep2%flo_satexsw / 86400.
 379 hyd_sep_array(ich,7) = 0. !hdsep2%flo_tile / 86400.
 383 ich = isdch
IF (ob(icmd)%ruleset /= "null" .and. ob(icmd)%ruleset /= "0") THEN Lines 386-391
 387 id = ob(icmd)%flo_dtbl
 388 d_tbl => dtbl_flo(id)
 389 call conditions (ich, id)
 390 call actions (ich, icmd, id)
END IFLine 391
IF (sd_ch(isdch)%wallo > 0) THEN Lines 394-396
 395 call wallo_control (sd_ch(isdch)%wallo)
END IFLine 396
IF (ob(icmd)%hyd_flo(1,1) > 1.e-6) THEN Lines 398-402
IF (ht2%flo / ob(icmd)%hyd_flo(1,1) > 1.5) THEN Lines 399-401
 400 a = 1.
END IFLine 401
END IFLine 402
 405 ob(icmd)%hd(1) = ht2
IF (cs_db%num_salts > 0) THEN Lines 408-413
DO isalt=1,cs_db%num_salts Lines 409-412
 410 hcs2%salt(isalt) = scoef * hcs3%salt(isalt)
 411 ch_water(ich)%salt(isalt) = hcs3%salt(isalt) - hcs2%salt(isalt)
END DOLine 412
END IFLine 413
IF (cs_db%num_cs > 0) THEN Lines 416-421
DO ics=1,cs_db%num_cs Lines 417-420
 418 hcs2%cs(ics) = scoef * hcs3%cs(ics)
 419 ch_water(ich)%cs(ics) = hcs3%cs(ics) - hcs2%cs(ics)
END DOLine 420
END IFLine 421
 424 ob(icmd)%hd(1)%temp = 5. + .75 * wst(iwst)%weat%tave
 425 ht2%temp = 5. + .75 * wst(iwst)%weat%tave
 426 ch_stor(isdch)%temp = 5. + .75 * wst(iwst)%weat%tave
IF (cs_db%num_pests > 0) THEN Lines 429-431
 430 obcs(icmd)%hd(1)%pest = hcs2%pest
END IFLine 431
 432 if (cs_db%num_salts > 0) then !rtb salt
 433 obcs(icmd)%hd(1)%salt = hcs2%salt
 435 if (cs_db%num_cs > 0) then !rtb cs
 436 obcs(icmd)%hd(1)%cs = hcs2%cs
 440 ch_out_d(isdch) = ob(icmd)%hd(1)                       !set outflow om hydrograph
 441 ch_out_d(isdch)%flo = ob(icmd)%hd(1)%flo / 86400.      !m3 -> m3/s
 444 ch_sed_bud(ich)%in_sed = ch_in_d(ich)%sed
 445 ch_sed_bud(ich)%out_sed = ht2%sed
 446 ch_sed_bud(ich)%fp_dep = fp_dep%sed
 447 ch_sed_bud(ich)%ch_dep = ch_dep%sed
 448 ch_sed_bud(ich)%bank_ero = bank_ero%sed
 449 ch_sed_bud(isdch)%fp_dep = fp_dep%sed
 450 ch_sed_bud(isdch)%ch_dep = ch_dep%sed
 451 ch_sed_bud(isdch)%bank_ero = bank_ero%sed
 454 ch_sed_bud(ich)%in_no3 = ch_in_d(ich)%no3
 455 ch_sed_bud(ich)%in_orgn = ch_in_d(ich)%orgn
 456 ch_sed_bud(ich)%out_no3 = ht2%no3
 457 ch_sed_bud(ich)%out_orgn = ht2%orgn
 458 ch_sed_bud(ich)%fp_no3 = fp_dep%no3
 459 ch_sed_bud(ich)%bank_no3 = bank_ero%no3
 460 ch_sed_bud(ich)%bed_no3 = bed_ero%no3
 461 ch_sed_bud(ich)%fp_orgn = fp_dep%orgn
 462 ch_sed_bud(ich)%ch_orgn = ch_dep%orgn
 463 ch_sed_bud(ich)%bank_orgn = bank_ero%orgn
 464 ch_sed_bud(ich)%bed_orgn = bed_ero%orgn
 465 ch_sed_bud(ich)%in_solp = ch_in_d(ich)%solp
 466 ch_sed_bud(ich)%in_orgp = ch_in_d(ich)%sedp
 467 ch_sed_bud(ich)%out_solp = ht2%solp
 468 ch_sed_bud(ich)%out_orgp = ht2%sedp
 469 ch_sed_bud(ich)%fp_solp = fp_dep%solp
 470 ch_sed_bud(ich)%bank_solp = bank_ero%solp
 471 ch_sed_bud(ich)%bed_solp = bed_ero%solp
 472 ch_sed_bud(ich)%fp_orgp = fp_dep%sedp
 473 ch_sed_bud(ich)%ch_orgp = ch_dep%sedp
 474 ch_sed_bud(ich)%bank_orgp = bank_ero%sedp
 475 ch_sed_bud(ich)%bed_orgp = bed_ero%sedp
 476 ch_sed_bud(ich)%no3_orgn = ch_trans%no3
 477 ch_sed_bud(ich)%solp_orgp = ch_trans%solp
 480 chsd_d(isdch)%flo = ob(icmd)%hd(1)%flo / 86400.        !adjust if overbank flooding is moved to landscape
 481 chsd_d(isdch)%flo_mm = ob(icmd)%hd(1)%flo / (10. * ob(icmd)%area_ha)   !flow out in mm
 482 chsd_d(isdch)%peakr = peakrate
 483 chsd_d(isdch)%sed_in = ob(icmd)%hin%sed
 484 chsd_d(isdch)%sed_out = ob(icmd)%hd(1)%sed
 485 chsd_d(isdch)%sed_stor = ch_stor(isdch)%sed
 486 ch_sed_bud(isdch)%bed_ero = bed_ero%sed
 487 chsd_d(isdch)%washld = ob(icmd)%hd(1)%sed
 488 chsd_d(isdch)%bedld = ch_dep%sed
 489 chsd_d(isdch)%dep = fp_dep%sed
 490 chsd_d(isdch)%deg_btm = bed_ero%sed
 491 chsd_d(isdch)%deg_bank = bank_ero%sed
 492 chsd_d(isdch)%hc_sed = hc_sed
 493 chsd_d(isdch)%width = sd_ch(isdch)%chw
 494 chsd_d(isdch)%depth = sd_ch(isdch)%chd
 495 chsd_d(isdch)%slope = sd_ch(isdch)%chs
 496 chsd_d(isdch)%deg_btm_m = ebtm_m
 497 chsd_d(isdch)%deg_bank_m = ebank_m
 498 chsd_d(isdch)%n_tot = ob(icmd)%hd(1)%orgn + ob(icmd)%hd(1)%no3 + ob(icmd)%hd(1)%nh3 + ob(icmd)%hd(1)%no2
 499 chsd_d(isdch)%p_tot = ob(icmd)%hd(1)%sedp + ob(icmd)%hd(1)%solp
 500 chsd_d(ich)%dep_bf = sd_ch_vel(ich)%dep_bf
 501 chsd_d(ich)%velav_bf = sd_ch_vel(ich)%vel_bf
 502 ch_out_d(ich) = ob(icmd)%hd(1)                       !set outflow om hydrograph
 503 ch_out_d(ich)%flo = ob(icmd)%hd(1)%flo / 86400.      !m3 -> m3/s
 506 chsd_d(ich)%flo = ob(icmd)%hd(1)%flo / 86400.        !adjust if overbank flooding is moved to landscape
 507 chsd_d(ich)%flo_mm = ob(icmd)%hd(1)%flo / (10. * ob(icmd)%area_ha)   !flow out in mm
 508 chsd_d(ich)%peakr = peakrate
DO ipest = 1, cs_db%num_pests Lines 511-524
 512 chpst_d(isdch)%pest(ipest)%tot_in = obcs(icmd)%hin(1)%pest(ipest)
 513 chpst_d(isdch)%pest(ipest)%sol_out = frsol * obcs(icmd)%hd(1)%pest(ipest)
 514 chpst_d(isdch)%pest(ipest)%sor_out = frsrb * obcs(icmd)%hd(1)%pest(ipest)
 515 chpst_d(isdch)%pest(ipest)%react = chpst%pest(ipest)%react
 516 chpst_d(isdch)%pest(ipest)%volat = chpst%pest(ipest)%volat
 517 chpst_d(isdch)%pest(ipest)%settle = chpst%pest(ipest)%settle
 518 chpst_d(isdch)%pest(ipest)%resus = chpst%pest(ipest)%resus
 519 chpst_d(isdch)%pest(ipest)%difus = chpst%pest(ipest)%difus
 520 chpst_d(isdch)%pest(ipest)%react_bot = chpst%pest(ipest)%react_bot
 521 chpst_d(isdch)%pest(ipest)%bury = chpst%pest(ipest)%bury
 522 chpst_d(isdch)%pest(ipest)%water = ch_water(ich)%pest(ipest)
 523 chpst_d(isdch)%pest(ipest)%benthic = ch_benthic(ich)%pest(ipest)
END DOLine 524
DO isalt = 1, cs_db%num_salts Lines 527-537
 528 chsalt_d(ich)%salt(isalt)%tot_in = hcs1%salt(isalt) + chsalt_d(ich)%salt(isalt)%gw_in !mass entering the channel (upstream + groundwater)
 529 chsalt_d(ich)%salt(isalt)%tot_out = hcs2%salt(isalt) !mass leaving the channel (for current day)
 530 chsalt_d(ich)%salt(isalt)%water = ch_water(ich)%salt(isalt) !mass stored in channel (for current day)
IF (ht2%flo > 0) THEN Lines 532-533
 533 chsalt_d(ich)%salt(isalt)%conc = (hcs2%salt(isalt) * 1000.) / ht2%flo !g/m3 = mg/L
END IFLine 533
ELSE Lines 534-536
 535 chsalt_d(ich)%salt(isalt)%conc = 0.
END IF Line 536
END DOLine 537
DO ics = 1, cs_db%num_cs Lines 540-549
 541 chcs_d(ich)%cs(ics)%tot_in = hcs1%cs(ics) + chcs_d(ich)%cs(ics)%gw_in !mass entering the channel (upstream + groundwater)
 542 chcs_d(ich)%cs(ics)%tot_out = hcs2%cs(ics) !kg mass leaving the channel (for current day)
 543 chcs_d(ich)%cs(ics)%water = ch_water(ich)%cs(ics) !kg mass stored in channel (for current day)
 544 if(ht2%flo > 0) then !concentration of outflow water
 545 chcs_d(ich)%cs(ics)%conc = (hcs2%cs(ics) * 1000.) / ht2%flo !g/m3 = mg/L
 547 chcs_d(ich)%cs(ics)%conc = 0.
END DOLine 549
 555 return
Allocations
n/a
Calls
Calls
Procedures called by this subroutine.
Local Variables
Type Visibility Attributes Name Initial
real, private :: flo_rt
integer, private :: isd_db
integer, private :: iob
integer, private :: idb
integer, private :: ihyd
integer, private :: ipest
integer, private :: isalt
integer, private :: ihru
integer, private :: iru
integer, private :: ise
integer, private :: ielem
integer, private :: id
integer, private :: iter
real, private :: ebtm_m
real, private :: ebank_m
real, private :: erode_bank_cut
real, private :: ebtm_t
real, private :: ebank_t
real, private :: sedout
real, private :: washld
real, private :: bedld
real, private :: dep
real, private :: hc_sed
real, private :: chside
real, private :: a
real, private :: b
real, private :: c
real, private :: p
real, private :: rh
real, private :: qman
real, private :: frac
real, private :: valint
integer, private :: ivalint
real, private :: tbase
real, private :: tb_pr
real, private :: tb
real, private :: vol_ovb
real, private :: const
integer, private :: ics
real, private :: ob_const
integer, private :: ii
real, private :: sum_vol
real, private :: xx
integer, private :: ic
real, private :: vol_overmx
real, private :: flood_dep
real, private :: dep_e
real, private :: rto
real, private :: sumtime
real, private :: vc
real, private :: pr_ratio
real, private :: shear_btm_cr
real, private :: shear_btm
real, private :: hc
integer, private :: max
integer, private :: iaq
integer, private :: iaq_ch
real, private :: det
real, private :: scoef
real, private :: flo_ls
real, private :: vel
real, private :: cohes
real, private :: vel_cr
real, private :: b_coef
real, private :: qcms
real, private :: veg
real, private :: rad_curv
real, private :: cla
real, private :: pk_rto
real, private :: vel_bend
real, private :: vel_rch
real, private :: arc_len
real, private :: hyd_radius
real, private :: prot_len
real, private :: gw_salt_in
real, private :: gw_cs_in
real, private :: seep_mass
real, private :: salt_conc
real, private :: cs_conc
real, private :: bf_flow
real, private :: conc_chng
real, private :: inflo_rate
real, private :: aqu_inflo
Call graph
sd_channel_control3 calls actions, ch_rtmusk, ch_rtpath, ch_rtpest, ch_watqual4, cli_lapse, conditions, gwflow_canl, gwflow_gwsw, gwflow_satx, gwflow_tile, rcurv_interp_flo, sd_channel_sediment3, wallo_control