sd_channel_control2 – test-src-project
sd_channel_control2 Subroutine
91 statements
Source File
subroutine sd_channel_control2()
Uses
channel_data_module
ch_pesticide_module
channel_module
conditional_module
climate_module
hydrograph_module
constituent_mass_module
sd_channel_module
Arguments
n/a
I/O
n/a
Outside Variables and Types
real (10 attributes from ch_pesticide_module)
Attribute Name Description
frsol
none |fraction of pesticide in reach that is soluble
Read more…
frsrb
none |fraction of pesticide in reach that is sorbed
Read more…
rttime
hr |reach travel time
Read more…
ben_area
m2 |benthic area (bottom sediments)
Read more…
rchdep
m |depth of flow on day
Read more…
peakr
wtemp
stream water temperature C
peakrate
trav_time
days |time spent in each hydrograph time step
Read more…
flo_dep
m^2 |hydraulic radius for each hydrograph time step
Read more…
type(ch_pesticide_output) (1 attribute from ch_pesticide_module)
Attribute Name Description
chpst_d
type (7 attributes from ch_pesticide_module)
Attribute Name Description
chpst%pest None
hd%flo None
ht1%flo None
ht1%temp None
cs_db%num_tot None
cs_db%num_pests None
hcs2%pest None
integer (5 attributes from channel_module)
Attribute Name Description
jnut
units |description
Read more…
iwst
|
isdch
|
icmd
|
ich
none |object number
Read more…
type(channel) (1 attribute from channel_module)
Attribute Name Description
ch
type(decision_table) (2 attributes from conditional_module)
Attribute Name Description
dtbl_flo
d_tbl
type(weather_station) (1 attribute from climate_module)
Attribute Name Description
wst
type(hyd_output) (5 attributes from hydrograph_module)
Attribute Name Description
hz
ht2
ht3
ch_in_d
ch_out_d
type(object_connectivity) (1 attribute from hydrograph_module)
Attribute Name Description
ob
type(channel_aquifer_elements) (1 attribute from hydrograph_module)
Attribute Name Description
aq_ch
sorted by drainage area (smallest first)
type(constituent_mass) (3 attributes from constituent_mass_module)
Attribute Name Description
ch_water
ch_benthic
hcs1
type(all_constituent_hydrograph) (1 attribute from constituent_mass_module)
Attribute Name Description
obcs
type(swatdeg_datafiles) (1 attribute from sd_channel_module)
Attribute Name Description
sd_dat
type(swatdeg_channel_dynamic) (1 attribute from sd_channel_module)
Attribute Name Description
sd_ch
type(sd_ch_output) (1 attribute from sd_channel_module)
Attribute Name Description
chsd_d
!! Bang Comments
set ht1 to incoming daily hydrograph if connected to aquifer - add flow set inflow hyds for printing zero outgoing flow and sediment - ht2 use modified qual-2e routines don't route constituents if flow is zero convert mass to concentration compute max flow depth and corresponding travel time during day convert concentration to mass route constituents call mike winchell's new routine for pesticide routing
route pathogens check decision table for flow control - water allocation output channel organic-mineral output flow to channel morphology set pesticide output variables
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure.
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
  21 ich = isdch
  22 isd_db = sd_dat(ich)%hyd
  23 iwst = ob(icmd)%wst
  26 ht1 = ob(icmd)%hin
  27 ht1%temp = 5.0 + 0.75 * wst(iwst)%weat%tave
  28 wtemp = 5.0 + 0.75 * wst(iwst)%weat%tave
IF (sd_ch(ich)%aqu_link > 0) THEN Lines 31-40
  32 iaq = sd_ch(ich)%aqu_link
  33 iaq_ch = sd_ch(ich)%aqu_link_ch
IF (aq_ch(iaq)%ch(iaq_ch)%flo_fr > 0.) THEN Lines 34-39
  35 chsd_d(ich)%aqu_in = (aq_ch(iaq)%ch(iaq_ch)%flo_fr * aq_ch(iaq)%hd%flo) / 86400.
  36 chsd_d(ich)%aqu_in_mm = (aq_ch(iaq)%ch(iaq_ch)%flo_fr * aq_ch(iaq)%hd%flo) / (10. * ob(icmd)%area_ha)
  37 ht1 = ht1 + aq_ch(iaq)%ch(iaq_ch)%flo_fr * aq_ch(iaq)%hd
  38 aq_ch(iaq)%ch(iaq_ch)%flo_fr = 0.
END IFLine 39
END IFLine 40
  43 chsd_d(ich)%flo_in = ht1%flo / 86400.     !flow for morphology output - m3/s
  44 chsd_d(ich)%flo_in_mm = ht1%flo / (10. * ob(icmd)%area_ha)   !flow in mm
  45 ch_in_d(ich) = ht1                        !set inflow om hydrograph
  46 ch_in_d(ich)%flo = ht1%flo / 86400.       !flow for om output - m3/s
IF (cs_db%num_tot > 0) THEN Lines 49-51
  50 hcs1 = obcs(icmd)%hin(1)
END IFLine 51
  53 ht2 = hz
  56 call ch_rtmusk
  59 call sd_channel_sediment3
  62 ht3 = ht1
IF (ht1%flo > 1.e-6) THEN
  68 call hyd_convert_mass_to_conc (ht3)
  69 jnut = sd_dat(ich)%nut
  70 ben_area = sd_ch(ich)%chw * sd_ch(ich)%chl
  73 rchdep = 0.
  74 rttime = 0.
  82 call ch_watqual4
  84 call hyd_convert_conc_to_mass (ht2)
  87 call ch_rtpest
  95 call ch_rtpath
  97 end if    ! ht1%flo > 0
 107 ob(icmd)%hd(1) = ht2
 109 ch_out_d(ich) = ob(icmd)%hd(1)                       !set outflow om hydrograph
 110 ch_out_d(ich)%flo = ob(icmd)%hd(1)%flo / 86400.      !m3 -> m3/s
 113 chsd_d(ich)%flo = ob(icmd)%hd(1)%flo / 86400.        !adjust if overbank flooding is moved to landscape
 114 chsd_d(ich)%flo_mm = ob(icmd)%hd(1)%flo / (10. * ob(icmd)%area_ha)   !flow out in mm
 115 chsd_d(ich)%peakr = peakrate
 133 return
DO ii = 1, time%step Lines 75-80
IF (flo_dep(ii) > rchdep) THEN Lines 76-79
  77 rchdep = flo_dep(ii)
  78 rttime = trav_time(ii)
END IFLine 79
END DOLine 80
IF (cs_db%num_pests > 0) THEN Lines 90-92
  91 obcs(icmd)%hd(1)%pest = hcs2%pest
END IFLine 92
IF (ob(icmd)%ruleset /= "null" .and. ob(icmd)%ruleset /= "0") THEN Lines 100-105
 101 id = ob(icmd)%flo_dtbl
 102 d_tbl => dtbl_flo(id)
 103 call conditions (ich, id)
 104 call actions (ich, icmd, id)
END IFLine 105
DO ipest = 1, cs_db%num_pests Lines 118-131
 119 chpst_d(ich)%pest(ipest)%tot_in = obcs(icmd)%hin(1)%pest(ipest)
 120 chpst_d(ich)%pest(ipest)%sol_out = frsol * obcs(icmd)%hd(1)%pest(ipest)
 121 chpst_d(ich)%pest(ipest)%sor_out = frsrb * obcs(icmd)%hd(1)%pest(ipest)
 122 chpst_d(ich)%pest(ipest)%react = chpst%pest(ipest)%react
 123 chpst_d(ich)%pest(ipest)%volat = chpst%pest(ipest)%volat
 124 chpst_d(ich)%pest(ipest)%settle = chpst%pest(ipest)%settle
 125 chpst_d(ich)%pest(ipest)%resus = chpst%pest(ipest)%resus
 126 chpst_d(ich)%pest(ipest)%difus = chpst%pest(ipest)%difus
 127 chpst_d(ich)%pest(ipest)%react_bot = chpst%pest(ipest)%react_bot
 128 chpst_d(ich)%pest(ipest)%bury = chpst%pest(ipest)%bury
 129 chpst_d(ich)%pest(ipest)%water = ch_water(ich)%pest(ipest)
 130 chpst_d(ich)%pest(ipest)%benthic = ch_benthic(ich)%pest(ipest)
END DOLine 131
END IF
Allocations
n/a
Calls
Calls
Procedures called by this subroutine.
Local Variables
Type Visibility Attributes Name Initial
integer, private :: isd_db
integer, private :: ipest
integer, private :: id
integer, private :: iaq
integer, private :: iaq_ch
integer, private :: ii
Call graph
sd_channel_control2 calls actions, ch_rtmusk, ch_rtpath, ch_rtpest, ch_watqual4, conditions, hyd_convert_conc_to_mass, hyd_convert_mass_to_conc, sd_channel_sediment3