sd_hydsed_init – test-src-project
sd_hydsed_init Subroutine
245 statements
Source File
subroutine sd_hydsed_init()
Uses
sd_channel_module
pesticide_data_module
basin_module
channel_velocity_module
hydrograph_module
constituent_mass_module
maximum_data_module
input_file_module
Arguments
n/a
I/O
n/a
Outside Variables and Types
type(swatdeg_hydsed_data) (1 attribute from sd_channel_module)
Attribute Name Description
sd_chd
type(swatdeg_sednut_data) (1 attribute from sd_channel_module)
Attribute Name Description
sd_chd1
channel sediment budget for output
type(gully_data) (1 attribute from sd_channel_module)
Attribute Name Description
gully
type(swatdeg_init_datafiles) (1 attribute from sd_channel_module)
Attribute Name Description
sd_init
type(swatdeg_datafiles) (1 attribute from sd_channel_module)
Attribute Name Description
sd_dat
type(swatdeg_channel_dynamic) (1 attribute from sd_channel_module)
Attribute Name Description
sd_ch
type (14 attributes from sd_channel_module)
Attribute Name Description
rcurv%vol_ch None
rcurv%flo_rate None
rcurv%vol None
bsn_cc%rte None
bsn_prm%msk_co2 None
bsn_prm%msk_co1 None
bsn_prm%msk_x None
sp_ob%chandeg None
sp_ob1%chandeg None
cs_db%num_pests None
cs_db%num_cs None
cs_db%pest_num None
cs_db%num_salts None
cs_db%num_paths None
type(channel_rating_curve) (1 attribute from sd_channel_module)
Attribute Name Description
ch_rcurv
type(pesticide_db) (1 attribute from pesticide_data_module)
Attribute Name Description
pestdb
type(channel_velocity_parameters) (1 attribute from channel_velocity_module)
Attribute Name Description
sd_ch_vel
integer (2 attributes from hydrograph_module)
Attribute Name Description
icmd
|
ich
none |object number
Read more…
type(hyd_output) (7 attributes from hydrograph_module)
Attribute Name Description
hz
om_init_water
ch_om_water_init
fp_om_water_init
ch_stor
channel storage - max bankfull
fp_stor
flood plain storage above wetland emergency
tot_stor
total - channel + flood plain storage
type(object_connectivity) (1 attribute from hydrograph_module)
Attribute Name Description
ob
type(constituent_mass) (2 attributes from constituent_mass_module)
Attribute Name Description
ch_water
ch_benthic
type(salt_cha_init_concentrations) (1 attribute from constituent_mass_module)
Attribute Name Description
salt_cha_ini
type(cs_cha_init_concentrations) (1 attribute from constituent_mass_module)
Attribute Name Description
cs_cha_ini
type(cs_water_init_concentrations) (2 attributes from constituent_mass_module)
Attribute Name Description
pest_water_ini
path_water_ini
!! Bang Comments
! nbs 1/24/22 compute headcut parameters compute travel time coefficients - delete when finished with flood plain check IF bottom width (b) is < 0 compute travel time coefficients - delete when finished with flood plain
compute rating curve set Muskingum parameters compute storage discharge for Muskingum at 0.1 and 1.0 times bankfull depth c^2=a^2+b^2 - a=dep; a/b=slope; b^2=a^2/slope^2 0.1bankfull storage discharge coef bankfull storage discharge coef Compute storage time constant for reach (msk_co1 + msk_co2 = 1.) Muskingum numerical stability -Jaehak Jeong, 2011 Discretize time interval to meet the stability criterion initial inflow-outflow compute coefficients c1+c2+c3 must equal 1 initialize rating curves - inflow and outflow at current time step initial volume is frac of flow depth - fracmmkm*1000. = m3
convert concentration to mass partition water between channel and flood plain depth below bankfull depth above bankfull save initial water if calibrating and rerunning calculate volume of active river bed sediment layer - m3 calculate mixing velocity using molecular weight and porosity
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure.
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
DO i = 1, sp_ob%chandeg
  67 icmd = sp_ob1%chandeg + i - 1
  68 idat = ob(icmd)%props
  69 idb = sd_dat(idat)%hyd
  70 idb1 = sd_dat(idat)%sednut
  71 sd_ch(i)%name = sd_chd(idb)%name
  72 sd_ch(i)%obj_no = icmd
  73 sd_ch(i)%order = sd_chd(idb)%order
  74 sd_ch(i)%chw = sd_chd(idb)%chw
  75 sd_ch(i)%chd = sd_chd(idb)%chd
  76 sd_ch(i)%chs = sd_chd(idb)%chs
  77 if (sd_ch(i)%chs < 1.e-9) sd_ch(i)%chs = .000001
  78 sd_ch(i)%chl = sd_chd(idb)%chl
  79 sd_ch(i)%chn = sd_chd(idb)%chn
  80 if (sd_ch(i)%chn < .05) sd_ch(i)%chn = .05
  81 sd_ch(i)%chk = sd_chd(idb)%chk
  82 sd_ch(i)%bank_exp = sd_chd(idb)%bank_exp
  83 sd_ch(i)%cov = sd_chd(idb)%cov
  84 sd_ch(i)%sinu = sd_chd(idb)%sinu
  85 if (sd_ch(i)%sinu < 1.05) sd_ch(i)%sinu = 1.05
  86 sd_ch(i)%vcr_coef = sd_chd(idb)%vcr_coef
  87 sd_ch(i)%d50 = sd_chd(idb)%d50
  88 sd_ch(i)%ch_clay = sd_chd(idb)%ch_clay
  89 sd_ch(i)%carbon = sd_chd(idb)%carbon
  90 sd_ch(i)%ch_bd = sd_chd(idb)%ch_bd
  91 sd_ch(i)%chss = sd_chd(idb)%chss
  92 sd_ch(i)%n_conc = sd_chd(idb)%n_conc
  93 sd_ch(i)%p_conc = sd_chd(idb)%p_conc
  94 sd_ch(i)%p_bio = sd_chd(idb)%p_bio
  95 sd_ch(i)%bankfull_flo = sd_chd(idb)%bankfull_flo
  96 if (sd_ch(i)%bankfull_flo <= 1.e-6) sd_ch(i)%bankfull_flo = 0.
  97 sd_ch(i)%fps = sd_chd(idb)%fps
  98 if (sd_ch(i)%fps > sd_ch(i)%chs) sd_ch(i)%fps = sd_ch(i)%chs
  99 if (sd_ch(i)%fps <= 1.e-6) sd_ch(i)%fps = .00001       !!! nbs 1/24/22
 100 sd_ch(i)%fpn = sd_chd(idb)%fpn
 101 sd_ch(i)%hc_kh = gully(0)%hc_kh
 102 sd_ch(i)%hc_hgt = gully(0)%hc_hgt
 103 sd_ch(i)%hc_ini = gully(0)%hc_ini
 104 sd_ch(i)%pk_rto = sd_chd1(idb1)%pk_rto
 105 sd_ch(i)%fp_inun_days = sd_chd1(idb1)%fp_inun_days
 106 sd_ch(i)%n_setl = sd_chd1(idb1)%n_setl
 107 sd_ch(i)%p_setl = sd_chd1(idb1)%p_setl
 108 sd_ch(i)%n_sol_part = sd_chd1(idb1)%n_sol_part
 109 sd_ch(i)%p_sol_part = sd_chd1(idb1)%p_sol_part
 110 sd_ch(i)%n_dep_enr = sd_chd1(idb1)%n_dep_enr
 111 sd_ch(i)%p_dep_enr = sd_chd1(idb1)%p_dep_enr
 112 sd_ch(i)%arc_len_fr = sd_chd1(idb1)%arc_len_fr
 113 sd_ch(i)%bed_exp = sd_chd1(idb1)%bed_exp
 114 sd_ch(i)%wash_bed_fr = sd_chd1(idb1)%wash_bed_fr
 117 kh = sd_ch(i)%hc_kh
 126 aa = 1.
 127 b = 0.
 128 d = 0.
 129 chside = sd_ch(i)%chss
 130 fps = 4.
 131 b = sd_ch(i)%chw - 2. * sd_ch(i)%chd * chside
 139 sd_ch_vel(i)%wid_btm = b
 140 sd_ch_vel(i)%dep_bf = sd_ch(i)%chd  !delete sd_ch_vel when finished
 144 call sd_rating_curve (i)
 167 msk1 = bsn_prm%msk_co1 / (bsn_prm%msk_co1 + bsn_prm%msk_co2)
 168 msk2 = bsn_prm%msk_co2 / (bsn_prm%msk_co1 + bsn_prm%msk_co2)
 169 xkm = sd_ch(i)%stor_dis_bf * msk1 + sd_ch(i)%stor_dis_01bf * msk2
 172 detmax = 2.* xkm * (1.- bsn_prm%msk_x)
 173 det = time%dtm / 60.      !hours
 174 sd_ch(i)%msk%substeps = 1
 183 sd_ch(i)%msk%nsteps = time%step * sd_ch(i)%msk%substeps
 192 det = det / sd_ch(i)%msk%substeps
 193 denom = 2. * xkm * (1. - bsn_prm%msk_x) + det
 194 sd_ch(i)%msk%c1 = (det - 2. * xkm * bsn_prm%msk_x) / denom
 195 sd_ch(i)%msk%c1 = Max(0., sd_ch(i)%msk%c1)
 196 sd_ch(i)%msk%c2 = (det + 2. * xkm * bsn_prm%msk_x) / denom
 197 sd_ch(i)%msk%c3 = (2. * xkm * (1. - bsn_prm%msk_x) - det) / denom
 199 sumc = sd_ch(i)%msk%c1 + sd_ch(i)%msk%c2 + sd_ch(i)%msk%c3
 200 sd_ch(i)%msk%c1 = sd_ch(i)%msk%c1 / sumc
 201 sd_ch(i)%msk%c2 = sd_ch(i)%msk%c2 / sumc
 202 sd_ch(i)%msk%c3 = sd_ch(i)%msk%c3 / sumc
 204 end do    !end of channel loop
 309 return
IF (kh > 1.e-6) THEN Lines 118-120
 119 sd_ch(i)%hc_co = .37 * (17.83 + 16.56 * kh - 15. * sd_ch(i)%cov)
 120 sd_ch(i)%hc_co = max (0., sd_ch(i)%hc_co)
END IFLine 120
ELSE Lines 121-123
 122 sd_ch(i)%hc_co = 0.
END IF Line 123
IF (b <= 0.) THEN Lines 134-138
 135 b = .5 * sd_ch(i)%chw
 136 b = Max(0., b)
 137 chside = (sd_ch(i)%chw - b) / (2. * sd_ch(i)%chd)
END IFLine 138
DO i_dep = 1, 2 Lines 148-164
 149 if (i_dep == 1) dep = 0.1 * sd_ch(i)%chd
 150 if (i_dep == 2) dep = sd_ch(i)%chd
 152 p = b + 2. * Sqrt(dep ** 2 * (1. + 1. / (sd_ch(i)%chss ** 2)))
 153 a = b * dep + dep / sd_ch(i)%chss
 154 rh = a / p
 155 vel = Qman(1., rh, sd_ch(i)%chn, sd_ch(i)%chs)
 156 celerity = vel * 5. / 3.
IF (i_dep == 1) THEN Lines 157-159
 159 sd_ch(i)%stor_dis_01bf = sd_ch(i)%chl / (3.6 * celerity)
END IFLine 159
ELSE Lines 160-163
 162 sd_ch(i)%stor_dis_bf = sd_ch(i)%chl / (3.6 * celerity)
END IF Line 163
END DOLine 164
IF (det > detmax) THEN Lines 177-179
 178 sd_ch(i)%msk%substeps = Int(det / detmax) + 1
END IFLine 179
IF (bsn_cc%rte == 0 .and. time%step <= 1) THEN Lines 180-182
 181 sd_ch(i)%msk%substeps = 1
END IFLine 182
IF (sd_ch(i)%msk%nsteps > 0) THEN Lines 186-189
 187 sd_ch(i)%in1_vol = rcurv%flo_rate / (86400. / sd_ch(i)%msk%nsteps)
 188 sd_ch(i)%out1_vol = rcurv%flo_rate / (86400. / sd_ch(i)%msk%nsteps)
END IFLine 189
DO ich = 1, sp_ob%chandeg Lines 207-249
 247 ch_om_water_init(ich) = ch_stor(ich)
 248 fp_om_water_init(ich) = fp_stor(ich)
IF (sd_ch(ich)%chl > 1.e-3) THEN Lines 209-241
 210 iob = sp_ob1%chandeg + ich - 1
 211 ichdat = ob(iob)%props
 212 ich_ini = sd_dat(ichdat)%init
 213 iom_ini = sd_init(ich_ini)%org_min
 214 tot_stor(ich) = om_init_water(iom_ini)
 217 flow_dep = om_init_water(iom_ini)%flo * sd_ch(ich)%chd
 218 icha = ich
 219 call rcurv_interp_dep (icha, flow_dep)
 220 ch_rcurv(ich)%in1 = rcurv
 221 ch_rcurv(ich)%out1 = rcurv
 225 tot_stor(ich)%flo = rcurv%vol
 228 call hyd_convert_conc_to_mass (tot_stor(ich))
IF (om_init_water(iom_ini)%flo <= 1.0) THEN Lines 231-234
 233 ch_stor(ich) = tot_stor(ich)
 234 fp_stor(ich) = hz
END IFLine 234
ELSE Lines 235-241
 237 rto = rcurv%vol_ch / rcurv%vol
 238 ch_stor(ich) = rto * tot_stor(ich)
 239 rto1 = 1. - rto
 240 fp_stor(ich) = rto1 * tot_stor(ich)
END IF Line 241
END IFLine 241
ELSE Lines 242-245
 243 ch_stor(ich) = hz
 244 fp_stor(ich) = hz
END IF Line 245
END DOLine 249
DO ich = 1, sp_ob%chandeg Lines 252-267
 253 iob = sp_ob1%chandeg + ich - 1
 254 ichdat = ob(iob)%props
 255 ich_ini = sd_dat(ichdat)%init
 256 ipest_ini = sd_init(ich_ini)%pest
DO ipest = 1, cs_db%num_pests Lines 257-266
 258 ipest_db = cs_db%pest_num(ipest)
 260 ch_water(ich)%pest(ipest) = pest_water_ini(ipest_ini)%water(ipest) * ch_stor(ich)%flo * 1000.
 262 bedvol = sd_ch(ich)%chw *sd_ch(ich)%chl * 1000.* pestdb(ipest_ini)%ben_act_dep
 263 ch_benthic(ich)%pest(ipest) = pest_water_ini(ipest_ini)%benthic(ipest) * bedvol * 1000.   ! mg = mg/kg * m3*1000.
 265 sd_ch(ich)%aq_mix(ipest) = pestdb(ipest_db)%mol_wt ** (-.6666) * (1. - sd_ch(ich)%ch_bd / 2.65) * (69.35 / 365)
END DOLine 266
END DOLine 267
DO ich = 1, sp_ob%chandeg Lines 270-279
 271 iob = sp_ob1%chandeg + ich - 1
 272 ichdat = ob(iob)%props
 273 ich_ini = sd_dat(ichdat)%init
 274 ipath_ini = sd_init(ich_ini)%path
DO ipath = 1, cs_db%num_paths Lines 275-278
 276 ch_water(ich)%path(ipath) = path_water_ini(ipest_ini)%water(ipath)
 277 ch_benthic(ich)%path(ipath) = path_water_ini(ipest_ini)%benthic(ipath)
END DOLine 278
END DOLine 279
IF (cs_db%num_salts > 0) THEN Lines 282-293
DO ich=1,sp_ob%chandeg Lines 283-292
 284 iob = sp_ob1%chandeg + ich - 1
 285 ichdat = ob(iob)%props
 286 ich_ini = sd_dat(ichdat)%init
 287 isalt_ini = sd_init(ich_ini)%salt
DO isalt=1,cs_db%num_salts Lines 288-291
 289 ch_water(ich)%saltc(isalt) = salt_cha_ini(isalt_ini)%conc(isalt) !g/m3
 290 ch_water(ich)%salt(isalt) = (salt_cha_ini(isalt_ini)%conc(isalt)/1000.) * tot_stor(ich)%flo !kg
END DOLine 291
END DOLine 292
END IFLine 293
IF (cs_db%num_cs > 0) THEN Lines 296-307
DO ich=1,sp_ob%chandeg Lines 297-306
 298 iob = sp_ob1%chandeg + ich - 1
 299 ichdat = ob(iob)%props
 300 ich_ini = sd_dat(ichdat)%init
 301 ics_ini = sd_init(ich_ini)%cs
DO ics=1,cs_db%num_cs Lines 302-305
 303 ch_water(ich)%csc(ics) = cs_cha_ini(ics_ini)%conc(ics)
 304 ch_water(ich)%cs(ics) = (cs_cha_ini(ics_ini)%conc(ics)/1000.) * tot_stor(ich)%flo !kg
END DOLine 305
END DOLine 306
END IFLine 307
END DO
Allocations
n/a
Calls
Calls
Procedures called by this subroutine.
Local Variables
Type Visibility Attributes Name Initial
real, private :: kh
integer, private :: idb
integer, private :: idb1
integer, private :: i
integer, private :: iob
integer, private :: ichdat
integer, private :: ich_ini
integer, private :: iom_ini
integer, private :: ipest_ini
integer, private :: ipest_db
integer, private :: ipath_ini
integer, private :: isalt_ini
integer, private :: ics_ini
integer, private :: ipest
integer, private :: ipath
integer, private :: idat
integer, private :: i_dep
integer, private :: icha
integer, private :: isalt
integer, private :: ics
real, private :: aa
real, private :: a
real, private :: b
real, private :: d
real, private :: p
real, private :: chside
real, private :: fps
integer, private :: max
real, private :: rh
real, private :: qman
real, private :: bedvol
real, private :: dep
real, private :: vel
real, private :: flow_dep
real, private :: celerity
real, private :: msk1
real, private :: msk2
real, private :: detmax
real, private :: xkm
real, private :: det
real, private :: denom
real, private :: rto
real, private :: rto1
real, private :: sumc
Call graph
sd_hydsed_init calls hyd_convert_conc_to_mass, rcurv_interp_dep, sd_rating_curve