surface – TestDataProject
surface Subroutine
39 statements
Source File
subroutine surface()
Called From
n/a
Arguments
n/a
Outside Variables and Types
type (2 attributes from basin_module)
Attribute Name Description
bsn_cc%crk None
luse%urb_lu None
type(irrigation_water_transfer) (1 attribute from hydrograph_module)
Attribute Name Description
irrig
dimension by hru
integer (2 attributes from hru_module)
Attribute Name Description
ulu
|
ihru
none |HRU number
Read more…
type(hydrologic_response_unit) (1 attribute from hru_module)
Attribute Name Description
hru
real (4 attributes from hru_module)
Attribute Name Description
precip_eff
mm |daily effective precip for runoff calculations = precipday + ls_overq + snomlt - canstor |precip_eff = precipday + ls_overq - snofall + snomlt - canstor
Read more…
qday
mm |surface runoff that reaches main channel during day in HRU
Read more…
qp_cms
surfq
Uses
basin_module
soil_module
time_module
hydrograph_module
urban_data_module
output_landscape_module
hru_module
I/O
n/a
Local Variables
Type Visibility Attributes Name Initial
integer, public :: j = 0
real, public :: ulu = 0.
real, public :: hruirrday = 0.
integer, public :: irmmdt = 0
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure. Use mouse wheel to zoom, drag to pan.
Reset Zoom Help
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
~ ~ ~ PURPOSE ~ ~ ~ (line 3)
this subroutine models surface hydrology at any desired time step (line 4)
~ ~ ~ INCOMING VARIABLES ~ ~ ~ (line 6)
name |units |definition (line 7)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ (line 8)
ovrlnd(:) |mm H2O |overland flow onto HRU from upstream (line 9)
|routing unit (line 10)
qp_cms |m3/sec |peak runoff rate (line 11)
surfq(:) |mm H2O |surface runoff generated in HRU during (line 12)
|the day (line 13)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ (line 14)
~ ~ ~ SUBROUTINES/FUNCTIONS CALLED ~ ~ ~ (line 15)
Intrinsic: Max (line 16)
SWAT: canopyint, snom, crackvol, dailycn, volq, crackflow, surfst_h2o, (line 17)
SWAT: alph, pkq, tran, eiusle, ysed (line 18)
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~ (line 20)
calculate subdaily curve number value (line 43)
compute runoff - surfq in mm H2O (line 46)
  26 qp_cms, precip_eff, qday                  !rtb gwflow
  38 j = ihru
  39 ulu = hru(j)%luse%urb_lu
  40 hruirrday = 0.
  41 irmmdt = 0.
  44 call sq_dailycn
IF (precip_eff > 0.1) THEN Lines 47-52
adjust runoff for loss into crack volume (line 50)
  48 call sq_volq
  51 if (surfq(j) > 0. .and. bsn_cc%crk == 1) call sq_crackflow
END IFLine 52
add irrigation runoff and surface runon runoff (line 54)
calculate amount of surface runoff reaching main channel during day (line 58)
(qday) and store the remainder (line 59)
  55 surfq(j) = surfq(j) + irrig(j)%runoff
  56 irrig(j)%runoff = 0.
  61 qday =  surfq(j)
IF (qday > 1.e-6) THEN Lines 63-66
compute peak rate - qp_cms in m3/s (line 64)
  65 call ero_pkq
END IFLine 66
IF (qday > 1.e-6 .and. qp_cms > 1.e-6) THEN Lines 68-73
calculate sediment erosion by rainfall and overland flow (line 71)
  69 call ero_eiusle
  72 call ero_ovrsed
END IFLine 73
IF (surfq(j) > 1.e-6 .and. qp_cms > 1.e-6) THEN Lines 75-78
  76 call ero_cfactor
  77 call ero_ysed
END IFLine 78
  80 if (qday < 0.) qday = 0.
  83 return
Allocations
n/a
Calls
Procedures Called
List of procedures called by this Subroutine.
sq_dailycn
sq_volq
sq_crackflow
ero_pkq
ero_eiusle
ero_ovrsed
ero_cfactor
ero_ysed
Call Graph
Visual representation of procedures called by this Subroutine.
Call graph
surface calls ero_cfactor, ero_eiusle, ero_ovrsed, ero_pkq, ero_ysed, sq_crackflow, sq_dailycn, sq_volq