swr_percmain – test-src-project
swr_percmain Subroutine
143 statements
Source File
subroutine swr_percmain()
Uses
hru_module
septic_data_module
basin_module
hydrograph_module
soil_module
gwflow_module
Arguments
n/a
I/O
n/a
Outside Variables and Types
integer (5 attributes from hru_module)
Attribute Name Description
isep
|
ihru
none |HRU number
Read more…
i_sep
gw_soil_flag
|
gw_solute_flag
|main flag
type(hydrologic_response_unit) (1 attribute from hru_module)
Attribute Name Description
hru
real (12 attributes from hru_module)
Attribute Name Description
sw_excess
wt_shall
qtile
latlyr
mm |lateral flow in soil layer for the day
Read more…
inflpcp
mm |amount of precipitation that infiltrates
Read more…
sepday
sepcrktot
lyrtile
qstemm
septic changes added 1/28/09 gsm
latq
sepbtm
gwsoilq
rtb gwflow
type(septic_system) (1 attribute from septic_data_module)
Attribute Name Description
sep
type (5 attributes from basin_module)
Attribute Name Description
bsn_cc%crk None
bsn_cc%gwflow None
bsn_cc%tdrn None
bsn_cc%wtdn None
ht1%flo None
type(irrigation_water_transfer) (1 attribute from hydrograph_module)
Attribute Name Description
irrig
dimension by hru
type(soil_profile) (1 attribute from soil_module)
Attribute Name Description
soil
!! Bang Comments
~ ~ ~ PURPOSE ~ ~ ~ this subroutine is the master soil percolation component.
~ ~ ~ INCOMING VARIABLES ~ ~ ~ name |units |definition ~ ~ ~ OUTGOING VARIABLES ~ ~ ~ name |units |definition ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ new water table depth equations 01/2009 c |none |a factor used to convert airvol to wtd dg |mm |soil layer thickness in HRU new water table depth equations 01/2009 latq(:) |mm H2O |total lateral flow in soil profile for the |day in HRU lyrtile |mm H2O |drainage tile flow in soil layer for day new water table depth equations 01/2009 ne_p |mm/hr |effective porosity in HRU for all soil profile layers ne_w |mm/hr |effective porosity in HRU for soil layers above wtd new water table depth equations 01/2009 qtile |mm H2O |drainage tile flow in soil profile for the day sepday |mm H2O |micropore percolation from soil layer sepbtm(:) |mm H2O |percolation from bottom of soil profile for |the day in HRU sw_excess |mm H2O |amount of water in excess of field capacity |stored in soil layer on the current day new water table depth equations 01/2009 new water table depth equations 01/2009 wt_shall |mm H2O |shallow water table height above bottom of soil profile ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ w2 |mm | y1 |mm |dummy variable for wat ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
initialize water entering first soil layer ht1%flo is infiltration from overland flow routing calculate crack flow add water moving into soil layer from overlying layer septic tank inflow to biozone layer J.Jeong
determine gravity drained water in layer initialize variables for current layer calculate tile flow (lyrtile), lateral flow (latlyr) and percolation (sepday) summary calculations redistribute soil water if above saturation (high water table) update soil profile water compute shallow water table depth and tile flow drainmod tile equations 08/11/2006 drainmod wt_shall equations 10/23/2006 drainmod wt_shall equations 10/23/2006
Start Daniel"s tile equations modifications 01/2006 drainmod tile equations compute tile flow using drainmod tile equations compute tile flow using existing tile equations End Daniel"s tile equations modifications 01/2006
update soil profile water after tile drainage update soil profile water
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure.
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
  37 sw_excess, wt_shall, qtile, gwsoilq !rtb gwflow
  60 j = ihru
  61 ires =  hru(j)%dbs%surf_stor !Jaehak 2022
IF (bsn_cc%gwflow.eq.1) THEN Lines 64-66
  65 call gwflow_soil(j)
END IFLine 66
IF (ires==0) THEN Lines 70-71
  71 sepday = inflpcp + irrig(j)%applied + ht1%flo / (hru(j)%area_ha * 10.)
END IFLine 71
ELSE Lines 72-74
  73 sepday = inflpcp + ht1%flo / (hru(j)%area_ha * 10.)
END IF Line 74
IF (bsn_cc%crk == 1) THEN Lines 79-82
  80 call swr_percmacro
  81 sepday = sepday - sepcrktot
END IFLine 82
  85 slug = 1000.  !4.  !1000.   !this should be an input in parameters.bsn
  86 sep_left = sepday
DO !slug loop
  88 sepday = amin1(sep_left, slug)
  89 sep_left = sep_left - sepday
  90 sep_left = max(0., sep_left)
 131 if (sep_left <= 0.) exit
 132 end do                    !slug loop
 135 call swr_satexcess
 138 soil(j)%sw = 0.
 144 qtile = 0.
 145 wt_shall = soil(j)%zmx
 147 if (soil(j)%phys(2)%tmp > 0.) then   !Daniel 1/29/09
 148 por_air = 0.9
 149 d = soil(j)%zmx - hru(j)%lumv%sdr_dep   !height of tiles above bottom of soil profile
 151 if (bsn_cc%wtdn == 0) then !compute wt_shall using original eq-Daniel 10/23/06
 220 soil(j)%sw = 0.
 225 return
DO j1 = 1, soil(j)%nly Lines 91-130
  93 soil(j)%phys(j1)%st = soil(j)%phys(j1)%st + sepday
  97 if (j1 == i_sep(j) .and. soil(j)%phys(j1)%tmp > 0. .and.          &
  98 sep(isep)%opt  /= 0) then
  99 soil(j)%phys(j1)%st = soil(j)%phys(j1)%st + qstemm(j)  ! in mm
 103 sw_excess = soil(j)%phys(j1)%st - soil(j)%phys(j1)%fc
 106 sepday = 0.
 107 latlyr = 0.
 108 lyrtile = 0.
 123 latq(j) = latq(j) + latlyr
 124 qtile = qtile + lyrtile
 125 soil(j)%ly(j1)%flat = latlyr + lyrtile
 126 soil(j)%ly(j1)%prk = soil(j)%ly(j1)%prk + sepday
 127 if (latq(j) < 1.e-6) latq(j) = 0.
 128 if (qtile < 1.e-6) qtile = 0.
 129 if (soil(j)%ly(j1)%flat < 1.e-6) soil(j)%ly(j1)%flat = 0.
IF (sw_excess > 1.e-5) THEN Lines 110-117
 113 call swr_percmicro(j1)
 115 soil(j)%phys(j1)%st = soil(j)%phys(j1)%st - sepday - latlyr - lyrtile
 116 soil(j)%phys(j1)%st = Max(1.e-6, soil(j)%phys(j1)%st)
END IFLine 117
IF (j1 == soil(j)%nly) THEN Lines 120-122
 121 sepbtm(j) = sepbtm(j) + sepday
END IFLine 122
END DOLine 130
DO j1 = 1, soil(j)%nly Lines 139-141
 140 soil(j)%sw = soil(j)%sw + soil(j)%phys(j1)%st
END DOLine 141
IF (soil(j)%sw > soil(j)%sumfc) THEN Lines 152-162
 153 yy = soil(j)%sumul * por_air
 157 xx = (soil(j)%sw - soil(j)%sumfc) / (yy - soil(j)%sumfc)
 158 if (xx > 1.) xx = 1.
 159 wt_shall = xx * soil(j)%zmx
 160 wat = soil(j)%zmx - wt_shall
 161 if(wat > soil(j)%zmx) wat = soil(j)%zmx
IF (yy < 1.1 * soil(j)%sumfc) THEN Lines 154-156
 155 yy = 1.1 * soil(j)%sumfc
END IFLine 156
END IFLine 162
DO j1 = 1, soil(j)%nly Lines 165-175
IF (soil(j)%wat_tbl < soil(j)%phys(j1)%d) THEN Lines 166-174
 167 sw_del = soil(j)%swpwt - soil(j)%sw
 168 wt_del = sw_del * soil(j)%ly(j1)%vwt
 169 soil(j)%wat_tbl = soil(j)%wat_tbl + wt_del
 170 if(soil(j)%wat_tbl > soil(j)%zmx)  soil(j)%wat_tbl = soil(j)%zmx
 171 wt_shall = soil(j)%zmx - soil(j)%wat_tbl
 172 soil(j)%swpwt = soil(j)%sw
 173 exit
END IFLine 174
END DOLine 175
IF (hru(j)%tiledrain > 0) THEN Lines 179-194
IF (hru(j)%lumv%sdr_dep > 0.) THEN Lines 180-193
IF (wt_shall <= d) THEN Lines 181-182
 182 qtile = 0.
END IFLine 182
ELSE Lines 183-192
IF (bsn_cc%tdrn == 1) THEN Lines 185-187
 187 call swr_drains           !! compute tile flow using drainmod tile equations
END IFLine 187
ELSE Lines 188-191
 189 call swr_origtile(d)      !! compute tile flow using existing tile equations
 190 if(qtile < 0.) qtile = 0.
END IF Line 191
END IF Line 192
END IFLine 193
END IFLine 194
IF (qtile > 0.) THEN Lines 198-217
 200 sumqtile = qtile
DO j1 = 1, soil(j)%nly Lines 201-212
 202 xx = soil(j)%phys(j1)%st - soil(j)%phys(j1)%fc
IF (xx > 0.) THEN Lines 203-211
IF (xx > sumqtile) THEN Lines 204-206
 205 soil(j)%phys(j1)%st = soil(j)%phys(j1)%st - sumqtile
 206 sumqtile = 0.
END IFLine 206
ELSE Lines 207-210
 208 sumqtile = sumqtile - xx
 209 soil(j)%phys(j1)%st = soil(j)%phys(j1)%fc
END IF Line 210
END IFLine 211
END DOLine 212
IF (sumqtile > 0.) THEN Lines 213-216
 214 qtile = qtile - sumqtile
 215 qtile = Max(0., qtile)
END IFLine 216
END IFLine 217
DO j1 = 1, soil(j)%nly Lines 221-223
 222 soil(j)%sw = soil(j)%sw + soil(j)%phys(j1)%st
END DOLine 223
END DO
Allocations
n/a
Calls
Calls
Procedures called by this subroutine.
Local Variables
Type Visibility Attributes Name Initial
integer, private :: j
integer, private :: j1
integer, private :: ires
real, private :: slug
real, private :: sep_left
real, private :: por_air
real, private :: d
real, private :: yy
real, private :: xx
real, private :: wat
real, private :: sw_del
real, private :: wt_del
real, private :: sumqtile
Call graph
swr_percmain calls amin1, gwflow_soil, swr_drains, swr_origtile, swr_percmacro, swr_percmicro, swr_satexcess