time_control – TestDataProject
time_control Subroutine
272 statements
Source File
subroutine time_control()
Called From
n/a
Arguments
n/a
Outside Variables and Types
character(len=40) (1 attribute from plant_data_module)
Attribute Name Description
plts_bsn
none |plant names simulated in current run
Read more…
type(plant_db) (1 attribute from plant_data_module)
Attribute Name Description
pldb
integer (11 attributes from hydrograph_module)
Attribute Name Description
ich
none |object number
Read more…
basin_plants
number of different plants in the basin
ipl
mo
ihru
none |HRU number
Read more…
yr_skip
mgt_ops
ndays
ndays_leap
ndays_noleap
ndmo
cumulative number of days accrued in the month since the simulation began - the array location number is the number of the month
Read more…
type(hyd_output) (4 attributes from hydrograph_module)
Attribute Name Description
ch_stor_y
chaz
ch_in_y
ch_out_y
type(object_connectivity) (1 attribute from hydrograph_module)
Attribute Name Description
ob
type (44 attributes from hydrograph_module)
Attribute Name Description
sp_ob%chandeg None
sp_ob%hru None
sp_ob%hru_lte None
sp_ob%res None
sp_ob1%chandeg None
sp_ob1%hru None
db_mx%cond_up None
db_mx%mallo_db None
db_mx%wallo_db None
cs_db%num_pests None
bsn_cc%cswat None
pco%day_print_over None
pco%sw_init None
pco%yrc_start None
pco%int_day_cur None
pco%aa_numint None
pco%aa_yrs None
pco%day_print None
pco%yrc_end None
pco%nyskip None
pco%int_day None
pco%day_start None
pco%day_end None
time%yrs_prt_int None
time%days_prt None
time%end_sim None
time%day_end_yr None
time%prt_int_cur None
time%end_mo None
time%yrc_end None
time%yrs_prt None
time%num_leap None
time%day_start None
time%yrc None
time%nbyr None
time%day None
time%yrc_start None
time%day_end None
time%mo None
time%yrs None
time%day_mo None
time%end_yr None
time%yrc_tot None
time%end_aa_prt None
type(output_waterbal) (3 attributes from output_landscape_module)
Attribute Name Description
hwb_y
hwbz
hltwb_y
type(output_nutbal) (3 attributes from output_landscape_module)
Attribute Name Description
hnb_y
hnbz
hltnb_y
type(output_losses) (3 attributes from output_landscape_module)
Attribute Name Description
hls_y
hlsz
hltls_y
type(output_plantweather) (3 attributes from output_landscape_module)
Attribute Name Description
hpw_y
hpwz
hltpw_y
type(plant_community) (1 attribute from plant_module)
Attribute Name Description
pcom
type(basin_crop_yields) (3 attributes from plant_module)
Attribute Name Description
bsn_crop_yld
bsn_crop_yld_aa
bsn_crop_yld_z
type(pesticide_balance) (1 attribute from output_ls_pesticide_module)
Attribute Name Description
pestbz
type(object_pesticide_balance) (1 attribute from output_ls_pesticide_module)
Attribute Name Description
hpestb_y
type(channel_morphology_output) (1 attribute from sd_channel_module)
Attribute Name Description
ch_morph
type(swatdeg_channel_dynamic) (1 attribute from sd_channel_module)
Attribute Name Description
sd_ch
type(sd_ch_output) (2 attributes from sd_channel_module)
Attribute Name Description
chsd_y
chsdz
type(update_conditional) (1 attribute from calibration_data_module)
Attribute Name Description
upd_cond
type(hydrologic_response_unit) (1 attribute from hru_module)
Attribute Name Description
hru
real (2 attributes from hru_module)
Attribute Name Description
phubase
yrs_print
type(water_allocation) (1 attribute from water_allocation_module)
Attribute Name Description
wallo
dimension by water allocation objects
type(water_body) (2 attributes from water_body_module)
Attribute Name Description
wbodz
ch_wat_y
type(decision_table) (2 attributes from conditional_module)
Attribute Name Description
dtbl_scen
d_tbl
type(management_schedule) (1 attribute from mgt_operations_module)
Attribute Name Description
sched
character(len=29) (1 attribute from time_module)
Attribute Name Description
cal_sim
type(time_current) (1 attribute from time_module)
Attribute Name Description
time_init
Uses
plant_data_module
hydrograph_module
output_landscape_module
climate_module
maximum_data_module
plant_module
output_ls_pesticide_module
sd_channel_module
calibration_data_module
constituent_mass_module
hru_module
water_allocation_module
water_body_module
hru_lte_module
basin_module
conditional_module
mgt_operations_module
soil_module
time_module
I/O
I/O units used in this subroutine.
Unit Type Filename
unit_* Output not specified
unit_9003 Output not specified
unit_5100 Output not specified
unit_5101 Output not specified
unit_7778 Output not specified
Local Variables
Type Visibility Attributes Name Initial
integer, public :: j = 0
integer, public :: julian_day = 0
integer, public :: id = 0
integer, public :: isched = 0
integer, public :: idp = 0
integer, public :: iplt = 0
integer, public :: iupd = 0
integer, public :: ipest = 0
integer, public :: date_time(8) = 0
character(len=10), public :: b(3)
real, public :: crop_yld_t_ha = 0.
real, public :: sw_init = 0.
real, public :: sno_init = 0.
real, public :: bank_mm
real, public :: bed_mm
integer, public :: iob = 0
integer, public :: curyr = 0
integer, public :: mo = 0
integer, public :: day_mo = 0
integer, public :: iwallo = 0
integer, public :: imallo = 0
integer, public :: ires = 0
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure. Use mouse wheel to zoom, drag to pan.
Reset Zoom Help
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
~ ~ ~ PURPOSE ~ ~ ~ (line 3)
this subroutine contains the loops governing the modeling of processes (line 4)
in the watershed (line 5)
~ ~ ~ INCOMING VARIABLES ~ ~ ~ (line 7)
name |units |definition (line 8)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ (line 9)
biomix(:) |none |biological mixing efficiency. (line 10)
|Mixing of soil due to activity of earthworms (line 11)
|and other soil biota. Mixing is performed at (line 12)
|the end of every calendar year. (line 13)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ (line 14)
~ ~ ~ OUTGOING VARIABLES ~ ~ ~ (line 16)
name |units |definition (line 17)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ (line 18)
~ ~ ~ LOCAL DEFINITIONS ~ ~ ~ (line 20)
name |units |definition (line 21)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ (line 22)
ic |none |counter (line 23)
iix |none |sequence number of current year in rotation (line 24)
iiz |none |sequence number of current crop grown (line 25)
|within the current year (line 26)
xx |none |current year in simulation sequence (line 27)
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ (line 28)
~ ~ ~ SUBROUTINES/FUNCTIONS CALLED ~ ~ ~ (line 30)
Intrinsic: Mod, Real (line 31)
SWAT: std3, xmon, sim_initday, clicon, command (line 32)
SWAT: writed, writem, tillmix (line 33)
~ ~ ~ ~ ~ ~ END SPECIFICATIONS ~ ~ ~ ~ ~ ~ (line 35)
generate precip for the first day - %precip_next (line 87)
  85 time%yrc = time%yrc_start
IF (Mod(time%yrc,4) == 0) THEN Lines 88-89
  89 time%day_end_yr = ndays_leap(13)
END IFLine 89
ELSE Lines 90-92
  91 time%day_end_yr = ndays_noleap(13)
END IF Line 92
  94 time%yrs = 1
  95 time%day = time%day_start
  96 call xmon (time%day, mo, day_mo)
  97 time%mo = mo
  98 time%day_mo = day_mo
  99 call cli_precip_control (0)
DO curyr = 1, time%nbyr
!!! uncomment next three lines for RELEASE version only (Srin/Karim) (line 102)
determine beginning and ending dates of simulation in current year (line 109)
determine beginning and ending dates of simulation in current year (line 109)
set beginning day of simulation for year (line 126)
set beginning day of simulation for year (line 126)
set ending day of simulation for year (line 131)
sum years of printing for average annual writes (line 138)
sum years of printing for average annual writes (line 138)
set initial soil water for hru, basin and lsu - for checking water balance (line 147)
set initial soil water for hru, basin and lsu - for checking water balance (line 147)
 107 time%yrs = curyr
 132 time%day_end_yr = ndays(13)
IF (Mod(time%yrc,4) == 0) THEN Lines 110-121
IF (Mod(time%yrc,100) == 0) THEN Lines 111-117
IF (Mod(time%yrc,400) == 0) THEN Lines 112-114
 113 ndays = ndays_leap
 114 time%num_leap = time%num_leap + 1
END IFLine 114
ELSE Lines 115-117
 116 ndays = ndays_noleap
END IF Line 117
END IFLine 117
ELSE Lines 118-121
 119 ndays = ndays_leap
 120 time%num_leap = time%num_leap + 1
END IF Line 121
END IFLine 121
ELSE Lines 122-124
 123 ndays = ndays_noleap
END IF Line 124
IF (time%yrs > 1 .or. time%day_start == 0) THEN Lines 127-129
 128 time%day_start = 1
END IFLine 129
IF (time%yrs == time%nbyr .and. time%day_end > 0) THEN Lines 133-136
 134 time%day_end_yr = time%day_end
 135 time%day_end_yr =  amin0 (time%day_end_yr, ndays(13))  ! if user inputs 366 on non-leap year
END IFLine 136
IF (time%yrs > pco%nyskip) THEN Lines 139-141
 140 time%yrs_prt = time%yrs_prt + float(time%day_end_yr - time%day_start + 1)
 141 time%days_prt = time%days_prt + float(time%day_end_yr - time%day_start + 1)
END IFLine 141
ELSE Lines 142-145
tell user they are skipping more years than simulating (line 143)
 144 time%yrs_prt = time%nbyr
END IF Line 145
IF (pco%sw_init == "n") THEN Lines 148-154
IF (time%yrs > pco%nyskip) THEN Lines 149-153
 150 call basin_sw_init
 151 call aqu_pest_output_init
 152 pco%sw_init = "y"  !! won't reset again
END IFLine 153
END IFLine 154
DO julian_day = time%day_start, time%day_end_yr !! begin daily loop
determine month and day of month - time%mo and time%day_mo (line 158)
Uncomment next three lines for DEBUG version only (line 164)
check for end of month, year and simulation (line 172)
check time interval for daily printing (line 198)
check time interval for daily printing (line 198)
initialize variables at beginning of day for hru's (line 215)
conditional reset of land use and management (line 224)
allocate water for water rights objects (line 234)
allocate water for water rights objects (line 234)
allocate manure to appropriate demand objects (line 243)
allocate manure to appropriate demand objects (line 243)
perform end-of-year processes (line 276)
write annual basin crop yields and harvested areas (line 280)
write annual basin crop yields and harvested areas (line 280)
update simulation year (line 370)
write reservoir trap efficiencies (line 390)
ave annual calibration output and reset time for next simulation (line 396)
 157 time%day = julian_day
 159 call xmon (time%day, mo, day_mo)
 160 time%mo = mo
 161 time%day_mo = day_mo
 163 time%yrc_tot = time%yrc_end - time%yrc_start + 1
 166 call DATE_AND_TIME (b(1), b(2), b(3), date_time)
 167 write (*,1234) cal_sim, time%mo, time%day_mo, time%yrc, time%yrs, time%yrc_tot,    &
 168 date_time(5), date_time(6), date_time(7)
 169 write (9003,1234) cal_sim, time%mo, time%day_mo, time%yrc, time%yrs, time%yrc_tot, &
 170 date_time(5), date_time(6), date_time(7)
 173 time%end_mo = 0
 174 time%end_yr = 0
 175 time%end_sim = 0
 216 if (sp_ob%hru > 0) call sim_initday
 218 if (time%yrs > pco%nyskip) ndmo(time%mo) = ndmo(time%mo) + 1
 220 call climate_control      !! read in/generate weather
 222 call cli_atmodep_time_control     !! set array counter for atmospheric deposition
 250 call command              !! command loop
 274 end do              !! end daily loop
 278 call calsoft_sum_output
 371 time%yrc = time%yrc + 1
 372 end do            !!     end annual loop
 397 call calsoft_ave_output
 398 yrs_print = time%yrs_prt
 399 time = time_init
 401 return
 402 1234 format (1x, a, 2i4, 2x,i4,' Yr ', i4,' of ', i4, " Time",2x,i2,":",i2,":",i2)
IF (time%end_aa_prt == 1) THEN Lines 176-179
 177 time%end_aa_prt = 0
 178 time%prt_int_cur = 0.
END IFLine 179
IF (time%day == ndays(time%mo+1)) THEN Lines 180-182
 181 time%end_mo = 1
END IFLine 182
IF (time%day == time%day_end_yr) THEN Lines 183-196
 184 time%end_yr = 1
IF (time%yrs == time%nbyr) THEN Lines 185-188
 186 time%end_sim = 1
 187 time%yrs_prt = time%yrs_prt / (365. + (time%num_leap / time%nbyr))
END IFLine 188
IF (pco%aa_numint > 0) THEN Lines 189-195
IF (time%yrc == pco%aa_yrs(time%prt_int_cur)) THEN Lines 190-194
 191 time%end_aa_prt = 1
 192 time%yrs_prt_int = time%yrs_prt_int / (365. + (time%num_leap / time%nbyr))
 193 time%prt_int_cur = time%prt_int_cur + 1
END IFLine 194
END IFLine 195
END IFLine 196
IF (pco%day_print_over == "n") THEN Lines 199-213
IF (pco%day_print == "n") THEN Lines 200-203
IF (time%day >= pco%day_start .and. time%yrc >= pco%yrc_start) THEN Lines 201-203
 202 pco%day_print = "y"
END IFLine 203
END IFLine 203
ELSE Lines 204-212
IF (time%day > pco%day_end .and. time%yrc == pco%yrc_end) THEN Lines 205-207
 206 pco%day_print = "n"
 207 pco%day_print_over = "y"
END IFLine 207
ELSE Lines 208-211
 209 pco%int_day_cur = pco%int_day_cur + 1
 210 if (pco%int_day_cur > pco%int_day) pco%int_day_cur = 1
END IF Line 211
END IF Line 212
END IFLine 213
DO iupd = 1, db_mx%cond_up Lines 225-232
 226 id = upd_cond(iupd)%cond_num
 227 d_tbl => dtbl_scen(id)
DO j = 1, sp_ob%hru Lines 228-231
 229 call conditions (j, id)
 230 call actions (j, iob, id)
END DOLine 231
END DOLine 232
IF (db_mx%wallo_db > 0) THEN Lines 235-241
DO iwallo = 1, db_mx%wallo_db Lines 236-240
if a channel is not an object, call at beginning of day (line 237)
 238 j = iwallo    ! to avoid a compiler warning
 239 if (wallo(iwallo)%cha_ob == "n") call wallo_control (j)
END DOLine 240
END IFLine 241
IF (db_mx%mallo_db > 0) THEN Lines 244-248
DO imallo = 1, db_mx%mallo_db Lines 245-247
 246 call mallo_control (imallo)
END DOLine 247
END IFLine 248
IF (time%day == 181) THEN Lines 254-272
DO ihru = 1, sp_ob%hru Lines 255-271
 256 iob = sp_ob1%hru + ihru - 1
IF (ob(iob)%lat < 0) THEN Lines 257-270
zero yearly irrigation for dtbl conditioning jga6-25 (line 258)
 259 hru(ihru)%irr_yr = 0.
 261 phubase(ihru) = 0.
 262 yr_skip(ihru) = 0
 263 isched = hru(ihru)%mgt_ops
IF (isched > 0 .and. sched(isched)%num_ops > 0) THEN Lines 264-269
 265 if (sched(isched)%mgt_ops(hru(ihru)%cur_op)%op == "skip") hru(ihru)%cur_op = hru(ihru)%cur_op + 1
IF (hru(ihru)%cur_op > sched(isched)%num_ops) THEN Lines 266-268
 267 hru(ihru)%cur_op = 1
END IFLine 268
END IFLine 269
END IFLine 270
END DOLine 271
END IFLine 272
IF (sp_ob%hru > 0) THEN Lines 281-298
DO iplt = 1, basin_plants Lines 282-297
 283 crop_yld_t_ha = bsn_crop_yld(iplt)%yield / (bsn_crop_yld(iplt)%area_ha + 1.e-6)
 284 write (5100,*) time%yrc, iplt, plts_bsn(iplt), bsn_crop_yld(iplt)%area_ha,            &
 285 bsn_crop_yld(iplt)%yield, crop_yld_t_ha
 286 bsn_crop_yld_aa(iplt)%area_ha = bsn_crop_yld_aa(iplt)%area_ha + bsn_crop_yld(iplt)%area_ha
 287 bsn_crop_yld_aa(iplt)%yield = bsn_crop_yld_aa(iplt)%yield + bsn_crop_yld(iplt)%yield
 288 bsn_crop_yld(iplt) = bsn_crop_yld_z
IF (time%end_sim == 1) THEN Lines 289-296
 290 crop_yld_t_ha = bsn_crop_yld_aa(iplt)%yield / (bsn_crop_yld_aa(iplt)%area_ha + 1.e-6)
 291 bsn_crop_yld_aa(iplt)%area_ha = bsn_crop_yld_aa(iplt)%area_ha / time%yrs_prt
 292 bsn_crop_yld_aa(iplt)%yield = bsn_crop_yld_aa(iplt)%yield / time%yrs_prt
 293 write (5101,*) time%yrc, iplt, plts_bsn(iplt), bsn_crop_yld_aa(iplt)%area_ha,   &
 294 bsn_crop_yld_aa(iplt)%yield, crop_yld_t_ha
 295 bsn_crop_yld_aa(iplt) = bsn_crop_yld_z
END IFLine 296
END DOLine 297
END IFLine 298
DO j = 1, sp_ob%hru_lte Lines 300-306
zero yearly balances after using them in soft data calibration (was in hru_lte_output) (line 301)
 302 hltwb_y(j) = hwbz
 303 hltnb_y(j) = hnbz
 304 hltpw_y(j) = hpwz
 305 hltls_y(j) = hlsz
END DOLine 306
DO ich = 1, sp_ob%chandeg Lines 308-315
zero yearly balances after using them in soft data calibration (was in sd_channel_output) (line 309)
 310 chsd_y(ich) = chsdz
 311 ch_stor_y(ich) = chaz
 312 ch_in_y(ich) = chaz
 313 ch_out_y(ich) = chaz
 314 ch_wat_y(ich) = wbodz
END DOLine 315
DO j = 1, sp_ob%hru Lines 317-368
zero yearly balances after using them in soft data calibration (was in hru_output) (line 318)
zero yearly pesticide balances after using them in soft data calibration (was in hru_output) (line 327)
zero yearly pesticide balances after using them in soft data calibration (was in hru_output) (line 327)
compute biological mixing at the end of every year (line 334)
update sequence number for year in rotation to that of (line 339)
the next year and reset sequence numbers for operations (line 340)
 319 sw_init = hwb_y(j)%sw_final
 320 sno_init = hwb_y(j)%sno_final
 321 hwb_y(j) = hwbz
 322 hwb_y(j)%sw_init = sw_init
 323 hwb_y(j)%sno_init = sno_init
 324 hnb_y(j) = hnbz
 325 hpw_y(j) = hpwz
 326 hls_y(j) = hlsz
 335 if (bsn_cc%cswat /= 2) then                                       !! fg added this because so that cbn_zhang2 can handle bio mixing directly
 336 if (hru(j)%hyd%biomix > 1.e-6) call mgt_newtillmix (j, hru(j)%hyd%biomix, 0)
 353 iob = sp_ob1%hru + j - 1
IF (cs_db%num_pests > 0) THEN Lines 328-332
DO ipest = 1, cs_db%num_pests Lines 329-331
 330 hpestb_y(j)%pest(ipest) = pestbz
END DOLine 331
END IFLine 332
DO ipl = 1, pcom(j)%npl Lines 341-349
 342 idp = pcom(j)%plcur(ipl)%idplt
IF (idp > 0) THEN Lines 343-348
IF (pldb(idp)%typ == "perennial") THEN Lines 344-347
 345 pcom(j)%plcur(ipl)%curyr_mat = pcom(j)%plcur(ipl)%curyr_mat + 1
 346 pcom(j)%plcur(ipl)%curyr_mat = Min(pcom(j)%plcur(ipl)%curyr_mat,pldb(idp)%mat_yrs)
END IFLine 347
END IFLine 348
END DOLine 349
IF (ob(iob)%lat >= 0) THEN Lines 354-367
 356 hru(ihru)%irr_yr = 0.
 358 phubase(j) = 0.
 359 yr_skip(j) = 0
 360 isched = hru(j)%mgt_ops
IF (isched > 0 .and. sched(isched)%num_ops > 0) THEN Lines 361-366
 362 if (sched(isched)%mgt_ops(hru(j)%cur_op)%op == "skip") hru(j)%cur_op = hru(j)%cur_op + 1
IF (hru(j)%cur_op > sched(isched)%num_ops) THEN Lines 363-365
 364 hru(j)%cur_op = 1
END IFLine 365
END IFLine 366
END IFLine 367
END DOLine 368
DO ich = 1, sp_ob%chandeg Lines 374-387
write channel morphology - downcutting and widening (line 375)
mm = t / (3.*bd*w*l) -> assume fp width = 3*chw; len(m)=1000.*km; bd=t/m3; mm=1000.*m (line 380)
 376 bank_mm = ch_morph(ich)%w_yr
 377 bed_mm = ch_morph(ich)%d_yr
 378 ch_morph(ich)%w_yr = ch_morph(ich)%w_yr / sd_ch(ich)%chw / time%yrs_prt
 379 ch_morph(ich)%d_yr = ch_morph(ich)%d_yr / sd_ch(ich)%chd / time%yrs_prt
 381 ch_morph(ich)%fp_mm = ch_morph(ich)%fp_mm / (3. * sd_ch(ich)%chw *           &
 382 sd_ch(ich)%chl) / time%yrs_prt
 383 iob = sp_ob1%chandeg + ich - 1
 384 write (7778,*) ich, ob(iob)%name, ob(iob)%area_ha, sd_ch(ich)%chw, bank_mm,  &
 385 ch_morph(ich)%w_yr, sd_ch(ich)%chd, bed_mm, ch_morph(ich)%d_yr,      &
 386 ch_morph(ich)%fp_mm
END DOLine 387
DO ich = 1, sp_ob%res Lines 389-394
END DOLine 394
END DO
END DO
Allocations
n/a
Calls
Procedures Called
List of procedures called by this Subroutine.
xmon
cli_precip_control
amin0
float
basin_sw_init
aqu_pest_output_init
sim_initday
climate_control
cli_atmodep_time_control
conditions
actions
wallo_control
mallo_control
command
calsoft_sum_output
mgt_newtillmix
calsoft_ave_output
Call Graph
Visual representation of procedures called by this Subroutine.
Call graph
time_control calls actions, amin0, aqu_pest_output_init, basin_sw_init, calsoft_ave_output, calsoft_sum_output, cli_atmodep_time_control, cli_precip_control, climate_control, command, conditions, float, mallo_control, mgt_newtillmix, sim_initday, wallo_control, xmon