wallo_control – test-src-project
wallo_control Subroutine
106 statements
Source File
subroutine wallo_control(iwallo)
Uses
plant_module
hru_module
basin_module
hydrograph_module
soil_module
constituent_mass_module
water_allocation_module
time_module
organic_mineral_mass_module
Arguments
Type Intent Optional Attributes Name
integer, intent(inout) :: iwallo
I/O
I/O units used in this subroutine.
Unit Type Filename
unit_2612 Output not specified
Outside Variables and Types
type(plant_community) (1 attribute from plant_module)
Attribute Name Description
pcom
type(hydrologic_response_unit) (1 attribute from hru_module)
Attribute Name Description
hru
real (7 attributes from hru_module)
Attribute Name Description
sol_sumno3
sol_sumsolp
phubase
dmd_m3
m3 |demand
Read more…
div_volume_daily
daily volume of canal water added to total
div_volume_total
volume of canal water available for irrigation
div_delay
number of days that diverted irrigation water can be used
type (8 attributes from basin_module)
Attribute Name Description
pco%mgtout None
cs_db%num_salts None
cs_db%num_cs None
time%yrc None
time%mo None
time%day None
time%day_mo None
time%yrs None
type(hyd_output) (3 attributes from hydrograph_module)
Attribute Name Description
hd
hz
trt
wastewater treatment plants
type(irrigation_water_transfer) (1 attribute from hydrograph_module)
Attribute Name Description
irrig
dimension by hru
type(recall_hydrograph_inputs) (1 attribute from hydrograph_module)
Attribute Name Description
recall
type(soil_profile) (1 attribute from soil_module)
Attribute Name Description
soil
type(source_output) (1 attribute from water_allocation_module)
Attribute Name Description
walloz
type(water_allocation) (1 attribute from water_allocation_module)
Attribute Name Description
wallo
dimension by water allocation objects
type(water_allocation_output) (1 attribute from water_allocation_module)
Attribute Name Description
wallod_out
dimension by demand objects
type(soil_profile_mass) (1 attribute from organic_mineral_mass_module)
Attribute Name Description
soil1
type(plant_community_mass) (1 attribute from organic_mineral_mass_module)
Attribute Name Description
pl_mass
!! Bang Comments
check if canal or inflow diversions and set available water from recall object set total volumes of canal diversions (source = "div") - rtb set total volumes of inflow diversions from recall file set total volumes of inflow diversions from monthly flow rate (m3/s) loop through each demand object zero demand, withdrawal, and unmet for each source set demand for each object if demand - check source availability check if water is available from each source - set withdrawal and unmet loop through sources again to check if compensation is allowed compute total withdrawal for demand object from all sources if irrigating set amount applied and runoff irrigation demand treatment of withdrawn water no treatment - treated = withdrawal compute treatment by inputting the mass or concentrations transfer (diversion) of withdrawn and possibly treated water sum demand, withdrawal, and unmet for entire allocation object
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure.
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
  28 wallo(iwallo)%tot = walloz
DO isrc = 1,wallo(iwallo)%src_obs Lines 31-61
IF (wallo(iwallo)%src(isrc)%ob_typ == "div") THEN Lines 33-47
  34 irec = wallo(iwallo)%src(isrc)%ob_num !number in recall.rec
  36 div_daily = recall(irec)%hd(time%day,time%yrs)%flo * (-1) !m3; make positive
  40 div_total = div_volume_daily(irec) !m3
  41 div_volume_daily(irec) = ((1.-div_delay)*div_daily) + (div_delay*div_total) !m3
  46 div_volume_total(irec) = div_volume_total(irec) + div_volume_daily(irec) !m3
IF (div_daily > 0) THEN Lines 37-39
  38 dum = 10
END IFLine 39
IF (div_volume_daily(irec) < 1.e-6) THEN Lines 42-44
  43 div_volume_daily(irec) = 0.
END IFLine 44
END IFLine 47
IF (wallo(iwallo)%src(isrc)%ob_typ == "div_rec") THEN Lines 50-54
  51 irec = wallo(iwallo)%src(isrc)%rec_num !number in recall.rec
  53 wallo(iwallo)%src(isrc)%div_vol = recall(irec)%hd(time%day,time%yrs)%flo !m3
END IFLine 54
IF (wallo(iwallo)%src(isrc)%ob_typ == "div_in") THEN Lines 57-60
  59 wallo(iwallo)%src(isrc)%div_vol = wallo(iwallo)%src(isrc)%limit_mon(time%mo) * 86400.
END IFLine 60
END DOLine 61
DO idmd = 1, wallo(iwallo)%dmd_obs
  72 call wallo_demand (iwallo, idmd)
DO isrc = 1, wallo(iwallo)%dmd(idmd)%dmd_src_obs Lines 67-69
  68 wallod_out(iwallo)%dmd(idmd)%src(isrc) = walloz
END DOLine 69
IF (wallod_out(iwallo)%dmd(idmd)%dmd_tot > 0.) THEN
  77 wallo(iwallo)%dmd(idmd)%hd = hz
  97 wallo(iwallo)%dmd(idmd)%withdr_tot = 0.
 136 end if      !if there is demand
 153 wallo(iwallo)%tot%demand = wallo(iwallo)%tot%demand + wallod_out(iwallo)%dmd(idmd)%dmd_tot
 154 wallo(iwallo)%tot%withdr = wallo(iwallo)%tot%withdr + wallo(iwallo)%dmd(idmd)%withdr_tot
 155 wallo(iwallo)%tot%unmet = wallo(iwallo)%tot%unmet + wallo(iwallo)%dmd(idmd)%unmet_m3
 157 end do        !demand object loop
 159 return
DO isrc = 1, wallo(iwallo)%dmd(idmd)%dmd_src_obs Lines 79-84
  80 dmd_m3 = wallod_out(iwallo)%dmd(idmd)%src(isrc)%demand
IF (dmd_m3 > 1.e-6) THEN Lines 81-83
  82 call wallo_withdraw (iwallo, idmd, isrc)
END IFLine 83
END DOLine 84
DO isrc = 1, wallo(iwallo)%dmd(idmd)%dmd_src_obs Lines 87-94
IF (wallo(iwallo)%dmd(idmd)%src(isrc)%comp == "y") THEN Lines 88-93
  89 dmd_m3 = wallo(iwallo)%dmd(idmd)%unmet_m3
IF (dmd_m3 > 1.e-6) THEN Lines 90-92
  91 call wallo_withdraw (iwallo, idmd, isrc)
END IFLine 92
END IFLine 93
END DOLine 94
DO isrc = 1, wallo(iwallo)%dmd(idmd)%dmd_src_obs Lines 98-101
  99 wallo(iwallo)%dmd(idmd)%withdr_tot = wallo(iwallo)%dmd(idmd)%withdr_tot +           &
 100 wallod_out(iwallo)%dmd(idmd)%src(isrc)%withdr
END DOLine 101
SELECT CASE (wallo(iwallo)%dmd(idmd)%ob_typ) Lines 104-134
CASE ("hru") Lines 106-133
IF (wallo(iwallo)%dmd(idmd)%withdr_tot > 0.) THEN Lines 107-133
 108 j = wallo(iwallo)%dmd(idmd)%ob_num
 109 irr_mm = wallo(iwallo)%dmd(idmd)%withdr_tot / (hru(j)%area_ha * 10.)      !mm = m3 / (ha * 10.)
 110 irrig(j)%applied = irr_mm * wallo(iwallo)%dmd(idmd)%irr_eff * (1. - wallo(iwallo)%dmd(idmd)%surq)
 111 irrig(j)%runoff = wallo(iwallo)%dmd(idmd)%amount * wallo(iwallo)%dmd(idmd)%surq
 112 pcom(j)%days_irr = 1            ! reset days since last irrigation
 126 hru(j)%irr_yr = hru(j)%irr_yr + irrig(j)%applied
IF (cs_db%num_salts > 0) THEN Lines 115-118
 116 jj = idmd !to avoid a compiler warning
 117 call salt_irrig(iwallo,jj,j)
END IFLine 118
IF (cs_db%num_cs > 0) THEN Lines 120-123
 121 jj = idmd !to avoid a compiler warning
 122 call cs_irrig(iwallo,jj,j)
END IFLine 123
IF (pco%mgtout == "y") THEN Lines 128-132
 129 write (2612, *) j, time%yrc, time%mo, time%day_mo, wallo(iwallo)%name, "IRRIGATE", phubase(j),  &
 130 pcom(j)%plcur(1)%phuacc, soil(j)%sw, pl_mass(j)%tot(1)%m, soil1(j)%rsd(1)%m,           &
 131 sol_sumno3(j), sol_sumsolp(j), irrig(j)%applied
END IFLine 132
END IFLine 133
END SELECTLine 134
IF (wallo(iwallo)%dmd(idmd)%treat_typ == "out") THEN Lines 139-141
 141 wallo(iwallo)%dmd(idmd)%trt = wallo(iwallo)%dmd(idmd)%hd
END IFLine 141
ELSE Lines 142-145
 144 call wallo_treatment (iwallo, idmd)
END IF Line 145
IF (wallo(iwallo)%dmd(idmd)%rcv_ob /= "null") THEN Lines 148-150
 149 call wallo_transfer (iwallo, idmd)
END IFLine 150
END IF
END DO
Allocations
n/a
Calls
Calls
Procedures called by this subroutine.
Local Variables
Type Visibility Attributes Name Initial
integer, private :: idmd
integer, private :: isrc
integer, private :: j
integer, private :: jj
integer, private :: irec
integer, private :: dum
real, private :: irr_mm
real, private :: div_total
real, private :: div_daily
Variables
Type Visibility Attributes Name Initial
integer, public :: iwallo
Call graph
wallo_control calls cs_irrig, salt_irrig, wallo_demand, wallo_transfer, wallo_treatment, wallo_withdraw