wetland_control – TestDataProject
wetland_control Subroutine
203 statements
Source File
subroutine wetland_control()
Called From
n/a
Arguments
n/a
Outside Variables and Types
type(reservoir_data_char_input) (1 attribute from reservoir_data_module)
Attribute Name Description
wet_dat_c
type(reservoir_data) (1 attribute from reservoir_data_module)
Attribute Name Description
wet_dat
type(wetland_hyd_data) (1 attribute from reservoir_data_module)
Attribute Name Description
wet_hyd
type(water_body_data_parameters) (2 attributes from reservoir_data_module)
Attribute Name Description
wet_prm
wbody_prm
used for reservoir and wetlands
type (25 attributes from basin_module)
Attribute Name Description
bsn_cc%gwflow None
bsn_prm%prf None
pco%nyskip None
time%yrs None
time%step None
ht2%flo None
ht2%sag None
ht2%no3 None
ht2%sed None
ht2%solp None
ht2%sil None
ht2%lag None
ht2%grv None
ht2%cla None
ht2%orgn None
ht2%san None
ht2%sedp None
wbody%flo None
wbody%no3 None
wbody%sed None
wbody%solp None
wbody%orgn None
wbody%nh3 None
wbody%sedp None
w%precip None
type(decision_table) (2 attributes from conditional_module)
Attribute Name Description
dtbl_res
d_tbl
type(soil_profile) (1 attribute from soil_module)
Attribute Name Description
soil
integer (3 attributes from hydrograph_module)
Attribute Name Description
icmd
|
ihru
none |HRU number
Read more…
mgt_ops
type(hyd_output) (7 attributes from hydrograph_module)
Attribute Name Description
hd
ht1
wet
wet_seep_day
Jaehak 2022 wetland seepage volume
resz
wet_in_d
wet_out_d
type(object_connectivity) (1 attribute from hydrograph_module)
Attribute Name Description
ob
type(irrigation_water_transfer) (1 attribute from hydrograph_module)
Attribute Name Description
irrig
dimension by hru
type(management_schedule) (1 attribute from mgt_operations_module)
Attribute Name Description
sched
type(wetland) (1 attribute from reservoir_module)
Attribute Name Description
wet_ob
type(hydrologic_response_unit) (1 attribute from hru_module)
Attribute Name Description
hru
real (19 attributes from hru_module)
Attribute Name Description
qp_cms
pet_day
sanyld
silyld
clayld
sagyld
lagyld
grayld
tconc
usle_cfac
cklsp
sedminpa
sedminps
sedorgn
sedorgp
sedyld
surfq
surqno3
hhsurfq
type(soil_profile_mass) (1 attribute from organic_mineral_mass_module)
Attribute Name Description
soil1
type(water_body) (2 attributes from water_body_module)
Attribute Name Description
wet_wat_d
wbody_wb
used for reservoir and wetlands
Uses
reservoir_data_module
basin_module
conditional_module
time_module
soil_module
hydrograph_module
mgt_operations_module
constituent_mass_module
reservoir_module
hru_module
channel_module
organic_mineral_mass_module
water_body_module
gwflow_module
climate_module
aquifer_module
I/O
n/a
Local Variables
Type Visibility Attributes Name Initial
real, public :: bypass = 1.
integer, public :: j = 0
real, public :: x1 = 0.
real, public :: wet_h = 0.
real, public :: wet_h1 = 0.
integer, public :: ised = 0
integer, public :: irel = 0
integer, public :: icon = 0
integer, public :: ires = 0
integer, public :: j1 = 0
integer, public :: ii = 0
integer, public :: ihyd = 0
integer, public :: isched = 0
real, public :: wet_fr = 0.
real, public :: pvol_m3 = 0.
real, public :: evol_m3 = 0.
real, public :: dep = 0.
real, public :: weir_hgt = 0.
real, public :: wsa1 = 0.
real, public :: sedppm = 0.
real, public :: no3ppm = 0.
real, public :: seep_rto = 0.
real, public :: qp_cms = 0.
real, public :: dep_init = 0.
real, public :: volseep = 0.
real, public :: volex = 0.
real, public :: swst(20) = 0.
Control Flow
Control Flow Graph
Visual representation of the execution flow within this procedure. Use mouse wheel to zoom, drag to pan.
Reset Zoom Help
Logic Blocks
Control flow structures organized as they appear in the source code. Each block is collapsible to help navigate complex procedures.
zero outgoing flow (line 59)
set water body pointer to res (line 63)
initialize variables for wetland daily simulation (line 69)
add precipitation - mm*ha*10.=m3 (used same area for infiltration and soil evap) (line 74)
add irrigation water to the paddy/wetland storage (line 79)
update wetland surface area - solve quadratic to find new depth (line 84)
   6 surqno3, sedorgn, sedorgp, ihru, pet_day, surfq, tconc, usle_cfac, cklsp, hhsurfq
  50 j = ihru
  51 ires = hru(j)%dbs%surf_stor
  52 ihyd = wet_dat(ires)%hyd
  53 ised = wet_dat(ires)%sed
  54 irel = wet_dat(ires)%release
  55 wsa1 = hru(j)%area_ha * 10.
  56 isched = hru(j)%mgt_ops
  57 wet_wat_d(j)%area_ha = hru(j)%area_ha
  60 ht2 = resz
  64 wbody => wet(j)
  65 wbody_wb => wet_wat_d(j)
  66 wbody_prm => wet_prm(j)
  70 hru(j)%water_seep = 0.
  71 wet_ob(j)%depth = wet(j)%flo / wsa1 / 1000. !m
  72 dep_init = wet_ob(j)%depth !m
  75 wet_wat_d(j)%precip = w%precip * wsa1 !m3
  76 wet_ob(j)%depth = wet_ob(j)%depth + w%precip / 1000.  !m  Jaehak 2022
  77 wet(j)%flo =  wet(j)%flo + wet_wat_d(j)%precip !m3
  80 wet(j)%flo =  wet(j)%flo + irrig(j)%applied * wsa1 !m3
  81 wet(j)%no3 = wet(j)%no3 + irrig(j)%no3 * irrig(j)%applied * wsa1 * 0.001 !kg
  83 if (wet(j)%flo > 0.) then  !paddy is assumed flat
  85 x1 = wet_hyd(j)%bcoef ** 2 + 4. * wet_hyd(j)%ccoef * (1. - wet(j)%flo / (wet_ob(j)%pvol + 1.e-9))
IF (x1 < 1.e-6) THEN Lines 86-87
  87 wet_h = 0.
END IFLine 87
ELSE Lines 88-91
  89 wet_h1 = (-wet_hyd(j)%bcoef - sqrt(x1)) / (2. * wet_hyd(j)%ccoef + 1.e-9)
  90 wet_h = wet_h1 + wet_hyd(j)%bcoef
END IF Line 91
infiltration of the standing water to the topsoil layer. (line 103)
Any excess infiltration volume estimated here is reverted (back to waterbody) in swr_satexcess. (line 104)
  92 wet_fr = (1. + wet_hyd(j)%acoef * wet_h)
  93 wet_fr = min(wet_fr,1.)
  94 wet_fr = max(wet_fr,0.01)
  97 if (wet_dat_c(ires)%hyd.ne.'paddy') wet_wat_d(j)%area_ha = hru(j)%area_ha * wet_fr
 100 if(bsn_cc%gwflow == 1) then !rtb gwflow
 101 call gwflow_wetl(j)
 102 else !original seepage calculations
 105 wet_wat_d(j)%seep = min(wet(j)%flo, hru(j)%wet_hc * 24. * wet_wat_d(j)%area_ha * 10.) !m3
 106 end if !check for gwflow
 110 volseep = wet_wat_d(j)%seep / wsa1 !mm
IF (volseep>0.1) THEN Lines 111-135
 124 volex = 0
 134 wet_wat_d(j)%seep = max(0., wet_wat_d(j)%seep - volex * wsa1) !m3
DO j1 = 1, soil(j)%nly Lines 112-121
 113 swst(j1) = soil(j)%phys(j1)%st + volseep
 114 if (swst(j1)>soil(j)%phys(j1)%ul*0.9) then !oversaturated Jaehak 2022
 115 volex = swst(j1) - soil(j)%phys(j1)%ul*0.9  !excess water. soil is assumed to remain saturated Jaehak 2022
 116 volseep = min(volex, soil(j)%phys(j1)%k*24.)
 117 swst(j1) = swst(j1) - volseep
 119 volseep = 0
END DOLine 121
DO j1 = soil(j)%nly, 1, -1 Lines 125-131
 126 swst(j1) = swst(j1) + volex
 127 if (swst(j1)>soil(j)%phys(j1)%ul*0.9) then !oversaturated
 128 volex = max(0., swst(j1) - soil(j)%phys(j1)%ul*0.9)  !excess water.
 129 swst(j1) = swst(j1) - volex                         !update soil water
END DOLine 131
END IFLine 135
 137 wet(j)%flo = wet(j)%flo - wet_wat_d(j)%seep
 139 hru(j)%water_seep = wet_wat_d(j)%seep / wsa1   !mm=m3/(10*ha)
IF (wet_wat_d(j)%seep + wet(j)%flo > 0.01) THEN Lines 142-143
 143 seep_rto = wet_wat_d(j)%seep / (wet_wat_d(j)%seep + wet(j)%flo)
END IFLine 143
ELSE Lines 144-146
 145 seep_rto = 0.
END IF Line 146
if not a floodplain wetland (line 168)
calc release from decision table (line 170)
 147 soil1(j)%mn(1)%no3 = soil1(j)%mn(1)%no3 + wet(j)%no3 * seep_rto / hru(j)%area_ha !kg/ha
 148 soil1(j)%mn(1)%nh4 = soil1(j)%mn(1)%nh4 + wet(j)%nh3 * seep_rto / hru(j)%area_ha !kg/ha
 149 soil1(j)%mp(1)%act = soil1(j)%mp(1)%act + wet(j)%solp * seep_rto / hru(j)%area_ha !kg/ha
 150 soil1(j)%water(1)%n = soil1(j)%water(1)%n + wet(j)%orgn * seep_rto / hru(j)%area_ha !kg/ha
 151 soil1(j)%water(1)%p = soil1(j)%water(1)%p + wet(j)%sedp * seep_rto / hru(j)%area_ha !kg/ha
 154 wet_seep_day(j)%no3 = wet(j)%no3 * seep_rto !kg
 155 wet_seep_day(j)%nh3 = wet(j)%nh3 * seep_rto
 156 wet_seep_day(j)%orgn = wet(j)%orgn * seep_rto
 157 wet_seep_day(j)%solp = wet(j)%solp * seep_rto
 158 wet_seep_day(j)%sedp = wet(j)%sedp * seep_rto
 161 wet(j)%no3 = wet(j)%no3 - wet_seep_day(j)%no3
 162 wet(j)%nh3 = wet(j)%nh3 - wet_seep_day(j)%nh3
 163 wet(j)%orgn = wet(j)%orgn - wet_seep_day(j)%orgn
 164 wet(j)%solp = wet(j)%solp - wet_seep_day(j)%solp
 165 wet(j)%sedp = wet(j)%sedp - wet_seep_day(j)%sedp
 171 d_tbl => dtbl_res(irel)
 172 wbody => wet(j)
 173 wbody_wb => wet_wat_d(j)
 174 pvol_m3 = wet_ob(j)%pvol
 175 evol_m3 = wet_ob(j)%evol
IF (hru(j)%area_ha > 1.e-6) THEN Lines 177-179
 179 dep = wet(j)%flo / wsa1 / 1000.    !m
END IFLine 179
ELSE Lines 180-182
 181 dep = 0.
END IF Line 182
weir discharge (ht2) by decision tables (line 186)
 183 weir_hgt = wet_ob(j)%weir_hgt   !m
 184 wet_ob(j)%depth = dep           !m
 187 call conditions (j, irel)
 188 call res_hydro (j, irel, pvol_m3, evol_m3)
IF (hru(j)%area_ha > 1.e-6) THEN Lines 190-192
 192 dep = wet(j)%flo / wsa1 / 1000.    !m
END IFLine 192
ELSE Lines 193-195
 194 dep = 0.
END IF Line 195
IF (sched(isched)%num_autos == 0.and.dep>0.01) THEN Lines 197-200
 198 call res_weir_release (j, irel, ihyd, evol_m3, dep, weir_hgt)
 199 wet(j)%flo = wbody%flo
END IFLine 200
subtract outflow from storage (line 203)
 205 surfq(j) = ht2%flo / wsa1 !mm
IF (time%step > 1) THEN Lines 207-212
DO ii = 1, time%step Lines 208-211
daily total runoff (line 209)
 210 hhsurfq(j,ii) = surfq(j) / real(time%step)
END DOLine 211
END IFLine 212
compute sediment deposition (line 217)
perform reservoir nutrient balance (line 222)
perform salt ion constituent balance (line 230)
perform wetland constituent balance (line 233)
 215 wet_ob(j)%depth = wet(j)%flo / wsa1 / 1000. !m
 218 call res_sediment
 220 wet(j)%sed = wbody%sed !t
 223 call res_nutrient (j)
 225 wet(j)%no3 = wbody%no3
 226 wet(j)%nh3 = wbody%nh3
 227 wet(j)%orgn =wbody%orgn
 228 wet(j)%sedp = wbody%sedp
 229 wet(j)%solp = wbody%solp
 231 call wet_salt(icmd,j)
 234 icon = wet_dat(ires)%cs
 235 call wet_cs(icmd,icon,j)
IF (dep_init<0.0001 .and. ht2%flo>0.) THEN Lines 238-246
 239 call ero_cfactor
 240 qp_cms = bsn_prm%prf / 6578.6 * hru(j)%area_ha * surfq(j) / tconc(j) / 35.3
 241 cklsp(j) = usle_cfac(j) * hru(j)%lumv%usle_mult
 242 wet(j)%sed = (10. * surfq(j) * qp_cms * hru(j)%area_ha) ** .56 * cklsp(j) !tons
 243 sedyld(j) = wet(j)%sed * ht2%flo / (wet(j)%flo + ht2%flo)
 244 wet(j)%sed = max(0., wet(j)%sed - sedyld(j)) !tons
 245 ht2%sed = sedyld(j) !tons sediment yield
END IFLine 246
IF (wet(j)%flo>0) THEN Lines 248-250
 249 sedppm=wet(j)%sed/wet(j)%flo*1000000.
 250 no3ppm=wet(j)%no3/wet(j)%flo*1000.
END IFLine 250
ELSE Lines 251-254
 252 sedppm=0
 253 no3ppm=0
END IF Line 254
perform reservoir pesticide transformations (line 259)
set values for routing variables (line 262)
set inflow and outflow variables for reservoir_output (line 283)
 263 ob(icmd)%hd(1)%temp = 0.                  !!undefined
 266 sedyld(j) = ht2%sed + sedyld(j) * bypass
 267 sanyld(j) = ht2%san + sanyld(j) * bypass
 268 silyld(j) = ht2%sil + silyld(j) * bypass
 269 clayld(j) = ht2%cla + clayld(j) * bypass
 270 sagyld(j) = ht2%sag + sagyld(j) * bypass
 271 lagyld(j) = ht2%lag + lagyld(j) * bypass
 272 grayld(j) = ht2%grv + grayld(j) * bypass
 275 sedorgn(j) = ht2%orgn / hru(j)%area_ha + sedorgn(j) * bypass
 276 sedorgp(j) = ht2%sedp / hru(j)%area_ha + sedorgp(j) * bypass
 277 surqno3(j) = ht2%no3/ hru(j)%area_ha  + surqno3(j) * bypass
 280 sedminps(j) = ht2%solp / hru(j)%area_ha / 2. + sedminps(j) * bypass
 281 sedminpa(j) = ht2%solp / hru(j)%area_ha / 2. + sedminpa(j) * bypass
IF (time%yrs > pco%nyskip) THEN Lines 284-287
 285 wet_in_d(j) = wet_in_d(j) + ht1
 286 wet_out_d(j) = ht2
END IFLine 287
 289 return
Allocations
n/a
Calls
Procedures Called
List of procedures called by this Subroutine.
gwflow_wetl
conditions
res_hydro
res_weir_release
res_sediment
res_nutrient
wet_salt
wet_cs
ero_cfactor
Call Graph
Visual representation of procedures called by this Subroutine.
Call graph
wetland_control calls conditions, ero_cfactor, gwflow_wetl, res_hydro, res_nutrient, res_sediment, res_weir_release, wet_cs, wet_salt