main – TestDataProject
main Program
96 statements
Source File
Uses
time_module
calibration_data_module
hydrograph_module
maximum_data_module
hru_module
!! for Luis only
!! for Luis only
read decision table data for conditional management initialize carbon and nutrient contents for each hru simulate watershed processes export coefficient - average annual write output for SWIFT input write successful completion to screen and file
Calls
Variables
Type Attributes Name Initial
integer :: date_time(8)
character(len=10) :: b(3)
integer :: iob = 0
integer, allocatable, dimension(:) :: cmd_next
Call graph
main calls cal_cond_read, cal_parmchg_read, calhard_control, calsoft_control, cli_lapse, command, cs_cha_read, dr_db_read, dr_ru, dtbl_flocon_read, dtbl_lum_read, dtbl_res_read, dtbl_scen_read, exco_db_read, hru_dtbl_actions_init, hru_lte_read, hyd_connect, hyd_connect_out, lsu_read_elements, manure_allocation_read, object_read_output, om_water_init, path_cha_res_read, pest_cha_res_read, proc_aqu, proc_bsn, proc_cal, proc_cha, proc_cond, proc_date_time, proc_db, proc_hru, proc_open, proc_read, proc_res, res_read_weir, salt_cha_read, soil_nutcarb_init, swift_output, time_control, treat_read_om, unit_hyd_ru_hru, water_allocation_read, wet_all_initial, wet_fp_init, wet_read, wet_read_hyd, wet_read_salt_cs