aqu_pesticide_module – test-src-project
aqu_pesticide_module Module
116 statements
Source File
routines for swatdeg_hru module
Used by
Variables
Type Visibility Attributes Name Initial
type(aqu_pesticide_processes), public :: aqu_pestbz
type(aqu_pesticide_output), public, dimension(:), allocatable, save :: aqupst_d
type(aqu_pesticide_output), public, dimension(:), allocatable, save :: aqupst_m
type(aqu_pesticide_output), public, dimension(:), allocatable, save :: aqupst_y
type(aqu_pesticide_output), public, dimension(:), allocatable, save :: aqupst_a
type(aqu_pesticide_output), public :: baqupst_d
type(aqu_pesticide_output), public :: baqupst_m
type(aqu_pesticide_output), public :: baqupst_y
type(aqu_pesticide_output), public :: baqupst_a
type(aqu_pesticide_output), public :: aqupst
type(aqu_pesticide_output), public :: aqupstz
type(aqu_pesticide_header), public :: aqupest_hdr
Interfaces
public interface operator (+)
public function aqupest_add(aqu1, aqu2) result(aqu3)
Arguments
Type Intent Optional Attributes Name
type(aqu_pesticide_processes), intent(in) :: aqu1
type(aqu_pesticide_processes), intent(in) :: aqu2
Return Value type(aqu_pesticide_processes)
Called by
public interface operator (.sum.)
public function aqupest_add_all(aqu1, aqu2) result(aqu3)
Arguments
Type Intent Optional Attributes Name
type(aqu_pesticide_processes), intent(in) :: aqu1
type(aqu_pesticide_processes), intent(in) :: aqu2
Return Value type(aqu_pesticide_processes)
Called by
public interface operator (/)
public function aqupest_div(aqu1, const) result(aqu2)
Arguments
Type Intent Optional Attributes Name
type(aqu_pesticide_processes), intent(in) :: aqu1
real, intent(in) :: const
Return Value type(aqu_pesticide_processes)
Called by
public interface operator (//)
public function aqupest_ave(aqu1, const) result(aqu2)
Arguments
Type Intent Optional Attributes Name
type(aqu_pesticide_processes), intent(in) :: aqu1
real, intent(in) :: const
Return Value type(aqu_pesticide_processes)
Called by
Derived Types
type, public :: aqu_pesticide_processes
Components
Type Visibility Attributes Name Initial
real, public :: tot_in = 0.
kg !total pesticide into aquifer
Read more…
real, public :: sol_flo = 0.
kg !soluble pesticide out of aquifer
Read more…
real, public :: sor_flo = 0.
kg !sorbed pesticide out of aquifer
Read more…
real, public :: sol_perc = 0.
kg !sorbed pesticide out of aquifer
Read more…
real, public :: react = 0.
kg !pesticide lost through reactions
Read more…
real, public :: metab = 0.
kg !amount of pesticide metabolized from parent
Read more…
real, public :: stor_ave = 0.
kg !average end of day pesticide in aquifer during the time period
Read more…
real, public :: stor_init = 0.
kg !pesticide in aquifer at the start of the day
Read more…
real, public :: stor_final = 0.
kg !pesticide in aquifer at the end of the day
Read more…
type, public :: aqu_pesticide_output
Components
Type Visibility Attributes Name Initial
type(aqu_pesticide_processes), public, dimension (:), allocatable :: pest
pesticide hydrographs
type, public :: aqu_pesticide_header
Components
Type Visibility Attributes Name Initial
character(len=6), public :: day = "jday"
character(len=6), public :: mo = "mon"
character(len=6), public :: day_mo = "day"
character(len=6), public :: yrc = "yr"
character(len=8), public :: isd = "unit "
character(len=8), public :: id = " gis_id "
character(len=16), public :: name = " name"
character(len=16), public :: pest = " pesticide"
character(len=13), public :: tot_in = "tot_in_kg "
(mg)
character(len=13), public :: sol_out = "sol_flo_kg"
(mg)
character(len=13), public :: sor_out = "sor_flo_kg"
(mg)
character(len=13), public :: sol_perc = "sol_perc_kg"
(mg)
character(len=13), public :: react = "react_kg"
(mg)
character(len=13), public :: metab = "metab_kg"
(mg)
character(len=13), public :: stor_ave = "stor_ave_kg"
(mg)
character(len=13), public :: stor_init = "stor_init_kg"
(mg)
character(len=13), public :: stor_final = "stor_final_kg"
(mg)
Functions
public function aqupest_add(aqu1, aqu2) result(aqu3)
Arguments
Type Intent Optional Attributes Name
type(aqu_pesticide_processes), intent(in) :: aqu1
type(aqu_pesticide_processes), intent(in) :: aqu2
Return Value type(aqu_pesticide_processes)
Called by
public function aqupest_add_all(aqu1, aqu2) result(aqu3)
Arguments
Type Intent Optional Attributes Name
type(aqu_pesticide_processes), intent(in) :: aqu1
type(aqu_pesticide_processes), intent(in) :: aqu2
Return Value type(aqu_pesticide_processes)
Called by
public function aqupest_div(aqu1, const) result(aqu2)
Arguments
Type Intent Optional Attributes Name
type(aqu_pesticide_processes), intent(in) :: aqu1
real, intent(in) :: const
Return Value type(aqu_pesticide_processes)
Called by
public function aqupest_ave(aqu1, const) result(aqu2)
Arguments
Type Intent Optional Attributes Name
type(aqu_pesticide_processes), intent(in) :: aqu1
real, intent(in) :: const
Return Value type(aqu_pesticide_processes)
Called by
Call graph
operator (+) calls aqupest_add
operator (.sum.) calls aqupest_add_all
operator (SLASH) calls aqupest_div
operator (SLASHSLASH) calls aqupest_ave