aquifer_module – TestDataProject
aquifer_module Module
222 statements
Source File
Used by
Variables
Type Visibility Attributes Name Initial
type(aquifer_database), public, dimension(:), allocatable :: aqudb
type(aquifer_database), public, dimension(:), allocatable :: aqu_dat
type(aquifer_data_parameters), public, dimension(:), allocatable :: aqu_prm
type(aquifer_dynamic), public, dimension(:), allocatable :: aqu_om_init
type(aquifer_dynamic), public, dimension(:), allocatable :: aqu_d
type(aquifer_dynamic), public, dimension(:), allocatable :: aqu_m
type(aquifer_dynamic), public, dimension(:), allocatable :: aqu_y
type(aquifer_dynamic), public, dimension(:), allocatable :: aqu_a
type(aquifer_dynamic), public, dimension(:), allocatable :: saqu_d
type(aquifer_dynamic), public, dimension(:), allocatable :: saqu_m
type(aquifer_dynamic), public, dimension(:), allocatable :: saqu_y
type(aquifer_dynamic), public, dimension(:), allocatable :: saqu_a
type(aquifer_dynamic), public :: baqu_d
type(aquifer_dynamic), public :: baqu_m
type(aquifer_dynamic), public :: baqu_y
type(aquifer_dynamic), public :: baqu_a
type(aquifer_dynamic), public :: aquz
type(aquifer_init_data_char), public, dimension(:), allocatable :: aqu_init_dat_c
type(aquifer_init_data_char_cs), public, dimension(:), allocatable :: aqu_init_dat_c_cs
type(aquifer_init_data), public, dimension(:), allocatable :: aqu_init
type(aqu_header), public :: aqu_hdr
type(aqu_header_units), public :: aqu_hdr_units
Interfaces
public interface operator (+)
public function aqu_add(aqo1, aqo2) result(aqo3)
Arguments
Type Intent Optional Attributes Name
type(aquifer_dynamic), intent(in) :: aqo1
type(aquifer_dynamic), intent(in) :: aqo2
Return Value type(aquifer_dynamic)
Called by
public interface operator (/)
public function aqu_div(aq1, const) result(aq2)
Arguments
Type Intent Optional Attributes Name
type(aquifer_dynamic), intent(in) :: aq1
real, intent(in) :: const
Return Value type(aquifer_dynamic)
Called by
public interface operator (*)
public function aqu_mult(aq1, const) result(aq2)
Arguments
Type Intent Optional Attributes Name
type(aquifer_dynamic), intent(in) :: aq1
real, intent(in) :: const
Return Value type(aquifer_dynamic)
Called by
Derived Types
type, public :: aquifer_database
Components
Type Visibility Attributes Name Initial
character(len=16), public :: aqunm = ""
aquifer name
character(len=16), public :: aqu_ini = ""
initial aquifer data- points to name in initial.aqu
real, public :: flo = 0.05
mm |flow from aquifer in current time step
Read more…
real, public :: dep_bot = 0.
m |depth - mid-slope surface to bottom of aquifer
Read more…
real, public :: dep_wt = 0.
m |depth - mid-slope surface to water table (initial)
Read more…
real, public :: no3 = 0.
ppm NO3-N |nitrate-N concentration in aquifer (initial)
Read more…
real, public :: minp = 0.
ppm P |mineral phosphorus concentration in aquifer (initial)
Read more…
real, public :: cbn = .5
percent |organic carbon in aquifer (initial)
Read more…
real, public :: flo_dist = 50.
m |average flow distance to stream or object
Read more…
real, public :: bf_max = 0.
mm |maximum daily baseflow - when all channels are contributing
Read more…
real, public :: alpha = 0.
1/days |lag factor for groundwater recession curve
Read more…
real, public :: revap_co = 0.
|revap oefficient - evap=pet*revap_co
real, public :: seep = 0.
frac |fraction of recharge that seeps from aquifer
Read more…
real, public :: spyld = 0.
m^3/m^3 |specific yield of aquifer
Read more…
real, public :: hlife_n = 30.
days |half-life of nitrogen in groundwater
Read more…
real, public :: flo_min = 0.
m |water table depth for return flow to occur
Read more…
real, public :: revap_min = 0.
m |water table depth for revap to occur
Read more…
type, public :: aquifer_data_parameters
Components
Type Visibility Attributes Name Initial
real, public :: area_ha = 0.
ha |surface area of aquifer
Read more…
real, public :: alpha_e = 0.
days |Exp(-alpha)
Read more…
real, public :: nloss = 0.
frac |nloss based on half life
Read more…
real, public :: rchrg_prev = 0.
m^3 |previous days recharge
Read more…
real, public :: rchrgn_prev = 0.
m^3 |previous days n recharge
Read more…
type, public :: aquifer_dynamic
Components
Type Visibility Attributes Name Initial
real, public :: flo = 0.
mm |lateral flow from aquifer
Read more…
real, public :: dep_wt = 0.
m |average depth from average surface elevation to water table
Read more…
real, public :: stor = 0.
mm |average water storage in aquifer in timestep
Read more…
real, public :: rchrg = 0.
mm |recharge entering aquifer from other objects
Read more…
real, public :: seep = 0.
mm |seepage from bottom of aquifer
Read more…
real, public :: revap = 0.
mm |plant water uptake and evaporation
Read more…
real, public :: no3_st = 0.
kg/ha N |current total NO3-N mass in aquifer
Read more…
real, public :: minp = 0.
kg/ha P |mineral phosphorus transported in return (lateral) flow
Read more…
real, public :: cbn = 0.
percent |organic carbon in aquifer - currently static
Read more…
real, public :: orgn = 0.
kg/ha P |organic nitrogen in aquifer - currently static
Read more…
real, public :: no3_rchg = 0.
kg/ha N |nitrate NO3-N flowing into aquifer from another object
Read more…
real, public :: no3_loss = 0.
kg/ha |nitrate NO3-N loss
Read more…
real, public :: no3_lat = 0.
kg/ha N |nitrate loading to reach in groundwater
Read more…
real, public :: no3_seep = 0.
kg/ha N |seepage of no3 to next object
Read more…
real, public :: flo_cha = 0.
mm H2O |surface runoff flowing into channels
Read more…
real, public :: flo_res = 0.
mm H2O |surface runoff flowing into reservoirs
Read more…
real, public :: flo_ls = 0.
mm H2O |surface runoff flowing into a landscape element (hru or ru)
Read more…
type, public :: aquifer_init_data_char
Components
Type Visibility Attributes Name Initial
character(len=16), public :: name = ""
xwalk with aqudb(iaqu)%aqu_ini
character(len=16), public :: org_min = ""
points to initial organic-mineral input file
character(len=16), public :: pest = ""
points to initial pesticide input file
character(len=16), public :: path = ""
points to initial pathogen input file
character(len=16), public :: hmet = ""
points to initial heavy metals input file
character(len=16), public :: salt = ""
points to initial salt input file
type, public :: aquifer_init_data_char_cs
Components
Type Visibility Attributes Name Initial
character(len=16), public :: name = ""
xwalk with aqudb(iaqu)%aqu_ini
character(len=16), public :: pest = ""
points to initial pesticide input file
character(len=16), public :: path = ""
points to initial pathogen input file
character(len=16), public :: hmet = ""
points to initial heavy metals input file
character(len=16), public :: salt = ""
points to initial salt input file (salt_aqu.ini)
character(len=16), public :: cs = ""
points to initial constituent input file (cs_aqu.ini)
type, public :: aquifer_init_data
Components
Type Visibility Attributes Name Initial
integer, public :: org_min = 1
points to initial organic-mineral input file
integer, public :: pest = 1
points to initial pesticide input file
integer, public :: path = 1
points to initial pathogen input file
integer, public :: hmet = 1
points to initial heavy metals input file
integer, public :: salt = 1
points to initial salt input file
integer, public :: cs = 1
points to initial constituent input file (rtb cs)
type, public :: aqu_header
Components
Type Visibility Attributes Name Initial
character(len=6), public :: day = "jday"
character(len=6), public :: mo = "mon"
character(len=6), public :: day_mo = "day"
character(len=6), public :: yrc = "yr"
character(len=8), public :: isd = "unit "
character(len=8), public :: id = " gis_id "
character(len=16), public :: name = " name"
character(len=16), public :: flo = "flo"
(mm)
character(len=16), public :: dep_wt = "dep_wt"
(m)
character(len=15), public :: stor = "stor"
(mm)
character(len=15), public :: rchrg = "rchrg"
(mm)
character(len=15), public :: seep = "seep"
(mm)
character(len=15), public :: revap = "revap"
(mm)
character(len=15), public :: no3_st = "no3_st"
(kg/ha N)
character(len=15), public :: minp = "minp"
(kg/ha P)
character(len=15), public :: orgn = "orgn"
(kg/ha N)
character(len=15), public :: orgp = "orgp"
(kg/ha P)
character(len=15), public :: no3_rchg = "no3_rchg"
(kg/ha N)
character(len=15), public :: no3_loss = "no3_loss"
(kg/ha N)
character(len=15), public :: no3_lat = "no3_lat"
(kg N/ha)
character(len=15), public :: no3_seep = "no3_seep"
(kg N/ha)
character(len=15), public :: flo_cha = "flo_cha"
(mm)
character(len=15), public :: flo_res = "flo_res"
(mm)
character(len=15), public :: flo_ls = "flo_ls"
(mm)
type, public :: aqu_header_units
Components
Type Visibility Attributes Name Initial
character(len=6), public :: day = ""
character(len=6), public :: mo = ""
character(len=6), public :: day_mo = ""
character(len=6), public :: yrc = ""
character(len=8), public :: isd = ""
character(len=8), public :: id = ""
character(len=16), public :: name = ""
character(len=16), public :: flo = "mm"
(mm)
character(len=16), public :: depwt = "m "
(m)
character(len=15), public :: stor = "mm"
(mm)
character(len=15), public :: rchrg = "mm"
(mm)
character(len=15), public :: seep = "mm"
(mm)
character(len=15), public :: revap = "mm"
(mm)
character(len=15), public :: no3_st = "kg/ha_N"
(kg/ha N)
character(len=15), public :: minp = "kg/ha_P"
(kg/ha P)
character(len=15), public :: orgn = "kg/ha_N"
(kg/ha N)
character(len=15), public :: orgp = "kg/ha_P"
(kg/ha P)
character(len=15), public :: no3_rchg = "kg/ha_N"
(kg/ha N)
character(len=15), public :: no3_loss = "kg/ha_N"
(kg/ha N)
character(len=15), public :: no3_lat = "kg/ha_N"
(kg N/ha)
character(len=15), public :: no3_seep = "kg/ha_N"
(kg N/ha)
character(len=15), public :: flo_cha = "mm"
(mm)
character(len=15), public :: flo_res = "mm"
(mm)
character(len=15), public :: flo_ls = "mm"
(mm)
Functions
public function aqu_add(aqo1, aqo2) result(aqo3)
Arguments
Type Intent Optional Attributes Name
type(aquifer_dynamic), intent(in) :: aqo1
type(aquifer_dynamic), intent(in) :: aqo2
Return Value type(aquifer_dynamic)
Called by
public function aqu_div(aq1, const) result(aq2)
Arguments
Type Intent Optional Attributes Name
type(aquifer_dynamic), intent(in) :: aq1
real, intent(in) :: const
Return Value type(aquifer_dynamic)
Called by
public function aqu_mult(aq1, const) result(aq2)
Arguments
Type Intent Optional Attributes Name
type(aquifer_dynamic), intent(in) :: aq1
real, intent(in) :: const
Return Value type(aquifer_dynamic)
Called by
Call graph
operator (+) calls aqu_add
operator (SLASH) calls aqu_div
operator (ASTERISK) calls aqu_mult