ch_pathogen_module – TestDataProject
ch_pathogen_module Module
79 statements
Source File
routines for swatdeg_hru module
Variables
Type Visibility Attributes Name Initial
type(ch_pathogen_output), public, dimension(:), allocatable, save :: chpth_d
type(ch_pathogen_output), public, dimension(:), allocatable, save :: chpth_m
type(ch_pathogen_output), public, dimension(:), allocatable, save :: chpth_y
type(ch_pathogen_output), public, dimension(:), allocatable, save :: chpth_a
type(ch_pathogen_output), public :: bchpth_d
type(ch_pathogen_output), public :: bchpth_m
type(ch_pathogen_output), public :: bchpth_y
type(ch_pathogen_output), public :: bchpth_a
type(ch_pathogen_output), public :: chpthz
type(ch_pathogen_header), public :: chpath_hdr
Interfaces
public interface operator (+)
public function chpath_add(cho1, cho2) result(cho3)
Arguments
Type Intent Optional Attributes Name
type(ch_pathogen_output), intent(in) :: cho1
type(ch_pathogen_output), intent(in) :: cho2
Return Value type(ch_pathogen_output)
Called by
public interface operator (/)
public function chpath_div(ch1, const) result(ch2)
Arguments
Type Intent Optional Attributes Name
type(ch_pathogen_output), intent(in) :: ch1
real, intent(in) :: const
Return Value type(ch_pathogen_output)
Called by
public interface operator (*)
public function chpath_mult(const, chn1) result(chn2)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: const
type(ch_pathogen_output), intent(in) :: chn1
Return Value type(ch_pathogen_output)
Called by
Derived Types
type, public :: ch_pathogen_output
Components
Type Visibility Attributes Name Initial
real, public :: pth_in = 0.
Read more…
Read more…
real, public :: pth_out = 0.
Read more…
Read more…
real, public :: dre_off = 0.
Read more…
Read more…
real, public :: regrow = 0.
Read more…
Read more…
real, public :: water = 0.
Read more…
Read more…
real, public :: benthic = 0.
Read more…
Read more…
type, public :: ch_pathogen_header
Components
Type Visibility Attributes Name Initial
character(len=6), public :: day = " jday"
character(len=6), public :: mo = " mon"
character(len=6), public :: day_mo = " day"
character(len=6), public :: yrc = " yr"
character(len=8), public :: isd = " unit "
character(len=8), public :: id = " gis_id "
character(len=16), public :: name = " name "
character(len=19), public :: pth_in = " path_in_#cfu/100ml"
Read more…
Read more…
character(len=20), public :: pth_out = " path_out_#cfu/100ml"
Read more…
Read more…
character(len=21), public :: dre_off = " dre_off_#cfu/100ml "
Read more…
Read more…
character(len=21), public :: regrow = " regrow_#cfu/100ml"
Read more…
Read more…
character(len=22), public :: water = " water_stor_#cfu/100ml"
Read more…
Read more…
character(len=21), public :: benthic = " benthic_#cfu/100ml"
Read more…
Read more…
Functions
public function chpath_add(cho1, cho2) result(cho3)
Arguments
Type Intent Optional Attributes Name
type(ch_pathogen_output), intent(in) :: cho1
type(ch_pathogen_output), intent(in) :: cho2
Return Value type(ch_pathogen_output)
Called by
public function chpath_div(ch1, const) result(ch2)
Arguments
Type Intent Optional Attributes Name
type(ch_pathogen_output), intent(in) :: ch1
real, intent(in) :: const
Return Value type(ch_pathogen_output)
Called by
public function chpath_mult(const, chn1) result(chn2)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: const
type(ch_pathogen_output), intent(in) :: chn1
Return Value type(ch_pathogen_output)
Called by
Call graph
operator (+) calls chpath_add
operator (SLASH) calls chpath_div
operator (ASTERISK) calls chpath_mult