ch_pesticide_module – TestDataProject
ch_pesticide_module Module
127 statements
Source File
Uses
constituent_mass_module
Used by
Variables
Type Visibility Attributes Name Initial
real, public :: frsol = 0.
none |fraction of pesticide in reach that is soluble
real, public :: frsrb = 0.
none |fraction of pesticide in reach that is sorbed
type(ch_pesticide_processes), public :: ch_pestbz
type(ch_pesticide_output), public, dimension(:), allocatable, save :: chpst_d
type(ch_pesticide_output), public, dimension(:), allocatable, save :: chpst_m
type(ch_pesticide_output), public, dimension(:), allocatable, save :: chpst_y
type(ch_pesticide_output), public, dimension(:), allocatable, save :: chpst_a
type(ch_pesticide_output), public :: bchpst_d
type(ch_pesticide_output), public :: bchpst_m
type(ch_pesticide_output), public :: bchpst_y
type(ch_pesticide_output), public :: bchpst_a
type(ch_pesticide_output), public :: chpst
type(ch_pesticide_output), public :: chpstz
type(ch_pesticide_header), public :: chpest_hdr
Interfaces
public interface operator (+)
public function chpest_add(cho1, cho2) result(cho3)
Arguments
Type Intent Optional Attributes Name
type(ch_pesticide_processes), intent(in) :: cho1
type(ch_pesticide_processes), intent(in) :: cho2
Return Value type(ch_pesticide_processes)
Called by
public interface operator (/)
public function chpest_div(ch1, const) result(ch2)
Arguments
Type Intent Optional Attributes Name
type(ch_pesticide_processes), intent(in) :: ch1
real, intent(in) :: const
Return Value type(ch_pesticide_processes)
Called by
public interface operator (//)
public function chpest_ave(ch1, const) result(ch2)
Arguments
Type Intent Optional Attributes Name
type(ch_pesticide_processes), intent(in) :: ch1
real, intent(in) :: const
Return Value type(ch_pesticide_processes)
Called by
Derived Types
type, public :: ch_pesticide_processes
Components
Type Visibility Attributes Name Initial
real, public :: tot_in = 0.
kg !total pesticide into reservoir
Read more…
real, public :: sol_out = 0.
kg !soluble pesticide out of reservoir
Read more…
real, public :: sor_out = 0.
kg !sorbed pesticide out of reservoir
Read more…
real, public :: react = 0.
kg !pesticide lost through reactions in water layer
Read more…
real, public :: metab = 0.
kg !pesticide metabolized from parent in water layer
Read more…
real, public :: volat = 0.
kg !pesticide lost through volatilization
Read more…
real, public :: settle = 0.
kg !pesticide settling to sediment layer
Read more…
real, public :: resus = 0.
kg !pesticide resuspended into lake water
Read more…
real, public :: difus = 0.
kg !pesticide diffusing from sediment to water
Read more…
real, public :: react_bot = 0.
kg !pesticide lost from benthic sediment by reactions
Read more…
real, public :: metab_bot = 0.
kg !pesticide metabolized from parent in water layer
Read more…
real, public :: bury = 0.
kg !pesticide lost from benthic sediment by burial
Read more…
real, public :: water = 0.
kg !pesticide in water at end of day
Read more…
real, public :: benthic = 0.
kg !pesticide in benthic sediment at tend of day
Read more…
type, public :: ch_pesticide_output
Components
Type Visibility Attributes Name Initial
type(ch_pesticide_processes), public, dimension (:), allocatable :: pest
pesticide hydrographs
type, public :: ch_pesticide_header
Components
Type Visibility Attributes Name Initial
character(len=6), public :: day = "jday"
character(len=6), public :: mo = "mon"
character(len=6), public :: day_mo = "day"
character(len=6), public :: yrc = "yr"
character(len=8), public :: isd = "unit "
character(len=8), public :: id = " gis_id "
character(len=16), public :: name = " name"
character(len=16), public :: pest = " pesticide"
character(len=13), public :: tot_in = "tot_in_kg "
(kg)
character(len=13), public :: sol_out = "sol_out_kg "
(kg)
character(len=14), public :: sor_out = "sor_out_kg "
(kg)
character(len=13), public :: react = "react_h2o_kg "
(kg)
character(len=13), public :: metab = "metab_h2o_kg "
(kg)
character(len=12), public :: volat = "volat_kg "
(kg)
character(len=12), public :: settle = "settle_kg "
(kg)
character(len=13), public :: resus = "resuspend_kg "
(kg)
character(len=12), public :: difus = "diffuse_kg "
(kg)
character(len=15), public :: react_bot = "react_benth_kg "
(kg)
character(len=15), public :: metab_bot = "metab_benth_kg "
(kg)
character(len=14), public :: bury = "bury_benth_kg "
(kg)
character(len=14), public :: water = "water_stor_kg "
(kg)
character(len=12), public :: benthic = "benthic_kg "
(kg)
Functions
public function chpest_add(cho1, cho2) result(cho3)
Arguments
Type Intent Optional Attributes Name
type(ch_pesticide_processes), intent(in) :: cho1
type(ch_pesticide_processes), intent(in) :: cho2
Return Value type(ch_pesticide_processes)
Called by
public function chpest_div(ch1, const) result(ch2)
Arguments
Type Intent Optional Attributes Name
type(ch_pesticide_processes), intent(in) :: ch1
real, intent(in) :: const
Return Value type(ch_pesticide_processes)
Called by
public function chpest_ave(ch1, const) result(ch2)
Arguments
Type Intent Optional Attributes Name
type(ch_pesticide_processes), intent(in) :: ch1
real, intent(in) :: const
Return Value type(ch_pesticide_processes)
Called by
Call graph
operator (+) calls chpest_add
operator (SLASH) calls chpest_div
operator (SLASHSLASH) calls chpest_ave