hydrograph_module – TestDataProject
hydrograph_module Module
1366 statements
Source File
function to convert mass to concentration function to convert concentration to mass function to convert mass to concentration routines for hydrograph module routines for hydrograph module routines for hydrograph module routines for hydrograph module
Uses
basin_module
time_module
Used by
Variables
Type Visibility Attributes Name Initial
integer, public :: mhyd = 0
none |max number of hydrographs
integer, public :: mcmd = 0
|
integer, public :: inum2 = 0
none |inflow hydrograph storage location number
integer, public :: jrch = 0
none |reach number
integer, public :: jrchq = 0
|
integer, public :: mrte = 0
|
integer, public :: ihout = 0
none |outflow hydrograph storage location number
integer, public :: iwst = 0
|
integer, public :: isdch = 0
|
integer, public :: icmd = 0
|
integer, public :: ich = 0
none |object number
integer, public :: mobj_out = 0
none |end of loop
integer, public :: isd_chsur = 0
|
integer, public, dimension (:), allocatable :: rcv_sum
|
integer, public, dimension (:), allocatable :: dfn_sum
|
integer, public, dimension (:), allocatable :: elem_cnt
|
integer, public, dimension (:), allocatable :: defunit_num
|
integer, public, dimension (:), allocatable :: ru_seq
|
real, public, dimension (:), allocatable :: hyd_km2
|
integer, public, dimension (:), allocatable :: ob_order
|
real, public, dimension(:,:,:), allocatable :: rchhr
|
real, public, allocatable :: wyld_rto(:)
mm=m3/(10*ha) |output runoff/precip ratio
type(hyd_output), public, dimension(:), allocatable :: hd
type(hyd_output), public, dimension(:), allocatable :: rec_d
type(hyd_output), public, dimension(:), allocatable :: rec_m
type(hyd_output), public, dimension(:), allocatable :: rec_y
type(hyd_output), public, dimension(:), allocatable :: rec_a
type(hyd_output), public, dimension(:), allocatable :: srec_d
type(hyd_output), public, dimension(:), allocatable :: srec_m
type(hyd_output), public, dimension(:), allocatable :: srec_y
type(hyd_output), public, dimension(:), allocatable :: srec_a
type(hyd_output), public, dimension(:), allocatable :: ru_d
type(hyd_output), public, dimension(:), allocatable :: ru_m
type(hyd_output), public, dimension(:), allocatable :: ru_y
type(hyd_output), public, dimension(:), allocatable :: ru_a
type(hyd_output), public :: brec_d
type(hyd_output), public :: brec_m
type(hyd_output), public :: brec_y
type(hyd_output), public :: brec_a
type(hyd_output), public :: bru_d
type(hyd_output), public :: bru_m
type(hyd_output), public :: bru_y
type(hyd_output), public :: bru_a
type(hyd_output), public :: binhyd_d
type(hyd_output), public :: hz
type(hyd_output), public :: dr1
type(hyd_output), public, dimension(:), allocatable :: hcnst
type(hyd_output), public, dimension(:), allocatable :: hhr
type(hyd_output), public :: ht1
type(hyd_output), public :: ht2
type(hyd_output), public :: ht3
type(hyd_output), public :: ht4
type(hyd_output), public :: ht5
type(hyd_output), public :: delrto
type(hyd_output), public :: fp_dep
type(hyd_output), public :: ch_dep
type(hyd_output), public :: bank_ero
type(hyd_output), public :: bed_ero
type(hyd_output), public :: ch_trans
type(hyd_sep), public :: hdsep1
type(hyd_sep), public :: hdsep2
type(hyd_sep), public, dimension(:), allocatable :: ch_stor_hdsep
real, public, dimension(:,:), allocatable :: hyd_sep_array
character(len=16), public, dimension(:), allocatable :: om_init_name
type(hyd_output), public, dimension(:), allocatable, target :: aqu
type(hyd_output), public, dimension(:), allocatable, target :: res
type(hyd_output), public, dimension(:), allocatable, target :: wet
type(hyd_output), public, dimension(:), allocatable :: res_om_init
type(hyd_output), public, dimension(:), allocatable :: wet_om_init
type(hyd_output), public, dimension(:), allocatable :: wet_seep_day
Jaehak 2022 wetland seepage volume
type(hyd_output), public :: resz
type(hyd_output), public, pointer :: wbody
used for reservoir and wetlands
type(hyd_output), public, dimension(:), allocatable :: om_init_water
type(hyd_output), public, dimension(:), allocatable :: ch_om_water_init
type(hyd_output), public, dimension(:), allocatable :: fp_om_water_init
type(hyd_output), public, dimension(:), allocatable :: ch_stor
channel storage - max bankfull
type(hyd_output), public, dimension(:), allocatable :: fp_stor
flood plain storage above wetland emergency
type(hyd_output), public, dimension(:), allocatable :: tot_stor
total - channel + flood plain storage
type(hyd_output), public, dimension(:), allocatable :: wet_stor
wetland storage in flood plain
type(hyd_output), public, dimension(:), allocatable :: ch_stor_m
type(hyd_output), public, dimension(:), allocatable :: ch_stor_y
type(hyd_output), public, dimension(:), allocatable :: ch_stor_a
type(hyd_output), public :: chaz
type(hyd_output), public, dimension(:), allocatable, save :: res_in_d
type(hyd_output), public, dimension(:), allocatable, save :: res_in_m
type(hyd_output), public, dimension(:), allocatable, save :: res_in_y
type(hyd_output), public, dimension(:), allocatable, save :: res_in_a
type(hyd_output), public, dimension(:), allocatable, save :: res_trap
type(hyd_output), public :: bres_in_d
type(hyd_output), public :: bres_in_m
type(hyd_output), public :: bres_in_y
type(hyd_output), public :: bres_in_a
type(hyd_output), public, dimension(:), allocatable, save :: res_out_d
type(hyd_output), public, dimension(:), allocatable, save :: res_out_m
type(hyd_output), public, dimension(:), allocatable, save :: res_out_y
type(hyd_output), public, dimension(:), allocatable, save :: res_out_a
type(hyd_output), public :: bres
type(hyd_output), public :: bres_out_d
type(hyd_output), public :: bres_out_m
type(hyd_output), public :: bres_out_y
type(hyd_output), public :: bres_out_a
type(hyd_output), public :: resmz
type(hyd_output), public, dimension(:), allocatable, save :: wet_in_d
type(hyd_output), public, dimension(:), allocatable, save :: wet_in_m
type(hyd_output), public, dimension(:), allocatable, save :: wet_in_y
type(hyd_output), public, dimension(:), allocatable, save :: wet_in_a
type(hyd_output), public :: bwet_in_d
type(hyd_output), public :: bwet_in_m
type(hyd_output), public :: bwet_in_y
type(hyd_output), public :: bwet_in_a
type(hyd_output), public, dimension(:), allocatable, save :: wet_out_d
type(hyd_output), public, dimension(:), allocatable, save :: wet_out_m
type(hyd_output), public, dimension(:), allocatable, save :: wet_out_y
type(hyd_output), public, dimension(:), allocatable, save :: wet_out_a
type(hyd_output), public :: bwet_out_d
type(hyd_output), public :: bwet_out_m
type(hyd_output), public :: bwet_out_y
type(hyd_output), public :: bwet_out_a
type(hyd_output), public, dimension(:), allocatable, save :: ch_in_d
type(hyd_output), public, dimension(:), allocatable, save :: ch_in_m
type(hyd_output), public, dimension(:), allocatable, save :: ch_in_y
type(hyd_output), public, dimension(:), allocatable, save :: ch_in_a
type(hyd_output), public :: bch_stor_d
type(hyd_output), public :: bch_stor_m
type(hyd_output), public :: bch_stor_y
type(hyd_output), public :: bch_stor_a
type(hyd_output), public :: bch_in_d
type(hyd_output), public :: bch_in_m
type(hyd_output), public :: bch_in_y
type(hyd_output), public :: bch_in_a
type(hyd_output), public, dimension(:), allocatable, save :: ch_out_d
type(hyd_output), public, dimension(:), allocatable, save :: ch_out_m
type(hyd_output), public, dimension(:), allocatable, save :: ch_out_y
type(hyd_output), public, dimension(:), allocatable, save :: ch_out_a
type(hyd_output), public :: bch_out_d
type(hyd_output), public :: bch_out_m
type(hyd_output), public :: bch_out_y
type(hyd_output), public :: bch_out_a
type(hyd_output), public :: chomz
type(object_output), public, dimension (:), allocatable :: ob_out
type(channel_floodplain_water_balance), public, dimension (:), allocatable :: ch_fp_wb
type(timestep), public, dimension(:), allocatable, save :: ts
type(water_temperature_data), public :: w_temp
integer, public :: fdc_npts = 27
real, public, dimension (27) :: fdc_p = (/.1, .5, 1., 2., 3., 5., 10., 15., 20., 25., 30., 35., 40., 45., 50., 55., 60., 65., 70., 75., 80., 85., 90., 95., 97., 98., 99./)
percent |output percent on the fdc (input)
integer, public, dimension (27) :: fdc_days = (/1, 2, 4, 7, 11, 18, 37, 55, 73, 91, 110, 128, 146, 164, 182, 201, 219, 237, 256, 274, 292, 310, 329, 347, 354, 358, 361/)
real, public, dimension (27) :: fdc_n = 0.
|flow on the fdc at given percents
real, public, dimension (27) :: fdc_norm_mean = 0.
|normalized flow on the fdc at given percents
type(object_connectivity), public, dimension(:), allocatable, save :: ob
type(irrigation_water_transfer), public, dimension(:), allocatable :: irrig
dimension by hru
type(recall_hydrograph_inputs), public, dimension(:), allocatable :: recall
type(spatial_objects), public :: sp_ob
total number of the object
type(spatial_objects), public :: sp_ob1
first sequential number of the object
type(object_total_hydrographs), public :: hd_tot
type(routing_unit_data), public, dimension(:), allocatable :: ru_def
type(routing_unit_elements), public, dimension(:), allocatable :: ru_elem
integer, public, dimension(:), allocatable :: ielem_ru
sequential counter for ru the hru is in
type(channel_surface_elements), public, dimension(:), allocatable :: ch_sur
type(geomorphic_baseflow_channel_data), public, dimension(:), allocatable :: aqu_cha
unsorted
type(channel_aquifer_elements), public, dimension(:), allocatable :: aq_ch
sorted by drainage area (smallest first)
type(hyd_output), public, dimension(:), allocatable :: dr
delivery ratio for objects- chan, res, lu
type(hyd_output), public, dimension(:), allocatable :: trt
wastewater treatment plants
type(hyd_output), public, dimension(:), allocatable :: exco
export coefficient
type(hyd_header), public :: hyd_hdr
type(hyd_stor_header), public :: hyd_stor_hdr
type(hyd_in_header), public :: hyd_in_hdr
type(hyd_out_header), public :: hyd_out_hdr
type(hyd_inout_header), public :: hyd_inout_hdr
type(wtmp_out_header), public :: wtmp_hdr
type(sed_hyd_header), public :: sd_hyd_hdr
type(sd_hyd_header_units), public :: sd_hyd_hdr_units
type(sol_header), public :: sol_hdr
type(plant_header), public :: plt_hdr
type(flood_plain_header), public :: fp_hdr
type(ch_watbod_header), public :: ch_wbod_hdr
type(ch_watbod_header_units), public :: ch_wbod_hdr_units
type(ch_watbod_inoutheader), public :: ch_wbod_inouthdr
type(ch_watbod_inoutheader_units), public :: ch_wbod_inouthdr_units
type(hyd_header_units1), public :: hyd_hdr_units1
type(hyd_header_units3), public :: hyd_hdr_units3
type(hydinout_header_units1), public :: hydinout_hdr_units1
type(wtmp_header_units), public :: wtmp_units
type(hyd_header_units), public :: hyd_hdr_units
type(hyd_header_units2), public :: hyd_hdr_units2
type(hyd_header_time), public :: hyd_hdr_time
type(rec_header_time), public :: rec_hdr_time
type(hyd_header_obj), public :: hyd_hdr_obj
type(output_flow_duration_header), public :: fdc_hdr
type(calibration_header), public :: calb_hdr
type(calibration2_header), public :: calb2_hdr
type(calibration3_header), public :: calb3_hdr
type(output_checker_header), public :: chk_hdr
type(output_checker_unit), public :: chk_unit
type(hru_swift_header), public :: hru_swift_hdr
Interfaces
public interface operator (+)
public function hydout_add(hyd1, hyd2) result(hyd3)
Arguments
Type Intent Optional Attributes Name
type(hyd_output), intent(in) :: hyd1
type(hyd_output), intent(in) :: hyd2
Return Value type(hyd_output)
Called by
public interface operator (-)
public function hydout_subtract(hyd1, hyd2) result(hyd3)
Arguments
Type Intent Optional Attributes Name
type(hyd_output), intent(in) :: hyd1
type(hyd_output), intent(in) :: hyd2
Return Value type(hyd_output)
Called by
public interface operator (**)
public function hydout_mult(hyd1, hyd2) result(hyd3)
Arguments
Type Intent Optional Attributes Name
type(hyd_output), intent(in) :: hyd1
type(hyd_output), intent(in) :: hyd2
Return Value type(hyd_output)
Called by
public interface operator (.add.)
public function hydout_add_const(const, hyd1) result(hyd2)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: const
type(hyd_output), intent(in) :: hyd1
Return Value type(hyd_output)
Called by
public interface operator (*)
public function hydout_mult_const(const, hyd1) result(hyd2)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: const
type(hyd_output), intent(in) :: hyd1
Return Value type(hyd_output)
Called by
public interface operator (/)
public function hydout_div_const(hyd1, const) result(hyd2)
Arguments
Type Intent Optional Attributes Name
type(hyd_output), intent(in) :: hyd1
real, intent(in) :: const
Return Value type(hyd_output)
Called by
public interface operator (//)
public function hydout_div_conv(hyd1, hyd2) result(hyd3)
Arguments
Type Intent Optional Attributes Name
type(hyd_output), intent(in) :: hyd1
type(hyd_output), intent(in) :: hyd2
Return Value type(hyd_output)
Called by
Derived Types
type, public :: hyd_output
Components
Type Visibility Attributes Name Initial
real, public :: flo = 0.
m^3 |volume of water
Read more…
real, public :: sed = 0.
metric tons |sediment
Read more…
real, public :: orgn = 0.
kg N |organic N
Read more…
real, public :: sedp = 0.
kg P |organic P
Read more…
real, public :: no3 = 0.
kg N |NO3-N
Read more…
real, public :: solp = 0.
kg P |mineral (soluble P)
Read more…
real, public :: chla = 0.
kg |chlorophyll-a
Read more…
real, public :: nh3 = 0.
kg N |NH3
Read more…
real, public :: no2 = 0.
kg N |NO2
Read more…
real, public :: cbod = 0.
kg |carbonaceous biological oxygen demand
Read more…
real, public :: dox = 0.
kg |dissolved oxygen
Read more…
real, public :: san = 0.
tons |detached sand
Read more…
real, public :: sil = 0.
tons |detached silt
Read more…
real, public :: cla = 0.
tons |detached clay
Read more…
real, public :: sag = 0.
tons |detached small ag
Read more…
real, public :: lag = 0.
tons |detached large ag
Read more…
real, public :: grv = 0.
tons |gravel
Read more…
real, public :: temp = 0.
deg c |temperature
Read more…
type, public :: hyd_sep
Components
Type Visibility Attributes Name Initial
real, public :: flo_surq = 0.
m3 |volume of water from surface runoff
Read more…
real, public :: flo_latq = 0.
m3 |volume of water from surface runoff
Read more…
real, public :: flo_gwsw = 0.
m3 |volume of water from groundwater discharge
Read more…
real, public :: flo_swgw = 0.
m3 |volume of water from stream seepage
Read more…
real, public :: flo_satex = 0.
m3 |volume of water from saturation excess (high water table; from gwflow module)
Read more…
real, public :: flo_satexsw = 0.
m3 |volume of water from saturation excess (saturated profile)
Read more…
real, public :: flo_tile = 0.
m3 |volume of water from tile flow
Read more…
type, public :: object_output
Components
Type Visibility Attributes Name Initial
character(len=10), public :: name = ""
character(len=10), public :: obtyp = ""
object type: hru,hlt,hs,rxc,dr,out,sdc
integer, public :: obtypno = 0
object type number: 1=hru, 2=hru_lte, 3=channel
character(len=20), public :: hydtyp = ""
hydrograph type: tot,rhg,sur,lat,til
integer, public :: objno = 0
object number
integer, public :: hydno = 0
code computes from hydtyp
character(len=26), public :: filename = ""
file with hydrograph output from the object
integer, public :: unitno = 6100
filename unit number
type, public :: channel_floodplain_water_balance
Components
Type Visibility Attributes Name Initial
real, public :: inflo = 0.
m3 | inflow
Read more…
real, public :: outflo = 0.
m3 | outflow
Read more…
real, public :: tl = 0.
m3 | transmission losses
Read more…
real, public :: ev = 0.
m3 | evaporation
Read more…
real, public :: ch_stor_init = 0.
m3 | channel storage at start of time step
Read more…
real, public :: ch_stor = 0.
m3 | channel storage at end of time step
Read more…
real, public :: fp_stor_init = 0.
m3 | flood plain storage at start of time step (all flood plain storage above wetland emergency volume)
Read more…
real, public :: fp_stor = 0.
m3 | flood plain storage at end of time step
Read more…
real, public :: tot_stor_init = 0.
m3 | total channel + wetland storage at start of time step
Read more…
real, public :: tot_stor = 0.
m3 | total channel + wetland storage at end of time step
Read more…
real, public :: wet_stor_init = 0.
m3 | wetland flood plain storage at start of time step
Read more…
real, public :: wet_stor = 0.
m3 | wetland flood plain storage at end of time step
Read more…
type, public :: timestep
Components
Type Visibility Attributes Name Initial
type(hyd_output), public, dimension(:), allocatable :: hh
type, public :: sorted_duration_curve
Components
Type Visibility Attributes Name Initial
real, public :: val = 0.
integer, public :: next = 0
type, public :: duration_curve_points
Components
Type Visibility Attributes Name Initial
real, public :: min = 1.e10
real, public :: max = 0.
real, public :: mean = 0
real, public, dimension (27) :: p = 0.
probabilities for all points on the fdc
type, public :: water_temperature_data
Components
Type Visibility Attributes Name Initial
character(len=16), public :: name = ""
real, public :: sno_mlt = 1.
none |coefficient influencing snowmelt temperature contributions
Read more…
real, public :: gw = .97
none |coefficient influencing groundwater temperature contributions
Read more…
real, public :: sur_lat = 1.
none |coefficient influencing surface and lateral flow temperature contributions
Read more…
integer, public :: airlag_d = 6
days |average air temperature lag
Read more…
real, public :: hex_coef1 = .67
1/hour |heat transfer coefficient 1
Read more…
real, public :: hex_coef2 = 1.16
1/hour |heat transfer coefficient 2
Read more…
type, public :: flow_duration_curve
Components
Type Visibility Attributes Name Initial
integer, public :: mfe = 1
integer, public :: mle = 1
type(duration_curve_points), public :: p_md
median of all years
type(duration_curve_points), public, dimension (:), allocatable :: yr
flow on the fdc at given percents for each year
type, public :: inflow_unit_hyds
Components
Type Visibility Attributes Name Initial
real, public, dimension (:,:), allocatable :: uh
unit hydrograph
real, public, dimension (:,:), allocatable :: hyd_flo
flow hydrograph
type, public :: flashiness_index
Components
Type Visibility Attributes Name Initial
real, public :: sum_q_q1 = 0.
sum of difference in current day flow minus previous day flow
real, public :: sum_q = 0.
sum of daily flow over simulation period
real, public :: q_prev = 0.
previous day flow
real, public :: index = 0.
index
type, public :: object_connectivity
Components
Type Visibility Attributes Name Initial
character(len=16), public :: name = "default"
character(len=8), public :: typ = " "
object type - ie hru, hru_lte, sub, chan, res, recall
integer, public :: nhyds = 0
hru=5, chan=3 - see type hd_tot for each object
real, public :: lat = 0.
latitude (degrees)
real, public :: long = 0.
longitude (degrees)
real, public :: elev = 100.
elevation (m)
real, public :: plaps = 0.
precipitation lapse applied to object precip
real, public :: tlaps = 0.
temperature lapse applied to object precip
real, public :: area_ha = 80.
input drainag area - ha
integer, public :: sp_ob_no = 1
spatial object number - ie: hru number, channel number, etc
real, public :: area_ha_calc = 80.
calculated drainage area-ha. only for checking - doesn't work if routing across landscape
integer, public :: props = 1
properties number from data base (ie hru.dat, sub.dat) - change props to data
character(len=50), public :: wst_c = ""
weather station name
integer, public :: wst = 1
weather station number
integer, public :: constit = 0
constituent data pointer to pesticides, pathogens, metals, salts
integer, public :: props2 = 0
overbank connectivity pointer to landscape units - change props2 to overbank
character(len=16), public :: ruleset = ""
points to the name of the dtbl in flo_con.dtl for out flow control
integer, public :: flo_dtbl = 0
dtbl pointer for flow fraction of hydrograph
integer, public :: num = 1
spatial object number- ie hru number corresponding to sequential command number
integer(kind=8), public :: gis_id = 0
gis number for database purposes
integer, public :: fired = 0
0=not fired; 1=fired off as a command
integer, public :: cmd_next = 0
next command (object) number
integer, public :: cmd_prev = 0
previous command (object) number
integer, public :: cmd_order = 0
1=headwater,2=2nd order,etc
integer, public :: src_tot = 0
total number of outgoing (source) objects
integer, public :: rcv_tot = 0
total number of incoming (receiving) hydrographs
integer, public :: dfn_tot = 0
total number of defining objects (ie hru"s within a subbasin)
integer, public :: ru_tot = 0
number of routing units that contain this object
integer, public, dimension (:), allocatable :: ru
subbasin the element is in
integer, public :: elem = 0
subbasins element number for this object- used for routing over (can only have one)
integer, public :: flood_ch_lnk = 0
channel the landscape unit is linked to
integer, public :: flood_ch_elem = 0
landscape unit number - 1 is nearest to stream
integer, public :: flood_frac = 0
fraction of flood flow assigned to the object
character(len=3), public, dimension (:), allocatable :: obtyp_out
outflow object type (ie 1=hru, 2=sd_hru, 3=sub, 4=chan, etc)
integer, public, dimension(:), allocatable :: obtypno_out
outflow object type name
integer, public, dimension(:), allocatable :: obj_out
outflow object
character(len=3), public, dimension (:), allocatable :: htyp_out
outflow hyd type (ie 1=tot, 2= recharge, 3=surf, etc)
integer, public, dimension (:), allocatable :: ihtyp_out
outflow hyd type (ie 1=tot, 2= recharge, 3=surf, etc)
real, public, dimension (:), allocatable :: frac_out
fraction of hydrograph
character(len=8), public, dimension(:), allocatable :: obtyp_in
inflow object type (ie 1=hru, 2=sd_hru, 3=sub, 4=chan, etc)
integer, public, dimension(:), allocatable :: obtypno_in
inflow object type number
integer, public, dimension(:), allocatable :: obj_in
character(len=3), public, dimension(:), allocatable :: htyp_in
inflow hyd type (ie 1=tot, 2= recharge, 3=surf, etc)
integer, public, dimension(:), allocatable :: ihtyp_in
real, public, dimension(:), allocatable :: frac_in
integer, public, dimension(:), allocatable :: rcvob_inhyd
inflow hydrograph number of receiving object - used for dtbl flow fractions
type(flow_duration_curve), public :: fdc
use for daily flows and then use to get median of annual fdc"s
type(sorted_duration_curve), public, dimension(:), allocatable :: fdc_ll
linked list of daily flow for year - dimensioned to 366
type(sorted_duration_curve), public, dimension(:), allocatable :: fdc_lla
linked list of annual flow for simulation - dimensioned to nbyr
type(flashiness_index), public :: flash_idx
flashiness index object
type(hyd_output), public :: hin
inflow hydrograph for surface runon - sum of all inflow hyds
type(hyd_output), public :: hin_sur
inflow hydrograph for surface runoff - sum of all surface inflow hyds
type(hyd_output), public :: hin_lat
inflow hydrograph for lateral soil flow - sum of all lateral inflow hyds
type(hyd_output), public :: hin_til
inflow hydrograph for tile flow - sum of all tile inflow hyds
type(hyd_output), public :: hin_aqu
inflow hydrograph for aquifer flow - sum of all aquifer inflow hyds
type(hyd_output), public, dimension(:), allocatable :: hd
daily hydrograph (ie 1=tot, 2= recharge, 3=surf, etc)
type(hyd_output), public, dimension(:), allocatable :: hd_aa
ave annual hydrograph for hru for swift (ie 1=tot, 2= recharge, 3=surf, etc)
type(hyd_output), public, dimension(:,:), allocatable :: ts
subdaily hydrographs
type(inflow_unit_hyds), public, dimension(:), allocatable :: hin_uh
inflow unit hydrographs
real, public, dimension(:,:), allocatable :: uh
subdaily surface runoff unit hydrograph
real, public, dimension(:,:), allocatable :: hyd_flo
subdaily surface runoff hydrograph
real, public, dimension(:), allocatable :: tsin
inflow subdaily flow hydrograph
type(hyd_output), public :: trans
water transfer in water allocation
type(hyd_output), public :: hin_tot
total inflow hydrograph to the object
type(hyd_output), public :: hout_tot
total outflow hydrograph to the object
type(hyd_output), public :: conc_prev
concentration of previous timestep for watqual2e routine
real, public :: demand = 0.
water irrigation demand (ha-m)
integer, public :: day_cur = 0
current hydrograph day in ts
integer, public :: day_max = 0
maximum number of days to store the hydrograph
real, public :: peakrate = 0.
peak flow rate during time step - m3/s
type(hyd_output), public, dimension(:), allocatable :: hin_d
type(hyd_output), public, dimension(:), allocatable :: hin_m
type(hyd_output), public, dimension(:), allocatable :: hin_y
type(hyd_output), public, dimension(:), allocatable :: hin_a
type(hyd_output), public, dimension(:), allocatable :: hout_m
type(hyd_output), public, dimension(:), allocatable :: hout_y
type(hyd_output), public, dimension(:), allocatable :: hout_a
type(hyd_output), public :: hdep_m
type(hyd_output), public :: hdep_y
type(hyd_output), public :: hdep_a
type(hyd_sep), public :: hdsep
type(hyd_sep), public :: hdsep_in
integer, public, dimension(:), allocatable :: obj_subs
subbasins object number that contain this object
type, public :: water_rights_elements
Components
Type Visibility Attributes Name Initial
integer, public :: num = 0
character(len=16), public :: ob_typ = ""
object type - hru, channel, reservoir, etc
integer, public :: ob_num = 0
object number
character(len=16), public :: irr_typ = ""
character from irr.ops - was irr demand, minimum flow, flow fraction, etc
integer, public :: irr_no = 0
irrigation number from irr.ops - walk irr_typ
real, public :: amount = 0.
0 for irr demand; ha-m for min_flo; frac for min_frac
integer, public :: rights = 0
0-100 scale
type, public :: irrigation_water_transfer
Components
Type Visibility Attributes Name Initial
real, public :: demand = 0.
irrigation demand |m3
Read more…
real, public :: applied = 0.
irrigation applied |mm
Read more…
real, public :: runoff = 0.
irrigation surface runoff |mm
Read more…
real, public :: eff = 1.
irrigation efficiency as a fraction of irrigation. Jaehak 2022
real, public :: frac_surq = 0.
fraction of irrigation lost in runoff flow. Jaehak 2022
real, public :: no3 = 0.
nitrate concentration in irrigation water |kg Jaehak 2023
Read more…
real, public :: salt = 0.
salt concentration in irrigation water |ppm
Read more…
type(hyd_output), public :: water
irrigation water
type, public :: recall_hydrograph_inputs
Components
Type Visibility Attributes Name Initial
character(len=25), public :: name = ""
integer, public :: num = 0
number of elements
integer, public :: typ = -1
recall type - 0=subdaily, 1=day, 2=mon, 3=year
character(len=25), public :: filename = ""
filename
type(hyd_output), public, dimension (:,:), allocatable :: hd
m3/s for flow |input total hyd for daily, monthly, annual and exco
Read more…
real, public, dimension (:,:), allocatable :: hyd_flo
m3/s |input total flow hyd only for subdaily recall
Read more…
integer, public :: start_yr = 0
start year of point source file
integer, public :: end_yr = 0
end year of point source file
type, public :: spatial_objects
Components
Type Visibility Attributes Name Initial
integer, public :: objs = 0
number of objects or 1st object command
integer, public :: hru = 0
1-number of hru"s or 1st hru command
integer, public :: hru_lte = 0
2-number of hru_lte"s or 1st hru_lte command
integer, public :: ru = 0
3-number of ru"s or 1st ru command
integer, public :: gwflow = 0
4-number of gwflow"s or 1st gwflow command !rtb gwflow
integer, public :: aqu = 0
5-number of aquifer"s or 1st aquifer command
integer, public :: chan = 0
6-number of chan"s or 1st chan command
integer, public :: res = 0
7-number of res"s or 1st res command
integer, public :: recall = 0
8-number of recdays"s or 1st recday command
integer, public :: exco = 0
11-number of exco"s or 1st export coeff command
integer, public :: dr = 0
12-number of dr"s or 1st del ratio command
integer, public :: canal = 0
13-number of canal"s or 1st canal command
integer, public :: pump = 0
14-number of pump"s or 1st pump command
integer, public :: outlet = 0
15-number of outlet"s or 1st outlet command
integer, public :: chandeg = 0
16-number of swat-deg channel"s or 1st swat-deg channel command
integer, public :: aqu2d = 0
17-not currently used (number of 2D aquifer"s or 1st 2D aquifer command)
integer, public :: herd = 0
18-not currently used (number of herds)
integer, public :: wro = 0
19-not currently used (number of water rights)
type, public :: object_total_hydrographs
Components
Type Visibility Attributes Name Initial
integer, public :: hru = 5
1=total 2=recharge 3=surface 4=lateral 5= tile
integer, public :: hru_lte = 5
1=total 2=recharge 3=surface 4=lateral 5= tile
integer, public :: ru = 5
1=total 2=recharge 3=surface 4=lateral 5= tile
integer, public :: gwflow = 1
1=total
integer, public :: aqu = 2
1=return flow 2=deep perc
integer, public :: chan = 3
1=total 2=recharge 3=overbank
integer, public :: res = 2
1=total 2=recharge
integer, public :: recall = 1
1=total
integer, public :: exco = 2
1=surface 2=groundwater
integer, public :: dr = 2
1=surface 2=groundwater
integer, public :: pump = 1
1=total
integer, public :: outlet = 1
1=total
integer, public :: chandeg = 3
1=total 2=recharge 3=overbank
integer, public :: aqu2d = 2
1=return flow 3=deep perc
integer, public :: herd = 1
integer, public :: wro = 1
type, public :: routing_unit_data
Components
Type Visibility Attributes Name Initial
character(len=16), public :: name = ""
integer, public :: num_tot = 0
integer, public, dimension (:), allocatable :: num
points to subbasin element (sub_elem)
type, public :: routing_unit_elements
Components
Type Visibility Attributes Name Initial
character(len=16), public :: name = ""
integer, public :: obj = 1
object number
character(len=3), public :: obtyp = ""
object type- 1=hru, 2=hru_lte, 11=export coef, etc
integer, public :: obtypno = 0
2-number of hru_lte"s or 1st hru_lte command
real, public :: frac = 0
fraction of element in ru (expansion factor)
character(len=16), public :: dr_name = ""
name of dr in delratio.del
type(hyd_output), public :: dr
calculated (or input in delratio.del) dr's for element
type, public :: channel_surface_elements
Components
Type Visibility Attributes Name Initial
character(len=16), public :: name = ""
integer, public :: num = 0
number of elements
integer, public :: chnum = 0
channel number
integer, public :: resnum = 0
character(len=3), public, dimension(:), allocatable :: obtyp
object type- 1=hru, 2=hru_lte, 11=export coef, etc
integer, public, dimension(:), allocatable :: obtypno
2-number of hru_lte"s or 1st hru_lte command
real, public, dimension(:), allocatable :: wid
maxflood plain width for each element
real, public, dimension(:), allocatable :: dep
max flood depth for each element
real, public, dimension(:), allocatable :: flood_volmx
max flood volume for each landscape unit
type(hyd_output), public, dimension (:), allocatable :: hd
flood water for each element
type, public :: geomorphic_baseflow_channel_data
Components
Type Visibility Attributes Name Initial
real, public :: area = 0.
drainage area of the channel
real, public :: len = 0.
length of the channel
real, public :: len_left = 0.
fraction of chan length left when channel becomes non-contributing
real, public :: flo_fr = 0.
fraction of aquifer baseflow for each channel
type, public :: channel_aquifer_elements
Components
Type Visibility Attributes Name Initial
character(len=16), public :: name = ""
integer, public :: num_tot = 0
number of elements
integer, public, dimension(:), allocatable :: num
channel numbers
real, public :: len_tot = 0.
total length of channels in aquifer (km)
type(hyd_output), public :: hd
baseflow hydrograph for the aquifer
type(geomorphic_baseflow_channel_data), public, dimension(:), allocatable :: ch
type, public :: hyd_header
Components
Type Visibility Attributes Name Initial
character(len=17), public :: flo = "flo"
ha-m |volume of water
Read more…
character(len=15), public :: sed = "sed"
metric tons |sediment
Read more…
character(len=15), public :: orgn = "orgn"
kg N |organic N
Read more…
character(len=15), public :: sedp = "sedp"
kg P |organic P
Read more…
character(len=15), public :: no3 = "no3"
kg N |NO3-N
Read more…
character(len=15), public :: solp = "solp"
kg P |mineral (soluble P)
Read more…
character(len=15), public :: chla = "chla"
kg |chlorophyll-a
Read more…
character(len=15), public :: nh3 = "nh3"
kg N |NH3
Read more…
character(len=15), public :: no2 = "no2"
kg N |NO2
Read more…
character(len=15), public :: cbod = "cbod"
kg |carbonaceous biological oxygen demand
Read more…
character(len=15), public :: dox = "dox"
kg |dissolved oxygen
Read more…
character(len=15), public :: san = "san"
tons |detached sand
Read more…
character(len=15), public :: sil = "sil"
tons |detached silt
Read more…
character(len=15), public :: cla = "cla"
tons |detached clay
Read more…
character(len=15), public :: sag = "sag"
tons |detached small ag
Read more…
character(len=15), public :: lag = "lag"
tons |detached large ag
Read more…
character(len=15), public :: grv = "grv"
tons |gravel
Read more…
character(len=15), public :: temp = "null"
deg c |temperature
Read more…
type, public :: hyd_stor_header
Components
Type Visibility Attributes Name Initial
character(len=17), public :: flo_stor = "flo_stor"
m^3/s |water stored at the end of time period
Read more…
character(len=15), public :: sed_stor = "sed_stor"
metric tons |sediment stored at the end of time period
Read more…
character(len=15), public :: orgn_stor = "orgn_stor"
kg N |organic N stored at the end of time period
Read more…
character(len=15), public :: sedp_stor = "sedp_stor"
kg P |organic P stored at the end of time period
Read more…
character(len=15), public :: no3_stor = "no3_stor"
kg N |NO3-N stored at the end of time period
Read more…
character(len=15), public :: solp_stor = "solp_stor"
kg P |mineral (soluble P) stored at end of time period
Read more…
character(len=15), public :: chla_stor = "chla_stor"
kg |chlorophyll-a stored at end of time period
Read more…
character(len=15), public :: nh3_stor = "nh3_stor"
kg N |NH3-N (ammonium) stored at end of time period
Read more…
character(len=15), public :: no2_stor = "no2_stor"
kg N |NO2-N (nitrite) stored at end of time period
Read more…
character(len=15), public :: cbod_stor = "cbod_stor"
kg |carbonaceous biological oxygen demand at end of time period
Read more…
character(len=15), public :: dox_stor = "dox_stor"
kg |dissolved oxygen stored at end of time period
Read more…
character(len=15), public :: san_stor = "san_stor"
tons |detached sand stored at end of time period
Read more…
character(len=15), public :: sil_stor = "sil_stor"
tons |detached silt stored at end of time period
Read more…
character(len=15), public :: cla_stor = "cla_stor"
tons |detached clay stored at end of time period
Read more…
character(len=15), public :: sag_stor = "sag_stor"
tons |detached small ag stored at end of time period
Read more…
character(len=15), public :: lag_stor = "lag_stor"
tons |detached large ag stored at end of time period
Read more…
character(len=15), public :: grv_stor = "grv_stor"
tons |gravel stored at end of time period
Read more…
character(len=15), public :: temp_stor = "null"
deg c |water temperature
Read more…
type, public :: hyd_in_header
Components
Type Visibility Attributes Name Initial
character(len=15), public :: flo_in = "flo_in"
m^3/s |water in
Read more…
character(len=15), public :: sed_in = "sed_in"
metric tons |sediment in
Read more…
character(len=15), public :: orgn_in = "orgn_in"
kg N |organic N in
Read more…
character(len=15), public :: sedp_in = "sedp_in"
kg P |organic P in
Read more…
character(len=15), public :: no3_in = "no3_in"
kg N |NO3-N (nitrate) in
Read more…
character(len=15), public :: solp_in = "solp_in"
kg P |mineral (soluble P) in
Read more…
character(len=15), public :: chla_in = "chla_in"
kg |chlorophyll-a in
Read more…
character(len=15), public :: nh3_in = "nh3_in"
kg N |NH3-N (ammonium) in
Read more…
character(len=15), public :: no2_in = "no2_in"
kg N |NO2-N (nitrate) in
Read more…
character(len=15), public :: cbod_in = "cbod_in"
kg |carbonaceous biological oxygen demand in
Read more…
character(len=15), public :: dox_in = "dox_in"
kg |dissolved oxygen in
Read more…
character(len=15), public :: san_in = "san_in"
tons |detached sand in
Read more…
character(len=15), public :: sil_in = "sil_in"
tons |detached silt in
Read more…
character(len=15), public :: cla_in = "cla_in"
tons |detached clay in
Read more…
character(len=15), public :: sag_in = "sag_in"
tons |detached small ag in
Read more…
character(len=15), public :: lag_in = "lag_in"
tons |detached large ag in
Read more…
character(len=15), public :: grv_in = "grv_in"
tons |gravel in
Read more…
character(len=15), public :: temp_in = "null"
deg c |temperature in
Read more…
type, public :: hyd_out_header
Components
Type Visibility Attributes Name Initial
character(len=15), public :: flo_out = "flo_out"
m^3/s |water out
Read more…
character(len=15), public :: sed_out = "sed_out"
metric tons |sediment out
Read more…
character(len=15), public :: orgn_out = "orgn_out"
kg N |organic N out
Read more…
character(len=15), public :: sedp_out = "sedp_out"
kg P |organic P out
Read more…
character(len=15), public :: no3_out = "no3_out"
kg N |NO3-N out
Read more…
character(len=15), public :: solp_out = "solp_out"
kg P |mineral (soluble P) out
Read more…
character(len=15), public :: chla_out = "chla_out"
kg |chlorophyll-a out
Read more…
character(len=15), public :: nh3_out = "nh3_out"
kg N |NH3-N (ammonium) out
Read more…
character(len=15), public :: no2_out = "no2_out"
kg N |NO2-N (nitrite) out
Read more…
character(len=15), public :: cbod_out = "cbod_out"
kg |carbonaceous biological oxygen demand out
Read more…
character(len=15), public :: dox_out = "dox_out"
kg |dissolved oxygen out
Read more…
character(len=15), public :: san_out = "san_out"
tons |detached sand out
Read more…
character(len=15), public :: sil_out = "sil_out"
tons |detached silt out
Read more…
character(len=15), public :: cla_out = "cla_out"
tons |detached clay out
Read more…
character(len=15), public :: sag_out = "sag_out"
tons |detached small ag out
Read more…
character(len=15), public :: lag_out = "lag_out"
tons |detached large ag out
Read more…
character(len=15), public :: grv_out = "grv_out"
tons |gravel out
Read more…
character(len=15), public :: temp_out = "null"
deg c |temperature out
Read more…
type, public :: hyd_inout_header
Components
Type Visibility Attributes Name Initial
character(len=15), public :: flo_in = "flo_in"
m^3/s |water in
Read more…
character(len=15), public :: flo_out = "flo_out"
m^3/s |water out
Read more…
character(len=15), public :: sed_in = "sed_in"
metric tons |sediment in
Read more…
character(len=15), public :: sed_out = "sed_out"
metric tons |sediment out
Read more…
character(len=15), public :: orgn_in = "orgn_in"
kg N |organic N in
Read more…
character(len=15), public :: orgn_out = "orgn_out"
kg N |organic N out
Read more…
character(len=15), public :: sedp_in = "sedp_in"
kg P |organic P in
Read more…
character(len=15), public :: sedp_out = "sedp_out"
kg P |organic P out
Read more…
character(len=15), public :: no3_in = "no3_in"
kg N |NO3-N (nitrate) in
Read more…
character(len=15), public :: no3_out = "no3_out"
kg N |NO3-N out
Read more…
character(len=15), public :: solp_in = "solp_in"
kg P |mineral (soluble P) in
Read more…
character(len=15), public :: solp_out = "solp_out"
kg P |mineral (soluble P) out
Read more…
character(len=15), public :: chla_in = "chla_in"
kg |chlorophyll-a in
Read more…
character(len=15), public :: chla_out = "chla_out"
kg |chlorophyll-a out
Read more…
character(len=15), public :: nh3_in = "nh3_in"
kg N |NH3-N (ammonium) in
Read more…
character(len=15), public :: nh3_out = "nh3_out"
kg N |NH3-N (ammonium) out
Read more…
character(len=15), public :: no2_in = "no2_in"
kg N |NO2-N (nitrate) in
Read more…
character(len=15), public :: no2_out = "no2_out"
kg N |NO2-N (nitrite) out
Read more…
character(len=15), public :: cbod_in = "cbod_in"
kg |carbonaceous biological oxygen demand in
Read more…
character(len=15), public :: cbod_out = "cbod_out"
kg |carbonaceous biological oxygen demand out
Read more…
character(len=15), public :: dox_in = "dox_in"
kg |dissolved oxygen in
Read more…
character(len=15), public :: dox_out = "dox_out"
kg |dissolved oxygen out
Read more…
type, public :: wtmp_out_header
Components
Type Visibility Attributes Name Initial
character(len=15), public :: water_temp = "water_temp"
deg c |temperature
Read more…
type, public :: sed_hyd_header
Components
Type Visibility Attributes Name Initial
character(len=15), public :: flo_in = "flo_in"
m^3/s |volume of water
Read more…
character(len=15), public :: flo_out = "flo_out"
m^3/s |volume of water
Read more…
character(len=15), public :: sed_in = "sed_in"
metric tons |sediment
Read more…
character(len=15), public :: sed_out = "sed_out"
metric tons |sediment
Read more…
character(len=15), public :: orgn_in = "orgn_in"
kg N |organic N
Read more…
character(len=15), public :: orgn_out = "orgn_out"
kg N |organic N
Read more…
character(len=15), public :: sedp_in = "sedp_in"
kg P |organic P
Read more…
character(len=15), public :: sedp_out = "sedp_out"
kg P |organic P
Read more…
character(len=15), public :: no3_in = "no3_in"
kg N |NO3-N
Read more…
character(len=15), public :: no3_out = "no3_out"
kg N |NO3-N
Read more…
character(len=15), public :: solp_in = "solp_in"
kg P |mineral (soluble P)
Read more…
character(len=15), public :: solp_out = "solp_out"
kg P |mineral (soluble P)
Read more…
character(len=15), public :: chla_in = "chla_in"
kg |chlorophyll-a
Read more…
character(len=15), public :: chla_out = "chla_out"
kg |chlorophyll-a
Read more…
character(len=15), public :: nh3_in = "nh3_in"
kg N |NH3
Read more…
character(len=15), public :: nh3_out = "nh3_out"
kg N |NH3
Read more…
character(len=15), public :: no2_in = "no2_in"
kg N |NO2
Read more…
character(len=15), public :: no2_out = "no2_out"
kg N |NO2
Read more…
character(len=15), public :: cbod_in = "cbod_in"
kg |carbonaceous biological oxygen demand
Read more…
character(len=15), public :: cbod_out = "cbod_out"
kg |carbonaceous biological oxygen demand
Read more…
character(len=15), public :: dox_in = "dox_in"
kg |dissolved oxygen
Read more…
character(len=15), public :: dox_out = "dox_out"
kg |dissolved oxygen
Read more…
character(len=15), public :: temp_in = "temp_in"
deg c |temperature
Read more…
character(len=15), public :: temp_out = "temp_out"
deg c |temperature
Read more…
type, public :: sd_hyd_header_units
Components
Type Visibility Attributes Name Initial
character(len=15), public :: flo_in = "m^3/s"
avg daily m^3/s |volume of water
Read more…
character(len=15), public :: flo_out = "m^3/s"
avg daily m^3/s |volume of water
Read more…
character(len=15), public :: sed_in = "tons"
metric tons |sediment
Read more…
character(len=15), public :: sed_out = "tons"
metric tons |sediment
Read more…
character(len=15), public :: orgn_in = "kgN"
kg N |organic N
Read more…
character(len=15), public :: orgn_out = "kgN"
kg N |organic N
Read more…
character(len=15), public :: sedp_in = "kgP"
kg P |organic P
Read more…
character(len=15), public :: sedp_out = "kgP"
kg P |organic P
Read more…
character(len=15), public :: no3_in = "kgN"
kg N |NO3-N
Read more…
character(len=15), public :: no3_out = "kgN"
kg N |NO3-N
Read more…
character(len=15), public :: solp_in = "kgP"
kg P |mineral (soluble P)
Read more…
character(len=15), public :: solp_out = "kgP"
kg P |mineral (soluble P)
Read more…
character(len=15), public :: chla_in = "kg"
kg |chlorophyll-a
Read more…
character(len=15), public :: chla_out = "kg"
kg |chlorophyll-a
Read more…
character(len=15), public :: nh3_in = "kgN"
kg N |NH3
Read more…
character(len=15), public :: nh3_out = "kgN"
kg N |NH3
Read more…
character(len=15), public :: no2_in = "kgN"
kg N |NO2
Read more…
character(len=15), public :: no2_out = "kgN"
kg N |NO2
Read more…
character(len=15), public :: cbod_in = "kg"
kg |carbonaceous biological oxygen demand
Read more…
character(len=15), public :: cbod_out = "kg"
kg |carbonaceous biological oxygen demand
Read more…
character(len=15), public :: dox_in = "kg"
kg |dissolved oxygen
Read more…
character(len=15), public :: dox_out = "kg"
kg |dissolved oxygen
Read more…
character(len=15), public :: temp_in = "degc"
deg c |temperature
Read more…
character(len=15), public :: temp_out = "degc"
deg c |temperature
Read more…
type, public :: sol_header
Components
Type Visibility Attributes Name Initial
character(len=15), public :: layer1 = "st_mm_1"
mm H2O |plant name
Read more…
character(len=15), public :: layer2 = "st_mm_2"
mm H2O |amt of water stored in layer 2
Read more…
character(len=15), public :: layer3 = "st_mm_3"
mm H2O |amt of water stored in layer 3
Read more…
character(len=15), public :: layer4 = "st_mm_4"
mm H2O |amt of water stored in layer 4
Read more…
character(len=15), public :: layer5 = "st_mm_5"
mm H2O |amt of water stored in layer 5
Read more…
character(len=15), public :: layer6 = "st_mm_6"
mm H2O |amt of water stored in layer 6
Read more…
character(len=15), public :: layer7 = "st_mm_7"
mm H2O |amt of water stored in layer 7
Read more…
character(len=15), public :: layer8 = "st_mm_8"
mm H2O |amt of water stored in layer 8
Read more…
character(len=15), public :: layer9 = "st_mm_9"
mm H2O |amt of water stored in layer 9
Read more…
character(len=15), public :: layer10 = "st_mm_10"
mm H2O |amt of water stored in layer 10
Read more…
type, public :: plant_header
Components
Type Visibility Attributes Name Initial
character(len=17), public :: name = "name"
none |plant name
Read more…
character(len=15), public :: growing = "growing"
none |plant growing
Read more…
character(len=15), public :: dormant = "dormant"
none |plant dormant
Read more…
character(len=15), public :: lai = "lai"
none |leaf area index
Read more…
character(len=15), public :: can_hgt = "can_hgt"
m |canopy height
Read more…
character(len=15), public :: root_dep = "root_dep"
m |root depth
Read more…
character(len=15), public :: phuacc = "phuacc"
0-1 |accumulated heat units
Read more…
character(len=15), public :: tot_m = "tot_m"
kg/ha |total biomass
Read more…
character(len=15), public :: ab_gr_m = "ab_gr_m"
kg/ha |above ground biomass
Read more…
character(len=15), public :: leaf_m = "leaf_m"
kg/ha |leaf biomass
Read more…
character(len=15), public :: root_m = "root_m"
kg/ha |root biomass
Read more…
character(len=15), public :: stem_m = "stem_m"
kg/ha |stem biomass
Read more…
character(len=15), public :: seed_m = "seed_m"
kg/ha |seed biomass
Read more…
type, public :: flood_plain_header
Components
Type Visibility Attributes Name Initial
character(len=15), public :: inflo = "inflo"
m3 | inflow
Read more…
character(len=15), public :: outflo = "outflo"
m3 | outflow
Read more…
character(len=15), public :: dormant = "dormant"
m3 | evaporation
Read more…
character(len=15), public :: tl = "tl"
m3 | transmission losses
Read more…
character(len=15), public :: ev = "ev"
m3 | evaporation
Read more…
character(len=15), public :: ch_stor_init = " ch_stor_init"
m3 | channel storage at start of time step
Read more…
character(len=15), public :: ch_stor = "ch_stor"
m3 | channel storage at end of time step
Read more…
character(len=15), public :: fp_stor_init = " fp_stor_init"
m3 | flood plain storage at start of time step (all flood plain storage above wetland emergency volume)
Read more…
character(len=15), public :: fp_stor = "fp_stor"
m3 | flood plain storage at end of time step
Read more…
character(len=15), public :: tot_stor_init = "tot_stor_init"
m3 | total channel + wetland storage at start of time step
Read more…
character(len=15), public :: tot_stor = "tot_stor"
m3 | total channel + wetland storage at end of time step
Read more…
character(len=15), public :: wet_stor_init = "wet_stor_init"
m3 | wetland flood plain storage at start of time step
Read more…
character(len=15), public :: wet_stor = "wet_stor"
m3 | wetland flood plain storage at end of time step
Read more…
type, public :: ch_watbod_header
Components
Type Visibility Attributes Name Initial
character(len=6), public :: day = "jday"
character(len=6), public :: mo = "mon"
character(len=6), public :: day_mo = "day"
character(len=6), public :: yrc = "yr"
character(len=9), public :: isd = "unit"
character(len=9), public :: id = "gis_id"
character(len=15), public :: name = "name"
character(len=15), public :: area_ha = 'area'
character(len=15), public :: precip = 'precip'
character(len=15), public :: evap = 'evap'
character(len=15), public :: seep = 'seep'
type, public :: ch_watbod_header_units
Components
Type Visibility Attributes Name Initial
character(len=6), public :: day = ""
character(len=6), public :: mo = ""
character(len=6), public :: day_mo = ""
character(len=6), public :: yrc = ""
character(len=9), public :: isd = ""
character(len=9), public :: id = ""
character(len=15), public :: name = ""
character(len=15), public :: area_ha = 'ha'
character(len=15), public :: precip = 'm^3'
character(len=15), public :: evap = 'm^3'
character(len=15), public :: seep = 'm^3'
type, public :: ch_watbod_inoutheader
Components
Type Visibility Attributes Name Initial
character(len=6), public :: day = "jday"
character(len=6), public :: mo = "mon"
character(len=6), public :: day_mo = "day"
character(len=6), public :: yrc = "yr"
character(len=9), public :: id = "unit"
character(len=9), public :: gis_id = " gis_id"
character(len=15), public :: name = "name"
type, public :: ch_watbod_inoutheader_units
Components
Type Visibility Attributes Name Initial
character(len=6), public :: day = ""
character(len=6), public :: mo = ""
character(len=6), public :: day_mo = ""
character(len=6), public :: yrc = ""
character(len=9), public :: id = ""
character(len=9), public :: gis_id = ""
character(len=15), public :: name = ""
type, public :: hyd_header_units1
Components
Type Visibility Attributes Name Initial
character(len=15), public :: flo = "m^3/s"
m^3/s |volume of water
Read more…
character(len=15), public :: sed = "tons"
metric tons |sediment
Read more…
character(len=15), public :: orgn = "kgN"
kg N |organic N
Read more…
character(len=15), public :: sedp = "kgP"
kg P |organic P
Read more…
character(len=15), public :: no3 = "kgN"
kg N |NO3-N
Read more…
character(len=15), public :: solp = "kgP"
kg P |mineral (soluble P)
Read more…
character(len=15), public :: chla = "kg"
kg |chlorophyll-a
Read more…
character(len=15), public :: nh3 = "kgN"
kg N |NH3
Read more…
character(len=15), public :: no2 = "kgN"
kg N |NO2
Read more…
character(len=15), public :: cbod = "kg"
kg |carbonaceous biological oxygen demand
Read more…
character(len=15), public :: dox = "kg"
kg |dissolved oxygen
Read more…
character(len=15), public :: san = "tons"
tons |detached sand
Read more…
character(len=15), public :: sil = "tons"
tons |detached silt
Read more…
character(len=15), public :: cla = "tons"
tons |detached clay
Read more…
character(len=15), public :: sag = "tons"
tons |detached small ag
Read more…
character(len=15), public :: lag = "tons"
tons |detached large ag
Read more…
character(len=15), public :: grv = "tons"
tons |gravel
Read more…
character(len=15), public :: temp = ""
deg c |temperature
Read more…
type, public :: hyd_header_units3
Components
Type Visibility Attributes Name Initial
character(len=15), public :: flo = "m^3"
m^3 |volume of water
Read more…
character(len=15), public :: sed = "tons"
metric tons |sediment
Read more…
character(len=15), public :: orgn = "kgN"
kg N |organic N
Read more…
character(len=15), public :: sedp = "kgP"
kg P |organic P
Read more…
character(len=15), public :: no3 = "kgN"
kg N |NO3-N
Read more…
character(len=15), public :: solp = "kgP"
kg P |mineral (soluble P)
Read more…
character(len=15), public :: chla = "kg"
kg |chlorophyll-a
Read more…
character(len=15), public :: nh3 = "kgN"
kg N |NH3
Read more…
character(len=15), public :: no2 = "kgN"
kg N |NO2
Read more…
character(len=15), public :: cbod = "kg"
kg |carbonaceous biological oxygen demand
Read more…
character(len=15), public :: dox = "kg"
kg |dissolved oxygen
Read more…
character(len=15), public :: san = "tons"
tons |detached sand
Read more…
character(len=15), public :: sil = "tons"
tons |detached silt
Read more…
character(len=15), public :: cla = "tons"
tons |detached clay
Read more…
character(len=15), public :: sag = "tons"
tons |detached small ag
Read more…
character(len=15), public :: lag = "tons"
tons |detached large ag
Read more…
character(len=15), public :: grv = "tons"
tons |gravel
Read more…
character(len=15), public :: temp = ""
deg c |temperature
Read more…
type, public :: hydinout_header_units1
Components
Type Visibility Attributes Name Initial
character(len=15), public :: flo_in = " av daily m^3/s"
avg daily m^3/s |volume of water
Read more…
character(len=15), public :: flo_out = " av daily m^3/s"
avg daily m^3/s |volume of water
Read more…
character(len=15), public :: sed_in = "tons"
metric tons |sediment
Read more…
character(len=15), public :: sed_out = "tons"
metric tons |sediment
Read more…
character(len=15), public :: orgn_in = "kgN"
kg N |organic N
Read more…
character(len=15), public :: orgn_out = "kgN"
kg N |organic N
Read more…
character(len=15), public :: sedp_in = "kgP"
kg P |organic P
Read more…
character(len=15), public :: sedp_ouy = "kgP"
kg P |organic P
Read more…
character(len=15), public :: no3_in = "kgN"
kg N |NO3-N
Read more…
character(len=15), public :: no3_out = "kgN"
kg N |NO3-N
Read more…
character(len=15), public :: solp_in = "kgP"
kg P |mineral (soluble P)
Read more…
character(len=15), public :: solp_out = "kgP"
kg P |mineral (soluble P)
Read more…
character(len=15), public :: chla_in = "kg"
kg |chlorophyll-a
Read more…
character(len=15), public :: chla_out = "kg"
kg |chlorophyll-a
Read more…
character(len=15), public :: nh3_in = "kgN"
kg N |NH3
Read more…
character(len=15), public :: nh3_out = "kgN"
kg N |NH3
Read more…
character(len=15), public :: no2_in = "kgN"
kg N |NO2
Read more…
character(len=15), public :: no2_out = "kgN"
kg N |NO2
Read more…
character(len=15), public :: cbod_in = "kg"
kg |carbonaceous biological oxygen demand
Read more…
character(len=15), public :: cbod_out = "kg"
kg |carbonaceous biological oxygen demand
Read more…
character(len=15), public :: dox_in = "kg"
kg |dissolved oxygen
Read more…
character(len=15), public :: dox_out = "kg"
kg |dissolved oxygen
Read more…
type, public :: wtmp_header_units
Components
Type Visibility Attributes Name Initial
character(len=15), public :: wtmp = "degc"
deg c |temperature
Read more…
type, public :: hyd_header_units
pts (point source)/deposition/ru (routing_unit) files output uses this units header
Components
Type Visibility Attributes Name Initial
character(len=11), public :: day = ""
character(len=12), public :: mo = ""
character(len=12), public :: day_mo = ""
character(len=13), public :: yrc = ""
character(len=12), public :: name = ""
character(len=6), public :: otype = ""
character(len=17), public :: flo = "m^3/s"
m^3/s |volume of water
Read more…
character(len=15), public :: sed = "tons"
metric tons |sediment
Read more…
character(len=15), public :: orgn = "kgN"
kg N |organic N
Read more…
character(len=15), public :: sedp = "kgP"
kg P |organic P
Read more…
character(len=15), public :: no3 = "kgN"
kg N |NO3-N
Read more…
character(len=15), public :: solp = "kgP"
kg P |mineral (soluble P)
Read more…
character(len=15), public :: chla = "kg"
kg |chlorophyll-a
Read more…
character(len=15), public :: nh3 = "kgN"
kg N |NH3
Read more…
character(len=15), public :: no2 = "kgN"
kg N |NO2
Read more…
character(len=15), public :: cbod = "kg"
kg |carbonaceous biological oxygen demand
Read more…
character(len=15), public :: dox = "kg"
kg |dissolved oxygen
Read more…
character(len=15), public :: san = "tons"
tons |detached sand
Read more…
character(len=15), public :: sil = "tons"
tons |detached silt
Read more…
character(len=15), public :: cla = "tons"
tons |detached clay
Read more…
character(len=15), public :: sag = "tons"
tons |detached small ag
Read more…
character(len=15), public :: lag = "tons"
tons |detached large ag
Read more…
character(len=15), public :: grv = "tons"
tons |gravel
Read more…
character(len=15), public :: temp = "degc"
deg c |temperature
Read more…
type, public :: hyd_header_units2
hydin/hydout files uses this units header
Components
Type Visibility Attributes Name Initial
character(len=11), public :: day = ""
character(len=12), public :: mo = ""
character(len=12), public :: day_mo = ""
character(len=13), public :: yrc = ""
character(len=12), public :: name = ""
character(len=6), public :: otype = ""
character(len=13), public :: iotyp = ""
character(len=9), public :: iotypno = ""
character(len=8), public :: hydio = ""
character(len=8), public :: objno = ""
character(len=17), public :: flo = "m^3/s"
m^3/s |volume of water
Read more…
character(len=15), public :: sed = "tons"
metric tons |sediment
Read more…
character(len=15), public :: orgn = "kgN"
kg N |organic N
Read more…
character(len=15), public :: sedp = "kgP"
kg P |organic P
Read more…
character(len=15), public :: no3 = "kgN"
kg N |NO3-N
Read more…
character(len=15), public :: solp = "kgP"
kg P |mineral (soluble P)
Read more…
character(len=15), public :: chla = "kg"
kg |chlorophyll-a
Read more…
character(len=15), public :: nh3 = "kgN"
kg N |NH3
Read more…
character(len=15), public :: no2 = "kgN"
kg N |NO2
Read more…
character(len=15), public :: cbod = "kg"
kg |carbonaceous biological oxygen demand
Read more…
character(len=15), public :: dox = "kg"
kg |dissolved oxygen
Read more…
character(len=15), public :: san = "tons"
tons |detached sand
Read more…
character(len=15), public :: sil = "tons"
tons |detached silt
Read more…
character(len=15), public :: cla = "tons"
tons |detached clay
Read more…
character(len=15), public :: sag = "tons"
tons |detached small ag
Read more…
character(len=15), public :: lag = "tons"
tons |detached large ag
Read more…
character(len=15), public :: grv = "tons"
tons |gravel
Read more…
character(len=15), public :: temp = "degc"
deg c |temperature
Read more…
type, public :: hyd_header_time
Components
Type Visibility Attributes Name Initial
character(len=11), public :: day = "jday"
character(len=12), public :: mo = "mon"
character(len=12), public :: day_mo = "day"
character(len=13), public :: yrc = "yr"
character(len=12), public :: name = "name"
character(len=6), public :: otype = "type"
type, public :: rec_header_time
Components
Type Visibility Attributes Name Initial
character(len=11), public :: day = "jday"
character(len=12), public :: mo = "mon"
character(len=12), public :: day_mo = "day"
character(len=13), public :: yrc = "yr"
character(len=12), public :: name = "name"
character(len=6), public :: blank = ""
type, public :: hyd_header_obj
Components
Type Visibility Attributes Name Initial
character(len=13), public :: iotyp = "objtyp"
character(len=9), public :: iotypno = "typ_no "
character(len=8), public :: hydio = "hyd_typ "
character(len=8), public :: objno = "fraction"
type, public :: output_flow_duration_header
Components
Type Visibility Attributes Name Initial
character(len=11), public :: obtyp = "ob_typ"
character(len=12), public :: props = "props"
character(len=12), public :: area = "area_ha "
character(len=12), public :: f_idx = "flash_idx "
character(len=13), public :: mean = "mean "
character(len=11), public :: max = "max "
character(len=18), public :: p01 = "p.1 "
character(len=13), public :: p05 = "p.5 "
character(len=19), public :: p1 = "p1 "
character(len=15), public :: p2 = "p2 "
character(len=15), public :: p3 = "p3 "
character(len=15), public :: p5 = "p5 "
character(len=15), public :: p10 = "p10 "
character(len=15), public :: p15 = "p15 "
character(len=15), public :: p20 = "p20 "
character(len=15), public :: p25 = "p25 "
character(len=15), public :: p30 = "p30 "
character(len=15), public :: p35 = "p35 "
character(len=15), public :: p40 = "p40 "
character(len=15), public :: p45 = "p45 "
character(len=15), public :: p50 = "p50 "
character(len=15), public :: p55 = "p55 "
character(len=15), public :: p60 = "p60 "
character(len=15), public :: p65 = "p65 "
character(len=15), public :: p70 = "p70 "
character(len=15), public :: p75 = "p75 "
character(len=15), public :: p80 = "p80 "
character(len=15), public :: p85 = "p85 "
character(len=15), public :: p90 = "p90 "
character(len=15), public :: p95 = "p95 "
character(len=15), public :: p97 = "p97 "
character(len=15), public :: p98 = "p98 "
character(len=15), public :: p99 = "p99 "
character(len=11), public :: min = "min "
type, public :: calibration_header
Components
Type Visibility Attributes Name Initial
character(len=16), public :: name = "name"
character(len=12), public :: ha = "ha"
character(len=12), public :: nbyr = "nbyr"
character(len=12), public :: prec = "precip"
character(len=16), public :: meas = "name"
character(len=12), public :: srr = "srr"
character(len=12), public :: lfr = "lfr"
character(len=12), public :: pcr = "pcr"
character(len=12), public :: etr = "etr"
character(len=12), public :: tfr = "tfr"
character(len=12), public :: sed = "sed"
character(len=12), public :: orgn = "orgn"
character(len=12), public :: orgp = "orgp"
character(len=12), public :: no3 = "no3"
character(len=12), public :: solp = "solp"
character(len=16), public :: aa = "name"
character(len=12), public :: srr_aa = "srr"
character(len=12), public :: lfr_aa = "lfr"
character(len=12), public :: pcr_aa = "pcr"
character(len=12), public :: etr_aa = "etr"
character(len=12), public :: tfr_aa = "tfr"
character(len=12), public :: sed_aa = "sed"
character(len=12), public :: orgn_aa = "orgn"
character(len=12), public :: orgp_aa = "orgp"
character(len=12), public :: no3_aa = "no3"
character(len=12), public :: solp_aa = "solp"
character(len=12), public :: cn_prm_aa = "cn"
character(len=12), public :: esco = "esco"
character(len=12), public :: lat_len = "lat_len"
character(len=12), public :: petco = "petco"
character(len=12), public :: slope = "slope"
character(len=12), public :: tconc = "tconc"
character(len=12), public :: etco = "etco"
character(len=12), public :: perco = "perco"
character(len=12), public :: revapc = "revapc"
character(len=12), public :: cn3_swf = " cn3_swf"
type, public :: calibration2_header
Components
Type Visibility Attributes Name Initial
character(len=16), public :: name = "name "
character(len=12), public :: dakm2 = "da_km2 "
character(len=12), public :: cn2 = "cn2 "
character(len=12), public :: tc = "tc_min "
character(len=12), public :: soildep = " soildep_mm "
character(len=12), public :: perco_co = "perco_co "
character(len=12), public :: slope = "slope_m/m "
character(len=12), public :: slopelen = "slplen_m "
character(len=12), public :: etco = "etco "
character(len=12), public :: sy = "sy_mm "
character(len=12), public :: abf = "abf "
character(len=12), public :: revapc = "revapc "
character(len=12), public :: percc = "percc "
character(len=12), public :: sw = "sw_frac "
character(len=12), public :: gw = "gw_mm "
character(len=12), public :: gwflow = "gwflow_mm "
character(len=12), public :: gwdeep = "gwdeep_mm "
character(len=12), public :: snow = "snow_mm "
character(len=12), public :: xlat = "xlat "
character(len=12), public :: itext = "itext "
character(len=12), public :: tropical = "tropical "
character(len=12), public :: igrow1 = "igrow1_jd "
character(len=12), public :: igrow2 = "igrow2_jd "
character(len=12), public :: plant = "plant "
character(len=12), public :: ipet = "ipet "
character(len=12), public :: irr = "irr "
character(len=12), public :: irrsrc = "irrsrc "
character(len=12), public :: tdrain = "tdrain_hr "
character(len=12), public :: uslek = "uslek "
character(len=12), public :: uslec = "uslec "
character(len=12), public :: uslep = "uslep "
character(len=12), public :: uslels = "uslels "
type, public :: calibration3_header
Components
Type Visibility Attributes Name Initial
character(len=16), public :: name = "name "
character(len=12), public :: chgtyp = "chg_typ "
character(len=12), public :: val = "val "
character(len=12), public :: conds = "conds "
character(len=12), public :: lyr1 = "lyr1 "
character(len=12), public :: lyr2 = "lyr2 "
character(len=12), public :: year1 = "year1 "
character(len=12), public :: year2 = "year2 "
character(len=12), public :: day1 = "day1 "
character(len=12), public :: day2 = "day2 "
character(len=12), public :: objtot = "obj_tot "
type, public :: output_checker_header
Components
Type Visibility Attributes Name Initial
character(len=16), public :: sname = ""
character(len=16), public :: hydgrp = ""
character(len=12), public :: zmx = "zmx"
character(len=12), public :: usle_k = "usle_k "
character(len=12), public :: sumfc = "sumfc "
character(len=12), public :: sumul = "sumul "
character(len=12), public :: usle_p = "usle_p "
character(len=12), public :: usle_ls = "usle_ls "
character(len=12), public :: esco = "esco "
character(len=12), public :: epco = "epco "
character(len=12), public :: cn3_swf = "cn3_swf "
character(len=12), public :: perco = "perco "
character(len=12), public :: latq_co = "latq_co "
character(len=12), public :: tiledrain = "tiledrain "
type, public :: output_checker_unit
Components
Type Visibility Attributes Name Initial
character(len=16), public :: sname = "sname"
character(len=16), public :: hydgrp = "hydgrp"
character(len=12), public :: zmx = "(mm) "
character(len=12), public :: usle_k = ""
character(len=12), public :: sumfc = "(mm) "
character(len=12), public :: sumul = "(mm) "
character(len=12), public :: usle_p = ""
character(len=12), public :: usle_ls = ""
character(len=12), public :: esco = ""
character(len=12), public :: epco = ""
character(len=12), public :: cn3_swf = ""
character(len=12), public :: perco = ""
character(len=12), public :: latq_co = ""
character(len=16), public :: tiledrain = "0=notile;1=tile;"
type, public :: hru_swift_header_base
Components
Type Visibility Attributes Name Initial
character(len=16), public :: sed = "sed "
metric tons |sediment
Read more…
character(len=16), public :: orgn = "orgn "
kg N |organic N
Read more…
character(len=16), public :: sedp = "sedp "
kg P |organic P
Read more…
character(len=16), public :: no3 = "no3 "
kg N |NO3-N
Read more…
character(len=16), public :: solp = "solp "
kg P |mineral (soluble P)
Read more…
character(len=16), public :: nh3 = "nh3 "
kg N |NH3
Read more…
character(len=16), public :: no2 = "no2 "
kg N |NO2
Read more…
type, public :: hru_swift_header_baseunit
Components
Type Visibility Attributes Name Initial
character(len=16), public :: unitsed = "tons "
metric tons |sediment
Read more…
character(len=16), public :: unitorgn = "kgN "
kg N |organic N
Read more…
character(len=16), public :: unitsedp = "kgP "
kg P |organic P
Read more…
character(len=16), public :: unitno3 = "kgN "
kg N |NO3-N
Read more…
character(len=16), public :: unitsolp = "kgP "
kg P |mineral (soluble P)
Read more…
character(len=16), public :: unitnh3 = "kgN "
kg N |NH3
Read more…
character(len=16), public :: unitno2 = "kgN "
kg N |NO2
Read more…
type, public :: hru_swift_header_base2
Components
Type Visibility Attributes Name Initial
character(len=17), public :: flo = "flo "
ha-m |volume of water
Read more…
type(hru_swift_header_base), public :: base
type, public :: hru_swift_header_baseunit2
Components
Type Visibility Attributes Name Initial
character(len=16), public :: unitflo = "m^3 "
m^3 |volume of water
Read more…
type(hru_swift_header_baseunit), public :: base
type, public :: hru_swift_header
Components
Type Visibility Attributes Name Initial
character(len=17), public :: hd_type(5) = ["total_flow", "percolation", "surface_runoff", "lateral_flow", "tile_flow"]
type(hru_swift_header_base), public :: exco
type(hru_swift_header_baseunit), public :: exco_unit
type(hru_swift_header_base2), public :: dr
type(hru_swift_header_baseunit2), public :: dr_unit
Functions
public function hydout_add(hyd1, hyd2) result(hyd3)
Arguments
Type Intent Optional Attributes Name
type(hyd_output), intent(in) :: hyd1
type(hyd_output), intent(in) :: hyd2
Return Value type(hyd_output)
Called by
public function hydout_subtract(hyd1, hyd2) result(hyd3)
Arguments
Type Intent Optional Attributes Name
type(hyd_output), intent(in) :: hyd1
type(hyd_output), intent(in) :: hyd2
Return Value type(hyd_output)
Called by
public function hydout_mult(hyd1, hyd2) result(hyd3)
Arguments
Type Intent Optional Attributes Name
type(hyd_output), intent(in) :: hyd1
type(hyd_output), intent(in) :: hyd2
Return Value type(hyd_output)
Called by
public function hydout_add_const(const, hyd1) result(hyd2)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: const
type(hyd_output), intent(in) :: hyd1
Return Value type(hyd_output)
Called by
public function hydout_mult_const(const, hyd1) result(hyd2)
Arguments
Type Intent Optional Attributes Name
real, intent(in) :: const
type(hyd_output), intent(in) :: hyd1
Return Value type(hyd_output)
Called by
public function hydout_div_const(hyd1, const) result(hyd2)
Arguments
Type Intent Optional Attributes Name
type(hyd_output), intent(in) :: hyd1
real, intent(in) :: const
Return Value type(hyd_output)
Called by
public function hydout_div_conv(hyd1, hyd2) result(hyd3)
Arguments
Type Intent Optional Attributes Name
type(hyd_output), intent(in) :: hyd1
type(hyd_output), intent(in) :: hyd2
Return Value type(hyd_output)
Called by
Subroutines
public subroutine hyd_convert_conc_to_mass(hyd1)
Arguments
Type Intent Optional Attributes Name
type(hyd_output), intent(inout) :: hyd1
Called by
public subroutine res_convert_mass(hyd1, pvol)
Arguments
Type Intent Optional Attributes Name
type(hyd_output), intent(inout) :: hyd1
real, intent(in) :: pvol
Called by
public subroutine hyd_convert_mass_to_conc(hyd1)
Arguments
Type Intent Optional Attributes Name
type(hyd_output), intent(inout) :: hyd1
Called by
Call graph
operator (+) calls hydout_add
operator (ASTERISKASTERISK) calls hydout_mult
operator (.add.) calls hydout_add_const
operator (ASTERISK) calls hydout_mult_const
operator (SLASH) calls hydout_div_const
operator (SLASHSLASH) calls hydout_div_conv
sd_channel_control calls hyd_convert_conc_to_mass, hyd_convert_mass_to_conc
sd_channel_control2 calls hyd_convert_conc_to_mass, hyd_convert_mass_to_conc
sd_hydsed_init calls hyd_convert_conc_to_mass
wallo_treatment calls hyd_convert_conc_to_mass
res_initial calls res_convert_mass
wet_initial calls res_convert_mass
swift_output calls hyd_convert_mass_to_conc