output_ls_pesticide_module – TestDataProject
output_ls_pesticide_module Module
161 statements
Source File
Used by
Variables
Type Visibility Attributes Name Initial
type(pesticide_balance), public :: pestbz
type(object_pesticide_balance), public, dimension (:), allocatable :: hpestb_d
type(object_pesticide_balance), public, dimension (:), allocatable :: hpestb_m
type(object_pesticide_balance), public, dimension (:), allocatable :: hpestb_y
type(object_pesticide_balance), public, dimension (:), allocatable :: hpestb_a
type(object_pesticide_balance), public, dimension (:), allocatable :: rupestb_d
type(object_pesticide_balance), public, dimension (:), allocatable :: rupestb_m
type(object_pesticide_balance), public, dimension (:), allocatable :: rupestb_y
type(object_pesticide_balance), public, dimension (:), allocatable :: rupestb_a
type(object_pesticide_balance), public :: bpestb_d
type(object_pesticide_balance), public :: bpestb_m
type(object_pesticide_balance), public :: bpestb_y
type(object_pesticide_balance), public :: bpestb_a
type(output_pestbal_header), public :: pestb_hdr
Interfaces
public interface operator (+)
public function hruout_pestbal_add(hru1, hru2) result(hru3)
Arguments
Type Intent Optional Attributes Name
type(pesticide_balance), intent(in) :: hru1
type(pesticide_balance), intent(in) :: hru2
Return Value type(pesticide_balance)
Called by
public interface operator (*)
public function hruout_pestbal_mult(hru1, const) result(hru2)
Arguments
Type Intent Optional Attributes Name
type(pesticide_balance), intent(in) :: hru1
real, intent(in) :: const
Return Value type(pesticide_balance)
Called by
public interface operator (/)
public function hruout_pestbal_div(hru1, const) result(hru2)
Arguments
Type Intent Optional Attributes Name
type(pesticide_balance), intent(in) :: hru1
real, intent(in) :: const
Return Value type(pesticide_balance)
Called by
public interface operator (//)
public function hruout_pestbal_ave(hru1, const) result(hru2)
Arguments
Type Intent Optional Attributes Name
type(pesticide_balance), intent(in) :: hru1
real, intent(in) :: const
Return Value type(pesticide_balance)
Called by
Derived Types
type, public :: pesticide_balance
Components
Type Visibility Attributes Name Initial
real, public :: plant = 0.
|kg/ha |pesticide on plant foliage
Read more…
real, public :: soil = 0.
|kg/ha |pesticide in soil
Read more…
real, public :: sed = 0.
|kg/ha |pesticide loading from HRU sorbed onto sediment
Read more…
real, public :: surq = 0.
|kg/ha |amount of pesticide type lost in surface runoff in HRU
Read more…
real, public :: latq = 0.
|kg/ha |amount of pesticide in lateral flow in HRU
Read more…
real, public :: tileq = 0.
|kg/ha |amount of pesticide in tile flow in HRU
Read more…
real, public :: perc = 0.
|kg/ha |amount of pesticide leached past bottom of soil
Read more…
real, public :: apply_s = 0.
|kg/ha |amount of pesticide applied on soil
Read more…
real, public :: apply_f = 0.
|kg/ha |amount of pesticide applied on foliage
Read more…
real, public :: decay_s = 0.
|kg/ha |amount of pesticide decayed on soil
Read more…
real, public :: decay_f = 0.
|kg/ha |amount of pesticide decayed on foliage
Read more…
real, public :: wash = 0.
|kg/ha |amount of pesticide washed off from plant to soil
Read more…
real, public :: metab_s = 0.
|kg/ha |amount of pesticide metabolized from parent in soil
Read more…
real, public :: metab_f = 0.
|kg/ha |amount of pesticide metabolized from parent on foilage
Read more…
real, public :: pl_uptake = 0.
|kg/ha |amount of pesticide taken up by plants
Read more…
real, public :: in_plant = 0.
|kg/ha |pesticide in plant foliage
Read more…
type, public :: object_pesticide_balance
Components
Type Visibility Attributes Name Initial
type(pesticide_balance), public, dimension (:), allocatable :: pest
type, public :: output_pestbal_header
Components
Type Visibility Attributes Name Initial
character(len=5), public :: day = " jday"
character(len=6), public :: mo = "mon"
character(len=6), public :: day_mo = "day"
character(len=6), public :: yrc = "yr"
character(len=8), public :: isd = "unit"
character(len=8), public :: id = "gis_id"
character(len=16), public :: name = "name"
character(len=16), public :: pest = "pesticide"
character(len=15), public :: on_plant = " on_plant_kg/ha"
character(len=15), public :: soil = "soil_kg/ha "
character(len=15), public :: sed = "sed_kg/ha"
character(len=15), public :: surq = "surq_kg/ha"
character(len=15), public :: latq = "latq_kg/ha"
character(len=15), public :: tileq = "tileq_kg/ha"
character(len=15), public :: perc = "perc_kg/ha"
character(len=15), public :: apply_s = " apply_s_kg/ha "
character(len=15), public :: apply_f = " apply_f_kg/ha "
character(len=15), public :: decay_s = " decay_s_kg/ha "
character(len=15), public :: decay_f = " decay_f_kg/ha "
character(len=15), public :: wash = "wash_kg/ha"
character(len=15), public :: metab_s = " metab_s_kg/ha "
character(len=15), public :: metab_f = " metab_f_kg/ha "
character(len=15), public :: uptake = "uptake_kg/ha "
character(len=15), public :: in_plant = "in_plant_kg/ha "
Functions
public function hruout_pestbal_add(hru1, hru2) result(hru3)
Arguments
Type Intent Optional Attributes Name
type(pesticide_balance), intent(in) :: hru1
type(pesticide_balance), intent(in) :: hru2
Return Value type(pesticide_balance)
Called by
public function hruout_pestbal_mult(hru1, const) result(hru2)
Arguments
Type Intent Optional Attributes Name
type(pesticide_balance), intent(in) :: hru1
real, intent(in) :: const
Return Value type(pesticide_balance)
Called by
public function hruout_pestbal_div(hru1, const) result(hru2)
Arguments
Type Intent Optional Attributes Name
type(pesticide_balance), intent(in) :: hru1
real, intent(in) :: const
Return Value type(pesticide_balance)
Called by
public function hruout_pestbal_ave(hru1, const) result(hru2)
Arguments
Type Intent Optional Attributes Name
type(pesticide_balance), intent(in) :: hru1
real, intent(in) :: const
Return Value type(pesticide_balance)
Called by
Call graph
operator (+) calls hruout_pestbal_add
operator (ASTERISK) calls hruout_pestbal_mult
operator (SLASH) calls hruout_pestbal_div
operator (SLASHSLASH) calls hruout_pestbal_ave