output_ls_salt_module – TestDataProject
output_ls_salt_module Module
92 statements
Source File
Variables
Type Visibility Attributes Name Initial
type(salt_balance), public :: saltbz
type(object_salt_balance), public, dimension (:), allocatable :: hsaltb_d
type(object_salt_balance), public, dimension (:), allocatable :: hsaltb_m
type(object_salt_balance), public, dimension (:), allocatable :: hsaltb_y
type(object_salt_balance), public, dimension (:), allocatable :: hsaltb_a
type(object_salt_balance), public, dimension (:), allocatable :: rusaltb_d
type(object_salt_balance), public, dimension (:), allocatable :: rusaltb_m
type(object_salt_balance), public, dimension (:), allocatable :: rusaltb_y
type(object_salt_balance), public, dimension (:), allocatable :: rusaltb_a
type(object_salt_balance), public :: bsaltb_d
type(object_salt_balance), public :: bsaltb_m
type(object_salt_balance), public :: bsaltb_y
type(object_salt_balance), public :: bsaltb_a
type(output_saltbal_header), public :: saltb_hdr
Interfaces
public interface operator (+)
public function hruout_saltbal_add(hru1, hru2) result(hru3)
Arguments
Type Intent Optional Attributes Name
type(salt_balance), intent(in) :: hru1
type(salt_balance), intent(in) :: hru2
Return Value type(salt_balance)
Called by
public interface operator (/)
public function hruout_saltbal_div(hru1, const) result(hru2)
Arguments
Type Intent Optional Attributes Name
type(salt_balance), intent(in) :: hru1
real, intent(in) :: const
Return Value type(salt_balance)
Called by
public interface operator (//)
public function hruout_saltbal_ave(hru1, const) result(hru2)
Arguments
Type Intent Optional Attributes Name
type(salt_balance), intent(in) :: hru1
real, intent(in) :: const
Return Value type(salt_balance)
Called by
Derived Types
type, public :: salt_balance
Components
Type Visibility Attributes Name Initial
real, public :: plant = 0.
|kg/ha |salt in plant foliage
Read more…
real, public :: soil = 0.
|kg/ha |salt in soil
Read more…
real, public :: surq = 0.
|kg/ha |amount of pesticide type lost in surface runoff in HRU
Read more…
real, public :: latq = 0.
|kg/ha |amount of pesticide in lateral flow in HRU
Read more…
real, public :: tileq = 0.
|kg/ha |amount of pesticide in tile flow in HRU
Read more…
real, public :: perc = 0.
|kg/ha |amount of pesticide leached past bottom of soil
Read more…
real, public :: irrig = 0.
|kg/ha |amount of pesticide applied on soil
Read more…
type, public :: object_salt_balance
Components
Type Visibility Attributes Name Initial
type(salt_balance), public, dimension (:), allocatable :: salt
type, public :: output_saltbal_header
Components
Type Visibility Attributes Name Initial
character(len=5), public :: day = " jday"
character(len=6), public :: mo = " mon"
character(len=6), public :: day_mo = " day"
character(len=6), public :: yrc = " yr"
character(len=8), public :: isd = " unit"
character(len=8), public :: id = " gis_id"
character(len=16), public :: name = " name "
character(len=16), public :: salt = " salt_ion "
character(len=13), public :: plant = " plant_kg/h "
character(len=13), public :: soil = " soil_kg/h"
character(len=13), public :: surq = " surq_kg/h "
character(len=13), public :: latq = " latq_kg/h "
character(len=13), public :: tileq = " tileq_kg/h "
character(len=13), public :: perc = " perc_kg/h "
character(len=16), public :: irrig = " irrig_kg/h"
Functions
public function hruout_saltbal_add(hru1, hru2) result(hru3)
Arguments
Type Intent Optional Attributes Name
type(salt_balance), intent(in) :: hru1
type(salt_balance), intent(in) :: hru2
Return Value type(salt_balance)
Called by
public function hruout_saltbal_div(hru1, const) result(hru2)
Arguments
Type Intent Optional Attributes Name
type(salt_balance), intent(in) :: hru1
real, intent(in) :: const
Return Value type(salt_balance)
Called by
public function hruout_saltbal_ave(hru1, const) result(hru2)
Arguments
Type Intent Optional Attributes Name
type(salt_balance), intent(in) :: hru1
real, intent(in) :: const
Return Value type(salt_balance)
Called by
Call graph
operator (+) calls hruout_saltbal_add
operator (SLASH) calls hruout_saltbal_div
operator (SLASHSLASH) calls hruout_saltbal_ave