output_ls_pathogen_module – TestDataProject
output_ls_pathogen_module Module
95 statements
Source File
Used by
Variables
Type Visibility Attributes Name Initial
type(pathogen_balance), public :: pathbz
type(object_pathogen_balance), public, dimension (:), allocatable :: hpath_bal
type(object_pathogen_balance), public, dimension (:), allocatable :: hpathb_m
type(object_pathogen_balance), public, dimension (:), allocatable :: hpathb_y
type(object_pathogen_balance), public, dimension (:), allocatable :: hpathb_a
type(object_pathogen_balance), public, dimension (:), allocatable :: rupathb_d
type(object_pathogen_balance), public, dimension (:), allocatable :: rupathb_m
type(object_pathogen_balance), public, dimension (:), allocatable :: rupathb_y
type(object_pathogen_balance), public, dimension (:), allocatable :: rupathb_a
type(object_pathogen_balance), public :: bpathb_d
type(object_pathogen_balance), public :: bpathb_m
type(object_pathogen_balance), public :: bpathb_y
type(object_pathogen_balance), public :: bpathb_a
type(output_pathbal_header), public :: pathb_hdr
Interfaces
public interface operator (+)
public function hruout_pathbal_add(hru1, hru2) result(hru3)
Arguments
Type Intent Optional Attributes Name
type(pathogen_balance), intent(in) :: hru1
type(pathogen_balance), intent(in) :: hru2
Return Value type(pathogen_balance)
Called by
public interface operator (/)
public function hruout_pathbal_div(hru1, const) result(hru2)
Arguments
Type Intent Optional Attributes Name
type(pathogen_balance), intent(in) :: hru1
real, intent(in) :: const
Return Value type(pathogen_balance)
Called by
public interface operator (//)
public function hruout_pathbal_ave(hru1, const) result(hru2)
Arguments
Type Intent Optional Attributes Name
type(pathogen_balance), intent(in) :: hru1
real, intent(in) :: const
Return Value type(pathogen_balance)
Called by
Derived Types
type, public :: pathogen_balance
Components
Type Visibility Attributes Name Initial
real, public :: plant = 0.
|kg/ha |pathogen on plant foliage
Read more…
real, public :: soil = 0.
|kg/ha |pathogen enrichment ratio
Read more…
real, public :: sed = 0.
|kg/ha |pathogen loading from HRU sorbed onto sediment
Read more…
real, public :: surq = 0.
|kg/ha |amount of pathogen type lost in surface runoff on current day in HRU
Read more…
real, public :: latq = 0.
|kg/ha |amount of pathogen in lateral flow in HRU for the day
Read more…
real, public :: perc1 = 0.
|kg/ha |amount of pathogen leached past first layer
Read more…
real, public :: apply_sol = 0.
|kg/ha |amount of pathogen applied to soil
Read more…
real, public :: apply_plt = 0.
|kg/ha |amount of pathogen applied to plant
Read more…
real, public :: regro = 0.
|kg/ha |amount of pathogen regrowth
Read more…
real, public :: die_off = 0.
|kg/ha |amount of pathogen die-off
Read more…
real, public :: wash = 0.
|kg/ha |amount of pathogen washed off from plant to soil
Read more…
type, public :: object_pathogen_balance
Components
Type Visibility Attributes Name Initial
type(pathogen_balance), public, dimension (:), allocatable :: path
type, public :: output_pathbal_header
Components
Type Visibility Attributes Name Initial
character(len=5), public :: day = " jday"
character(len=6), public :: mo = "mon"
character(len=6), public :: day_mo = "day"
character(len=6), public :: yrc = "yr"
character(len=8), public :: isd = "unit"
character(len=8), public :: id = "gis_id"
character(len=16), public :: name = "name"
character(len=14), public :: plant = "plant_kg/h"
character(len=12), public :: soil = "soil_kg/h"
character(len=12), public :: sed = "sed_kg/h"
character(len=12), public :: surq = "surq_kg/h"
character(len=12), public :: latq = "latq_kg/h"
character(len=12), public :: perc = "perc_kg/h"
character(len=12), public :: apply = " apply_kg/h"
character(len=12), public :: decay = " decay_kg/h"
Functions
public function hruout_pathbal_add(hru1, hru2) result(hru3)
Arguments
Type Intent Optional Attributes Name
type(pathogen_balance), intent(in) :: hru1
type(pathogen_balance), intent(in) :: hru2
Return Value type(pathogen_balance)
Called by
public function hruout_pathbal_div(hru1, const) result(hru2)
Arguments
Type Intent Optional Attributes Name
type(pathogen_balance), intent(in) :: hru1
real, intent(in) :: const
Return Value type(pathogen_balance)
Called by
public function hruout_pathbal_ave(hru1, const) result(hru2)
Arguments
Type Intent Optional Attributes Name
type(pathogen_balance), intent(in) :: hru1
real, intent(in) :: const
Return Value type(pathogen_balance)
Called by
Call graph
operator (+) calls hruout_pathbal_add
operator (SLASH) calls hruout_pathbal_div
operator (SLASHSLASH) calls hruout_pathbal_ave