water_body_module – test-src-project
water_body_module Module
68 statements
Source File
water body (reservoir, wetland, and channel) output not included in hyd_output object
routines for water body module
Used by
Variables
Type Visibility Attributes Name Initial
type(water_body), public :: wbodz
type(water_body), public, dimension(:), allocatable, target :: res_wat_d
type(water_body), public, dimension(:), allocatable :: res_wat_m
type(water_body), public, dimension(:), allocatable :: res_wat_y
type(water_body), public, dimension(:), allocatable :: res_wat_a
type(water_body), public, dimension(:), allocatable, target :: wet_wat_d
type(water_body), public, dimension(:), allocatable :: wet_wat_m
type(water_body), public, dimension(:), allocatable :: wet_wat_y
type(water_body), public, dimension(:), allocatable :: wet_wat_a
type(water_body), public, dimension(:), allocatable :: ch_wat_d
type(water_body), public, dimension(:), allocatable :: ch_wat_m
type(water_body), public, dimension(:), allocatable :: ch_wat_y
type(water_body), public, dimension(:), allocatable :: ch_wat_a
type(water_body), public :: bch_wat_d
type(water_body), public :: bch_wat_m
type(water_body), public :: bch_wat_y
type(water_body), public :: bch_wat_a
type(water_body), public :: bres_wat_d
type(water_body), public :: bres_wat_m
type(water_body), public :: bres_wat_y
type(water_body), public :: bres_wat_a
type(water_body), public, pointer :: wbody_wb
used for reservoir and wetlands
Interfaces
public interface operator (+)
public function watbod_add(wbod1, wbod2) result(wbod3)
Arguments
Type Intent Optional Attributes Name
type(water_body), intent(in) :: wbod1
type(water_body), intent(in) :: wbod2
Return Value type(water_body)
Called by
public interface operator (/)
public function watbod_div(wbod1, const) result(wbod2)
Arguments
Type Intent Optional Attributes Name
type(water_body), intent(in) :: wbod1
real, intent(in) :: const
Return Value type(water_body)
Called by
public interface operator (//)
public function watbod_ave(wbod1, const) result(wbod2)
Arguments
Type Intent Optional Attributes Name
type(water_body), intent(in) :: wbod1
real, intent(in) :: const
Return Value type(water_body)
Called by
Derived Types
type, public :: water_body
Components
Type Visibility Attributes Name Initial
real, public :: area_ha = 0.
ha |water body surface area
Read more…
real, public :: precip = 0.
m3 |precip on the water body
Read more…
real, public :: evap = 0.
m3 |evaporation from the water surface
Read more…
real, public :: seep = 0.
m3 |seepage from bottom of water body
Read more…
Functions
public function watbod_add(wbod1, wbod2) result(wbod3)
Arguments
Type Intent Optional Attributes Name
type(water_body), intent(in) :: wbod1
type(water_body), intent(in) :: wbod2
Return Value type(water_body)
Called by
public function watbod_div(wbod1, const) result(wbod2)
Arguments
Type Intent Optional Attributes Name
type(water_body), intent(in) :: wbod1
real, intent(in) :: const
Return Value type(water_body)
Called by
public function watbod_ave(wbod1, const) result(wbod2)
Arguments
Type Intent Optional Attributes Name
type(water_body), intent(in) :: wbod1
real, intent(in) :: const
Return Value type(water_body)
Called by
Call graph
operator (+) calls watbod_add
operator (SLASH) calls watbod_div
operator (SLASHSLASH) calls watbod_ave